### PR TITLE
Add Free Available Domains suffixes

### PR DESCRIPTION
**Pull request by freeavailabledomains**
We are free sub-domain provider and other users requested to add our domains into Public Suffix List.

### CODE REVIEW

**Comment by freeavailabledomains** [comment]
DNS entries added:

_psl.usa.cc.		3600	IN	TXT	"https://github.com/publicsuffix/list/pull/532"
_psl.nut.cc.		3600	IN	TXT	"https://github.com/publicsuffix/list/pull/532"
_psl.flu.cc.		3600	IN	TXT	"https://github.com/publicsuffix/list/pull/532"
_psl.igg.biz.		3600	IN	TXT	"https://github.com/publicsuffix/list/pull/532"

**Comment by patrakov** [comment]
I believe this is not right. The pull request effectively says "every subdomain of usa.cc has subsubdomains that belong to mutually distrusting third parties". While in fact this is only true for usa.cc itself, as well as nut.cc, flu.cc, and igg.biz.

**Comment by freeavailabledomains** [comment]
Changed.

**Comment by weppos** [comment]
No followup

**Pull request closed without merging**
