### PR TITLE
Add city.kharkov.ua

### PR DESCRIPTION
**Pull request by d1rOn**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====
The Kharkiv City Council (Ukraine)
Organization Website: 

Reason for PSL Inclusion
====
We want to use a Cloudflare on subdomain

DNS Verification via dig
=======
```
dig +short TXT _psl.city.kharkov.ua
"https://github.com/publicsuffix/list/pull/990"
```

make test
=========
Test passed

### CODE REVIEW

**Comment by dnsguru** [comment]
**Looks like the city name is misspelled in the comment within the patch**

Validated NS:
```
>nslookup -type=TXT _psl.city.kharkov.ua
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.city.kharkov.ua    text =

        "https://github.com/publicsuffix/list/pull/990"

```

**Comment by dnsguru** [comment]
Kharkiv or Kharkov    ?    (O or I?)

**Comment by d1rOn** [comment]
No, there are no errors.
Organization name with (I), but domain name with (O).

**Comment by dnsguru** [comment]
@d1rOn Did you mean you needed this for cookie horizons?  Can you explain what you mean by Cloudflare?  we have another similar request about cloudflare (#876) and want to understand the need

**Comment by d1rOn** [comment]
@dnsguru We want to use a Cloudflare as proxy on website dr.city.kharkov.ua. But we cant because of it does not accept our domain due to it is not root domain. We know that Cloudflare uses publicsuffix to determine root domains. And we decided to add a city.kharkov.ua to publicsuffix list for this reason.

**Comment by dnsguru** [comment]
@d1rOn thank you - are you referencing this :
[https://support.cloudflare.com/hc/en-us/articles/205359838-I-cannot-add-my-domain-to-Cloudflare-   (See Step 2)](https://support.cloudflare.com/hc/en-us/articles/205359838-I-cannot-add-my-domain-to-Cloudflare-)?

**Comment by d1rOn** [comment]
@dnsguru yes.

**Comment by dnsguru** [comment]
[Similar discussion thread re: Cloudflare](https://github.com/publicsuffix/list/pull/876#issuecomment-612147532)

**Comment by dnsguru** [comment]
We would need to see revised policies from .ua or the _txt record added for kharov.ua to add relevant record to DNS to proceeed ;  closing for now

**Pull request closed without merging**
