### PR TITLE
Knock Knock WHOIS There's (KKWT) wildcard entries for .blog

### PR DESCRIPTION
**Pull request by varlese**
Updated the public_suffix_list.dat file to include Knock Knock WHOIS There's (KKWT) wildcard entries for .blog subdomains available via WordPress.com.

* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [X] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://my.blog/

My name is Erica Varlese, I am the Policy and Compliance Officer at Knock Knock WHOIS There, the registry for .blog domains. 

Knock Knock WHOIS There, LLC is a subsidiary of Automattic, the parent company of WordPress.com and Jetpack. It was created in 2015 to manage the launch and development of the .blog gTLD.

Automattic has been working towards offering .blog domain names almost since its inception, in 2005. Its goal is to offer bloggers across the world a great new name space at a great price — whether they are WordPress users or not.

Reason for PSL Inclusion
====

We've partnered with WordPress.com to offer a number of subdomains on .blog domains to WordPress.com users. We want to include wildcards of these subdomains in the PSL so that customers using these addresses can be included in search ranking listings, such as Amazon Alexa. 

DNS Verification via dig
=======

[Pending]

make test
=========

Tests were run and passed.

### CODE REVIEW

**Comment by dnsguru** [comment]
@varlese please confirm that these are to be treated within the #private section and you're certain about these being correctly configured.

**Comment by varlese** [comment]
Thanks @dnsguru! Yes, I can confirm everything should be in the #private section and it's configured correctly.

We're just waiting to add the DNS records if you still need those for the verification.

**Comment by sleevi** [comment]
@dnsguru No need to confirm you know them. We treat everyone the same: based on DNS ;)

@varlese Can you include a few sample domains? It’s unclear to me if the format is well-formed for what you want.

I noticed you said you wanted to ensure better ranking on Alexa. However, the public suffix list’s primary purpose is to ensure the separation of cookies. It would help to understand if this is a necessary addition if you could describe a little bit more about the control of content users on your service have. If it really is limited, and the sole purpose is ranking, then this seems like it would fit under the same policy as applicants who come wanting to raise Let’s Encrypt rate limits; which is to say contacting Amazon Alexa directly.

Hopefully, the explanation and examples won’t slow things down, since it sounds like DNS is still propagating, and that’s required to merge this :)

**Comment by varlese** [comment]
Apologies for the delay, @sleevi. After your comment, we had some more discussions internally and decided that we won't be making these changes at the moment. Thanks so much for your clarification.

**Pull request closed without merging**
