### PR TITLE
Add Adobe Developer Platform domains `adobeio-static.net` and `adobeioruntime.net`

### PR DESCRIPTION
**Pull request by purplecabbage**
Adds domain names for Adobe Developer Platform

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://adobe.com/ https://developer.adobe.com

I am an engineer for Adobe Developer Platform.  We allow customers to build application extensions which are isolated by subdomains.

Reason for PSL Inclusion
====

Our main goal with this submission is Cookie Security, as different customers will have control over different subdomains of the service.

Domain registrations are valid for 3 years.

Number of users this request is being made to serve:
Estimate: 1000

DNS Verification via dig
=======
```bash
➜ dig +short TXT _psl.adobeio-static.net
"https://github.com/publicsuffix/list/pull/1633"
➜ dig +short TXT _psl.adobeioruntime.net
"https://github.com/publicsuffix/list/pull/1633"
```

Results of Syntax Checker (`make test`)
=========

test-syntax passes
test-rules is failing with:
```
Can't exec "autopoint": No such file or directory at /opt/homebrew/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 293.
autoreconf: error: autopoint failed with exit status: 2
```
This failed without changes ...

### CODE REVIEW

**Comment by purplecabbage** [comment]
This should be ready to go now, thanks in advance

**Comment by dnsguru** [comment]
Thanks for being so responsive.  There are a number of requests ahead of
this, and the volunteer pool (currently just me) are FCFS on requests to
the best of our ability on processing them, so it will be a little while.

**Comment by purplecabbage** [comment]
Any update here? Anything I can do to help?

**Comment by dnsguru** [comment]
The obstacle is a combination of there being reviews ahead of yours, a
growing queue and then more crucially my darn bank wanting me to pay my
mortgage - they seem to GZF about volunteer work.    it keeps me in #dayjob
mode.  This is a volunteer based project.

**Review by dnsguru — APPROVED** [review]
* DNS Validates
* Guidelines followed
* Tests Pass
* No Conflict with base

APPROVED

**Comment by purplecabbage** [comment]
Thanks @dnsguru !

**Pull request merged**
