### PR TITLE
add 2 more domains for SinaAppEngine

### PR DESCRIPTION
**Pull request by C0reFast**
The SinaAppEngine enabled 2 more domains for it's PaaS service

### CODE REVIEW

**Comment by sleevi** [comment]
Please sort your domains, as per the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) , and indicate how these can be validated (e.g. DNS TXT records)

**Comment by C0reFast** [comment]
hello @sleevi , the domains have being sorted and the DNS TXT Record were added to these domains, please check the validation.

**Comment by weppos** [comment]
@C0reFast I was able to validate the TXT records.

```
➜  ~ dig TXT _psl.1kapp.com +short
"https://github.com/publicsuffix/list/pull/121"
➜  ~ dig TXT _psl.appchizi.com +short
"https://github.com/publicsuffix/list/pull/121"
➜  ~ dig TXT _psl.applinzi.com +short
"https://github.com/publicsuffix/list/pull/121"
```

If you can rebase against master, I'll go ahead and merge your PR.

**Comment by C0reFast** [comment]
@weppos it's ok now :smile:

**Pull request merged**
