### PR TITLE
Add resin.io device domains as public suffixes

### PR DESCRIPTION
**Pull request by pimterry**
We expose our users' device-hosted web services at `<device id>.resindevice.io` and in our staging environment at `<device id>.devices.resinstaging.io`. We'd like to ensure these devices are isolated from one another in browsers.

~~I'm organising authentication for these domains at the moment, I'll update here shortly once we've got the `_ps1` TXT records set up.~~ `_ps1` TXT records for these domains are now live.

### CODE REVIEW

**Comment by pimterry** [comment]
@sleevi This is now authenticated:

```bash
> dig TXT _ps1.resindevice.io +short                    
"https://github.com/publicsuffix/list/pull/499"

> dig TXT _ps1.devices.resinstaging.io +short       
"https://github.com/publicsuffix/list/pull/499"
```

Let me know if there's anything else I need to do.

**Comment by brownjohnf** [comment]
What's the status on this? We'd like to remove the validation records from resin's DNS.

**Comment by brownjohnf** [comment]
Sounds good. I'll consider my ticket closed then :-)

**Comment by sleevi** [comment]
I'm unable to find a record at `_psl.resindevice.com`

Can you please ensure it complies with [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

It looks like you may have done `_ps1` rather than `_psl`, but we require `_psl` for the reason @weppos mentioned

**Comment by pimterry** [comment]
Damn, you're completely right - we've done `_ps1` in both cases. I'll get that updated now.

**Comment by pimterry** [comment]
@sleevi these are now updated. I see:

```bash
> dig TXT _psl.resindevice.io +short
"https://github.com/publicsuffix/list/pull/499"

> dig TXT _psl.devices.resinstaging.io +short
"https://github.com/publicsuffix/list/pull/499"
```

**Comment by pimterry** [comment]
Any updates on this? Let me know if there's anything I can do to help.

**Comment by pimterry** [comment]
Hi, it's been nearly three months, and we're still waiting on this! I think it's ready to go now, I'd love to get this merged @weppos @sleevi. Let me know if there's anything I can do to help.

**Comment by weppos** [comment]
@pimterry Please remember to preserve the DNS records after the merge.

**Comment by pimterry** [comment]
Amazing, thank you!

**Pull request merged**
