### PR TITLE
Adding Oddle.me to the domain list

### PR DESCRIPTION
**Pull request by vyvy1988**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

**### Description of Organization**
Oddle is a SaaS platform that helps restaurants go online. Oddle provides restaurants with their own online ordering system which enables them to receive and manage orders from their customers. Oddle currently serves over 3,000 restaurants globally.

**### Reason for PSL Inclusion**
Restaurants using our platform are able to build their own e-commerce webstore. They will be given their own oddle.me subdomain, removing the need for them to buy a domain to go online. For example, the url for a restaurant A would be https://restauranta.oddle.me. Some examples of our actual customers include https://genkisushi.oddle.me/, https://penangplace.oddle.me/ and https://taicheong.oddle.me/. We would like to include oddle.me domain for improved cookie security. Do note that all subdomains are covered by our wildcard SSL certs.

**### DNS Verification via dig**
dig +short TXT _psl.oddle.me
"https://github.com/publicsuffix/list/pull/1246"

**### Run Syntax Checker (make test)**
All tests are passed

### CODE REVIEW

**Comment by dnsguru** [comment]
Noticed missing assertion of 2+ years of registration; this caused more time to be invested in verifying the registration period, and the registration period ends in October of this year.  As it stands, this would not pass.

```
Registry Expiry Date: 2021-10-18T10:27:49Z
```

**Comment by vyvy1988** [comment]
Thank you @dnsguru, we're working on extending the period, will get back to you asap. Sorry for the inconvenience caused

**Comment by vyvy1988** [comment]
We've updated the registration period, please help to check @dnsguru. Thank you very much.
`Registry Expiry Date: 2026-10-18T10:27:49Z
`

**Review by dnsguru — CHANGES_REQUESTED** [review]
This must be added to the section below the # PRIVATE  section.  Please revise PR to locate this lower in the file, alphabetically within the PRIVATE section within this file.

**Comment by vyvy1988** [comment]
Thank you @dnsguru, I've moved it to the private section. Please let me know if you have any further concerns.

**Comment by dnsguru** [comment]
@vyvy1988 can you please re-factor and locate the change alphabetically in the PRIVATE section, not the ICANN section?

**Comment by vyvy1988** [comment]
Hi @dnsguru , the private section begins at line 10642 and I put my entries on lines 12873-12875. Please let me know if that's not correct, I will fix then. Thank you sir.

**Comment by vyvy1988** [comment]
Hi @dnsguru , can you help to check my PR please? Thank you po

**Comment by dnsguru** [comment]
@vyvy1988  please rebase and re-add the change - it is unusable as-is

**Comment by vyvy1988** [comment]
@dnsguru I've rebased and re-added the change, please help to check. Thank you Jothan.

**Comment by vyvy1988** [comment]
@dnsguru Can you help to review this please?

**Comment by dnsguru** [comment]
Please review #1245  - we have been receinving a higher than typical number of requests very similar to yours where the requestor seeks to work around rate limits through being included in the PSL.  

Typically our colleagues from Facebook who are helping triage some of the increased load take the time to walk requests like this through the implications of the affectation of listing the raw domain if subdomaining is the objective outcome....

The challenge is that a request could be a problem for the root domain.  and it is important that you carefully identify that this request is not going to break anything unintentionally, such as wildcard cert renewals or cookie behavior on root domain, as we have no control over the timing on when changes are added or rolled back (this is explained in the guidelines [LINK](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion). better with graphics)

If after reading and understanding the potentially unexpected breakage outcome, you decide that you still want to proceed - you'd have to accept that it would probably take at least 45=60 days to process a rollback under the current workload, and we have no control over the timing of when that change to the PSL gets subsequently picked up in browsers etc.  

Just reply with ... I understand, go for it 

_an aside: We're volunteers and I don't like getting nudges to my personal email address.  This one is taking longer because of the iterations as well as the need to clarify as above - we are experiencing heavier than typical flow of requests due to a change in IOS 14.5, so the current workload competes for the team's available time to volunteer cycles._

**Comment by vyvy1988** [comment]
@dnsguru Hi Mr Jothan, first of all I'm really sorry for bothering you via personal email, that's really unprofessional, we wont do that again.

About the potentially unexpected breakage, we're aware of it and we understand of the risk. Please help to go for it and merge our pull request.
Thank you very much for your help and I apologise for any inconvenience caused.

**Comment by dnsguru** [comment]
Is this related to the issue in #1245 ?  (yes / no)

**Comment by vyvy1988** [comment]
@dnsguru Thank you Jothan.
Yes it is related to the issue in https://github.com/publicsuffix/list/issues/1245, pls help to process. Thank you Jothan.

**Comment by dnsguru** [comment]
all requests related to FB/IOS are wontfix for now. Maybe/maybe not forever, we are looking at the overall issue to see how well it is resolved while respecting the integrity of the privacy or rate limits that are in place.

  It is regrettable that Facebook directed people to the PSL for a cure - that should not have happened, but the misleading texts have been updated to help not set inappropriate expectations for their customers that PSL listing fixes things.

By now, a facebook employee should have joined this comment stream to engage with you here, they may be doing so via email or other means directly.

Any pressures on this, friendly nudges, pleading etc are best directed to your account manager or support teams at Facebook.

**Comment by n8schloss** [comment]
Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737  

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift. 

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
excellent @n8schloss closing this, reference this pr# should a new one be requested

**Pull request closed without merging**
