### PR TITLE
add dnshome.de

### PR DESCRIPTION
**Pull request by blackm**
Please add dnshome.de to the list.

dnshome.de is a German dDNS service. Before creating this issue I contacted the owner of the domain dnshome.de and asked for this approval to be added to the list. He has given the approval

Thanks :-)

### CODE REVIEW

**Comment by Bodenhaltung** [comment]
`dig +short psl.dnshome.de TXT
"https://github.com/publicsuffix/list/pull/139"`

**Comment by sleevi** [comment]
Please rebase this PR and update the validation domain to `_psl` (note the leading underscore), as per the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

**Comment by blackm** [comment]
I think I messed it up and created this conflict by deleting my fork. :-1: 

@Bodenhaltung can you try? I think we need to go through a new PR
@sleevi maybe this will not delay things when we reference this new PR here :-/

**Comment by Bodenhaltung** [comment]
New PR: #212.

**Comment by sleevi** [comment]
Closing this in favor of #212

**Pull request closed without merging**
