### PR TITLE
Remove stackspace.space from PSL

### PR DESCRIPTION
**Pull request by dbkegley**
We would like to remove our domain's entry from the PSL.

### CODE REVIEW

**Comment by dbkegley** [comment]
```
$dig TXT +short _psl.stackspace.space
"https://github.com/publicsuffix/list/pull/691"
```

**Comment by weppos** [comment]
Related to https://github.com/publicsuffix/list/pull/272

Out of curiosity, can you please share the reason of the removal?

**Comment by dbkegley** [comment]
We've been having trouble renewing our wildcard cert for our domain from namecheap and thought this may be related

**Comment by dbkegley** [comment]
COMODO is the CA for our cert through Namecheap. @weppos if you have any ideas as to why our request for a new wildcard is being denied we'd like to hear your thoughts. Our wildcard was issued initially before we added our domain to the PSL but it has since expired so we need to provision a new one.

**Comment by weppos** [comment]
Sorry for the delay @dbkegley . I went ahead and removed the entry. It's not the first time I hear about issues with Comodo. If I recall correctly @sleevi got the same feedback in another PR.

@sleevi did you have the chance to follow up with Comodo?

**Pull request merged**
