### PR TITLE
add maxlivingpromo.com

### PR DESCRIPTION
**Pull request by coronado101**
* [ ] Description of Organization
* [ ] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: [https://www.gritmedium.com](https://www.gritmedium.com)
Digital marketing company that uses social media platforms to help clients grow their business.

Reason for PSL Inclusion
====
Facebook is now requiring domain verification for ads pointing to and tracking webpages. This is the method facebook prefers to also verify subdomains.

DNS Verification via dig
=======
dig TXT _psl.maxlivingpromo.com +short
"https://publicsuffix.org/list/public_suffix_list.dat"

make test
=========

### CODE REVIEW

**Comment by dnsguru** [comment]
#1245 

Try Facebook's solution to domain validation issue: [https://developers.facebook.com/docs/sharing/domain-verification](https://developers.facebook.com/docs/sharing/domain-verification)

**Comment by coronado101** [comment]
> #1245
> 
> Try Facebook's solution to domain validation issue: https://developers.facebook.com/docs/sharing/domain-verification

All root domains have been verified through Facebook using it's domain verification process, their solution for subdomains involves adding to the domains to PSL, so including subdomains points me back to PSL pull request.

**Comment by dnsguru** [comment]
I read further and you're right... was trying to be helpful on a recommendation in pursuing this at the root cause.  Appears that was circular catch-22 on the matter.

The root solution will have to come from where these folks are working their stuff out: [https://github.com/privacycg/private-click-measurement/issues/78](https://github.com/privacycg/private-click-measurement/issues/78)

**Comment by bedfordsean** [comment]
Hi @coronado101,

The guidance from Facebook (clarified last week in the help centre article) is that this process is intended for large platform partners (like Shopify) to allow businesses that they host on behalf of to successfully validate their domain as if it were an eTLD+1. 

The Public Suffix List is not useful, nor intended to be used as a means to gain additional subdomain events reporting. If you just want to use subdomains as part of Facebook's aggregate event measurement, you already get 8 events under your eTLD+1 of maxlivingpromo.com. 

Can you confirm why you need subdomains under this eTLD+1 to be individually treated as eTLD+1s with cookie separation, which would be the behaviour post-addition to the PSL?

**Pull request closed without merging**
