### PR TITLE
Add Woods Valldata lottery and raffle domains

### PR DESCRIPTION
**Pull request by ChrisWhittleWV**
* [ X ] Description of Organization
* [ X ] Reason for PSL Inclusion
* [x] DNS verification via dig
* [ X ] Run Syntax Checker (make test)

* [ X ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organisation
====
Organisation Website: https://www.woodsvalldata.co.uk/
WoodsValldata is a charity fundraising service provider.
I am a software developer at WoodsValldata catering for the hosted raffle and lottery websites that we provide.

Reason for PSL Inclusion
====
Our raffle and lottery domains are used to issue subdomains to our clients for the sole purpose of running their lottery and/or raffle websites.
We wish to lock down the Cookie Security of these websites so that cross-contamination cannot occur on the domains that we wish to add to the PSL.

DNS Verification via dig
=======

make test
=========
I have followed the test as outlined in https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change
and the output hasn't come back with any errors.

### CODE REVIEW

**Comment by benjaminsavage** [comment]
Is this request related to issue #1245? That is to say, are you interested in allowing customers to run Facebook ads for specific sub-domains of this domain?

**Comment by dnsguru** [comment]
@ChrisWhittleWV : Please do reply regarding #1245 in the [question above](https://github.com/publicsuffix/list/pull/1329#issuecomment-847045727) in order for this request to proceed (or not)

**Comment by dnsguru** [comment]
@ChrisWhittleWV nudge

**Comment by dnsguru** [comment]
Hi @ChrisWhittleWV to determine if this can be processed or not, please truthfully answer the following:

__Submitter affirms the following:__ 
  * [ ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [ ] This request was _not_ submitted with the objective of working around other third party limits
  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

**Comment by n8schloss** [comment]
Hi @ChrisWhittleWV, is this related to iOS 14 and Facebook advertising at all? If so please see below:

Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift.

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by ChrisWhittleWV** [comment]
@n8schloss 
Many thanks for the information.

I have been in contact with the people in our business who made the decision to be included in the public suffix list and can confirm that one of the main reasons is due to Facebook pixel no longer working for our clients (we do not use Facebooks services ourselves) - therefore there does appear to be some crossover with regards to iOS 14 Facebook advertising.

We also want to use this functionality to help ensure that our clients are less likely to cross-contaminate their cookies with each other and understand that the web browsers which use the PSL do so by preventing cookies from being applied at the domain level.

I had followed the information provided in Facebook's help pages to get this far - although since then it appears that the information has evolved to include filling out the form you have kindly provided directions to find.

I have attempted to fill out the form provided by Facebook - however, it appears to be bugged and I get the attached screenshot when trying to submit the form.

image

I did once manage to get through the form and had an email saying that someone from the Facebook team would be reaching out shortly. But I signed up on Wednesday 02/06 and have had no further communication from Facebook - for reference, the "Job Number" I was assigned from Facebook via this email was 2994044684213654.
 
I attempted to use Facebook's bug report feature on the form URL, and have not heard back from that either.
 
I am now at a loss on how I can proceed with this request, as Facebook does not appear to have any direct help contact information. I can confirm that adding our domains to the PSL is something that our business does want to proceed with.

**Comment by bedfordsean** [comment]
Hi @ChrisWhittleWV I can confirm that this is in the system. The reason we expect a business manager in that dropdown is that any activities should be associated with FB marketing activities. You won't have seen one likely because you don't have access to a FB business manager on your FB account.

We'll come back to you in due course on next steps via the form you've completed

**Comment by dnsguru** [comment]
Excellent - closing this PR for now, please reference it should the FB review process move forward

**Comment by MartinKirk237** [comment]
Could we re-open this ticket and discuss our options please.  Failure to add these domains to the PSL is causing our clients real pain and loss of charitable income as well as preventing them advertising on FB.  Any advice is most welcome.

**Comment by bedfordsean** [comment]
Hi @MartinKirk237  -what was the outcome of your process with Facebook review?

**Comment by MartinKirk237** [comment]
Thanks for the quick response.

We got nowhere I’m afraid because we do not have a FB manager of our own as we do not advertise on FB ourselves.

Is there anywhere of getting on the PSL without FB involvement or is there a contact with FB you might be able to put me in touch with please?

MARTIN KIRK
Chief Technology Officer
T 01249 280074
M 07786 383883
E ***@***.******@***.***>

***@***.***

**Comment by bedfordsean** [comment]
@MartinKirk237 let me chase this one and get back to you shortly. I'll give you a call to follow up either tomorrow or Monday as I'm also in the UK. I've noted your mobile number from here. Just as a note that your number didn't get stripped here so you may wish to edit your comment to remove it from being cached by a search engine

**Comment by MartinKirk237** [comment]
Thank you for your help, very much appreciated.

**Comment by bedfordsean** [comment]
Hi @MartinKirk237 I've followed this one up internally. The main issue that we're facing with making a recommendation to proceed is that there are very few subdomains listed underneath the eTLD+1s that you'd actually like to add to the PSL.

For the sake of brevity on the PSL, we are generally following an approach in the FB recommendations flow of requiring the impact of being on the PSL to be beneficial to a minimum of 1000 subdomains. A Google search for *.raffleentry.org.uk and *.weeklylottery.org.uk is only showing up a handful of subdomains in total.

Can you confirm roughly speaking how many subdomains you serve today so that we can better understand a ballpark of how many businesses you serve and therefore how many businesses would benefit from a PSL addition?

**Comment by MartinKirk237** [comment]
Hi bedfordsean

Thank you for looking into this for us.

I cannot say we will have 1,000 subdomains on any of the eTLD+1s to be honest but the AffintyLottery could get close to that number (being launched next month).  There are more clients than it appears at the moment as the subdomain is only visible during periods of marketing activity and while raffle campaigns are active, generally most clients run 4 raffle campaigns p.a. each for 8 weeks or so at a time.  In total this will be effecting C.300 charity clients this year.

Our reasons for wanting to go onto the PSL are:

1) We want to segregate users cookies for security purposes, so that one subdomain cannot track cookies under another subdomain, as these cookies are intended for completely different clients. As we don’t host any websites at our top level domain, we are not interested in setting cookies for ourselves, simply to stop our clients from inadvertently sharing data, as they are all separate legal entities.

2) Our clients are currently having issues with signing up to Facebooks Aggregated Events Management because it requires for our clients to be able to have a level of control of the eTLD + 1 in Facebook.
Our clients do not share data between each other, which would be allowed in the event that we signed up for Facebooks Aggregated Events Management ourselves and allowed our clients as “business partners” so that they could use the information under our domain.
There is also a further issue that Facebooks Aggregated Events Management allows just 8 conversion points to anyone linked up to the eTLD + 1, which at the moment is any of the domains that we are attempting to list in the PSL.
Some of our clients use 4 conversion points, so this would prevent more than 2 of our clients from accessing Facebooks Aggregated Events Management services.

What we are trying to achieve is a level of cookie security preventing clients from being able to see each other’s data, and to allow our clients to use Facebooks Aggregated Events Management services.

I appreciate we may not meet the general criteria but I hope you understand this is causing major problems for our clients who are reducing, and in some cases, have paused their marketing campaigns until this issue can be resolved and as a consequence they are losing income.

I would really appreciate any advice you can give that may get this issue resolved.

Martin

MARTIN KIRK
Chief Technology Officer
E ***@***.******@***.***>

***@***.***

**Pull request closed without merging**
