### PR TITLE
Add digitaloceanspaces.com & regional subdomains

### PR DESCRIPTION
**Pull request by robbat2**
Add all regions of DigitalOcean Spaces to the PSL, to deliniate the
names which can be registered by users. This mirrors the inclusion of
Amazon S3.

Please note the contact email address goes to a superset of the domain
registration group, suitable for reaching all critical points of contact
regarding DigitalOcean's PSL entries.

Signed-off-by: Robin H. Johnson <rjohnson@digitalocean.com>

* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [ ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [X] This request was _not_ submitted with the objective of working around other third party limits
  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Organization Website: https://www.digitalocean.com/

I am Robin H. Johnson. I work for DigitalOcean. DigitalOcean offers many cloud services including virtualized servers, managed databases, managed kubernetes clusters, storage services, and an application platform.

Reason for PSL Inclusion
====

DigitalOcean's Object Storage Service: "Spaces" creates permits users to have subdomains for their services, within various scopes of the `digitaloceanspaces.com.` domain: 3rd & 4th level subdomains, with further subdomains within those (periods are permitted within the user-controlled portion of the FQDN). 

- We would like to be included in the list to provide cookie security for our end users.
- We would like to make it clear that separate customer-controlled content is hosted on each subdomain, and that inclusion/exclusion on blocking lists, such as the UK's web blocking system [who claim to use PSL to make some determinations].

This reflects similar entries listed for AWS S3: https://github.com/publicsuffix/list/blob/428efccbe95f13dc6d6399bef8aa274bdb588e86/public_suffix_list.dat#L10740

The domains are registered through 2028:
```
$ whois digitaloceanspaces.com |grep Date
Updated Date: 2021-06-09T20:23:10Z
Creation Date: 2017-02-23T21:30:06Z
Registry Expiry Date: 2028-02-23T21:30:06Z
Updated Date: 2021-06-21T20:50:33Z
Creation Date: 2017-02-23T21:30:06Z
Registrar Registration Expiration Date: 2028-02-23T21:30:06Z
```

DNS Verification via dig
=======

```
_psl.digitaloceanspaces.com. 600 IN	TXT	"https://github.com/publicsuffix/list/pull/1421"
_psl.ams3.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
_psl.fra1.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
_psl.nyc3.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
_psl.sfo2.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
_psl.sfo3.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
_psl.sgp1.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
_psl.ams3-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.fra1-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.nyc3-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.sfo2-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.sfo3-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.sgp1-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.ams3.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.fra1.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.nyc3.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.sfo2.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.sfo3.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
_psl.sgp1.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
```

make test
=========
Tests ran & passed.

### CODE REVIEW

**Review by sleevi — CHANGES_REQUESTED** [review]
Hi Robin,

We're trying to be mindful of the growth of the PSL here. This seems like quite a bit. Since you mentioned the Amazon design, note that it leads to a lot of security issues, and isn't exactly the best model to adopt.

Could you discuss a bit more about your name hierarchy and purpose? For example, it seems like a single entry, `*.digitaloceanspaces.com`, would give you all the flexibility you need. It'd be useful to understand more if you disagree, and better understand the constraints here.

**Comment by robbat2** [comment]
Hi @sleevi, the one concern we identified is that we may have future subdomains within `digitaloceanspaces.com` where we might want cookie sharing and other behaviors. As such, we've chosen to clearly represent the exact boundaries between customer & non-customer subdomains today. I think the root `digitaloceanspaces.com` domain might need to be removed entirely for this requirement. The PSL system does provide a negation operator `!`, but using that would require a lengthy period of making sure the negated entry was available in the PSL before depending on functionality.

The subdomains themselves cannot be changed as they were chosen years ago, before I joined this job, and customers already depend on them :-(.

- `${REGION}.digitaloceanspaces.com`, provides the S3 API endpoints, which CAN also return meaningful regular (browser-style) responses for GET requests etc.
- `${REGION}-static.digitaloceanspaces.com`, provides the S3 Website endpoints, which are strictly read-only, and provide some different behavior regarding redirections, as well what content is served for URLs that end with a slash like subdirectories.
- `${REGION}.cdn.digitaloceanspaces.com`, provides CDN wrappers to the other endpoints.

We also have the ability to launch other geographical regions in future.

P.S. i'm still waiting on approval loops on my end for the `_psl` DNS records to go live, hopefully in the next day or so.

**Comment by sleevi** [comment]
@robbat2 I’d like to push back on that a little, and ask that you consider the implications to end users from such a decision. Such enumerations are really an anti-pattern, and one of the considerations at play is limiting the number of entries an organization/registrant can have.

Part of these reviews are to try to identify equally workable alternatives, that don’t carry the same negative costs to end users and browsers.

Is there any technical reason you couldn’t use a separate domain for that use case (of shared cookies), allowing this entry to be limited, and thus reflective of a good Internet citizen looking to do the right thing?

**Review by dnsguru — CHANGES_REQUESTED** [review]
Just a sorting nit, but the cdn section should be before the static section alphabetically.  Please re-order those

**Comment by robbat2** [comment]
@dnsguru @sleevi I've converted it to the single wildcard for now, but would to request that preserve the history when you merge this PR, so that it does show the proposal to have the enumeration.

The _psl DNS records are also active now:
```
$ git show e01fa255992c3e02d524ca416c3d85854321e030:public_suffix_list.dat  |grep digitaloceanspaces.com |sed 's,^,_psl.,g' |xargs -n1 dig  -t TXT +noall +question +answer
;_psl.digitaloceanspaces.com.	IN	TXT
_psl.digitaloceanspaces.com. 600 IN	TXT	"https://github.com/publicsuffix/list/pull/1421"
;_psl.ams3.digitaloceanspaces.com. IN	TXT
_psl.ams3.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
;_psl.fra1.digitaloceanspaces.com. IN	TXT
_psl.fra1.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
;_psl.nyc3.digitaloceanspaces.com. IN	TXT
_psl.nyc3.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
;_psl.sfo2.digitaloceanspaces.com. IN	TXT
_psl.sfo2.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
;_psl.sfo3.digitaloceanspaces.com. IN	TXT
_psl.sfo3.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
;_psl.sgp1.digitaloceanspaces.com. IN	TXT
_psl.sgp1.digitaloceanspaces.com. 600 IN TXT	"https://github.com/publicsuffix/list/pull/1421"
;_psl.ams3-static.digitaloceanspaces.com. IN TXT
_psl.ams3-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.fra1-static.digitaloceanspaces.com. IN TXT
_psl.fra1-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.nyc3-static.digitaloceanspaces.com. IN TXT
_psl.nyc3-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.sfo2-static.digitaloceanspaces.com. IN TXT
_psl.sfo2-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.sfo3-static.digitaloceanspaces.com. IN TXT
_psl.sfo3-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.sgp1-static.digitaloceanspaces.com. IN TXT
_psl.sgp1-static.digitaloceanspaces.com. 600 IN	TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.ams3.cdn.digitaloceanspaces.com. IN TXT
_psl.ams3.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.fra1.cdn.digitaloceanspaces.com. IN TXT
_psl.fra1.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.nyc3.cdn.digitaloceanspaces.com. IN TXT
_psl.nyc3.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.sfo2.cdn.digitaloceanspaces.com. IN TXT
_psl.sfo2.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.sfo3.cdn.digitaloceanspaces.com. IN TXT
_psl.sfo3.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
;_psl.sgp1.cdn.digitaloceanspaces.com. IN TXT
_psl.sgp1.cdn.digitaloceanspaces.com. 600 IN TXT "https://github.com/publicsuffix/list/pull/1421"
```

**Review by dnsguru — COMMENTED** [review]
nslookup -type=txt _psl.digitaloceanspaces.com 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
_psl.digitaloceanspaces.com     text = "https://github.com/publicsuffix/list/pull/1421"

**Comment by dnsguru** [comment]
@sleevi this appears to have been revised to address the changes which you'd requested in https://github.com/publicsuffix/list/pull/1421#issuecomment-920545418 - the request otherwise passes the standard approval stage requirements that we typically validate against.

**Review by sleevi — APPROVED** [review]
As @dnsguru mentioned, thanks hugely for the consideration.

Our normal process is to squash-and-merge, but GitHub will maintain the PR history to reflect the discussion.

**Comment by robbat2** [comment]
Any remaining blockers for me to complete before you merge this?

**Comment by dnsguru** [comment]
No blockers, just available volunteer cycles.

**Comment by dnsguru** [comment]
@robbat2 all set.  Thsnk you again for addressing the modesty constraints

**Pull request merged**
