### PR TITLE
Adding Hoplix domains

### PR DESCRIPTION
**Pull request by W3b3r**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [X] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [X] This request was _not_ submitted with the objective of working around other third party limits
  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Organization Website: https://hoplix.com
I'm a Senior Software Engineer at Hoplix S.R.L., a company of print on demand product.

Reason for PSL Inclusion
====
Hoplxi S.R.L. offer free service of hosting on third level of hoplix.shop domain
We'd like to properly isolate each subdomain to prevent global cookie setting on hoplix.shop and our users need to verify our subdomains by yourself for facebook ads

All our users can purchase and/or connect their own domain name to their shops, if our user don't want to purchase and/or connect their own domain we need to improve cookie security and isolate each subdomain cookies for all *.hoplix.shop domains.

In addition if they use and/or not use own domain name we need to consider, the request between *.hoplix.shop domains samesite, and needed to leaving them open to CSRF.

DNS Verification via dig
=======
```
dig +short TXT _psl.hoplix.shop
"https://github.com/publicsuffix/list/pull/1364"
"https://github.com/publicsuffix/list/pull/1282" //old PR
```

make test
=========
```
============================================================================
Testsuite summary for libpsl 0.21.0
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

```
Extra info
=========
There is another PR(#1282) about this domain make for try to add hoplix.shop to public suffix

### CODE REVIEW

**Comment by bedfordsean** [comment]
Hi @W3b3r - have you followed the process detailed on #1282? Please can you confirm your Facebook form ID that was provided when you submitted a request to Facebook for review?

**Comment by W3b3r** [comment]
Hi bedfordsean,

we are waiting for facebook who complete our request to verify our facebook, instagram page/account

Thanks for patience

**Comment by bedfordsean** [comment]
Hi @W3b3r, to confirm the process to verify a Facebook or Instagram page is not the same as the process to be listed on the public suffix list. Please refer to the help center article here for more information: https://www.facebook.com/business/help/126789292407737?id=1205376682832142

**Comment by W3b3r** [comment]
Hi @bedfordsean, 

here is a facebook review ID #877998199483143 there 
Also i attach the screenshot if needed
https://s3-eu-west-1.amazonaws.com/s3-shareit/chrome_y1Gt0hgOFL.png

Kind Regards.

**Comment by bedfordsean** [comment]
Thanks @W3b3r, this was only raised 17 hours ago, so we have not yet followed through on this request. Note that you have not confirmed each of the entires on the form and until you do, we cannot proceed. Facebook support will be in touch with you shortly via that process. For now this GitHut request cannot be followed through on

**Comment by dnsguru** [comment]
No updates since July 5; closing this.  

IF and once this might be sorted out with Facebook first, open a new Pull Request and reference this PR, or re-open this one and include the information from the process with Facebook review.

**Comment by W3b3r** [comment]
I'm still waiting facebook response from July 5

**Comment by bedfordsean** [comment]
@W3b3r I will chase on this one for you. Once we close out that process, if we make a recommendation to proceed, then as dnsguru mentions here the approach will be to open a new PR. Please don't do that until we follow through on the Facebook side of things

**Comment by W3b3r** [comment]
@bedfordsean Ok thank you so much :D

**Pull request closed without merging**
