### PR TITLE
add `*.beget.app`

### PR DESCRIPTION
**Pull request by coding-liki**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website:  https://beget.com

I am a Software Engineer at Beget LLC, a hosting provider and domain registrar from Russia. 

Reason for PSL Inclusion
====
We are adding new software called BigBlueButton (https://bigbluebutton.org) on our VPS stack. We decided to give our customers a subdomain for each instance of BigBlueButton on their VPS.

Because of the software scope (virtual classroom, video conference), we'd like to properly isolate each subdomain to prevent global cookie setting on beget.app and highlight that each subdomain hosts BigBlueButton instance of a different user, unrelated to the others.

We will request the SSL certificate for these subdomains from  Let's Encrypt. As we have more than 7000 active VPS right now, we requested them for Rate Limit Adjustment by their form and received their approve.

DNS Verification via dig
=======
```
dig +short TXT _psl.beget.app
"https://github.com/publicsuffix/list/pull/1470"
```

make test
=========
test ran and passed

### CODE REVIEW

**Comment by dnsguru** [comment]
This appears to still be a draft - submitter please update if you wish to proceed for us to review

**Comment by coding-liki** [comment]
We are waiting for letsencrypt to proceed our request. That is why this pull request is still a draft. 
I do not want to deceive you about third party limits.
Also I have a question about domain maintaining check.
According to whois information our domain was registered on 2021-05-28 and the registry expiry date is 2023-05-28. 
Do we need to renew the domain for a longer period?

**Comment by dnsguru** [comment]
> We are waiting for letsencrypt to proceed our request. That is why this pull request is still a draft. I do not want to deceive you about third party limits. 

This authenticity is strongly appreciated

> Also I have a question about domain maintaining check. According to whois information our domain was registered on 2021-05-28 and the registry expiry date is 2023-05-28. Do we need to renew the domain for a longer period?

The registration term requirement was placed there to do two things.  

First, this volunteer-run project does not have the time, resources or tools to constantly review the PSL for stale domains - and we're looking to a future project of using some form of automated batch processes that purge out old entries, which would use  a combination of the expiry date and the presence of the TXT record in-zone.   Secondarily, it serves as a means to filter out "too-casual" requests where someone has a tactical need to get around rate limits to solve an immediate problem without thought for the longer term implications.   

If you would simply state ```I attest that we will keep the domain name renewed while present in the PSL and will maintain the TXT record in the DNS that was used to validate, understanding that our entries can be removed by future automation if we fail to do these things.``` it could suffice

**Comment by coding-liki** [comment]
Finally Lets-encrypt proceed our request and accepted the adjustment.  Thank you for waiting.

**Comment by coding-liki** [comment]
Also I can confirm that we will keep the domain name renewed while present in the PSL and will maintain the TXT record in the DNS that was used to validate

**Review by dnsguru — APPROVED** [review]
- DNS validation ok
- Tests pass
- No conflict with base
- Follows submission guidelines

APPROVED

**Comment by dnsguru** [comment]
@coding-liki MERGED

**Comment by coding-liki** [comment]
@dnsguru thank you.

**Pull request merged**
