### PR TITLE
hb.cldmail.ru has been removed

### PR DESCRIPTION
**Pull request by aplokmailru**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
VK LLC (former Mail.ru Group) is a diversified IT company.
We are providing B2C services as well as B2B.
Also we provide a cloud platform solutions https://mcs.mail.ru/en/

I'm Anton Plokhotnyuk, SRE at VK LLC, one of the persons who maintain projects infrastructure

Organization Website: 
https://vk.company

Reason for PSL Removal
====
We have been included to PSL due to PR #421 but now it makes us impossible to get wildcard SSL certificate.
So we decided to request to remove hb.cldmail.ru from PSL

DNS Verification via dig
=======

```
dig +short TXT _psl.hb.cldmail.ru
"https://github.com/publicsuffix/list/pull/1871"
```
Results of Syntax Checker (`make test`)
=========

```
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by aplokmailru** [comment]
Hello @dnsguru !
Do I need to add any additional info to this PR?

**Comment by simon-friedberger** [comment]
@aplokmailru Are the original security concerns for which this domain was added no longer valid? It seems like using wildcard certs is not really related to e.g. cookie separation.

**Comment by aplokmailru** [comment]
@simon-friedberger 
This domain is using as an endpoint for S3-like object storage. Consumers are unable to run any code behind it or use their own SSL certificates. So we control all cookies and hold other security issues under control. But the absence of wildcard certificate will make impossible usage of this domain at all.

**Review by simon-friedberger — APPROVED** [review]
LGTM

**Comment by simon-friedberger** [comment]
@aplokmailru I just read this: https://community.letsencrypt.org/t/what-happens-to-existing-wildcard-cert-when-domain-is-added-to-public-suffix-list/172552/10

Are you sure that you cannot get a wildcard cert?

**Comment by simon-friedberger** [comment]
@aplokmailru Do you still want this?

**Pull request closed without merging**
