### PR TITLE
Add `tech.orange`

### PR DESCRIPTION
**Pull request by AlexandreLINTE**
Add tech.orange in PSL

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by AlexandreLINTE** [comment]
We host many differents devops services (including Orange group hosting services) under tech.orange and for security reason we want to avoid cross cookies setting on the tech.orange domain.
A dedicated domain is defined for each service : <service_name>.tech.orange.

**Comment by dnsguru** [comment]
@AlexandreLINTE thank you for your PR.  

Despite the wide use of the PSL we are a small and lightly resourced team of volunteers, and we count on some automation to allow us to do more.  Specifically, we have automation built in 2014 as the nTLDs were starting to be added that pulls the json file from ICANN outlining the TLDs, and it did not contemplate subdomain requests by the TLD registry operator. 

We want to ensure that a subdomain within an 2012 round nTLD if added would not get overwritten by our automation.

Alternatively, if your request is time-sensitive, you update your PR to relocate this in the lower, private section as we have done with another of the 2012 round TLDs.  It would have the same net effect.

**Comment by AlexandreLINTE** [comment]
Time sensitive, it depend how long it will take to publish tech.orange into the PSL ? if we are talking about days, it s ok like this.
TXT DNS record is in place.

**Comment by cpu** [comment]
> @cpu what is the impact to the icann autpull automation if this is merged as-is? Should we recommend it be placed in private or will this work?

@dnsguru Anything between the `// newGTLDs` and `// ===END ICANN DOMAINS===` markers in the PSL dat file will be overwritten by the automation. The PRs are built by replacing that content with the result of processing the ICANN gtlds.json and the IANA tlds-alpha-by-domains.txt files and so I suspect merging this PR as-is would result in it being reverted by the next automation run.

**Comment by dnsguru** [comment]
@AlexandreLINTE it is as I feared, our automation would overwrite this if we place the domain as you are in the ICANN section.

We had to do a similar workaround for Rusnames in #1156 and #1159 where they submitted their substrings into the private section and that worked ok.  I think that is the fastest approach to take for now to suit your objective.

Option A is wait for ... no ETA or Option B is to please submit the PR but add a section for orange in the #PRIVATE section

**Review by dnsguru — CHANGES_REQUESTED** [review]
Slight 'friendly amendment' - could you please sort this higher into the file by commented company name?

**Comment by dnsguru** [comment]
@AlexandreLINTE if you can please move this so that it is sorted by commmented company name (this would conform to the guidelines) vs placing it at EOF

**Comment by AlexandreLINTE** [comment]
It's done, sorry for the mistake

**Review by dnsguru — APPROVED** [review]
Thank you, now sorted to guidelines.

- DNS Validates
- Guidelines Followed
- Tests Pass
- No Conflict With Base

APPROVED

**Pull request merged**
