### PR TITLE
Add myaddr.{dev,io,tools}

### PR DESCRIPTION
**Pull request by dnschecktool**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

addr.tools is a collection of (mostly) dns-based online tools.

addr.tools provides dynamic dns service with user-controlled subdomains under:
- myaddr.dev
- myaddr.io
- myaddr.tools

I, an individual, am submitting the above three domains for inclusion in the PSL as sole owner and creator of the service and owner of all domains listed.

Website: https://myaddr.tools

Reason for PSL Inclusion
====

Cookie security between subdomains in control by different users of the dynamic dns service

All three domains hold and shall continue to hold registration terms longer than 2 years.

Number of users this request is being made to serve: service is open to the public

DNS Verification via dig
=======

```
$ dig +short txt _psl.myaddr.{dev,io,tools}
"https://github.com/publicsuffix/list/pull/1912"
"https://github.com/publicsuffix/list/pull/1912"
"https://github.com/publicsuffix/list/pull/1912"
```

Results of Syntax Checker (`make test`)
=========

Nothing broke :)

### CODE REVIEW

**Comment by simon-friedberger** [comment]
That website suggests bad practices like DNS names for IP addresses of the form 1-2-3-4.foo.tld (which are explicitly forbidden in the guidelines) and redirecting the domain validation through its service.

**Comment by dnschecktool** [comment]
> That website suggests bad practices like DNS names for IP addresses of the form 1-2-3-4.foo.tld (which are explicitly forbidden in the guidelines) and redirecting the domain validation through its service.

Those are features of other sister tools, not of myaddr.{dev,io,tools} itself. The domains offering the "bad practices" as mentioned are not included in this review.

**Comment by simon-friedberger** [comment]
More bad practice: private keys are generated for the users. Actually, from the usage instructions it seems the private key is either a secret key (symmetric) or, more likely, a strong password.

@dnschecktool Since the service is open to the public, can you please provide user numbers?

**Comment by dnschecktool** [comment]
The "private keys" are actually just API tokens / strong passwords. They are generated from a crypto-secure source (/dev/urandom), are of more-than-sufficient bit length to make brute force attacks infeasible, and are only stored in a hashed form by the service. These are no different in functionality and security than tokens you would use to access other public APIs from Cloudflare, GitHub, etc.

In the last 30 days as of this comment, ~362k unique IPs queried the dynamic dns service across all user-controlled subdomains. So, the number of monthly users who visit services behind the dynamic dns subdomains is approximately on the order of hundreds of thousands. The number of active user-controlled subdomains is much smaller, though, in the hundreds. So it depends how you define "user". The security aspect of how browsers handle cookies for these domains certainly applies to all visitors.

**Comment by simon-friedberger** [comment]
* [x] Expiration
  * [x] myaddr.dev expires 2026-11-06
  * [x] myaddr.io expires 2026-11-06
  * [x] myaddr.tools expires 2026-11-06
* [x] DNS _psl entries
* [x] Tests pass
* [x] Sorting according to guidelines
* [x] Reasoning/Organization description

**Review by simon-friedberger — APPROVED** [review]

**Comment by dnsguru** [comment]
> In the last 30 days as of this comment, ~362k unique IPs queried the dynamic dns service across all user-controlled subdomains. So, the number of monthly users who visit services behind the dynamic dns subdomains is approximately on the order of hundreds of thousands. The number of active user-controlled subdomains is much smaller, though, in the hundreds. So it depends how you define "user". The security aspect of how browsers handle cookies for these domains certainly applies to all visitors.

hundreds then and still probably not to a scale that would be added.   Congrats on the audience, seriously, but by our definition, which really focuses on the eDNS+1's that are defined, the acctive user-controlled spaces seeking isolation for is the count.

**Comment by dnschecktool** [comment]
understood. thank you for the consideration.

**Pull request closed without merging**
