### PR TITLE
Adding Dynu.com domain names to the PSL

### PR DESCRIPTION
**Pull request by DynuSystems**
Adding the Dynu.com domain names to public_suffix_list.dat.

### CODE REVIEW

**Comment by DynuSystems** [comment]
For each suffix included in this patch, we have added a corresponding DNS TXT record called _psl that contains the link to this PR.

**Comment by zeva-dev** [comment]
dynu.com is one of the major free dns provider. Looking forward it is added to the list!

**Comment by milux** [comment]
+1

**Comment by sleevi** [comment]
Please ensure this PR complies with the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

**Comment by milux** [comment]
@DynuSystems Took me a few minutes, but I spotted the error:
You didn't sort the domains by TLD. Guidelines say sort first by TLDs, then by domain names.

**Comment by DynuSystems** [comment]
1. We are a free dynamic DNS service provider and we provide subdomains to our customers who may need Let's Encrypt certificates. We are adding the domain names to PSL to resolve the issue of rate limits.
2. For each suffix included in this patch, we have added a corresponding DNS TXT record called _psl that contains the link to this PR for DNS authentication purposes.
3. The recent commit fixed the sorting order issue in the previous commit.

Please let us know if there are any other issues with this PR. We appreciate your assistance and thank you very much for your time.

**Comment by sleevi** [comment]
The basis of this request appears to be to avoid Let's Encrypt rate limits, which are not a valid reason, per https://github.com/publicsuffix/list/wiki/Guidelines#validation

**Comment by ChrisShire** [comment]
Is that different from the inclusion of DuckDNS, no-ip.com, dynodes.com and other dynamic DNS providers?

**Comment by sleevi** [comment]
Those that followed the Guidelines?

**Comment by ChrisShire** [comment]
Respectfully, the basis for those services inclusion seems identical- They are all Dynamic DNS providers who want their customers to be able to use subdomains with Lets Encrypt, which seems to violate the guidelines. Genuine question as to why they were included in the list and Dynu.com would not be? Not trying to be rude.

**Comment by sleevi** [comment]
@ChrisShire We base the decision on the Pull Request and its adherence to the guidelines.

**Comment by DynuSystems** [comment]
Regardless of Let's Encrypt, the 13 domain names we are trying to add are public suffixes under which users directly register names to host their websites and many other services. Thank you.

**Comment by milux** [comment]
@sleevi With all due respect, when DDNS providers today mention that Let's Encrypt rate limits are one reason for them to apply for this list, maybe the main reason, then they are **just honest.**
Everything what might do better than @DynuSystems is to hide their real intentions.
Closing ones eyes for this reality and not giving equal service providers equal rights because of superior formulation of their request is double-standard.

As far as I can see it, this recognition is also reflected in the guidelines, quote:
> We do not accept entries whose **sole purpose** is to circumvent Let's Encrypt rate limits.
This rule was **clearly NOT violated!** Being a DDNS provider, and thus providing host names, is a valid reason to apply for this list. That means, that Let's Encrypt rate limits cannot be the **sole purpose**.

Please correct me if I'm mistaken or you can't agree with my interpretation.

**Comment by sleevi** [comment]
Again, we base decisions on the ability of the requestor to follow the guidelines and provide sufficient detail. Being a DDNS provider is not, in and of itself, a reason to apply for the list. In any event, it does not seem any further information is needed except from the domain holder, who is responsible for ensuring the request follows the guidelines.

**Comment by sleevi** [comment]
As this is a volunteer project, you are merely detracting from the time and resources that might be otherwise be used to assess and merge requests.

If you are not the domain holder, it is generally not helpful to continue commenting, and otherwise detrimental to your objectives, as it consumes otherwise sparse resources.

Pull requests are periodically reviewed. I would encourage those who support this PR to do so in a way that otherwise does not interfere with that - such as using the +1.

Put differently - arguing is not productive. It is otherwise best to wait until the maintainers have sufficient time to review the data - from the domain holder - and its compliance to the guidelines.

**Comment by sleevi** [comment]
And when in doubt, review the Guidelines and what is requested.

**Comment by milux** [comment]
I'm a volunteer as well, and I hate to see my time wasted by smart-asses as well, so I understand that perfectly.
The best strategy to avoid it is to always tell people outright what they do wrong, tell wrong, or speak wrong.

I checked the guidelines multiple times and compared this PR to similar PRs, and this one seems valid and complete to me. So, I assume that it will be merged soon.

Thanks for your time and your efforts, all the best!

**Comment by DynuSystems** [comment]
The domain names in this pull request are offered to third party individuals and organizations to register subdomains. The subdomains are used for host websites, FTP servers, identify a remote device etc. For example, roby9.dynu.net, arktia.dynu.net. This is the main purpose of adding those domain names to PSL. We do not deny that Let's encrypt certificate limit is also part of the reason for this request.

Please let us know if you need any more information or any further actions from us. Thank you.

**Pull request merged**
