### PR TITLE
Add `adoveo.com` to public suffix list

### PR DESCRIPTION
**Pull request by NagaVenkata**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

 * [x] * Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
Adoveo is a digital marketing company which provides the creation of interactive landing pages for high end brands in FMCG, Retail and charity.
Organization Website: https://adoveo.com

Reason for PSL Inclusion
====
Adoveo platform helps users to create their own websites under subdomains.

Main reason we would like to be included in the list is to provide cookie security for our users. As well, our users need to be able to issue Let's Encrypt certificates for their subdomains.

We previously made pull request for solving FB issues, but it's not the case anymore.

DNS Verification via dig
=======
dig +short TXT adoveo.com
"https://github.com/publicsuffix/list/pull/1495"

make test
=========
Tests passed OK.

### CODE REVIEW

**Comment by dnsguru** [comment]
Related wontfix: #1345 #1346

**Comment by dnsguru** [comment]
Hoping to hear from FB/Meta colleagues on the review and vetting having taken place.

**Comment by NagaVenkata** [comment]
Hi, Do we need to make any action from our side now? We have waited for so long. Can we speed up process somehow?

**Comment by dnsguru** [comment]
Can you explain how the situation changed from the original request to have this entry as a workaround to rate limits in order to enable FB?

**Comment by NagaVenkata** [comment]
Our platform makes subdomains linked to user's accounts like $user.adoveo.com. That's why every subdomain should be treated as separate domain. Since our clients responsible for cookies and GDPR policy we need to forward rights for every subdomain in user's hands to increase security level. Another problem is that we need to allow automatic ACME registration for all used subdomains. We getting more and more request on cookies security from clients so FB is not the case anymore.

**Comment by dnsguru** [comment]
Requestor attests this is not a #1245 workaround

**Comment by dnsguru** [comment]
Closing due to >30 day non-response or update by submitting party.  The linter _stuff_ needed to be removed to proceed. 

Please re-open and correct the issue if this pull request is still desired

**Pull request closed without merging**
