### PR TITLE
Add workers.dev

### PR DESCRIPTION
**Pull request by jRiest**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://www.cloudflare.com/

Cloudflare recently announced workers.dev ([blog post](https://blog.cloudflare.com/announcing-workers-dev/)) as a way to easily deploy serverless applications running on [Cloudflare Workers](https://www.cloudflare.com/products/cloudflare-workers/). More information on the project is also available at the [workers.dev](https://workers.dev/) homepage.

I am an engineer on the Workers team at Cloudflare. For this PR, we setup an email alias (publicsuffixlist@cloudflare.com) that can be used to contact the relevant employees at Cloudflare.

Reason for PSL Inclusion
====

Cloudflare customers will given a subdomain of `workers.dev` to which they can deploy their serverless applications. Because subdomains are each controlled by different customers, they should be treated as separate domains for cookie purposes.

DNS Verification via dig
=======

```
$ dig +short TXT _psl.workers.dev
"https://github.com/publicsuffix/list/pull/772"
```

make test
=========
[make test output](https://pastebin.com/rJPKXJhH)

### CODE REVIEW

**Comment by weppos** [comment]
@jRiest I see the site is published at workers.dev. By setting `workers.dev` as public suffix, browsers won't be able to set cookies on the site.

That's just one example. Other consumers may consider https://workers.dev as invalid since it's a suffix. It's generally not adviseable to publish a site that matches a suffix.

The common alternatives are to (1) use a different name/level for the public suffix (e.g. workers.io, site.workers.dev) or (2) use the www for hosting the site (e.g. https://www.workers.dev).

I understand both options will not have the same marketing effect, but I wanted to warned you before merging the changes. Ultimately, if you decide to accept the risk of unexpected behaviors, I'll be fine to go ahead and merge.

**Comment by ExE-Boss** [comment]
Well, `js.org` has a website at https://js.org/.

**Comment by weppos** [comment]
@ExE-Boss I didn't say it was not possible, I just said that it could lead to unexpected behaviors in browsers and other clients. 

I know Chrome for example won't be able to set any cookie, as @sleevi mentioned in the past for similar cases.

If you understand and accept this caveat, I have to objection to merge. But I felt the responsibility to warn you before.

**Comment by jRiest** [comment]
Thank you for the warning @weppos. We can switch to hosting the main page from `www.workers.dev` but we want to proceed with merging this PR in the meantime.

**Pull request merged**
