### PR TITLE
Update cn.vu in Private section

### PR DESCRIPTION
**Pull request by neupeer**
Update to the latest changes.

### CODE REVIEW

**Comment by sleevi** [comment]
This pull request provides no justification for why these changes are being made. We'll be required to WontFix this without further details.

**Comment by neupeer** [comment]
Thanks for your kind reminder. As you could see, the name and website of our organization, as well as my usual contact email address, have changed, so necessary changes need to be made so that the information in the list is consistent with the latest and accurate.

**Comment by dnsguru** [comment]
revises #987

**Review by dnsguru — APPROVED** [review]
* Updates comments not name ; cosmetic
* Follows format and structure guides
* Updater = Sub-section Submitter
* Rationale sufficient

**Approved**

(should we consider prioritizing #1201 ?)

**Pull request merged**
