### PR TITLE
Securepoint Dynamic DNS - spdyn

### PR DESCRIPTION
**Pull request by Naugrimm**

### CODE REVIEW

**Comment by Naugrimm** [comment]
- [x] DNS updated

**Comment by sleif** [comment]
I'm looking forward to this! I want to secure my owncloud server access.

**Comment by trendyanoraks** [comment]
Me too!

**Comment by mommmomm** [comment]
Tanks for adding spdns.de and all the other spdyn domains,, Naugrimm!

@PSL How long can such a simple merge possibly take?

**Comment by migasQ** [comment]
*push

**Comment by sleevi** [comment]
Please see https://github.com/publicsuffix/list/wiki/Guidelines on how to properly format a Pull Request so that it can be validated and merged.

**Comment by Naugrimm** [comment]
@sleevi 
- [x] modified pull request

**Comment by rsdev277** [comment]
I'm looking forward to this!

**Comment by logopk** [comment]
Need this too. Please!

**Comment by ohunecker** [comment]
Please merge!

**Comment by stefanLeo** [comment]
Looking forward to it as well! - Pls. merge :+1:

**Comment by sleevi** [comment]
Please do not comment on "Please merge" - GitHub has reactions for that reason.

As it stands, this cannot be merged because it needs to be rebased (see the status below). Once done we can merge.

**Comment by freaky-m0** [comment]
So it is still not possible to use Let's Encrypt with SPDYN/SPDNS Domains? I get an error if i try it with my Synology NAS. "Too many requests....."

**Comment by weppos** [comment]
@Naugrimm the PR looks good however, before proceeding, I actually want to notify you that quite a few things changed since May and the correct way to avoid the Let's Encrypt limits is to request the limits to be adjusted using the official form as described in https://letsencrypt.org/docs/rate-limits/

Therefore, merging this PR, may not affect Let's Encrypt at all, but instead will have consequences on how clients will interpret your domains.

Are you aware of this? Given this change, do you still want to proceed?

**Comment by Naugrimm** [comment]
@weppos  I was not aware of the changes to the rate-limiting. Thank you. I will reach out to the letsencrypt people to see if there is a solution for dyndns-providers.

Nevertheless we think the domains our customers use should appear in the PSL, so someone who owns `a.spdns.de` can not set a cookie for `.spdns.de` that gets transmitted to all other users of this 2nd-level-domain.

So if I did not totally misunderstood the concept of the PSL, I kindly ask you to merge this PR.

**Pull request merged**
