### PR TITLE
Adding cloud66.zone

### PR DESCRIPTION
**Pull request by khash**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

## Description of Organization
`cloud66.zone` is owned by Cloud 66 (www.cloud66.com). Cloud 66 products allow developers and operators build, manage and maintain their application stacks on any cloud provider. 
Organization website: https://www.cloud66.com

Reason for PSL Inclusion
====
`cloud66.zone` is used by Cloud 66 customers to make their Kubernetes hosted services externally available in turn secure them with Let's Encrypt. The DNS records for this domain are automatically updated and maintained by Cloud 66.

DNS Verification via dig
=======

```
dig +short TXT _psl.cloud66.zone
"https://github.com/publicsuffix/list/pull/797"
```

make test
=========
done

### CODE REVIEW

**Comment by groundcat** [comment]
Hello @khash I have noticed that the domain cloud66.zone has expired for a while (Registry Expiry Date: 2025-03-27T19:13:39Z). 

Is this project still active? If the service has been decommissioned and the domain is no longer linked to an active project, please confirm whether it can be safely removed from the PSL. To maintain your domain in the PSL, please ensure it is renewed **for more than 2 years at all times**.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period (over 30 days), your entry may be subject to removal. Thank you. #1119

**Comment by khash** [comment]
Hi @groundcat thank you for the message and your work on the PSL. Our organization and other PSL domains we have are still active and working, except for cloud66.zone which is part of a discontinued feature. This can now be deleted. I can submit a PR for it's removal if you prefer, or leave it to be removed automatically.

**Comment by groundcat** [comment]
Thank you for confirming @khash

Since cloud66.zone is no longer needed, we would appreciate if you could submit a new PR to remove it from the PSL. We plan to implement something like automated removal in the future based on missing _psl records but that system isn't currently implemented (yet), so manual PRs are still the only method for removing entries. Thanks for your prompt response and for helping us keep the PSL current!

**Comment by khash** [comment]
@groundcat absolutely! the PR is here. Since the PR guidelines are around adding a new entry, I removed them from the comments. https://github.com/publicsuffix/list/pull/2483

**Pull request merged**
