### PR TITLE
Update DynDNS Domains dnshome.de

### PR DESCRIPTION
**Pull request by Bodenhaltung**
* [X] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://www.dnshome.de

DynDNS Service.

Reason for PSL Inclusion
====

Let's Encrypt

DNS Verification via dig
=======

```
for i in $(cat psl.txt); do echo -n "$i": && dig +short _psl."$i" TXT; done
ddnssec.de:"https://github.com/publicsuffix/list/pull/786"
dnshome.de:"https://github.com/publicsuffix/list/pull/786"
dnshome.icu:"https://github.com/publicsuffix/list/pull/786"
dyndns.icu:"https://github.com/publicsuffix/list/pull/786"
dyndnssec.de:"https://github.com/publicsuffix/list/pull/786"
resolve.bar:"https://github.com/publicsuffix/list/pull/786"
srvdns.de:"https://github.com/publicsuffix/list/pull/786"
```

make test
=========

Without errors.

### CODE REVIEW

**Comment by sleevi** [comment]
I don't believe this change is correct, but the lack of information in the description makes this difficult to confirm.

Are you sure you want a wildcard entry? Providing example entries of the domains you'd like to separate will confirm, as a wildcard has the effect of making all subdomains of the listed domain themselves treated as public suffices.

**Comment by Bodenhaltung** [comment]
> I don't believe this change is correct, but the lack of information in the description makes this difficult to confirm.

Which informations do you need?

> Are you sure you want a wildcard entry? Providing example entries of the domains you'd like to separate will confirm, as a wildcard has the effect of making all subdomains of the listed domain themselves treated as public suffices.

I am sure, yes. It is a DynDNS Service, so there exists many subdomains and a lot of needs e.g. letsencrypt certificates.

**Comment by sleevi** [comment]
Please read the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) and make sure you've provided example domains.

Again, your use of wildcards affects not just the subdomains, but causes each of them to be treated as public suffices. For many CAs, this will prevent obtaining *any* certificate. If you have example domains that your users use, this clarifies.

However, I'm closing this, per the Guidelines, as requesting to increase Let's Encrypt rate limits can be done with Let's Encrypt itself.

**Comment by Bodenhaltung** [comment]
> However, I'm closing this, per the Guidelines, as requesting to increase Let's Encrypt rate limits can be done with Let's Encrypt itself.

I have read the Guidlines and i have also sub.sub.domain.tld. So is the use of is wildacrds correct.

I quote from Lets Encrypt rate limits desciption:

> The main limit is Certificates per Registered Domain (50 per week). A registered domain is, generally speaking, the part of the domain you purchased from your domain name registrar. For instance, in the name www.example.com, the registered domain is example.com. In new.blog.example.co.uk, the registered domain is example.co.uk. We use the Public Suffix List to calculate the registered domain.

Source: https://letsencrypt.org/docs/rate-limits/

**Pull request closed without merging**
