### PR TITLE
addition of ss sld's sch.ss and me.ss

### PR DESCRIPTION
**Pull request by jawr**
* [ x] Description of Organization
* [x ] Reason for PSL Inclusion
* [ x] DNS verification via dig
* [ x] Run Syntax Checker (make test)

Description of Organization
====
Individual.

Reason for PSL Inclusion
====
This adds missing entries that are stated on https://registry.nic.ss/ (pointed to via https://www.iana.org/domains/root/db/ss.html)

DNS Verification via dig
=======
Requesting DNS Verification be set aside as we are updating the entry for an existing entry to align it with the registry listed information that is verifiably listed at the authoritative registry listed with the IANA.

make test
=========
Ran with no issues.

### CODE REVIEW

**Comment by dnsguru** [comment]
Thank you for submission.  Because this was submitted without DNS verification proof in zone, I have reached out to registry point of contact at KENIC to verify these

**Comment by dnsguru** [comment]
Relates to #983

**Comment by dnsguru** [comment]
+ @ahmedlandi

**Comment by jchoudha** [comment]
@dnsguru shouldn't the contact be technical at nic.ss/ssNIC, for .ss? I'm not sure what KENIC have to do with ssNIC.

**Comment by dnsguru** [comment]
> @dnsguru shouldn't the contact be technical at nic.ss/ssNIC, for .ss? I'm not sure what KENIC have to do with ssNIC.

@jchoudha .ke also operate the .ss as well.

nudge: @ahmedlandi

**Comment by ahmedlandi** [comment]
aplogies for delays - sch.ss and me.ss has been part of the .ss zones delegation since inception.

**Comment by dnsguru** [comment]
That was feedback from previously validated registry operator approving the
change.

**Review by dnsguru — APPROVED** [review]
Change validated by registry / section submitter

APPROVED

**Pull request merged**
