### PR TITLE
Add `myamaze.net`

### PR DESCRIPTION
**Pull request by amazesoftware**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowlegements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Amaze Software provides:
1. A WYSIWYG SaaS design tool for building HTML5 sites that have a mobile, card-based, touch-based interface, with 3D transitions, and e-commerce integrations.
2. An HTTPS publishing platform for these apps, with automatic certificate generation of both (a) custom domains, and (b) subdomains off myamaze.net.

Currently, most customers publish on a sub-folder of my-amaze.net, but we would like to provide each custumer a custom a subdomain off myamaze.net, rather than a sub-folder, for better branding and technical isolation.

I am Ben Woolley, the current Domain Admin <domainadmin@amaze.co> (mentioned in the PSL submission), and software developer who has developed the custom domain feature, with integration into letsencrypt (via greenlock), and am generally leading improvements to the hosting aspects of the product.

Organization Website: 

https://amaze.co

Reason for PSL Inclusion
====

We would like to automatically provision a unique sub-domain for each customer:
1. so each customer gets their own branded host, for better e-commerce conversions.
2. to better technically isolate each customer's published apps, for measurement (cookie isolation) and abuse purposes (some abuse notifications may become more specific to the customer).
3. to register ourselves with the community as a "private registrar" like other e-commerce platforms that provide per-user subdomains, like shopify. 

We already have a rate increase with letsencrypt. 

Number of users this request is being made to serve:

We have a letsencrypt rate limit increase for myamaze.net to 1000 per week. Currently several hundred new customers per week, to expand greatly with new marketing efforts. 

DNS Verification via dig
=======

```
dig +short TXT _psl.myamaze.net
"https://github.com/publicsuffix/list/pull/1602"
```

Results of Syntax Checker (`make test`)
=========

```
$ make test-syntax
cd linter;                                \
	  ./pslint_selftest.sh;                     \
	  ./pslint.py ../public_suffix_list.dat;
-n test_NFKC:
OK
-n test_allowedchars:
OK
-n test_dots:
OK
-n test_duplicate:
OK
-n test_exception:
OK
-n test_punycode:
OK
-n test_section1:
OK
-n test_section2:
OK
-n test_section3:
OK
-n test_section4:
OK
-n test_spaces:
OK
-n test_wildcard:
OK
```

```
$ LIBICU_CFLAGS=-I/opt/homebrew/Cellar/icu4c/70.1/include LIBICU_LIBS='-L/opt/homebrew/Cellar/icu4c/70.1/lib -licui18n -licuio -licuuc' make test
[...]
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

### CODE REVIEW

**Comment by amazesoftware** [comment]
Added organization verification through DNS, in the manner you have recently requested from canva. 
```
dig +short TXT _psl.amaze.co
"https://github.com/publicsuffix/list/pull/1602"
```

**Comment by amazesoftware** [comment]
Rebased and resolved conflict with Amazon updates next to this entry.

**Comment by dnsguru** [comment]
Thank you for validating org and rebasing

**Review by dnsguru — APPROVED** [review]
* sorts to guidelines
* validated org email connection via DNS TXT= PR
* validated submitted domains via DNS TXT = PR
* tests pass
* No conflict with base

APPROVED

**Comment by dnsguru** [comment]
@amazesoftware This has been merged

**Comment by HostFly** [comment]
Is this some special case that got approved so quickly?

**Pull request merged**
