### PR TITLE
Add Hash Hackers TLDs under `telegram.ind.in`, `iii.ind.in` and `hashhackers.win`

### PR DESCRIPTION
**Pull request by PBhadoo**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

====

Organization Website: https://hashhackers.com

Hash Hackers makes free service websites to make the internet better, we are a group of people who build open source software's, contribute to them, deploy free software's on Servers based on donations and free products of different organizations. We're building new products now which will require each user to have their own domain name (eg. Telegram Web).

Reason for PSL Inclusion
====

* First Reason is Cloudflare and other DNS hosting providers like Netlify. Every user who will make app from our network will need to use services like Netlify, Cloudflare Workers, Cloudflare Pages, Vercel or Heroku. Their Free plan are enough to run our currently [available](https://gitlab.com/ParveenBhadooOfficial/Google-Drive-Index) and upcoming apps.
* For Telegram we are building an Application Network for users to have their own web version of Telegram, making it easier to use for every user at their own host privately. Also we are making it possible to each user to have their own domain which they can share in public to link their profile, channel or groups.
* Using different domains to deploy different project on different locations. eg. our Rapidleech Deployments. (Not Possible on sub-domains when there are large numbers of users and IP addresses of Rapidleech host providers change time to time.)
* These all should cover the Cookie Security, Let's Encrypt issuance, Cloudflare/Netlify Host issues.

DNS Verification via dig
=======

````
dig +short TXT _psl.hashhackers.win
"https://github.com/publicsuffix/list/pull/1562"
dig +short TXT _psl.*.app.hashhackers.win
"https://github.com/publicsuffix/list/pull/1562"
dig +short TXT _psl.iii.ind.in
"https://github.com/publicsuffix/list/pull/1562"
dig +short TXT _psl.*.app.iii.ind.in
"https://github.com/publicsuffix/list/pull/1562"
dig +short TXT _psl.telegram.ind.in
"https://github.com/publicsuffix/list/pull/1562"
dig +short TXT _psl.*.b.telegram.ind.in
"https://github.com/publicsuffix/list/pull/1562"
dig +short TXT _psl.*.c.telegram.ind.in
"https://github.com/publicsuffix/list/pull/1562"
dig +short TXT _psl.*.g.telegram.ind.in
"https://github.com/publicsuffix/list/pull/1562"
dig +short TXT _psl.*.u.telegram.ind.in
"https://github.com/publicsuffix/list/pull/1562"
````

make test
=========

I ran the test but couldn't understand much about it.
````
D:\test\list>D:\GnuWin32\bin\make.exe
cd linter;                                \
          ./pslint_selftest.sh;                     \
          ./pslint.py ../public_suffix_list.dat;
The system cannot find the path specified.
make: *** [test-syntax] Error 1
````

### CODE REVIEW

**Comment by dnsguru** [comment]
Trying to reconcile 

>"First Reason is Cloudflare and other DNS hosting providers like Netlify. Every user who will make app from our network will need to use services like Netlify, Cloudflare Workers, Cloudflare Pages, Vercel or Heroku. "

against 

>[x] This request was not submitted with the objective of working around other third-party limits

These seem to be in conflict - can you explain how this request is not attempting to work around rate limits or restrictions of third party systems?

**Comment by PBhadoo** [comment]
It's pretty Simple concept.

Any domain included in PSL automatically works around rate limits or restrictions of third party systems.

But, Our main goal is to treat each user as separate on the domain.
To provide Cookie Security, Let's Encrypt issuance problems on each domain for each user.

While users can use AWS (if domain is not in PSL), without the PSL inclusion Cookie Security and Other Cross Domain Security issues arises.

With PSL inclusion each user can manage their domain name with their favorite DNS provider without the Cookie Security issues. And additional unwillingly solves another issue, where users can also use Cloudflare or Netlify as their DNS provider. Most importantly the users for *.app.hashhackers.win domain where they need to host their APPs on Cloudflare Workers.

The conflict is merely a coincidence, that PSL inclusion also fixes some additional problems.

**Review by dnsguru — CHANGES_REQUESTED** [review]
This was added in the wrong section of the PSL - it belongs in the PRIVATE section.  

Please move it for consideration and security/validity review to begin

**Comment by PBhadoo** [comment]
@dnsguru Proceed Please. I've done changes, it requires review from your end now.

**Comment by Juegonegro1991** [comment]
Alguien me puede decir cuál programa es mejor para hackear facebook q no cobre y sin servidos para entrar

**Comment by PBhadoo** [comment]
@dnsguru Please review this.

**Comment by PBhadoo** [comment]
delayed too long.

**Comment by dnsguru** [comment]
We await security review ; also, the domain is not viewable to review that this is or is not a request that violates the guidelines in focusing on working around third party limits.

**Comment by dnsguru** [comment]
Thank you.  Based upon the description provided, an entry in the PSL is saught in order to bypass the rate limits of Cloudflare amd Netlify.

This is against the policy of PSL inclusions.

The appropriate thing to do is to work directly with those organizations to discuss inclusion in rate limit exceptions.

**Comment by PBhadoo** [comment]
> Thank you. Based upon the description provided, an entry in the PSL is saught in order to bypass the rate limits of Cloudflare amd Netlify.
> 
> This is against the policy of PSL inclusions.
> 
> The appropriate thing to do is to work directly with those organizations to discuss inclusion in rate limit exceptions.

No, this is not to bypass rate limits.
This is to provide each user a Seperate domain name.

**Comment by dnsguru** [comment]
Both are true.  These are not mutually exclusive attributes.

Please work directly with Netlify or Cloudflare etc to address those issues with individual domains, as the PSL is not designed to be used for bypassing other's system limits or restrictions as indicated.

**Comment by simon-friedberger** [comment]
Organization website unavailable. Tests were never run. Is this still wanted?

**Pull request closed without merging**
