### PR TITLE
Please add keymachine.de into public_suffix_list

### PR DESCRIPTION
**Pull request by MartinDannehl**
Added keymachine.de - keyweb.de Hosting Company generic hostname suffix.

### CODE REVIEW

**Comment by MartinDannehl** [comment]
Hello,

_psl.keymachine.de IN TXT "https://github.com/publicsuffix/list/pull/310"

has been created now and should be propagated within the next 24h.

```
 host -t TXT _psl.keymachine.de ns.keymachine.de
Using domain server:
Name: ns.keymachine.de
Address: 62.141.48.94#53

_psl.keymachine.de descriptive text "https://github.com/publicsuffix/list/pull/310"

```

Feedback if anything else is needed would be appreciated.

**Comment by sleevi** [comment]
For the header, please list in the form of

`Company Name : Company URL`

After that, we should be ready to go.

**Comment by MartinDannehl** [comment]
Keyweb AG : https://www.keyweb.de

Or should i create a new pull request?

Thank you

**Comment by sleevi** [comment]
You should be able to use GitHub's web editor to edit your branch and
update the pull request

**Comment by MartinDannehl** [comment]
Hello,

i've updated the request.

Thank you

**Comment by MartinDannehl** [comment]
Hello,

seems that update results in a conflict, could you please give me a hint what i've done wrong?

Best Regards
Martin Dannehl

**Comment by MartinDannehl** [comment]
Hello,

seems the recent merges to PSL causes the conflict, edited it with the recent master version of PSL again

Please let me know if there is anything else i could do.

Best Regards
Martin Dannehl

**Comment by MartinDannehl** [comment]
As this still creates a conflict, i've created a new pull request:

https://github.com/publicsuffix/list/pull/318

Please let me know if i need to change the _psl.keymachine.de TXT record or if authentificating for #310 is enoug.

**Pull request closed without merging**
