### PR TITLE
Update public_suffix_list.dat

### PR DESCRIPTION
**Pull request by nats**
Add bnr.la

### CODE REVIEW

**Comment by sleevi** [comment]
Please review https://github.com/publicsuffix/list/wiki/Guidelines for how to authenticate this request.

**Comment by nats** [comment]
I have added DNS authentication

**Comment by sleevi** [comment]
Sorry for not being explicit, but please review https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change

**Comment by nats** [comment]
> add a brief description of why you want the suffix(es) to be added to the list

BinaryLane is a low-cost VPS service, often used by small developers and enthusiasts.  Many of our customers do not want to pay for their own domain but (understandably) do not find their IP address memorable; we will be providing customers ability to create their own subdomain  under bnr.la to reference their server.

We want to add bnr.la to the public suffix list to ensure that customers do not accidentally leak their individual website cookies to our other customers.

**Pull request merged**
