### PR TITLE
Added MoblyPage domain: mobly.page

### PR DESCRIPTION
**Pull request by adrianodimatteo**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [ ] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://moblypage.com/

MoblyPage is a platform for building mobile websites. I'm the web developer of this platform.
Registered users get their own subdomain (e.g. username.mobly.page) on which their sites are hosted.

#1303 

Reason for PSL Inclusion
====

We'd like to properly isolate each subdomain to prevent global cookie setting on mobly.page and highlight that each subdomain hosts sites of a different user, unrelated to the others.
It will also help us to verify subdomains on Facebook and to follow Apple's requests for updates to the IOS14 data policy.

DNS Verification via dig
=======

```
dig +short TXT _psl.mobly.page
"https://github.com/publicsuffix/list/pull/1303"
```

make test
=========

### CODE REVIEW

**Comment by n8schloss** [comment]
Hi @adrianodimatteo,

Facebook recently updated our [help center guidance](https://www.facebook.com/business/help/126789292407737?id=1205376682832142) around this and I'd like to specifically call out this section:

> Our current efforts are designed to support preexisting Public Suffix List domain registrations or eTLDs. This support is in line with Apple’s recent Private Click Measurement update. There are other technical implications if a domain is registered as a Public Suffix that a business should consider (for example, the domain that is registered on the Public Suffix List cannot have its own cookies) and as such, we do not recommend that clients register their domains on the Public Suffix List specifically for Facebook event configuration.

I do not see content on mobly.page, searching for '\*.mobly.page' does show quite a few distinct subdomains, and it seems like those subdomains are used for distinct entities. So given that you stated that cookie security is also a desired outcome here, then I think that this request makes sense. However, before continuing with this request please make sure to read Facebook's updated guidance and make sure that you understand the full implications of being added to the PSL. Given the update cadence of browsers using this list if you get added and then notice breakages and want to be removed it may take many months for things to be updated.

**Comment by adrianodimatteo** [comment]
Thanks for the quick reply. I am sure I want to proceed.

**Comment by dnsguru** [comment]
Please read #1245

**Comment by n8schloss** [comment]
Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737  

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift. 

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
excellent @n8schloss closing this, reference this pr# should a new one be requested

**Pull request closed without merging**
