### PR TITLE
Add encoway domain: eu.encoway.cloud

### PR DESCRIPTION
**Pull request by Marcel-D-encoway**
Description of Organization
====

Organization Website: https://www.encoway.de/en/
encoway GmbH provides companies from the manufacturing industry with CPQ software.

Reason for PSL Inclusion
====

For each installation our clients get a subdomain of eu.encoway.cloud so they can access their system via web without having to incure additional fees for domains, static IP address or dyndns as this is handled by our system. Since each installation belongs to a separated legal entity and deals with that entity valuable information, security is top concern for us and our clients. It has proven that having the subdomains recognized by the browsers as separate domains and not share cookies or other vital information is a good working practice.

DNS Verification via dig
=======

```
dig +short TXT _psl.eu.encoway.cloud
"https://github.com/publicsuffix/list/pull/1430"
```

 
* [x]  Description of Organization
* [x]  Reason for PSL Inclusion
* [x]  DNS verification via dig
* [x]  Run Syntax Checker (make test)
* [x]  Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place
 
**Submitter affirms the following:**
 
* [x]  We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
* [x]  This request was _not_ submitted with the objective of working around other third party limits
* [x]  The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
* [x]  The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

**For Private section requests that are submitting entries for domains that match their organization website's primary domain:**

```
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```

(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

* [x]  Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.

### CODE REVIEW

**Comment by dnsguru** [comment]
The following must be answered and addressed in order to have a complete request.  The PR stays public record for those downline to the PSL that incorporate it in order to see that there was some review done with the submitting party.

Additionally, we volunteer reviewers use the count summary as a measure to determine that a submitted PR is complete or not.

We will need more information on the organzation description and the reason for inclusion, as well as answers to the other questions.

* [ ] Description of Organization
* [ ] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)


* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place


__Submitter affirms the following:__ 
  * [ ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [ ] This request was _not_ submitted with the objective of working around other third party limits
  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [ ] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

**Comment by Marcel-D-encoway** [comment]
@dnsguru thank you for your feedback.
We have updated the initial comment.

**Comment by dnsguru** [comment]
In reviewing the PR, the sorting of the organization should be alphabetical, so it seems this needs to be placed deeper in the E

**Comment by Marcel-D-encoway** [comment]
Your are right, my fold, sorry.
I fixed that.

I am only surprised that the company
https://ecgrobotics.org comes after the company https://www.enalean.com,
where the c stands before the n in the alphabet.
The same with the company https://ellucian.com line 11650

The problem was that I did not scroll down far enough to see the company ecgrobotics.

**Review by dnsguru — CHANGES_REQUESTED** [review]
Is this company part of one.com?  Please confirm, otherwise, would it not go in the E's?

**Comment by dnsguru** [comment]
We merge based upon "all commits" and your revised commit places your section square in the one.com section, which I am not certain was intended.

**Comment by Marcel-D-encoway** [comment]
I'm a bit confused and I think then I don't understand the sorting correctly. I thought the list is sorted by the company name in the comments: 
// En root‽ : https://en-root.org                 
// Enalean SAS: https://www.enalean.com 
// ECG Robotics, Inc: https://ecgrobotics.org
// One.com: https://www.one.com/
// EU.org https://eu.org/

Now I don't understand why one even appears here in the list.
Where should I put our company encoway?

**Comment by sleevi** [comment]
[ICANN lookup](https://lookup.icann.org/) returns

```
Name: encoway.cloud
Registry Domain ID: D66CD9826A79D4FD095C30F8ADE7E7908-NSR
Domain Status:
active

Nameservers:
ns2-05.azure-dns.net
ns3-05.azure-dns.org
ns1-05.azure-dns.com
ns4-05.azure-dns.info

Dates
Registry Expiration: 2022-01-19 12:53:59 UTC
```

**Comment by dnsguru** [comment]
It appears that the domain name was extended to Jan 2023 renewal ; this is short of the 2 year request term.  Please attest that you will keep the domain renewed, understanding that future automation of removals from the PSL may be tied to the expiry date being <1 y or the _PSL dns record not being active may cause unintended and automated removal of this entry.

**Comment by Marcel-D-encoway** [comment]
Hi,

yes unfortunately we can not book the domain longer than this time in advance with our provider.
But I confirm that we as encoway will extend this domain. We are also aware that automatic deletion is associated with it if the expiration date is <1 year.

**Comment by dnsguru** [comment]
> Hi,
> 
> yes unfortunately we can not book the domain longer than this time in advance with our provider. But I confirm that we as encoway will extend this domain. We are also aware that automatic deletion is associated with it if the expiration date is <1 year.

Thank you, that is sufficient.  Please leave in place the _PSL DNS txt record to ensure the entry remains in place for future automation reviews.

**Review by dnsguru — APPROVED** [review]
- DNS TXT Record validated
- Sorted / conforms to guidelines
- Attested to continuous renewal
- No conflict with base
- Tests OK

APPROVED

**Pull request merged**
