### PR TITLE
Adding tuchacloud.com private domain

### PR DESCRIPTION
**Pull request by Lennon114**

### CODE REVIEW

**Comment by Lennon114** [comment]
TuchaCloud is a VPS hosting provider

**Comment by tmm1** [comment]
Are you the owner of this domain? Please verify ownership by adding the required TXT record.

**Comment by Lennon114** [comment]
I'm a representative of the domain owner. This one? 
[record.txt](https://github.com/publicsuffix/list/files/1182456/record.txt)

**Comment by Lennon114** [comment]
Hello, where shold we add the record.txt as the domain owners, and is this file correct? What are the next steps? 

Great Thanks.

 

--

Sincerely,

Dmytro Myslynskyi

Content Manager

TuchaCloud VPS Provider 

+380 44 583-5-583 (EXT. 981)

 <https://tuchacloud.com/> https://tuchacloud.com/

**Pull request closed without merging**
