### PR TITLE
Add `lolipopmc.jp`

### PR DESCRIPTION
**Pull request by takumakume**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://pepabo.com, https://mc.lolipop.jp

`LOLIPOP! Managed Cloud` is a Web Hosting service, provides by GMO Pepabo, inc.
For more information about `LOLIPOP! Managed Cloud` head over to [our website](https://mc.lolipop.jp/)

Reason for PSL Inclusion
====

We provide every app/website on LOLIPOP! Managed Cloud with its own `lolipopmc.jp` subdomain.
We'd like to be included in the list to improve our cookie security.

GMO Pepabo, Inc. has previously added domains for hosting services.

[Add 105 lolipop.io # 881] (https://github.com/publicsuffix/list/pull/881), [Add 105 lolipop and heteml domains to private section for GMO # 1522] (https://github.com/ publicsuffix / list / pull / 1522)

The purpose of this PR is because the `lolipopmc.jp` domain has also been added to the` LOLIPOP! Managed Cloud`, our hosting service.

DNS Verification via dig
=======

```
dig +short TXT _psl.lolipop.jp
"https://github.com/publicsuffix/list/pull/1522"
```

make test
=========

```
% make test-syntax
cd linter;                                \
	  ./pslint_selftest.sh;                     \
	  ./pslint.py ../public_suffix_list.dat;
-n test_NFKC:
OK
-n test_allowedchars:
OK
-n test_dots:
OK
-n test_duplicate:
OK
-n test_exception:
OK
-n test_punycode:
OK
-n test_section1:
OK
-n test_section2:
OK
-n test_section3:
OK
-n test_section4:
OK
-n test_spaces:
OK
-n test_wildcard:
OK
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Kume San, would you please add to the description of the purpose of this
request, and reference the PR number from the first group which GMO Pepabo
submitted for
Lolipop previously.

**Comment by takumakume** [comment]
@dnsguru 
Hi! Thank you for your review.
I have written in detail the purpose of this PR. 
Please check.

```
Reason for PSL Inclusion
====

We provide every app/website on LOLIPOP! Managed Cloud with its own `lolipopmc.jp` subdomain.
We'd like to be included in the list to improve our cookie security.

GMO Pepabo, Inc. has previously added domains for hosting services.

[Add 105 lolipop.io # 881] (https://github.com/publicsuffix/list/pull/881), [Add 105 lolipop and heteml domains to private section for GMO # 1522] (https://github.com/ publicsuffix / list / pull / 1522)

The purpose of this PR is because the `lolipopmc.jp` domain has also been added to the` LOLIPOP! Managed Cloud`, our hosting service.```

**Review by dnsguru — CHANGES_REQUESTED** [review]
Please revise this to place lolipopmc.jp in the correct sorting order

**Comment by takumakume** [comment]
@dnsguru 
Sorted the domains of GMO Pepabo.

**Comment by dnsguru** [comment]
Hi @takumakume 
The sorting needs to be by Top Level Domain (TLD) A-z, then by Second Level Domain (SLD) A-z - it looks like these got sorted by SLD then TLD by accident and not TLD then SLD.

**Comment by takumakume** [comment]
I'm sorry, I made a mistake.
Fix it.
@dnsguru

**Review by dnsguru — APPROVED** [review]
- submitter=revisor
- tests pass
- no conflict with base
- DNS validates

APPROVED

**Pull request merged**
