### PR TITLE
Correcting error in AWS EC2 China domain

### PR DESCRIPTION
**Pull request by pallchin-amzn**
As member of Amazon AWS EC2, revising EC2 portion of list to target correct China domain.

### CODE REVIEW

**Comment by pallchin-amzn** [comment]
Straight forward change to the .cn EC2 compute domain.

**Comment by lawells** [comment]
Confirmed that @pallchin-amzn is an Amazon employee and both commits look good to me. @weppos - any chance you can have a look?

**Comment by weppos** [comment]
Thanks @lawells. I'm currently on a flight. I'll give it a check asap I hope by the next 24 hours.

**Comment by weppos** [comment]
@pallchin-amzn it looks good to me. Please swap

```
compute.amazonaws.com.cn
compute.amazonaws.com
```

into

```
compute.amazonaws.com.cn
compute.amazonaws.com
```

(we generally keep items sorted, using a right-hand sort mechanism). Once that is done, I'll go ahead and merge it right away.

**Comment by pallchin-amzn** [comment]
Applied sorting corrections.

**Comment by weppos** [comment]
Merged!

**Pull request merged**
