### PR TITLE
Add `{id,io,ai}.vn` for .vn ccTLD in ICANN Section

### PR DESCRIPTION
**Pull request by BadAimWeeb**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Vietnam Internet Network Information Center (VNNIC) is an affiliation to the Ministry of Information and Communications, founded on 28th April 2000, and carries out the functions of managing, allocating, supervising and promoting the use of Internet domain name, address (IP), Autonomous System Number (ASN) in Vietnam (collectively called as “Internet resources”); providing Internet-related guidance, statistics on Internet; joining international activities on Internet. VNNIC owns and controls over .vn ccTLD.

I do not have connection with VNNIC, I'm just making changes to PSL to update according to new changes.

Organization Website: https://www.vnnic.vn/

Reason for PSL Inclusion
====

On June 1st 2023, VNNIC opened up three new suffix, which are:
- ID.VN: For individuals who are Vietnamese citizens to register to use personal images, products and personal brands in the online environment
- IO.VN: For organizations and individuals that register to use technology applications, platforms and services in the network environment
- AI.VN: For organizations and individuals that register to use for activities and services related to the field of artificial intelligence

This change is reflected by the inclusion of these three new suffix in https://www.vnnic.vn/en/domain/cctld-vn.

Number of users this request is being made to serve: Unlimited

DNS Verification via dig
=======

Test omitted as I do not have control over that.

Results of Syntax Checker (`make test`)
=========

```
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-public-builtin.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Thank you for taling time and submitting this.

There is a change needed.

One can follow from the IANA website to the respective .vn page, which shows [vnnic.vn](http://vnnic.vn/) as the registration authority.

One can find the registration policies page on [vnnic.vn](http://vnnic.vn/) that confirm these three extensions.

Through that method of publicly available top-down validation, the requirement the typical DNS TXT verification can be considered satisfied.

*What needs to be fixed:*
There is a matter of sorting the second level .vn sub-space in a-z alphabetical order that needs fixing so this PR can be compliant with the submission guidelines.

Current:
```
vn
com.vn
net.vn
org.vn
edu.vn
gov.vn
int.vn
ac.vn
biz.vn
info.vn
name.vn
pro.vn
health.vn
```

This should be re-organized:
```
vn
ac.vn
ai.vn
biz.vn
com.vn
edu.vn
gov.vn
health.vn
id.vn
info.vn
int.vn
io.vn
name.vn
net.vn
org.vn
pro.vn
```

Can you modify the submission to correctly sort the .vn namespace please?

**Comment by BadAimWeeb** [comment]
Sorry for that, I modified the order as you requested, because I was quite confused about old sorting value so I didn't sort properly.

**Comment by iamncdai** [comment]
Hi @dnsguru , can you accept this pull request soon? Thanks.

**Comment by timhangnhanh** [comment]
Hi @dnsguru, I'm sure there are 100 million people waiting for this PR to be merged!
Thank you so much!

**Comment by iamncdai** [comment]
Hi @dnsguru,

I'm sure there are 100 million people waiting for this PR to be merged!

Thanks.

**Comment by dnsguru** [comment]
Due to the mass impact indicated by two posters, we will need to have the _PSL txt entries added to these zones in order validate this request.

**Comment by BadAimWeeb** [comment]
> Due to the mass impact indicated by two posters, we will need to have the _PSL txt entries added to these zones in order validate this request.

This is not possible. Isn't public source enough for authentication according to guidelines?

The mass impact indicated by two posters is that VNNIC allows Vietnamese citizens to register .id.vn with a really low registration fee (even free for people in the age range of 18-22, this including me, otherwise just around ~3USD/year).

**Comment by haha0205** [comment]
@dnsguru Are there any things that should be completed left ?

**Comment by iamncdai** [comment]
Hi @dnsguru ,

This is the list of domain names of Vietnam as announced by **VNNIC** **(VIETNAM INTERNET NETWORK INFORMATION CENTER)** on the official website. I think it helps a bit.

**Country-code top level domain name (ccTLD .VN)**
[https://www.vnnic.vn/en/domain/cctld-vn](https://www.vnnic.vn/en/domain/cctld-vn)

Thanks.

**Comment by rinihome** [comment]
Hi @dnsguru

Please support this case. Domain names id.vn, io.vn, ai.vn are granted to the entire population at a low cost for the purpose of digitizing citizens.

Thank you.

**Comment by dnsguru** [comment]
There's a stack of other requests ahead of this, and I am an unpaid volunteer here - please stop w the "encouragement"

**Comment by trinv** [comment]
Hi @dnsguru 
I really appreciate what you and the PSL team are doing for us and the Internet. 
Could you please please check & validate this request !
Thanks & Best regards,
Tri Nguyen

`_psl.ai.vn.             TXT     "https://github.com/publicsuffix/list/pull/1771"`
`_psl.id.vn.             TXT     "https://github.com/publicsuffix/list/pull/1771"`
`_psl.io.vn.             TXT     "https://github.com/publicsuffix/list/pull/1771"`

**Comment by tuan1996qn** [comment]
@trinv Thank you for adding TXT records
@BadAimWeeb please update checklist

**Comment by dnsguru** [comment]
> @trinv Thank you for adding TXT records 

Yes, this helped me proceed.  Spamming the pull request with cheap entries was causing more review friction to be needed

>@BadAimWeeb please update checklist

I took care of this

**Review by dnsguru — APPROVED** [review]
* DNS validated
* Tests Pass
* No Conflict
* IANA db->registry confirmed

Approved

(Expedited as this is IANA/ICANN section change)

**Comment by dnsguru** [comment]
Also, thank you for ordering the subdomains according to the guidelines

**Comment by trinv** [comment]
Thank you so much @dnsguru

**Pull request merged**
