### PR TITLE
Adding musica.ar SLD - https://nic.ar/Enterate/Noticias/registra-tu-d…

### PR DESCRIPTION
**Pull request by matiasvillanueva**
…ominio-musica-ar

For more information, please visiti nic.ar site

https://nic.ar/Enterate/Noticias/registra-tu-dominio-musica-ar

Thanks

### CODE REVIEW

**Comment by matiasvillanueva** [comment]
https://nic.ar/nic-argentina/normativa-vigente

**Comment by sleevi** [comment]
Are you the registrar? Per our [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), we only accept requests from the domain holder

**Comment by matiasvillanueva** [comment]
Hi!

I do not understand you question, sorry.
I do not work for nic.ar, I just want to contribute to the project.
The musica.ar SDL is documented at https://nic.ar/nic-argentina/normativa-vigente and there are domains registed (Ex: coda.musica.ar, karaokeando.musica.ar, midi9.musica.ar), it should be in the list.
I have done other contributions to the list before, only for ICANN domanis, not private(https://github.com/publicsuffix/list/pull/42) without been the domain holder.
Maybe you can verify this new SLD.

Best regards.-

**Comment by weppos** [comment]
@sleevi it looks like musica.ar is managed by the nic, and it's an official subzone.
https://nic.ar/nic-argentina/normativa-vigente

I updated the list to remove the suffixes not officially supported. Unless you have any objection, I'm 👍  to merge.

**Comment by matiasvillanueva** [comment]
@sleevi @weppos removing edu.ar not correct.

As you can read in this article (https://nic.ar/nic-argentina/nuestros-dominios - I could not find it in English ) Edu.ar SDLs are managed by ARIU (Asociación de Redes de Interconexión Universitaria - Association of University Interconnection Networks), but belongs to NIC. That is why you do not see it in https://nic.ar/nic-argentina/normativa-vigente.

There are lots of domains registed:
http://www.unr.edu.ar
https://www.uai.edu.ar

Maybe you can email nic.ar to get more info.

Regards.

**Pull request merged**
