### PR TITLE
add missing IDN ccTLDs:  for Bahrain and Laos ( .xn--mgbcpq6gpa1a and .xn--q7ce6a )

### LINKED ISSUE #1174: Handling EBERO TLDs (ex: .wed)
The list seems to be missing 3 valid TLDs, which are included on IANA.org: https://data.iana.org/TLD/tlds-alpha-by-domain.txt

Namely:
* .wed
* .xn--q7ce6a (and equivalent .ລາວ)
* .xn--mgbcpq6gpa1a (and equivalent .البحرين)

### PR DESCRIPTION
**Pull request by martimlobao**
* [ ] Description of Organization
* [X] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====
* .wed is a valid TLD since 2013: https://www.icann.org/resources/agreement/wed-2013-10-01-en
* .البحرين [.xn--mgbcpq6gpa1a] is a valid TLD for "albahrain": https://www.iana.org/reports/2020/xn--mgbcpq6gpa1a-report-20200110.html
* .ລາວ [.xn--q7ce6a] is a valid TLD for "Lao": https://www.iana.org/reports/2020/xn--q7ce6a-report-20200110.html
* .za is a valid TLD and the only one in this list of ICANN domains that is not included without any subdomain (even other TLDs which are typically only issued with a secondary domain like .uk are included as a standalone TLD)

DNS Verification via dig
=======

make test
=========
I'm unable to run the tests locally, I keep getting an error with `libicu` that I haven't been able to fix. If anyone wants to double-check that the tests don't fail, I'd appreciate it.

Fixes #1174

### CODE REVIEW

**Comment by dnsguru** [comment]
Thank you for the submission.  Can this be split into three distinct PR, or could you revise this request to remove ZA and WED from this PR?

The .wed TLD was cancelled and returned to ICANN by the applicant so it is no longer in the root zone, and thus deliberately absent from the list
.ZA would need to be submitted by the ZADNA and validated by them, as their absence may be deliberate for the TLD at the top level due to allocation policies or rules that they have for allowing or disallowing second level registrations.

 The two IDN ccTLDs for Bahrain and Laos could be included, but we're going to loop in the registry back end that technically operates these for comment (in this case, @gbxyz Centralnic) to identify that these were overlooked and need addition, or were deliberately excluded from being listed.

**Comment by martimlobao** [comment]
Thanks, I'd be happy to update this PR and drop .WED and .ZA.

Regarding .WED though, it looks like there are still live websites that use the .web TLD, such as [get.wed](http://get.wed/), [atgron.wed](https://www.atgron.wed/), and even [may27.wed](https://may27.wed/) despite it being listed as terminated in the [ICANN gTLD file](https://www.icann.org/resources/registries/gtlds/v2/gtlds.json) you linked. No other terminated TLD seems to have any active website listed on Google, which seems to make .wed unique in that regard. ICANN also currently lists .wed in this other [list of TLDs](https://data.iana.org/TLD/tlds-alpha-by-domain.txt), as well as in the [Root Zone Database](https://www.iana.org/domains/root/db) as being managed by them, but doesn't do so for any other terminated TLD (e.g. .zippo or .aigo).

Since .WED appears to (currently) be live and in use, would it make sense to still include it?

**Comment by dnsguru** [comment]
Pardon my binary thinking on the .WED TLD's inclusion or not.  Your comment was very lucid and carrried some important facts.  I have reconsidered on .WED being a closed matter, but believe it should be split off from this into its own PR to discuss...  Would  you split that into a separate PR so we can discuss that separately from the two IDN @martimlobao ?

 I think you've raised a fair and lucid point with respect to the existing .WED registrations and the existence of the TLD in the IANA TLD list.  The .WED TLD did have its contract terminated but that is a different matter entirely to if there are registrants with domains inside the zone.  For such circumstances, ICANN have in place measures for maintaining existing registrations for a period of time, so that should there be a TLD that has a business or other failure there is continuity for existing registrants.

**Comment by martimlobao** [comment]
Thanks for the changes to the PR. I added #1176 to continue the discussion on .wed.

**Comment by gbxyz** [comment]
Please can this merge request be closed? I have contacted the relevant authorities to obtain their authorisation and will submit separate merge requests for them once this authorisation has been received.

Thanks.

**Comment by gbxyz** [comment]
> Please can this merge request be closed? I have contacted the relevant authorities to obtain their authorisation and will submit separate merge requests for them once this authorisation has been received.
> 
> Thanks.

Scratch that - there's no reason for this MR to be closed. When we have the authorisations we need we'll add the DNS entries to point to this MR, and I'll add a comment when this has been done.

**Comment by dnsguru** [comment]
Hi and Happy New Year Gavin

Will leave open - and if you get an affirmative response from one or the
other, splitting up the PR into two separate ones may be wise.  Let's see
what the universe brings us, and thank you for following up on this!

-J

**Comment by gbxyz** [comment]
Lao National Internet Center (LANIC, the sponsoring organisation of .ລາວ) have asked that the following second-level domains be added to the PSL in addition to the TLD. Can this merge request be updated to include them, or should I submit a new MR?

```
xn--86cejd6cudem.xn--q7ce6a
xn--86cl7au9aq7o.xn--q7ce6a
xn--p6c5fb6ar.xn--q7ce6a
xn--p6cl9c0d1a5c.xn--q7ce6a
xn--q6cd2a1j0a1a5d8c.xn--q7ce6a
xn--p6c2c6b6a8b.xn--q7ce6a
xn--p6c2bh0dvczay.xn--q7ce6a
xn--q6c0cxa0h8cxa.xn--q7ce6a
xn--c7ce7ctal.xn--q7ce6a
```

The U-labels for the above A-labels are:

```
ລັດຖະບານ.ລາວ ("government.lao")
ບໍລິສັດ.ລາວ ("company.lao")
ສຶກສາ.ລາວ ("education.lao")
ອົງການ.ລາວ ("organization.lao")
ເຄືອຂ່າຍ.ລາວ ("network.lao")
ສາກົນ.ລາວ ("international.lao")
ທຸລະກິດ.ລາວ ("business.lao")
ຂໍ້ມູນ.ລາວ ("information.lao")
ທະຫານ.ລາວ ("military.lao")
```

**Comment by dnsguru** [comment]
Gavin that is a very thorough response for the Laotian IDNccTLD

Thank you for the outreach on this..   Can you open a new pr and add all of
those in the location that the .xn--q7ce6a

The entries would be in their u-label forms, but it may be helpful (but not
necessary)  to put their English meaning and a-label commented above each
(similar to the header for the TLD).  The comment lines are helpful to
non-Laotian speakers, but this is "nice to have" vs required

Sub-entries should be sorted by subdomain in ascending order.

-Jothan

On Wed, Jan 20, 2021, 1:28 AM Gavin Brown <notifications@github.com> wrote:

> Lao National Internet Center (LANIC, the sponsoring organisation of .ລາວ)
> have asked that the following second-level domains be added to the PSL in
> addition to the TLD. Can this merge request be updated to include them, or
> should I submit a new MR?
>
ລັດຖະບານ.ລາວ

//"government.lao" xn--86cejd6cudem.xn--q7ce6a

**Comment by gbxyz** [comment]
Hi Jothan - I will submit a new request for the SLDs in due course.

In the meantime, TXT records have been published at `_psl.البحرين` and `_psl.ລາວ` which reference this PR:

```
$ dig +noall +answer TXT _psl.xn--mgbcpq6gpa1a
_psl.xn--mgbcpq6gpa1a.	825	IN	TXT	"https://github.com/publicsuffix/list/pull/1175"

$ dig +noall +answer TXT _psl.xn--q7ce6a      
_psl.xn--q7ce6a.	830	IN	TXT	"https://github.com/publicsuffix/list/pull/1175"
```

**Review by dnsguru — APPROVED** [review]
- DNS Delegation Validated via DNS TXT records
- Rationale Correct and Accurate
- Administrative Verification through review of PSL Txt leaf entries matching PR number
- Tests pass
- No Conflict with Base.

**APPROVED**

**Comment by dnsguru** [comment]
.DESI is moving to EBERO
https://www.icann.org/en/announcements/details/desi-to-be-placed-in-the-emergency-back-end-registry-operator-program-16-10-2023-en

**Pull request merged**
