### PR TITLE
Add `l.tunwg.com`

### PR DESCRIPTION
**Pull request by ntnj**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [*] Description of Organization
* [*] Robust Reason for PSL Inclusion
* [*] DNS verification via dig
* [*] Run Syntax Checker (make test)

* [*] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [*] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [*] This request was _not_ submitted with the objective of working around other third-party limits

  * [*] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [*] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [*] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
tunwg is an open source tool which will allow users to setup tunneling to their locally running http servers. There is a free instance hosted at tunwg.com, but allows users to self host their instance.
tunwg server proxies https tcp traffic over wireguard to the end user by using the SNI from incoming https server, and doesn't decrypt https traffic. 
Each client connected to tunwg server gets an encoded subdomain at tunwg.com. The server itself has no state, and all information about wireguard public key is encoded in the sub domain. It provides a similar functionality to ngrok except it's end to end encrypted.

Organization Website: https://tunwg.com

Reason for PSL Inclusion
====
Users using the tunwg tool to tunnel get an encoded subdomain for each host and forwarded destination pair. It provides similar functionality to ngrok.
Having the domain in PSL will provide cookie security as subdomains are controlled by users of the tool. 
It'll also allow more users to use the tool, since each machine:port pair generates a new subdomain, and allow them to issue SSL certificates. Wildcard certificates can't be used as the traffic is end to end encrypted, and server just forwards the TCP stream to clients.
Since each HTTPS certificate is persisted to local disk, and each subdomain represents a different service, this won't abuse LetsEncrypt certificate issuance limits, as the subdomain remains constant for a service even if the host machine is restarted.

Number of users this request is being made to serve: 100-1000
This is an estimate, as the service doesn't collect any metrics or do any logging.

DNS Verification via dig
=======
dig +short TXT _psl.l.tunwg.com 
"https://github.com/publicsuffix/list/pull/1734"

Results of Syntax Checker (`make test`)
=========
Getting an error, but it's broken on HEAD too.
```
configure.ac:67: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:92: error: possibly undefined macro: AC_LINK_IFELSE
configure.ac:93: error: possibly undefined macro: AC_LANG_PROGRAM
configure.ac:196: error: possibly undefined macro: AC_SEARCH_LIBS
configure.ac:225: error: possibly undefined macro: AC_MSG_CHECKING
configure.ac:230: error: possibly undefined macro: AC_MSG_RESULT
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
make: *** [Makefile:18: libpsl-config] Error 1
```

### CODE REVIEW

**Comment by ntnj** [comment]
I've updated the domain in pull request to `l.tunwg.com` instead e.g. https://d6lq7niz3keamhjp.l.tunwg.com or https://d6lq7niz3keam27n.l.tunwg.com

**Comment by simon-friedberger** [comment]
@ntnj Is this obsolete?

**Comment by ntnj** [comment]
It's still relevant, but since the tool is open source and has no analytics, I don't any data on how many people are using it. It has around 150 stars on github though. Not sure if that's sufficient for inclusing in PSL.  
Since all users of the tool get an encoded subdomain on `l.tunwg.com`, it'll still be beneficial.

**Comment by dnsguru** [comment]
We typically are looking at multiple thousands, tens of thousands, or some presence on majestic/umbrella to qualify out of respect for keeping file bloat modest

**Comment by simon-friedberger** [comment]
Since connections are based on public keys, can you at please provide the average number of keys which are using a tunnel per day?

**Pull request closed without merging**
