### PR TITLE
Added *.0emm.com to Google's list

### PR DESCRIPTION
**Pull request by scottwug**
Hi Eduardo (@sirdarckcat),
This is Scott Wu from Google. I'm working with Han on the 0emm.com stuff.
Could you help to approve the pull request?
Please let me know if there is any problem.

Thank you very much!
Scott Wu

### CODE REVIEW

**Comment by weppos** [comment]
@sleevi do you want to take care of this?

**Comment by sirdarckcat** [comment]
This looks good from security team's pov :)

**Comment by sleevi** [comment]
Confirming that 0emm.com is operated by Google ( dns-admin@google.com ) and the correct party (in this case, @sirdarckcat , has signed off)

Because it's three commits, I'm going to try to figure out GitHub's squash support ( https://github.com/blog/2141-squash-your-commits ) before merging.

**Comment by marc-etienne** [comment]
Hi @scottwug ,

May I ask what the domain is used for? I couldn't find any information from Google about the usage of 0emm.com of any of the [associated domains that look generated](https://crt.sh/?q=07e1694e307d7be82837b52455c19c42986e8ebff2c8a3d910d6e0a973f63240).

Thanks!

**Pull request merged**
