### PR TITLE
add torproject.net

### PR DESCRIPTION
**Pull request by anarcat**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://torproject.org/

I'm the senior sysadmin at the Tor Project, Inc. (proof at [the people page as well](https://www.torproject.org/about/people/)) empowered to represent the interests of the company (and the project) insofar as technical resources like DNS are concerned. 

Reason for PSL Inclusion
====

The torproject.org domain is the main domain used by the Tor
Project. All machines under that domain are managed by the TPA
team (Tor Project sysAdmins).

The torproject.net domain, however, can be delegated to third parties
and is less trusted.

This is the same policy as the `debian.net` domain.

We will possibly start hosting "GitLab pages" under the
pages.torproject.net domain.

The goal of those changes is to make it more difficult to operate
cross-site scripting attacks by setting cookies across that those
domains.

DNS Verification via dig
=======

```
$ dig +short TXT _psl.torproject.net
"https://github.com/publicsuffix/list/pull/1196"
$ dig +short TXT _psl.pages.torproject.net
"https://github.com/publicsuffix/list/pull/1196"
```

make test
=========

Output of `make test`: https://paste.anarc.at/publish/2021-01-27-j5kfz4GOKxeW_Nvr0Nv1p8eSOolo52QlYU0Uv2q_kow/stdin.txt

### CODE REVIEW

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Comment by dnsguru** [comment]
@anarcat this was just merged.  Should start to trickle out - recommend monitoring to ensure this resulted in the expected way and if you need to modify the entry, create another PR and please reference this PR

**Comment by anarcat** [comment]
thanks, @dnsguru  - how long does that actually take to trickle out? any recommendations for the monitoring? :)

**Comment by dnsguru** [comment]
It is up to those who download and what they then do, not us.

**Comment by anarcat** [comment]
yeah, i realize that but i figured you might have a hint of an idea. ;) thanks in any case, for the fast response! :)

**Comment by sleevi** [comment]
Six months to three years.

**Comment by simon-friedberger** [comment]
@anarcat Are you still using this or can we roll it back?

**Comment by anarcat** [comment]
we are still using this, are those entries supposed to expire after 3 and a half years? :)

**Pull request merged**
