### PR TITLE
Add realm.cz to private section

### PR DESCRIPTION
**Pull request by aleshaczech**

### CODE REVIEW

**Comment by aleshaczech** [comment]
Please add this domain to the PSL. I have just added the TXT record for verification, it might take a couple of minutes to propagate:

    $ dig -t txt +short psl.realm.cz
    "https://github.com/publicsuffix/list/pull/172"

**Comment by weppos** [comment]
Please add the entry in the appropriate order. Also note that the record should be `_psl`.
https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by aleshaczech** [comment]
@weppos Both issues resolved & rebased against master.

**Comment by aleshaczech** [comment]
@weppos Thanks!

**Pull request merged**
