### PR TITLE
Removal of `blog.kg` from private section

### PR DESCRIPTION
**Pull request by berkaycagir**
I would like to remove my domain `blog.kg` from PSL (related: #1753).

Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

I am acting on my own behalf as an individual.

Organization Website: N/A

Reason for PSL Inclusion
====

N/A, I would like to remove my domain from PSL.

Number of users this request is being made to serve: N/A

DNS Verification via dig
=======

```
$ dig +short TXT _psl.blog.kg
"https://github.com/publicsuffix/list/pull/1840"
```

Results of Syntax Checker (`make test`)
=========

```
$ make test
cd linter;                                \
	  ./pslint_selftest.sh;                     \
	  ./pslint.py ../public_suffix_list.dat;
-n test_NFKC:
OK
-n test_allowedchars:
OK
-n test_dots:
OK
-n test_duplicate:
OK
-n test_exception:
OK
-n test_punycode:
OK
-n test_section1:
OK
-n test_section2:
OK
-n test_section3:
OK
-n test_section4:
OK
-n test_spaces:
OK
-n test_wildcard:
OK
test -d libpsl || git clone --depth=1 https://github.com/rockdaboot/libpsl;   \
	  cd libpsl;                                                                    \
	  git pull;                                                                     \
	  echo "EXTRA_DIST =" >  gtk-doc.make;                                          \
	  echo "CLEANFILES =" >> gtk-doc.make;                                          \
	  autoreconf --install --force --symlink;
Already up to date.
autopoint: using AM_GNU_GETTEXT_REQUIRE_VERSION instead of AM_GNU_GETTEXT_VERSION
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: linking file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: linking file 'm4/libtool.m4'
glibtoolize: linking file 'm4/ltoptions.m4'
glibtoolize: linking file 'm4/ltsugar.m4'
glibtoolize: linking file 'm4/ltversion.m4'
glibtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
aclocal.m4:765: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:383: warning: file `version.txt' included several times
configure.ac:10: installing 'build-aux/compile'
configure.ac:4: installing 'build-aux/missing'
fuzz/Makefile.am: installing 'build-aux/depcomp'
cd libpsl && ./configure -q -C --enable-runtime=libicu --enable-builtin=libicu --with-psl-file=/Users/berkay/GitHub/public-suffix-list/public_suffix_list.dat --with-psl-testfile=/Users/berkay/GitHub/public-suffix-list/tests/tests.txt && make -s clean && make -s check -j4
configure: WARNING: --enable-builtin=libicu is deprecated, use --enable-builtin (enabled by default)
config.status: creating po/POTFILES
config.status: creating po/Makefile
Making clean in po
Making clean in include
Making clean in src
rm -f ./so_locations
Making clean in tools
 rm -f psl
Making clean in fuzz
 rm -f libpsl_icu_fuzzer libpsl_icu_load_fuzzer libpsl_icu_load_dafsa_fuzzer
Making clean in tests
 rm -f test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain
Making clean in msvc
Making check in po
Making check in include
Making check in src
  CC       libpsl_la-lookup_string_in_fixed_set.lo
  CC       libpsl_la-psl.lo
  CCLD     libpsl.la
Making check in tools
  CC       psl.o
  CCLD     psl
Making check in fuzz
  CC       libpsl_fuzzer.o
  CC       main.o
  CC       libpsl_load_fuzzer.o
  CC       libpsl_load_dafsa_fuzzer.o
  CCLD     libpsl_icu_fuzzer
  CCLD     libpsl_icu_load_fuzzer
  CCLD     libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-all.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
libtool: warning: '-no-install' is ignored for x86_64-apple-darwin22.6.0
libtool: warning: '-no-install' is ignored for x86_64-apple-darwin22.6.0
libtool: warning: assuming '-no-fast-install' instead
libtool: warning: assuming '-no-fast-install' instead
libtool: warning: '-no-install' is ignored for x86_64-apple-darwin22.6.0
libtool: warning: '-no-install' is ignored for x86_64-apple-darwin22.6.0
libtool: warning: assuming '-no-fast-install' instead
libtool: warning: assuming '-no-fast-install' instead
  CCLD     test-registrable-domain
libtool: warning: '-no-install' is ignored for x86_64-apple-darwin22.6.0
libtool: warning: assuming '-no-fast-install' instead
PASS: test-is-public-builtin
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-all
PASS: test-is-public
PASS: test-registrable-domain
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Running the unit tests on this - it appears that you'll need to make this change against a new snapshot of the PSL - you can open a new PR with a fresh branch and reference this PR, or you can update the base used.  Can't walk you through the second option

**Comment by dnsguru** [comment]
OK looks like that's sorted out

**Comment by berkaycagir** [comment]
Yep, I had just rebased the branch today. Do I need to do anything else?

**Comment by dnsguru** [comment]
```
dig +short TXT _psl.blog.kg @8.8.8.8
"https://github.com/publicsuffix/list/pull/1840"
```

**Comment by dnsguru** [comment]
This is taking a lot of time as it is tangled up (not unlike a string of holiday lights) with a ton of other PR #953 #1014 #1656 #1753 #1741 in what I can only technically describe as a hot, fugly mess left by the ghosted github accounts that set up neko.am and voxel.sh.

**Comment by berkaycagir** [comment]
☹️ Do you plan/wish to delete all of the affected entries in a single merge?

**Comment by dnsguru** [comment]
Working this out with the volunteers - would love to just delete all these but want to make sure there is no 'friendly fire' scenarios that occur unintentionally from pulling the entirety of them.

Your individual domain name and not having you held up in the whole batch dialog is part of the discussion.

I also created #1866 about this

**Comment by dnsguru** [comment]
it took a lot of review to ensure low impact, which required reviewing all impacted domains for each of the inter-connected pull requests, one by one.  

The current plan is to process #1741 and #1755 which will solve your issue, but we need the author of #1755 to update theirs, perhaps you can nudge them?

**Comment by berkaycagir** [comment]
Thanks a lot for letting me know.

I checked #1755 but that domain doesn't satisfy the registration duration requirement anyway, is there any point in trying to get the author to update it? In fact it never satisfied that requirement, and on their website it's not listed as a service as well, so I have a fair guess of that PR (and the domain as well) dying down.

**Comment by berkaycagir** [comment]
I dug deeper into #1755 a bit more and it gets weirder. While https://nic.us.kg exists, it's not managed by the author's non-profit but an alleged company called EdgeAlpha Ltd: https://nic.us.kg/terms-of-service/

Almost the same thing was mentioned before in the PR, but with an entirely different alleged company name. The author acknowledged this but didn't do any changes in their PR, which poses yet another issue on top of the registration duration requirement.

At this point it feels like a child's play to me, does it really make sense to hold all the other invalid entries just because of this? ☹️

**Comment by dnsguru** [comment]
fair point.  will review more when additional volunteer cycles are available again

**Review by dnsguru — APPROVED** [review]
* Sorted to Guidelines
* DNS TXT = Pull Request URL
* Tests Pass
* No conflict with base

APPROVED

**Comment by berkaycagir** [comment]
Thank you!

**Pull request merged**
