### PR TITLE
New policy for .museum, without all the SLD (Second-Level Domains)

### PR DESCRIPTION
**Pull request by bortzmeyer**
Public Suffix List (PSL) Pull Request (PR) 
====

### Checklist of required steps

* [ X] Description of Organization
* [X ] Robust Reason for PSL Inclusion
* [X] DNS verification via dig
* [ X] Run Syntax Checker (make test)

* [ X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [X ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [X ] This request was _not_ submitted with the objective of working around other third-party limits

  * [ X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

 * [ X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

[Afnic](https://www.afnic.fr/) is the technical operator for the .museum TLD. This pull request is done in accordance with the registry

Organization Website: 

https://www.afnic.fr/

Reason for PSL Inclusion
====
The current listing of .museum SLD (Second-Level Domains) reflects an old organisation of the TLD. Nowadays, .museum is a "regular" TLD, where everything is done directly under the TLD.

Number of users this request is being made to serve:
?

DNS Verification via dig
=======

Not done yet since I don't yet know the number of the PR.

Results of Syntax Checker (`make test`)
=========

```
Making check in tests
  CC       test-is-public-builtin.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Review by dnsguru — APPROVED** [review]
Thank you, @bortzmeyer - I appreciate that you responded to this request from the volunteers here.
This PR addresses some or all of #1563 and the following is for records as to why this was approved and merged so promptly.
IANA contact for .museum https://www.iana.org/domains/root/db/museum.html lists https://about.museum as the registry authority, which redirects to welcome.museum, the furnished domain in the commenting.  The urls related to registration policy in the commented line sufficiently describe the changes in .museum namespace that affect/alter the previously defined entities.

* Trusted source, by following chain from root delegation
* conforms to guidelines
* no conflict with base
* tests pass

Additionally, the submitter is a known, highly respected, long-term participant in the operation of secure and trusted namespace for afnic.fr, who are the providers of the registry service for .museum.

**Comment by dnsguru** [comment]
@bortzmeyer if there is a .museum registrant that was adversely impacted by this pull request being merged, they should be directed to submit a pull request for their name in the #PRIVATE section of the PSL and reference this PR within it, so they can be re-added to the PSL.

**Comment by bortzmeyer** [comment]
Thanks. Any idea on the delay before it is published on https://publicsuffix.org/list/public_suffix_list.dat ?

**Comment by dnsguru** [comment]
I opened an issue on this, because mozilla recently migrated cloud
providers, but I believe that generally there is approximately a 24h cycle,
run oncendaily, on the update moving to the cdn and publicsuffix.org from
the most recent github version (if updated)

**Comment by bortzmeyer** [comment]
Indeed, the file is now updated, thanks.

**Comment by bortzmeyer** [comment]
On Wed, Apr 05, 2023 at 08:50:17AM -0700,
 Jothan Frakes ***@***.***> wrote 
 a message of 111 lines which said:

> Would you kindly take a moment and review the list is accurate in the
> #ICANN section other gTLD/ccTLDs which Afnic maintains?

Done. There are only changes in the URLs of reference documents, see
PR #1732.

**Pull request merged**
