### PR TITLE
Add activo domains: 6r.cz, 6s.cz, e-shop.cz

### PR DESCRIPTION
**Pull request by kraja**
Domains: 6r.cz, 6s.cz, e-shop.cz

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS Verification via dig
* [x] make test

Description of Organization
====
activo systems s.r.o. (known as UPLINK.CZ) is stable Czech Republic webhosting/serverhosting provider since 2008, member of Fiber Telecom (Ltd) group. 

Reason for PSL Inclusion
====
We provide for our clients domains for their vps/hostings to testing and temporary usage. We now working on public dyndns service and free-hosting on short domains 6r.cz, 6s.cz and subdomains registrar on e-shop.cz domain, for ecommerce business, where we need have option to delegate NS records for other webhosting companies to use "our" subdomain hosting everywhere.

DNS Verification via dig
=======
```
# dig +short TXT _psl.6r.cz
"https://github.com/publicsuffix/list/pull/734"

# dig +short TXT _psl.6s.cz
"https://github.com/publicsuffix/list/pull/734"

# dig +short TXT _psl.e-shop.cz
"https://github.com/publicsuffix/list/pull/734"
```

make test
=========
`make test` completed successfully.

### CODE REVIEW

**Comment by frju365** [comment]
Befaire we could review this PR, Can you rebase your PR on master branch ? Because there are too much commit now.

**Comment by kraja** [comment]
> 
> 
> Before we could review this PR, Can you rebase your PR on master branch ? Because there are too much commit now.

Sorry, i dont understand where is problem, or what you want now from me, sorry. Please specify me.

**Comment by kozmagabor** [comment]
Hi @kraja,

It will help you.

## Sync’ing a GitHub Fork via the Command Line

### Cloning Fork Locally

`git clone git@github.com:kraja/list.git`

### Adding the Original Repo as an upstream remote

`git remote add upstream git@github.com:publicsuffix/list.git`

### To update your local repo to the original upstream repo – run
`git fetch upstream`

### To make sure then you are in your correct branch ... 
`git checkout master`

### To reset to your commit
`git reset 9dc69fd6d1e16e6e75d1eb749e7edab22149c0e8`

### To rebase your branch with the upstream repo branch, run…
`git rebase upstream/master`

### Finally push the changes to the GitHub repo fork
`git push origin master -f`

Best regards,
Gabo

**Comment by sleevi** [comment]
Closing this as an invalid PR (as shown from the editor)

**Pull request closed without merging**
