### PR TITLE
feat: Add pro.typeform.com to PSL

### PR DESCRIPTION
**Pull request by mumpo**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://www.typeform.com/

I'm Sergi Ferriz, a Software Engineer at Typeform.

Typeform is a SaaS company that gives users tools for creating forms and surveys that are friendly to answer with one question at a time – like a conversation.

Reason for PSL Inclusion
====

Typeform is in the process of developing a new feature: "Landing Page Builder". This feature will enable Pro users to create their own landing pages before sending respondents to the actual forms.

We need to include "pro.typeform.com" to provide an isolated and secure space for every landing page cookies and make clear that each landing page belongs to a different user.

DNS Verification via dig
=======

```
dig +short TXT _psl.pro.typeform.com
"https://github.com/publicsuffix/list/pull/XXXX"
```

make test
=========

The tests have been ran and they passed.

### CODE REVIEW

**Comment by beldar** [comment]
@dnsguru @sleevi hi there 👋  this has been sitting in draft for a while, I was wondering if you guys can check if we're missing something or we can move forward.

**Comment by dnsguru** [comment]
```
nslookup -type=txt _psl.pro.typeform.com 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.pro.typeform.com   text =

        "https://github.com/publicsuffix/list/pull/1457"
```

DNS Verifies

**Review by dnsguru — APPROVED** [review]
- DNS Validates
- Follows Sorting
- No Conflict With Base
- Tests Pass

Approved

**Comment by dnsguru** [comment]
@mumpo this project is maintained by unpaid volunteers who contribute their time, which means that things can take a while.

Approved and Merging

**Pull request merged**
