### PR TITLE
Add Balena.io device domains

### PR DESCRIPTION
**Pull request by brownjohnf**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Make test

Description of Organization
====

Organization Website: https://www.balena.io

Balena is a fleet-management product for IoT devices. 

Reason for PSL Inclusion
====

We have a cloud platform that has the capability of exposing ports on devices via a proxy managed by us, hosted on the domains below. We'd like to ensure isolation for security purposes.

DNS Verification via dig
=======

```
dig +short TXT _psl.balena-devices.com
"https://github.com/publicsuffix/list/pull/717"
```

```
dig +short TXT _psl.balena-staging-devices.com
"https://github.com/publicsuffix/list/pull/717"
```

### CODE REVIEW

**Comment by brownjohnf** [comment]
cc @pimterry, since you handled this last time.

**Comment by brownjohnf** [comment]
This should be ready for merge, as far as I'm aware. Thanks!

**Comment by weppos** [comment]
@brownjohnf apologize for the delay. I've updated the Guidelines to clarify it
https://github.com/publicsuffix/list/wiki/Guidelines

You should order the changeset based on the company/product name, in your case `Balena`.

Your changeset is currently placed between `Resin.io` and `RethinkDB`, but `Balena` alphabetically precedes `Resin.io`.

**Comment by aengelas** [comment]
I'm no longer with Balena, but I'll ping someone who will be able to move this forward.

@petrosagg Sorry about the long delay on this, but I missed the notification email. Someone should probably follow up with this, if it's still relevant to Balena.

**Comment by brownjohnf** [comment]
Whoops, wrong account, but that message above is from me :-)

**Comment by petrosagg** [comment]
@weppos @brownjohnf I created a new PR with the above fixed and also updated the DNS records. We can close this one and move to  https://github.com/publicsuffix/list/pull/814

**Pull request closed without merging**
