### PR TITLE
Add additional entries to .GY ccTLD

### PR DESCRIPTION
**Pull request by richardwsmith**
http://registry.gy states:
Presently, .gy; .co.gy; .com.gy; .org.gy; .net.gy; .edu.gy and .gov.gy domain names. are available for registration.

### CODE REVIEW

**Comment by weppos** [comment]
@richardwsmith thanks for the patch. Are you affiliated with the .GY registry?

Can I also ask you to update the patch so that the .GY items will be sorted alphabetically?

**Comment by richardwsmith** [comment]
I am not affiliated with the .GY registry.  I work for Comodo CA, Ltd.  We use the PSL in determining registerable domains in our CA systems, and realized there the list was incomplete when we received a request for a certificate for a .gov.gy domain.

I have updated the file as requested.

**Comment by weppos** [comment]
I was able to validate the list using the information on the website:

screen shot 2016-01-11 at 22 36 24

**Comment by weppos** [comment]
Thanks @richardwsmith, I merged the patch.

**Comment by richardwsmith** [comment]
@weppos 
Happy to help.

**Pull request merged**
