### PR TITLE
Add zone.id

### PR DESCRIPTION
**Pull request by hdrxs312**
My website https://zone.id is a subdomain provider, which let someone to register a subdomain and park it to their website / blog.
I am worrying about cookie stealing throug XSS (Cross Site scripting) or other method.
Please help me.

### CODE REVIEW

**Comment by hdrxs312** [comment]
@weppos would you like to approve my PR immediately?

**Comment by hdrxs312** [comment]
@ayende can you review my request?

**Comment by hdrxs312** [comment]
as written in Guideline, i should do follow up.
now, can you let me know my PR progress?
i start worry about my website.
with 1400+ user and 4000+ registered subdomain, it's very potentially cookie stealing.
hope you understand me.. :-( @sleevi @weppos

**Comment by hdrxs312** [comment]
this has been a month but no reply.
If something wrong, let me know.
But, if everthing is fine, please merge It.

**Comment by weppos** [comment]
There will be a reply when your PR will be reviewed. Please be patient.

**Comment by hdrxs312** [comment]
As written in guidelines, I must follow up my request.
I think posting here is the way. Right?

**Comment by weppos** [comment]
You should follow up if clarifications are required/requested. There is no need to follow up periodically if no update if posted.

**Comment by hdrxs312** [comment]
Oh.. I am sorry.
Because there is no sentense like you just said in guideline. 
There is a PR that submitted 13 saya ago, but already approved. So, I think should remind you by doing follow up..

**Comment by hdrxs312** [comment]
dig +short TXT _psl.zone.id
    "https://github.com/publicsuffix/list/pull/575"

**Comment by hdrxs312** [comment]
Ready for review?

**Comment by hdrxs312** [comment]
URGENT!
@weppos please help us..
we are having major problems, regarding website cookies.
some website use document.cookie script on their page.

**Comment by hdrxs312** [comment]
@sleevi @weppos
i am waiting for long time. no one care. it was very disappointing.
.
please help us. i will apreciate it.
thanks..

**Comment by weppos** [comment]
Both @sleevi and I are involved in several other projects, some of them even consuming a reasonable amount of our personal time.

I do not expect you to understand this, but I do expect you to understand that as stated in our docs there is no guarantee of listing, nor timing.

There are other 50 requests, your is not more important or more relevant than the others. When the time will come, we will review it. I would rather prefer spending my time reviewing PRs, instead of having to reply over and over the same thing.

**Comment by hdrxs312** [comment]
:-( not important and not relevant?
i do expect you understand our problem

**Comment by sleevi** [comment]
While this does not meet the level of detail required by the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), I'm willing to grandfather this pull request in.

Requests should include information of example subdomains to ensure that the list entry is well-formed, for example.

**Comment by hdrxs312** [comment]
Thank you @sleevi

**Pull request merged**
