### PR TITLE
Add Creditas.com to public suffix list

### PR DESCRIPTION
**Pull request by creditasshojimau**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website:  https://www.creditas.com/ 

Creditas is the largest fintech for secured loans in Brazil. With secured loans, Creditas can provide lower interest rates for its clients and thus help people achieve their life projects. Currently having 4 offices in Brazil, 1 office in Spain and 1 office in Mexico. There are more than 2,000 employees. The company was valuated in US$1.75 billion in December of 2020.

Reason for PSL Inclusion
====
We're adding our domains and subdomains to PSL for cookie security, for registration on Facebook and for following Apple's demands for IOS14 data policy updates.
With that registration done and consequently registrated on Facebook, we are going to be able to configure our conversion events to optimize online campaign strategies. Otherwise, companies that does not follow this instructions will have all campaigns set-up on Facebook paused until this registration is done. Which means a huge financial impact.

DNS Verification via dig
=======

dig +short TXT _psl.creditas.com
https://github.com/publicsuffix/list/pull/1295

dig +short TXT _psl.creditas.com.br
https://github.com/publicsuffix/list/pull/1295

dig +short TXT _psl.creditas.com.mx
https://github.com/publicsuffix/list/pull/1295

dig +short TXT _psl.ajuda.creditas.com
"https://github.com/publicsuffix/list/pull/1295"

dig +short TXT _psl.app.creditas.com
https://github.com/publicsuffix/list/pull/1295

dig +short TXT _psl.auto.creditas.com
https://github.com/publicsuffix/list/pull/1295

dig +short TXT _psl.imovel.creditas.com
https://github.com/publicsuffix/list/pull/1295

dig +short TXT _psl.solucoes.creditas.com
https://github.com/publicsuffix/list/pull/1295

dig +short TXT _psl.store-mx.creditas.com
https://github.com/publicsuffix/list/pull/1295

make test
====

Making check in tests
  CC       test-is-public.o
  CC       test-is-public-builtin.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-registrable-domain.o
  CCLD     test-is-public
  CCLD     test-is-public-builtin
  CCLD     test-is-public-all
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-registrable-domain
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-builtin
PASS: test-registrable-domain
PASS: test-is-public-all

Testsuite summary for libpsl 0.21.1
TOTAL: 5
PASS:  5
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

Additional information
====

creditas.com - expires: 2029-03-31
creditas.com.br - expires: 2029-10-16
creditas.com.mx - expires: 2022-03-30   // we're talking to our office to extend this expiration date for at least +2 year.

### CODE REVIEW

**Comment by dnsguru** [comment]
#1245

**Comment by creditasshojimau** [comment]
@dnsguru Hello, do we need to do any changes to merge this PR?

**Comment by dnsguru** [comment]
Not sure if you read #1245 but we're not proceeding with approval on these while Facebook organizes their solution and process, as the PSL was not created or intended for working around limits.    Also see this: [expectations, propagation, inclusion](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion).

One of the key rationale from that is to ensure that people are not breaking something unintentionally with their request, having the downstream (browsers in this case, but could be anything) that pull the PSL and incorporate it.  Look at the diagrams and you will see a visualization of the consequences of a wrong request on core domains.

Typically one of the folks from FB who are hovering and monitoring things will join in on the dialog and walk the submitters through the process of ensuring submitters are requesting the right things and won't break something unintentionally.

Will wach for one of them to step up here.  This is currently a wontfix but we are reviewing ways to soften that wall.  We are unpaid volunteers on this project, so we put in cycles as we can, so patience will help also.

**Comment by bedfordsean** [comment]
Hi @creditasshojimau 

Checking in from the FB side here. Can you confirm how the creditas.com.* domains work? 

I don't see any subdomains that may represent distinct business entities on Google underneath your top level domains as listed in this pull request.

We don't intend the PSL to be used as a means to work around the limits as @dnsguru states above. Instead any PSL additions should be for the purposes of separate businesses. How do "app.creditas.com" and "auto.creditas.com" relate to each other?

**Comment by creditasshojimau** [comment]
@dnsguru @bedfordsean Thanks a lot for your work and attention, we did some alignment with Facebook

We will try another ways to make it workout.

Closing this PR, :)

**Pull request closed without merging**
