### PR TITLE
MjosereneCreate devcontainer.json

### PR DESCRIPTION
**Pull request by willj5t6969**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [ ] Description of Organization
* [ ] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
    - [Cloudflare](https://developers.cloudflare.com/learning-paths/get-started/add-domain-to-cf/add-site/)
    - [Letsencrypt](https://letsencrypt.org/docs/rate-limits/)
    - <UPDATE THIS LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY! REMOVE THIS LINE!>

  * [ ] This request was _not_ submitted with the objective of working around other third-party limits

  * [ ] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

Number of users this request is being made to serve:

DNS Verification via dig
=======

Results of Syntax Checker (`make test`)
=========

### CODE REVIEW

**Comment by willj5t6969** [comment]
[curl --request POST  

    --url https://api.cloudflare.com/client/v4/accounts/ea60feb9b7bb5374ed74d596dd42d487/request-tracer/tracer     --header 'Content-Type: application/json'  

    --header 'Authorization: Bearer $CF_AUTH_TOKEN'  

    --data '{"url":"Https://elliganceshops.myshopify.com","method":"PATCH","context":{"bot_score":""},"body":{"plain_text":""}}'](url)

**Comment by wdhdev** [comment]
May I ask what is the point of this PR?

**Comment by groundcat** [comment]
I'm guessing this pull request is somehow related to Visual Studio Code [Dev Containers](https://code.visualstudio.com/docs/devcontainers/containers), based on what the same requester did in a different project linked [here](https://github.com/vitest-dev/vscode/pull/437). However, I don't see how this is relevant or helpful to the PSL, and the requester hasn't provided much clarification about what they are trying to achieve...

**Comment by dnsguru** [comment]
@willj5t6969 we're closing this ; so that we don't block your user, before you open another of these rando PR's please explain what you're doing or knock it off

**Pull request closed without merging**
