### PR TITLE
Update Rad Web Hosting Domains section - add myradweb.net, servername.us

### PR DESCRIPTION
**Pull request by sclaeys**
> Also, the template had 10 tasks. Please put them all back and complete them.

### Checklist of required steps

* [x ] Description of Organization
Organization Website: https://radwebhosting.com

My name is Scott Claeys, I am a network engineer, and I represent Rad Web Hosting.

Rad Web Hosting provides web hosting and servers to users around the globe.
* [ x] Robust Reason for PSL Inclusion
Rad Web Hosting offers clients the ability to reserve unclaimed subdomains of *.myradweb.net for the purpose of staging incoming site migrations, viewing site updates in the wild, or for creation of webspaces to host websites and applications without registering a paid domain name.

We need to isolate them from one another (eg: we don't want client1.myradweb.net to be able to set a cookie readable from client2.myradweb.net).

Same applies for region specific endpoints. client1.uscp.myradweb.net should not be able to set cookies readable from bob-client2.uscp.myradweb.net site.

Number of users this request is being made to serve: Currently some hundreds are already using the service, but it is estimated to increase to thousands as our clients are continuously finding new creative use-cases for use of these "staging" domains.

Rad Web Hosting automatically generates unique hostnames for every cloud instance deployed that utilizes the *.servername.us second-level domain. These hostnames also provide access to a DNS zone which can be modified and customized by client.

We need to isolate them from one another (eg: we don't want client1.servername.us to be able to set a cookie readable from client2.servername.us).

Same applies for region specific endpoints. client1.us.servername.us should not be able to set cookies readable from bob-client2.us.servername.us site.

Number of users this request is being made to serve: Currently, this system is supporting hundreds of instances.
* [ x] DNS verification via dig
```
dig +short TXT _psl.myradweb.net
"https://github.com/publicsuffix/list/pull/1760"
```

```
dig +short TXT _psl.servername.us
"https://github.com/publicsuffix/list/pull/1760"
```
* [ x] Run Syntax Checker (make test)
Test run successfully

* [x ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x ] This request was _not_ submitted with the objective of working around other third-party limits

  * [x ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [ x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.

### CODE REVIEW

**Comment by sclaeys** [comment]
Confirmed

**Comment by sclaeys** [comment]
Please let us know of any further requirements for inclusion.

**Comment by sitedata** [comment]
Seems good!

**Review by sitedata — COMMENTED** [review]
Safe to merge

**Comment by sclaeys** [comment]
Is there anyone with write access who can check this PR? Very urgent.

**Review by sclaeys — COMMENTED** [review]
Perfect

**Comment by dnsguru** [comment]
It appears the request template was never completed, listing rationale and number of users etc.   

Complete requests are helpful for the unpaid reviewers who volunteer their time on this project as they process through the queue of PR.

Recommemd to complete request and also read the guidelines - especially about propogation timing - to ensure all expectations are aligned with the project resourcing.

**Comment by sclaeys** [comment]
> It appears the request template was never completed, listing rationale and number of users etc.
> 
> Complete requests are helpful for the unpaid reviewers who volunteer their time on this project as they process through the queue of PR.
> 
> Recommemd to complete request and also read the guidelines - especially about propogation timing - to ensure all expectations are aligned with the project resourcing.

Please check the updated comment

**Comment by sclaeys** [comment]
> It appears the request template was never completed, listing rationale and number of users etc.
> 
> Complete requests are helpful for the unpaid reviewers who volunteer their time on this project as they process through the queue of PR.
> 
> Recommemd to complete request and also read the guidelines - especially about propogation timing - to ensure all expectations are aligned with the project resourcing.

**Comment by sclaeys** [comment]
[Test](https://github.com/publicsuffix/list/actions/workflows/test.yml)



> * [x]  Description of Organization
> * [x]  Reason for PSL Inclusion
> * [x]  DNS verification via dig
> * [x]  Run Syntax Checker (make test)
> * [x]  Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.
> 
> # Description of Organization
> Organization Website: https://radwebhosting.com
> 
> My name is Scott Claeys, I am a network engineer, and I represent Rad Web Hosting.
> 
> Rad Web Hosting provides web hosting and servers to users around the globe.
> 
> # Reason for PSL Inclusion
> Rad Web Hosting offers clients the ability to reserve unclaimed subdomains of ***.myradweb.net** for the purpose of staging incoming site migrations, viewing site updates in the wild, or for creation of webspaces to host websites and applications without registering a paid domain name.
> 
> We need to isolate them from one another (eg: we don't want client1.myradweb.net to be able to set a cookie readable from client2.myradweb.net).
> 
> Same applies for region specific endpoints. client1.uscp.myradweb.net should not be able to set cookies readable from bob-client2.uscp.myradweb.net site.
> 
> Number of users this request is being made to serve: Currently some hundreds are already using the service, but it is estimated to increase to thousands as our clients are continuously finding new creative use-cases for use of these "staging" domains.
> 
> Rad Web Hosting automatically generates unique hostnames for every cloud instance deployed that utilizes the ***.servername.us** second-level domain. These hostnames also provide access to a DNS zone which can be modified and customized by client.
> 
> We need to isolate them from one another (eg: we don't want client1.servername.us to be able to set a cookie readable from client2.servername.us).
> 
> Same applies for region specific endpoints. client1.us.servername.us should not be able to set cookies readable from bob-client2.us.servername.us site.
> 
> Number of users this request is being made to serve: Currently, this system is supporting hundreds of instances.
> 
> ```
> % whois myradweb.net | grep "Registry Expiry"
> Registry Expiry Date: 2024-12-25T08:53:14Z
> 
> % whois servername.us | grep "Registry Expiry"
> Registry Expiry Date: 2024-10-13T09:17:28Z
> ```
> 
> # DNS Verification via dig
> ```
> dig +short TXT _psl.myradweb.net
> "https://github.com/publicsuffix/list/pull/1760"
> 
> dig +short TXT _psl.servername.us
> "https://github.com/publicsuffix/list/pull/1760"
> ```
> 
> # make test
> Test run successfully

@dnsguru Would this be more suitable?

**Comment by sitedata** [comment]
[Test](https://github.com/publicsuffix/list/actions/workflows/test.yml) 

Nice 👍

**Review by simon-friedberger — CHANGES_REQUESTED** [review]
> Same applies for region specific endpoints. client1.uscp.myradweb.net should not be able to set cookies readable from bob-client2.uscp.myradweb.net site.

This does not work with the PR as is.

**Comment by sitedata** [comment]
> > Same applies for region specific endpoints. client1.uscp.myradweb.net should not be able to set cookies readable from bob-client2.uscp.myradweb.net site.
> 
> This does not work with the PR as is.
If you’re referencing the fourth level domains, this will actually be solved internally.

Note that all we need is the second level names added. Apologies if this was unclear.

**Comment by simon-friedberger** [comment]
> > > Same applies for region specific endpoints. client1.uscp.myradweb.net should not be able to set cookies readable from bob-client2.uscp.myradweb.net site.
> > This does not work with the PR as is.
> If you’re referencing the fourth level domains, this will actually be solved internally.
I'm not sure how you're going to solve how browsers set cookies internally. Anyway, if you really don't need it pls remove it from the PR description.

**Comment by simon-friedberger** [comment]
Also, the template had 10 tasks. Please put them all back and complete them.

**Comment by sclaeys** [comment]
> Also, the template had 10 tasks. Please put them all back and complete them.

### Checklist of required steps

* [x ] Description of Organization
Organization Website: https://radwebhosting.com

My name is Scott Claeys, I am a network engineer, and I represent Rad Web Hosting.

Rad Web Hosting provides web hosting and servers to users around the globe.
* [ x] Robust Reason for PSL Inclusion
Rad Web Hosting offers clients the ability to reserve unclaimed subdomains of *.myradweb.net for the purpose of staging incoming site migrations, viewing site updates in the wild, or for creation of webspaces to host websites and applications without registering a paid domain name.

We need to isolate them from one another (eg: we don't want client1.myradweb.net to be able to set a cookie readable from client2.myradweb.net).

Same applies for region specific endpoints. client1.uscp.myradweb.net should not be able to set cookies readable from bob-client2.uscp.myradweb.net site.

Number of users this request is being made to serve: Currently some hundreds are already using the service, but it is estimated to increase to thousands as our clients are continuously finding new creative use-cases for use of these "staging" domains.

Rad Web Hosting automatically generates unique hostnames for every cloud instance deployed that utilizes the *.servername.us second-level domain. These hostnames also provide access to a DNS zone which can be modified and customized by client.

We need to isolate them from one another (eg: we don't want client1.servername.us to be able to set a cookie readable from client2.servername.us).

Same applies for region specific endpoints. client1.us.servername.us should not be able to set cookies readable from bob-client2.us.servername.us site.

Number of users this request is being made to serve: Currently, this system is supporting hundreds of instances.
* [ x] DNS verification via dig
```
dig +short TXT _psl.myradweb.net
"https://github.com/publicsuffix/list/pull/1760"
```

```
dig +short TXT _psl.servername.us
"https://github.com/publicsuffix/list/pull/1760"
```
* [ x] Run Syntax Checker (make test)
Test run successfully

* [x ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)



  * [x ] This request was _not_ submitted with the objective of working around other third-party limits



  * [x ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting



---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.



(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [ x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.

**Comment by simon-friedberger** [comment]
Could you please update the top comment instead of adding more?

**Comment by sclaeys** [comment]
> Could you please update the top comment instead of adding more?

Yes, good thoughts. I've made the recommended changes.

**Comment by sitedata** [comment]
Looks good 👍

**Comment by sclaeys** [comment]
> Also, the template had 10 tasks. Please put them all back and complete them.

We've reviewed and replaced this omission. Please follow up if you spot any other errors.

**Comment by sitedata** [comment]
According to what I can find from https://github.com/publicsuffix/list/actions/runs/6877814303/job/18706150168?pr=1760 this seems good to go

**Comment by simon-friedberger** [comment]
* [ ] Expiration (Note: Must STAY >2y at all times)
  * [x] myradweb.net expires 2026-12-25
  * [x] servername.us expires 2027-10-13
  * [ ] cloudsite.builders expires 2025-07-28
* [ ] DNS _psl entries (Note: Must STAY in place)
  * [ ] myradweb.net
  * [x] servername.us
  * [x] cloudsite.builders
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Comment by sclaeys** [comment]
Hello, not sure why the DNS _psl entry for myradweb.net wasn't available, but it's been in place since May 13, 2023.
Reference: [https://dnsrecords.io/_psl.myradweb.net](https://dnsrecords.io/_psl.myradweb.net)

Regarding cloudsite.builders, the expiration has been fixed and is now 2026-07-28.
Reference: [https://rdap.identitydigital.services/rdap/domain/cloudsite.builders](https://rdap.identitydigital.services/rdap/domain/cloudsite.builders)

**Review by sitedata — COMMENTED** [review]
Passing, by all accounts.

**Review by simon-friedberger — APPROVED** [review]

**Comment by sclaeys** [comment]
@dnsguru, what's the best way forward?

**Review by sitedata — COMMENTED** [review]
No conflicts with merge

**Comment by groundcat** [comment]
Hello @sclaeys I have noticed that the domain `myradweb.net` has been returning an `NXDOMAIN` error. Could you please confirm whether this project is still active? If the service has been decommissioned and the domain is no longer linked to an active project, please submit a removal request from the PSL. 

Additionally, the WHOIS records indicate that the domain's expiration is less than two years from now. To maintain your inclusion in the PSL, please ensure that your domain is renewed for more than two years at all times. If we do not receive a response within 30 days, your entry may be subject to removal. Thank you.

**Pull request merged**
