### PR TITLE
Add `cloudil.com` domains

### PR DESCRIPTION
**Pull request by GHCommiter**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowlegements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

CloudIL is an Israeli-based venture founded by Yandex — one of the leading tech companies in Europe — in collaboration with local partners. The mission of CloudIL is to deliver a high-performing cloud platform comparable to global hyperscalers in quality, and with unprecedented levels of security for full compliance with local laws and requirements for data privacy, access and control.

Organization Website: 

https://cloudil.com

Reason for PSL Inclusion
====

As a part of a service, we provide data storage for our customers, that can be used to deviler content and to host simple static websites (similar to AWS S3).

Here is the list of locations available for our customers to host there own content:

https://storage.cloudil.com/<bucket_name>/**
https://<bucket_name>.website.cloudil.com/**

Number of users this request is being made to serve:

More 10000

DNS Verification via dig
=======

dig +short TXT _psl.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.apigw.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.containers.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.docapi.serverless.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.functions.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.functions6.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.gitlab.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.logging.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.mdb.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.s3.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.storage.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.website.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

dig +short TXT _psl.ydb.serverless.cloudil.com
"https://github.com/publicsuffix/list/pull/1620"

Results of Syntax Checker (`make test`)
=========

```
make test
cd linter;                                \
  ./pslint_selftest.sh;                     \
  ./pslint.py ../public_suffix_list.dat;
test_allowedchars: OK
test_dots: OK
test_duplicate: OK
test_exception: OK
test_NFKC: OK
test_punycode: OK
test_section1: OK
test_section2: OK
test_section3: OK
test_section4: OK
test_spaces: OK
test_wildcard: OK
test -d libpsl || git clone --depth=1 https://github.com/rockdaboot/libpsl;   \
  cd libpsl;                                                                    \
  git pull;                                                                     \
  echo "EXTRA_DIST =" >  gtk-doc.make;                                          \
  echo "CLEANFILES =" >> gtk-doc.make;                                          \
  autoreconf --install --force --symlink;
Already up to date.
autopoint: using AM_GNU_GETTEXT_REQUIRE_VERSION instead of AM_GNU_GETTEXT_VERSION
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: linking file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
aclocal.m4:765: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:383: warning: file `version.txt' included several times
configure.ac:10: installing 'build-aux/compile'
configure.ac:4: installing 'build-aux/missing'
fuzz/Makefile.am: installing 'build-aux/depcomp'
cd libpsl && ./configure -q -C --enable-runtime=libicu --enable-builtin=libicu --with-psl-file=/home/slipko/list/public_suffix_list.dat --with-psl-testfile=/home/slipko/list/tests/tests.txt && make -s clean && make -s check -j4
./configure: line 13519: gl_VISIBILITY: command not found
configure: WARNING: --enable-builtin=libicu is deprecated, use --enable-builtin (enabled by default)
config.status: creating po/POTFILES
config.status: creating po/Makefile
Making clean in po
Making clean in include
Making clean in src
rm -f ./so_locations
Making clean in tools
 rm -f psl
Making clean in fuzz
 rm -f libpsl_icu_fuzzer libpsl_icu_load_fuzzer libpsl_icu_load_dafsa_fuzzer
Making clean in tests
 rm -f test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain
Making clean in msvc
Making check in po
Making check in include
Making check in src
  CC       libpsl_la-psl.lo
  CC       libpsl_la-lookup_string_in_fixed_set.lo
  CCLD     libpsl.la
Making check in tools
  CC       psl.o
  CCLD     psl
Making check in fuzz
  CC       libpsl_fuzzer.o
  CC       main.o
  CC       libpsl_load_fuzzer.o
  CC       libpsl_load_dafsa_fuzzer.o
  CCLD     libpsl_icu_fuzzer
  CCLD     libpsl_icu_load_fuzzer
  CCLD     libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-public
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public
PASS: test-is-public-builtin
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Please sort the entries according to the [guidelines](https://github.com/publicsuffix/list/blob/0c4beeb76338bfa580ea9aa7782776f748a6d105/CONTRIBUTING.md) and provide a description of your organization as well as a rationale for the inclusion

**Comment by dnsguru** [comment]
Please see [Comment in #1645 about the domain ordering](https://github.com/publicsuffix/list/pull/1645#issuecomment-1306095856) to fix that flaw, and then rebase your source and move from EoF into the appropriate alphabetical organization name (around the other Cloud companies) in the PRIVATE section

**Comment by GHCommiter** [comment]
Added Short org info, moved our domains up to by alphabet, added some dig checks...

**Review by GHCommiter — COMMENTED** [review]
Hello!
We ready for check our pull request before merge.

**Comment by GHCommiter** [comment]
Corrected sort based on https://github.com/publicsuffix/list/pull/1645#issuecomment-1306095856

**Comment by GHCommiter** [comment]
> Please sort the entries according to the [guidelines](https://github.com/publicsuffix/list/blob/0c4beeb76338bfa580ea9aa7782776f748a6d105/CONTRIBUTING.md) and provide a description of your organization as well as a rationale for the inclusion

When you can check it?

**Comment by dnsguru** [comment]
Because this is a volunteer-maintained repo, and there are not any other volunteers, it is done as it can be.  If you need a calendar date, the best I can guarantee is before 12-Dec-2023, but likely a lot sooner.

**Comment by GHCommiter** [comment]
> 

Ok. No problem.

**Pull request closed without merging**
