### PR TITLE
Add additional private Fastly domains, update contact email to fastly security

### PR DESCRIPTION
**Pull request by zmallen**

### CODE REVIEW

**Comment by zmallen** [comment]
We are working on TXT record for verification

**Comment by zmallen** [comment]
map.fastly.net

```shell
└─[13:01]$ dig TXT _psl.map.fastly.net

; <<>> DiG 9.8.3-P1 <<>> TXT _psl.map.fastly.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52949
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_psl.map.fastly.net.		IN	TXT

;; ANSWER SECTION:
_psl.map.fastly.net.	299	IN	TXT	"https://github.com/publicsuffix/list/pull/371"

;; Query time: 38 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jan  4 13:01:32 2017
;; MSG SIZE  rcvd: 95 
```

map.fastlylb.net

```shell
└─[13:01]$ dig TXT _psl.map.fastlylb.net

; <<>> DiG 9.8.3-P1 <<>> TXT _psl.map.fastlylb.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 100
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_psl.map.fastlylb.net.		IN	TXT

;; ANSWER SECTION:
_psl.map.fastlylb.net.	299	IN	TXT	"https://github.com/publicsuffix/list/pull/371"

;; Query time: 42 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jan  4 13:02:14 2017
;; MSG SIZE  rcvd: 97
```

fastlylb.net

```shell
└─[13:02]$ dig TXT _psl.fastlylb.net

; <<>> DiG 9.8.3-P1 <<>> TXT _psl.fastlylb.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12231
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_psl.fastlylb.net.		IN	TXT

;; ANSWER SECTION:
_psl.fastlylb.net.	299	IN	TXT	"https://github.com/publicsuffix/list/pull/371"

;; Query time: 97 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jan  4 13:04:35 2017
;; MSG SIZE  rcvd: 93
```

**Comment by weppos** [comment]
@zmallen I have two request for you:

1. Can you please alphabetically sort the items right-to-left as documented [here](https://github.com/publicsuffix/list/wiki/Guidelines#prepare-the-change). I am also starting a [format](https://github.com/publicsuffix/list/wiki/Format) page to better describe the format of the list

2. I encourage you to leave (or add) the `_psl` DNS records for all the entries. We are considering to increase the automation process to periodically check the DNS records for inclusion. Removing them _may_ cause the records to be removed in the future, although the process is still under development and there is no removal policy at the moment (I just wanted to mention it).

**Comment by zmallen** [comment]
Any update on merging this? Thanks

**Comment by weppos** [comment]
Validated via DNS.

```
➜  ~ for name ( map.fastly.net
a.prod.fastly.net
global.prod.fastly.net
a.ssl.fastly.net
b.ssl.fastly.net
global.ssl.fastly.net
fastlylb.net
map.fastlylb.net )
do
    echo $name
    dig TXT _psl.$name +short
done

map.fastly.net
"https://github.com/publicsuffix/list/pull/371"
a.prod.fastly.net
"https://github.com/publicsuffix/list/pull/371"
global.prod.fastly.net
"https://github.com/publicsuffix/list/pull/371"
a.ssl.fastly.net
"https://github.com/publicsuffix/list/pull/371"
b.ssl.fastly.net
"https://github.com/publicsuffix/list/pull/371"
global.ssl.fastly.net
"https://github.com/publicsuffix/list/pull/371"
fastlylb.net
"https://github.com/publicsuffix/list/pull/371"
map.fastlylb.net
"https://github.com/publicsuffix/list/pull/371"
```

**Pull request merged**
