### PR TITLE
add *.stage.nodeart.io

### PR DESCRIPTION
**Pull request by nosovk**
I reopened https://github.com/publicsuffix/list/pull/470 to have clear explanation of why my pull request isn't merged.

> In addition, owners of privately-registered domains who themselves issue subdomains to mutually-untrusting parties may wish to be added to the PRIVATE section of the list.

We isssue sub-domains to our clients, which can deploy their apps to their subdomains to get benefit of our CI and monitoring service. Regarding you [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) it's correct for me to add that sub-domain into the list. It's the preferable way to secure my clients data from stealing buy another client, am I correct?

### CODE REVIEW

**Comment by sleevi** [comment]
@nosovk Please carefully review the full [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) for how to submit a proper request. For example, see https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change

The goal of these guidelines is to ensure the PSL remains effective and manageable. Requests which continue to be submitted in contravention to the Guidelines may pose an unreasonable maintenance burden.

**Comment by nosovk** [comment]
Sorry for absence, I'm back and found that I missed to update DNS verification according to new pull request. Sorry. Here it goes:
image

* When submitting private domains, add a brief description of why you want the suffix(es) to be added to the list
* When submitting private domains, provide expected input/output if you want us to help you validating the correctness of the request

Currently most of out customers deploy their products under stage sub-domains (*.stage.nodeart.io). And it's a security concern for HIPPA compliant app for example. We wont to isolate cookies for each client application, to avoid stealing personal data or having similar issues.
I expect that each client sub-domain will be recognized as an individual domain and cross-domain cookies will be disabled between clients sub-domains.
Also I expect that apps like git.nodeart.io and wiki.nodeart.io would continue communicate using SSO placed in a root domain (and SSO cookie will be isolated from stage apps, keeping users safe from stealing their auth with another client)

**Comment by nosovk** [comment]
also rebased pull request to current master, no conflicts now.

**Comment by sleevi** [comment]
From the description, without the sample domains, it's unclear whether or not the pull request matches your intent.

That is, as written, `*.stage.nodeart.io` would mean each `foo.stage.nodeart.io` is itself a public suffix - meaning cookies cannot be set, and that `git.foo.stage.nodeart.io` and `wiki.foo.stage.nodeart.io` are separate cookie domains.

Is that correct, or is the wildcard unnecessary?

**Comment by nosovk** [comment]
probably I mistaken about `*`
`7bit.stage.nodeart.io` and `m.7bit.stage.nodeart.io` is the one cookie domain, but `appup.stage.nodeart.io` is another.
And also `wiki.nodeart.ip` and `jira.nodeart.io` are seprated from them all.
I will remove * now.

**Pull request merged**
