### PR TITLE
Added Cyclic Software

### PR DESCRIPTION
**Pull request by seekayel**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms

  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Cyclic Software is a Platform as a Service provider (PaaS). Developers are able to deploy applications to subdomains under any of the listed domains using our service. We sell hosting services to these developers and then host under one of the listed domains for these developers. The developers are independent and their applications are completely separate code bases from independent organizations.

I am the cofounder of Cyclic.

Organization Website: https://www.cyclic.sh

Reason for PSL Inclusion
====

Number of users this request is being made to serve: over 57k

- We provide each application a user deploys on our service a unique subdomain.
- We allow each user to change their subdomain.
- We want our users' apps to be isolated from each other (cookies, etc.)
- We want to prevent setting cookies on the apex domains.

DNS Verification via dig
=======
```
dig +short TXT _psl.cyclic.app
"https://github.com/publicsuffix/list/pull/1737"
```

```
dig +short TXT _psl.cyclic.cloud
"https://github.com/publicsuffix/list/pull/1737"
```

```
dig +short TXT _psl.cyclic-app.com
"https://github.com/publicsuffix/list/pull/1737"
```

```
dig +short TXT _psl.cyclic.co.in
"https://github.com/publicsuffix/list/pull/1737"
```

Results of Syntax Checker (`make test`)
=========

All tests passed.

### CODE REVIEW

**Comment by simon-friedberger** [comment]
Can you please provide a number of users and some example domains?

**Comment by seekayel** [comment]
Number of users:
- last month 13k active developers
- 126k all time

Example domains:
- https://raccoonjpdaikou.cyclic.app/
- https://nice-red-octopus-ring.cyclic.cloud/
- https://hilarious-cod-shirt.cyclic.app/
- https://wikigame.cyclic.app/

Please let me know if this is what you were looking for or would like something else.

**Review by simon-friedberger — CHANGES_REQUESTED** [review]
* [x] Expiration (Note: Must STAY >2y at all times!)
  * [x] cyclic.app expires 2028-12-12
  * [x] cyclic.cloud expires 2027-01-05
  * [x] cyclic-app.com expires 2026-03-01
  * [x] cyclic.co.in expires 2027-04-19
* [x] DNS _psl entries
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Comment by seekayel** [comment]
Extended Expirations:
- cyclic.app expires 2028-12-12
- cyclic.cloud expires 2028-01-05
- cyclic-app.com expires 2028-03-01
- cyclic.co.in expires 2028-04-19

**Review by simon-friedberger — APPROVED** [review]

**Comment by dnsguru** [comment]
@simon-friedberger approved.  Merging

**Pull request merged**
