### PR TITLE
Update public_suffix_list.dat for FAESA

### PR DESCRIPTION
**Pull request by Ttoledo28**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====FAESA is a Brazilian college with undergraduate and graduate courses

Organization Website: https://www.faesa.br/

 My name is Tayro, I'm a marketing coordinator at Grupo A. We are a company in the education segment. 
FAESA is a partner institution of which we share domains and subdomains:
FAESA domain: https://www.faesa.br/ 
Grupo A subdomain: https://ead.faesa.br/

Reason for PSL Inclusion
====FAESA is a partner college of the company A + Educação, which shares subdomains. We would like to add this domain to the PSL to use Facebook's PIXEL events in campaigns

#1296 
#1245 

DNS Verification via dig
=======

make test
=========
dig +short TXT _psl.faesa.br
"https://github.com/publicsuffix/list/pull/1300

### CODE REVIEW

**Comment by n8schloss** [comment]
Hi @Ttoledo28,

Facebook recently updated our [help center guidance](https://www.facebook.com/business/help/126789292407737?id=1205376682832142) around this and I'd like to specifically call out this section:

> Our current efforts are designed to support preexisting Public Suffix List domain registrations or eTLDs. This support is in line with Apple’s recent Private Click Measurement update. There are other technical implications if a domain is registered as a Public Suffix that a business should consider (for example, the domain that is registered on the Public Suffix List cannot have its own cookies) and as such, we do not recommend that clients register their domains on the Public Suffix List specifically for Facebook event configuration.

When I visit https://www.faesa.br/ I see lots of content and am even asked about turning on notifications. So given that there's a full site at that domain I'm not sure if being added to the PSL is the best solution here. Being added to the PSL will break a lot of the functionality on that page and given that browsers have varying cadence for updating their copies of the PSL, if you get added and notice breakages then it may be months before you could be removed.

**Comment by Ttoledo28** [comment]
Helo @n8schloss! Ty for your help.

As I understand it, to include my domain in the PSL, I need to give up my coockies on the page and that could harm my navigation strategies, correct?

Is there any other solution for configuring Facebook's Pixel events on subdomains?

**Comment by Ttoledo28** [comment]
> Hi @Ttoledo28,
> 
> Facebook recently updated our [help center guidance](https://www.facebook.com/business/help/126789292407737?id=1205376682832142) around this and I'd like to specifically call out this section:
> 
> > Our current efforts are designed to support preexisting Public Suffix List domain registrations or eTLDs. This support is in line with Apple’s recent Private Click Measurement update. There are other technical implications if a domain is registered as a Public Suffix that a business should consider (for example, the domain that is registered on the Public Suffix List cannot have its own cookies) and as such, we do not recommend that clients register their domains on the Public Suffix List specifically for Facebook event configuration.
> 
> When I visit https://www.faesa.br/ I see lots of content and am even asked about turning on notifications. So given that there's a full site at that domain I'm not sure if being added to the PSL is the best solution here. Being added to the PSL will break a lot of the functionality on that page and given that browsers have varying cadence for updating their copies of the PSL, if you get added and notice breakages then it may be months before you could be removed.



Helo!

As I understand it, to include my domain in the PSL, I need to give up my coockies on the page and that could harm my navigation strategies, correct?

Is there any other solution for configuring Facebook's Pixel events on subdomains?

**Comment by n8schloss** [comment]
@Ttoledo28, at this time there's a limit of 8 conversion events per domain. The limitations on ad measurement are definitely regrettable, but these restrictions all derive ultimately from Apple's decision to limit the amount of entropy in PCM reports to 4 bits of "trigger_data" on websites. Apple is giving each business/entity this entropy budget to decide for themselves how to spend.

Being added to PSL is not appropriate here, so the alternative would be to not use a subdomain and register a new domain if ead.faesa.br is a distinct entity from www.faesa.br.

I empathize with your plight, and we are trying to propose alternative privacy-proposing alternatives to Apple through the W3C, but at this time this is the limitation.

**Pull request closed without merging**
