### PR TITLE
Adding Drud Holdings PaaS domains

### PR DESCRIPTION
**Pull request by cyberswat**

### CODE REVIEW

**Comment by cyberswat** [comment]
Drud operates a Platform as a Service (PaaS) supporting Drupal and WordPress Content Management Systems (CMS). Host names under drud.com, drud.io, and drud.us are under administrative control of Drud prospective customers, customers, partners, and others.

**Comment by cyberswat** [comment]
The dns records are in place and should be ready to verify.
```
➜  ~ dig +short TXT _psl.drud.com
"https://github.com/publicsuffix/list/pull/234"
➜  ~ dig +short TXT _psl.drud.io
"https://github.com/publicsuffix/list/pull/234"
➜  ~ dig +short TXT _psl.drud.us
"https://github.com/publicsuffix/list/pull/234"
```

**Comment by weppos** [comment]
@cyberswat  before I move forward, are you aware that if the patch will be merged your primary domain may not work anymore in browsers or other clients using the PSL if you will ever remove the www prefix, because of the fact you requested it to be treated as a suffix `drud.com`?

**Comment by cyberswat** [comment]
We discussed it internally and decided to remove drud.com to the list.  Thanks for pointing that out.  The pull request was updated.

**Pull request merged**
