### PR TITLE
Add edgecompute.app

### PR DESCRIPTION
**Pull request by jfoote**
Hello,

Jonathan Foote from the Fastly security team here, adding another PSL entry for the organization.

Update: This PR is ready for review.

Thanks,
Jon

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: [www.fastly.com](https://www.fastly.com)

Fastly’s global edge cloud platform processes, serves, and secures applications for users. See [www.fastly.com](https://www.fastly.com) for more information.

Reason for PSL Inclusion
====

User (third-party) content is served from subdomains of edgecompute.app. Adding this domain to the PSL will stymie cookie stuffing attacks across these subdomains.

The registration term for edgecompute.app is greater than 2 years in the future, and it will be extended automatically in advance of expiration. 

```
% whois edgecompute.app | grep "Registry Expiry"
Registry Expiry Date: 2025-09-26T17:20:49Z
```

DNS Verification via dig
=======

DNS is ready for verification

```
% dig +short TXT _psl.edgecompute.app
"https://github.com/publicsuffix/list/pull/1212"
```

make test
=========

`make test` completed successfully

### CODE REVIEW

**Comment by dnsguru** [comment]
Updates #194 #371 #424, (+same author #729)

**Comment by jfoote** [comment]
DNS has been updated and I've confirmed the registration will be extended automatically going forward. This is ready for review. If you need any additional information please just let me know.

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok - (updated to reflect this PR, thx @jfoote)
- Tests ok
- Rationale ok
- No conflict with base

Approved

**Comment by jfoote** [comment]
Thank you!

**Pull request merged**
