### PR TITLE
Update public_suffix_list.dat

### PR DESCRIPTION
**Pull request by RegistryPRO**
Add nitr.pro on ICANN List Suffix of PSL

/ RegistryPRO Northern Ireland and Tyrone: http://www.registry.nitr.pro
+// Submitted by Saymon Rhuano saymonrhuano@gmail.com
+nitr.pro

### CODE REVIEW

**Comment by RegistryPRO** [comment]
Registrars List:

https://www.nominate.com/nitr.pro.shtml
https://www.bb-online.com/mobile/nitr.pro.shtml
https://domainr.com/pro
https://www.brighterdomains.com/international-domains.shtml
https://icannwiki.org/.nitr.pro
https://www.freevaluator.com/directory/available-tld

**Comment by sleevi** [comment]
None of these sources meet the requirements of the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), which clearly state that they must come from the registry website or be authenticated via DNS.

**Comment by RegistryPRO** [comment]
@sleevi What should I do?

**Comment by sleevi** [comment]
Have the registry update their documentation, or have the TXT record.

**Comment by RegistryPRO** [comment]
@sleevi Você está hospedado TXT incluído no DNS utilizando o ID 5768

**Comment by RegistryPRO** [comment]
@sleevi The suffix already has the TXT record under ID 5768

**Comment by RegistryPRO** [comment]
@sleevi We do the test and check on WHOIS and Gwhois.org and the suffix is presenting the PSL record TXT ID 5768

**Comment by sleevi** [comment]
Please read the Guidelines carefully.

**Comment by frju365** [comment]
This PR(659) : In fact, you must add a subdomain in your record like : 
`_psl.nitr.pro 3600 IN TXT "https://github.com/publicsuffix/list/pull/659"`
Just that to confirm. Then you just add in your comment here the test to check it : something like `dig +short TXT _psl.nitr.pro` and you write clearly the result which must be the URL of this PR : https://github.com/publicsuffix/list/pull/659

**Comment by RegistryPRO** [comment]
@frju365 @sleevi Many thanks again for the enlightening help.

Registration was added with access!

**Comment by RegistryPRO** [comment]
The reason you request the PR for NITR.PRO:

NITR.PRO was marketed by Afilias, but since last year I took over the operations and got in touch with registrars.
NITR.PRO is currently a public suffix marketed by several companies.

**Pull request closed without merging**
