### PR TITLE
Add *.bzattachments.org - the bugzilla.org attachments subdomain service.

### PR DESCRIPTION
**Pull request by gerv**

### CODE REVIEW

**Comment by weppos** [comment]
@gerv there is another similar entry already on the list:

```
// Mozilla Foundation : https://mozilla.org/
// Submitted by glob <glob@mozilla.com>
bmoattachments.org
```

It is still valid?

**Comment by gerv** [comment]
bmoattachments.org is the attachments for Bugzilla.Mozilla.Org - BMO.

*.bzattachments.org is so the Bugzilla development team can offer similar facilities to other Bugzilla installations without them all having to get an entry added to the PSL like BMO did. We will delegate subdomains to people maintaining installations, hence the *.

**Comment by gerv** [comment]
gerv@hare$ dig TXT +short _psl.bzattachments.org
"https://github.com/publicsuffix/list/pull/218"

**Comment by gerv** [comment]
> gerv@hare:/usr/src/publicsuffix.org$ dig TXT +short _psl.bzattachments.org
> https ://github.com/publicsuffix/list/pull/218

**Comment by weppos** [comment]
@gerv LGTM, validated via DNS.

**Comment by sleevi** [comment]
@gerv did you want to land this?

**Comment by sleevi** [comment]
@gerv Closing this due to no comment. I'm assuming you'll reopen and land if it's correct :)

**Pull request closed without merging**
