### PR TITLE
add `nyat.app`

### PR DESCRIPTION
**Pull request by fakeboboliu**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

We are a tunnel service provider like ngrok in China.
We just launched a subdomain service `nyat.app` into our service per user's request last month.
I'm one of the developers and administrators of the service, who can on behalf of the team.

Organization Website: https://www.natfrp.com

Reason for PSL Inclusion
====

Cookie security, we currently providing subdomains per user's request, there're tons of login pages and APIs on different subdomains,  
we want to make sure the cookies are secure and not shared between subdomains.

Number of users this request is being made to serve: 500(users who owning a subdomain right now, can be verified through CT) - ~100000(users we have and may use subdomain in the future, estimated according to a survey)

DNS Verification via dig
=======

```
dig +short TXT _psl.nyat.app
"https://github.com/publicsuffix/list/pull/2122"
```

Results of Syntax Checker (`make test`)
=========

```
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

PASS: test-is-public-builtin
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by fakeboboliu** [comment]
Asking for the DNS manager to add the `_psl` record, it's delegated and my api can't add a root TXT record. ;)

**Review by wdhdev — COMMENTED** [review]
Your entry should be sorted between `NGO.US Registry` and `ngrok`.

**Comment by wdhdev** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] nyat.app expires 2030-07-04
* [x] DNS _psl entries (Note: Must STAY in place)
  * [x] `_psl.nyat.app`
* [x] Tests pass
* [ ] Sorting
* [x] Reasoning/Organization description
* [x] Non-personal email address

---

> ~100000 (users we have and may use subdomain in the future, estimated according to a survey)

Are you able to show evidence of your survey? 500 users isn't enough usage as seen in our guidelines:

> Projects that are smaller in scale or are temporary or seasonal in nature will likely be declined. Examples of this might be private-use, sandbox, test, lab, beta, or other exploratory nature changes or requets. It should be expected that despite whatever site or service referred a requestor to seek addition of their domain(s) to the list, projects not serving more then thousands of users are quite likely to be declined.

**Comment by fakeboboliu** [comment]
> Your entry should be sorted between `NGO.US Registry` and `ngrok`.

Can you explain why? It looks doesn't match any rules, neither the Right-to-left sorting rule nor alphabetical order of service name.

> 500 users isn't enough usage as seen in our guidelines

It's 500 users can be currently verified though CT because they are using hosted free certificates, the number is limited since it's an experimental feature that not been promoted to all our users.
We have more than 1000k users for the project itself, it's obviously not the case.

**Comment by groundcat** [comment]
The sorting looks good to me, properly ordered by the commented company name according to the [guideline](https://github.com/publicsuffix/list/wiki/Guidelines#sort-your-submission-correctly-important).

https://github.com/publicsuffix/list/blob/76d85a34e839c346d14155a12cc7dd3607a6d8f8/public_suffix_list.dat#L14356-L14366

As far as I know, Sakura Frp is a popular tunneling service in Asia, so I believe the user base is much larger than 500. 

My questions are:
- Is there any mention of the use of the 'nyat.app' domain somewhere on the Sakura Frp website at natfrp.com? This would help us verify the nexus—whether this PR is truly submitted by Sakura Frp/natfrp.com.
- How likely is it that most/all users will adopt the 'nyat.app' domain in the near future? The PSL typically doesn't accept entries that are sandbox, testing, or experimental in nature, as it focuses on long-term projects. Additionally, changes would take over 90 days to propagate, so I want to ensure that the intention of using the 'nyat.app' domain is likely to be realized and maintained long-term (ideally more than 2 or 3 years).

**Comment by wdhdev** [comment]
@fakeboboliu @groundcat The sorting is incorrect as the start of the company name is lowercase, not uppercase. Please correct me if I'm wrong though.

**Comment by fakeboboliu** [comment]
@groundcat

> Is there any mention of the use of the 'nyat.app' domain somewhere on the Sakura Frp website at natfrp.com? This would help us verify the nexus—whether this PR is truly submitted by Sakura Frp/natfrp.com.

Yes, there are mentions available at our doc in Chinese.
https://doc.natfrp.com/bestpractice/domain-bind.html
`SakuraFrp 为所有用户提供免费的 nyat.app 子域名和 SSL 证书` which means SakuraFrp provides free `nyat.app` subdomain and ssl certs.

> How likely is it that most/all users will adopt the 'nyat.app' domain in the near future?

It has been started for 2mo and been a part of our service now, we not likely shutdown the service as long as we still operating.
It's only promoted to users who asked about SSL certification errors for now, but already available to all our users as a standardized service.

***

@wdhdev I submitted the name based on our internal convention, if that makes you confusion, I'll replace it with a capitalized `SakuraFrp`

**Comment by wdhdev** [comment]
> @wdhdev I submitted the name based on our internal convention, if that makes you confusion, I'll replace it with a capitalized Sakura Frp

That works, however you need to move that entry down one as `SAKURA Internet Inc.` is above as the `A` is capitalised. Basically capitalised names come before uncapitalised names.

**Comment by fakeboboliu** [comment]
> you need to move that entry down one as `SAKURA Internet Inc.` is above as the `A` is capitalised. Basically capitalised names come before uncapitalised names.

I didnot find any rule and living example in `public_suffix_list.dat`, i'll change it if you can make sure.

**Comment by wdhdev** [comment]
It seems you're correct, please ignore that review. Sorry, I'm very tired 😆

**Comment by groundcat** [comment]
> Basically capitalised names come before uncapitalised names.

Based on other entries in the private section, it seems that the ordering of organization names is case-insensitive. There are many instances in the PSL where whether the first character of the organization's name is capitalized or not does not affect the order. 

One of such examples:

https://github.com/publicsuffix/list/blob/fa153b452b9e8ab1ba52982bde6ace5ecdaddd77/public_suffix_list.dat#L12421-L12443

However, I did find a comment in one of the internal parser tools that suggests otherwise ("ordering is case-sensitive, whitespace-sensitive and punctuation-sensitive"):

https://github.com/publicsuffix/list/blob/fa153b452b9e8ab1ba52982bde6ace5ecdaddd77/tools/internal/parser/unicode.go#L44-L51

But if we want to follow the convention of other entries in the PSL, I think the ordering in this specific PR seems acceptable.

**Comment by fakeboboliu** [comment]
@groundcat I tried the tool you mentioned `psltool fmt public_suffix_list.dat` and it shows we do have two lines need reorder, but not that line.
Maybe the fmt tool is still in WIP?

```diff
diff --git a/public_suffix_list.dat b/public_suffix_list.dat
index b66ee5e..a4b13ca 100644
--- a/public_suffix_list.dat
+++ b/public_suffix_list.dat
@@ -13911,14 +13911,14 @@ ipifony.net
 // Submitted by Ali Soizi <info@nic.ir.md>
 ir.md
 
-// is-a.dev : https://www.is-a.dev
-// Submitted by William Harrison <admin@m.is-a.dev>
-is-a.dev
-
 // is-a-good.dev : https://is-a-good.dev
 // Submitted by William Harrison <webmaster@is-a-good.dev>
 is-a-good.dev
 
+// is-a.dev : https://www.is-a.dev
+// Submitted by William Harrison <admin@m.is-a.dev>
+is-a.dev
+
 // IServ GmbH : https://iserv.de
 // Submitted by Mario Hoberg <info@iserv.de>
 iservschule.de
@@ -14212,11 +14212,6 @@ barsyonline.co.uk
 // Submitted by Ilya Zaretskiy <zaretskiy@corp.mail.ru>
 hb.cldmail.ru
 
-// May First - People Link : https://mayfirst.org/
-// Submitted by Jamie McClelland <info@mayfirst.org>
-mayfirst.info
-mayfirst.org
-
 // MathWorks : https://www.mathworks.com/
 // Submitted by Emily Reed <psl-maintainers@groups.mathworks.com>
 matlab.cloud
@@ -14224,6 +14219,11 @@ modelscape.com
 mwcloudnonprod.com
 polyspace.com
 
+// May First - People Link : https://mayfirst.org/
+// Submitted by Jamie McClelland <info@mayfirst.org>
+mayfirst.info
+mayfirst.org
+
 // Maze Play: https://www.mazeplay.com
 // Submitted by Adam Humpherys <adam@mws.dev>
 mazeplay.com
```

**Comment by fakeboboliu** [comment]
sorry for closed by accident, those buttons are just too close

**Comment by fakeboboliu** [comment]
So, all requirements seem met now?

**Comment by groundcat** [comment]
> So, all requirements seem met now?

Kindly wait patiently, as the decision to merge or ask follow-up questions now rests with the maintainers. You may refer to [Resourcing and Level of Effort (LoE)](https://github.com/publicsuffix/list/wiki/Guidelines#resourcing-and-level-of-effort-loe-impacts-the-pace-of-processing-validation-or-merge-of-a-contribution) if needed.

**Comment by simon-friedberger** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] nyat.app expires 2030-07-04
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description
* [x] Non-personal email address

**Pull request merged**
