### PR TITLE
add lgbt.sh

### PR DESCRIPTION
**Pull request by cvyl**
# Public Suffix List (PSL) Submission

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Test results included

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the `_psl` TXT record in place in the respective zone(s).

__Submitter affirms the following:__ 

 * [x] We are listing *any* third-party limits that we seek to work around in our rationale, such as those between iOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example).

We are **not** submitting this request to bypass any third-party limitations. Specifically:
 - Cloudflare: No issues or rate limits are being addressed through this request. `lgbt.sh` operates independently of Cloudflare's systems.
 - Let's Encrypt: We are not seeking to circumvent Let's Encrypt rate limits. Certificates for `lgbt.sh` and its subdomains are issued within standard limits and policies.
 - Other third parties: This request is not intended to address issues related to iOS, Facebook, or any other third-party systems.

This submission is being made solely to ensure that `lgbt.sh` is recognized as a public suffix for proper handling of cookies, cross-origin policies, and security isolation.

 * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, and responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

 * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms to them.
 * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting.

**Abuse Contact:**

* [x] Abuse contact information (email or web form) is available and easily accessible.

  URL where abuse contact or abuse reporting form can be found: 
  [abuse email](mailto:abuse@lgbt.sh) / [Abuse Page https://lgbt.sh/abuse.html](https://lgbt.sh/abuse)

---

 * [x] *Yes, I understand*. I could break my organization's website cookies and cause other issues, and the rollback timing is acceptable. *Proceed anyways*.

---

## Description of Organization

**Organization Name:** LGBT.SH  
**Organization Website:** [https://lgbt.sh](https://lgbt.sh)  
**Description:** LGBT.SH is a public subdomain registry that provides domain name services specifically tailored to the global LGBTQ+ community. The platform allows users to register subdomains under `lgbt.sh` for personal, organizational, or advocacy purposes. 

Subdomain registrations are available through two methods: email requests or by opening a GitHub issue. This ensures transparency and ease of access for a wide range of users. Abuse reporting mechanisms are in place to address any misuse.

---

## Reason for PSL Inclusion

The inclusion of `lgbt.sh` in the Public Suffix List is requested to ensure proper handling of cookies, security, and cross-origin policies. Being a public subdomain registry, `lgbt.sh` allows independent registration of subdomains by users, which makes its behavior closer to a TLD than a typical domain.

This inclusion will enhance compatibility with browsers and applications, enabling subdomain users to implement independent security policies without cross-origin interference from other subdomains.

**Number of users this request is being made to serve:**  
Approximately **180 active subdomains**, with potential for continued growth as registrations increase.

---

## DNS Verification

The following DNS verification records have been added:

```
dig +short TXT _psl.lgbt.sh
"https://github.com/publicsuffix/list/pull/2304"
```

---

## Test Results

The `make test` command was run as part of the submission process, and all tests passed successfully:

https://pastebin.com/raw/CLJnfQ5s

---

Thank you for considering this submission. I am happy to provide additional information or address any concerns the reviewers might have.

### CODE REVIEW

**Comment by wdhdev** [comment]
180 users/subdomains is generally top little to be approved, I would recommend closing this and reopening it when you reach around 1,000 users.

**Comment by cvyl** [comment]
> 180 users/subdomains is generally top little to be approved, I would recommend closing this and reopening it when you reach around 1,000 users.

Thank you for taking the time to review my submission. I appreciate the feedback and the opportunity to learn more about the criteria for inclusion. I was under the impression that there wasn't a specific user minimum for submissions, so I apologize for any misunderstanding on my part.

Would the current size of my user base make LGBT.SH ineligible, or is it simply a matter of scaling the project further before reapplying? This is a project I’m actively reworking to make registration and usage even easier, and I'm hopeful it will continue to grow in the coming year.

Again, thank you for your time. I'm happy to follow any recommendations to improve my chances for approval in the future.

**Comment by wdhdev** [comment]
As per our guidelines:
> Projects that are smaller in scale or are temporary or seasonal in nature will likely be declined. Examples of this might be private-use, sandbox, test, lab, beta, or other exploratory nature changes or requests. It should be expected that despite whatever site or service referred a requestor to seek addition of their domain(s) to the list, projects not serving more then thousands of users are quite likely to be declined.

> Would the current size of my user base make LGBT.SH ineligible, or is it simply a matter of scaling the project further before reapplying?

The current user base size is likely ineligible, we normally require a minimum of 1,000 users, as per my previous comment. You would need to scale the project further before you will be accepted.

Once you have around 1,000 users, you should be good to be approved.

**Comment by groundcat** [comment]
I agree with @wdhdev that the project typically cannot accept submissions for smaller-scale projects, as each entry in the PSL (Public Suffix List) must demonstrate substantial user impact - typically at least thousands of users - to merit inclusion. I do appreciate the free subdomain registries like the ones you are operating, though.

However, please note that _subdomain count_ is just one metric for evaluating a project's _scale_, not the sole criterion. If you can provide additional metrics or evidence demonstrating your service's current user impact, we will evaluate those as part of the consideration process.

**Comment by cvyl** [comment]
Thank you for taking the time to review and provide guidance on my submission. I understand the minimum user requirement, but I’d like to share additional points to highlight the value of LGBT.SH and how inclusion in the Public Suffix List (PSL) can enhance its ability to serve a growing global audience.

LGBT.SH provides free subdomains to individuals across the globe (Most common in Europe, the Americas, and China), enabling users to create blogs and personal sites to express themselves freely without having to register/pay for a domain of their own. This is particularly important for members of the LGBTQ+ community, where access to safe online spaces can be a lifeline for self-expression and connection.

### Why Inclusion in the PSL Matters:

1. Improved Cookie Isolation for Better Privacy:
Inclusion in the PSL ensures that cookies are isolated between subdomains. This is vital for users hosting personal sites, as it protects their privacy and prevents potential conflicts caused by shared cookie storage across unrelated subdomains.

2. Equal Treatment Across Browsers and Systems:
Without PSL inclusion, some browsers and systems may treat subdomains of LGBT.SH as part of a single entity, limiting functionality for individual users. For example, issues with cross-origin policies, JavaScript behaviour, and cookie handling can occur. PSL inclusion ensures that subdomains are recognized as independent entities, giving users the full benefits of secure, modern web standards.

3. Perception of Legitimacy and Professionalism:
Inclusion in the PSL helps establish LGBT.SH as a recognized public suffix, making it comparable to larger platforms like `.github.io` or `.co.uk`. This boosts the credibility of LGBT.SH subdomains, making users feel more confident hosting their sites on a trusted and technically recognized domain.

4. Users in Restricted Regions:
In regions like China, where internet censorship and surveillance are common, users face significant challenges in accessing platforms for self-expression and community engagement. LGBT.SH provides a vital, safe space for these individuals by offering an accessible and secure way to establish a web presence.

Registrations are completely free and can be done anonymously if needed, using email as the sole requirement. This ease of access removes barriers for those who may otherwise be unable to obtain a web address. Inclusion in the PSL further enhances the reliability and security of the platform, making sure that users in restrictive environments can continue to benefit from a stable and technically sound service.

By helping individuals with their web presence, LGBT.SH plays a role in enabling free expression and fostering connections across borders, regardless of the limitations imposed by local governments or social stigmas.

5. Scalability and Growth Potential:
By being recognized as a public suffix, LGBT.SH becomes more attractive to new users and developers, who may be drawn to PSL inclusion's enhanced functionality and trust. This would enable the project to grow faster, benefiting even more individuals seeking free, safe, and accessible hosting.

### Commitment to Growth:
I am actively reworking LGBT.SH to make registration even more user-friendly and accessible. I believe inclusion in the PSL will help drive adoption by addressing the technical challenges and perceived limitations of subdomain-based platforms, ultimately enabling me to serve a much larger community.

Thank you again for considering this submission. I hope this shows how inclusion in the PSL can significantly enhance the value LGBT.SH provides to its global user base. I’m open to any additional feedback or recommendations.

**Comment by groundcat** [comment]
@cvyl Perhaps I was not clear enough - we are seeking any form of **quantitative** evidence that supports the claim regarding how many users would benefit from having your domain included in the PSL. While the number of subdomains is a significant indicator, we also consider other factors. These could potentially include the number of users within multiple individual subdomains who may benefit indirectly, or tunneling use cases that are not visible to external sources such as search engines, etc. We are not interested in non-quantitative narratives or marketing materials, but rather focus on technical aspects that can be quantified and verified.

**Comment by cvyl** [comment]
> @cvyl Perhaps I was not clear enough - we are seeking any form of **quantitative** evidence that supports the claim regarding how many users would benefit from having your domain included in the PSL. While the number of subdomains is a significant indicator, we also consider other factors. These could potentially include the number of users within multiple individual subdomains who may benefit indirectly, or tunneling use cases that are not visible to external sources such as search engines, etc. We are not interested in non-quantitative narratives or marketing materials, but rather focus on technical aspects that can be quantified and verified. As previously indicated, 180 subdomains (assuming it indicates 180 users) does appear insufficient, and it might be best to close this one and in the future submit a new PR after your service has gained a sufficient user base.

Thank you for the clarification! I understand now. I will close this PR and re-submit it once the requirements are met.
Wishing you a good rest of the week.

**Comment by wdhdev** [comment]
In addition to what @groundcat said, it is unlikely an AI generated response will likely help it get approved.

Point 1 & 2 are pretty much the same thing.

In point 3, you say being included on the PSL helps boost the trust of a domain. The PSL is not intended to be used as a method of verifying the trust of domains.

Regarding censorship, it is still possible on the .sh TLD as it is a ccTLD, so it is bound to the laws of the country operating it. (The same as other ccTLDs like .au, .uk, etc.)

Regarding point number 5, the purpose of PSL inclusion is not intended to get publicity for a domain.

I would recommend just waiting to reapply in future when you have around 1,000 users, or if you have a proper reason as to why you need to be included now.

**Pull request closed without merging**
