### PR TITLE
Add mybluemix.net

### PR DESCRIPTION
**Pull request by IvanGoncharov**
See this article: https://developer.ibm.com/bluemix/2014/06/16/introducing-mybluemix-net-new-domain-application/

### CODE REVIEW

**Comment by gerv** [comment]
Hi Ivan,

We can only add this with the consent of the domain owner. Do you represent them?

Gerv

**Comment by IvanGoncharov** [comment]
@gerv No, but I opened an official issue to ask for consent.

**Comment by pmuellr** [comment]
Seems like this should be ok - but I don't speak for (or work at, anymore) IBM.  Note however there are multiple `mybluemix.net` styled domains, for the different geo's that Bluemix is available in.  Someone from IBM would have to provide those names, and there's an issue that the number may grow over time.

**Comment by jsloyer** [comment]
mybluemix.net, eu-gb.mybluemix.net, au-syd.mybluemix.net

**Comment by IvanGoncharov** [comment]
@jsloyer I need to add contact person email. Can you please write your corporate email?

**Comment by IvanGoncharov** [comment]
@gerv I updated PR with information from @jsloyer 
He is Bluemix Developer Advocates so represent domain owner.
Can you please merge it.

**Comment by gerv** [comment]
If there are lots of subdomain options, why not add *.mybluemix.net? @jsloyer : after studying https://publicsuffix.org/list/ , can you comment on what the right rule is?

Gerv

**Comment by jsloyer** [comment]
@gerv yeah that is fine.

**Comment by IvanGoncharov** [comment]
@gerv In my particular case address is `xforce-api.mybluemix.net`.
 if rule is `*.mybluemix.net` what will be suffix?

**Comment by gerv** [comment]
IvanGoncharov: you should read the PSL spec :-) But in that case the public suffix would be xforce-api.mybluemix.net, and so the registered domain (or equivalent) would be foo.xforce-api.mybluemix.net. 

If you are saying that mybluemix.net offers both foobar.mybluemix.net and foobar.eu-gb.mybluemix.net and foobar.au-syd.mybluemix.net then yes, unfortunately, we need to enumerate a full list of the en-gb/au-syd things, otherwise we can't tell the difference between the two cases.

**Comment by jsloyer** [comment]
@gerv we need the full list.

- `*.mybluemix.net`
- `*.eu-gb.mybluemix.net`
- `*.au-syd.mybluemix.net`

**Comment by IvanGoncharov** [comment]
@jsloyer  it's exactly what I put in my PR. @gerv So it could be merged, right?

**Comment by IvanGoncharov** [comment]
@gerv Can you please merge it?

**Comment by gerv** [comment]
> @jsloyer it's exactly what I put in my PR. 

No, it's not. Your PR has those domains without the *. The fact that you don't see a difference suggests to me that you haven't quite grasped the semantics of the PSL. There are big differences between the rules `mybluemix.net` and `*.mybluemix.net`. Which do you want?

It might help if you gave some examples (multiple examples) of the actual domains that customers use.

Are eu-gb and au-syd the only current geos in which this service is available?

**Comment by sleevi** [comment]
@jsloyer Can you please respond to Gerv's question here - https://github.com/publicsuffix/list/pull/46#issuecomment-160679724 ? Otherwise, we will not be able to proceed with this.

**Comment by sleevi** [comment]
Closing due to no followup.

**Comment by jsloyer** [comment]
@sleevi can we reopen this?

**Comment by sleevi** [comment]
Please see https://github.com/publicsuffix/list/pull/46#issuecomment-206038288

**Comment by jsloyer** [comment]
@sleevi sorry for not responding...

So here are some examples.

customerxyz.mybluemix.net
abc123.mybluemix.net

customerxyz.eu-gb.mybluemix.net
abc123.eu-gb.mybluemix.net

customerxyz.au-syd.mybluemix.net
abc123.au-syd.mybluemix.net

Additionally in the future there will by additional domains.  Where xxxxxx is a datacenter.
customerxyz.xxxxxx.mybluemix.net
abc123.xxxxx.mybluemix.net

**Comment by sleevi** [comment]
@jsloyer I can't re-open this because the original repository appears to have been deleted, but it *sounds* like what you want is:

`mybluemix.net`

for now.

Unfortunately, as structured, that will significantly impair your ability to (safely) launch new datacenters, because any addition of `xxxxxxx` can take up to 18 months to propagate to applications. In essence, I would strongly encourage you to consider segregating your customer 3LDs and your internal-naming 3LDs. We can proceed as proposed, but with the overhead for turning something up, it does seem... less than ideal.

**Comment by sleevi** [comment]
In any event, you'll need to open a new PR that follows https://github.com/publicsuffix/list/wiki/Guidelines since I don't believe GitHub can recover this one.

**Pull request closed without merging**
