### PR TITLE
Updates to NIXI `.in` subspace in ICANN section of PSL

### PR DESCRIPTION
**Pull request by kansal15**
### Checklist of required steps

* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] Run Syntax Checker (make test)

**Description of Organization**
===
NIXI is a not for profit Organization under section 8 of the Companies Act 2013, and was registered on 19th June, 2003. NIXI was set up for peering of ISP's among themselves for the purpose of routing the domestic traffic within the country, instead of taking it all the way to US/Abroad, thereby resulting in better quality of service (reduced latency) and reduced bandwidth charges for ISP's by saving on International Bandwidth. NIXI is managed and operated on a Neutral basis, in line with the best practices for such initiatives globally.
Organization Website: https://registry.in/

**Reason for PSL Inclusion**
===
As per info available here - https://registry.in/policies 

Unlimited registrations are available in the following zones.
.in
co.in
net.in
org.in
firm.in
gen.in (general)
ind.in (individuals)
5g.in
6g.in
ai.in
am.in
bihar.in
biz.in
business.in
ca.in
cn.in
com.in
coop.in
cs.in
delhi.in
dr.in
er.in
gujarat.in
info.in
int.in
internet.in
io.in
me.in
pg.in
post.in
pro.in
travel.in
tv.in
uk.in
up.in
us.in
 

Results of Syntax Checker (`make test`)
===
Testsuite summary for libpsl 0.21.1
TOTAL: 5
PASS:  5
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

### CODE REVIEW

**Comment by dnsguru** [comment]
@kansal15 are you with NIXI?

**Comment by dnsguru** [comment]
associated : #1576

**Comment by kansal15** [comment]
> @kansal15 are you with NIXI?

@dnsguru Not with NIXI but working closely with them. if u need some sort of approval or confirmation from NIXI before merging this, then please let me know.

**Comment by kansal15** [comment]
@dnsguru 
DNS TXT records are added.

```
% dig _psl.6g.in TXT +short  @1.10.10.10
"https://github.com/publicsuffix/list/pull/1588"

% dig _psl.5g.in TXT +short @1.10.10.10 
"https://github.com/publicsuffix/list/pull/1588"
```

**Comment by dnsguru** [comment]
@kansal15 
do you seek to narrow the request down to the 5g.in and 6g.in namespaces?  

The guidelines require that would need to see the txt records added to all of the requested etld+

**Comment by kansal15** [comment]
DNS TXT records added for all the suffixes. Just for info, i shows the output of those two.

**Comment by kansal15** [comment]
@dnsguru 
TXT records for all the new suffixes --- 

```
% for i in ` cat temp`; do echo $i ;dig _psl.$i TXT +short @1.10.10.10 ; done 
5g.in
"https://github.com/publicsuffix/list/pull/1588"
6g.in
"https://github.com/publicsuffix/list/pull/1588"
ai.in
"https://github.com/publicsuffix/list/pull/1588"
am.in
"https://github.com/publicsuffix/list/pull/1588"
bihar.in
"https://github.com/publicsuffix/list/pull/1588"
biz.in
"https://github.com/publicsuffix/list/pull/1588"
business.in
"https://github.com/publicsuffix/list/pull/1588"
ca.in
"https://github.com/publicsuffix/list/pull/1588"
cn.in
"https://github.com/publicsuffix/list/pull/1588"
com.in
"https://github.com/publicsuffix/list/pull/1588"
coop.in
"https://github.com/publicsuffix/list/pull/1588"
cs.in
"https://github.com/publicsuffix/list/pull/1588"
delhi.in
"https://github.com/publicsuffix/list/pull/1588"
dr.in
"https://github.com/publicsuffix/list/pull/1588"
er.in
"https://github.com/publicsuffix/list/pull/1588"
gujarat.in
"https://github.com/publicsuffix/list/pull/1588"
info.in
"https://github.com/publicsuffix/list/pull/1588"
int.in
"https://github.com/publicsuffix/list/pull/1588"
internet.in
"https://github.com/publicsuffix/list/pull/1588"
io.in
"https://github.com/publicsuffix/list/pull/1588"
me.in
"https://github.com/publicsuffix/list/pull/1588"
pg.in
"https://github.com/publicsuffix/list/pull/1588"
post.in
"https://github.com/publicsuffix/list/pull/1588"
pro.in
"https://github.com/publicsuffix/list/pull/1588"
travel.in
"https://github.com/publicsuffix/list/pull/1588"
tv.in
"https://github.com/publicsuffix/list/pull/1588"
uk.in
"https://github.com/publicsuffix/list/pull/1588"
up.in
"https://github.com/publicsuffix/list/pull/1588"
us.in
"https://github.com/publicsuffix/list/pull/1588"
```

**Comment by dnsguru** [comment]
@kansal15 
Please also verify the _psl TXT record in .in and .co.in as well 
Also, this requires further verification as it eliminates .gov.in .mil.in .edu.in and ac.in without relocating them elsewhere in the PSL, which could have adverse impact upon those systems and services, so it will be necessary to either place _psl TXT records into those.  

GREAT CARE is taken in review when changes are proposed to acedemic, military or goverenment resources.

**Comment by dnsguru** [comment]
upon review of the section header :

```
// Please note, that nic.in is not an official eTLD, but used by most
// government institutions.
```

It sounds like that namespace had or has Governmental use.  Please count nic.in as well as the other strings being proposed to remove as part of this PR in that list of names requiring _psl txt record.

**Comment by kansal15** [comment]
@dnsguru Many thanks for figuring out the issue. Somehow while sorting the values, few domains got missed.

Now,  i have added these additional domains in the PR -- 

```
ac.in
edu.in
gov.in
mil.in
nic.in
res.in
```

Kindly have a look.

**Comment by dnsguru** [comment]
@kansal15  I have been busy and I volunteer here so it gets cycles when I am able.  I spot checked _psl.gov.in and _psl.nic.in and got NX responses so it seems those are not configured and can't proceed until those are all good.

**Comment by dnsguru** [comment]
Submitter has furnished/evidenced connection/nexus with the authoritative body for the .in TLD through the validation of the PSL records in the following manner:

### 1 Top Level Authoritative Data.   
IANA [IANA Root Zone DB entry for .in](https://www.iana.org/domains/root/db/in.html) lists the following:
```Registry Information
URL for registration services: http://www.registry.in/
WHOIS Server: whois.registry.in
```
### 2 Subsequent, Connected Linkage.
The IANA-Listed registration services domain at the URL above, registry.in, has a [Policy URL which articulates the list of available namespaces](https://www.registry.in/policies) that matches that of the PR.

### 3 _PSL TXT Record Validation
The URL of the PR was added into a TXT record for the DNS for the namespaces that are listed in the policies URL above.  The matching information in the TXT record at the apex of the affected zones have been validated against a number of public resolvers.  This is believed to be appropriate "connective tissue", signaling that the authoritative body, NIXI / Registry.in as listed in the IANA:

- Are aware of this pull request
- Understand the affectation of this pull request
- Consent to/Approve this pull request

**Comment by dnsguru** [comment]
I have validated that the requested additions do not exist in other locations within the PSL

**Comment by dnsguru** [comment]
> @kansal15 I have been busy and I volunteer here so it gets cycles when I am able. I spot checked _psl.gov.in and _psl.nic.in and got NX responses so it seems those are not configured and can't proceed until those are all good.

I see these were re-added, I had expressed a concern with the removals requiring there be _PSL DNS entries in order to really really really really be sure that these were intentional removals, but seeing as these are remaining, the requirement to validate them is no longer necessary.

**Review by dnsguru — APPROVED** [review]
- ICANN Section Change - Top-Down validation confirmed via IANA->Registry->DNS
- Tests Pass
- Conforms to Guidelines
- No Conflict with Base

APPROVED

**Comment by dnsguru** [comment]
Thanks for your patience in handling this.  
@kansal15 this is being merged.  

Great care is taken to ensure that parties connected to the delegated administrative authority are involved for changes to ICANN section entries.  Additionally, anything related to impacts of removal, addition or change to gov/mil or such (which was briefly the case) receive VERY close review and higher levels of validation.

Because the PR dialog is public record, there is a desire to have the community be able to view the raionale and results of review and approvals when it relates to affectation on an ICANN section TLD.

Also, this is a project that receives volunteer sourcing for the updates, which can take longer.  That said, I have had the privilege of visiting India and working with exceptional professionals like yourself who use this namespace as their choice of domain, so I prioritized this and put in additional effort to ensure it would not create unintentional disruption.

**Comment by RohanD-GD** [comment]
Many thanks @dnsguru @kansal15 ....

**Pull request merged**
