### PR TITLE
Add geodomains Faitid registry

### PR DESCRIPTION
**Pull request by AlexeySa**
Registry: https://faitid.org/ru/node/346 http://faitid.org/en/node/367
Registrars: http://faitid.org/en/node/597

### CODE REVIEW

**Comment by weppos** [comment]
Hi @AlexeySa,

Please have a look at our guidelines for submission
https://github.com/publicsuffix/list/wiki/Guidelines
and update your PR accordingly.

**Comment by AlexeySa** [comment]
Hi@weppos , 

Could you help me? I do not know what to add here.

**Comment by weppos** [comment]
@AlexeySa according to our [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), only the domain owners can submit them. There is also a procedure required to validate each domain with DNS records.

Are you the owner of these domains?

**Comment by weppos** [comment]
Duplicate of https://github.com/publicsuffix/list/pull/384

**Pull request closed without merging**
