### PR TITLE
Add dyndns.dappnode.io

### PR DESCRIPTION
**Pull request by vdo**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://dappnode.io/

I'm a software and systems engineer working at DAppNode.
DAppNode is a solution to allow users to conveniently host P2P and distributed technologies on their own hardware, with focus on blockchain and cryptocurrency projects.

DAppNode software is an open-source platform developed by the non-profit association DAppNode association in Zug, Switzerland. DAppNode Association is driven and funded by the community, at the moment we have three grants from EF, Aragon, and ECF, but the association also has sustainability sources relying on projects that want their package uploaded to DAppNode and featured in the installer section, or the selling of hardware with DAppNode preinstalled which implies a donation to the association for every piece of hardware with DAppNode pre-installed sold, we are also backed by individual donors and supporters.

Reason for PSL Inclusion
====

We offer a dynamic DNS service to our users so they can easily access their hardware running at home. Hosted services and APIs can be reachable through a VPN, but we also want to expose them using domains with the form <userid>.dyndns.dappnode.io so users can host their own services. Those can be full nodes, hosted cloud storage, dsitributed apps (DApps), IPFS gateways, etc.
We want to improve cookie security of such services, and identify them as part of their own dynamic domain recognized as a public suffix. We also want to add SSL security to them and this inclusion would make it easier to generate Let's Encrypt certificates in case it's needed.

DNS Verification via dig
=======

    dig +short TXT _psl.dyndns.dappnode.io
    "https://github.com/publicsuffix/list/pull/912"

make test
=========

The test passed successfully

### CODE REVIEW

**Comment by sleevi** [comment]
I'm unable to validate this PR via `_psl.dyndns.dappnode.io`

**Comment by vdo** [comment]
> I'm unable to validate this PR via `_psl.dyndns.dappnode.io`

Can you please try again?

**Comment by vdo** [comment]
@sleevi The DNS record was added again.

**Comment by dnsguru** [comment]
> @sleevi The DNS record was added again.

Validated
```
>nslookup -type=txt _psl.dyndns.dappnode.io
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.dyndns.dappnode.io text =

        "https://github.com/publicsuffix/list/pull/912"
```

**Pull request merged**
