### PR TITLE
Add more Lukanet Ltd domains

### PR DESCRIPTION
**Pull request by lukavia**
We are expanding our service and add 15 more domains

### CODE REVIEW

**Comment by frju365** [comment]
And barsy.me seem to be even not registered.

**Comment by lukavia** [comment]
Done. 
We had to fix the nameservers for barsycenter.com with the registrar, so this might take up to 48 hours for you to see it because of caching. 
barsy.me was registered but, there was a problem in the slaves dns witch is now fixed and the change should be visible immediately

**Comment by lukavia** [comment]
I've verified with an outside server that all the records are visible now. 

```
~# for d in barsy.co.uk barsyonline.co.uk barsycenter.com barsy.club barsy.info barsy.io barsy.me barsy.menu barsy.mobi barsy.org barsy.pro barsy.pub barsy.shop barsy.site barsy.uk
> do
> host -t txt _psl.$d
> done
_psl.barsy.co.uk descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsyonline.co.uk descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsycenter.com descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.club descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.info descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.io descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.me descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.menu descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.mobi descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.org descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.pro descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.pub descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.shop descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.site descriptive text "https://github.com/publicsuffix/list/pull/596"
_psl.barsy.uk descriptive text "https://github.com/publicsuffix/list/pull/596"

```

**Comment by sleevi** [comment]
Please be aware that we are exploring the potential to limit the number of entries a given site may have, due to the size constraints of PSL consumers. While I will merge this PSL, future expansions may need to be denied.

**Pull request closed without merging**
