### PR TITLE
Add app.banzaicloud.io

### PR DESCRIPTION
**Pull request by kozmagabor**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://banzaicloud.com

Banzai Cloud provide a free cloud agnostic service to simplify manage kubernetes clusters and workloads.

Reason for PSL Inclusion
====

We would like to enable our users to manage their subdomain like {orgname}.beta.banzaicloud.io
We would like all of our domain names to be compliant, including cookie handling, DNS sorting, and Let's Encrypt cert issuance

DNS Verification via dig
=======

```
dig +short TXT _psl.app.banzaicloud.io
"https://github.com/publicsuffix/list/pull/730"
```

make test
=========

Test result:
https://gist.github.com/kozmagabor/0d0fbf188602f2c030d33cd6e8eaab5e

### CODE REVIEW

**Comment by kozmagabor** [comment]
Hi @weppos,

This PR Is ready for review. Could you check it, please?

Thanks,
Gabor

**Comment by kozmagabor** [comment]
Hi Simone,

We would like to kindly ask if the information we have provided in this request fulfills the criteria for acceptance, or do we need to provide additional information. The aforementioned free service has been started at the beginning of last December, and we would like to turn this DNS feature on for our users.

Find it at https://beta.banzaicloud.com

Thank you very much
Gabor

**Comment by kozmagabor** [comment]
Any update? @sleevi @weppos @dnsguru

**Comment by weppos** [comment]
@kozmagabor before I proceed, I have a question. I see the use of `beta`. What is the expectation when the product will exit beta? Will you keep the same name? Will the list need to be re-updated?

**Comment by kozmagabor** [comment]
Hi @weppos

Thanks for looking at this PR.

We discussed your question internally and came to the conclusion that it might not make sense to use the beta domain anymore, so we updated the PR to `app.banzaicloud.io`.

Thanks a lot for the suggestion!

**Comment by kozmagabor** [comment]
Thank you!

**Pull request merged**
