### PR TITLE
Add prone.ws

### PR DESCRIPTION
**Pull request by johnsonjh**
* [X] Description of Organization
  *  Private consultant
* [X] Reason for PSL Inclusion
  * GitLab/GitHub Pages-style hosting for different clients.
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place
  *  The prone.ws domain has been registered since 2012 and has more than two years remaining, and I intended to continue to maintain this registration in good standing. 

__Submitter affirms the following:__ 
  * [X] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

  *  Private consultant

Organization Website: 

* https://keybase.io/trnsz
* https://ban.ai/
* https://prone.ws/

Reason for PSL Inclusion
====

  *  The prone.ws domain has been registered since 2012 and has more than two years remaining, and I intended to continue to maintain this registration in good standing. PSL listing for Cookie security / GitLab/GitHub Pages-style hosting.

DNS Verification via dig
=======

Done

make test
=========

Done.

### CODE REVIEW

**Comment by johnsonjh** [comment]
Not IOS-FB related

**Comment by dnsguru** [comment]
Thank you for overtly stating this is not attempting to bypass the rate
limits and functionality in ios/fb.

Can you please provide better information on the purpose and rationale, as
well as the number of affected parties estimated by this change?

**Comment by johnsonjh** [comment]
Yes, 

Currently, my plan is to reverse proxy client sites (client1.prone.ws, test1.client1.prone.ws) and would like to have an additional level of separation - mostly for cookies - between other client sites, as another level of assurance against misconfigurations, as I will not directly administer every service.

Currently this would only affect myself and four client subdomains - submitting the listing with PSL was requested by one of the clients.  I also plan to make use of this kind of arrangement more in the future.

I currently host a personal website at prone.ws with links to some of my own (non-professional and open-source projects). I plan to change the prone.ws site to a simple landing page and move my personal site to a subdomain as described above.

I hope this is an acceptable use of the PRIVATE area of the PSL.

**Comment by johnsonjh** [comment]
I have also switched to using a wildcard certificate for *.prone.ws via Lets Encrypt. As Let's Encrypt allows issuing a top-level for PRIVATE area listings; it isn't the intention to bypass any rating limiting and individual subdomain certificates would be extremely rare.

**Comment by dnsguru** [comment]
This is a globally circulated file that gets incorporated into browsers and
systems; requests for smaller scale, lab/tinker/experiments or temporary
projects get rejected - to respect the modesty of the file size and
downloads.

**Comment by johnsonjh** [comment]
> lab/tinker/experiments or temporary
projects get rejected - to respect the modesty of the file size and
downloads.

I can respect that and you may close the request if you wish.  

For the record, I don’t believe this qualifies as a lab/tinker/experiment, but it will be temporary and I can never see having more than 10 active client projects at any one time. 

However, I have clarified why the public suffix listing is important to the client, and was pointed to the following bug report for Chrome (a browser I do not use) which, shockingly - or perhaps not - has been an ongoing saga and open for nearly eight years:

https://bugs.chromium.org/p/chromium/issues/detail?id=383910

Apparently, using the Chrome password manager has caused the employees to submit incorrect username and passwords to different internal servers (staging and dev environments) and an extremely frustrating experience.

I should also note, while I can do everything “right”, the behavior of the browser is seemingly random at best and unsafe and hostile at worst, and while this should not be happening or a problem, it apparently has been, and has been for the better part of a decade.

I’m not contesting your decision or policies, and I understand your position.

However, when Google is shipping a broken browser, with autofill heuristics so complicated that apparently many developers and even Google employees unable to understand them, and with a publicsuffix entry (which seems to be the only way to successfully mitigate the problem, according to my current clients) unavailable, I’m not sure I can do anything reasonable.

For now, better understanding the problem, I will register a separate project domains for each client and for each project, or, I will have the clients who already own their own domains handle DNS themselves or setup delegation.

I imagine you’ll be getting a lot more of these requests, as the client requesting the listing is a very large and well known company. On the flip side, they are large enough to buy throwaway domains.

It’s unfortunate that the dominant browser vendor is shipping a “security feature” that is  involved in actually leaking credentials with no clear solution for so long, and no workaround besides a PSL listing.

I’ve encouraged my clients to complain to Google directly and not request their consultants to bother the volunteers of this project, but this is probably a waste of time if the past is any indication.

I’ll take the listing if available, as I believe my usage meets all technical criteria and terms.

I’m also afraid if you accept it, then Google will never fix their broken software.

Thanks for your time and maintaining this resource.

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base
- Formatted / Sorted per Guidelines

**Approved**

**Comment by dnsguru** [comment]
Scale of project prevents this from proceeding but all other aspects would have been approved - this was well formed and formatted and identified the rationale and org authentically and completely.  Putting this in the notes for reference.

**Pull request closed without merging**
