### PR TITLE
Add ticket.io

### PR DESCRIPTION
**Pull request by ChristianFranke**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://ticket.io

We are a ticket service provider and sell tickets on behalf of our clients (event organizers). Registered event organizers get their own subdomain (e.g. username.ticket.io) on which their shop are hosted.

Reason for PSL Inclusion
====

We'd like to properly isolate each subdomain to prevent global cookie setting on ticket.io and highlight that each subdomain hosts sites of a different user, unrelated to the others.

DNS Verification via dig
=======

```
dig +short TXT _psl.ticket.io
"https://github.com/publicsuffix/list/pull/1277"
```

make test
=========

```
============================================================================
Testsuite summary for libpsl 0.21.0
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by sleevi** [comment]
Are you aware that this can, in some applications, prevent accessing your website (`ticket.io`)? Or that it can create issues since I notice you have several "operational" related domains (e.g. `backstage.ticket.io` will be isolated from `landing.ticket.io`)?

In general, hosting user-generated content on the same registerable domain as your brand (that is, having `user.ticket.io` in addition to telling users to visit `ticket.io`) is almost certainly going to cause compatibility issues for you, and once they happen, it may be a year or longer to get those resolved.

If you're absolutely certain you want to jeopardize your brand and website, we can continue, but wanted to make sure you understood some of the "worst possible" cases here.

**Comment by dnsguru** [comment]
@ChristianFranke please read the [question above](https://github.com/publicsuffix/list/pull/1277#issuecomment-819871151) and respond...  we're trying to clarify and identify that you understand the impact this will have on cookies for ticket.io and you'd like this to proceed, and your response is the step that is blocking this from proceeding forward.

**Comment by dnsguru** [comment]
Q: @ChristianFranke please review #1245 and the contributing guidelines (link below)

Can you confirm that this request is not related to working around the IOS/FB issue? 

Can you confirm that this request adheres to the guidelines?

**Comment by dnsguru** [comment]
@ChristianFranke we'll go ahead and close this without responses in the next few days.

Please answer the following which are true:
__Submitter affirms the following:__ 
  * [ ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [ ] This request was _not_ submitted with the objective of working around other third party limits
  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting
  
  Update your rationale or add it into the conversation if there's adjustments to be made.

**Comment by n8schloss** [comment]
@ChristianFranke, is this related to iOS 14 and Facebook advertising? If so please see the information below:

Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift.

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
@ChristianFranke going to close this due to non-response - if this was done in error, reopen this, read the comment thread and respond to the questions that were asked - OR - if you were seeking to address the issue of IOS/FB, follow the path that is outlined in the comments above via the facebook link.

**Comment by ChristianFranke** [comment]
We would like to change ticket.io to tickets.io, can I open a new pull request?

**Comment by bedfordsean** [comment]
@ChristianFranke please follow the guidance on the previous comment to determine the right course of action to take. This pull request was never actioned and "ticket.io" is not in the public suffix list today due to non-response: 


> @ChristianFranke going to close this due to non-response - if this was done in error, reopen this, read the comment thread and respond to the questions that were asked - OR - if you were seeking to address the issue of IOS/FB, follow the path that is outlined in the comments above via the facebook link.

**Comment by dnsguru** [comment]
Ah, you are alive.  

Suggest you start a new PR, follow the guidelines and respond to the questions asked within THIS pr that we never received answers to.  

Do reference this pr in any new one.

**Pull request closed without merging**
