### PR TITLE
Add pgs.sh and tuns.sh

### PR DESCRIPTION
**Pull request by neurosnap**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits
  * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

**pico.sh** provides manages services for users to host static websites, images, and reverse-proxy/tunneling service that allows developers to expose local servers at a public endpoint.  Customers are given many subdomains on our primary service domains (pgs.sh and tuns.sh).

My name is Eric Bower and I'm the cofounder of pico.sh.

Organization Website: 

https://pico.sh

Reason for PSL Inclusion
====

The primary reason is prevent external site owners from setting cookies on our domain.

Number of users this request is being made to serve:

- 3176 (as of today)

DNS Verification via dig
=======

```
dig +short TXT _psl.pgs.sh
"https://github.com/publicsuffix/list/pull/2038"
```

```
dig +short TXT _psl.tuns.sh
"https://github.com/publicsuffix/list/pull/2038"
```

Results of Syntax Checker (`make test`)
=========

I ran the test and everything passed.

### CODE REVIEW

**Comment by simon-friedberger** [comment]
* [ ] Expiration (Note: Must STAY >2y at all times)
  * [ ] tuns.sh expires 2026-07-11
  * [ ] pgs.sh expires 2026-07-06
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [ ] Reasoning/Organization description
* [x] Non-personal email address

**Comment by simon-friedberger** [comment]
> 3176 (as of today)

Is this the amount of users who have signed up, the amount of users who are accessing sites, the amount of users who currently have sites or something else?

**Comment by neurosnap** [comment]
Hi!  I just purchased another year for both domains.

> Is this the amount of users who have signed up, the amount of users who are accessing sites, the amount of users who currently have sites or something else?

This is the total number of users that have the ability to deploy sites on our platform.

Happy to answer any followup questions.

Thanks for taking the time to look at this!

**Comment by simon-friedberger** [comment]
Could you provide how many users actually have sites?

**Comment by neurosnap** [comment]
Sure!

Total users with live sites at the moment: 282

**Comment by simon-friedberger** [comment]
Unfortunately, that doesn't meet our current requirements.

> Projects that are smaller in scale or are temporary or seasonal in nature will likely be declined. Examples of this might be private-use, sandbox, test, lab, beta, or other exploratory nature changes or requets. It should be expected that despite whatever site or service referred a requestor to seek addition of their domain(s) to the list, projects not serving more then thousands of users are quite likely to be declined.

We're currently usually accepting projects with as few as 1k users because the size of the PSL is extremely small compared to the current scale of the internet but that is the current bar. Feel free to re-open once you have reached that or if you have some other argument why you think inclusion is particularly important in this case.

**Pull request closed without merging**
