### PR TITLE
Please add koobin.events to the PSL

### PR DESCRIPTION
**Pull request by ioliva**
This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we seek to resolve the impacts to the best of our ability to do so. Both Apple and Facebook support Public Suffix List for Private Click Measurement and Aggregated Event Measurement respectively.

* We have reviewed the wiki here outlining the PSL and understand what it is and is not.
* We have reviewed this matter with the team at Facebook, we are now fully aware about the consequences to the change we are requesting as it relates to cookies or other services, and choose to proceed in submitting this PR. We understand that despite reviewing the matter with Facebook, Facebook cannot control which use cases get accepted to the PSL
* We understand that there is not any urgency and should this PR be merged to include our requested change, that there is no control over the timing of this change being updated downstream in browsers, libraries, certificate authorities or other systems or processes that incorporate the PSL.
* We understand that if we later want to back out this change, there is also no guarantee that this will occur in a rapid fashion due to the same lack of control over browser, library, certificate authority, or other system or process changes.

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://www.koobin.com

I'm Iván Oliva, developer at KoobinEvent, SL. We provide a ticketing platform for third parties, as SaaS. These third parties can be theaters, sports clubs, operas, concert halls and so on.

Reason for PSL Inclusion
====

Our clients ticketing sites are currently published on subdomains of one of our domains (koobin.cat, koobin.com, koobin.es). However, some of our clients have expressed interest on proper Facebook pixel tracking with iOS 14.5 and above. That's why, after reviewing your guidelines and consulting with Facebook, we have reserved a new koobin.events domain, where we will migrate those clients to. By the way, our clients' website run independently, so they must not share cookies between them.

Besides, we will not run any website directly on koobin.events, since our corporate website runs under www.koobin.com.

I hereby confirm that our koobin.events domain, although reserved last July,  maintain more than 4 years registration term at the time of this PR (until 6/29/2026).

I will be glad to further clarify my petition if there is still any doubt about it.

DNS Verification via dig
=======

DNS verification added:

```
dig +short TXT _psl.koobin.events
"https://github.com/publicsuffix/list/pull/1462"
```

make test
=========

Test ran.

Thanks a lot in advance.

### CODE REVIEW

**Comment by dnsguru** [comment]
Please read https://github.com/publicsuffix/list/issues/1245#issuecomment-981883312

**Comment by ioliva** [comment]
Thanks. Already read your comment. If I have understood well, this will be merged at the end of this week, on or about December 3rd. Right?

**Comment by bedfordsean** [comment]
Confirming from the Facebook perspective that we have carried out our checks, and to the best of our ability to understand, Base is a legitimate platform hosting use case that caters to multiple subdomain businesses and therefore has a legitimate reason to be placed on to the PSL for the purposes of cookie separation for each of those subdomains.

**Comment by dnsguru** [comment]
Per notes in #1245 , seeing no objections, another small subgroup of submitted PR related to the IOS PCM changes and the effect on certain Facebook/Meta pixel clients that have been patienly waiting in the queue will proceed, assuming their _PSL entries and all of the other standard conditions of approval were met.

**Review by dnsguru — APPROVED** [review]
- Tests Pass
- DNS Validated
- Properly formatted
- Appropriate Rationale
- No Conflict with base

APPROVED

**Comment by dnsguru** [comment]
@ioliva @bedfordsean this is being merged per notes in #1245 - please watch for adverse impacts

**Pull request merged**
