### PR TITLE
Add edu.mu and biz.mu, sort .mu suffixes

### PR DESCRIPTION
**Pull request by dge9**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====
.mu ccTLD administered by MUNIC: [http://nic.mu](http://nic.mu)
Wikipedia: [https://en.wikipedia.org/wiki/.mu](https://en.wikipedia.org/wiki/.mu)

Reason for PSL Inclusion
====
.edu.mu and .biz.mu subdomains recently made available under .mu ccTLD. Adjust existing subdomains to sort alphabetically.

DNS Verification via dig
=======
N/A

make test
=========
Ran and passed.

### CODE REVIEW

**Comment by dge9** [comment]
@weppos Good morning, I do not represent NIC.MU but I have corresponded with them regarding setup of the .edu.mu suffix. I have requested an official reference and will update when I hear back. Thanks.

**Comment by weppos** [comment]
>  I have requested an official reference and will update when I hear back. Thanks.

Much appreciated. Thank you.

**Comment by dge9** [comment]
@weppos Good afternoon, my requests to the registry have unfortunately not yet been met with an official reference. Is it possible to proceed on the basis that the NS and SOA records for edu.mu are consistent with established TLDs such as net.mu and org.mu? I note that for some reason this is not the case for biz.mu which I am happy to remove from the pull request.
Thanks.

**Comment by weppos** [comment]
@dge9 unfortunately, I won't be able to proceed without an official confirmation from the MU registry. I am closing for now, feel free to reference this PR to them for follow up.

Thanks for the help.

**Pull request closed without merging**
