### PR TITLE
Add on-aptible.com public suffix

### PR DESCRIPTION
**Pull request by krallin**
Hey there!

We'd like to add on-aptible.com to the Public Suffix List. The admin email on the whois records for the domain can be used to reach us (through whoisguard).

Is there anything else needed from us? 

Thanks!

--

cc @fancyremarker @aaw

### CODE REVIEW

**Comment by krallin** [comment]
Hey folks,

How can I possibly help move this forward? I'm at a bit of a loss here, and we've been waiting for a really long time.

Are we missing some form of validation that should have been done prior to making the pull request? The instructions at https://publicsuffix.org/submit/ suggest we've done exactly what should have been done, but please let me know if there are other docs I should be looking at?

Thanks!

**Comment by sleevi** [comment]
The best way to help this is to ensure there are no conflicts (there are right now) and that the patch is formatted and authenticated based on the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

**Comment by krallin** [comment]
Thanks @sleevi. I figured there might be some instructions on validation somewhere :)

I made the two changes you asked for.

**Comment by sleevi** [comment]
The header is still not formatted according to the Guidelines. The date in particular stands out.

**Comment by krallin** [comment]
Sorry about that. I did not realize the guidelines had changed since I originally made the PR.

Thanks!

**Comment by sleevi** [comment]
Verified via TXT

**Comment by krallin** [comment]
Thanks @sleevi !

**Pull request merged**
