### PR TITLE
Update public_suffix_list.dat - Existing Section

### PR DESCRIPTION
**Pull request by DaveMcCormack**
This is an update of the existing NymNom section.

This updates -
 
a) contact details (as per format)
b) adds new suffix to NymNom section

Thank you for your time,

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: nymnom.com

Reason for PSL Inclusion
====

This is an update of the existing NymNom section.

This updates -
 
a) contact details (as per format)
b) adds new suffixes to NymNom section

Thank you for your time,

DNS Verification via dig
=======

THIS IS CORRECT -
RESOLVES TO -

dig +short TXT _psl.nom.bz
"https://github.com/publicsuffix/list/pull/940"

dig +short TXT _psl.nom.lv
"https://github.com/publicsuffix/list/pull/940"

make test
=========

THIS IS CORRECT - NO ERRORS DETECTED

### CODE REVIEW

**Comment by DaveMcCormack** [comment]
The DNS verification TXT record has been completed and is verifiable.

All tasks have been completed.

Please inform if any other tasks are needed.

Thank you for your time,

**Comment by dnsguru** [comment]
Reviewed.  Unfortunately, both _psl.nom.lv and _psl.nom.bz are returning **NXD** on the validation on quad 1 8 and 9

**Comment by dnsguru** [comment]
@DaveMcCormack please reactivate the _psl DNS entries to validate - these are returning NXD and it is not possible to validate as result

**Comment by DaveMcCormack** [comment]
Good morning,

Thank you for your reply.

I am not sure what went wrong there.

The DNS verification TXT record has been completed and is verifiable.

The DNS verification TXT record(s) can be found at -
_psl.nom.bz
_psl.nom.lv

Please verify the DNS TXT records to complete inclusion of domains in the 'PSL'.

As this issue was literally 10 hours ago, and has been fixed, can this be completed today?
This request is over 2 months old.
Having to wait again, is a bit pointless.

Can you verify the DNS TXT records today, and complete inclusion of domains in the 'PSL' today, please?

Thank you for your time,

**Comment by dnsguru** [comment]
DNS verification checks out 
all tests pass
no white space issues
S+M

**Comment by dnsguru** [comment]
Chain of related PR: #425 #771 #823

**Pull request merged**
