### PR TITLE
add botdash domains

### PR DESCRIPTION
**Pull request by inventorgg**
# Public Suffix List (PSL) Submission

### Checklist of required steps

* [X] Description of Organization
* [X] Robust Reason for PSL Inclusion
* [X] DNS verification via dig

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the `_psl` TXT record in place in the respective zone(s).

__Submitter affirms the following:__ 

 * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

 * [X] This request was _not_ submitted with the objective of working around other third-party limits.

 * [X] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, and responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

 * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms to them.
 * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting.

 * [X] A role-based email address has been used and this inbox is actively monitored with a response time of no more than 30 days.

**Abuse Contact:**

* [X] Abuse contact information (email or web form) is available and easily accessible.

  URL where abuse contact or abuse reporting form can be found: https://inventor.gg/legal/terms
  

---

For PRIVATE section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*. I could break my organization's website cookies and cause other issues, and the rollback timing is acceptable. *Proceed anyways*.
---

## Description of Organization

We provide a no-code platform for the development and hosting for Discord bots. One of the features we offer is called BotDash, which allows Inventor bot developers to create web dashboards. From these dashboards, their users can manage settings on Inventor-created Discord bots.

**Organization Website:**

https://inventor.gg

## Reason for PSL Inclusion

We allow the registration of subdomains on our BotDash domains. Currently, we provide a very limited BotDash feature (using only pre-made components) but wish to expand this to allow users to write custom HTML/CSS/JS and directly handle server-side actions. In order to ensure cookie security and privacy between different BotDash sites on the same root domain, we wish for our BotDash domains to be included in the PSL.

**Number of users this request is being made to serve:**

We currently serve around 2k active/registered BotDash sites (with the current limited/beta version of BotDash).

## DNS Verification

```
dig +short TXT _psl.botdash.app
"https://github.com/publicsuffix/list/pull/2342"
```

```
dig +short TXT _psl.botdash.dev
"https://github.com/publicsuffix/list/pull/2342"
```

```
dig +short TXT _psl.botdash.gg
"https://github.com/publicsuffix/list/pull/2342"
```

```
dig +short TXT _psl.botdash.net
"https://github.com/publicsuffix/list/pull/2342"
```

```
dig +short TXT _psl.botda.sh
"https://github.com/publicsuffix/list/pull/2342"
```

```
dig +short TXT _psl.botdash.xyz
"https://github.com/publicsuffix/list/pull/2342"
```

### CODE REVIEW

**Comment by wdhdev** [comment]
All looks good to me, all domains are > 2y expiry, all _psl TXT records are in place. The only thing I want to mention is that the abuse contact is not easily findable from the homepage of https://inventor.gg, if you could add a link in the footer, or something similar, that would be good.

**Comment by wdhdev** [comment]
That was fast! Amazing, thank you. I think this is all we need, this PR LGTM.

@groundcat Any comments?

**Comment by groundcat** [comment]
- [x]  Expiration (Note: Must STAY >2y at all times)
  - botdash.app 2027-02-18
  - botdash.dev 2027-02-18
  - botdash.gg N/A
  - botdash.net 2027-02-17
  - botda.sh 2027-08-03
  - botdash.xyz 2027-02-17
- [x]  DNS _psl entries (Note: Must STAY in place)
- [x]  Sorting
- [x]  Reasoning/Organization description
- [x]  Non-personal email address
- [x]  Abuse contact

**Comment by simon-friedberger** [comment]
Do more domains somehow increase search ranking or what is the point of having all these different domains all redirecting to inventor.gg?

**Comment by groundcat** [comment]
Hello @inventorgg I notice that **none** of your domains (botdash.app, botdash.dev, botdash.gg, botdash.net, botda.sh, and botdash.xyz) currently have the required _psl TXT DNS records pointing to PR #2342. According to the PSL guidelines, maintaining these records is necessary for continued inclusion in the list. Could you please restore these DNS records to ensure your domains remain properly listed in the PSL?

**Pull request merged**
