### PR TITLE
nic.it - update regions and provinces

### PR DESCRIPTION
**Pull request by daftano**
Update TLDs from nic.it in compliance with version 7.1 of Italian Regulation assignation.
In particular:

regions are listed in Appendix A;
provinces are listed in Appendix B.

Municipalities are omitted due to limits and constraints of PSL. See also #519 for further discussions.

### CODE REVIEW

**Comment by gsmember** [comment]
@daftano 
Hello,
I found two other domains that should be added:
cles.tn.it
cles.trento.it

**Comment by daftano** [comment]
@weppos @sleevi @pzb any thoughts about this pull request?

**Comment by sleevi** [comment]
Thanks for the detailed pull request and relevant links. I confirmed that 7.1 is the current in-force policy doc.

**Comment by dnsguru** [comment]
#519 see also

**Pull request merged**
