### PR TITLE
Add multiple Akamai domains to the PSL

### PR DESCRIPTION
**Pull request by enygren**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS
validation and syntax checking, as well as a number of acknowledgements
from the submitter.  This template must be included with each PR, and
the submitting party MUST provide responses to all of the elements in
order to be considered.

### Checklist of required steps

* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [ ] DNS verification via dig --- _(not possible, see below)_
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [X] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [X] This request was _not_ submitted with the objective of working around other third-party limits

  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Akamai started as one of the largest Content Delivery Networks (CDNs)
in the world.  Today we provide a wide range of security, performance,
compute, and content delivery services for many of the world's largest
companies.

This PR is being submitted by a Fellow and Chief Architect at Akamai
who has been at Akamai for over 20 years.  The addition of these
domains to the Public Suffix List has been reviewed through our
Architecture Review and Change Management processes and has
received executive-level approval.

Organization Website:
https://www.akamai.com/

Reason for PSL Inclusion
====

The domains included in this change are primarily associated with
content delivery and/or load balancing services.  They are domains
where multiple independent customers/tenants are serving content with
a shared public suffix, and thus where cross-hostname cookie sharing
is not desirable from a security or end-user privacy perspective.
Some of these domains are covered by Akamai-managed wildcard TLS
certificates.

For example, some of these are common patterns where
"foo" and "bar" are hostnames from unrelated customers:

* "foo.akamaized.net" and "bar.akamaized.net"
* "example.foo.com.edgesuite.net" and "example.bar.com.edgesuite.net"
* "example.foo.akadns.net" and "example.bar.akadns.net"

We published a customer-facing public blog post explaining
to our customers why we are adding these domains to the PSL:

https://www.akamai.com/blog/developers/adding-akamai-shared-domains-to-the-public-suffix-list

Note that the "-staging" and "test.edgekey.net" domains are
all customer-facing environments which have the same
properties of multiple customers sharing a suffix.

All of these domains are mission-critical production domains
and we do not intend to ever let their registrations lapse.

Number of users this request is being made to serve:
Altogether, these hostnames are involved in serving many
trillions of HTTP(S) requests per day.

DNS Verification via dig
=======

Adding the _psl text records is not possible for many of these domains
due to the DNS load balancer implementations.
Please instead verify by contacting publicsuffixlist@akamai.com
and security@akamai.com, and/or by seeing details in our
public blog post:

https://www.akamai.com/blog/developers/adding-akamai-shared-domains-to-the-public-suffix-list

Results of Syntax Checker (`make test`)
=========

```
test_allowedchars: OK
test_dots: OK
test_duplicate: OK
test_exception: OK
test_NFKC: OK
test_punycode: OK
test_section1: OK
test_section2: OK
test_section3: OK
test_section4: OK
test_spaces: OK
test_wildcard: OK
[...]
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
[...]
PASS: test-is-public-builtin
PASS: test-is-public
PASS: test-registrable-domain
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by dnsguru** [comment]
The entries that are prefixed with com or net are triggering a "spidey sense" concern on potentially enabling sub-domain abuse scenarios based upon it enabling lookalike domains.

Can you provide some further rationale on those specific entries and _their_ use case or purpose?

Also, just observing that due to processing delay times that are resulting from how the PSL is resourced by volunteers, that the blog posting referenced in this PR was from March of 2022, but this pull request was submitted on the last day in October 2022. It seems like Akamai processing time is aligned with the PSL's turnaround capacity.

**Comment by enygren** [comment]
On the domains prefixed with com/net, for 20-year-old historical reasons there are many customer hostnames of the form: "something.example.com.edgesuite.net" (on our CDN) or "something.example.com.akadns.net" (on our global load balancer).  While we have a range of validation rules and safeguards (at least for new configurations), we have a large set of customer hostnames that have been using this structure for decades.
 
If were were to design/implement everything from scratch today with what we know, we might use hyphens instead in cases under customer control.  While these are normally used as CNAME targets from actual customer hostnames, we do have some very large sites which use hostnames of this form directly for delivery.   For example, the "Umbrella top-1M" list has multiple examples in the top-10k of hostnames with these suffixes.

The ones included on the list here are ones where analysis has determined that we have significant customer sharing of the same suffix, making it a "public" suffix.   (We'd considered including entries such as "*.edgesuite.net" and "*.*.edgesuite.net" but decided that it would introduce too much risk.)

But yes, it took quite a bit of time between performing our customer notification and blog post and until we'd done enough change safety analysis and internal review to be ready to submit this PR.  (Appreciating that the PSL is resourced by volunteers and that additions are a one-way operation for all intents and purposes, and that there may be unforseen risks, are certainly contributing factors to caution and internal review here.)

**Comment by jschauma** [comment]
Just dropping a +1 here to hopefully bubble this up in case there's anything else needed from Akamai's side. :-)

**Comment by dnsguru** [comment]
"Nudge" noted.  I am an unpaid volunteer here so these get attention when
they can, and typically are FIFO

Unfortunately with all the inflation, #mortgagepay gets focus right now.
 dropping a -1 to that which unfortunately offsets the +1

**Comment by jschauma** [comment]
Fair enough. Just let us know whenever cycles allow if there's anything else we can do.

**Comment by dnsguru** [comment]
> Just dropping a +1 here to hopefully bubble this up in case there's anything else needed from Akamai's side. :-)

@jschauma I skipped some family time to look at this again... Here's a repeat of the suggestion...

If the entries with the .com or .net prefixes are removed and submitted as a separate PR later (citing this one), it might go faster.   

Yes, understood those are for legacy customers but those are of much higher security concern due to the manner in which that a-holes use deeply nested subdomains to phish.

This PR would go faster if Akamai were to split those off into a separate request, as I'd initially identified.  Let those which don't need deeper scrutiny in security review glide through and then the .com / .net ones can get the deeper review from folks in the browser community.  With all the various shifting headcounts and forced alumnist stuff that companies are doing this year, it is all held up, and I am just volunteering here.

**Comment by tfpauly** [comment]
If splitting off the domains that don't begin with `com.` and `net.` makes it easier to make progress, that would be great.

Speaking from the perspective of a client stack that uses the PSL, having these CDN domains (including the `com.` and `net.` domains) be included is important to prevent cookie sharing, etc, across different customers of the CDN. So, I consider it to be more of a security issue to leave these off the list, than to include them.

**Comment by dnsguru** [comment]
Going to close this as it was split into #1701 and a soon to be submitted PR which had some strings that might merit closer security review

**Pull request closed without merging**
