### PR TITLE
AWS Submissions to the Public Suffix List - Q1 2023

### PR DESCRIPTION
**Pull request by aph3rson**
Description of Organization
====

Amazon Web Services is an infrastructure-as-a-service cloud computing provider.
More information about AWS is availble on our website:
[What is AWS?](https://aws.amazon.com/what-is-aws/)

**Organization Website:**  
[AWS Homepage](https://aws.amazon.com)

Reason for PSL Inclusion
====

These features/services have been identified by AWS Security and AWS service
teams as supporting different distinct customers/resources across shared
DNS suffixes. Adding these suffixes to the PSL is expected to improve the
security posture of customers using our services.

**Number of users this request is being made to serve:**  
These changes are expected to impact all customers using these AWS services.
This includes both AWS-internal and external customers. Specific user counts
for these listed features/services are not publicly available.

Services/Features in PR:
====

- Analytics on AWS
- AWS Cloud9

DNS Verification via dig
=======

<details>
<summary>DNS query results</summary>

```
dig +short -t TXT _psl.analytics-gateway.ap-northeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.analytics-gateway.eu-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.analytics-gateway.us-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.analytics-gateway.us-east-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.analytics-gateway.us-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.af-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.ap-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.ap-northeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.ap-northeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.ap-northeast-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.ap-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.ap-southeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.ap-southeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.ca-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.eu-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.eu-north-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.eu-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.eu-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.eu-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.eu-west-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.me-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.sa-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.us-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.us-east-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.us-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
dig +short -t TXT _psl.webview-assets.aws-cloud9.us-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1600"
```

</details>

Results of Syntax Checker (`make test`)
=========

<details>
<summary>Test results</summary>

```
cd linter;                                \
	  ./pslint_selftest.sh;                     \
	  ./pslint.py ../public_suffix_list.dat;
-n test_NFKC: 
OK
-n test_allowedchars: 
OK
-n test_dots: 
OK
-n test_duplicate: 
OK
-n test_exception: 
OK
-n test_punycode: 
OK
-n test_section1: 
OK
-n test_section2: 
OK
-n test_section3: 
OK
-n test_section4: 
OK
-n test_spaces: 
OK
-n test_wildcard: 
OK
test -d libpsl || git clone --depth=1 https://github.com/rockdaboot/libpsl;   \
	  cd libpsl;                                                                    \
	  git pull;                                                                     \
	  echo "EXTRA_DIST =" >  gtk-doc.make;                                          \
	  echo "CLEANFILES =" >> gtk-doc.make;                                          \
	  autoreconf --install --force --symlink;
Already up to date.
autopoint: using AM_GNU_GETTEXT_REQUIRE_VERSION instead of AM_GNU_GETTEXT_VERSION
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: linking file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: linking file 'm4/libtool.m4'
glibtoolize: linking file 'm4/ltoptions.m4'
glibtoolize: linking file 'm4/ltsugar.m4'
glibtoolize: linking file 'm4/ltversion.m4'
glibtoolize: linking file 'm4/lt~obsolete.m4'
cd libpsl && ./configure -q -C --enable-runtime=libicu --enable-builtin=libicu --with-psl-file=/__fake__/public_suffix_list.dat --with-psl-testfile=/__fake__/tests/tests.txt && make -s clean && make -s check -j4
config.status: creating po/POTFILES
config.status: creating po/Makefile
Making clean in po
Making clean in include
Making clean in src
rm -f ./so_locations
Making clean in tools
 rm -f psl
Making clean in fuzz
 rm -f libpsl_icu_fuzzer libpsl_icu_load_fuzzer libpsl_icu_load_dafsa_fuzzer
Making clean in tests
 rm -f test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain
Making clean in msvc
Making check in po
Making check in include
Making check in src
  CC       libpsl_la-psl.lo
  CC       libpsl_la-lookup_string_in_fixed_set.lo
  CCLD     libpsl.la
Making check in tools
  CC       psl.o
  CCLD     psl
Making check in fuzz
  CC       libpsl_fuzzer.o
  CC       main.o
  CC       libpsl_load_fuzzer.o
  CC       libpsl_load_dafsa_fuzzer.o
  CCLD     libpsl_icu_load_fuzzer
  CCLD     libpsl_icu_load_dafsa_fuzzer
  CCLD     libpsl_icu_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public
PASS: test-is-public-all
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-builtin
PASS: test-registrable-domain
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

</details>

### CODE REVIEW

**Comment by dnsguru** [comment]
related draft #1590 - @aph3rson  this is confusing to PSL volunteers to have parallel evolution and various drafts - respectfully requesting AMAZON (holistically) have 1 PR at a time.

**Comment by aph3rson** [comment]
@dnsguru:

> this is confusing to PSL volunteers to have parallel evolution and various drafts

We agree - however, we still only have one draft at a time. Please observe that #1590 was moved out of draft (into submitted state) on Thursday last, right around when this new draft was opened. We only ever expect to have one draft open at a time - any other PRs from AWS which are not in draft would be ready for merging whenever the PSL volunteers approve our PR(s).

We could instead operate on having a single PR at any given time, but this makes it incredibly difficult for our team/service teams to know which PR their changes will land on. We work among a number of highly-distributed service teams, who need time to deploy appropriate DNS records for the appropriate PR. When we move a PR out of draft state, we know that there are no more services which will be added to that PR (and it's ready for your team).

Does this route still work for you/your team?

**Comment by dnsguru** [comment]
We could tolerate a two at once (draft + production), but a monthly cadence is undesirable..  Please, does this close  #1403 , #1404 , #1460  to consolidate all Amazon (notice it says Amazon and not AWS) requests?  

One corporate voice helps keep the bigco domains organized, plus burns through fewer volunteer cycles as the ambition here.

**Comment by dnsguru** [comment]
Also, was just taking a high level review of #1590 - which contains 46 lines in contrast to a typical modest 3-4 and mentions 2 per month a possible cadence.  Intial reaction is that pace is more ambitious than PSL resourcing can support - Plus - you should review https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion and think in terms of lower frequency of changes for reasons beyond just the resource constraints of the project.
 
A cadence of 1/Quarter MIGHT be reasonably accomplished given the available project volunteer resources, but the bigger concern is the variance of UX that would occur with >1 different PSL versions of your section out there in the wild due to propogation timing.   That propogation timing is what it is (IE outside PSL volunteers control or influence), and 180 days tends to be the timespan for stuff to normalize across the various propogation/integrations.

REALLY encourage lower frequency for the latter architecturally, (and the former selfishly).

This is not any formal service level / SLA commitment

That pace needs to also could be impacted to factor in how large the requests are and be respectful of PR other than Amazon's being worked on, and likely 1/Year if we also have to field the non-AWS amazon requests in parallel / addition to those coming from AWS.

**Comment by aph3rson** [comment]
@dnsguru - respectfully, I'd like to keep discussions related to individual PRs on the PRs themselves, and centralize procedural discussions elsewhere. We have other service teams watching these PRs for updates, and we want to ensure we don't unnecessarily engage those folks.

To that effect, I've created #1605 for centralizing procedural discussions, and I've answered some of your questions and concerns there. I'll also be responding on #1590 to some of your points regarding that PR.

**Comment by dnsguru** [comment]
[Just a note to reviewing volunteers, this is intentionally draft and was developed as internal process at Amazon, who will update it upon their needs]

**Comment by aph3rson** [comment]
@dnsguru FYI, we're closing in on an internal release of some tooling to improve how we get our service teams onto the PSL.  
For that reason, we're delaying this submission to be ready ~end of Q1 2023.
​
This release should reduce the amount of manual effort within our team, while simultaneously improving the quality of our submissions to the volunteer maintainers.

**Comment by dnsguru** [comment]
Definitely appreciate that - as it turns out this cadence is a bit more
aligned with the realistic turnaround pace.

I believe there was initially a thought about pace and cadence of
subsequent requests that 1-2 a month was desired.   We're learning that may
have been solved through some of your proactive interactions within Amazon
groups, or maybe we're not seeing the anticipated burst windows occurring.

Thank you for the efforts in reducing the impacts on our resourcing

**Comment by aph3rson** [comment]
@dnsguru re: your comment on #1689:

> can [...]  #1600 (the perpetual draft) be closed until such time as AWS internally sorts this all out and has something to submit ?

We ask that this draft remain in draft state until we're able to get this batch of zones together. Closing this draft would be detrimental to our efforts so far.  
We have a number of services that are still working on getting appropriate validation records set, and closing this draft will require teams to start over on that.

**Comment by dnsguru** [comment]
I seem to recall this being explained face to face as to why this was tied to some form of production process flow now that you have mentioned this, there was just sensitivity to the age of this request being kept open for such a protracted period of time, with this PR having been initiated in August of 2022.

When the PSL was reviewed by ICANN's Security and Stability Advisory Committee for SAC070, the metrics on ticket durations were inelegantly weaponized without context as a shortcoming of the PSL volunteers ability to process things, which started the wrong conversations and we lost a few volunteers due the demotivational aspect of that cognitive distortion to weaponize statistics to match a narrative.

Many who aspire to replace the PSL like to throw shade at the PSL volunteers' pace of processing use the processing time from open to close, so I'll just note that the volunteers response times on this are crisp, and the PR remains open at the request of the creator, where the completion delays live.

**Comment by INCIBE-CERT** [comment]
Let me chime in to state the obvious that any such metric should be excluding any time the requests have been in draft status, Doing otherwise unfairly attributes to the PSL reviewers the delay taken by the organization to finish their PR.

**Comment by aph3rson** [comment]
@dnsguru - thanks for your patience on this. This PR is now ready for review, so I've taken it out of draft state.  
(I'm unable to remove the "DRAFT" GitHub label, though - I think only owners can do that.)

**Comment by dnsguru** [comment]
Ok thanks for making that clear.

Starting "clock" at June 10, 2023

**Review by dnsguru — APPROVED** [review]
* Tests Pass
* No Conflict with Base
* Guideline/Sorting followed
* DNS Validations connect this to requestor org

APPROVED

**Pull request merged**
