### PR TITLE
 removal of freight.aero

### PR DESCRIPTION
**Pull request by devrinoy**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Back-end registry services provider for .aero registry

Reason for PSL Inclusion
====

It used to be a official registry sub-zone, but has since been deprecated

DNS Verification via dig
=======

dig TXT _psl.freight.aero

make test
=========

### CODE REVIEW

**Comment by sleevi** [comment]
This request is missing all required information. I’m afraid we’ll have to close it without that information.

If you’d like to edit the description to fill in the requested info, and comment when you’ve done so, that would be great. Thanks!

**Comment by devrinoy** [comment]
updated the missing information

**Comment by devrinoy** [comment]
Please merge this request

Thanks

**Comment by dnsguru** [comment]
The DNS test does not indicate the PR to validate that this comes from an authoritative source.  

Is there a documented policy of the registry that shows this change?

Have made offline request to Afilias to validate this change.

**Comment by BENOITBERTIN** [comment]
CHAMP Cargosystems is the owner of the root domain freight.aero amd has added the following DNS record to the zone file of freight aero.
_psl.freight.aero TXT "https://github.com/publicsuffix/list/pull/976”
Can you confirm that it can be removed please
Thanks
Benoit

**Comment by BENOITBERTIN** [comment]
C:\WINDOWS\System32>nslookup -q=txt _psl.freight.aero 8.8.8.8
Server:  dns.google
Address:  8.8.8.8
Non-authoritative answer:
_psl.freight.aero       text ="https://github.com/publicsuffix/list/pull/976"
C:\WINDOWS\System32>

**Comment by devrinoy** [comment]
Confirmed, please proceed

**Comment by dnsguru** [comment]
I have had dialog with the registry where they have confirmed the removal of this domain from the registry allocations, but the published document does still list it.  

The DNS entry is present, which demonstrates that the requestor is administratively operates the domain in question:
```
nslookup -q=txt _psl.freight.aero
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.freight.aero       text =

        "https://github.com/publicsuffix/list/pull/976"
```
I assert that this is different circumstances than what held up #518 , because we have the DNS validation, in addition to direct dialog with the registry provider.  On that basis I would like to proceed to merging this, unless there is an objection.

**Comment by dnsguru** [comment]
@sleevi the DNS checks out, would like to merge this

**Pull request merged**
