### PR TITLE
Add bizml.site to mail.ru Private entry list

### PR DESCRIPTION
**Pull request by truetug**
Add bizml.site

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [] DNS verification via dig
* [] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://corp.mail.ru
Mail.ru Group provides social networking, gaming, entertainment services and cloud  B2B and B2C services. Few Mail.ru domains (including mail.ru itself) are listed in Alexa Top-100.
https://biz.mail.ru provides cloud mail hosting and site hosting services.

Reason for PSL Inclusion
====

Subdomain in bizml.site can be registered by users via biz.mail.ru. This subdomain may be used to host internet site with user-provided content and/or send e-mail messages. PSL inclusion is required to
- Indicate the subdomains and content belong to different entities 
- Limit the the cookies scope to prevent crossite cookies accesss
- Limit DMARC policies scope to prevent e-mail spoofing

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by dnsguru** [comment]
Unfortunately, this is rejected.

According to [registry rdap](https://rdap.centralnic.com/site/domain/bizml.site) (new name for whois), the domain name is confirmed to be owned by mail.ru, however it also indicates that **the domain name expires in <30 days**.  The expiration date of November 9, 2020 means this request would not proceed as domains must have >2y expiration date to be submitted.

We would also want to see the _psl DNS record added to the zone in order to validate that the submitting party is connected to the administrator.

**Comment by dnsguru** [comment]
Renewing the domain name for >2y and resubmitting a new PR that references this PR could allow this to proceed, if accompanied by the appropriate DNS entry.

**Comment by truetug** [comment]
> Renewing the domain name for >2y and resubmitting a new PR that references this PR could allow this to proceed, if accompanied by the appropriate DNS entry.

This requirement conflicts with .ru national (geographical) TLD rules and can not be satisfied. .ru domain can only be renewed for 1 year and can not be renewed until 60 days prior to expire, see e.g.
https://manage.whois.com/kb/answer/1336#ren
mail.ru is registered since 1997 and had no expiration issues in the past.

**Comment by dnsguru** [comment]
Thanks for the note, Sergey... mail.ru was not the issue, it was bizml.site
that was the domain being submitted that did not meet the requirements on
new entries.  It appears that this domain was extended since the PR was
closed.

Your notes on the .ru renewal lengths will be taken into consideration
where they are applicable on development of automation of entry reviews in
the public section.  I believe that there will be other TLDs which may have
similar policies or may require special handling when that is developed.

Also, mail.ru is well known, as is yandex or other sites within .ru ; it
may be that the alexa100k list might be considered as another input to
whatever process automation in order to not disrupt major sites, but the
automation is not yet in existence.

**Pull request closed without merging**
