### PR TITLE
adding sth.ac.at

### PR DESCRIPTION
**Pull request by stasic**
ac.at-Registry <https://www.nic.aco.net/> has also a subdomain for Dormitories: sth.ac.at 
see: <https://www.aco.net/domain.html?L=1>

* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: <https://www.aco.net/domain.html?L=1>

Reason for PSL Inclusion
====

We got a User Request regrading:  Cookie Security

DNS Verification via dig
=======

```
dig sth.ac.at txt +short
"subdomain for student hostels in Austria"
"Studentenheime - Dormitories"
```

make test
=========
```
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.0
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-public-builtin.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public
  CCLD     test-is-public-builtin
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.0
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by dnsguru** [comment]
DNS _PSL TXT Validation matching PR# **did not** pass
```
>nslookup -type=txt _psl.sth.ac.at
Server:  one.one.one.one
Address:  1.1.1.1

*** one.one.one.one can't find _psl.sth.ac.at: Non-existent domains
```
However, purpose stated matches description in TXT record
```
>nslookup -type=txt sth.ac.at
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
sth.ac.at       text =

        "subdomain for student hostels in Austria"
sth.ac.at       text =

        "Studentenheime - Dormitories"
```
**NOTE:** rather than force submitter to update TXT record, assignee reached out to meyerhofer@nic.at and validated this request as verified out of band via email
Tests pass

**Comment by dnsguru** [comment]
@stasic I do have a confirmation from NIC.AT but we try to have good documentation on modifications to the ICANN section elements.

Could you please complete one more step - add the _PSL.sth.ac.at TXT record 
"https://github.com/publicsuffix/list/pull/997"

That would provide us better validation / verification to connect to this request - and be consistent with our handling of ICANN section changes.

**Comment by stasic** [comment]
@dnsguru done.
```
dig _psl.sth.ac.at txt @9.9.9.9 +short
"https://github.com/publicsuffix/list/pull/997"
```

**Comment by dnsguru** [comment]
Thank you @stasic it is now merged

**Pull request merged**
