### PR TITLE
Added KingHost domains

### PR DESCRIPTION
**Pull request by fbraz3**
Our host company provides free subdomains for our customers:

>  kinghost.com.br
>  kinghost.net
>  king.host
>  uni5.net

This pull request add this subdomains

### CODE REVIEW

**Comment by frju365** [comment]
Can you provide a short description of your organization, a reason et provide test proof as it's written in the guidelines. Pls, read : https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change

**Comment by fbraz3** [comment]
Hi @frju365 

KingHost is one of largest hosting providers in Brazil. We provide a free domain under kinghost.net, uni5.net, kinghost.com.br or king.host for customers who dont have (or dont want to) register a common domain.

We also provide free lets encrypt certificate, and we having issues with its rate limit for these customers.

For the domain validation, i've added the txt records as requested:

>14:44 root@web01:[~]# dig TXT _psl.kinghost.com.br +short
> "https://github.com/publicsuffix/list/pull/686
> 14:44 root@web01:[~]# dig TXT _psl.kinghost.net +short
> "https://github.com/publicsuffix/list/pull/686"
> 14:44 root@web01:[~]# dig TXT _psl.uni5.net +short
> "https://github.com/publicsuffix/list/pull/686"
> 14:52 root@web01:[~]# dig TXT _psl.king.host +short
> "https://github.com/publicsuffix/list/pull/686"

Dig tests also confirmed by google apps toolbox =)
https://toolbox.googleapps.com/apps/dig/#TXT/

**Comment by fbraz3** [comment]
Hi, any news about this PR ?

thanks in advance.

**Comment by fbraz3** [comment]
Created a new pull request following the instructions: https://github.com/publicsuffix/list/pull/800

**Pull request closed without merging**
