### PR TITLE
Add telebit.io .app .xyz

### PR DESCRIPTION
**Pull request by coolaj86**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Supersedes #672 in order to
* to be free of merge conflicts
* to use only our best branded domains
  * telebit.io
  * telebit.app
  * *.telebit.xyz (for unlimited subdomains for users)

Description of Telebit
====

Organization Website: <https://rootprojects.org>
Product Website: <https://telebit.cloud>

I'm the owner and operator of <https://rootprojects.org>, which offers a number a products and services related to home servers, self-hosting, and social file and document sharing.

We're getting ready to launch https://telebit.cloud, which is an authenticated relay service to allow developers to connect a testable public domain to private devices and services - such as apps running in development on localhost and IoT devices and Raspberry Pis behind school firewalls.

terminal-example-1

Reason for adding Telebit domains
====

Telebit is similar to services like ngrok, serveo, and localtunnel.me, but we're focused on home and education, and committed to open standards (no vendor lock-in).

Each device gets a semi-random subdomain on one of our domains (such as lucky-duck-42.telebit.io) with unlimited subdomains (i.e. home.lucky-duck-42.telebit.xyz).

We want to remove the rate-limit restrictions of Let's Encrypt as well has have separate cookies for each of the sites.

DNS Verification
=====

```
dig TXT +short _psl.telebit.app
"https://github.com/publicsuffix/list/pull/726"
```

```
dig TXT +short _psl.telebit.io
"https://github.com/publicsuffix/list/pull/726"
```

```
dig TXT +short _psl.telebit.xyz
"https://github.com/publicsuffix/list/pull/726"
```
make test
=======

None of the failing entries are related to this change.

### CODE REVIEW

**Comment by coolaj86** [comment]
Hey @weppos, could I get you to take a look at this when you have a minute?

**Comment by coolaj86** [comment]
@weppos Would you mind giving this a once-over?

**Review by weppos — APPROVED** [review]
```
➜  ~ dig +short TXT _psl.telebit.app
"https://github.com/publicsuffix/list/pull/726"
➜  ~ dig +short TXT _psl.telebit.io
"https://github.com/publicsuffix/list/pull/726"
➜  ~ dig +short TXT _psl.telebit.xyz
"https://github.com/publicsuffix/list/pull/726"
```

**Comment by groundcat** [comment]
Hi @coolaj86 do you still need telebit.io .app .xyz to be included in the PSL? It seems that the project is no longer active.

**Comment by coolaj86** [comment]
It's still active, but apparently there's a proxy issue right now I need to look into.

**Pull request merged**
