### PR TITLE
Update `prvcy.page` contact email

### PR DESCRIPTION
**Pull request by o3o-ca**
Hello, we are updating our contact email address for `prvcy.page` which was added from #1859. Thank you!

### CODE REVIEW

**Comment by groundcat** [comment]
- Requestor = Initial requestor (#1859)
- Tests passed

**Comment by groundcat** [comment]
@o3o-ca Would you please update the TXT record for `_psl.prvcy.page` to this PR?

**Comment by wdhdev** [comment]
We do not explicitly have specific email addresses we send from as there are a few volunteers, like myself and @groundcat which do not work at Mozilla, nor have Mozilla email addresses and we send emails from personal email addresses.

Maybe we could create a file in this repository with a list of email addresses you should explicitly allow emails from for important PSL notices.

**Comment by groundcat** [comment]
I agree with both of your points; perhaps it's best to create a new issue to specifically address this email concern: #2184

**Pull request merged**
