### PR TITLE
Add hepforge.org

### PR DESCRIPTION
**Pull request by dgrell**
Contact  admin (at) hepforge.org  for confirmation.

### CODE REVIEW

**Comment by weppos** [comment]
Can you please rebase the patch against master, reformat the PR and provide the DNS records as requested by our Guidelines?
https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by dgrell** [comment]
Rebased and reformatted, waiting for DNS update

**Comment by dgrell** [comment]
OK, all done:

`$ dig +short TXT  _psl.hepforge.org`
`"https://github.com/publicsuffix/list/pull/158"`

**Comment by weppos** [comment]
Thanks @dgrell. Before moving on, as requested by the Guidelines, please briefly explain the reason why you want the domain included in the list.

**Comment by dgrell** [comment]
hepforge.org provides virtual hosting for individual, independent software projects in high energy physics. Their domains are <projectname>.hepforge.org. The various projects do not automatically trust each other. 

Thanks!

**Pull request merged**
