### PR TITLE
AWS Submissions to the Public Suffix List - Month of 2022-07

### PR DESCRIPTION
**Pull request by aph3rson**
Description of Organization
====

Amazon Web Services is an infrastructure-as-a-service cloud computing provider.
More information about AWS is availble on our website:
[What is AWS?](https://aws.amazon.com/what-is-aws/)

**Organization Website:**  
[AWS Homepage](https://aws.amazon.com)

Reason for PSL Inclusion
====

These features/services have been identified by AWS Security and AWS service
teams as supporting different distinct customers/resources across shared
DNS suffixes. Adding these suffixes to the PSL is expected to improve the
security posture of customers using our services.

**Number of users this request is being made to serve:**  
These changes are expected to impact all customers using these AWS services.
This includes both AWS-internal and external customers. Specific user counts
for these listed features/services are not publicly available.

Services/Features in PR:
====

- AWS Cloud9 - Application Preview, Webviews

DNS Verification via dig
=======

<details>
<summary>Click here</summary>

```
$> dig +short TXT _psl.vfs.cloud9.af-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.af-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.ap-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.ap-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.ap-northeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.ap-northeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.ap-northeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.ap-northeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.ap-northeast-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.ap-northeast-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.ap-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.ap-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.ap-southeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.ap-southeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.ap-southeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.ap-southeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.ca-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.ca-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.eu-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.eu-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.eu-north-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.eu-north-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.eu-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.eu-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.eu-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.eu-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.eu-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.eu-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.eu-west-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.eu-west-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.me-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.me-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.sa-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.sa-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.us-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.us-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.us-east-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.us-east-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.us-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.us-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.vfs.cloud9.us-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
$> dig +short TXT _psl.webview-assets.cloud9.us-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1590"
```

</details>

Results of Syntax Checker (`make test`)
=========
<details>
<summary>Click here</summary>

```
cd linter;                                \
  ./pslint_selftest.sh;                     \
  ./pslint.py ../public_suffix_list.dat;
test_allowedchars: OK
test_dots: OK
test_duplicate: OK
test_exception: OK
test_NFKC: OK
test_punycode: OK
test_section1: OK
test_section2: OK
test_section3: OK
test_section4: OK
test_spaces: OK
test_wildcard: OK
test -d libpsl || git clone --depth=1 https://github.com/rockdaboot/libpsl;   \
  cd libpsl;                                                                    \
  git pull;                                                                     \
  echo "EXTRA_DIST =" >  gtk-doc.make;                                          \
  echo "CLEANFILES =" >> gtk-doc.make;                                          \
  autoreconf --install --force --symlink;
Already up to date.
autopoint: using AM_GNU_GETTEXT_REQUIRE_VERSION instead of AM_GNU_GETTEXT_VERSION
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:381: warning: file `version.txt' included several times
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:381: warning: file `version.txt' included several times
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
aclocal.m4:763: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:381: warning: file `version.txt' included several times
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: linking file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:381: warning: file `version.txt' included several times
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:381: warning: file `version.txt' included several times
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
aclocal.m4:763: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:381: warning: file `version.txt' included several times
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
aclocal.m4:763: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:381: warning: file `version.txt' included several times
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
aclocal.m4:763: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:381: warning: file `version.txt' included several times
configure.ac:10: installing 'build-aux/compile'
configure.ac:4: installing 'build-aux/missing'
fuzz/Makefile.am: installing 'build-aux/depcomp'
cd libpsl && ./configure -q -C --enable-runtime=libicu --enable-builtin=libicu --with-psl-file=[snip]/public_suffix_list.dat --with-psl-testfile=[snip]/tests/tests.txt && make -s clean && make -s check -j4
configure: WARNING: --enable-builtin=libicu is deprecated, use --enable-builtin (enabled by default)
config.status: creating po/POTFILES
config.status: creating po/Makefile
Making clean in po
Making clean in include
Making clean in src
rm -f ./so_locations
Making clean in tools
 rm -f psl
Making clean in fuzz
 rm -f libpsl_icu_fuzzer libpsl_icu_load_fuzzer libpsl_icu_load_dafsa_fuzzer
Making clean in tests
 rm -f test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain
Making clean in msvc
Making check in po
Making check in include
Making check in src
  CC       libpsl_la-psl.lo
  CC       libpsl_la-lookup_string_in_fixed_set.lo
  CCLD     libpsl.la
Making check in tools
  CC       psl.o
  CCLD     psl
Making check in fuzz
  CC       libpsl_fuzzer.o
  CC       main.o
  CC       libpsl_load_fuzzer.o
  CC       libpsl_load_dafsa_fuzzer.o
  CCLD     libpsl_icu_fuzzer
  CCLD     libpsl_icu_load_fuzzer
  CCLD     libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public
PASS: test-is-public-builtin
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc

```

</details>

### CODE REVIEW

**Comment by dnsguru** [comment]
Will you be addressing all of Amazon or only AWS?  There be a metric "effton"

**Comment by dnsguru** [comment]
@aph3rson Still draft - Still needed?

**Comment by aph3rson** [comment]
@dnsguru: 

> Will you be addressing all of Amazon or only AWS?

This is only for AWS - specifically, a chunk of AWS as we get services onboarded. As mentioned by @plygrnd in https://github.com/publicsuffix/list/pull/1460#issuecomment-1018853222, we plan on aggregating requests to a limited cadence to reduce load on your team. We're aiming for 2/month, though we recognize we've got some work to do before we get to that cadence.

This PR will only include one service, and we're working on getting those rules added at this moment.

**Comment by aph3rson** [comment]
@dnsguru, re: your comments on #1600 ([1](https://github.com/publicsuffix/list/pull/1600#issuecomment-1230990811), [2](https://github.com/publicsuffix/list/pull/1600#issuecomment-1231006237)):

> Please, does this close #1403 , #1404 , #1460

This PR should be considered as superseding #1403.

-----

> which contains 46 lines in contrast to a typical modest 3-4

This is partially related to changes made in #145. The suffixes identified are the bare-minimum required for full PSL coverage for this service/feature - we're unable to use wildcards, as the wildcardable-portion (the region) would not be in the left-most label of the suffix on the PSL.

The number of suffixes here is mostly on-par for a service which we can't use wildcarding with (most of them). AWS currently operates 23 public regions, and this particular service has two zones for different types of resources. As more regions launch, we expect that number to increase.

We did try to prove that these domains have been validated by providing both output from `make test` and the applicable output from `dig` for those zones.

-----

> mentions 2 per month a possible cadence. Intial reaction is that pace is more ambitious than PSL resourcing can support

We're happy to discuss changes in cadence, though that shouldn't impact the contents of this PR. I've opened #XXXX to discuss this (and other outstanding topics).

**Comment by aph3rson** [comment]
@dnsguru any updates here?

**Comment by dnsguru** [comment]
Soonest ETA to review PRs is week of 9/28, assuming no other impacts to available volunteer cycles.   Just a high-level guesstimate.    

One thing noticed in a fast-pass review of the PR is that there was a mention of 23 data centers, but there are only 42 lines of hosts requested.  42/2 = 21 so is that short by 2 datacenters?    Just want to confirm

**Comment by dnsguru** [comment]
Did not receive confirmation but will process

**Comment by dnsguru** [comment]
```dig  in txt webview-assets.cloud9.af-south-1.amazonaws.com. 8.8.8.8```

NXDOMAIN on the first required TXT records that should match the pull request, so please set those up so we're not wasting the reviewer time on iterations.

```
; <<>> DiG 9.10.6 <<>> in txt webview-assets.cloud9.af-south-1.amazonaws.com. 8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43424
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;webview-assets.cloud9.af-south-1.amazonaws.com.	IN TXT

;; AUTHORITY SECTION:
cloud9.af-south-1.amazonaws.com. 891 IN	SOA	ns-381.awsdns-47.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
```

**Comment by aph3rson** [comment]
@dnsguru - I wasn't aware that particular query was part of the verification process. The verification process states that reviewers would query the `_psl` zone affixed to the suffix being submitted - that's the verification we did prior, [and those records are still there](https://dns.google/query?name=_psl.webview-assets.cloud9.af-south-1.amazonaws.com&rr_type=TXT&ecs=).

I checked a recently-merged PR (#1594), and they seem to have followed the same pattern. 

Are we missing something here?

**Comment by dnsguru** [comment]
IAN that was my bad.  I am weary at ICANN 75 from trying to get more PSL
support in Kuala Lumpur, and wanted to advance your pr review hastily
during a quick gap in the schedule I had.

Folks seem to be applying pressures in different fora to wanting PSL more
responsive, which is ironically sucking more unpaid time I didn't have.

Anyway this was my bad...
I made a velocity error didnt prefix the _psl on the query, which splains
the outcome.  Will re-run and if the _psl txt records are in place this
will proceed.

Separately, while i have your eyes... Did you see my prior question about
all the entries being right?

Assuming you will catch in future PR if so.

**Comment by dnsguru** [comment]
```dig +short in txt _psl.webview-assets.cloud9.af-south-1.amazonaws.com. 8.8.8.8```
(correctly added _psl)

```"https://github.com/publicsuffix/list/pull/1590"```
Expected result.

same all true for balance of listed names in PR

**Review by dnsguru — APPROVED** [review]
* follows guidelines
* no conflict with base
* passes tests
* DNS validates to PR
APPROVED

**Pull request merged**
