### PR TITLE
Add definima domain suffix

### PR DESCRIPTION
**Pull request by Maxence**
We use *.definima.net and *.definima.io for our customers projects.

### CODE REVIEW

**Comment by Maxence** [comment]
My TXT is already ready :)
`dig txt _psl.definima.net +short
"https://github.com/publicsuffix/list/pull/383"`

**Comment by Maxence** [comment]
Hello @sleevi How long we have to wait to know if our pull is accepted or not ?
Good luck :)

**Comment by sleevi** [comment]
This PR does not comply with the https://github.com/publicsuffix/list/wiki/Guidelines

Please sort by company name

**Comment by Maxence** [comment]
I sorted by company name on my last commit and added definima.io suffix

Here is my TXT 
`dig txt _psl.definima.io +short
"https://github.com/publicsuffix/list/pull/383"`

**Pull request merged**
