### PR TITLE
Please add myqnapcloud domain to publicsuffix list

### PR DESCRIPTION
**Pull request by qnapnickchang**
QNAP is providing dyndns services to their customers on the .myqnapcloud.com domain. I work in QNAP. Please add myqnapcloud domain to public suffix list

### CODE REVIEW

**Comment by qnapnickchang** [comment]
_psl.dev-myqnapcloud.com and _psl.alpha-myqnapcloud.com and _psl.myqnapcloud.com TXT records are live. Please Check.  Thanks for your help.

**Comment by qnapnickchang** [comment]
We, QNAP Systems, Inc. (https://www.qnap.com), provide network attached storage (NAS) to our users
We provide the dynamic dns service on [myqnapcloud.com]
Our user can easier and faster to set up Let's encrypt's SSL Certificate through the QNAP NAS.
Setting the Certificate can help user strengthen the NAS security

Please help merge this request (https://github.com/publicsuffix/list/pull/222)
Thanks for your help.

**Comment by weppos** [comment]
As per our Guidelines, please properly sort the items in the list.
https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by weppos** [comment]
Actually, my fault. The items are already in the proper order.

**Comment by qnapnickchang** [comment]
@weppos Could you merge this?

**Comment by qnapnickchang** [comment]
@weppos  Is there any information missing from our request? Please advise, thank you.

**Pull request merged**
