### PR TITLE
Add `wpsquared.site` and `wp2.host` to private section

### PR DESCRIPTION
**Pull request by atoomic**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

WebPros provides solutions in the web industry for more than 20 years.
Among the known solutions: `cPanel`, `Plesk` web hosting control panel software.
It provides a graphical interface (GUI) and automation tools designed to simplify the process of hosting a web site to the website owner or the "end user". It enables administration through a standard web browser using a three-tier structure.

The submitter, Nicolas Rochelemagne, is a Technical Lead Manager for different products developed by WebPros, including WordPress Squared, a new WebPanel focused around WordPress needs.

Organization Website: 
https://www.webpros.com/

Reason for PSL Inclusion
====

We issue LetsEncrypt certificates for server's hostnames and websites for our hosting partners. 
We want our customers' sites to be isolated for other customers (cookies, suffix highlighting, etc) and be able to deliver SSL certificates to each records.

We use two different domains for different purposes:
* `wp2.host` used to point to the server itself using something like `1-2-3-4.wp2.host` where `1.2.3.4` is the the public IP.
* `wpsquared.site` to provide a direct access to a website. Example `my-cool-website-com.wpsquared.site`

Number of users this request is being made to serve:
At this day WebPros provides different web hosting solutions for bringing online more than 90,000,000 websites that could start using that new WPSquared solution.

DNS Verification via dig
=======

```
dig +short TXT _psl.wp2.host
"https://github.com/publicsuffix/list/pull/1957"
```

```
dig +short TXT _psl.wpsquared.site
"https://github.com/publicsuffix/list/pull/1957"
```

Results of Syntax Checker (`make test`)
=========

```
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       common.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-public
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-all
  CCLD     test-is-public-builtin
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Please follow sorting guidelines (by TLD first, then SLD)

**Comment by atoomic** [comment]
resolved the conflict, reran the tests and resubmit 
this is now ready for review 
thanks

**Comment by simon-friedberger** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] wp2.host expires 2029-04-04
  * [ ] wpsquared.site expires 2025-06-20
* [ ] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [ ] Reasoning/Organization description

**Comment by simon-friedberger** [comment]
Can you elaborate on what you need the IP based addresses? We generally discourage such overlap of the IP namespace and the DNS namespace.

**Comment by atoomic** [comment]
Thanks sorry for the oversight of the expiration date. 
Here are some extra details and replies to your questions.

## Expiration

The expiration date issue is now fixed:
* wp2.host `Registry Expiry Date: 2029-04-04T23:59:59.0Z`
* wpsquared.site  `Registrar Registration Expiration Date: 2027-06-20T23:59:59`

## DNS Verification

Sorry the DNS txt records for the `_psl` records were removed outside of my vision during a registrar transfer, I made sure this would not happen again and both are now restored.
```
> dig +short TXT _psl.wp2.host
"https://github.com/publicsuffix/list/pull/1957"
> dig +short TXT _psl.wpsquared.site
"https://github.com/publicsuffix/list/pull/1957"
```

## Reason for inclusion (elaboration)

`WebPros` owns `cPanel` and is currently developing a more WordPress centric solution where the brand cPanel is going to be replaced. This case is similar to what is achieved via #1892 using a different branding as we do not want to use `*.cprapid.com`  where `cp` stands for `cPanel`.

We do not necessary need the IPv4 mapping. 
We want to provide out of the box SSL certificates: 
* For hosting companies using the `*.wp2.host` domain so they can directly access to our WebHosting panel using
example:
```
# either a UUID for their server
my-server-uuid.wp2.host
# or the public IP of their server
5-4-3-2.wp2.host
```
* For website owners using the `*.wpsquared.site` domain while their domain purchase and setup is processed
example 
```
my-website.com.wpsquared.site
sub.my-website.com.wpsquared.site
```

**Comment by simon-friedberger** [comment]
Please double check if the wildcards are what you want. Your examples for the first domain seem to not match.

**Comment by atoomic** [comment]
Indeed this is what we want to use, this is mainly an alternate branding to the `*.cprapid.com` rule added by #1892.
Thanks for checking

**Comment by simon-friedberger** [comment]
The current wildcards make `my-server-uuid.wp2.host` a public suffix instead of `wp2.host`. You're really sure?

**Comment by simon-friedberger** [comment]
@atoomic ping

**Comment by atoomic** [comment]
I see your point, we are looking at customer isolation for cookies.

After reading https://github.com/publicsuffix/list/wiki/Format#example
looks like we do not need to use the `*.` at all and we probably incorrectly used it there #1892 in first place.

Thanks @simon-friedberger for pointing the issue, I've adjusted the rules from the Pull Request.

**Comment by simon-friedberger** [comment]
Sorry for being annoying but you gave two different examples:
* In `my-server-uuid.wp2.host` the user gets `my-server-uuid` and the common part is `wp2.host` so `wp2.host` would be the public suffix.
* In `my-website.com.wpsquared.site` the users gets `my-website` and the common part is `com.wpsquared.site` or maybe for a different TLD it is `bananacollective.org.wpsquared.site` and `org.wpsquared.site` is the common part. So here the public suffix would be `*.wpsquared.site`.

**Comment by atoomic** [comment]
Sorry I provided an incorrect example. Here are some better use cases:
* `my-server-uuid.wp2.host` here `wp2.host` is the public suffix.
* `my-website-com.wpsquared.site` or `my-website.wpsquared.site` and `wpsquared.site` will be the public suffix 

Using the `*.` was a mistake for both domains IMO.

**Comment by simon-friedberger** [comment]
Great, thanks for bearing with me!

Follow-up question: should the cPanel section from #1892 be move here and the wildcard fixed? IIUC it's the same organization so it would be logical to keep them together.

**Comment by atoomic** [comment]
Sorry I was off the grid for tte last few days. Will not have access to a
keyboard before next week.
But yes it makes sense. I also think the entry for cprapid should not use
the wildcard.

I will merge the two sections as WebPros, and update my pull request. Give
me a couple of days

Thanks

**Comment by atoomic** [comment]
Thanks @simon-friedberger I've submitted the merge via https://github.com/publicsuffix/list/pull/2013

**Pull request merged**
