### PR TITLE
Add domains for `encore.dev`

### PR DESCRIPTION
**Pull request by eandre**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [X] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [X] This request was _not_ submitted with the objective of working around other third-party limits

  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://encore.dev

Encore is a developer platform for building cloud-hosted backend and soon full-stack web applications. We provide users with a unique `$MYAPP.encoreapi.com` and `$MYAPP.encr.app` subdomain that they can use to host their application on.

Reason for PSL Inclusion
====

As we allow customers to host their backend and frontend on a shared domain there is a security risk if they can write and read cookies intended solely for other customers. We have taken some steps already to mitigate this in the API Gateway we provide (by rewriting `Set-Cookie` headers from the backend), but it's not enough. It's still possible to set client-side cookies with JavaScript in ways that affect the per-customer isolation we're looking for. Inclusion in the PSL would add another, stronger layer of security on top.

DNS Verification via dig
=======

```
$ dig +short TXT _psl.encr.app
"https://github.com/publicsuffix/list/pull/1531"

$ dig +short TXT _psl.encoreapi.com
"https://github.com/publicsuffix/list/pull/1531"
```

make test
=========

```
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by eandre** [comment]
I'm not sure why this was marked as non-acceptance; I've manually reviewed all the points in the acceptance criteria. The only one I could think of is the domain expiration date; it was already configured to auto-renew but I've manually extended the current registration period to 3+ years out for both `encr.app` and `encoreapi.com`. Let me know if there was something else, thanks.

**Comment by dnsguru** [comment]
Please provide more description about the request.  So far, the use case
described appears to have the objective of signalling let's encrypt to not
use their standard limits on subdomains, and routing around third-party
limits via the PSL is something which is typically declined.

If the brief description provided the wrong message, and enabling customers
around lets encrypt limits as described was not an objective, a more robust
description would have helped avoid this.  If the objective is to route
around let's encrypt limits or subdomain users, please address this
directly with let's encrypt.

**Comment by eandre** [comment]
My apologies, I shouldn't have mentioned LetsEncrypt as we don't use them at all and have no plans of using them.

The reason for submission is entirely due to improving browser security, particularly cookie domain isolation. We provide some mitigation for this already through our API Gateways but it's not sufficient.

I will update the description to better explain our use case.

**Comment by eandre** [comment]
Hi @dnsguru, I've now amended the description to provide additional information about our use case and why we're requesting inclusion. Thanks!

**Comment by eandre** [comment]
Hi again, is there anything else I need to do on our side? Couldn't find any documentation on this label. Thank you!

**Comment by dnsguru** [comment]
>Couldn't find any documentation on this label. 

The NOT IOS FB label exists so we can visually see which have been vetted against that might have been impacted by the IOS PCM changes that are seeking to use the PSL (inappropriately) as a bugfix.  You took care of the issue of NON-ACCEPTANCE by adding more words.

Appreciate that the LE mention was for transparency and not the stated objective.  It is a fine line, but once too many PSL entries start to pop up to create exceptions to the rate limits of third parties, those third parties (and browsers) are likely to discontinue to use the PSL and likely would splinter off into their own directions.  That would make for some really challenging troubleshooting and n+1 places to resolve cookie isolation, so we're super quick to serve up hot cups of nope for those.

>Thank you!

you're welcome, and I am sure you appreciate also that this is volunteer run here, so cycles come as they do.  Thank you for your patience

**Comment by eandre** [comment]
Thank you so much for the explanation and for your efforts. Very much appreciate the help!

**Pull request merged**
