### PR TITLE
Add oy.lc

### PR DESCRIPTION
**Pull request by Changaco**
http://oy.lc/

### CODE REVIEW

**Comment by Changaco** [comment]
Ping. This PR really is a no-brainer. oy.lc is similar in spirit to eu.org which already is in the list.

**Comment by weppos** [comment]
Can you please update this request and the patch according to https://github.com/publicsuffix/list/wiki/Guidelines

Once updated, I'll be happy to review it.

**Comment by weppos** [comment]
Ideally, please rebase the entire patch into a single commit.

**Comment by Changaco** [comment]
Done. I've rebased the PR and attached a `TXT` record to `_psl.oy.lc`.

**Comment by weppos** [comment]
Please replace "Changaco" with a valid name, and remove the date.

**Comment by Changaco** [comment]
Done.

**Pull request merged**
