### PR TITLE
Add TownNews.com suffixes

### PR DESCRIPTION
**Pull request by dward**
This is a request add our customer level domains to the suffix list.

Please let me know if/what verification is needed.

### CODE REVIEW

**Comment by dward** [comment]
What's needed for verification for this to get merged in?

Thanks1

**Comment by weppos** [comment]
Please have a look at https://github.com/publicsuffix/list/wiki/Guidelines

I also have one more question: why are you asking to add a staging domain?

**Comment by dward** [comment]
Great. Thanks, I was unaware of the guidelines page.

The staging domain is used for customers which are not yet fully live or have their own domain name, but we still expect full isolation for $customer.townnews-staging.com.

**Comment by dward** [comment]
dig TXT _psl.bloxcms.com
_psl.bloxcms.com.       300     IN      TXT     "https://github.com/publicsuffix/list/pull/137"

dig TXT _psl.townnews-staging.com
_psl.townnews-staging.com. 7200 IN      TXT     "https://github.com/publicsuffix/list/pull/137"

**Comment by sleevi** [comment]
Please sort your domains and this will be good to go.

**Comment by dward** [comment]
Thanks, it should be sorted properly now.

**Pull request merged**
