### PR TITLE
Create lifetime.hosting SLDs

### PR DESCRIPTION
**Pull request by fukkani**
We are a hosting company (https://lifetime.hosting) and we provide subdomains (SLDs) to our customers. For cookie isolation, SSL management, Direct URL translation, and the inevitable developments in security, it would be great to get added to the public suffix list.

### CODE REVIEW

**Comment by fukkani** [comment]
[~]# dig +short TXT _psl.co.business
"https://github.com/publicsuffix/list/pull/598"

[~]# dig +short TXT _psl.co.education
"https://github.com/publicsuffix/list/pull/598"

[~]# dig +short TXT _psl.co.technology
"https://github.com/publicsuffix/list/pull/598"

[~]# dig +short TXT _psl.co.events
"https://github.com/publicsuffix/list/pull/598"

[~]# dig +short TXT _psl.co.financial
"https://github.com/publicsuffix/list/pull/598"

[~]# dig +short TXT _psl.co.network
"https://github.com/publicsuffix/list/pull/598"

[~]# dig +short TXT _psl.co.place
"https://github.com/publicsuffix/list/pull/598"

[~]# dig +short TXT _psl.co.technology
"https://github.com/publicsuffix/list/pull/598"

**Comment by fukkani** [comment]
I hope I have submitted the change request properly this time,

**Comment by frju365** [comment]
no, you have just to modify `public_suffix_list.dat` file and add your entry(prefix) at the end of the file, and not create a new file for your prefix.

**Comment by frju365** [comment]
And you have to add your domain with alphabetic order, sorry in the private section.

**Comment by weppos** [comment]
Closing as this PR is not properly mergeable (it also splits the list).

**Pull request closed without merging**
