### PR TITLE
Update .fr list, move some subspaces to PRIVATE section listing of smallregistry.net

### PR DESCRIPTION
**Pull request by jerome**
Reason for PSL Inclusion
====

- The AFNIC no longer manages the SLD list, now mostly handled by Smallregistry
- The French National Board of Surveyors (Ordre des Géometres-Experts) asks for their domain geometres-experts.fr to be removed (contact: <ordre@geometre-expert.fr> )

### Checklist of required steps

* [X] Description of Organization
* [X] Robust Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [X] This request was _not_ submitted with the objective of working around other third-party limits

  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

SMALLREGISTRY manages .fr SLD

Organization Website: https://www.smallregistry.net

### CODE REVIEW

**Comment by jerome** [comment]
/ping @dnsguru https://github.com/publicsuffix/list/pull/1621#pullrequestreview-1379600487 - Thank you, and sorry for the mess

**Comment by dnsguru** [comment]
@jerome please remove the extra newlines and this can proceed

**Comment by dnsguru** [comment]
Noting that this has the label [🚩ICANN (IANA/ICP-3) Section ](https://github.com/publicsuffix/list/labels/%F0%9F%9A%A9ICANN%20%28IANA%2FICP-3%29%20Section) because there technically is a change to the ICP-3 section, in that this pull request moves items away from there to the private section as a result of the sponsorship change on the relevant and affected ccTLD namespaces in scope of the pull-request.  This has been discussed with and approved by the impacted ccTLD administrator, AFNIC.

**Review by dnsguru — APPROVED** [review]
* Thoroughly reviewed with .FR registry (see comment thread) due to impact on migrating these entries out of the #ICANN section to the #PRIVATE section - all good, no objections
* DNS Tests on public resover show the appropriate _PSL TXT records per zone
* No conflict with Base (thank you for revising the change once AFNIC had updated their section)
* PR follows Guidelines for Sorting
* Tests Pass

APPROVED, Merging

**Comment by dnsguru** [comment]
@jerome this is now merged

**Pull request merged**
