### PR TITLE
Add `hatenablog.com`, etc.

### PR DESCRIPTION
**Pull request by NanimonoDemonai**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Hatena Co., Ltd. is the provider of the blog hosting service [Hatena Blog](https://hatena.blog/). Users of Hatena Blog can create their blogs using subdomains provided by Hatena.

I am an engineer at Hatena.

Organization Website: https://hatena.co.jp/

Reason for PSL Inclusion
====

Number of users this request is being made to serve: Hatena has 12.3 million[^1] registered users who can create blogs.

We serve users' blogs on the following domains (e.g. example.hatenablog.com)
 * *.hatenablog.com
 * *.hatenadiary.com
 * *.hateblo.jp
 * *.hatenablog.jp
 * *.hatenadiary.jp
 * *.hatenadiary.org

We want our user's blogs to be isolated from each other.
  * Users can write any JavaScript and set cookies on their blogs, but we want the cookies set there to be isolated from other blogs.
  * The ads.txt references items located at eTLD + 1 for the site's domain. By adding these domains to the PSL, we aim to make the domain of users' blogs eTLD + 1, allowing ads.txt to be set up for each blog.

DNS Verification via dig
=======

```
dig TXT _psl.hatenablog.com +short
"https://github.com/publicsuffix/list/pull/1948"
```

```
dig TXT _psl.hatenadiary.com +short
"https://github.com/publicsuffix/list/pull/1948"
```

```
dig TXT _psl.hateblo.jp +short
"https://github.com/publicsuffix/list/pull/1948"
```

```
dig TXT _psl.hatenablog.jp +short
"https://github.com/publicsuffix/list/pull/1948"
```

```
dig TXT _psl.hatenadiary.jp +short
"https://github.com/publicsuffix/list/pull/1948"
```

```
dig TXT _psl.hatenadiary.org +short
"https://github.com/publicsuffix/list/pull/1948"
```

Results of Syntax Checker (`make test`)
=========

```
============================================================================
 Testsuite summary for libpsl 0.21.5
 ============================================================================
 # TOTAL: 5
 # PASS:  5
 # SKIP:  0
 # XFAIL: 0
 # FAIL:  0
 # XPASS: 0
 # ERROR: 0
 ============================================================================
```

[^1]: The basis for the number of users is Hatena's IR material: [決算説明資料](https://hatena.co.jp/ir/presentation.html) ≫ [
2024年７月期　第2四半期決算説明会資料](https://ssl4.eir-parts.net/doc/3930/ir_material_for_fiscal_ym/152543/00.pdf#page=33)

### CODE REVIEW

**Comment by simon-friedberger** [comment]
What is this ads.txt that you are referring to?

**Comment by simon-friedberger** [comment]
* [ ] Expiration (Note: Must STAY >2y at all times)
  * [ ] hatenablog.com expires 2024-10-17
  * [ ] hatenadiary.com expires 2025-11-04
  * [x] .jp cannot be checked ⚠️
  * [ ] hatenadiary.org expires 2024-11-14
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [ ] Reasoning/Organization description

**Comment by groundcat** [comment]
.jp can be checked here: 
JPRS WHOIS  https://whois.jprs.jp/ (whois.jprs.jp)

Expiration (Note: Must STAY >2y at all times)
- [ ] hateblo.jp expires 2024/10/31 ⚠️
- [ ] hatenablog.jp expires 2024/10/31 ⚠️
- [ ] hatenadiary.jp expires 2024/11/30 ⚠️

**Comment by groundcat** [comment]
> What is this ads.txt that you are referring to?

I believe the `ads.txt` file the requester mentioned is connected to addressing certain Google AdSense limitations, based on the post below, though I'm not completely certain.

https://bunsho-de-kasegu.com/archives/adsenseadstxt.html

**Comment by NanimonoDemonai** [comment]
We have extended the domain expiration dates.

- hatenablog.com expires 2026-10-17
- hatenadiary.com expires 2026-11-04
- hateblo.jp expires 2026-10-31
- hatenablog.jp expires 2026-10-31
- hatenadiary.jp expires 2026-11-30
- hatenadiary.org expires 2026-11-14

The expiration dates for the .jp domains have also been extended, but due to the limitation of the .jp domain registry (JPRS), the expiration date on WHOIS is only updated annually.
Therefore, the updated expiration dates cannot be confirmed via WHOIS at this time.

> Can you please provide the number of users who actually have such a blog? What is the number of active URLs.

As of May 2024, the number of active subdomains is approximately 300,000 to 3,000,000 per domain.
For business reasons, we cannot provide the exact numbers.

> What is this ads.txt that you are referring to?

ads.txt refers to https://iabtechlab.com/ads-txt/. It is a file distributed under the eTLD+1 domain of the site, and the PSL is referenced during this process.
Although I mentioned it as reference information, the primary reason for our request to add the domains to the PSL is to isolate cookies for each site.

Please review again @simon-friedberger

**Comment by groundcat** [comment]
All three `.com` and `.org` domains expire more than two years from now.

- **hatenablog.com**
  - Registry Expiry Date: 2026-10-17T04:29:39Z
- **hatenadiary.com**
  - Registry Expiry Date: 2026-11-04T02:25:09Z
- **hatenadiary.org**
  - Registry Expiry Date: 2026-11-14T02:07:52Z

For the three `.jp` domains, according to the current registry WHOIS record:

- **hateblo.jp**
  - Expires on: 2024/10/31
- **hatenablog.jp**
  - Expires on: 2024/10/31
- **hatenadiary.jp**
  - Expires on: 2024/11/30

However, the `.jp` registry [has its own way of managing the expiry dates in its WHOIS records](https://faq.interlink.or.jp/faq2/View/wcDisplayContent.aspx?sso_step=1&id=980), as the submitter mentioned, so this might not reflect the actual expiry dates.

```
jpドメインの場合、Whois上で表示される有効期限は、有効期限日の翌日に更新されます。 
有効期限の延長は、jpドメインの管理元であるJPRS(株式会社日本レジストリサービス)が
行います。
```

This means that the WHOIS database updates the expiration date information the day after the current expiration date passes.

A quick Google search of `site:` across each of these 6 domains shows a significant number of user sites. Spot-checked a few of them, and they appear to belong to different users—personal blogs or organizational sites, way more than tens of thousands of sites. This aligns with the description under "Reason for PSL Inclusion"; thus, I do see the security implications and the necessity to include them in the PSL for cookie isolation, etc. (The ads.txt third-party limit might not be the submitter's primary intention.)

**Comment by simon-friedberger** [comment]
TY @groundcat !

**Pull request merged**
