### PR TITLE
Add private domains for airy.host

### PR DESCRIPTION
**Pull request by KirillUlyanov**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

PE Ulyanov Kirill Sergeevich; Hosting

Organization Website: https://airy.host/

Reason for PSL Inclusion
====

Domains under management airy.host (lk3.ru , zsew.ru , ra-ru.ru) should be listed in the PSL to provide cookie security and to allow password managers to apply the correct password on different subdomains.

.RU domains are registered for not more than 1 year, but domains have been in use for over 2 years. 

DNS Verification via dig
=======

```
% dig +short TXT _psl.lk3.ru       
"https://github.com/publicsuffix/list/pull/1149"

% dig +short TXT _psl.ra-ru.ru
"https://github.com/publicsuffix/list/pull/1149"

% dig +short TXT _psl.zsew.ru 
"https://github.com/publicsuffix/list/pull/1149"
```

make test
=========

Add merge via web

### CODE REVIEW

**Review by dnsguru — CHANGES_REQUESTED** [review]
Please revise so that these are in alphabetical order, by first letter

**Comment by KirillUlyanov** [comment]
> Please revise so that these are in alphabetical order, by first letter

I fixed the order of domains in the list.

**Comment by fsodic** [comment]
> > Please revise so that these are in alphabetical order, by first letter
> 
> I fixed the order of domains in the list.

Reorder alphabet your company name bro

**Comment by KirillUlyanov** [comment]
> > > Please revise so that these are in alphabetical order, by first letter
> > 
> > 
> > I fixed the order of domains in the list.
> 
> Reorder alphabet your company name bro

Hey! Check now please :sweat_smile:

**Comment by fsodic** [comment]
Okay bro, just wait @dnsguru or @sleevi to approve it.

**Comment by fsodic** [comment]
If this is approve, please remember to keep your domain still active and if 1 or more domains isn't active just revise the list.

**Review by dnsguru — APPROVED** [review]
- DNS Validation Records Present and Confirmed Matching PR
- Tests Pass
- Rationale Clear and Accurate
- No Conflict with Base
- Domain Name Expiry <2Y; however, this will be accepted because: 
  - .RU TLD does not allow >1Y, but domains are registered in 2016 (as opposed to newly registered domain names, indicating a demonstration of continuity), and 
  - all whois matches to common registrar source and share domain nameservers and common ownership to the submitting entity.

Additionally, submitting party thoughtfully updated sorting of submission domains and subsequently the listing location of their submission section.

**APPROVED**

**Comment by dnsguru** [comment]
@KirillUlyanov Approved; MERGING
@fsodic thank you for catching the section sorting

**Pull request merged**
