### PR TITLE
Add CDDO's `api.gov.uk` domain

### PR DESCRIPTION
**Pull request by jamietanna**
Signed-off-by: Jamie Tanna <jamie.tanna@digital.cabinet-office.gov.uk>

### CODE REVIEW

**Comment by dnsguru** [comment]
Verified submitting party out of band via email

**Comment by jamietanna** [comment]
We have confirmed that we are happy with this going ahead. Marking as Ready for Review :+1:

**Comment by dnsguru** [comment]
- **Tests Pass**
- **DNS Verified** _(Out of band Verification of Gov resource also performed)_
- **No Conflict with Base**
- **Follows Guidelines**

Approved

Merged @jamietanna

**Review by dnsguru — COMMENTED** [review]
Approved

**Pull request merged**
