### PR TITLE
Add free selfhost dyndns

### PR DESCRIPTION
**Pull request by frankenstein91**
+selfhost.eu

### CODE REVIEW

**Comment by nexosone** [comment]
It is a free DDNS hoster, it's ok and save.

**Comment by weppos** [comment]
Are you the owner of the domain?

**Comment by frankenstein91** [comment]
No I'm not the owner of the domain. But it is needed for Let's encrypt.
Many German users are connected to this ddns hoster and can't create
certificates because of the domain limitation.
Am 31.03.2016 12:07 schrieb "Simone Carletti" <notifications@github.com>:

**Comment by weppos** [comment]
I'm sorry, the list is independently managed from Let's Encrypt.
Our guidelines requires the request to come from the owner.
https://github.com/publicsuffix/list/wiki/Guidelines

Let's Encrypt is currently in beta. They have recently relaxed the limits, and they will continue doing it while working towards the general availability.

**Comment by frankenstein91** [comment]
It's a no go the we must relay on a slow support for security. So please
contact them from your side if a approve is really needed. I think you
didn't speak with the owner of dotde.

You should support the security of the Web if some organization like let's
encrypt uses this list.

It's such a easy way to close and not helping.
Am 31.03.2016 13:32 schrieb "Simone Carletti" <notifications@github.com>:

**Comment by nexosone** [comment]
We all want to improve the Let's encrypt project, so it will be helpfull to extend the supported DDNS hoster. Also it would be nice for the security of the Internet. In my opinion Frank requests the right way.
It is the wrong way, to wait for the support of a DDNS hoster.

**Comment by weppos** [comment]
> We all want to improve the Let's encrypt project

The main issue in this discussion, is that _this_ is not the Let's Encrypt project. This is the public suffix list. If you want to improve Let's Encrypt, then you should move the discussion to the Let's Encrypt forums and issue tracker.

We don't plan to change our policy to please users of a particular service.

Moreover, you also have to understand that Let's Encrypt limit exists for a reason, and the service is still in beta.

**Pull request closed without merging**
