### PR TITLE
Adding WeDeploy domains

### PR DESCRIPTION
**Pull request by henvic**
I will let you know once the DNS authentication is ready.

### CODE REVIEW

**Comment by henvic** [comment]
The DNS Authentication is ready:

```bash
$ dig TXT _psl.wedeploy.me

; <<>> DiG 9.8.3-P1 <<>> TXT _psl.wedeploy.me
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59016
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_psl.wedeploy.me.		IN	TXT

;; ANSWER SECTION:
_psl.wedeploy.me.	242	IN	TXT	"https://github.com/publicsuffix/list/pull/420"

;; Query time: 97 msec
;; SERVER: 200.255.255.65#53(200.255.255.65)
;; WHEN: Thu Mar 23 11:47:37 2017
;; MSG SIZE  rcvd: 92

$ dig TXT _psl.wedeploy.io

; <<>> DiG 9.8.3-P1 <<>> TXT _psl.wedeploy.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29549
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_psl.wedeploy.io.		IN	TXT

;; ANSWER SECTION:
_psl.wedeploy.io.	237	IN	TXT	"https://github.com/publicsuffix/list/pull/420"

;; Query time: 99 msec
;; SERVER: 200.255.255.65#53(200.255.255.65)
;; WHEN: Thu Mar 23 11:47:39 2017
;; MSG SIZE  rcvd: 92
```

**Comment by sleevi** [comment]
As per the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) please explain why you are making this request, and provide sample domains so we can help make sure the entries are correct.

**Comment by henvic** [comment]
Hi @sleevi,

We allow costumers to create projects using the <project>.wedeploy.io (for production) and <project>.wedeploy.me for local development.

Some examples:
http://whatsapp.wedeploy.io/
http://supermarket.wedeploy.io/
http://boilerplate-auth.wedeploy.io/
http://boilerplate-liferay.wedeploy.io/
http://metrics.wedeploy.io/

These are all different sites, from different costumers (in this case, they are demos), not related with each other (besides the fact they are run on our infrastructure).

Docs: http://wedeploy.com/docs/

Thank you.

**Comment by sleevi** [comment]
Two quick followups - https://wedeploy.com gives an invalid cert, and https://www.wedeploy.com just redirects back to http://wedeploy.com . Could you make sure the domain you have is correct?

The name is listed as "WeDeploy", but based on the copyright, it sounds like it's LifeRay, Inc. Could you clarify and update the PR?

I've verified the TXT records are in place and this is otherwise ready to go.

**Comment by henvic** [comment]
Yes, @sleevi.
I can confirm the domain is correct.

I have updated the pull request.

WeDeploy is a service created by the company Liferay, Inc.

**Comment by groundcat** [comment]
Hi @henvic Do you still need these entries in the PSL? One or more domains have expired for a while. If the project has been decommissioned and the domain is no longer associated with an active project as described in your original request, please submit a new PR to rollback to avoid leaving unnecessary debris for PSL volunteers and future registrants to deal with. Thank you.

```
Domain Name: wedeploy.me
Registry Domain ID: 6a25cf54f8dd4c8c8957d61373575f86-DONUTS
Registrar WHOIS Server: WHOIS.ENOM.COM
Registrar URL: http://www.enom.com/
Updated Date: 2024-07-30T20:02:36Z
Creation Date: 2023-06-18T10:57:30Z
Registry Expiry Date: 2024-06-18T10:57:30Z
```

**Pull request merged**
