### PR TITLE
add CloudAccess.net free domains to Private

### PR DESCRIPTION
**Pull request by Pawel-Panek**
Domains used for free site provisioning.

### CODE REVIEW

**Comment by Pawel-Panek** [comment]
TXT record for verification added to all domains.

**Comment by Pawel-Panek** [comment]
Anything else we need to do to get the request accepted? We really need this for LetsEncrypt provisioning.

**Comment by gerv** [comment]
If it's Let's Encrypt you want, you will get what you want far faster by filling in their exceptions form.

**Comment by Pawel-Panek** [comment]
Thank you for advice. We've just done it. Anyways, please keep this PR under consideration.

**Comment by sleevi** [comment]
Needs to be updated per https://github.com/publicsuffix/list/wiki/Guidelines

Please provide sample domains, justification, and sort within the file appropriately.

**Comment by weppos** [comment]
Closed as no follow up.

**Comment by Pawel-Panek** [comment]
Please re-open.

I really missed your question, sorry for that. Here is the follow up:

**Sample domains**
Please go to https://www.cloudaccess.net and you will see options for site registration. Listed domains are available for free site registration. I can't disclose any live domain names as they belong to our customers. You may generate example domains by registering free service at CloudAccess.

**Justification**
We want to benefit especially from cookie protection. Other reasons are:
- Restricting cookie setting
- Restricting the setting of the document.domain property
- Sorting in the download manager
- Sorting in the cookie manager
- Searching in history
- Domain highlighting in the URL bar

**Sort within the file**
Can you explain this one? The domain list in patch file is sorted alphabetically. Should it be something else?

**Comment by weppos** [comment]
See https://github.com/publicsuffix/list/wiki/Guidelines

You need to sort the block by company, alphabetically. Instead, you simply added the entry at the end of the PRIVATE section.

**Comment by Pawel-Panek** [comment]
@weppos I moved our section up. It seems it makes a conflict with other pending commit. Anyways, it's above cloudControl now.

**Comment by weppos** [comment]
@Pawel-Panek please rebase your change with master so that it applies cleanly and I can merge it

**Comment by Pawel-Panek** [comment]
@weppos alright, it's showing no conflicts now.

**Comment by weppos** [comment]
@Pawel-Panek please **rebase** against master. The changeset should only contain your changes, not all of these:
https://github.com/publicsuffix/list/pull/372/files

**Comment by Pawel-Panek** [comment]
This is what git did when I did `git rebase master`. I know it looks messy but I'm not really proficient in git
to make it right. I better just add new PR so it looks clean. Here it is https://github.com/publicsuffix/list/pull/466

**Comment by sleevi** [comment]
Closing in favor of #466

**Pull request closed without merging**
