### PR TITLE
Adding Hoplix domains

### PR DESCRIPTION
**Pull request by W3b3r**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [X] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [X] This request was _not_ submitted with the objective of working around other third party limits
  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Organization Website: https://hoplix.com
I'm a Senior Software Engineer at Hoplix S.R.L., a company of print on demand product.

Reason for PSL Inclusion
====
Hoplxi S.R.L. offer free service of hosting on third level of hoplix.shop domain
We'd like to properly isolate each subdomain to prevent global cookie setting on hoplix.shop and our users need to verify our subdomains by yourself for facebook ads

All our users can purchase and/or connect their own domain name to their shops, if our user don't want to purchase and/or connect their own domain we need to improve cookie security and isolate each subdomain cookies for all *.hoplix.shop domains.

In addition if they use and/or not use own domain name we need to consider, the request between *.hoplix.shop domains samesite, and needed to leaving them open to CSRF.

This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we seek to resolve the impacts to the best of our ability to do so. Both Apple and Facebook support Public Suffix List for Private Click Measurement and Aggregated Event Measurement respectively.

* We have reviewed the wiki here outlining the PSL and understand what it is and is not.
* We have reviewed this matter with the team at Facebook, we are now fully aware about the consequences to the change we are requesting as it relates to cookies or other services, and choose to proceed in submitting this PR. We understand that despite reviewing the matter with Facebook, Facebook cannot control which use cases get accepted to the PSL
* We understand that there is not any urgency and should this PR be merged to include our requested change, that there is no control over the timing of this change being updated downstream in browsers, libraries, certificate authorities or other systems or processes that incorporate the PSL.
* We understand that if we later want to back out this change, there is also no guarantee that this will occur in a rapid fashion due to the same lack of control over browser, library, certificate authority, or other system or process changes.

DNS Verification via dig
=======
```
dig +short TXT _psl.hoplix.shop
"https://github.com/publicsuffix/list/pull/1405"
"https://github.com/publicsuffix/list/pull/1364" //old PR
"https://github.com/publicsuffix/list/pull/1282" //old PR
```

make test
=========
```
============================================================================
Testsuite summary for libpsl 0.21.0
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

```
Extra info
=========
There is another PR(#1364) about this domain make for try to add hoplix.shop to public suffix
There is another PR(#1282) about this domain make for try to add hoplix.shop to public suffix

### CODE REVIEW

**Comment by W3b3r** [comment]
Hello, today facebook sent me an email and now i seded to facebook this new PR link.
So I hope that the confirmation times from facebook on this PR are not too long to close the PR

**Comment by bedfordsean** [comment]
Confirming from the Facebook perspective that we have carried out our checks, and to the best of our ability to understand, Hoplix.shop is a legitimate platform hosting use case that caters to multiple subdomain businesses and therefore has a legitimate reason to be placed on to the PSL for the purposes of cookie separation for each of those subdomains.

@W3b3r please can you modify your TXT record to reference this PSL request?

**Comment by W3b3r** [comment]
@bedfordsean I'm currenctly editing that just a minute for the test with dig

**Comment by W3b3r** [comment]
@bedfordsean Ok i modified the TXT record.
Thank you for support.

**Comment by dnsguru** [comment]
Please read https://github.com/publicsuffix/list/issues/1245#issuecomment-981883312

**Comment by W3b3r** [comment]
@dnsguru I readed and I agree for proceed to PSL inclusion of hoplix.shop domain

**Comment by dnsguru** [comment]
Per notes in #1245 , seeing no objections, another small subgroup of submitted PR related to the IOS PCM changes and the effect on certain Facebook/Meta pixel clients that have been patienly waiting in the queue will proceed, assuming their _PSL entries and all of the other standard conditions of approval were met.

**Comment by dnsguru** [comment]
@W3b3r @bedfordsean Merged - keep an eye on this for unexpected impacts

**Pull request merged**
