### PR TITLE
Add `*.on-acorn.io`

### PR DESCRIPTION
**Pull request by cjellick**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowlegements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
This is being submitted on behalf of Acorn Labs. I, Craig Jellick, am a software architect at the company.

Acorn Labs is focused on improving the developer experience and operations of applications deployed on top of Kubernetes.

As it pertains to putting our domain on the PSL, our objective is to ease the pain of exposing applications deployed on otherwise private Kubernetes to the Internet. This is a very convoluted and inconsistent process across different Kubernetes cluster types and we seek to bring simplicity and consistency to that process.

Organization Website: https://acorn.io, but we haven't made it public yet. We are an early-stage startup.

Reason for PSL Inclusion
====
We are adding a feature to automatically provide each user cluster with a `<service name>.<user-id>.on-acorn.io` DNS entry, so each user-id is a mutually untrusting third-party that should not be able to set cookies readable by each other. We also plan to provide Let's Encrypt wildcard certs for each user-id.

Number of users this request is being made to serve: Since we will substantially ease a common pain associated with public cloud Kubernetes offerings, we expect this to quickly reach several thousand users.

DNS Verification via dig
=======

Done
```
dig +short TXT _psl.on-acorn.io
"https://github.com/publicsuffix/list/pull/1578"
```

Results of Syntax Checker (`make test`)
=========
Passed!
```
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
```

### CODE REVIEW

**Comment by dnsguru** [comment]
>We also plan to provide Let's Encrypt wildcard certs for each user-id.

No resources to support q&a on this here among the volunteer-based skeleton crew of the PSL, but you should check with LE to ensure that this PR would not actually have the opposite outcome from what you'd want with respect to wildcard issuance.   Rollbacks are unpredictable and take a long time.  Measure thrice, cut once :)

**Comment by cjellick** [comment]
Thanks. We've actually done this before for a different service called Rio. The author of that PR, @vincent99, is part of this effort as well.

That PR is here: https://github.com/publicsuffix/list/pull/779/files

Very similar situation, so we are familiar with how it will behave on the LE side.

**Comment by vincent99** [comment]
Correct... we successfully ran almost the same thing for Rio, but it was sadly just a side project that did not get any love from the entity that bought Rancher.  And we no longer work for them.  This will be a prominent feature of Acorn's main project.

The net effect of being added to PSL for LE will be that each `<user-id>.on-acorn.io` gets its own set of rate limits independent from other users.  Which is an admittedly convenient property to us, but not the only reason for the PR.

**Comment by cjellick** [comment]
Hi @dnsguru - wanted to check in on this.

I reread the guidelines again and I can't find anything we are going against. Your primary concern seems to be that we submitted this to get around Let's Encrypt limits. We addressed that via their process (and always intended to). We now would like to address the browser cookie isolation issue.

Thanks again for your time.

**Review by dnsguru — APPROVED** [review]
`
$ dig +short TXT _psl.on-acorn.io
"https://github.com/publicsuffix/list/pull/1578"
`

* DNS Validates
* Follows Guidelines
* Tests Pass
* No Conflict with Base

APPROVED

**Comment by dnsguru** [comment]
It appears that this is not an attempt to route around the LE Rate Limits, and that you've addressed that directly.

> We now would like to address the browser cookie isolation issue.

Yes, this appears the case.

**Comment by cjellick** [comment]
thanks @dnsguru! Much appreciated

**Comment by groundcat** [comment]
Hello @cjellick , it seems that the project or organization associated with your domain, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. 

- on-acorn.io is SERVFAIL

If the service has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Comment by drpebcak** [comment]
@groundcat I have fixed the issues with the nameservers for `on-acorn.io`, and I have ensured that the `_psl` txt record is present. We still want and need inclusion in the PSL. Thank you!

**Comment by cjellick** [comment]
Yep, just confirmed what @drpebcak said above, since I opened the original PR.

**Comment by groundcat** [comment]
Thank you @drpebcak @cjellick for confirming. `on-acorn.io` will be kept in the future as long as it meets the [guideline](https://github.com/publicsuffix/list/wiki/Guidelines).

**Comment by groundcat** [comment]
@cjellick do you still need on-acorn.io to be listed in the PSL? It is pointing to domain parking. acorn.io was listed on dan.com market.

**Comment by cjellick** [comment]
we do not. thanks for checking

**Pull request merged**
