### PR TITLE
Remove github.dev from PSL

### PR DESCRIPTION
**Pull request by josebalius**
* [x] Description of Organization
* [x] Reason for PSL Exclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: github.com

I'm a software engineer at GitHub working on the Codespaces product.

Reason for PSL Exclusion
====

We no longer want `github.dev` to be included in the PSL. The original intent for the addition was predicting several use cases that are no longer valid for our plans with `github.dev`. We have some initiatives that require removal.

DNS Verification via dig
=======

Do I still need to update DNS to this PR even though it is a removal? You can see the current record points to the PR where we added the domain: https://github.com/publicsuffix/list/pull/1290

make test
=========

### CODE REVIEW

**Comment by dnsguru** [comment]
>Do I still need to update DNS to this PR even though it is a removal? You can see the current record points to the PR where we added the domain: #1290

Not needed if prior submitter = update/removal submitter, but is needed where these are not same party.  Because this was submitted by @dmilburn w a 'bless' by @ptoomey3 we'd need the DNS _PSL txt to match this PR or both their thumbs up on this. 

See #1319 which is under proposal to help parties submitting PR to really consider their initial request to not disrupt their domain in the first place.

Just want to note, there is not a predictable (or controllable) timeline for when downstream PSL integrators/users/projects each update.  We really discourage (non-technical term) 'willy-nilly' add-remove as it can be disruptive to the requestor's affected domain(s), but also it is net double tax on disposible volunteer cycles vs taking no action at all to begin with.

Also, please add the WHY to the reason for excllusion.   We appreciate where parties submitting their rationale with some details as to what promoted the need to roll back the requested PR, as it builds documentation of things that people can avoid doing in the first place if at all possible.

**Comment by josebalius** [comment]
Thanks @dnsguru . They are both aware of this change, so I'm sure I can get their approval on this.

I'll update the OP with the rationale. We are also aware of the unpredictable timeline with a change like this and have discussed it at length. Ultimately we think this is the right move, and thank you for raising it.

**Comment by dnsguru** [comment]
No doubt you are right they will provide input or a thumbs up.  Will watch for their feedback.

That expanded rationale will help others avoid whatever was attempted and didn't work for github in this instance so describing what the initial request had hoped to acchieve, how the result differed from that once the PSL entry was present, and what unexpected outcomes that were bad.   Anything you can furnish to help others not make the same futile attempt is good for the community.

**Comment by dnsguru** [comment]
``` We no longer want github.dev to be included in the PSL. The original intent for the addition was predicting several use cases that are no longer valid for our plans with github.dev. We have some initiatives that require removal. ```

That added more words but remains unhelpful to others because it was equally vague

**Comment by dnsguru** [comment]
Not seeking to be punative for wasting my time, but was hoping we could get something better as a means to help others as opposed to "because: our reason", as it has zero real value - the primary objective is in reduction of the onslaught from the IOS/FB thundering herd... if we can point at things that outline requests that can be avoided and why.

**Comment by dnsguru** [comment]
So this doesn't rollback #1290, just github.dev.  githubpreview.dev remains, correct?

**Comment by josebalius** [comment]
`githubpreview.dev` remains correct.

**Review by ptoomey3 — APPROVED** [review]
👍 - Also wanted to acknowledge that removing something from the PSL doesn't guarantee is't removal from anything downstream of the list.

**Review by dnsguru — APPROVED** [review]
submitter ack'd rollback.

**Comment by dnsguru** [comment]
@ptoomey3 @josebalius @dmilburn THX for ACKS 

Since this project is currently crashing on your gitcouch... and technically #1319 is in discussion, merging this now

**Pull request merged**
