### PR TITLE
Add info.cx

### PR DESCRIPTION
**Pull request by igloo22225**
info.cx offers free sub domains through afraid.org. I would like to add the domain to the suffix list to ensure cookies are handled properly.

### CODE REVIEW

**Comment by igloo22225** [comment]
I have added a TXT record for _psl.info.cx. If you wish to validate by e-mail as well, I'll get back to any inquiries sent to the official whois e-mail swiftly.

**Comment by igloo22225** [comment]
Example domains:
illuminati.info.cx
iconoclasm.info.cx
igloo.info.cx

**Comment by sleevi** [comment]
Note: Adding info.cx to the PSL can prevent navigation to http://info.cx . Are you sure that's what you do?

**Comment by igloo22225** [comment]
Yes - that is not an issue. The page on the root domain has only been maintained at this point for liability purposes.

**Pull request merged**
