### PR TITLE
Add lelux.site

### PR DESCRIPTION
**Pull request by theel0ja**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://lelux.fi/

Organization providing services powered by free software. (related: https://libreho.st/)

I'm the administator of Lelux.fi.

Reason for PSL Inclusion
====

Going to be used for a public GitLab Pages instance.

DNS Verification via dig
=======

```
dig +short TXT _psl.lelux.site
"https://github.com/publicsuffix/list/pull/849"
```

make test
=========

I ran the test and it passed succesfully.

### CODE REVIEW

**Comment by sleevi** [comment]
You didn't share edit privileges, so I can't correct the issue by pointing the organization domain to lelux.fi , rather than the (not serving content) lelux.site

**Comment by theel0ja** [comment]
@sleevi I fixed it already.

**Comment by theel0ja** [comment]
Fixed, if this is what you want.

**Comment by sleevi** [comment]
It's normally easier if you allow maintainers to edit your pull requests. In looking at this again, another issue is that it's not sorted correctly - Lelux.fi does not come before GitHub.com when sorting by organization name. I would normally fix this so that it matches the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), but you'll need to do this.

**Comment by theel0ja** [comment]
@sleevi allowed edits from maintainers

**Comment by sleevi** [comment]
Thanks. I corrected the sorting now.

**Pull request merged**
