### PR TITLE
Update WapBlog.ID domain

### PR DESCRIPTION
**Pull request by fsodic**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====
Organization Website: https://www.wapblog.id

I'm Fajar Sodik from WapBlog Developer Team
WapBlog.ID is a platform for create a blog.

Reason for PSL Inclusion
====
WapBlog.ID is a platform blog builder who user can create a blog which our subdomain or their own domain. If they don't have a domain, we provide some excelent domain for them like wbq.me or wblog.id and many other.

It could be very usefull, if browser could correctly manage those subdomains (cookies, highlighting the subdomain, sorting by subdomain and not all the domain ). We want these services to be recognized as a known public suffix and wapblog.id services too.

Update:
i was mistake write the file which i contain **bloghp.id** and in my submission i write bloger.id

DNS Verification via dig
=======
My domain has PR on #1111 

make test
=========

### CODE REVIEW

**Comment by fsodic** [comment]
Hi @dnsguru  and @sleevi can i revise my previous PR?
#1111

**Review by dnsguru — APPROVED** [review]
Clerical change for typo;
- DNS validated 
- Rationale correct
- Tests Pass
- No Conflict with Base

**APPROVED**

**Comment by dnsguru** [comment]
Corrects domain typo in #1111

**Comment by fsodic** [comment]
Thanks :)

**Pull request merged**
