### PR TITLE
For our own free provider

### PR DESCRIPTION
**Pull request by MontiMcMannus**
Hi,

we are setting up an simple provider for free domains (currently we are testing our service, especially dyndns domains).
The sub domains will be available for everybody, so we would like to be on the list. Our background is the support for lets encrypt.

Thanks,
Jan Mönnich

### CODE REVIEW

**Comment by weppos** [comment]
Given that the service is not even developed, I encourage you to use the Let's Encrypt staging server (which has no rate limiting) for testing. Rate limiting will be lifted at some point when LE will exit the beta phase. In our view, that means that people should no longer need to be added to the PSL just to use LE.

Does it work for you?

**Comment by MontiMcMannus** [comment]
Hello,

not really, the service is fully developed. We are additional selling server boxes and started already testing with some choosen customers. This service provides a free dyndns service (and a configurable dns server). If you are interessent, please email me for the registration page for sub domains. The only thing which is not yet started is the final company with the public product.

Thanks, Jan

**Comment by MontiMcMannus** [comment]
Of course, you can validate the domain by writing to postmaster@ownprovider.com or via a whois.

**Comment by sleevi** [comment]
Please see [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) on how to format this request and authenticate it. Note: You will need to rebase it to avoid the conflicts being presented.

**Comment by MontiMcMannus** [comment]
- Email changed to jan.moennich@ownprovider.com (or must it be domain@moennich.net because of whois?)
- Rebased
- _psl.ownprovider.com.   3600    IN      TXT     "https://github.com/publicsuffix/list/pull/113"

**Comment by sleevi** [comment]
1) Please update the header to match the guidelines (note the leading and trailing space between the colon separating company name and address)

2) Are you sure this is correct? It is extremely dangerous to host arbitrary subdomains (e.g. `user1.ownprovider.com`, `user2.ownprovider.com`) with the official pages (`www.ownprovider.com`), in general, because it explicitly prohibits you from using subdomains to link your own resources (for example, for all intents and purposes, `www.ownprovider.com` and `login.ownprovider.com` would be treated as wholly distinct, even if they're both part of the OwnProvider infrastructure). Please confirm that you've read the Guidelines, are aware of the technical risks, and still want to proceed.

**Comment by MontiMcMannus** [comment]
1) Added the space
2) Yes, I know the implications, (it will enforce a more responsive page even for my successors due the lack of server hopping, and for more complex infrastructure we will use another domain), and I want to proceed. I read the guidelines at https://github.com/publicsuffix/list/wiki/Guidelines. And definitely most of the subdomains "belongs" to independent cusomers, which I want to seperate from each other (even my www.).

**Comment by sleevi** [comment]
Validated via TXT

**Pull request merged**
