### PR TITLE
Add cloud-ip.biz and ip-dynamic.org for ClouDNS

### PR DESCRIPTION
**Pull request by boyanpeychev**
# Public Suffix List (PSL) Submission

### Checklist of required steps

* [X] Description of Organization
* [X] Robust Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (`make test`)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the `_psl` TXT record in place in the respective zone(s).

__Submitter affirms the following:__ 

 * [X] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

ClouDNS is not using this to work around rate-limits of third party services. We are trying to work around this and understand deeply the customers requests for adding of our DDNS domain names in the PSL, because it looks like the lets encrypt limits are not the only one issue they are experiencing.

 * [X] This request was _not_ submitted with the objective of working around other third-party limits.

 * [X] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, and responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

 * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms to them.
 * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting.

---

For PRIVATE section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*. I could break my organization's website cookies and cause other issues, and the rollback timing is acceptable. *Proceed anyways*.
---

## Description of Organization

ClouDNS provides free dynamic dns hosting with subdomains.

**Organization Website:**

https://www.cloudns.net

## Reason for PSL Inclusion

We are dynamic dns provider. Each sub-domain name is used by different user. Usually we provide up to 30K sub-delegations per domain.

**Number of users this request is being made to serve: up to 30000**

## DNS Verification

```
$ dig _psl.cloud-ip.biz txt +short
"https://github.com/publicsuffix/list/pull/2202"

$ dig _psl.ip-dynamic.org txt +short
"https://github.com/publicsuffix/list/pull/2202"
```

## Results of Syntax Checker (`make test`)

TOTAL: 5
PASS: 5

### CODE REVIEW

**Comment by boyanpeychev** [comment]
$ dig _psl.cloud-ip.biz txt +short
"https://github.com/publicsuffix/list/pull/2202"

$ dig _psl.ip-dynamic.org txt +short
"https://github.com/publicsuffix/list/pull/2202"

**Comment by wdhdev** [comment]
@boyanpeychev Can you please put the PR template back and fill it out, thank you.

**Comment by boyanpeychev** [comment]
> @boyanpeychev Can you please put the PR template back and fill it out, thank you.

Done.

**Comment by groundcat** [comment]
- [x]  Expiration (Note: Must STAY >2y at all times)
  - [x]  cloud-ip.biz expires 2027-06-01
  - [x] ip-dynamic.org expires 2027-08-20
- [x]  DNS _psl entries (Note: Must STAY in place)
- [x]  Tests pass
- [x]  Sorting
- [x]  Reasoning/Organization description
  - Same requestor as in [#1593](https://github.com/publicsuffix/list/pull/1593)
- [x]  Non-personal email address

**Comment by wdhdev** [comment]
@boyanpeychev You have noted that you are looking to get around Cloudflare and Let's Encrypt rate limits, which is not allowed as per our guidelines. (Did you forget to remove them from the template?)

**Comment by boyanpeychev** [comment]
> @boyanpeychev You have noted that you are looking to get around Cloudflare and Let's Encrypt rate limits, which is not allowed as per our guidelines. (Did you forget to remove them from the template?)

Sorry, check by mistake. Fixed.

**Comment by wdhdev** [comment]
So to confirm, you are **not** submitting this PR with intentiond to evade Cloudflare and Let's Encrypt restrictions?

**Comment by simon-friedberger** [comment]
> No, we are submitting this PR as all our other domain names, because the end users using the sub-domains want to issue their own SSL certificates.

**Comment by simon-friedberger** [comment]
(Sorry, misclick.)

Could you please clarify how your users are prevented from getting SSL certificates without a PSL entry?

**Comment by boyanpeychev** [comment]
From what I know they are unable to make wildcard ssl validations and some services didn't accept them.
As I mentioned, we are providing hostnames to around 30K users per domain name. That never was an questioned before, I believe our first entries here are 7-8 years old.

**Comment by wdhdev** [comment]
Could it be due to Let's Encrypt rate limits? I've never had issues registering wildcards at the 4th, or even 5th level.

**Comment by boyanpeychev** [comment]
Well, I was thinking the same, but for some reason two comments above someone told me this is prohibited and I was thinking this is something I have submitted wrong.

**Comment by simon-friedberger** [comment]
Right, this is unfortunately a little confusing. The *reason* for inclusion must be something other than working around third party limits. So, if you are submitting something because you need separate domains for customers (as you clearly do) that's fine. However, in that case we would still like to know about any third party limits that this is also relevant to.

If you are submitting something _only_ to work around third party limits we ask that you resolve this with the third party directly.

**Comment by wdhdev** [comment]
@simon-friedberger I think it is fine. They already have other entries on the PSL and it seems they are seeking cookie separation as per their rationale (please confirm this @boyanpeychev). I think they just forgot to remove the part of the template stating they are trying to get around specific limits. They also have specified they are not attempting to get around any limits in their PR template.

**Comment by groundcat** [comment]
I have a ClouDNS account, which [allows](https://github.com/publicsuffix/list/pull/2196#issuecomment-2392685466) me to create subdomains under both `cloud-ip.biz` and `ip-dynamic.org` and point these subdomains to specific IP addresses. This aligns with the description in this PR, "dynamic DNS hosting with subdomains," I believe it is a valid reason for PSL inclusion to enable cookie separation for browsers, as I see no reason why ClouDNS would submit this PR _solely_ to bypass third-party limits. Based on [historically merged PRs](https://github.com/publicsuffix/list/pulls?q=is%3Amerged+DDNS), DDNS services are generally a valid use case for PSL inclusion.

**Comment by boyanpeychev** [comment]
@wdhdev yes cookie separation is also a reason to have our free domain names in this list. Thanks for pointing this!

**Comment by groundcat** [comment]
> From what I know they are unable to make wildcard ssl validations and some services didn't accept them.

Slightly off-topic here, but it seems that CAs like Let's Encrypt likely [ignore](https://community.letsencrypt.org/t/pantheon-and-public-suffix-domain-failure/98739/7) the private section and only use the ICANN section of the PSL. So, for domains in the private section, wildcards are still possible.

According to the [Baseline Requirements](https://cabforum.org/uploads/CA-Browser-Forum-BR-1.6.5.pdf):

> Current best practice is to consult a “public suffix list” such as http://publicsuffix.org/ (PSL), and to
> retrieve a fresh copy regularly. If using the PSL, a CA SHOULD consult the "ICANN DOMAINS" section only, not
> the "PRIVATE DOMAINS" section.

**Comment by simon-friedberger** [comment]
@wdhdev I also think it's fine I just wanted to resolve the communication issues. Clearly, they are also getting added because of third-party limits but these are not listed in the PR description now.

> From what I know they are unable to make wildcard ssl validations and some services didn't accept them.

Presumably, these are Letsencrypt and Cloudflare, but it would be great to know if there is anything else.

**Comment by danderson** [comment]
While we're here: another suffix in your block, `cloudns.ph`, seems to be unavailable. It's currently failing TXT record validation because all authoritative nameservers for that domain are down. Could you please fix it, or remove `cloudns.ph` from the PSL?

**Comment by boyanpeychev** [comment]
> While we're here: another suffix in your block, `cloudns.ph`, seems to be unavailable. It's currently failing TXT record validation because all authoritative nameservers for that domain are down. Could you please fix it, or remove `cloudns.ph` from the PSL?

Name servers are up and running and sub-delegations where working. Fixed the TXT record, thanks!

**Comment by simon-friedberger** [comment]
@boyanpeychev If you could add a statement that you are working around cloudflare and letsencrypt limits, and whatever else to the initial comment we could merge this.

**Comment by boyanpeychev** [comment]
> @boyanpeychev If you could add a statement that you are working around cloudflare and letsencrypt limits, and whatever else to the initial comment we could merge this.

We have tried to contact the complaining users first to get the whole picture first. Thanks!

**Comment by boyanpeychev** [comment]
Can we get this merged?

**Comment by groundcat** [comment]
Hello @boyanpeychev I have noticed that the domain `cloud-ip.biz` has been returning an `NXDOMAIN` error for some time. Additionally, a WHOIS lookup indicates a `serverHold` status. If the project associated with this domain has been decommissioned and there are no plans to reinstate it with the registry, please confirm whether it can be safely removed from the PSL.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period (over 30 days), your entry may be subject to removal. Thank you.

**Comment by boyanpeychev** [comment]
Yes, you are correct. This domain name was put on serverHold by the registry (GoDaddy) and they are not responding to any e-mails from our side. 

If you think it is better, I can submit PR to remove it for now until we get this case resolved?

**Comment by groundcat** [comment]
Thank you for your prompt response! I understand the situation - the domain is currently on serverHold by GoDaddy Registry and they haven't been responsive to your communications.

The main goal of this reminder/notification is to avoid accumulating non-functioning entries in the PSL, but we don't need to be overly strict about immediate removal if there's a possibility of restoration. It's up to your team's judgment:

- If you believe there's still a reasonable chance that GoDaddy Registry will restore the domain's functionality, we can keep it in the PSL for now
- However, if you think it's unlikely that the domain will be reinstated during its registration cycle, then yes, please feel free to submit a PR to remove it

**Comment by wdhdev** [comment]
That would be good.

**Pull request merged**
