### PR TITLE
Update (remove) .tn entries

### PR DESCRIPTION
**Pull request by smoussa2021**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Whois WebSite: https://whois.ati.tn
Organization Website: https://www.ati.tn
First E-mail Contact: nic@ati.tn
Second E-mail Contact: samir.moussa@ati.tn

Reason for PSL Inclusion
====

Listed sub-extensions are passed to domains under .TN.
DEFENSE.TN, RNU.TN , RNRT.TN, TUREN.TN, RNS.TN, EDUNET.TN and AGRINET.TN

They are no longer sub-extensions under which registrants can register domains.

Decision of the national telecommunication regulator, INTT:
http://www.intt.tn/upload/txts/fr/decision_du_college_de_l'int_n11-2020_du_23_dec_2020.pdf

DNS Verification via dig
=======
dig +short TXT _psl.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.com.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.ens.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.fin.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.gov.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.ind.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.info.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.intl.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.mincom.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.nat.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.net.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.org.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.perso.tn
"https://github.com/publicsuffix/list/pull/1426"

dig +short TXT _psl.tourism.tn
"https://github.com/publicsuffix/list/pull/1426"

make test
=========
Test ran and it was Ok.
Extensions list updated at https://www.ati.tn/nom-de-domaine/

### CODE REVIEW

**Comment by dnsguru** [comment]
IANA [.TN Entry](https://www.iana.org/domains/root/db/tn.html) lists ati.tn as NIC, for context

**Comment by dnsguru** [comment]
I viewed the ati.tr website, which is the NIC for .tn as identified by the IANA.  The [NIC's domain name page](https://www.ati.tn/nom-de-domaine/) shows the following namespaces available:

- .tn
- .agrinet.tn
- .com.tn
- .edunet.tn
- .ens.tn
- .fin.tn
- .gov.tn
- .ind.tn
- .info.tn
- .intl.tn
- .mincom.tn
- .nat.tn
- .net.tn
- .org.tn
- .perso.tn
- .rnrt.tn
- .rns.tn
- .rnu.tn
- .tourism.tn
- .turen.tn

This list comes from the only verifiable source that we can follow Authority from the IANA to .TN, and it does not seem to match the requested changes to the PSL.
 
While the letter referenced does appear official, it is sourced from a domain outside of the NIC and the affected extensions were not submitted with DNS proof.  The _psl txt records for info.tn and minicom.tn are different than those of the ones requested for removal.  Additionally, the verification of these txt records from 8.8.8.8 or other public resolvers fails at this time.

IF there are working DNS Proof tags (_psl) placed inside of ati.tn or .tn itself, or the affected strings that are requested for removal so that we can make a verification, it will help to further review on how to proceed.

**Comment by smoussa2021** [comment]
> 
> 
> IANA [.TN Entry](https://www.iana.org/domains/root/db/tn.html) lists ati.tn as NIC, for context

Extensions list updated at https://www.ati.tn/nom-de-domaine/
And DNS verification is ok.

**Comment by dnsguru** [comment]
Wow, very impressive and thorough, @smoussa2021 you have indicated administrative control of this namespace is tied to this PR and have validated it to my satisfaction by placing the DNS records.

```
Confirmed Locally:
~/.ssh$ dig +short TXT _psl.tn
"https://github.com/publicsuffix/list/pull/1426"
```
Confirmed Globally:
```
~/.ssh$ dig +short TXT _psl.tn 8.8.8.8
"https://github.com/publicsuffix/list/pull/1426"

~/.ssh$ dig +short TXT _psl.tn 1.1.1.1
"https://github.com/publicsuffix/list/pull/1426"

~/.ssh$ dig +short TXT _psl.tn 9.9.9.9
"https://github.com/publicsuffix/list/pull/1426"
```

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base
- Formatted / Sorted per Guidelines 

**Approved**

**Comment by dnsguru** [comment]
@smoussa2021 this is completed.

**Comment by smoussa2021** [comment]
Thank you for the time you spent for us.

**Pull request merged**
