### PR TITLE
Update public_suffix_list.dat

### PR DESCRIPTION
**Pull request by Lennon114**
$ dig TXT _psl.tuchacloud.com
https://github.com/publicsuffix/list/pull/100

### CODE REVIEW

**Comment by Lennon114** [comment]
I want to add tuchacloud.com as a VPS hosting provider.

**Comment by sleevi** [comment]
Validation record is missing, and request doesn't comply with https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change

**Comment by Lennon114** [comment]
Could You tell me, please, how to make validation record?
Thank You!

**Comment by Lennon114** [comment]
add pull request with info for domain

**Pull request closed without merging**
