### PR TITLE
add azurecontainer.io

### PR DESCRIPTION
**Pull request by jluk**
Users may create an arbitrary amount of subdomains for off of this one.

### CODE REVIEW

**Comment by sleevi** [comment]
It looks like you're waiting for the TXT record to be set. Could you explain why you didn't combine this with the previous Microsoft entry that @blowdart added?

**Comment by jluk** [comment]
@sleevi wasn't sure how to designate a different contact. I could slate it under the previous Microsoft entry with a dedicated comment with my info if that's preferred.

**Comment by blowdart** [comment]
Yea, I've moved on from Azure security now, so the removal of my name is a bonus :)

**Comment by blowdart** [comment]
I'll start up a discussion internally with the azure folks to get a DL set up anyway, but @jluk you should head the DNS route anyway. That came in long after I did my additions, so ... I didn't have to do that work *grin*

**Comment by jluk** [comment]
Update TXT record is in place.

```
:~$ dig TXT _psl.azurecontainer.io +short
"https://github.com/publicsuffix/list/pull/637"
```

**Comment by sleevi** [comment]
@blowdart Just since you were the last to touch, and because of https://github.com/publicsuffix/list/pull/637#issuecomment-379899227 , I just wanted to make sure y'all are good landing as is, as it seems to be in order (now that I resorted)

**Comment by blowdart** [comment]
Yea that discussion has started, and is now out of my hands. Thank goodness :) I'll let azure mull over what they want to do. But yea, it's fine by me.

**Pull request merged**
