### PR TITLE
Add `torun.pl`

### PR DESCRIPTION
**Pull request by MatKra84**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

The Nicolaus Copernicus University in Toruń was established in 1945 and is one of Poland's largest universities. It is composed of 17 faculties, including 3 dedicated to medicine at the Collegium Medicum UMK in Bydgoszcz. It offers education in over 100 fields of study, is a research university and has state-of-the-art research infrastructure. The Metropolitan Area Network in Torun (MSK TORMAN) is governed by the university.
MSK TORMAN not only manages the university's network, but is also telecommunication operator who offers a range of services. One of them is the possibility of registering subdomains in the regional domain "torun.pl".

Organization Website: 
https://www.man.torun.pl

Reason for PSL Inclusion
====

The "torun.pl" is a regional domain for institutions, enterprises and people associated with the city of Toruń.
Subdomains (*.torun.pl) are registered by independent 3rd parties. Main reason for PSL inclusion is to increase the level of security (Cookie Security).

Number of users this request is being made to serve:
around 1000

DNS Verification via dig
=======

dig +short TXT _psl.torun.pl 
"https://github.com/publicsuffix/list/pull/1684"

Results of Syntax Checker (`make test`)
=========

> PASS: libpsl_icu_fuzzer
> PASS: libpsl_icu_load_dafsa_fuzzer
> PASS: libpsl_icu_load_fuzzer
> ============================================================================
> Testsuite summary for libpsl 0.21.2
> ============================================================================
> # TOTAL: 3
> # PASS:  3
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  0
> # XPASS: 0
> # ERROR: 0
> ============================================================================
> Making check in tests
>   CC       test-is-public.o
>   CC       test-is-public-all.o
>   CC       test-is-cookie-domain-acceptable.o
>   CC       test-is-public-builtin.o
>   CC       test-registrable-domain.o
>   CCLD     test-is-cookie-domain-acceptable
>   CCLD     test-is-public-builtin
>   CCLD     test-is-public
>   CCLD     test-is-public-all
>   CCLD     test-registrable-domain
> PASS: test-is-public-builtin
> PASS: test-is-public
> PASS: test-is-cookie-domain-acceptable
> PASS: test-registrable-domain
> PASS: test-is-public-all
> ============================================================================
> Testsuite summary for libpsl 0.21.2
> ============================================================================
> # TOTAL: 5
> # PASS:  5
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  0
> # XPASS: 0
> # ERROR: 0
> ============================================================================

### CODE REVIEW

**Comment by mimi89999** [comment]
@dnsguru could you please review this pull request

**Comment by MatKra84** [comment]
The Nicolaus Copernicus University in Toruń is part of the public education sector. We need the add regional domain "torun.pl" to the PSL critically urgently, because one of the local government units needs to use the Cloudflare service and without this change is unable to do so. We have been waiting for moderation on the "to do" list for 8 months. @dnsguru could you please review this pull request? It's really important for us.

**Comment by MatKra84** [comment]
@dnsguru Any update  ? It's really important for us.

**Comment by simon-friedberger** [comment]
@MatKra84 Can you please explain what this Cloudflare service is and why you need a PSL entry for it?

**Comment by simon-friedberger** [comment]
@MatKra84 Thanks!

I am not sure how exactly to check validity for .pl domains. I am getting this from `dns.pl`:
`End of the billing period | 2024.12.31 13:00:00`
Could you show that you really have 2 years of validity?

**Comment by mimi89999** [comment]
@simon-friedberger 
```
$ whois torun.pl

DOMAIN NAME:           torun.pl
registrant type:       organization
nameservers:           bilbo.nask.org.pl. [195.187.245.51]
                       blackbox.uci.uni.torun.pl. [158.75.1.5]
                       flis.man.torun.pl. [158.75.33.142]
                       koala.uci.uni.torun.pl. [158.75.1.4]
created:               1995.01.01 12:00:00
last modified:         2021.12.08 18:42:15
renewal date:          2024.12.31 13:00:00

no option

dnssec:                Unsigned


REGISTRAR:
cyber_Folks S.A.
ul. Franklina Roosevelta 22
60-829 Poznań
Polska/Poland
tel.: +48.122963663
info@domeny.pl

WHOIS database responses: https://dns.pl/en/whois

WHOIS displays data with a delay not exceeding 15 minutes in relation to the .pl Registry system
```

You can also use the web interface https://dns.pl/whois

**Comment by simon-friedberger** [comment]
@mimi89999 Yes, that's what I did but it doesn't have an expiration it only has a renewal date and that is not more than 2 years in the future.

**Comment by dnsguru** [comment]
> The Nicolaus Copernicus University in Toruń is part of the public education sector. We need the add regional domain "torun.pl" to the PSL critically urgently, because one of the local government units needs to use the Cloudflare service and without this change is unable to do so. We have been waiting for moderation on the "to do" list for 8 months. @dnsguru could you please review this pull request? It's really important for us.
> 

Your request is in the queue for volunteers to review but there are many ahead of it.

Understanding the urgency, please work directly with Cloudflare to solve an urgent issue with Cloudflare.

They have elevated account options that allow names to exist in more than one account, or they are the most appropriate party to obtain exception to their account limits with.

The PSL guidelines specifically identify that requests to overcome third party limits are a rationale for rejection on pull requests.

Rather than reject the request, it requires additional time to review by the unpaid volunteers who maintain the project in their free time.

Option a - Working directly with Cloudflare, especially if this is urgent, is your most appropriate path.  

Option b is patience, but further pressure to use the PSL addition being needed to overcome third party limits as a rationale for expediting the PR is likely to be a rejection rationale.

**Comment by MatKra84** [comment]
First of all, thank you very much for your reaction, the entire discussion and a closer look at our domain case.

The Nicolaus Copernicus University has owned the "torun.pl" domain from the very beginning (1995). We regularly extend its validity for subsequent periods. The domain, as a regional domain, was (and is) possible to register by external entities practically from the very beginning.

I fully understand and greatly appreciate that the PSL list is maintained by volunteers who dedicate their time to manage it.

We're trying to be really patient and we don't want to put pressure on anyone. It just seems to me that waiting almost 11 months (from January 16, 2023) for a positive decision is not a short period of time.

In this particular case, we will try to solve the problem with Cloudflare (although I think it will not be easy), but the PSL is currently a really important list - cookie security, DMARC (a new law is coming into force in Poland forcing its use for public organizations), TLS certificates and much more.

Maybe it is worth taking advantage of the help offered by the M3AAWG group:

https://dmarc.org/2023/05/m3aawg-calls-for-coalition-to-support-public-suffix-list/

**Comment by simon-friedberger** [comment]
To be clear, I also checked
* [x] DNS record
* [x] Test run
* [x] Sorting
* [ ] Validity

The only issue here might be validity but it was almost 2 years when the PR was created.

I don't fully understand the limitation on the CF side. I've had a look at their documentation and it doesn't give a clear reason why this requirement exists. I've asked in their community forum [here](https://community.cloudflare.com/t/what-exactly-is-the-reason-for-a-site-to-require-the-apex-to-be-an-etld-1/575792). @MatKra84 If you get any information from them please add it here and in that thread.

**Review by simon-friedberger — APPROVED** [review]

**Comment by dnsguru** [comment]
@MatKra84 this is merged.  

After review of the pull request by peers it was determined that the primary objective of the PR was not to bypass third party limits.

Thank you for your patience, as this project is very lightly resourced by volunteers.

**Comment by MatKra84** [comment]
Thanks for all your support with adding "torun.pl" domain.
 I'm truly grateful for all the effort you've put into this task.

**Pull request merged**
