### PR TITLE
adding storj.farm for Storj Labs Inc.

### PR DESCRIPTION
**Pull request by phutchins**

### CODE REVIEW

**Comment by phutchins** [comment]
Before adding, I want to be sure that I should not be using *.storj.farm instead of storj.farm. We have users for which we will be generating DNS addresses. The host portion of the address will likely be derived from the users address on the Storj network which could look something like `03e91496a4b0016480dfa1aa640247ebcb10a370.storj.farm`.

They will use an automated service that we provide to generate individual Lets Encrypt certificates for this DNS address. The DNS address will point to that users host which is out of our control.

For this case would simply `storj.farm` be correct?

**Comment by phutchins** [comment]
Anything more that I need to do to get this going?

**Comment by phutchins** [comment]
Any movement on these?

**Comment by gerv** [comment]
> For this case would simply storj.farm be correct?

Yes.

Did you add the relevant DNS record, as outlined in the submission guidelines?

**Comment by phutchins** [comment]
@gerv, Thanks!

I hadn't added the DNS record as I was waiting on confirmation that I'd done this correctly. TXT record added. 

```
 dig TXT _pls.storj.io

; <<>> DiG 9.8.3-P1 <<>> TXT _pls.storj.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7292
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_pls.storj.io.                 IN      TXT

;; ANSWER SECTION:
_pls.storj.io.          1799    IN      TXT     "https://github.com/publicsuffix/list/pull/400"

;; Query time: 61 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Thu Mar  2 10:11:18 2017
;; MSG SIZE  rcvd: 89
```

**Comment by phutchins** [comment]
DNS added.

```
dig TXT _psl.storj.farm

; <<>> DiG 9.8.3-P1 <<>> TXT _psl.storj.farm
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53907
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_psl.storj.farm.               IN      TXT

;; ANSWER SECTION:
_psl.storj.farm.        1799    IN      TXT     "https://github.com/publicsuffix/list/pull/400"

;; Query time: 132 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Thu Mar  2 10:35:30 2017
;; MSG SIZE  rcvd: 91
```

**Comment by groundcat** [comment]
Hi @phutchins do you still need `storj.farm` to be included in the PSL? It seems that `storj.farm` is not actively used.

**Comment by phutchins** [comment]
No, I'm not with Storj labs any longer but you can surely remove storj.farm
from PSL.

Thanks
-Philip

**Pull request merged**
