### PR TITLE
The list of Jelastic public domains was extended. Addition to #1023 #1063 #1092

### PR DESCRIPTION
**Pull request by vadym-graf**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====
Jelastic is a Multi-Cloud PaaS (Platform as a Service) with decentralized network of independent cloud hosting service providers located across the Globe.

**Organization Website:** [https://jelastic.com](https://jelastic.com)

Reason for PSL Inclusion
====
Addition to #1023, #1063, and #1092
Security enhancement between the subdomains.
There is a large network of independent and distributed cloud hosting providers that offer shared domains for their end users, for example *.cloudjiffy.net. End users can get a custom subdomain on top of the shared public domain, for example myapp.cloudjiffy.net. Such subdomains are managed by different users or organisations with the ability to set cookies and they may create an arbitrary amount of subdomains. We would like all of the public domain names to be compliant, including cookie handling and DNS sorting.

Similar accepted cases:
#931
#637
#714

**The list of public domains:**
mel.cloudlets.com.au
cloud.interhostsolutions.be
users.scale.virtualcloud.com.br
mycloud.by
alp1.ae.flow.ch
es-1.axarnet.cloud
diadem.cloud
it1.eur.aruba.jenv-aruba.cloud
it1.jenv-aruba.cloud
it1-eur.jenv-arubabiz.cloud
primetel.cloud
uk.primetel.cloud
ch.trendhosting.cloud
de.trendhosting.cloud
clicketcloud.com
ams.cloudswitches.com
au.cloudswitches.com
sg.cloudswitches.com
elastyco.com
nv.elastyco.com
paas.hosted-by-previder.com
rag-cloud.hosteur.com
rag-cloud-ch.hosteur.com
jcloud-ver-jpc.ik-server.com
kilatiron.com
jed.wafaicloud.com
lon.wafaicloud.com
ryd.wafaicloud.com
paas.leviracloud.eu
demo.datacenter.fi
ocs.opusinteractive.io
cloud.unispace.io
cloud-de.unispace.io
cloud-fr1.unispace.io
jc.neen.it
cloud.jelastic.open.tim.it
jcloud.kz
upaas.kazteleport.kz
jl.serv.net.mx
fra1-de.cloudjiffy.net
west1-us.cloudjiffy.net
ams1.jls.docktera.net
jls-sto2.elastx.net
jls-sto3.elastx.net
fr-1.paas.massivegrid.net
lon-1.paas.massivegrid.net
lon-2.paas.massivegrid.net
ny-1.paas.massivegrid.net
ny-2.paas.massivegrid.net
sg-1.paas.massivegrid.net
nordeste-idc.saveincloud.net
j.scaleforce.net
jelastic.tsukaeru.net
atl.jelastic.vps-host.net
njs.jelastic.vps-host.net
unicloud.pl
mircloud.ru
enscaled.sg
phx.enscaled.us
mircloud.us

DNS Verification via dig
=======

```
graf@graf-l:~$ dig +short TXT _psl.mel.cloudlets.com.au
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.cloud.interhostsolutions.be
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.users.scale.virtualcloud.com.br
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.mycloud.by
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.alp1.ae.flow.ch
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.es-1.axarnet.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.diadem.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.it1.eur.aruba.jenv-aruba.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.it1.jenv-aruba.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.it1-eur.jenv-arubabiz.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.primetel.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.uk.primetel.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.ch.trendhosting.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.de.trendhosting.cloud
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.clicketcloud.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.ams.cloudswitches.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.au.cloudswitches.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.sg.cloudswitches.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.elastyco.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.nv.elastyco.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.paas.hosted-by-previder.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.rag-cloud.hosteur.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.rag-cloud-ch.hosteur.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.jcloud-ver-jpc.ik-server.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.kilatiron.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.jed.wafaicloud.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.lon.wafaicloud.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.ryd.wafaicloud.com
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.paas.leviracloud.eu
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.demo.datacenter.fi
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.ocs.opusinteractive.io
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.cloud.unispace.io
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.cloud-de.unispace.io
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.cloud-fr1.unispace.io
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.jc.neen.it
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.cloud.jelastic.open.tim.it
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.jcloud.kz
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.upaas.kazteleport.kz
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.jl.serv.net.mx
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.fra1-de.cloudjiffy.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.west1-us.cloudjiffy.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.ams1.jls.docktera.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.jls-sto2.elastx.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.jls-sto3.elastx.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.fr-1.paas.massivegrid.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.lon-1.paas.massivegrid.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.lon-2.paas.massivegrid.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.ny-1.paas.massivegrid.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.ny-2.paas.massivegrid.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.sg-1.paas.massivegrid.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.nordeste-idc.saveincloud.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.j.scaleforce.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.jelastic.tsukaeru.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.atl.jelastic.vps-host.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.njs.jelastic.vps-host.net
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.unicloud.pl
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.mircloud.ru
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.enscaled.sg
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.phx.enscaled.us
"https://github.com/publicsuffix/list/pull/1095"
graf@graf-l:~$ dig +short TXT _psl.mircloud.us
"https://github.com/publicsuffix/list/pull/1095"
```

make test
=========
```
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by dnsguru** [comment]
@vadym-graf I see "This pull request is still a work in progress" - will review once you commit

**Comment by dnsguru** [comment]
@ihorman AND @vadym-graf  please confirm you need this many domains - this is a substantial amount of domains to add to the overhead of downloading PSL with bandwidth and size

**Comment by ihorman** [comment]
@dnsguru that is the last big portion of public domains that are used by Jelastic Ecosystem and Jelastic partners. Then the list will be managed in far slowly manner.  All these domains are indeed real public domains.  Thank you in advance!

**Comment by ihorman** [comment]
Added 3 more public domains
ca.reclaim.cloud
uk.reclaim.cloud
us.reclaim.cloud
------------------------
 ihorman@IK-MacBook-Pro # dig +short TXT _psl.uk.reclaim.cloud                                                                         
"https://github.com/publicsuffix/list/pull/1095"
 ihorman@IK-MacBook-Pro # dig +short TXT _psl.ca.reclaim.cloud                                                                        "https://github.com/publicsuffix/list/pull/1095"
 ihorman@IK-MacBook-Pro # dig +short TXT _psl.us.reclaim.cloud                                                                         
"https://github.com/publicsuffix/list/pull/1095"

@dnsguru  
Could you please help us with the domains that are in a list?
I confirm that domains above are indeed real shared domains where subdomains are used by completely  different users, companies and organisations. Our goal is to make them secured and compliant. 
If you need any additional information about any of stated Jelastic Partner (domain owners) - I will be glad to provide it to you on request. 
Thank you for your understanding.

**Comment by dnsguru** [comment]
This is A LOT - to go through and review is taking longer than typical
reviews do.

Please respect and remember that this is volunteer-driven

**Comment by ihorman** [comment]
@dnsguru  thank you, we will be waiting :)

**Comment by dnsguru** [comment]
_psl.gpuoncloud.in and _psl.mum.gpuoncloud.in are timing out and failing all the DNS tests on 1.1.1.1 and 8.8.8.8 - confirm that domain is configured correctly.

**Comment by vadym-graf** [comment]
@dnsguru 
gpuoncloud.in and mum.gpuoncloud.in currently suspended and are not used. So I deleted them from public_suffix_list.dat.

**Comment by dnsguru** [comment]
Can you please explain why you submited a suspended name to this resource?

Between the additional edits made after the pr was submitted and this
expired name, the request is taking extra volunteer cycles.

Please review that the pr is final, confirm this is complete, and that the
names all have more than 1 year before they expire or require renewal.

**Comment by ihorman** [comment]
@dnsguru  
> Can you please explain why you submited a suspended name to this resource?
These both shared domains belongs to a company that used to be a part of Jelastic Ecosystem, they stopped their services just recently, accept our apologies for that inconvenience. 
@vadym-graf  could you please also delete these domains in a PR itself (I mean from the list, not only from the dat file).
Thanks in advance!

**Comment by vadym-graf** [comment]
> @vadym-graf could you please also delete these domains in a PR itself (I mean from the list, not only from the dat file).
Done

**Review by dnsguru — APPROVED** [review]
- DNS Validations OK
- Test passes
- Rationale clear and accurate
- No Conflict with Base

**APPROVED**

**Comment by dnsguru** [comment]
@ihorman @vadym-graf MERGING

appreciate these all coming in one comprehensive request, but this was a lot to go through in a single PR so it took longer.  

Please note #1109 and keep up on renewal durations for the future to keep entries in place.

**Comment by ihorman** [comment]
@dnsguru  thank you !

**Comment by groundcat** [comment]
Hello @ihorman Are these entries still needed in the PSL? 

```
cloud.unispace.io
cloud-de.unispace.io
cloud-fr1.unispace.io
```

The domain `unispace.io` has expired. Your domain may be removed from the PSL if we don't hear back from you. If the project has been decommissioned and the domain is no longer tied to an active project as described in your original request, please confirm here that it can be safely removed or submit a new PR to remove these. This will help avoid unnecessary clutter for PSL volunteers and future registrants. Thank you.

```
Domain Name: unispace.io
Registry Domain ID: 6b765189ce8d43fabc43a67d22296d3b-DONUTS
Registrar WHOIS Server: whois.regtons.com
Registrar URL: http://regtons.com/
Updated Date: 2024-08-29T22:15:26Z
Creation Date: 2017-08-09T08:21:40Z
Registry Expiry Date: 2024-08-09T08:21:40Z
```

**Comment by groundcat** [comment]
and also:

```
lon.wafaicloud.com
cloud.jelastic.open.tim.it
jelastic.tsukaeru.net
jelastic.regruhosting.ru
```

@ihorman @vadym-graf @tuchinsun @dmitrykhimich Please confirm. 

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Comment by tuchinsun** [comment]
Hi,
Thank you for the notification. I've reviewed our existing list, and the following domains(subdomains) can be deleted from the PSL list

```
mycloud.by
amscompute.com
kilatiron.com
lon.wafaicloud.com
cloud-fr1.unispace.io
cloud.jelastic.open.tim.it
faststacks.net
jelastic.tsukaeru.net
jelastic.regruhosting.ru
upaas.kazteleport.kz
```

**Comment by groundcat** [comment]
@tuchinsun thanks for confirming, opened PR #2148

**Comment by groundcat** [comment]
Hello @ihorman @vadym-graf @tuchinsun @dmitrykhimich

Is this entry still needed in the PSL?

`mircloud.us`

These nameservers are not responding:

```
Name Server: ns1.mircloud.us
Name Server: ns2.mircloud.us
```

`diadem.cloud`

Its DNS delegation appears consistent with domain parking.

```
Name Server: ns1.park-my-domain.net
Name Server: ns2.park-my-domain.net
```

**Pull request merged**
