### PR TITLE
Add kasserver.com / test-account.com to Private Section

### PR DESCRIPTION
**Pull request by wkallinklcom**
// kasserver.com & test-account.com : Submitted by Werner Kaltofen wk@all-inkl.com
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====
Web hosting company
Organization Website: all-inkl.com is a web hosting brand of Neue Medien Muennich GmbH

Reason for PSL Inclusion
====
The domain offer customers free subdomains (Cookie Security)

DNS Verification via dig
=======
 dig +short -t txt _psl.kasserver.com
 \"https\://github.com/publicsuffix/ list/pull/1004"

make test
=========
no mistakes

### CODE REVIEW

**Comment by wkallinklcom** [comment]
.

**Comment by wkallinklcom** [comment]
Add kasserver.com and test-account.com

**Comment by dnsguru** [comment]
DNS test confirmed **kasserver.com**
```
>nslookup -type=txt _psl.kasserver.com
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.kasserver.com      text =

        "https://github.com/publicsuffix/list/pull/1004"
```
DNS test confirmed **test-account.com**
```
>nslookup -type=txt _psl.test-account.com
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.test-account.com   text =

        "https://github.com/publicsuffix/list/pull/1004"
```

**Comment by weppos** [comment]
Given the PSL is a finite resource, we've been discouraging/rejecting the use of test domains.

For this reason, I've arguments against including test-account.com.

**Comment by weppos** [comment]
It's also worth to note this PR is incorrectly formatted, the sorting of the new entries is incorrect according to the guidelines.

**Comment by wkallinklcom** [comment]
I have now observed the sorting and removed test-account.com

**Comment by tinohager** [comment]
I think the domain “kasserver.com” should be listed in the section `// ===BEGIN PRIVATE DOMAINS===`.

 Currently, it is listed in the section `ICANN DOMAINS`, which means that `ns5.kasserver.com` is issued as a `TLD`.

**Comment by wdhdev** [comment]
It is in the private domains section, not sure what you're talking about.

https://github.com/publicsuffix/list/blob/main/public_suffix_list.dat#L11369

**Comment by tinohager** [comment]
@wdhdev Sorry, you're absolutely right, I made a mistake here, my apologies.

**Pull request closed without merging**
