### PR TITLE
Domains are removed `hidora.com`, `users.scale.virtualcloud.com.br`, `clicketcloud.com`

### PR DESCRIPTION
**Pull request by tuchinsun**
### Checklist of required steps

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 
  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting
---
 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Jelastic is a Multi-Cloud PaaS (Platform as a Service) with decentralized network of independent cloud hosting service providers located across the Globe.

Organization Website: 
https://jelastic.com

Reason for PSL Inclusion
====

We reviewed all previously added domains and we would like to remove domains. The reason is we can't renew wildcard SSL certificates because domains placed in PSL list 

The list of public domains to be removed:
* hidora.com
* users.scale.virtualcloud.com.br
* clicketcloud.com

DNS Verification via dig
=======
```
$ dig +short TXT _psl.hidora.com 
"https://github.com/publicsuffix/list/pull/1598"
```
```
$ dig +short TXT _psl.users.scale.virtualcloud.com.br
"https://github.com/publicsuffix/list/pull/1598"
```

```
$ dig +short TXT _psl.clicketcloud.com
"https://github.com/publicsuffix/list/pull/1598"
```

Results of Syntax Checker (`make test`)
=========

```
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by dnsguru** [comment]
rolls back portions of #1023 added in 2020

**Comment by dnsguru** [comment]
There is a bit of a queue ahead of this, and rollbacks are typically a 60 day waiting period to discourage hop-on, hop-off requests that burn through volunteer time.  

The propogation delay portion of the wiki should also be read in order to understand what appropriate expectations should be about how quickly changes [https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion)

**Comment by dnsguru** [comment]
@ihorman because you added these, please comment about this PR rollback

**Review by dnsguru — APPROVED** [review]
* rollback     PR Submitter != Initial PR Author
* DNS Validation Entries pass = this PR
* Tests Pass
* No Conflict with base
APPROVED  (pending brief comment period opportunity for prior PR author)

**Comment by ihorman** [comment]
Dear @dnsguru, unfortunately, because of some circumstances we have to remove the following domains from PSL. 
I confirm the rollback, please proceed. 
Thank you for your help.

**Comment by matthieu-robin** [comment]
Hello, could you please accept this PR as soon as possible? It's becoming very urgent. Thanks a lot for your help on this.

**Review by dnsguru — APPROVED** [review]
* tests pass
* no conlfict
* guidelines followed for soritng
* dns validation

APPROVED


thank you for cleaining up entries, many do not take the time to do this

**Comment by dnsguru** [comment]
@matthieu-robin MERGING This change thank you for patience

**Pull request merged**
