### PR TITLE
Add *.isc.upenn.edu to public suffix list

### PR DESCRIPTION
**Pull request by amh5366**

### CODE REVIEW

**Comment by amh5366** [comment]
Hello!

is there any movement on this? 

Thank you :)

**Comment by frju365** [comment]
We need a reason for this PR and a short description of the company/orga which owns these domains pls. Just say "add ...domain.tld" is just not enough. Pls follow Guidlines : https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by amh5366** [comment]
Hey frju365!

We have a project to test Let's Encrypt as a possible solution to satisfy our SSL Certificate needs. We have run into a snag where let's encrypt tries to use the Domain upenn.edu, which would be fine however, Pantheon currently uses Let's Encrypt to create SSL's with upenn.edu, and has a rate limit increase. We would like to add isc.upenn.edu because after talking with them, we believe adding this domain is the best solution to our problem. 

For authentication, if my personal email is not enough, we can use <linuxadmins@lists.upenn.edu> as that may meet your criteria. Doing a dig for _ps1.isc.upenn.edu may be problematic as it's being used by a different server, and we have a separate team that does DNS. 

Please let me know if this description is satisfactory! 

Andrew

**Comment by sleevi** [comment]
Closing as WontFix, per https://github.com/publicsuffix/list/wiki/Guidelines and https://publicsuffix.org/learn/

Bypassing rate limits or requests not from the DNS admin are not valid requests.

**Comment by sleevi** [comment]
Why are you trying to get added then?

**Comment by amh5366** [comment]
While reviewing the Let's Encrypt documentation, they state that they use the public suffix list to calculate the registered domain. (https://letsencrypt.org/docs/rate-limits/ , line 13).

When testing Let's Encrypt certificates, their client will only calculate 'upenn.edu' when trying to register a certificate. Our registered domain is 'isc.upenn.edu'. 

The reason that we are taking this route is because we believe this is the best course of action after hours of testing.

**Comment by sleevi** [comment]
This does not sound like a valid reason to request addition to the PSL,
then. Please see the links I mentioned.

**Comment by dtenney** [comment]
Hi Sleevi, Sorry to step in here, I know that this sounds a bit confusing, and I hope to help clear it up.

I work with Andrew on the same team here at the university, and we are looking for the ability to use the Let's Encrypt technology for our environment outside of the current products that are already used within a separate department on campus.

As you can imagine the complex and decentralized environment here makes it difficult to provide services as just "upenn.edu", and we'd like to portion off a third-level domain for deployment for our large server environment. Without the separation we are unable to utilize the service as there are others who have already maxed out the limits.

To answer frju365's question a bit more throughly, we are the Systems Administration group within ISC Tech Services under the University of Pennsylvania.

Please let me know if you need any clarifications around the need!

Thanks!

David

**Comment by davidstrauss** [comment]
I outlined the justifications for adding upenn.edu in private email (to a different maintainer), and still think it's appropriate for the PSL's role in web infrastructure. UPenn's case is not really about "increasing limits" as much as handling many parties with jurisdiction over different domains and subdomains. The most obvious manifestation of that problem for UPenn just happens to be in one party running into limits exhausted by another, but _this problem is not solvable by requesting higher limits_ because, if one party exhausts the new, higher limit, the problem occurs again as long as there's no isolation.

Also, normal PSL goals apply to UPenn's case:

- Avoiding supercookies that cause inadvertent exposure to credentials. A student-launched site should not be able to retrieve badly configured session cookies from, say, a department's site.
- Making it clear to users that the relevant authority behind most subdomains isn't the same as the one behind the subdomains. This mitigates potential phishing behavior by, say, a student-launched site running on a UPenn subdomain.
- Restricting activity like altering document.domain.
- Isolating DOM Storage allowances. A student-launched site should not be able to exhaust these limits for other UPenn sites.

While UPenn's subdomains are only open to private registration, that still seems to be allowed by the PSL guidelines.

The fact that UPenn experiences issues from Let's Encrypt treating all of upenn.edu as a shared quota is only one reason why isolating the sites using the PSL would be beneficial to them and their user community. It is not the sole reason I recommended that they seek inclusion in the PSL, even if it motivated the initial discussion.

**Comment by sleevi** [comment]
There has been no evidence provided to support these other claims. This
again continues to be a clear attempt to bypass Let’s Encrypt Rate Limits,
which is not a valid reason. Leaving this as Closed/WontFix.

**Comment by davidstrauss** [comment]
> There has been no evidence provided to support these other claims.

I'm not sure how to provide the evidence you're seeking. The only evidence mentioned in the PSL guidelines is authority to operate the domain, and that's not the sticking point here. Everything else is based on description of the how the subdomain operates.

While Let's Encrypt is why we *started* looking into options, the reason I recommended the PSL is because their deployment generally matches its goals. UPenn's ISC is, among other things, [a hosting provider](https://www.isc.upenn.edu/web-development) that deploys sites to its subdomains, just like Flynn, GlobeHosting, LCube, and Futureweb, which are on the PSL. Anyone with a UPenn affiliation has access to tools to deploy sites to `[something].isc.upenn.edu`.

> This again continues to be a clear attempt to bypass Let’s Encrypt Rate Limits, which is not a valid reason. Leaving this as Closed/WontFix.

The guidelines are clear that you don't support inclusions to the PSL "whose sole purpose is to circumvent Let's Encrypt rate limits," but that is not the sole purpose of this request. I believe you're conflating *why the discussion was started* with the *only goal*.

The conversation went like this:
- *UPenn:* The admins of sites we're launching on subdomains are running into Let's Encrypt limits.
- *Me:* Looking at how you're administering the subdomains (self-registration and a diversity of administrators of those sites), registration on the PSL would provide appropriate isolation of cookies, quotas, and other interactions, including the Let's Encrypt one you've noticed.

I feel like you're faulting UPenn for desiring quota isolation on Let's Encrypt, but that should have no bearing on their request (for or against). Their architecture is as suitable for the PSL as the hosting providers I mentioned, and UPenn's community will benefit from all of the effects, not just side-effects at Let's Encrypt.

**Pull request closed without merging**
