### PR TITLE
Add_customer-oci.com

### PR DESCRIPTION
**Pull request by greg-drake-oracle**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Oracle Cloud Infrastructure (OCI)
OCI Website: https://docs.cloud.oracle.com/iaas/Content/GSG/Concepts/baremetalintro.htm
OCI Documentation: https://docs.cloud.oracle.com/iaas/Content/GSG/Concepts/baremetalintro.htm

Reason for PSL Inclusion
====

Customer-oci.com is for customer use when using the Oracle Cloud Infrastructure platform. This domain is used for customers generating DNS endpoints for hosting customer provided code. This includes the parent domain customer-oci.com. as well as three children where cookies should be prevented below: oci.customer-oci.com., ocp.customer-oci.com. and ocs.customer-oci.com..

DNS Verification via dig
=======

```
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.customer-oci.com @ns1.p68.dns.oraclecloud.net
_psl.customer-oci.com.	3600	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.oci.customer-oci.com @ns1.p68.dns.oraclecloud.net
_psl.oci.customer-oci.com. 3600	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.ocp.customer-oci.com @ns1.p68.dns.oraclecloud.net
_psl.ocp.customer-oci.com. 3600	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.ocs.customer-oci.com @ns1.p68.dns.oraclecloud.net
_psl.ocs.customer-oci.com. 3600	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
```
```
gdrake@gdrake-mbpr:~$ dig +noall +answer +recurse TXT _psl.customer-oci.com @8.8.8.8
_psl.customer-oci.com.	3599	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +recurse TXT _psl.oci.customer-oci.com @8.8.8.8
_psl.oci.customer-oci.com. 3599	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +recurse TXT _psl.ocp.customer-oci.com @8.8.8.8
_psl.ocp.customer-oci.com. 3599	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +recurse TXT _psl.ocs.customer-oci.com @8.8.8.8
_psl.ocs.customer-oci.com. 3599	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
```

make test
=========

Passes locally

### CODE REVIEW

**Comment by sleevi** [comment]
@greg-drake-oracle Typo there - `_pls` != `_psl`. Unfortunately, we can't just accept it as is, since the domain administrator may have blocklisted `_psl` via policy. If you can update and demonstrate the correct proof, we can continue.

**Comment by greg-drake-oracle** [comment]
Apologies, I have corrected the TXT record DNS names.

```
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.customer-oci.com @ns1.p68.dns.oraclecloud.net
_psl.customer-oci.com.	3600	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.oci.customer-oci.com @ns1.p68.dns.oraclecloud.net
_psl.oci.customer-oci.com. 3600	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.ocp.customer-oci.com @ns1.p68.dns.oraclecloud.net
_psl.ocp.customer-oci.com. 3600	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.ocs.customer-oci.com @ns1.p68.dns.oraclecloud.net
_psl.ocs.customer-oci.com. 3600	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
```
```
gdrake@gdrake-mbpr:~$ dig +noall +answer +recurse TXT _psl.customer-oci.com @8.8.8.8
_psl.customer-oci.com.	3599	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +recurse TXT _psl.oci.customer-oci.com @8.8.8.8
_psl.oci.customer-oci.com. 3599	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +recurse TXT _psl.ocp.customer-oci.com @8.8.8.8
_psl.ocp.customer-oci.com. 3599	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
gdrake@gdrake-mbpr:~$ dig +noall +answer +recurse TXT _psl.ocs.customer-oci.com @8.8.8.8
_psl.ocs.customer-oci.com. 3599	IN	TXT	"https://github.com/publicsuffix/list/pull/811"
```

**Comment by sleevi** [comment]
Thanks. Can you provide a few sample domains to help validate that the wildcard is the correct form?

If your domains are in the form `customer.oci.customer-oci.com` then the wildcard isn’t needed, but if they’re of the form `customer.region.oci.customer-oci.com`, then what you have is correct. Just wanting to make sure all the variations of domains are accounted for by these rules.

**Comment by greg-drake-oracle** [comment]
Hello, thank you for your explanation. While the DNS is public, I am sure they would not like me posting a real customer example. I have created an example customer instance using the naming pattern nx-instance.nx-service.us-phoenix-1.oci.customer-oci.com:

```
gdrake@gdrake-mbpr:~$ dig +noall +answer nx-instance.nx-service.us-phoenix-1.oci.customer-oci.com @ns1.p68.dns.oraclecloud.net
nx-instance.nx-service.us-phoenix-1.oci.customer-oci.com. 60 IN	A 192.0.2.0
gdrake@gdrake-mbpr:~$ dig +noall +answer nx-instance.nx-service.us-phoenix-1.oci.customer-oci.com @8.8.8.8
nx-instance.nx-service.us-phoenix-1.oci.customer-oci.com. 59 IN	A 192.0.2.0
```
Please let me know if you have any other questions and/or concerns.

**Comment by sleevi** [comment]
Apologies for the delay in this.

While I can appreciate customer sensitivity, as someone unfamiliar with what `customer-oci.com` is, and merely trying to evaluate if this PR is going to do the needful, it's still difficult for me to evaluate.

Normally, examples can provide clarity, such as:

Given the two domains:
* `bob.domain.example`
* `alice.domain.example`
`alice` and `bob` are controlled by different entities.

Or:
Domains are of the form:
* `customer1.region-a.domain.example`
* `customer2.region-a.domain.example`
* `customer3.region-b.domain.example`
where `customer1`, `customer2`, and `customer3` are all different entities, and `region-a` and `region-b` refer to different regions of hosting

Can help make sure things are correct.

The problem with your example is I have no idea from your single domain, `nx-instance.nx-service.us-phoenix-1.oci.customer-oci.com`, where the boundaries are. I can presume that `us-phoenix-1` likely represents a provider-defined region, but I have no idea whether the boundary is at `nx-service` (vs, say, `nx-service-2`, which may be a different entity), or whether you're also trying to represent a boundary at `nx-instance` vs `nx-instance2` (which isn't supported as described)

I similarly don't have examples for what domains at the `customer-oci.com` listing is meant, and whether that means direct registrations are allowed for `user-a.customer-oci.com` vs `user-b.customer-oci.com`. If such registrations all take the form of `[region].oc?.customer-oci.com`, then you don't need to add `customer-oci.com`, but without more details, I can't be sure this is correct.

**Comment by greg-drake-oracle** [comment]
Hello,

Thank you for the detailed follow-up and apologies for my delay on this.

The domain customer-oci.com will be used for customer services that need to host customer provided code for their services using oracle features. The design goal is to not allow any cookies to be stored at the parent domain customer-oci.com including by oracle.

The oci, ocp and ocs labels will be used by different organizations within oracle cloud. I was not asked to prevent cookies specifically at these DNS labels but will take your advice based on the below use.

Each of these organization labels will be separated into the regional labels. In each region a customer will set up their service, in our example this will be nx-service and as you described another customer may use nx-service2. Below this label they will have their service instances. The design goal as I understand it will be to allow customers to set cookies for their own services such as nx-service but not allow cookies to be set above their service at the regional level. The pattern for customer usage as you described will be $customer.[region].oc?.customer-oci.com.

Please let me know if that makes more sense for you. Would you advise to also include policy for the oci, ocp and ocs DNS labels?

Thank you

**Comment by sleevi** [comment]
Thanks! That's really helpful!

Based on your description, everything looks right-ish to achieve that. Each `[region].oc?` will be treated as a distinct eTLD, meaning each `$customer` will be treated as a separate entity.

The one gap here is that Oracle would be able to set cookies on `oc?.customer-oci.com`, and those would propagate to both users and regions (in some implementations). One way to address that, you'd likely need to add a `*.customer-oci.com` record as well, which would ensure that you couldn't set cookies on the `oc?.customer-oci.com` domains (because they'd be treated as eTLDs), and then the subsequent `*.oc?.customer-oci.com` entries would handle the regional separation.

Would you like me to go ahead and make those changes and merge? I'll hold off to make sure I got everything correct, but if that's the intent, I can make sure to make that happen :)

**Comment by greg-drake-oracle** [comment]
Hello, thank you for the analysis. That makes sense regarding the intermediate label policy for *.customer-oci.com. If you are able to apply the change and merge that would be great. Otherwise, I am happy to add a new commit if preferred.

**Pull request merged**
