### PR TITLE
Add mozilla-iot.org

### PR DESCRIPTION
**Pull request by benfrancis**
Mozilla offers free subdomains for Web of Things gateways in people's homes as part of an experimental "Project Things". See https://iot.mozilla.org

Each subdomain points at a different web server under a different user's control so cookies should not be shared across subdomains.

Please use email authentication if possible.

Thanks!

### CODE REVIEW

**Comment by sleevi** [comment]
Hi @benfrancis - It would definitely be better to use DNS-based authentication, in part because we want to ensure that owners are maintaining that record (e.g. in the event of domain transfer)

Is it possible to set that up? If not, can you explain why?

**Comment by benfrancis** [comment]
Hi @sleevi, yes that's possible, just slightly inconvenient.

Please bear with me while I discuss with our team.

Thanks

**Comment by benfrancis** [comment]
The TXT record should now be live for _psl.mozilla-iot.org

Please can you confirm?

**Comment by weppos** [comment]
@benfrancis thanks, I was able to validate it. However, as per https://github.com/publicsuffix/list/wiki/Guidelines I will have to kindly update the PR to keep the entries in order by company.

If you follow that order you will see there is already a Mozilla block. You can append your changes there:

```
+// Submitted by Ben Francis <bfrancis@mozilla.com>
+mozilla-iot.org
```

**Comment by benfrancis** [comment]
Ah, sorry about that. I added a new section for Mozilla Corporation in the correct place (technically this is a request from the Mozilla Corporation, not Mozilla Foundation).

**Pull request merged**
