### PR TITLE
Add novecore.site

### PR DESCRIPTION
**Pull request by Moritz30**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://staclar.com

Staclar provides a variety of services to digital music companies, record labels and independent artists.

Reason for PSL Inclusion
====

Under novecore.site, we will be offering web hosting for artist websites. Listing in the PSL is requested for security reasons.

DNS Verification via dig
=======

```
dig +short TXT _psl.novecore.site
"https://github.com/publicsuffix/list/pull/1331"
```

make test
=========

Works

### CODE REVIEW

**Comment by Moritz30** [comment]
DNS record added:
`dig +short TXT _psl.novecore.site
"https://github.com/publicsuffix/list/pull/1331"`

**Comment by dnsguru** [comment]
Hello @Moritz30 - The rationale is not as robust as our typical submission; can you please review the guidelines (link below) and look at this issue #1245 and ensure that the request is in compliance with the guidelines and does not seek to work around rate limits or otherwise touch upon the issue #1245

**Comment by Moritz30** [comment]
> Hello @Moritz30 - The rationale is not as robust as our typical submission; can you please review the guidelines (link below) and look at this issue #1245 and ensure that the request is in compliance with the guidelines and does not seek to work around rate limits or otherwise touch upon the issue #1245

Pardon the basic rationale; my team has reviewed the guidelines and we fully comply with the guidelines. Also, we specifically have reviewed the #1245 issue and our use case is entirely separate from this.

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Pull request merged**
