### PR TITLE
Adding Scalable storefront domains to PSL

### PR DESCRIPTION
**Pull request by jeremykerr-sp**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Websites: https://scalable.inc & https://www.chipchip.com/

My name is Jeremy Kerr <jeremy.kerr@scalable.inc>. I am a DevOps engineer representing Scalable.

Scalable builds physical and software infrastructure to help entrepreneurs compete against the giants in e-commerce today. We provide merchants with a platform to sell customized merchandise online, to run a successful business with low overhead.

Reason for PSL Inclusion
====

The following rationale is the same for all 4 domains:
  * `chipchipstore.com` (expires May 4, 2024)
  * `chipstores.com` (expires March 7, 2025)
  * `mychipchip.com` (expires May 3, 2024)
  * `onchipchip.com` (expires May 4, 2024)

1. Remove any up-front costs for new merchants, by giving them subdomains instead of requiring domain registration.

2. Cookie security between subdomains. Each subdomain is a different business and we want to keep them isolated from each other. We are hoping after browsers refresh the PSL, they'll use these inclusions to better isolate consumer privacy for visitors of multiple storefronts, to supplement our other security measures.

3. Enable merchants using our product to advertise on 3rd-party platforms like Facebook & Google. We have read through https://github.com/publicsuffix/list/issues/1245 and recognize the issues raised. We don't want to impose an additional burden, but wanted to be up-front that this is one of the reasons we're hoping for inclusion.

_We registered these domains with these purposes in-mind, PSL inclusion does not risk breaking any pre-existing functionality for us or for our customers._

An example of a current storefront is https://www.animalthreads.com/. Future storefronts on the free subdomain model will look like:
  * `<brand>.chipchipstore.com`
  * `<brand>.chipstores.com`
  * `<brand>.mychipchip.com`
  * `<brand>.onchipchip.com`

DNS Verification via dig
=======

```
dig +short TXT _psl.chipchipstore.com
"https://github.com/publicsuffix/list/pull/1312"
```

```
dig +short TXT _psl.chipstores.com
"https://github.com/publicsuffix/list/pull/1312"
```

```
dig +short TXT _psl.mychipchip.com
"https://github.com/publicsuffix/list/pull/1312"
```

```
dig +short TXT _psl.onchipchip.com
"https://github.com/publicsuffix/list/pull/1312"
```

make test
=========

I ran the tests.

### CODE REVIEW

**Comment by bedfordsean** [comment]
Thanks @jeremykerr-sp, checking in from the FB side with a few questions:

1. I note that you don't yet have any subdomains live on any of these requested domains. When do you anticipate you will? This helps us validate and ensure this ask is legitimate and truly representative of separate business entities
2. Do you still plan to support sites running their own separate domains, such as the animal threads example above? Behind the scenes is this a CNAME to your *chipchip domain, or totally separated?
3. Roughly how many subdomains and sites do you anticipate will opt for the free hosted subdomain vs buying their own domain? I understand you may not want to share this information publicly here, so we can find another way to get a steer on this if needed

**Comment by jeremykerr-sp** [comment]
Thanks for reviewing this request @bedfordsean, I really appreciate it. Let me know if you have any other questions, or if you'd like more details here:

>     1. I note that you don't yet have any subdomains live on any of these requested domains. When do you anticipate you will? This helps us validate and ensure this ask is legitimate and truly representative of separate business entities

That's a great question. We're aiming to have this working 2-3 weeks from now, though the actual launch date will come later. We're building some demo sites on the subdomain model that we can share, that we anticipate will be available by May 28th.

>     2. Do you still plan to support sites running their own separate domains, such as the animal threads example above? Behind the scenes is this a CNAME to your *chipchip domain, or totally separated?

Yes, we intend to continue supporting custom domains as well as subdomains. Behind the scenes, these point at shared network infrastructure, though merchants have a lot of control over how their site behaves and what kind of analytics they tie into.

>     3. Roughly how many subdomains and sites do you anticipate will opt for the free hosted subdomain vs buying their own domain? I understand you may not want to share this information publicly here, so we can find another way to get a steer on this if needed

This is difficult to estimate. We currently have ~10,000 custom domains, and we're aiming to double that in 2021. We think that removing the up-front investment will make it easier for new merchants to try our platform to see if it's the right fit for their needs.

**Comment by dnsguru** [comment]
I get we volunteers must seem all 'DMV' about things and wontfix happy at the moment,  but want to ensure that there is a good quality sieve in place as well as learnings / patterns for the #1245 issue.  There are likely quite a large number of websites that had put in PR which would have broken things due to their requests where the current pause has protected them.

There is ongoing dialog with Facebook towards updating the process, and they thank you for patience.

**Comment by n8schloss** [comment]
Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737  

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift. 

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
excellent @n8schloss - appreciate FB stepping up to remedy the thundering herd sent to the PSL for salvation without context.    closing this, reference this pr# should a new one be requested

**Pull request closed without merging**
