### PR TITLE
Add crowdrole.io

### PR DESCRIPTION
**Pull request by emanuelones**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website:  https://crowdrole.com

We are a self-marketing platform that gives small businesses with little to no marketing experience the opportunity to promote their services on Facebook at a fraction of the costs of hiring a marketer or contracting a marketing agency. We provide each small business with pre-made landing pages, ad templates and a lead management system.

We also offer our clients a free and unique subdomain that they can pick for their business. For example:
1. Joe has a small business called Joe The Gardener. He can pick [joethegardener.crowdrole.io](https://joethegardener.crowdrole.io)
2. Jane has a small business called Puppy Haircut Salon. She can pick [puppyhaircut.crowdrole.io](https://puppyhaircut.crowdrole.io) 

My name is Emanuel Ones and I'm a co-owner of Crowdrole. 

Reason for PSL Inclusion
====

1. We want to give more direct control to our users over their content. Each user can edit their landing page in accordance with their business requirements. 
2. We would like cookies to be isolated between each business's subdomain for increased security.
3. We want to allow our customers to set aggregated measurements in Facebook Events Manager for their Facebook pixels for events that come from their subdomain that they choose on our platform (in accordance with [Facebook's domain verification docs](https://developers.facebook.com/docs/sharing/domain-verification/)).

The referenced domain (crowdrole.io) has been registered until 07/05/2024. We also commit to maintaining more than 2 (two) years  on our domain's registration

DNS Verification via dig
=======

```
dig +short TXT _psl.crowdrole.io
"https://github.com/publicsuffix/list/pull/1322"
```

make test
=========

The test completed successfully.

### CODE REVIEW

**Comment by dnsguru** [comment]
Please see #1245 as to why this is currently wontfix.  FB are monitoring the PRs posted here (hopefully) and reviewing the PRs submitted.  They were to have updated the guidance on the domain validation page to qualify those sent to PSL for salvation.

Due to that guidance from FB being so basic it does not identify the potential breakage caused to the root domain or other collateral problems that requests might introduce, as well as the propogation challenges on those who integrate or use the PSL in static ways, the timing they do so, and the challenges with rolling back a PR with propogation.

Requests for a PSL entry should get carefully curated by the FB team and many are closing their requests once they realize they would have broken something.

Because of the volume of requests that seek to un-break their IOS<->FB stuff, and the challenges and consequences requestors can inadvertently cause themselves by a casual 'PSL will fix this' request, we have these requests pooling as wontfix until we have a better understanding of the patterns, hazards and where it is appropriate and safe to proceed.

We can leave the PR open vs closing it, but it will sit in that waiting queue

**Comment by emanuelones** [comment]
@dnsguru Thank you for taking time to review this PR! 

I've made an update to the "Reasons for PSL inclusion" to be more thorough. Should've mentioned that we're fully aware of the implications/repercussions of having this domain (crowdrole.io) on PSL - especially after going through #1245 - and I apologize for not doing so from the start. The referenced domain (crowdrole.io) is only going to be used to create subdomains for our clients, there won't be any 'shared' cookie or any other resource on the base domain (kind of following what Shopify did with myshopify.com). As for Facebook's love story with Apple I'm pretty sure that they'll come up with something else.  

Is there any chance of this PR moving forward without the (wontfix) label? Thank you!

**Comment by bedfordsean** [comment]
Hi @emanuelones I don't see any sites listed on Google for *.crowdrole.io. Is this a new business venture or something existing?

As per the FB guidance, we do not recommend new use cases to the PSL, only that existing use cases will work: https://www.facebook.com/business/help/126789292407737?id=1205376682832142

**Comment by emanuelones** [comment]
Hi @bedfordsean , we've generally avoided index mainly for two reasons: 
1. Each subdomain is displaying a landing page for a specific business and we want to keep traffic sources under control in order to optimize the results for our customers - therefore those landing pages are almost always reached through redirects. 
2. This domain (crowdrole.io) is only used by the newest version of our platform which was recently released to give our customers more control and options over their content - we are currently moving all of our customers to our new platform. 

We've been on the market for almost a year but we've mostly worked directly with clients. The platform itself is newer.

As for the FB guidance - thank you for sharing an updated version - we are aware of their policy regarding PSL and we are waiting for them to come with a fix for the aggregated measurement inconveniences. However we want to get our suffix on the PSL list for the first 2 (two) reasons  which are (in short) 1. giving more control to clients over their content and 2. increased security by not sharing cookies and avoiding CSRF attacks.

**Comment by bedfordsean** [comment]
Thanks for confirming on no search indexing @emanuelones 

Just thought I'd check as I would have thought businesses may want their own domains exposed for visibility! 

The guidance I linked above clarified FB's stance given that PSL is not a straightforward process and there are a number of caveats to how it works functionally.

If, given that guidance and positioning, you still wish to proceed, then it's worth bearing in mind the guidance here: https://github.com/publicsuffix/list/wiki/Guidelines and especially https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion

As @dnsguru mentions, we've had a number of issues where people are raising requests here in relation to attempting to resolve their FB issues (there is no "easy fix" today), without fully understanding the repercussions of being on the PSL.

FB will be standing up a new process in the next few days to assess all open pull requests here (and any future ones) related to wanting to be on the PSL, and if the reason for this request is related to FB, I'd suggest following that process once available.

**Comment by emanuelones** [comment]
@bedfordsean, first of all, thanks for sharing all this resources!
 
Yes, usually any business would like/want their own domain/s exposed for visibility but in our platform's case we have to have some sort of control over traffic sources in order to keep client's budget under control & optimize their results.

I've reread all the guidance resources provided above and, after careful reanalysis the answer is **yes** we still wish to proceed. 

We are **now** fully aware, and glad to hear, that FB will come up with a new process in the next few days to assess all open pull requests and we will hopefully be on their list (Hi FB! 😄).

And yet we still want to provide our customers with their own subdomain for their business in order to prevent data sharing between those subdomains and give them more control over their landing pages. Also I should mention that we do not require any functionality on the referenced domain (except for a small redirect when the domain is directly accessed).

**Comment by n8schloss** [comment]
Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737  

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift. 

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
thanks @n8schloss - appreciate FB stepping up to address what can be addressed on this matter - the PSL as salvation was not as utopian as some of the early guidance suggested. Closing this - please reference its PR# if a new one is opened so there is case history.

Take a look at #1337 on their comment as to why they submitted and subsequently removed their PR - they will have to deal with the impacts that were unexpected for a few months while various browsers etc propogate to using the updated PSL, and the whole thing could have been avoided had there been no request in the first place.

**Pull request closed without merging**
