### PR TITLE
Add nodum.io aPaas

### PR DESCRIPTION
**Pull request by WietseWind**
Reason: x-domain, browsers. Customers generate their own subdomains. Contact: hello@nodum.io

### CODE REVIEW

**Comment by sleevi** [comment]
As per the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), can you provide sample domains so we can help make sure the entries are correct?

**Comment by WietseWind** [comment]
@sleevi Of course, this is about [nodum.io](https://nodum.io) and [nodum.co](https://nodum.co)
Sample customer subdomains:
- https://cmsx.nodum.io/
- https://beemster.nodum.io/
- https://haha.nodum.wietse.com/
- https://b.nodum.co/

**Comment by sleevi** [comment]
Your examples seem to conflict with the PR.

That is, `cmsx.nodum.io` and `beemster.nodum.io` would be accomodated by a rule stating `nodum.io`. You would only need `*.nodum.io` if `a.cmsx.nodum.io` and `b.cmsx.nodum.io` were independently operated or needed separation.

You mentioned `nodum.wietse.com` as part of the examples, but that was not part of your pull request. Was that intentional?

Your pull request notes "nodum", except it appears the registered company is `Nodum B.V.` - is that correct?

**Comment by WietseWind** [comment]
@sleevi My bad @ the wietse.com domain, copy-paste error. Should have been:
https://haha.nodum.co/

BV = "Besloten Vennootschap" (like Limited for UK), it's the legal entity. So yeah, that's the company.

Do you want me to change the company name (to include the B.V. part) and remove the wildcards with a new commit?

**Comment by sleevi** [comment]
Yeah, the wildcards don't do what you want from your examples, and adding the B.V. is appropriate (much like the inclusion of "Inc" or "s.r.o" elsewhere)

**Comment by WietseWind** [comment]
@sleevi Thanks, appreciate it! I've fixed it and ^^ there's a new commit.

**Pull request merged**
