### PR TITLE
Remove scapp.io and applicationcloud.io from PSL

### PR DESCRIPTION
**Pull request by JamesClonk**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://developer.swisscom.com

We at Swisscom would like to remove the two entries scapp.io and applicationcloud.io for our Application Cloud (https://developer.swisscom.com) product.

Reason for PSL Removal
====

We do not want these entries anymore.

### CODE REVIEW

**Comment by dnsguru** [comment]
Undos #698 
Submitter not same on change 

In order for us to proceed with this change

- @MatthiasWinzeler please identify that this removal is appropriate to roll back your section, 

or alternatively, 

- @JamesClonk  Please validate this request via DNS technique with _psl txt records - this is to allow for the verification that the removal request is being performed with the knowledge of the admin of the affected string(s).

**Comment by MatthiasWinzeler** [comment]
@dnsguru This removal request is appropriate.

**Comment by JamesClonk** [comment]
@dnsguru The DNS values have been changed accordingly.
```
$ dig TXT _psl.scapp.io +short
"https://github.com/publicsuffix/list/pull/1186"
 
$ dig TXT _psl.applicationcloud.io +short
"https://github.com/publicsuffix/list/pull/1186"
```

@MatthiasWinzeler Thanks! :smile: :+1:

**Comment by dnsguru** [comment]
> @dnsguru This removal request is appropriate.

> @dnsguru The DNS entries have been changed accordingly.

Thank you @MatthiasWinzeler @JamesClonk - proceeding

**Review by dnsguru — APPROVED** [review]
- Repeat submitting party, editing same section
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

Approved rollback of #698

**Pull request merged**
