### PR TITLE
Add onepage.me

### PR DESCRIPTION
**Pull request by kuzmenko1256**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://onepage.io

My name is Arthur Kuzmenko, I am CTO of Onepage.
Onepage is a website building platform.

Reason for PSL Inclusion
====
We allow users who do not bring their own domain to host content using a subdomain on one of our domains, i.e. `domain1.onepage.me`. We would like to isolate cookies and also be able to use Let's Encrypt for our customer's subdomains.

DNS Verification via dig
=======
```
dig +short  TXT _psl.onepage.me
"https://github.com/publicsuffix/list/pull/1244"
```

make test
=========

I'm still trying to figure out what I need installed for the tests. I installed automake from brew, but I get the following output:

```
▶ make test                  
cd linter;                                \
          ./pslint_selftest.sh;                     \
          ./pslint.py ../public_suffix_list.dat;
-n test_NFKC: 
OK
-n test_allowedchars: 
OK
-n test_dots: 
OK
-n test_duplicate: 
OK
-n test_exception: 
OK
-n test_punycode: 
OK
-n test_section1: 
OK
-n test_section2: 
OK
-n test_section3: 
OK
-n test_section4: 
OK
-n test_spaces: 
OK
-n test_wildcard: 
OK
test -d libpsl || git clone --depth=1 https://github.com/rockdaboot/libpsl;   \
          cd libpsl;                                                                    \
          git pull;                                                                     \
          echo "EXTRA_DIST =" >  gtk-doc.make;                                          \
          echo "CLEANFILES =" >> gtk-doc.make;                                          \
          autoreconf --install --force --symlink;
Already up to date.
Can't exec "autopoint": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
make: *** [libpsl-config] Error 1

```

### CODE REVIEW

**Review by dnsguru — CHANGES_REQUESTED** [review]
Please locate this lower in the file, alphabetically.

(I do notice that one.com's entry is in the wrong place and that is a separate matter for us to address with that party.)

**Comment by dnsguru** [comment]
This is stalled until the PR is revised to move the entry lower in the private section @kuzmenko1256

**Comment by kuzmenko1256** [comment]
> Please locate this lower in the file, alphabetically.

Fixed

**Comment by dnsguru** [comment]
Please see the (acceptance/validation)[https://github.com/publicsuffix/list/wiki/Guidelines#validation-and-non-acceptance-factors] section of the Wiki

It has a link for Let's Encrypt requests if this is the objective of the PR.  There is a bias against use of the PSL as a workaround for third party limits.  If there are other objectives, please expand the rationale.

**Comment by kuzmenko1256** [comment]
We decided to abandon Let's Encrypt.
We would like to isolate cookies and also be able to domain verification in the FB for our customer's subdomains.

**Comment by bedfordsean** [comment]
Checking in on the FB side since FB is now mentioned for the first time. 

Note that the current Facebook guidance is to *not* register for the public suffix list as per our help center article here: https://www.facebook.com/business/help/126789292407737?id=1205376682832142

> Our current efforts are designed to support **pre-existing** Public Suffix List domain registrations or eTLDs. This support is in line with Apple's recent private click measurement update. There are other technical implications if a domain is registered as a Public Suffix that a business should consider (for example, the domain that is registered on the Public Suffix List cannot have its own cookies) and as such, we don't recommend that clients register their domains on the Public Suffix List specifically for Facebook event configuration. 

What is your actual motivation for making this request? Facebook advertising, Lets Encrypt SSL requirements, or cookie isolation?

**Comment by bedfordsean** [comment]
Thanks @kuzmenko1256 

I think the only outstanding question at this point is one of volume... As you'll have seen on other PSL requests there is a trade off that the maintainers here have to make between supporting legitimate sites and keeping the list to a manageable overall size.

I've done a Google search and can see ~1000 sites using the *.onepage.me structure. I don't know if you have more that just aren't crawled?

I'm happy that this is a reasonable use case for PSL consideration given the separate businesses present on each onepage.me subdomain. Over to @dnsguru to discuss next steps based on the conversations/clarifications above!

**Comment by dnsguru** [comment]
@kuzmenko1256 After Facebook updates their guidance on Facebook Pixel and Domain Validation, there will be a review to determine which of the PR should proceed.  We still await those updates after 60 days, and then our volunteers will take the time to review the situation.

FB's most recent guidance is: 
> Our current efforts are designed to support clients with pre-existing Public Suffix List domain registrations or eTLDs. This support is in line with Apple's recent private click measurement update. There are other technical implications if a domain is registered as a Public Suffix that a business should consider (for example, the domain that is registered on the Public Suffix List cannot have its own cookies) and as such, **we do not recommend that clients register their domains on the Public Suffix List specifically for Facebook event configuration**.

They have yet to make those updates to their domain validation and other guidance, which is causing a pileup here with the project volunteer maintainers.

**Comment by kuzmenko1256** [comment]
@dnsguru Ok, we will wait for approval of this PR

**Comment by dnsguru** [comment]
Thank you for moving location in file to appropriate area.  Removing invalid label

Still wontfix due to #1245 and ongoing discussions

**Comment by n8schloss** [comment]
Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737  

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift. 

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
excellent @n8schloss - appreciate FB stepping up to remedy the thundering herd sent to the PSL for salvation without context.    closing this, reference this pr# should a new one be requested

**Pull request closed without merging**
