### PR TITLE
Add github dev domains

### PR DESCRIPTION
**Pull request by dmilburn**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: github.com (though this is for github.dev and githubpreview.dev)

I'm a software engineer at GitHub working on the new Codespaces product

Reason for PSL Inclusion
====

We want to restrict the ability to create cookies that span subdomains of github.dev and githubpreview.dev 

Both of these domains aren't set to expire until 2023:
```
$ whois github.dev|grep -i expir
Registry Expiry Date: 2023-01-16T16:27:37Z
$ whois githubpreview.dev|grep -i expir
Registry Expiry Date: 2022-12-09T21:03:15Z
```

DNS Verification via dig
=======

`dig +short TXT _psl.github.dev` and `dig +short TXT _psl.githubpreview.dev` both point to this URL

make test
=========

I wasn't able to get the tests to run locally but they do pass in CI. Let me know if this isn't sufficient!

### CODE REVIEW

**Comment by sleevi** [comment]
@ptoomey3

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

(thank you for correcting sort order)

**Comment by dnsguru** [comment]
@sleevi do we still want @ptoomey3 input on this?

**Comment by sleevi** [comment]
> @sleevi do we still want @ptoomey3 input on this?

If it checks out, I think we’re good, just wanted to make sure the previous GitHub security contact knew as well.

**Comment by ptoomey3** [comment]
We've discussed this internally already. I'll look at the specific PR tomorrow. Thanks for the heads up.

**Comment by dnsguru** [comment]
@ptoomey3 We can keep this lightweight - it just adds two domains github.dev and githubpreview.dev into your PSL domains - if that's a "go" (here is fine), I can go ahead and merge - just reply with a 'go ahead'

**Review by ptoomey3 — APPROVED** [review]
👍

**Pull request merged**
