### PR TITLE
Update comments for `.it`, `.jp`, `.se`, `.xn--fiqs8s`, `.xn--fiqz9s`

### PR DESCRIPTION
**Pull request by groundcat**
This PR is created to update comments for `.it`, `.jp`, `.se`, `.cn` to fix broken links and note some registry confirmation responses to improve documentation.

### CODE REVIEW

**Comment by simon-friedberger** [comment]
> // 2024-11-22: JPRS confirmed that since regional JP domain names are no longer 
> // accepting new registrations, any registered domain names listed under FQDNs 
> // are confirmed to have been fully discontinued will be removed from the PSL.

I am not sure what you are saying here. Could you please rephrase? 😅

**Comment by wdhdev** [comment]
I agree, the wording is a bit confusing. Did you mean something like `Regional .jp domain names no longer accept registrations, however we are waiting until all domains under them are expired, before we can remove them from the PSL.`?

**Comment by groundcat** [comment]
Sorry, it was confusing since I had translated it literally. From what I understand, they were trying to say that regional .jp suffixes no longer accept new registrations. Once all existing registrations expire (marking full discontinuation), these suffixes will be removed from the PSL.

**Comment by groundcat** [comment]
> Could you please rephrase?

Done :)

**Pull request merged**
