### PR TITLE
Added developerhub.io

### PR DESCRIPTION
**Pull request by zaiddabaeen**

### CODE REVIEW

**Comment by frju365** [comment]
Pls, check the guidelines before opening an empty PR. https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change

PR like that won't be reviewed in the future. It wastes maintainers' time.

**Comment by zaiddabaeen** [comment]
My true apologies, I missed that part.

DeveloperHub.io provides tools to create beautiful documentation that can be hosted under developerhub.io domain.

Subdomains can only be one-level subdomains such as company1.developerhub.io, xyz.developerhub.io and so on. It cannot be xyz.company.developerhub.io.

The change is:

```
// DeveloperHub.io : https://developerhub.io/
// Submitted by Zaid Daba'een <hello@developerhub.io>
developerhub.io
```

You can verify the request by DNS TXT Record.

**Comment by frju365** [comment]
It's well better. Now, we need a reason for this change. Security... We can guess what is it, but can you be more precise. about this reason ?

**Comment by zaiddabaeen** [comment]
I would like to be able to integrate with certain third party applications, which rely on your list for setting the proper cookie settings.

**Comment by sleevi** [comment]
Can you be more specific in these third party applications? This would help ensure we’re aware of how the PSL is being used.

**Comment by zaiddabaeen** [comment]
Intercom integration to be prevented on *.developerhub.io and all such other integrations from supercookies.

**Comment by zaiddabaeen** [comment]
If not then can you please disregard this commit. Thanks.

**Comment by weppos** [comment]
> I am sorry if I misunderstood, but would I also not be able to set cookies myself on developerhub.io domain? Or it is just third party integrations that wouldn't be able to?

Nobody using a client (including browsers) who is based on the PSL will be able to set cookie there. Including yourself.

**Comment by zaiddabaeen** [comment]
I understand. Please disregard this commit.

**Comment by zaiddabaeen** [comment]
Sorry for the wasted time

**Comment by weppos** [comment]
No worries.

**Pull request closed without merging**
