### PR TITLE
Add barsy.ro to Lukanet Ltd private domains

### PR DESCRIPTION
**Pull request by lukavia**
Description of Organization
====

Organization Website: https://lukanet.com
Product Website: https://barsy.bg

Lukanet Ltd is the owner and developer of a software for managing Bar, Restourants and other Businesses called [Barsy](https://barsy.bg). We already have a number of domains included in the list for the same reasons we want to include this new one.

Reason for PSL Inclusion
====
For each installation our clients get a subdomain so they can access their system via web without having to incure additional fees for domains, static IP address or dyndns as this is handled by our system. Since each installation belongs to a separated legal entity and deals with that entity valuable finantial information, security is top cencern for us and our clients. It has proven that having the subdomains recongnized by the browsers as separete domains and not share cookies or other vital information is a good working practise. We've number of included domains already in the list like: barsy.bg, barsy.uk, etc. 
We are now planing an expantion in Romania and would be great if we can provide the same level of security as to our existing customers. 

DNS Verification via dig
=======
```
$ dig +short TXT _psl.barsy.ro
"https://github.com/publicsuffix/list/pull/1402"
```
make test
=========
We have run the test and all the tests have passed

__We affirms the following:__ 
  * [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place
  * [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting
  * [X] Yes, We understand.  We could break our organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.

### CODE REVIEW

**Comment by dnsguru** [comment]
Related #439 #596 #732

**Comment by dnsguru** [comment]
Also related #652

**Comment by dnsguru** [comment]
@lukavia Anton the requirements for the PSL are agreed to above state that "Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place".

It actually applies to the whole section, and it is done to ensure there is registration term for **at least 2 years** to indicate the domains in the section do not get deleted in DNS but remain here in the file for us volunteers to have to clean up. 

In a check of the names in the barsy section, barsy.org does hold a _psl txt record, but expires on October 27th 2021 - which is under 2 months, and well below the requirements.  Rather than pull the names that didn't have appropriate durations from the PSL or cancelling this PR, could there be a review of the registration terms and removal of names that are not going to qualify?

**Comment by lukavia** [comment]
@dnsguru Thank you very much for taking the time to review our pull request. And thank you for your wonderful work, time and effort maintaing the Publix Suffix List. 

I'm sorry for my confusion I misunderstood that the 2y rule applies for adding new domains and not for already included ones. We have now renewed all the domains in the Lukanet Private section to have at least 2 years in their registration term. The only exception is barsy.de where the registrar doesn't allow us to place a second renew order at the moment, but there is still a year and a half in that term. 

As you can see our domains are in the list for more than 5 years and we have never released or are planning to release a domain in the list and let it expire. I can assure you that if such an unlikely event ever happens I would make effords to push another pull request removing the expired domains. 

I would also like to offer my time and services to help you maintain the list. If there is a task or any other way that I can be of assistance, please let me know.

**Comment by lukavia** [comment]
Here is a little bash command and the result that show the domains expiration date where possible for you convenience:
```
$ for f in barsy.bg barsy.co.uk barsyonline.co.uk barsycenter.com barsyonline.com barsy.club barsy.de barsy.eu barsy.in barsy.info barsy.io barsy.me barsy.menu barsy.mobi barsy.net barsy.online barsy.org barsy.pro barsy.pub barsy.ro barsy.shop barsy.site barsy.support barsy.uk; do echo -n "$f ";whois $f | grep -v 'Registered until' | egrep -i "(Expires|Expiry)" || echo ""; done
barsy.bg 
barsy.co.uk         Expiry date:  13-Dec-2023
barsyonline.co.uk         Expiry date:  13-Dec-2023
barsycenter.com    Registry Expiry Date: 2024-05-14T07:55:00Z
barsyonline.com    Registry Expiry Date: 2024-05-14T07:55:00Z
barsy.club Registry Expiry Date: 2024-02-19T23:59:59Z
barsy.de 
barsy.eu 
barsy.in Registry Expiry Date: 2023-10-20T15:19:21Z
barsy.info Registry Expiry Date: 2023-10-20T15:19:21Z
barsy.io Registry Expiry Date: 2024-02-20T18:28:58Z
barsy.me Registry Expiry Date: 2023-10-20T15:19:21Z
barsy.menu Registry Expiry Date: 2024-02-02T13:19:55Z
barsy.mobi Registry Expiry Date: 2023-10-20T15:27:30Z
barsy.net    Registry Expiry Date: 2024-10-27T09:39:58Z
barsy.online Registry Expiry Date: 2024-02-20T23:59:59.0Z
barsy.org Registry Expiry Date: 2023-10-27T09:39:58Z
barsy.pro Registry Expiry Date: 2023-10-20T15:19:21Z
barsy.pub Registry Expiry Date: 2024-02-02T13:19:55Z
barsy.ro   Expires On: 2024-08-23
barsy.shop Registry Expiry Date: 2023-12-13T23:59:59.0Z
barsy.site Registry Expiry Date: 2024-02-20T23:59:59.0Z
barsy.support Registry Expiry Date: 2023-10-20T15:39:23Z
barsy.uk         Expiry date:  13-Dec-2023

```

**Comment by dnsguru** [comment]
Thank you for offer of help - will keep in mind - watch for @lukavia on PRs

**Comment by lukavia** [comment]
Will do. Thank you.

**Pull request merged**
