### PR TITLE
Remove unused suffix (123sait.ru)

### PR DESCRIPTION
**Pull request by jacobbunk**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
One.com - a large hosting company that mainly operations in Northern Europe, recently acquired SimpleSite a web hosting company focused on providing web hosting based on their simple site builder. One.com is part of group.one that also operates the .one TLD as well as several other hosting brands that can be found at the https://group.one website.

I, the submitter, Jacob Bunk Nielsen work in the engineering team of one.com.

Organization Website: https://www.one.com/

Reason for PSL Inclusion
====
Removing as this no longer have to be considered a public suffix. It was submitted by me as part of https://github.com/publicsuffix/list/pull/1623

Number of users this request is being made to serve: none

DNS Verification via dig
=======

```
$ dig +short txt _psl.123sait.ru @1.1.1.1
"https://github.com/publicsuffix/list/pull/1844"
```

Results of Syntax Checker (`make test`)
=========

Ended badly, but I get a similar result on the master branch and can't imagine removing a domain from the list would cause this:
``` 
configure.ac:1: warning: file `version.txt' included several times
configure.ac:4: warning: file `version.txt' included several times
aclocal.m4:489: AM_INIT_AUTOMAKE is expanded from...
configure.ac:4: the top level
configure.ac:383: warning: file `version.txt' included several times
configure.ac:67: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:92: error: possibly undefined macro: AC_LINK_IFELSE
configure.ac:93: error: possibly undefined macro: AC_LANG_PROGRAM
configure.ac:196: error: possibly undefined macro: AC_SEARCH_LIBS
configure.ac:225: error: possibly undefined macro: AC_MSG_CHECKING
configure.ac:230: error: possibly undefined macro: AC_MSG_RESULT
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
make: *** [Makefile:18: libpsl-config] Error 1
```

### CODE REVIEW

**Comment by jacobbunk** [comment]
Clicked the last 3 checkboxes even though they are irrelevant in the context of PSL removal.

**Comment by jacobbunk** [comment]
@dnsguru - is more work required to merge this one?

It comes from a company acquisition where subdomains under this domain were sold to individual customers (without proper inclusion in PSL), but after we merged the companies and cleaned up the data this one turned out to no longer be needed.

**Comment by simon-friedberger** [comment]
Can you please add the DNS verification entry?

**Comment by jacobbunk** [comment]
> Can you please add the DNS verification entry?

Done, also updated description with the validation query.

**Pull request merged**
