### PR TITLE
Add en-root.fr domain

### PR DESCRIPTION
**Pull request by eraviart**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://en-root.org/

I am an individual, initiator of an informal non-profit organization called _En root‽_, whose aim is to provide tools for people working on _digital democracy_ and the French Parliament. Currently our collective works on storing each French laws and bills in Git repositories.

We provide some infrastructure to our members (forum, chat, etc) and we are currently adding a new service, a GitLab-based forge https://git.en-root.org.

Reason for PSL Inclusion
====

Our GitLab forge provides a GitLab Pages module using the en-root.fr domain. And he [GitLab Pages documentation](https://docs.gitlab.com/12.4/ee/administration/pages/#add-the-domain-to-the-public-suffix-list) states that we should add en-root.fr to the Public Suffix List...

DNS Verification via dig
=======

```bash
dig +short TXT _psl.en-root.fr
"https://github.com/publicsuffix/list/pull/910"
```

make test
=========

Test ran successfully:
```bash
make test
[...]
============================================================================
Testsuite summary for libpsl 0.21.0
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by sleevi** [comment]
Are you sure you intend to add your organization page? And not `git.en-root.fr`? Adding your organization page can cause all sorts of issues, especially with navigation and authentication.

Can you provide example domains that are registerable? For example, should `www.en-root.fr` be treated distinct from `login.en-root.fr`? Currently, they're treated the same, this would make them (and any other first-level) subdomains distinct, but still leave every subdomain of `git.en-root.fr` able to interfere with eachother.

**Comment by eraviart** [comment]
> Are you sure you intend to add your organization page? And not git.en-root.fr?

Our GitLab repository is git.en-root.ORG, not git.en-root.FR.

The en-root.fr TLD is reserved for the GitLab pages of git.en-root.org.

There won't be any subdomain of git.en-root.fr.

> Can you provide example domains that are registerable?

For example:
* the GitLab group https://git.en-root.org/tricoteuses can register domain tricoteuses.en-root.fr for its GitLab pages
* the GitLab user https://git.en-root.org/eraviart can register domain eraviart.en-root.fr for its GitLab pages
* and so on.

**Comment by sleevi** [comment]
Ah! Thanks for clarifying, and apologies for misreading :)

**Comment by groundcat** [comment]
Hello @eraviart do you still need `en-root.fr` to be listed in the PSL? It has been expired for months, since 2025-10-30T20:19:52Z

**Comment by eraviart** [comment]
Noits is no more needed. Thanks

**Pull request merged**
