### PR TITLE
Add frontgatetickets.com

### PR DESCRIPTION
**Pull request by bpaulsen-fgt**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://www.frontgatetickets.com

I am Ben Paulsen, Vice President of Product Development at Front Gate Tickets.  I oversee both Front Gate's engineering and product teams.

Front Gate Tickets is a full service ticketing solutions platform for music festival promoters.  It is a division of Ticketmaster.  We maintain 100+ white label ecommerce / ticketing sites for our clients.

Some examples of our sites:

https://stubbs.frontgatetickets.com/
https://bonnaroo.frontgatetickets.com/
https://outsidelands.frontgatetickets.com/
https://edclasvegas.frontgatetickets.com/

Reason for PSL Inclusion
====

In full transparency, we were directed toward adding ourselves to the PSL as a result of the newly imposed rules / limitations of IOS / Facebook (#1245).  That said, I believe our domain is appropriate for the list as each one of our ticketing sites is a unique brand (for unique clients) and we would certainly benefit from the added protection afforded by limiting cookie sharing across these sites.

DNS Verification via dig
=======

```
dig +short TXT _psl.frontgatetickets.com
"https://github.com/publicsuffix/list/pull/1315"
```

make test
=========

Tests have been run.

### CODE REVIEW

**Comment by bpaulsen-fgt** [comment]
We were directed here as a result of communications with staff at Facebook as well as via the information given at this url: https://www.facebook.com/business/help/331612538028890?id=42863664817020

Our use case is that we facilitate unique Facebook marketing efforts for our clients and the new limitations make that nearly impossible.  Facebook's staff pointed out that one option was inclusion on the PSL, but they did not explicitly recommend it.  They stated the decision was on us to consider whether our business and technical structure fit.

We carefully weighed the decision whether to submit for inclusion for nearly a month as our engineering staff looked into the risks (blocking frontgatetickets.com cookies) and well as the appropriateness of the request.  Ultimately, we decided that our model does feel appropriate for inclusion as our ticketing sites are unique from one another and effectively function as contained experiences (for differing clients / businesses).  So, outside of providing value for the FB marketing purposes, we see added value in the security afforded by PSL inclusion.

**Comment by bedfordsean** [comment]
Thanks @bpaulsen-fgt 

It sounds like you've done your research already but just wanted to point out that FB issued updated guidance here: https://www.facebook.com/business/help/126789292407737?id=1205376682832142. Please can you read this as well (especially the callouts of the implications of being on the PSL) and confirm for us once more that you do indeed wish to proceed.

**Comment by bpaulsen-fgt** [comment]
Thank you for the additional guidance @bedfordsean.  We've reviewed it and still feel confident that our inclusion is the right choice for us at this time.  We recognize that this will stop cross subdomain cookie sharing, but in reviewing both our white label e-commerce sites as well as other sites hosted under the frontgatetickets.com domain / suffix (such as our "www" corporate site), we have identified no practical reason for needing this behavior.  Rather we continue to see this as a value add for our sites.

**Comment by bedfordsean** [comment]
Thanks for confirming @bpaulsen-fgt 

@dnsguru, passing this one to you for review

**Comment by n8schloss** [comment]
Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737  

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift. 

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
excellent @n8schloss closing this, reference this pr# should a new one be requested

**Pull request closed without merging**
