### PR TITLE
Add Drobo Dynamic DNS service

### PR DESCRIPTION
**Pull request by ricardopadilha**
I'm adding the mydrobo.com domain that belongs to Drobo.

Please feel free to contact either me (rpadilha at drobo.com) or the CTO (rod at drobo.com) for confirmation.

### CODE REVIEW

**Comment by ricardopadilha** [comment]
Additional ownership information: although the domain does not currently have email setup, the admin and tech contacts are from drobo.com. See http://whois.domaintools.com/mydrobo.com for more information.

**Comment by weppos** [comment]
I was able to validate the authenticity of the request via email, and the connection between mydrobo.com and drobo.com using the whois.

```
Admin Name: Harvey, Greg
Admin Organization: Drobo, Inc.
Admin Street: 2540 Mission College Blvd
Admin City: Santa Clara
Admin State/Province: CA
Admin Postal Code: 95054
Admin Country: US
Admin Phone: +1.4084544200
Admin Phone Ext:
Admin Fax:
Admin Fax Ext:
Admin Email: droboit@drobo.com
```

/cc @gerv

**Comment by groundcat** [comment]
Hi @ricardopadilha do you still need this entry? Domain `MYDROBO.COM` has expired for over a month.

```
   Domain Name: MYDROBO.COM
   Registry Domain ID: 1070140860_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.networksolutions.com
   Registrar URL: http://networksolutions.com
   Updated Date: 2025-08-18T08:41:23Z
   Creation Date: 2007-07-06T22:13:11Z
   Registry Expiry Date: 2025-07-06T22:13:11Z
   Registrar: Network Solutions, LLC
   Registrar IANA ID: 2
   Registrar Abuse Contact Email: domain.operations@web.com
   Registrar Abuse Contact Phone: +1.8777228662
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Domain Status: redemptionPeriod https://icann.org/epp#redemptionPeriod
   Name Server: NS1.PENDINGRENEWALDELETION.COM
   Name Server: NS2.PENDINGRENEWALDELETION.COM
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2025-08-18T21:23:01Z <<<
```

**Comment by groundcat** [comment]
Hi @ricardopadilha do you still need `mydrobo.com` to be listed in the PSL? It has expired for over a month. (Registry Expiry Date: 2025-07-06T22:13:11Z)

**Comment by ricardopadilha** [comment]
Hi, sorry for the delay. Given that the company went under, yes, please feel free to remove the domain.

**Pull request merged**
