### PR TITLE
add mittwald product domains

### PR DESCRIPTION
**Pull request by ins0**
# Public Suffix List (PSL) Submission

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (`make test`)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the `_psl` TXT record in place in the respective zone(s).

__Submitter affirms the following:__

* [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
        - this pr will not aim to workaround any rate limitations

* [x] This request was _not_ submitted with the objective of working around other third-party limits.

* [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, and responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

* [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms to them.
* [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting.

---

For PRIVATE section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding.

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

* [x] *Yes, I understand*. I could break my organization's website cookies and cause other issues, and the rollback timing is acceptable. *Proceed anyways*.
---

## Description of Organization

**Organization Website:**
https://www.mittwald.de

Mittwald.de is a web hosting company in Germany and provides a wide range of hosting solutions
and domain registration services. 

We're providing tools that support efficient website management and development workflows
for our customers, this requires various pre-configured subdomains (mittwald named and whitelabel domains)
for easy access and configuration of our products without the need for our customers to purchase a domain first.

My name is Marco Rieger, and I work as a Software Engineer here at mittwald and acting on behalf of the Security team of mittwald which I'm also part of. 

## Reason for PSL Inclusion

**Examples for simplification only based on `webspaceconfig.de`**

Customers will be provided with default subdomains for their purchased products. This follows the pattern `p[id].webspaceconfig.de` additionally customers will be provided with custom subdomains based on their
installed managed applications eg. `[appId].p[id].webspaceconfig.de`.

By being included in the PSL, mittwald ensures that cookies are correctly scoped to their domains, preventing potential security risks such as cross-domain cookie sharing.

**Number of users this request is being made to serve:** 
- The affected domains listed in this PR will affect approximately ~300k customers instances.

## DNS Verification

```
sh-3.2$ dig +short TXT _psl.mydbserver.com 
"https://github.com/publicsuffix/list/pull/2171"
```
```
sh-3.2$ dig +short TXT _psl.webspaceconfig.de 
"https://github.com/publicsuffix/list/pull/2171"
```
```
sh-3.2$ dig +short TXT _psl.mittwald.info
"https://github.com/publicsuffix/list/pull/2171"
```
```
sh-3.2$ dig +short TXT _psl.mittwaldserver.info
"https://github.com/publicsuffix/list/pull/2171"
```
```
sh-3.2$ dig +short TXT _psl.typo3server.info
"https://github.com/publicsuffix/list/pull/2171"
```
```
sh-3.2$ dig +short TXT _psl.project.space
"https://github.com/publicsuffix/list/pull/2171"
```
## Results of Syntax Checker (`make test`)

```
Making clean in po
Making clean in include
Making clean in src
rm -f ./so_locations
Making clean in tools
 rm -f psl
Making clean in fuzz
 rm -f libpsl_icu_fuzzer libpsl_icu_load_fuzzer libpsl_icu_load_dafsa_fuzzer
Making clean in tests
 rm -f test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain
Making clean in msvc
Making check in po
Making check in include
Making check in src
  CC       libpsl_la-psl.lo
  CC       libpsl_la-lookup_string_in_fixed_set.lo
  CCLD     libpsl.la
Making check in tools
  CC       psl.o
  CCLD     psl
Making check in fuzz
  CC       libpsl_fuzzer.o
  CC       main.o
  CC       libpsl_load_dafsa_fuzzer.o
  CC       libpsl_load_fuzzer.o
  CCLD     libpsl_icu_fuzzer
  CCLD     libpsl_icu_load_fuzzer
  CCLD     libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       common.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-is-public-builtin
  CCLD     test-registrable-domain
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-all
PASS: test-is-public-builtin
PASS: test-registrable-domain
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by wdhdev** [comment]
* [ ] Expiration (Note: Must STAY >2y at all times)
  * [ ] mydbserver.com expires 2025-02-13
  * [ ] ⚠️ webspaceconfig.de expiry is not reported by registry
  * [ ] mittwald.info expires 2024-10-24
  * [ ] mittwaldserver.info expires 2025-07-10
  * [ ] typo3server.info expires 2025-08-18
  * [ ] project.space expires 2024-10-26
* [x] DNS _psl entries (Note: Must STAY in place)
  * [x] `_psl.mydbserver.com`
  * [x] `_psl.webspaceconfig.de`
  * [x] `_psl.mittwald.info`
  * [x] `_psl.mittwaldserver.info`
  * [x] `_psl.typo3server.info`
  * [x] `_psl.project.space`
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description
* [x] Non-personal email address

---

Notes:
* Please tell us the expiry date of `webspaceconfig.de` as it is not reported by the .de registry, please also ensure it is renewed for >2y, assuming the .de registry supports that.
* All of the other domains that do report expiry dates are <2y expiry, please renew them for >2y.

**Comment by ins0** [comment]
@wdhdev were renewed the domains, please note that `.de` tld don't have this option (https://kb.centralnicreseller.com/domains/tlds/de) thus the reason why no expiration date is reported.

**Comment by wdhdev** [comment]
> @wdhdev were renewed the domains, please note that .de tld don't have this option ([kb.centralnicreseller.com/domains/tlds/de](https://kb.centralnicreseller.com/domains/tlds/de)) thus the reason why no expiration date is reported.

All good, I've excluded that domain from that requirement. All of the other domains seem to be renewed >2y, so this PR is ready to be merged.

> Is there a difference when excluding the asterik in the domains?

If you have an entry without an asterisk, for example `mydomain.com`, `mydomain.com` is normally treated as a TLD (like `.com`, `.net`, etc.), so `subdomain.mydomain.com` would become almost as if it was a "root" domain name. However if you have an asterisk in your entry like `*.mydomain.com`, subdomains at the 3rd level (e.g. `subdomain.mydomain.com`, `othersub.mydomain.com`) become treated as TLDs, so a subdomain at the 4th level (e.g. `test.example.mydomain.com`) is then treated as if it were a "root" domain.

My advice is if you are only issuing subdomains at the 3rd level (e.g. `1234asdf.mydbserver.com`), remove the asterisk as then `1234asdf.mydbserver.com` would be treated as a TLD, instead of it's own domain. If you are issuing subdomains at the 4th level for users (e.g. `user1.us.mydbserver.com`, `user2.uk.mydbserver.com`) and not at the 3rd level, then keep the asterisk.

**Comment by ins0** [comment]
Ok looks good then and we're ready to go. Thanks @wdhdev @groundcat

**Comment by wdhdev** [comment]
@ins0 To confirm, you no longer want wildcard entries?

**Comment by ins0** [comment]
@wdhdev no since we're creating subdomains at the third level `p123.webspaceconfig.de` and down to the 4th `appName.p123.webspaceconfig.de` like u suggests the version without the wildcard suits better

**Comment by simon-friedberger** [comment]
To be clear, without the wildcard, if you have two version of an app running at 
* `appName_v1.p123.webspaceconfig.de` and 
* `appName_v2.p123.webspaceconfig.de` 
 
the public suffix will be `webspaceconfig.de` and the eTLD+1 will be `p123.webspaceconfig.de` and both of those apps will see the same cookies and that might break things.

Please confirm that you have thought long and hard about what you want to add.

**Comment by ins0** [comment]
@simon-friedberger thanks for the feedback - now i'm a bit confused - so with the wildcard `*.webspaceconfig.de` every subdomain would treated separated? eg. `foo.webspaceconfig.de`, `foo.bar.webspaceconfig.de`, `foo.bar.baz.webspaceconfig.de` ?

**Comment by simon-friedberger** [comment]
This is supposed to be documented at https://github.com/publicsuffix/list/wiki/Format

(If you have any suggestions about what we could add to the wiki to make this clearer, please let me know!)

To answer your question, no, the wildcard just means "there could be any domain here".
So, for example those could be customers with multiple apps or pages
`app1.customer1.webspaceconfig.de`
`app2.customer1.webspaceconfig.de`
`app3.customer1.webspaceconfig.de`
or it could be regions
`customer1.de.webspaceconfig.de`
`customer2.de.webspaceconfig.de`
`customer3.fi.webspaceconfig.de`

So for `*.webspaceconfig.de` every `something.webspaceconfig.de` domain would be a public suffix and anything under that like 
`foo.something.webspaceconfig.de` and `bar.something.webspaceconfig.de` would be separate sites.

But `main.foo.something.webspaceconfig.de` and `contact.foo.something.webspaceconfig.de` would still be the same site and would share cookies.

Conversely, if you only add `webspaceconfig.de` and look at the second example above, then multiple customers in the same region would share cookies which is probably not what you want.

Does this help: https://developer.mozilla.org/en-US/docs/Glossary/eTLD ?

**Comment by ins0** [comment]
@simon-friedberger thanks the eTld link was a great ressource especially the `eTLD+1` term to clear things up. We discussed internally and have thought long and hard about to not include the wildcard asterisk in the first stage of being included in the psl list.

**Pull request merged**
