### PR TITLE
Add the new subdomains for TLD .cv

### PR DESCRIPTION
**Pull request by keepalot**

### CODE REVIEW

**Comment by weppos** [comment]
Hi @keepalot, thanks for the submission. Do you represent the registry?

**Comment by keepalot** [comment]
No, I don't represent the registry.

**Comment by weppos** [comment]
Unfortunately, as per our [guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), we can only merge changes if a registry representative or an official documentation confirms them.

Do you have any official documentation to provide?

**Comment by keepalot** [comment]
I will contact the registry for confirmation.

**Comment by weppos** [comment]
Closing until further follow up.

**Pull request closed without merging**
