### PR TITLE
Added FlashDrive.io domain names

### PR DESCRIPTION
**Pull request by flashdriveio**
* [X ] Description of Organization
* [X ] Reason for PSL Inclusion
* [X ] DNS verification via dig
* [X ] Run Syntax Checker (make test)

* [X ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [X] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [X] This request was _not_ submitted with the objective of working around other third party limits
  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

### Description of organization
FlashDrive.io is a PaaS offering cloud hosting solution for developers and enterprises. We issue fldrv.com and onflashdrive.app subdomains to our users

### Reason for PSL Inclusion
We use Let's encrypt to issue SSL certificates for each independent subdomain and we'd like to have each subdomain treated as an independent domain since our service is multi-tenant

### DNS verification via dig

dig +short TXT psl.fldrv.com
"https://github.com/publicsuffix/list/pull/1401"

dig +short TXT psl.onflashdrive.app
"https://github.com/publicsuffix/list/pull/1401"

### CODE REVIEW

**Comment by dnsguru** [comment]
This appears to be stating that the rationale for requesting is for Lets Encrypt limit bypassing.  Please provide more robust rationale if that is not the case, and indicate where you have followed THEIR instructions directly with them for this.

**Comment by flashdriveio** [comment]
Hi,
No the main reason is that we create custom subdomains for each app hosted on FlashDrive.io
Since it's a multi-tenant hosting service we need each subdomain to be treated like an individual domain.

Thanks!

**Comment by dnsguru** [comment]
DNS Validation fails - noticed that you've got psl.fldrv.com - should be _psl.fldrv.com ; neither work when looking up on publicly accessible nameservers.

FIX this and comment once both your affected domains are correctly answering with _psl TXT records.  This will not proceed without it.

**Comment by flashdriveio** [comment]
Hi,

Sorry about that, the DNS have been updated.

Thanks,

Alex.

**Review by dnsguru — CHANGES_REQUESTED** [review]
.app sorts before .com, please reorder

**Comment by dnsguru** [comment]
DNS Validation now working
Passes tests
no conflict with base

needs to sort by TLD then SLD

**Comment by flashdriveio** [comment]
Hi,

Made the change with the sorting. Thanks.

**Comment by sleevi** [comment]
TXT records fail to validate; "`#1401`" != "`https://github.com/publicsuffix/list/pull/1401`"

**Comment by dnsguru** [comment]
> TXT records fail to validate; "`#1401`" != "`https://github.com/publicsuffix/list/pull/1401`"

I'll accept the PR number matching the PR without the balance of the URL

**Review by dnsguru — APPROVED** [review]
+ DNS Validation "Succeeds"
   **_NOTE:_** PR # matches, but not syntax of full URL - will merge but recommend @flashdriveio update from ```#1401``` to ```https://github.com/publicsuffix/list/pull/1401``` in the affected domains' DNS zones to match the correct formatting of these entries in order to avoid automation removing these unexpectedly at a point in the future.
+ No Conflict with Base
+ Tests Pass
+ Conforms to Guidelines

**APPROVED**

**Comment by simon-friedberger** [comment]
@qoddiapps Are you still using these? You seem to have rebranded and at least the DNS entry on onflashdrive.app is gone.

**Comment by groundcat** [comment]
> @qoddiapps Are you still using these? You seem to have rebranded and at least the DNS entry on onflashdrive.app is gone.

@simon-friedberger It seems that `onflashdrive.app` was registered by a different registrant on `2024-03-08T12:47:32Z` after the domain expired. It is probably registered by a website called `L53.net` (see [L53 announcement](https://customer.l53.net/news/domain-onflashdrive-app-inaccessible-in-certain-areas)) that allows its users to register subdomains of `onflashdrive.app`. A quick Google search shows that this domain is used by users specifically wanting to bypass Cloudflare limits ([Google search link](https://www.google.com/search?q="onflashdrive.app")).

On the order page, L53 also took advantage of another expired and then taken-over PSL domain:

- `filegear-sg.me` #713

image

image

**Comment by qoddiapps** [comment]
@simon-friedberger  As of today we are only using fldrv.com and qoddiapp.com
In the future we plan to use qoddi.app as well.

Thanks!
Alex.

**Comment by dnsguru** [comment]
> @simon-friedberger As of today we are only using fldrv.com and qoddiapp.com In the future we plan to use qoddi.app as well.
> 
> Thanks! Alex.

@qoddiapps We're volunteers investing our time in these dialogs, and your company's relaxed attitude on the domains it requested has created a potential security hole that allowed another company to register a domain name that you had requested be added to the PSL, but casually let lapse.   So that we don't remove the entire flashdrive.io section and all its domains, please thoroughly review your entries rather than a casual response as if we're your IT team.

**Comment by qoddiapps** [comment]
@simon-friedberger  Apologies about that, you're absolutely right.  I submitted an updated on the patch-1 branch, not sure if I should have done it on the master branch directly?

Thanks,

Alex.

**Comment by groundcat** [comment]
> I submitted an updated on the patch-1 branch, not sure if I should have done it on the master branch directly?

@qoddiapps You should follow the [guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) and submit a pull request.

**Pull request merged**
