### PR TITLE
Remove zone.id (!urgent)

### PR DESCRIPTION
**Pull request by hdrxs312**
this domain will be expired.
reason:
- the new owner may dont know about publicsuffix. it will be dangerous.
- keep the list from inactive domain, if there is no one buy this domain

* [x] Description of Organization
* [x] Reason for PSL **Removal**
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://www.zone.id

Reason for PSL _Removal_
====

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by sleevi** [comment]
I’m unclear. In
https://github.com/publicsuffix/list/pull/575 you stated people register
subdomains off this name.

Are you no longer providing this service? Are you not re-registering your
domain? Updates take between 6-18 months to propagate, and thus if you have
something else intended for this domain, it won’t be usable.

Have you followed all the other instructions? You didn’t fill them out, and
so it’s not clear.

**Comment by hdrxs312** [comment]
i will not extend this domain.
the new owner will confuse about this subdomain cookie.

it's not about me

**Comment by sleevi** [comment]
Yes. That is a consequence of adding to the PSL.

Have you followed the directions, as I asked previously?

**Comment by hdrxs312** [comment]
yes. all my subdomain is well-formed.
but i will close my business. not re-register this domain.

**Comment by sleevi** [comment]
You have not followed directions provided when opening a pull request.

**Comment by hdrxs312** [comment]
i am sorry. what is the direction?

**Comment by sleevi** [comment]
The pieces you deleted when you opened this PR, which repeatedly say don’t
open a PR unless you’ve followed the directions.

Read
https://github.com/publicsuffix/list/wiki/Guidelines and
https://raw.githubusercontent.com/publicsuffix/list/master/.github/pull_request_template.md

**Comment by hdrxs312** [comment]
i have created record for DNS verification.
`make test` also no problem.
about the template,

in 2017, the template is not present.
i see other pull request, just give the reason.
so i am did same

**Comment by hdrxs312** [comment]
so, what next mr @sleevi ?

**Pull request closed without merging**
