### PR TITLE
Add .RU and .SU geographic suffixes owned by FAITID

### PR DESCRIPTION
**Pull request by weppos**
Follow up to GH-359. See also GH-380.

This commit is also related to
https://bugzilla.mozilla.org/show_bug.cgi?id=1134993 https://github.com/publicsuffix/list/commit/601e0b094957f3289be53e50a5dbdcad6d744e6a
However, I need to follow up with FAITID because it's not clear the
boundary between the current list of .SU suffices, and the provided one.

### CODE REVIEW

**Comment by weppos** [comment]
Before this can be merged, I need to determine the overlap between the .SU domains provided by FATID, and the domains that were added in https://bugzilla.mozilla.org/show_bug.cgi?id=1134993

It seems that these domains were added by mistake in the .SU section, although they were managed by a different entity (FATID). The request was sponsored by the .SU registry (but it should really have been sponsored by FATID).

@gerv any feedback that may help to clarify https://bugzilla.mozilla.org/show_bug.cgi?id=1134993 is appreciated.

This is the diff between the current .SU domains, and the new list.

```diff
--- untitled
+++ (clipboard)
@@ -1,50 +1,30 @@
-abkhazia.su
 adygeya.su
-aktyubinsk.su
 arkhangelsk.su
-armenia.su
-ashgabad.su
-azerbaijan.su
 balashov.su
 bashkiria.su
 bryansk.su
-bukhara.su
-chimkent.su
 dagestan.su
-east-kazakhstan.su
-exnet.su
-georgia.su
 grozny.su
 ivanovo.su
-jambyl.su
 kalmykia.su
 kaluga.su
-karacol.su
-karaganda.su
 karelia.su
 khakassia.su
 krasnodar.su
 kurgan.su
-kustanai.su
 lenug.su
-mangyshlak.su
 mordovia.su
 msk.su
 murmansk.su
 nalchik.su
-navoi.su
-north-kazakhstan.su
 nov.su
 obninsk.su
 penza.su
 pokrovsk.su
 sochi.su
 spb.su
-tashkent.su
-termez.su
 togliatti.su
 troitsk.su
-tselinograd.su
 tula.su
 tuva.su
 vladikavkaz.su
```

I am going to follow up with FATID.

**Comment by SmilingNavern** [comment]
+1 to this MR.

We have a problem with letsencrypt ratelimiting for ru suffixes. This MR should fix those issues.

**Comment by yaleks** [comment]
We have up to date listing of domains operated by FAITID in #380 . 
All policies declarated in https://faitid.org/en/projects/RU.NET/documents . I think you have contacted @oldfrogger .
You can check each line by whois and obtain for example
```
$ whois adygeya.su                                                                                                                                                                                                     
% By submitting a query to RIPN's Whois Service                                                                                                                                                                                  
% you agree to abide by the following terms of use:                                                                                                                                                                              
% http://www.ripn.net/about/servpol.html#3.2 (in Russian)                                                                                                                                                                        
% http://www.ripn.net/about/en/servpol.html#3.2 (in English).                                                                                                                                                                    
                                                                                                                                                                                                                                 
domain:        ADYGEYA.SU                                                                                                                                                                                                        
descr:         Open registration                                                                                                                                                                                                 
descr:         http://faitid.org                                                                                                                                                                                                 
nserver:       ns3-geo.nic.ru.                                                                                                                                                                                                   
nserver:       ns4-geo.nic.ru.                                                                                                                                                                                                   
nserver:       ns8-geo.nic.ru.                                                                                                                                                                                                   
state:         REGISTERED, DELEGATED                                                                                                                                                                                             
org:           Foundation for Assistance for Internet Technologies and Infrastructure Development                                                                                                                                
phone:         +7 495 7898207                                                                                                                                                                                                    
fax:           +7 495 7375762                                                                                                                                                                                                    
e-mail:        info@faitid.org                                                                                                                                                                                                   
registrar:     RUCENTER-REG-FID                                                                                                                                                                                                  
created:       1999.06.18                                                                                                                                                                                                        
paid-till:     2017.10.01
free-date:     2017.11.03
source:        TCI

Last updated on 2017.01.17 13:36:30 MSK
$ whois spb.ru
% By submitting a query to RIPN's Whois Service
% you agree to abide by the following terms of use:
% http://www.ripn.net/about/servpol.html#3.2 (in Russian) 
% http://www.ripn.net/about/en/servpol.html#3.2 (in English).

domain:        SPB.RU
nserver:       ns3-geo.nic.ru.
nserver:       ns4-geo.nic.ru.
nserver:       ns8-geo.nic.ru.
state:         REGISTERED, DELEGATED, UNVERIFIED
org:           Foundation for Assistance for Internet Technologies and Infrastructure Development
registrar:     RU-CENTER-RU
admin-contact: https://www.nic.ru/whois
created:       1997.03.11
paid-till:     2017.04.01
free-date:     2017.05.02
source:        TCI

Last updated on 2017.01.17 13:41:31 MSK
```
Also you can validate that this domains available for public registration on https://www.nic.ru/dns/en/ or https://www.reg.com/domain/new/ .

We have broken 100000+ domains even for two weeks! This can cause stop of service, the security issues, etc...

**Comment by oldfrogger** [comment]
I included whois output for all those domains from TCI servers (those are mentioned in IANA .su page) in my responce from corporate e-mail.

**Comment by yaleks** [comment]
A comment regarding Mozilla bugzilla - the provided in 2015 list is not rely on any reference. 
I think it was copied from Wikipedia and not validated at all. 
In this case no need to explore the origin of lists differences.
It looks like [Sergey Ovcharenko](https://www.linkedin.com/in/sergey-ovcharenko-3a797999) leave FAITID, so contact @oldfrogger ([Maxim Alzoba](https://icannwiki.com/Maxim_Alzoba)) again.

**Comment by oldfrogger** [comment]
A correction.
 Sergey Ovcharenko worked for .SU and not for FAITID. The person in .SU, who replaced him is Vadim Mikhailov. I am trying to establish contact with him (the other way is to use .SU Adm contect from IANA Page).

**Comment by oldfrogger** [comment]
Hello Simone, 

Could you help us with the correct TXT field, for example for _pls.msk.ru (reffered here)
should it be (taken from guidance https://github.com/publicsuffix/list/wiki/Guidelines)
https://github.com/publicsuffix/list/pull/384
or
https://github.com/publicsuffix/list/pull/380
?

**Comment by yaleks** [comment]
@oldfrogger , IMHO #384 . Another PR  is closed.
Isn't it, @weppos ?

**Comment by weppos** [comment]
@oldfrogger I will follow up with you soon. I'm currently handling several tasks at the time, hence I don't always follow up on the same day.

As for the PR, you can use 384. It's not extremely relevant (as the important thing is to be able to determine you were able to create the record), but in this case I'd definitely use #384 as this is the one that I will likely merge.

**Comment by alexott** [comment]
I don't have any affiliation with FAITID, but please consider inclusion of this information into PSL, as we got affected by removal of `com.ru` from list...

FAITID handles several projects:

- RU.NET+: list of handled 2nd level domains is available at http://ru.faitid.org/sites/default/files/RRA_ADD1_end.pdf (it's Russian, but list is clearly recognizable). Customers can register 3rd level domains in .ABKHAZIA.SU, .ADYGEYA.RU, .ADYGEYA.SU, .AKTYUBINSK.SU, .ARKHANGELSK.SU, .ARMENIA.SU, .ASHGABAD.SU, .AZERBAIJAN.SU, .BALASHOV.SU, .BASHKIRIA.RU, .BASHKIRIA.SU, .BIR.RU, .BRYANSK.SU, .BUKHARA.SU, .CBG.RU, .CHIMKENT.SU, .COM.RU, .DAGESTAN.RU, .DAGESTAN.SU, .EAST-KAZAKHSTAN.SU, .EXNET.SU, .GEORGIA.SU, .GROZNY.RU, .GROZNY.SU, .IVANOVO.SU, .KALMYKIA.RU, .JAMBYL.SU, .KALMYKIA.SU, .KALUGA.SU, .KARACOL.SU, .KARAGANDA.SU, .KARELIA.SU, .KHAKASSIA.SU, .KRASNODAR.SU, .KURGAN.SU, .KUSTANAI.RU, .KUSTANAI.SU, .LENUG.SU, .MANGYSHLAK.SU, .MARINE.RU, .MORDOVIA.RU, .MORDOVIA.SU, .MSK.RU, .MSK.SU, .MURMANSK.SU, .MYTIS.RU, .NALCHIK.RU, .NALCHIK.SU, .NAVOI.SU, .NORTH-KAZAKHSTAN.SU, .NOV.RU, .NOV.SU, .OBNINSK.SU, .PENZA.SU, .POKROVSK.SU, .PYATIGORSK.RU, .RU.NET, .SOCHI.SU, .SPB.RU, .SPB.SU, .TASHKENT.SU, .TERMEZ.SU, .TOGLIATTI.SU, .TROITSK.SU, .TSELINOGRAD.SU, .TULA.SU, .TUVA.SU, .VLADIKAVKAZ.RU, .VLADIKAVKAZ.SU, .VLADIMIR.RU, .VLADIMIR.SU, .VOLOGDA.SU
- Moscow: domains `.MOSCOW` & `.МОСКВА`.  As I understand, they have special registration procedures for priority registration of government & companies (http://ru.faitid.org/projects/moscow/documents)
- RUCLID: http://ruclid.org/ - multiple TLDs for cities & regions of Russian Federation: `.TATAR`, `.РУС`, etc.
- Volga: TLD `.volga` for Volga region of Russian Federation (http://ru.faitid.org/ru/projects/volga) - part of RUCLID

**Comment by oldfrogger** [comment]
Hello Alex, 

.MOSCOW and .МОСКВА were already on the list (as ICANN contracted registries).

.TATAR and .РУС are independent registries.
(We just held place for discussions around new gTLD projects, and .volga did not happen due to various reasons.)

**Comment by demfloro** [comment]
Hello.

Please tell what stopping this pull request from merging? I'm an employee of one hosting provider and we are affected by removal of msk.ru and spb.ru prefixes from the list because of use of Let's Encrypt.

**Comment by oldfrogger** [comment]
We have made all confirmations and updated DNS records according to the Guidance. I hope it is fixed soon.

**Comment by valkuc** [comment]
@weppos Simone, any proggress on merging this pull request?

**Comment by weppos** [comment]
Validated via DNS.

```
for name (
  ru.net
  adygeya.ru
  bashkiria.ru
  bir.ru
  cbg.ru
  com.ru
  dagestan.ru
  grozny.ru
  kalmykia.ru
  kustanai.ru
  marine.ru
  mordovia.ru
  msk.ru
  mytis.ru
  nalchik.ru
  nov.ru
  pyatigorsk.ru
  spb.ru
  vladikavkaz.ru
  vladimir.ru
  abkhazia.su
  adygeya.su
  aktyubinsk.su
  arkhangelsk.su
  armenia.su
  ashgabad.su
  azerbaijan.su
  balashov.su
  bashkiria.su
  bryansk.su
  bukhara.su
  chimkent.su
  dagestan.su
  east-kazakhstan.su
  exnet.su
  georgia.su
  grozny.su
  ivanovo.su
  jambyl.su
  kalmykia.su
  kaluga.su
  karacol.su
  karaganda.su
  karelia.su
  khakassia.su
  krasnodar.su
  kurgan.su
  kustanai.su
  lenug.su
  mangyshlak.su
  mordovia.su
  msk.su
  murmansk.su
  nalchik.su
  navoi.su
  north-kazakhstan.su
  nov.su
  obninsk.su
  penza.su
  pokrovsk.su
  sochi.su
  spb.su
  tashkent.su
  termez.su
  togliatti.su
  troitsk.su
  tselinograd.su
  tula.su
  tuva.su
  vladikavkaz.su
  vladimir.su
  vologda.su
)
do
    echo $name
    dig TXT _psl.$name +short
done


ru.net
"https://github.com/publicsuffix/list/pull/384"
adygeya.ru
"https://github.com/publicsuffix/list/pull/384"
bashkiria.ru
"https://github.com/publicsuffix/list/pull/384"
bir.ru
"https://github.com/publicsuffix/list/pull/384"
cbg.ru
"https://github.com/publicsuffix/list/pull/384"
com.ru
"https://github.com/publicsuffix/list/pull/384"
dagestan.ru
"https://github.com/publicsuffix/list/pull/384"
grozny.ru
"https://github.com/publicsuffix/list/pull/384"
kalmykia.ru
"https://github.com/publicsuffix/list/pull/384"
kustanai.ru
"https://github.com/publicsuffix/list/pull/384"
marine.ru
"https://github.com/publicsuffix/list/pull/384"
mordovia.ru
"https://github.com/publicsuffix/list/pull/384"
msk.ru
"https://github.com/publicsuffix/list/pull/384"
mytis.ru
"https://github.com/publicsuffix/list/pull/384"
nalchik.ru
"https://github.com/publicsuffix/list/pull/384"
nov.ru
"https://github.com/publicsuffix/list/pull/384"
pyatigorsk.ru
"https://github.com/publicsuffix/list/pull/384"
spb.ru
"https://github.com/publicsuffix/list/pull/384"
vladikavkaz.ru
"https://github.com/publicsuffix/list/pull/384"
vladimir.ru
"https://github.com/publicsuffix/list/pull/384"
abkhazia.su
"https://github.com/publicsuffix/list/pull/384"
adygeya.su
"https://github.com/publicsuffix/list/pull/384"
aktyubinsk.su
"https://github.com/publicsuffix/list/pull/384"
arkhangelsk.su
"https://github.com/publicsuffix/list/pull/384"
armenia.su
"https://github.com/publicsuffix/list/pull/384"
ashgabad.su
"https://github.com/publicsuffix/list/pull/384"
azerbaijan.su
"https://github.com/publicsuffix/list/pull/384"
balashov.su
"https://github.com/publicsuffix/list/pull/384"
bashkiria.su
"https://github.com/publicsuffix/list/pull/384"
bryansk.su
"https://github.com/publicsuffix/list/pull/384"
bukhara.su
"https://github.com/publicsuffix/list/pull/384"
chimkent.su
"https://github.com/publicsuffix/list/pull/384"
dagestan.su
"https://github.com/publicsuffix/list/pull/384"
east-kazakhstan.su
"https://github.com/publicsuffix/list/pull/384"
exnet.su
"https://github.com/publicsuffix/list/pull/384"
georgia.su
"https://github.com/publicsuffix/list/pull/384"
grozny.su
"https://github.com/publicsuffix/list/pull/384"
ivanovo.su
"https://github.com/publicsuffix/list/pull/384"
jambyl.su
"https://github.com/publicsuffix/list/pull/384"
kalmykia.su
"https://github.com/publicsuffix/list/pull/384"
kaluga.su
"https://github.com/publicsuffix/list/pull/384"
karacol.su
"https://github.com/publicsuffix/list/pull/384"
karaganda.su
"https://github.com/publicsuffix/list/pull/384"
karelia.su
"https://github.com/publicsuffix/list/pull/384"
khakassia.su
"https://github.com/publicsuffix/list/pull/384"
krasnodar.su
"https://github.com/publicsuffix/list/pull/384"
kurgan.su
"https://github.com/publicsuffix/list/pull/384"
kustanai.su
"https://github.com/publicsuffix/list/pull/384"
lenug.su
"https://github.com/publicsuffix/list/pull/384"
mangyshlak.su
"https://github.com/publicsuffix/list/pull/384"
mordovia.su
"https://github.com/publicsuffix/list/pull/384"
msk.su
"https://github.com/publicsuffix/list/pull/384"
murmansk.su
"https://github.com/publicsuffix/list/pull/384"
nalchik.su
"https://github.com/publicsuffix/list/pull/384"
navoi.su
"https://github.com/publicsuffix/list/pull/384"
north-kazakhstan.su
"https://github.com/publicsuffix/list/pull/384"
nov.su
"https://github.com/publicsuffix/list/pull/384"
obninsk.su
"https://github.com/publicsuffix/list/pull/384"
penza.su
"https://github.com/publicsuffix/list/pull/384"
pokrovsk.su
"https://github.com/publicsuffix/list/pull/384"
sochi.su
"https://github.com/publicsuffix/list/pull/384"
spb.su
"https://github.com/publicsuffix/list/pull/384"
tashkent.su
"https://github.com/publicsuffix/list/pull/384"
termez.su
"https://github.com/publicsuffix/list/pull/384"
togliatti.su
"https://github.com/publicsuffix/list/pull/384"
troitsk.su
"https://github.com/publicsuffix/list/pull/384"
tselinograd.su
"https://github.com/publicsuffix/list/pull/384"
tula.su
"https://github.com/publicsuffix/list/pull/384"
tuva.su
"https://github.com/publicsuffix/list/pull/384"
vladikavkaz.su
"https://github.com/publicsuffix/list/pull/384"
vladimir.su
"https://github.com/publicsuffix/list/pull/384"
vologda.su
"https://github.com/publicsuffix/list/pull/384"
```

**Comment by valkuc** [comment]
Thanks all!

**Comment by oldfrogger** [comment]
Thanks all !

**Pull request merged**
