### PR TITLE
add .ind.mom 

### PR DESCRIPTION
**Pull request by anantsparrow**
Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization 
====

ind.mom is a sld domain managed by SparrowHost Registry, Our company aims to offer .ind.mom 3rd level domains to indian mothers for their business. We are accredited registrar and a registry company based in Jharkhand, India
I am the founder and ceo of SparrowHost

Organization Website:  https://registry.ind.mom

Reason for PSL Inclusion
====

- We are aiming to sell sub domains of .ind.mom through accredited registrars in India
- Our domain basically means an indian mom business domains, so lots of indian mothers can start their business with this sld

Number of users this request is being made to serve: 40k+

 **DNS Verification via dig**

dig +short TXT _psl.ind.mom
`"https://github.com/publicsuffix/list/pull/1984"`

 **Results of Syntax Checker (`make test`)**

All tests passed. no errors

### CODE REVIEW

**Comment by anantsparrow** [comment]
@simon-friedberger can you check why i am getting an error now? i just synced my PR from base.

**Comment by anantsparrow** [comment]
@yahesh hey there, sure we will change it to SLD, as we are preparing things to sell the SLD of .ind.mom domains for indian mother’s to grow their business online and all. We will change things on our website asap.

**Comment by anantsparrow** [comment]
@yahesh we have prepared and made epp registrar and registry modules + whmcs modules too for reselling it.

**Comment by anantsparrow** [comment]
> The sorting looks okay to me.
> 
> However, according to the advertising website:
> 
> > _The .ind.mom TLD is a domain extension specifically designed for individuals and organizations related to India's mom and parenting community. It provides a unique online presence for websites targeting this niche audience._
> 
> Adding `ind.mom` to the PSL will not make this a top-level domain. This advertisement is misleading.
> 
> Furthermore, the advertising website states:
> 
> > _As online spaces evolve, new domain extensions provide an opportunity to embrace innovation and stay ahead of the curve. By selecting a .ind.mom domain, you demonstrate adaptability and a willingness to explore emerging trends in the digital landscape._
> 
> Adding `ind.mom` to the PSL will not make this a "new domain extension". This advertisement is misleading.

We have changed our website contents from TLD to SLDs, as we will be providing 3rd level domains of .IND.MOM, Kindly confirm if we have to change anything else on the website? or it is fine for now?

**Comment by simon-friedberger** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] ind.mom expires 2026-06-18
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting (TY @yahesh)
* [x] Reasoning/Organization description

**Comment by anantsparrow** [comment]
@simon-friedberger Hey there, when it can be merged? will it take more time? or anything is left from my side?

**Comment by dnsguru** [comment]
you overwhelmed our cycles with persistence last go-around; could you please balance your patience with your persistence out of respect to the many other requestors.   Thank you in advance for chilling out

**Comment by anantsparrow** [comment]
can i add 1 another domain in it? or is it too late to modify it? @simon-friedberger

**Comment by simon-friedberger** [comment]
@anantsparrow Feel free to add more domains but please point it out in a comment.

**Comment by groundcat** [comment]
Hello @anantsparrow 

1. I have noted that the domain `ind.mom` will expire on 2026-06-18, which is less than two years from now. To ensure continued inclusion in the PSL, please renew the domain to maintain a validity period of over two years at all times.
2. Additionally, the required TXT record for `_psl.ind.mom` is no longer being returned. It is essential to maintain this record to comply with PSL requirements. Please address these issues at your earliest convenience to ensure continued eligibility.
3. OSINT analysis indicates that `ind.mom` no longer shows growth in subdomain counts, and [CT](https://crt.sh/?q=ind.mom) shows all SSL certificates issued have expired. Additionally, your website, https://sparrowhost.in/, no longer lists this as an available suffix for user registration.

Could you please confirm if the project associated with `ind.mom` is still active? If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period (over 30 days), your entry may be subject to review/removal. Thank you.

#1119 #1793

**Comment by anantsparrow** [comment]
1. Hey there it will be renewed within upcoming few days. It is already set on auto renewal at namecheap.
2. for the _psl record, we are facing some issues on adding this records with the epp registry backend, it gets overwrite everytime, if it is important to have for lifetime do let me know, i will figure out something.
3.  Depends upon the sale, as we are not doing marketing for it
4. i do not know how did you check but upon checking from my website, it is showing correctly and we are still selling the .ind.mon suffix and people are using it too. (https://dash.sparrowhost.in/?cmd=checkdomain ) i have listed my company's domain checking url. and attaching screenshot here

image

**Comment by wdhdev** [comment]
We do require an `_psl` TXT record to be present at all times. Quick question, are you able to tell us how many subdomains/users the domain has?

**Comment by anantsparrow** [comment]
here is the list of subdomains https://subdomainfinder.c99.nl/scans/2024-12-29/ind.mom

There are more but those seems to be not being used by customers. But those domains are active

**Comment by groundcat** [comment]
Thanks for the updates and information! @anantsparrow 

1. Regarding domain renewal: While auto-renewal is good, we recommend maintaining at least 2 years of registration at all times, not just when it's about to expire. Auto-renewal typically only triggers close to expiration, which wouldn't meet our requirement of maintaining >2 years registration term consistently. I'd recommend proactively renewing annually to ensure you always have more than 2 years remaining on the registration.
2. About the _psl TXT record: Yes, this is important to maintain long-term. We're planning to possibly implement automation in the future that may remove entries from the PSL if they don't have the required TXT record in place. Please work on finding a solution to keep the _psl TXT record persistent in your zone, even with the EPP registry backend challenges.

**Comment by anantsparrow** [comment]
1. Domain will be renewed in the first week of January, As i do not have control over that department.
2. I have told my technical team regarding this _psl record to be permanent forever. They are working on it and it will also take another 1 week, as we will have to change lots of things on the dns server + epp codes.

**Comment by anantsparrow** [comment]
Update 1. Domain has been renewed till 2028-06-18
2. _psl is still being done by our team. as it requires time to make changes smoothly on our registry system.

**Comment by anantsparrow** [comment]
Update: _psl txt record has been added permanently with value https://github.com/publicsuffix/list/pull/1984

**Comment by anantsparrow** [comment]
_psl record has been added.

**Comment by groundcat** [comment]
Thank you @anantsparrow for implementing both requirements - extending the domain registration through 2028 and adding the _psl TXT record. We appreciate your prompt attention to these compliance items.

**Comment by anantsparrow** [comment]
@groundcat i have one doubt here, let's suppose if i want to add few more slds here, so in the new pr, i will have to add under my private section right or anything else i have to do.

**Comment by groundcat** [comment]
> @groundcat i have one doubt here, let's suppose if i want to add few more slds here, so in the new pr, i will have to add under my private section right or anything else i have to do.

If you need to add new entries that also belong to SparrowHost, then yes, you should add them under the SparrowHost block. Just follow the guidelines, such as sorting requirements, etc.

**Pull request merged**
