### PR TITLE
add pages.internal.impertrix.com

### PR DESCRIPTION
**Pull request by impertrixsolutions**
* [ ] Description of Organization
* [ ] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://impertrix.com

we are a hosting provider/CSP

Reason for PSL Inclusion
====

we want to use this with gitlab pages to provide to internal engineers high efficiency when prototyping and easy deployment

DNS Verification via dig
=======

dig +short TXT _psl.pages.internal.impertrix.com
"https://github.com/publicsuffix/list/pull/1078"
make test
=========

make looks good, pass 5/5

### CODE REVIEW

**Comment by dnsguru** [comment]
Please look at #974 - is this a request for internal only project? PSL typically does not approve or integrate internal-only requests because this is a global resource that is downloaded and used widely.

**Comment by impertrixsolutions** [comment]
this is not for internal only, we do run public level websites on this, its only named internal as only internal engineers are allowed use it to host websites on there, but anyone can access the websites

**Comment by dnsguru** [comment]
related #1060

**Comment by dnsguru** [comment]
>we want to use this with gitlab pages to provide to **internal** engineers high efficiency when prototyping and easy deployment

Can you revise the rationale or provide a different one here in the comments?  It looks like this is a request for an internal only solution

**Comment by dnsguru** [comment]
@impertrixsolutions *NUDGE* 
This PR was not applied and needs to be re-based and resubmitted

**Pull request closed without merging**
