### PR TITLE
added changes for myshopmatic.com to be added to PSL

### PR DESCRIPTION
**Pull request by santoshsankannavar**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by santoshsankannavar** [comment]
organization: myshopmatic.com enables the merchants to sell their products online by providing platform to create the digital selling platform.
Reason for PSL Inclusion: Merchants using subdomain of myshopmatic.com are not able to  integrate their website with facebook and it wont  work untill we have our domain in PSL. please do add ASAP.

**Comment by santoshsankannavar** [comment]
dig TXT _psl.myshopmatic.com +short
"https://github.com/publicsuffix/list/pull/1275"

**Comment by dnsguru** [comment]
Please see #1245

**Comment by dnsguru** [comment]
See https://github.com/privacycg/private-click-measurement/issues/78

**Comment by santoshsankannavar** [comment]
Hi,
I am sorry i did not find any solution on how to proceed further on this. when we reached out to FB they clearly mentioned to have this domain added in PSL. hence created a PR. i guess its better you have this communicated to FB if you guys dont support FB related requests. looks like a communication gap between you guys. its unnecessary headache for users and clients. Neither your website talks about this exception. 
It will be great if you can help me with next course of action

**Comment by santoshsankannavar** [comment]
@dnsguru https://developers.facebook.com/docs/sharing/domain-verification
this is exactly what we want. we have registered domain with facebook however for TLD+ needs our domain mentioned in PSL. i am not sure why there is conflicting information between you guys and FB.

**Comment by bedfordsean** [comment]
Hi @santoshsankannavar 

Would you mind telling me who from FB guided you towards opening a request here?

The guidance from Facebook (clarified last week in the help centre article) is that this process is intended for large platform partners to allow businesses that they host on behalf of to successfully validate their domain as if it were an eTLD+1. Would 

The Public Suffix List is not useful, nor intended to be used as a means to gain additional subdomain events reporting. 

I did a Google for "*.myshopmatic.com" and do see various merchants hosted as subdomains so it is possible that you may meet this criteria. 

To clarify; do you wish for and intend for total cookie separation of each of those subdomains where subdomain owners can individually register through Facebook AEM and be treated as their own eTLD+1s? 

Effectively beyond owning "myshopmatic.com", you'll not have much control for that site itself. For example, I note you have a /login page on that domain. This may not work as it does today if you proceeded with a PSL addition.

**Comment by santoshsankannavar** [comment]
@bedfordsean why would it stop login page to work after adding domain. to psl?

**Comment by bedfordsean** [comment]
@santoshsankannavar it depends how you use, redirect, and set cookies after login. "myshopmatic.com" will no longer be able to set domain level cookies after PSL addition. I'd recommend reading up on how PSL works here first: https://github.com/publicsuffix/list/wiki

**Pull request closed without merging**
