### PR TITLE
Include *.cldrgov.us and *.st.cldrgov.us to the PSL

### PR DESCRIPTION
**Pull request by kedar031**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website:  https://www.cloudera.com/
I am an engineer at Cloudera, Inc. We sell enterprise software in both on-prem and cloud service forms.

Reason for PSL Inclusion
====

The PR adds 2 more domains to the previously submitted *.cloudera.site as part of https://github.com/publicsuffix/list/pull/1400

As part of Cloudera’s cloud service offering, we have provisioned FedRamp cluster for customers' access to their resources under
*.cldrgov.us domain. The feature can scale for multiple regions and each region points to a different domain such as <unique_region_id>.cldrgov.us. For the staging environment of the same cluster, we are using the domain <unique_region_id>.st.cldrgov.us

As we need to provide strong boundaries between customers, we should add the <unique-customer-id>.<region-id>.cldrgov.us to the public suffix list to ensure that

• Customer resources to be placed in their own region for data governance restrictions and compliance.
• Cookies cannot be set to apply across customers
•.The certificate generation activity of one customer doesn’t affect others

Number of users this request is being made to serve:  
Unfortunately, the near estimate number we wouldn't know at this point.  Approximately this would be 100 - 1000 users for the first 3-4 tenants.
Since the cluster is being setup fresh and initially this may be expected to serve fewer requests and eventually scale to 10,000+ users. 

DNS Verification via dig
=======

```
% dig +short TXT _psl.g0.st.cldrgov.us
"https://github.com/publicsuffix/list/pull/1724"
```

```
% dig +short TXT _psl.g0.cldrgov.us
"https://github.com/publicsuffix/list/pull/1724"
```

Results of Syntax Checker (`make test`)
=========

All tests passed

### CODE REVIEW

**Comment by kedar031** [comment]
PSL Team, this has been up for some time now. Can this be reviewed please?

**Comment by simon-friedberger** [comment]
Why does the staging environment need adding to the PSL? Cookies shouldn't be an issue there.

**Comment by kedar031** [comment]
> Why does the staging environment need adding to the PSL? Cookies shouldn't be an issue there.

Thanks for the review @simon-friedberger. 
Since we have a similar staging setup as Prod, would be good to test the setup for internal tenants on multiple regions. Please let me know if this violates any PSL inclusion rules by any chance.

**Comment by simon-friedberger** [comment]
In general that's fine. Can you please add user numbers to the PR?

**Comment by simon-friedberger** [comment]
* [ ] Expiration (Note: Must STAY >2y at all times)
  * [x] cldrgov.us expires 2033-02-01
  * [ ] cloudera.site expires 2024-04-25
* [ ] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [ ] Reasoning/Organization description

**Comment by kedar031** [comment]
> In general that's fine. Can you please add user numbers to initial PR description?

Update the section as below. 
```
Number of users this request is being made to serve:  
Unfortunately, the near estimate number we wouldn't know at this point.  Approximately this would be 100 - 1000 users for the first 3-4 tenants.
Since the cluster is being setup fresh and initially this may be expected to serve fewer requests and eventually scale to 10,000+ users. 
```

**Comment by kedar031** [comment]
> * [ ]  Expiration (Note: Must STAY >2y at all times)
>   
>   * [x]  cldrgov.us expires 2033-02-01
>   * [ ]  cloudera.site expires 2024-04-25
> * [ ]  DNS _psl entries (Note: Must STAY in place)
> * [x]  Tests pass
> * [x]  Sorting
> * [ ]  Reasoning/Organization description

hey @simon-friedberger - on the missing checks 

1.  DNS _psl entries are still in place, is there anything else apart from the below list that is missing?

```
% dig +short TXT _psl.g0.st.cldrgov.us
"https://github.com/publicsuffix/list/pull/1724"

% dig +short TXT _psl.g0.cldrgov.us
"https://github.com/publicsuffix/list/pull/1724"

% dig +short TXT _psl.cloudera.site
"https://github.com/publicsuffix/list/pull/1400"

% dig +short TXT _psl.b0.cloudera.site
"https://github.com/publicsuffix/list/pull/1400"
```

2. cloudera.site expires 2024-04-25

Have informed the Cloudera team who shall be renewing the "cloudera.site" domain shortly. 

3.   Reasoning/Organization description
Also please let me know if the description/reasoning around the user numbers updated is satisfactory. And if there is anything else that needs to be updated in the description.

**Comment by simon-friedberger** [comment]
```
> % dig +short TXT _psl.g0.st.cldrgov.us
> "https://github.com/publicsuffix/list/pull/1724"
```

You should have an entry at `_psl.cldrgov.us` and at `_psl.st.cldrgov.us`.

**Comment by simon-friedberger** [comment]
Note, the remaining validity should be at least 2 years. `cloudera.site` is still not valid for >2 years.

**Pull request closed without merging**
