### PR TITLE
additional ngrok domain - add `ngrok.pro`

### PR DESCRIPTION
**Pull request by benjaminchan**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

ngrok provides network ingress and tunneling services for more than 5 million developers. ngrok is used by engineers to aid in local development, as well as for network connectivity, and management for systems in production. I am an engineer at ngrok adding additional ingress domains, grouping different types of customers together, and also offering more customer choice.

Organization Website: https://ngrok.com

Reason for PSL Inclusion
====

The reason for inclusion is for Cookie Security between different users' sessions. Customers can reserve or be assigned subdomains of these domains for ingress, browsers should not send cookies across them.

Previous ngrok additions to PSL:
- The initial PR that added `ngrok.io`: https://github.com/publicsuffix/list/pull/48
- An additional PR that added `ngrok.app` `ngrok-free.app` `ngrok.dev` `ngrok-free.dev` more `ngrok.io` and `ngrok.pizza`: https://github.com/publicsuffix/list/pull/1653
  - Some background in a blog post: https://ngrok.com/blog-post/new-ngrok-domains

For this PR:
- ngrok seeks to provide subdomains on `ngrok.pro` as a choice for a specific customer segment, paying customers who want to connect to their ngrok domain via browser using HTTP, not HTTPS.  This requires use of a domain with a TLD that is not on the HSTS preload list utilized by browsers (`.pro` is not on this list, whereas `.app` and `.dev`, the currently supported options on the ngrok platform, are).

Number of users this request is being made to serve: 
- More than 5 million developers currently (https://ngrok.com/customers) 

Registration expiry is more than 2 years out:
```
ngrok.pro   2026-07-20
```

Example Use-Cases:

A developer wants to test the code running on their laptop with a system like Twilio that uses webhooks. The developer starts an ngrok agent locally and ngrok provides a public url which forwards encrypted traffic to the service running on their local machine. The developer can then configure Twilio to use that domain to call when an event occurs such as an incoming SMS message. A domain in that situation would look like `84c5df439d74.ngrok.dev`, or `3a5c10d67779.eu.ngrok.io` if the agent is configured to use the European region (one of seven regions available).

The user can then easily add [webhook verification](https://ngrok.com/docs/cloud-edge/modules/webhook) to make sure it is Twilio making the request, or add [basic-auth](https://blog.ngrok.com/posts/authentication-with-ngrok), [oauth](https://blog.ngrok.com/posts/how-to-secure-your-network-tunnels-with-oauth-fast), [mutual-TLS](https://ngrok.com/docs/ngrok-agent/ngrok#flags-12), [allow/deny CIDR ranges](https://ngrok.com/docs/ngrok-agent/ngrok#flags-12), and other features. More information is in the [Getting Started guide](https://ngrok.com/docs/getting-started), or this Twilio ["6 awesome reasons to use ngrok when testing webhooks"](https://www.twilio.com/blog/2015/09/6-awesome-reasons-to-use-ngrok-when-testing-webhooks.html) post.

Customers can also reserve specific subdomains instead of having them randomly assigned, which could look like `my-company.ngrok.app` or `webhook-development.ngrok.dev`.  

With the addition of `ngrok.pro` to the ngrok service, paying customers who want to connect to their ngrok domain via browser using HTTP, not HTTPS, would be able to use a subdomain of `ngrok.pro`.

Enterprise customers use ngrok to centrally manage and secure ingress for their many applications deployed across public cloud, serverless platforms, their own data center or Internet of Things devices. This article about the recent ngrok funding raise provides a nice overview: [techcrunch.com/2022/12/13/ngrok-a-service-to-help-devs-deploy-sites-services-and-apps-raises-50m](https://techcrunch.com/2022/12/13/ngrok-a-service-to-help-devs-deploy-sites-services-and-apps-raises-50m/)

DNS Verification via dig
=======

For `ngrok.pro`:
```
dig +short TXT _psl.ngrok.pro  
"https://github.com/publicsuffix/list/pull/1895"
```

Results of Syntax Checker (`make test`)
=========

The tests ran successfully:
```
# TOTAL: 5
# PASS:  5
```

### CODE REVIEW

**Comment by benjaminchan** [comment]
Couple ways to prove affiliation with the submitter org ngrok.com:
- DNS
```
dig +short TXT _psl.ngrok.com
"https://github.com/publicsuffix/list/pull/1895"
```
- input from the initial submitter: @inconshreveable could you confirm this PR is being made by ngrok?

**Comment by inconshreveable** [comment]
confirmed

**Comment by nijikokun** [comment]
@dnsguru any chance we can get someone to look at this, it's actively blocking us from launching a feature

**Comment by simon-friedberger** [comment]
* [x] ngrok.pro expires 2026-07-20
* [x] DNS _psl entries
* [x] Tests pass
* [x] Sorting according to guidelines
* [x] Reasoning/Organization description

**Review by simon-friedberger — APPROVED** [review]

**Comment by tammybailey** [comment]
@dnsguru would love to get this merged when you have a chance!

**Pull request merged**
