### PR TITLE
Add AWS Cloud9 domains

### PR DESCRIPTION
**Pull request by aprex**
Add domains for AWS Cloud9 service. AWS Cloud9 is IDE in browser, which allows customers to write and run code inside of browser.
Cloud9 provides Application Preview and Webviews functionalities, which implementation relies on domains added with this PR.

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Organization Website: https://aws.amazon.com/cloud9/
AWS Cloud9 is a service within Amazon Web services. It's a cloud-based integrated development environment (IDE) that lets you write, run, and debug your code with just a browser. It includes a code editor, debugger, and terminal.

I'm a software engineer working for Amazon Web Services, Cloud9 team https://www.linkedin.com/in/viktor-shcherba.

Reason for PSL Inclusion
====

For security reasons, AWS wants to prevent applications running on subdomains of `webview-assets.cloud9.<region>.amazonaws.com` and `vfs.cloud9.<region>.amazonaws.com` from setting and sharing cookies on such domains.

According to ICANN data expiration date for `amazonaws.com` is 2024-01-15, and for `amazonaws.com.cn` it is 2024-01-13.

DNS Verification via dig
=======

```
dig +short TXT _psl.vfs.cloud9.cn-north-1.amazonaws.com.cn
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.cn-northwest-1.amazonaws.com.cn
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.af-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.ap-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.ap-northeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.ap-northeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.ap-northeast-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.ap-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.ap-southeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.ap-southeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.ca-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.eu-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.eu-north-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.eu-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.eu-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.eu-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.eu-west-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.me-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.sa-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.us-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.us-east-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.us-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.vfs.cloud9.us-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.cn-north-1.amazonaws.com.cn
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.cn-northwest-1.amazonaws.com.cn
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.af-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.ap-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.ap-northeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.ap-northeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.ap-northeast-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.ap-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.ap-southeast-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.ap-southeast-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.ca-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.eu-central-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.eu-north-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.eu-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.eu-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.eu-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.eu-west-3.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.me-south-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.sa-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.us-east-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.us-east-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.us-west-1.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
dig +short TXT _psl.webview-assets.cloud9.us-west-2.amazonaws.com
"https://github.com/publicsuffix/list/pull/1403"
```

make test
=========

`make test` pass all tests and pulls the most recent revision on [`libpsl`](https://github.com/rockdaboot/libpsl)

https://pastebin.com/Z3nmy3Gw

### CODE REVIEW

**Comment by aprex** [comment]
`make test` currently is failing for long domain entries due to https://github.com/rockdaboot/libpsl/issues/172

**Comment by aprex** [comment]
All action items are done, PR is ready for review.

**Review by sleevi — CHANGES_REQUESTED** [review]
@aprex Please escalate with your Amazon colleagues that it's unlikely for the PSL to be able to support continued Amazon additions. Please see the discussions in https://github.com/publicsuffix/list/pull/1422 and https://github.com/publicsuffix/list/pull/1417

**Comment by dnsguru** [comment]
Is this PR still needed - has [Sleevi's Request](https://github.com/publicsuffix/list/pull/1403#pullrequestreview-781371451) been addressed to make this request as modest in size as possible?

**Comment by aprex** [comment]
Hi @dnsguru. Yes, this PR is still needed, we are discussing possible mitigation on our service side. As Cloud9 is regionalised AWS service, it requires extra work for us to change our approach for service URLs.
And due to the fact that PSL entries format allows wildcards only at the start of domain, we can't compress our entry to few lines right now.

**Comment by dnsguru** [comment]
Closing this, superceded by #1590

**Pull request closed without merging**
