### PR TITLE
Add clothesmentor.com

### PR DESCRIPTION
**Pull request by NTYFranchiseCo**
Add Clothes Mentor

Add clothesmentor.com to PSL

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://clothesmentor.com

Clothes Mentor is a franchise resale retail fashion boutique. Stores under the Clothes Mentor are sold by the franchisor NTY Franchise Co., LLC.

My name is Sean Marrs and I am the IT Administrator for NTY Franchise Co., LLC. 

Reason for PSL Inclusion
====
We would like to be added to the list to provide security for our franchisees and their websites. 

While we own and maintain clothesmentor.com, each of our franchise locations have a website as a subdomain of clothesmentor.com. (ex. sanduskyoh.clothesmentor.com). These subdomain sites are also their ecommerce sites hosted by Shopify. We would like to provide our franchisees and their customers a secure ecommerce environment.

Clothesmentor.com is registered with GoDaddy.com and is good until 2024. 

DNS Verification via dig
=======

```
dig +short TXT _psl.clothesmentor.com
"https://github.com/publicsuffix/list/pull/1261"
```

make test
=========
I tried to run it but I keep getting error 127, autoreconf not found. 
Assistance would be appreciated.

### CODE REVIEW

**Comment by dnsguru** [comment]
It looks like this is mid-stream in being submitted, but please do make sure that the rationale gets completed, as it appears to have cut off mid submission, and does not contain sufficient substance to allow this proceed

**Comment by NTYFranchiseCo** [comment]
Yes, I'm in the process. I had to leave my computer abruptly and saved a draft pull request that I hope to finish shortly.

Sean Marrs | IT/Tech Administrator

NTY Franchise Company
13801 Industrial Park Blvd.
Plymouth, MN 55441

Email: ***@***.***
Direct: 952-283-3421

________________________________

**Comment by dnsguru** [comment]
Please tick the boxes that are true below:

__Submitter affirms the following:__ 
  * [ ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [ ] This request was _not_ submitted with the objective of working around other third party limits
  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

**Comment by n8schloss** [comment]
@NTYFranchiseCo, if this is related to iOS 14 and Facebook at all please see the information below:

Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift.

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
@NTYFranchiseCo please have a look at this PR and the comment flow and let us know if you would like to proceed with this request.  If so, there are some questions that likely need some answers.  If you have decided not to proceed, we'll go ahead and close this PR if we do not hear back in the next few weeks.

**Comment by NTYFranchiseCo** [comment]
We will look them over and respond. Thanks!

Sean Marrs | IT/Tech Administrator

NTY Franchise Company<http://www.ntyfranchise.com/>
13801 Industrial Park Blvd.
Plymouth, MN 55441

Email: ***@***.***
Direct:  952-283-3421
***@***.***D76119.2C938120]

**Comment by dnsguru** [comment]
No update since June 14; closing this - re-open or reference this PR # if creating new Pull Request

**Pull request closed without merging**
