### PR TITLE
Add DDNS domain zones for public service `alviy.com`

### PR DESCRIPTION
**Pull request by alviy**
Public available domains in DDNS service

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://alviy.com (Old name was dyn.namn.ru)

Alviy is a free Dinamic DNS provider accessible to everyone.
We provide dyndns subdomain 4nmn.com, didns.ru, dynnamn.ru to our users, allowing them to  bypass some ISPs dynamic IP and to configure DNS entries automatically and to self-host some services without the need of buying a personnal domain.

Reason for PSL Inclusion
====

Currently we have over 5000 users and some of them use 3rd level hostnames as own primary domain. Submission to PSL allow to get LetsEncrypt TSL certificates and normal managing cookies.

DNS Verification via dig
=======
(upd)
dig +short TXT _psl.4nmn.com
`https://github.com/publicsuffix/list/pull/1502`
dig +short TXT _psl.didns.ru
`https://github.com/publicsuffix/list/pull/1502`
dig +short TXT _psl.dynnamn.ru
`https://github.com/publicsuffix/list/pull/1502`

make test
=========
cd linter;                                \
  ./pslint_selftest.sh;                     \
  ./pslint.py ../public_suffix_list.dat;
test_allowedchars: OK
test_dots: OK
test_duplicate: OK
test_exception: OK
test_NFKC: OK
test_punycode: OK
test_section1: OK
test_section2: OK
test_section3: OK
test_section4: OK
test_spaces: OK
test_wildcard: OK
. . .
`# TOTAL: 5`
`# PASS:  5`
`# SKIP:  0`
`# XFAIL: 0`
`# FAIL:  0`
`# XPASS: 0`
`# ERROR: 0`

Making check in msvc

### CODE REVIEW

**Comment by alviy** [comment]
Added TXT records

**Comment by alviy** [comment]
fixed test run

**Comment by alviy** [comment]
Hi @dnsguru, I feel awkward to remind but can I provide you with any additional information to prоcess request? I appreciate you work.

**Comment by alviy** [comment]
@dnsguru how can I help with this PR?

**Comment by alviy** [comment]
It is very discouraging when the request is not accepted and there are no comments.

**Comment by dnsguru** [comment]
You are heard.

Please hear ... The bank wants me to pay mortgage, so that i do not get
evicted, so i am not sure how to leverage your comment with them vs paying
them.   As an unpaid volunteer on PSL I have instead been focusing on paid
work, which allows me to pay the rent.

**Comment by dnsguru** [comment]
I found some unpaid volunteer cycles today to work on this, and it was found that 1 of the 3 submitted domain names did not work in the validation of TXT records, which is holding up this PR.

When any fail, we move to the next PR and then circle back to them at the next available volunteer time / opportunity.

In reviewing the one domain name that failed, it was present on virustotal.com, which has elevated a community pressure to screen names being included.   This prompted the creation of a discussion about this in issue #1699 - which is in discussion.

**Comment by simon-friedberger** [comment]
I would suggest we close this due to inactivity. @weppos @dnsguru wdyt?

**Comment by dnsguru** [comment]
Sounds good.

**Pull request closed without merging**
