### PR TITLE
UPDATE HOSTBIP DOMAIN NAMES (2024) +biz.ng +plc.ng -edu.scot -sch.so

### PR DESCRIPTION
**Pull request by hostbip**
### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
 
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

'HostBip' is a 'PDNR' (Private Domain Name Registry), allowing 3rd parties to register domain names in a variety of domain name extensions/suffixes. This pull request adds or updates the entries for a number of domain extensions that we operate, and disclaims a number of domain names we are no longer operating registry services for.

Organization Website: https://dash.hostbip.com/

Reason for PSL Inclusion
====

'HostBip' has an existing section in the 'Public Suffix List', and is updating the section to include additional domain extensions/suffixes in its portfolio and removing edu.scot and sch.so domain from the list.

This request is seeking to add these to the PSL so the individuals/institutions operating under these suffixes can gain access to services such as Let's Encrypt, Cloudflare and that other third party systems may better be able to identify the level at which the personal/private name has been registered.

Number of users this request is being made to serve: we are expecting to serve over 3000 public and private limited liability companies in the Nigerian marketplace.

DNS Verification via dig
=======

```
dig +short TXT _psl.biz.ng
"https://github.com/publicsuffix/list/pull/2127"
```
```
dig +short TXT _psl.plc.ng
"https://github.com/publicsuffix/list/pull/2127"
```

```
dig +short TXT _psl.co.biz.ng
"https://github.com/publicsuffix/list/pull/2127"
```
```
dig +short TXT _psl.dl.biz.ng
"https://github.com/publicsuffix/list/pull/2127"
```
```
dig +short TXT _psl.go.biz.ng
"https://github.com/publicsuffix/list/pull/2127"
```
```
dig +short TXT _psl.lg.biz.ng
"https://github.com/publicsuffix/list/pull/2127"
```
```
dig +short TXT _psl.on.biz.ng
"https://github.com/publicsuffix/list/pull/2127"
```

Results of Syntax Checker (`make test`)
=========

```
I've run make test, and it reports that all tests pass.
```

### CODE REVIEW

**Comment by wdhdev** [comment]
* [ ] Expiration (Note: Must STAY >2y at all times)
  * [ ] biz.ng expires 2026-11-17
  * [ ] plc.ng expires 2026-11-15
* [x] DNS _psl entries (Note: Must STAY in place)
  * [x] `_psl.biz.ng`
  * [x] `_psl.plc.ng`
* [x] Tests pass
* [x] Sorting
* [ ] Reasoning/Organization description
* [x] Non-personal email address

---

Notes:
* 300 users is not a large enough project in order to be added to the PSL.

> Projects that are smaller in scale or are temporary or seasonal in nature will likely be declined. Examples of this might be private-use, sandbox, test, lab, beta, or other exploratory nature changes or requets. It should be expected that despite whatever site or service referred a requestor to seek addition of their domain(s) to the list, projects not serving more then thousands of users are quite likely to be declined.

* You say your sole reason for inclusion is to get around Cloudflare and Letsencrypt rate limits, which is not allowed according to our guidelines:

> We do not accept entries that have the objective of getting around limitations that have been put in place by a vendor to protect internet users. The PSL is not a 'workaround', and Pull Requests that appear to be doing this should expect to be declined. Be thorough and candid with the rationale furnished with the request.

**Comment by hostbip** [comment]
@wdhdev it is a typographical error; it was intended to be 3000 business and corporate organizations.

**Comment by wdhdev** [comment]
> @wdhdev it is a typographical error; it was intended to be 3000 business and corporate organizations; as we should have above 300 businesses in each state. Allow me correct this shortly.

Are you able to show evidence of this usage?

> Both domain names are above 2 years; This is September 2024, while the domains should expire by November 2026. (making it 2 years and 2 months)

Whoops, my bad. I've fixed this.

> Lastly, we create sub-domain name for our users; who we require to enjoy the same privileges as a regular domain name.

This is not enough reasoning, like what specific features? Cookie separation, etc.

**Comment by hostbip** [comment]
@wdhdev The primary reason for adding to PSL is cookie separation for each domain, and determining wildcard subdomains such as *.zeefarms.de.biz.ng for cookie separation. Also, we want cloudflare and other third party systems to be able to identify the level for each domain name.

For the users, we have below 500 total users for these domain names as its closed to prevent spam. We are following extant regulations as we had issues of fraudulent registrations and abuse case - registration is only open to businesses registered in Nigeria that we must now verify.

We will be grateful if we can proceed to update the Hostbip section.

**Comment by simon-friedberger** [comment]
@hostbip I think this would be acceptable without the geographic subdomains. 300 businesses per entry is too low and generally businesses prefer using more generic names instead of geo-coded ones anyway.

And if you have 3000 users across your currently proposed 40 entries that's only 75 users per entry.

**Comment by hostbip** [comment]
@simon-friedberger This was placed into consideration. There are businesses that do not fall into the requirements of BIZ.NG; it is our intent to accommodate this category of business. Businesses under .BIZ.NG must be registered BUSINESS NAMES with the Corporate Affairs Commission. There are other agencies that registered Micro Small Medium Enterprises such as SMEDAN (https://smedan.gov.ng) - and this is on a state by state basis.

We will do our best to maintain our section better, and ensure its always in compliance. A reason we are moving to concentrate on a single marketplace.

Kindly consider.

**Comment by hostbip** [comment]
I am grateful for the feedback. Majority of the records is now removed. We request to proceed with `co.biz.ng`, `de.biz.ng`, `go.biz.ng`, `lg.biz.ng`, `on.biz.ng`. We will review in the near future and add more of the needed records on a case by case basis.

**Comment by groundcat** [comment]
Do you have information about the use of biz.ng and plc.ng on the Hostbip website or other reliable sources?

- The Hostbip.org website in your comment section at https://www.hostbip.com is not working. It is displaying a LiteSpeed Web Server default page with no content except a `cgi-bin` folder in the index.
- The website you listed in your PR https://dash.hostbip.com/ is showing only a login page.
  
If the website information has changed, please update the comments as well to reflect a functioning organization website.

> we have below 500 total users for these domain names

Based on the CT reports ([biz.ng](https://crt.sh/?q=biz.ng), [plc.ng](https://crt.sh/?q=plc.ng)) and search engine results ([biz.ng](https://www.google.com/search?q=site%3Abiz.ng&ie=UTF-8), [plc.ng](https://www.google.com/search?q=site%3Aplc.ng&ie=UTF-8)), there is minimal evidence of usage for both domains. Is there a reason why we don't observe much usage or why the clients are not using CT?

> it was intended to be 3000 business and corporate organizations; as we should have above 300 businesses in each state.

It would be appreciated if you could provide some level of evidence or a basis for calculating this number.

The other existing entries under Hostbip are in a similar condition, with few subdomains observed through search engines:

```
orx.biz
biz.gl
col.ng
firm.ng
gen.ng
ltd.ng
ngo.ng
```

**Comment by simon-friedberger** [comment]
```
dig +short TXT _psl.lg.biz.ng
"https://github.com/publicsuffix/list/pull/2127"
```
This is inaccurate, that entry is missing afaict.

**Comment by hostbip** [comment]
@simon-friedberger Please the DNS entry in now corrected.

@groundcat I have attached a database table summary for the registered subdomains across our supported domain names. The website hostbip.com is under maintenance, and will be up in the coming days. 

image

**Comment by groundcat** [comment]
@hostbip Hello, would you please fix the `firm.ng` domain's DNS? It has been showing a SERVFAIL error for over a month, as noted in #2172 We need `_psl.firm.ng` to remain active and consistently point to your PR's URL to ensure your entry stays in the PSL. Same applies for other entries in your submission. Thank you!

**Comment by hostbip** [comment]
Thank you for the notice. This is now corrected.

**Pull request merged**
