### PR TITLE
Add afn.space

### PR DESCRIPTION
**Pull request by kevinburke**
There's nothing currently there, but I plan to offer a functions-as-a-service
product there soon. A WHOIS should show that Kevin Burke is the registrar.

### CODE REVIEW

**Comment by kevinburke** [comment]
I tried to find more documentation on the DNS records for verification and couldn't find anything. I ended up borrowing this from another pull request. I hope this is right; if not please let me know and I'm happy to fix.

```
$ dig TXT _psl.afn.space

; <<>> DiG 9.10.4-P1 <<>> TXT _psl.afn.space
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44249
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_psl.afn.space.			IN	TXT

;; ANSWER SECTION:
_psl.afn.space.		299	IN	TXT	"https://github.com/publicsuffix/list/pull/265"

;; Query time: 68 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jul 13 20:59:07 PDT 2016
;; MSG SIZE  rcvd: 101
```

**Comment by kevinburke** [comment]
(I can put whatever content you like at that domain, right now there's nothing there, I wanted to get this PR up early in case it takes a while)

**Comment by sleevi** [comment]
https://github.com/publicsuffix/list/wiki/Guidelines has details about how validation is performed

**Comment by sleevi** [comment]
Could you expand a bit more on what you mean by "functions as a service" and how that relates to what the Public Suffix is for (as per https://www.publicsuffix.org )

**Comment by sleevi** [comment]
Closing this due to no feedback.

**Pull request closed without merging**
