### PR TITLE
Add Handshake zones

### PR DESCRIPTION
**Pull request by mikedamm**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

Organization Website: https://handshake.org/

Handshake is a decentralized, permissionless naming protocol compatible with DNS where every peer is validating and in charge of managing the root zone with the goal of creating an alternative to existing Certificate Authorities. Its purpose is not to replace the DNS protocol, but to replace the root zone file and the root servers with a public commons. The Handshake protocol maintains the root zone file in a decentralized manner, making the root zone uncensorable, permissionless, and free of gatekeepers.

I am a developer for this project.

Reason for PSL Inclusion
====

Names registered in Handshake are reflected in to the hs.zone and hs.run zones, allowing clients not running Handshake to look up these names. Because multiple parties can indirectly register names under these zones, cookie isolation is highly desirable.

DNS Verification via dig
=======

```
bash-3.2$ dig +short IN TXT _psl.hs.zone.
"https://github.com/publicsuffix/list/issues/796"
bash-3.2$ dig +short IN TXT _psl.hs.run.
"https://github.com/publicsuffix/list/issues/796"
```

make test
=========

Tested. https://pastebin.com/raw/iHMUfmMJ

```
============================================================================
Testsuite summary for libpsl 0.20.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================```

### CODE REVIEW

**Comment by sleevi** [comment]
From looking at the protocol specification, I don’t believe this will do
what is desired. Further, it seems this is functionally in conflict with
ICP-3, and thus that seems grounds to reject this PR.

**Comment by mikedamm** [comment]
> From looking at the protocol specification, I don’t believe this will do what is desired.

Can you elaborate on your concerns here? It is fully functional and tested, however the hs.zone transitional zone is not documented yet.

> Further, it seems this is functionally in conflict with ICP-3, and thus that seems grounds to reject this PR.

ICP-3 is not relevant here, as no new TLDs are being introduced in to the PSL ([.zone](https://icannwiki.org/.zone) and [.run](https://icannwiki.org/.run) are ICANN delegated TLDs). The functionality here is exactly the same as the [domains administered by CentralNic](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat#L10889), just with a blockchain based backend.

Hopefully that clears up the confusion.

**Comment by mikedamm** [comment]
@sleevi could you take a look at my previous comments and merge this?  If you have any further questions I'd be happy to explain.

**Comment by mikedamm** [comment]
@sleevi Anything else you need to merge this? I'd like to get this wrapped up and off my plate.

**Comment by groundcat** [comment]
Hello @mikedamm , it seems that the project associated with your domain, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. 

```
hs.zone
hs.run
```

If the handshake transitional zone service on these domains has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, **ensure that the required `_psl` TXT record is maintained**, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Pull request merged**
