### PR TITLE
Add sandcats.io dynamic DNS service as public suffix

### PR DESCRIPTION
**Pull request by paulproteus**
I'm on the sandstorm.io team, where we maintain a public dynamic DNS service at sandcats.io.

@kentonv is the listed domain owner. Let me know what we should do to fully confirm the domain name to your satisfaction.

### CODE REVIEW

**Comment by paulproteus** [comment]
Feel free to verify this with me at asheesh@sandstorm.io or with Kenton Varda kenton@sandstorm.io . If you need us to disable "protected WHOIS", let us know and Kenton will be able to say if that's possible.

Thanks as always for the security work you all do for the web as a whole!

**Comment by gerv** [comment]
Email sent to kenton@sandstorm.io.

**Comment by gerv** [comment]
Validated. Please can you resolve conflicts, and then ping me to merge?

**Comment by paulproteus** [comment]
Thanks @gerv - I've rebased this now. Thanks for your quick handling of this!

**Comment by paulproteus** [comment]
I just wanted to say:

Thank you!

**Pull request merged**
