### PR TITLE
adds protonet.io to the list

### PR DESCRIPTION
**Pull request by martindehh**
We, Protonet Inc (https://protonet.com), provide a dynamic DNS service for our customers (under the domain protonet.io)
Allowing our users to register SSL Certificates using Let's Encrypt is a huge benefit for the security of our users.

### CODE REVIEW

**Comment by martindehh** [comment]
added the DNS TXT Record for _psl.protonet.io to point here.

**Comment by sleevi** [comment]
Please update this PR to adhere to the Guidelines - https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by martindehh** [comment]
Sorry  @sleevi I have put the entry at the (hopefully) position based on our company name.
Also I created the mail address admin@protonet.io so this is all coming from one domain now.
I hope this is sufficient now. Please be so kind to tell me what I would have to change if it is not right now.
Thanks for your time and sorry for my malformed request.

**Comment by martindehh** [comment]
Sorry  @sleevi I have put the entry at the (hopefully) position based on our company name.
Also I created the mail address admin@protonet.io so this is all coming from one domain now.
I hope this is sufficient now. Please be so kind to tell me what I would have to change if it is not right now.
Thanks for your time and sorry for my malformed request.

**Comment by martindehh** [comment]
Hey @sleevi please tell me if I need to do more or something different for the request to succeed.
In the meantime I will be patiently waiting.

**Comment by groundcat** [comment]
Hello @martindehh

A few things came up while reviewing `protonet.io`, which was added in 2016 for Protonet's dynamic-DNS service:

- The current registration expires on 2026-08-05.
- The suffix itself resolves, but its HTTPS site could not be verified because its certificate chain could not be validated; its DNS delegation also appears consistent with domain parking.
- Public reputation data reports 3 malicious and 1 suspicious analysis results for the suffix.

Is this entry still needed and in active use for the original dynamic-DNS use case, and is the contact information on file still current? If we don't hear back, the maintainers may consider proposing removal of the entry in a future review.

**Pull request merged**
