### PR TITLE
added Storebase.store

### PR DESCRIPTION
**Pull request by tschirmer**
* [ x ] Description of Organization
* [ x ] Reason for PSL Inclusion
* [ x ] DNS verification via dig
* [ x ] Run Syntax Checker (make test)

* [ x ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://storebase.io

Storebase is an Ecommerce SaaS. We provide merchants the tools to sell their products online. 

Reason for PSL Inclusion
====

We provision store backends on *.storebase.store, and seperate out our admin login to the frontend domain selling the products online. We're looking to provide cookie protection to ensure CSRF attacks don't occur between the backends of storebase stores.

DNS Verification via dig
=======

```
dig +short TXT _psl.storebase.store
"https://github.com/publicsuffix/list/pull/1291"
```

make test
=========
```
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-public
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-registrable-domain
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by dnsguru** [comment]
#1245

**Comment by bedfordsean** [comment]
Hi @tschirmer, please can you provide some examples ofsubdomains hosted under storebase.store and a more detailed description of how these backends are used in practice from a web browsing context? I can't find any from doing a Google search so presume these are accessible primarily by business owners?

**Comment by tschirmer** [comment]
hey @bedfordsean. yes, the backend are for store owners. We disable google bot crawling and  indexing on them. It's the backend of the store that allows store owners to edit products, change website style, payment methods, shipping methods and contains payment and finanical data for orders that have been made.

we also use that domain to connect up api services, to interact with Point of Sale, Warehousing systems and accounting syncs.

**Comment by bedfordsean** [comment]
Thanks for the clarity. Do you allow those store owners to do back-end analytics or queries linked to the Facebook Pixel, or is this disconnected entirely from the mentioned issue https://github.com/publicsuffix/list/issues/1245 ?

**Comment by tschirmer** [comment]
@bedfordsean This isn't related to Facebook Pixel. Only a few of our consumers use that, and Pixel is only active on the frontend, not the backend.

**Comment by bedfordsean** [comment]
Thanks for clarifying @tschirmer!

**Comment by dnsguru** [comment]
@tschirmer thank you for enduring our questions and clarifications on this - as indicated in the #1245, there is an objective of helping validate that the requested changes won't break cookies on root domains for the requestor, and we're experiencing a bit heavier that typical flow of requests at the moment for the same reasons articulated in #1245.

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Pull request merged**
