### PR TITLE
Added e4.cz to E4YOU, spol. s.r.o.

### PR DESCRIPTION
**Pull request by e4you**
Hi,

we would like to add our e4.cz domain to Public Suffixes list. If any proves of domain ownership etc. required, please let us know.

Thank you!

### CODE REVIEW

**Comment by sleevi** [comment]
Please see [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) for how to format this pull request and how to validate it.

**Comment by e4you** [comment]
Added DNS TXT record for authentication.

Reason to add the domain: We use 3rd level domains for our customers applications when they don't have own one or for some reason don't want to use it for the application. Thereforre there are many unrelated websites running with e4.cz suffix and the e4.cz domain itself hosts no website.

**Comment by sleevi** [comment]
- Please update the header to include a space before and after the colon separating the company name and address.
- Please resolve the conflicts with master (e.g. rebase)
- Please remove the date from your submission

These are all covered in the aforementioned Guidelines

**Comment by e4you** [comment]
I submitted the changes as requested. Thank you for pointing out the problems.

**Comment by sleevi** [comment]
I'm not sure what you've done with this PR, but it now includes a massive number of unrelated changes. I'm unable to even advise on how to resolve this. As you can see, this PR now encompasses 94 commits and 34 files being changed.

I created https://github.com/publicsuffix/list/pull/231 as best I can tell from this PR. If you have further amendments to make, please submit a new PR based on the master and following the Guidelines.

**Pull request closed without merging**
