### PR TITLE
remove `blogspot.mr`

### PR DESCRIPTION
**Pull request by wdhdev**
## blogspot.mr
I'm not sure where this was originally added in, possibly added pre-GitHub. 

Pretty simple reason for removal; the domain name is expired.

When attempting to lookup the domain via WHOIS, the server returns:
```
$ whois blogspot.mr
Server can't process your request at the moment.
```
And to clarify, I don't believe this is a server issue as looking up, for example, `nic.mr` works perfectly fine and returns the WHOIS data.

When attempting to lookup NS records the server returns `NXDOMAIN`.

### CODE REVIEW

**Comment by wdhdev** [comment]
Yeah, I think it's possible they've decommissioned these ccTLDs. @simon-friedberger @dnsguru What do you guys think?

**Comment by simon-friedberger** [comment]
I asked about this here: https://github.com/publicsuffix/list/pull/1947#issuecomment-2092799159
@svipul Is there somebody whom you could ping?

**Comment by wdhdev** [comment]
Some other reasons worth mentioning for removal:
- No websites are returned when searching `site:blogspot.mr` or `site:blogspot.td` on Google, suggesting the domain is not used at all.
- No SSLs were found for `blogspot.mr`: https://crt.sh/?q=blogspot.mr
- SSLs were found for `blogspot.td`, however they are all expired and none have been created since `2021-09-24`: https://crt.sh/?q=blogspot.td

I think it would be safe to remove these in addition with other reasons mentioned in this PR.

**Comment by wdhdev** [comment]
@simon-friedberger I believe these are safe to remove as these 2 domains have expired, and as for the other Blogspot domains listed in the section it might be worth opening an issue and possibly emailing the email address Google has listed for contact.

**Comment by groundcat** [comment]
I tried to email `Public Suffix Editors <public-suffix-editors@google.com>` but it was bounced:

```
We're writing to let you know that the group you tried to contact (public-suffix-editors) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

* You might have spelled or formatted the group name incorrectly.
* The owner of the group may have removed this group.
* You may need to join the group before receiving permission to post.
* This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/google.com/bin/topic.py?topic=25838.

Thanks,

google.com admins
```

**Comment by simon-friedberger** [comment]
@krgovind Do you have a suggestion who to reach out to?

**Comment by wdhdev** [comment]
According to the WHOIS server on the registry website (https://whois.nic.mr), `blogspot.mr` is not registered, so that can be removed.

According to https://who.is/whois/blogspot.td, `blogspot.td` is registered as of `2023-01-16`, so maybe when this PR was opened the WHOIS server was down or something as it is a registered domain. `blogspot.td` is in fact registered to Google according to WHOIS data, therefore I will remove it from this PR, however as for `blogspot.mr` that should still be removed.

**Pull request merged**
