### PR TITLE
[WIP] Adding HATCH Studio domains

### PR DESCRIPTION
**Pull request by henvic**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website:  https://hatchstudio.co/

I'm a Senior Software Engineer at HATCH Studio, a company part of PVH – the owner of brands Tommy Hilfiger and Calvin Klein.

Our product is a Digital Showroom for fashion brands.

Reason for PSL Inclusion
====

**cloud.hatchstudio.co:**

We have different environments on `<example>.cloud.hatchstudio.co` and we want to avoid the risk of supercookies.
Later, we'll also have different multi-tenancy with more environments.

Examples:

```
prod.cloud.hatchstudio.co
dev.cloud.hatchstudio.co
```

These environments should be separated.

**hatchstudio.co**
Similar to the case above, but used for other internal/external services with diverse levels of security requirements.

Examples:

```
ds.hatchstudio.co
jobs.hatchstudio.co
```

We are an established company and intend to keep the domains registered for the foreseeable future.

DNS Verification via dig
=======

```
$ dig +short TXT _psl.hatchstudio.co
"https://github.com/publicsuffix/list/pull/1279"

$ dig +short TXT _psl.cloud.hatchstudio.co
"https://github.com/publicsuffix/list/pull/1279"
```

make test
=========

OK

### CODE REVIEW

**Comment by henvic** [comment]
I've asked our administrative contact to renew the domain for at least two years as it's almost due to the expiration date and will get back here once it's confirmed.

**Comment by dnsguru** [comment]
@henvic We can't review draft pr - is this an abandoned request? 

Please also read #1245

**Comment by henvic** [comment]
Hello @dnsguru,

Sorry about this. I missed the rule about the minimum remaining duration of domain registration. I moved this to draft to avoid someone reviewing it indeed (waiting for the domain to be renewed). If you prefer, let's close this, and I may reopen once I have got this requirement solved on my end.

Apologies for the inconvenience.

**Comment by dnsguru** [comment]
ok @henvic. Closing.  If/when you re-open, please refer back to this PR number.

**Pull request closed without merging**
