### PR TITLE
Add jotelulu.cloud

### PR DESCRIPTION
**Pull request by danielfh**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://jotelulu.com

Jotelulu S.L. is a cloud provider that offers SME-oriented services. We allow our users to work from anywhere without having to deal with a complicated interface. 

Reason for PSL Inclusion
====

We assign subdomains under the jotelulu.cloud domain to our clients (for example, customer1.jotelulu.cloud, customer2.jotelulu.cloud) to access their environments. There they can deploy any application.

We want to protect the subdomains under jotelulu.cloud from the exchange of cookies between subdomains.

The registration term for 'jotelulu.cloud' is greater than 2 years, and it will be extended automatically.

```
whois jotelulu.cloud | grep "Registry Expiry"
Registry Expiry Date: 2026-06-08T09:28:18Z
```

DNS Verification via dig
=======

```
dig +short TXT _psl.jotelulu.cloud
"https://github.com/publicsuffix/list/pull/1330"
```

make test
=========

```
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

### CODE REVIEW

**Review by dnsguru — CHANGES_REQUESTED** [review]
Hello - this would not be accepted in the ICANN section, please move chage to the PRIVATE section, and locate it alphabetically sorted by the name of your organization.

**Comment by danielfh** [comment]
> Hello - this would not be accepted in the ICANN section, please move chage to the PRIVATE section, and locate it alphabetically sorted by the name of your organization.

Fixed! :)

**Comment by dnsguru** [comment]
Looks like you moved it to the appropriate place in the file.   

Can you please read #1245 and the contributing guidelines (link in footer of #1330), Please identify that this is / is not related to #1245, and that the submission is in conformance with the guidelines.

**Comment by dnsguru** [comment]
@danielfh can you please state clearly here that this request is/is not for working around the IOS / Facebook issue?

**Comment by danielfh** [comment]
> @danielfh can you please state clearly here that this request is/is not for working around the IOS / Facebook issue?

Our aim is to increase the safety of our customers, this request is not related to any IOS / Facebook issue.

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Pull request merged**
