### PR TITLE
Update pull_request_template.md to ask for related issue or PR numbers

### PR DESCRIPTION
**Pull request by dnsguru**
Added request for submitting party to include historic Issue # or PR # to address issue #1027

* [x] Description of Organization
* [ ] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by dnsguru** [comment]
Fast-follow to #1109 in order to address #1027 (request for submitters to include historic Issue/PR)

**Comment by fsodic** [comment]
@sleevi & @dnsguru 
I completely disagree. Because it means we have to register the domain for the next 2 years which may add to the costs that are incurred for 1 year of financial statements if from an organization that already has a legal entity.
It might seem okay if the organization is large.
But think again if these organizations only target the local market in their respective countries.
So I think it makes more sense when the domain registered is at least 2 years old from the date of the PR request and not 2 years left since the PR request.
So we know whether the domain is well controlled and not all domains can immediately ask for PR for this publicsuffix.

**Comment by dnsguru** [comment]
The discussion was really amongst the core maintainers on how to address
the change as it is part of addressing expired or expiring names as a
general rule and not punitive response to the PR that included the expired
names.  That was more a catalyst to take a long-deferred action which was
to add the renewal term requirements.

The disagreement is noted.  It is understandable to seek to save money, but
the renewal terms serve to keep things efficient and protect the submitting
party while maintaining the integrity of this list.

If a name cannot be maintained with ample registration term, it really does
not belong on the list and should not get submitted.

What we often face is that submissions are 'set and forget' until a change
is needed from the submitting party, but mostly folks get what they want
and leave, and this causes some debris to clean up when renewals don't
occur.

Renewal expenses are what they are, and dodging the costs of maintaining
the submitted names pushes burden onto the volunteers of this project to
address the issues of expired names being on the list.  The objective is to
maintain quality and reliable listings and resourcing is such that dealing
with expired names (especially in new submissions) wastes volunteer time.

Volunteers are maintaining the public suffix list. Wasting their time is a
cost as well, which should not be considered to have a value of zero.
There is no entitlement to being listed that should be expected by any
party seeking entries within the private section, and requests should be
modest in nature and conform in respect of this being a voluntary global
resource.  We also see that the file size growing can introduce bandwidth
and scaling issues, which modesty of requests can help, but also
housekeeping of old records will aid in addressing.

Because the volunteer time gets wasted removing expired names or watching
for them, those maintaining the project candidly do not, but field reports
from new registrants of names.  Out of necessity we will at some point have
some form of automation that reviews expiry dates and make removals of
domains or sections.  These will depend upon expiry horizons beyond at
least a year, so the objective in entries having renewal obligations is
really a safety net for the submitting party, so they know the potential
consequences of non-renewal.

The objective is to maintain a quality list, through modest, efficient
means, and the renewal requirement aids in that objective.

**Comment by fsodic** [comment]
#1111 my PR not response bro?

**Comment by dnsguru** [comment]
Had to answer all this other distraction stuff first...

#lookingnow #volunteer #broke-a-f-due-to-pandemic
#volunteeringcompeteswithpaidgigs

**Comment by dnsguru** [comment]
@sleevi please approve and s/m

**Review by sleevi — APPROVED** [review]

**Pull request merged**
