### PR TITLE
Add verygood.site

### PR DESCRIPTION
**Pull request by VadimGuslistov**

### CODE REVIEW

**Comment by VadimGuslistov** [comment]
verygood.site is a website hosting platform

**Comment by weppos** [comment]
Hello @VadimGuslistov, the verygood.company site is currently not resolving and I was not able to validate the verygood.site domain.

It seems your product is still under development. I encourage you to contact us back when you have the product launched. Are you also aware of the implications of adding verygood.site to the PSL?

**Comment by VadimGuslistov** [comment]
Hello Simone, thanks for the quick response.

Yes, we aware of the implications of adding verygood.site to the PSL.

Yes, you are right that our product is still under development. But despite
this, I ask you to add verygood.site to the PSL because we can not finish
the product development without your help. When you do this we can
implement secure access to content in all domains of  new generation web
site hosting as a  verygood.site. At the moment this is not possible
because the Certificate Authority (https://letsencrypt.org/) considers
verygood.site as a website address on the Internet.

We need about one month after adding verygood.site to the PSL to provide
you with access to the closed beta service verygood.site.


--
Best regards,

Vadim Guslistov
Linkedin <https://www.linkedin.com/profile/view?id=49453523>

Tel: +7 (999) 20-VADIM
Tel: +1 (571) 20-VADIM
Skype: vadim.guslistov
E-mail: vadim@guslistov.com

**Comment by naox** [comment]
@weppos 
>>> Are you also aware of the implications of adding verygood.site to the PSL?

I'm considering that also for my domain so I'm interested, what implications are you talking about?

**Comment by VadimGuslistov** [comment]
I'm talking about situation when the  "supercookies" are not being set for high-level domain name suffixes.

**Comment by weppos** [comment]
It looks to me that the main motivation behind this (and probably other recent) requests is some kind of Let's Encrypt policy. For other reasons I was planning to have a look at Let's Encrypt, but I didn't have the chance yet.

Do you have any document or link I can check in order to better understand the usage that they are doing of the PSL and why you were requested to submit your domains?

**Comment by naox** [comment]
https://community.letsencrypt.org/t/beta-program-announcements/1631
```
The limit on Certificates/Domain is 5 certificates for a registered domain in a sliding window of 7 days. 
```
Supossigly they use publicsuffix for whitelist on this policy.
So basicly if your domain is not on publicsuffix you can't get more that 5 subdomains in that domain certified (in a 7 days) and thats quite a blocked because their certificates are issued with expiration date in 90 days.

**Comment by VadimGuslistov** [comment]
Yes, naox rights.

**Comment by VadimGuslistov** [comment]
Hello @weppos, what are you think about adding verygood.site to the PSL now?

**Comment by VadimGuslistov** [comment]
@weppos, we are waiting for one and a half months. Why?

**Comment by sleevi** [comment]
Can you please reformat this patch according to the Guidelines at https://github.com/publicsuffix/list/wiki/Guidelines 

This includes
* Sorting your entry so that it is sorted by company name (after UDR, before Yola)
* Including submission information
* Ensuring newlines before and after your entry

**Comment by sleevi** [comment]
Closing due to no response.

**Pull request closed without merging**
