### PR TITLE
Add ras.ru domains

### PR DESCRIPTION
**Pull request by rasnet**
The institutes of the Russian Academy of Sciences use a custom subdomains of **ras.ru**

### CODE REVIEW

**Comment by daftano** [comment]
Hi @rasnet. How are related the subdomains between each other?

**Comment by rasnet** [comment]
Hi @daftano. The Russian Academy of Sciences (ras.ru) comprises a large number of research institutions. Each research institute is provided with a subdomain, which they use on their own.

**Comment by daftano** [comment]
I saw you also set the TXT record
```
$ dig TXT _psl.ras.ru +short
"https://github.com/publicsuffix/list/pull/511"
```
Thank you.

Adding the domain of your main site can prevent navigation or access to it in PSL consumers clients; as those clients may not allow setting on suffices (e.g.: not allowing to set a cookie for 'com'), and some prevent navigation (e.g. not allowing navigation to 'com').
Currently your main site is available as http://ras.ru and some stuff (e.g. login and access to private areas) may stop working.

Can you confirm you still wish to be added?

**Comment by rasnet** [comment]
Hi @daftano 
We have a problem with www.ras.ru and ras.ru. I'll write as soon as the Department dealing with the problem will solve it.

**Comment by rasnet** [comment]
Hi @daftano

We have solved our problem. We are ready

**Pull request merged**
