### PR TITLE
update `.bj` 

### PR DESCRIPTION
**Pull request by aadehan**
### Checklist of required steps

* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [X] This request was _not_ submitted with the objective of working around other third-party limits

  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
JENY SAS is the registry of ccTld .bj  ( https://www.iana.org/domains/root/db/bj.html ). I work for them as a consultant.

Organization Website: http://www.nic.bj/

Reason for PSL Inclusion
====

Since several months, the list of .bj second level domains has been updated. some slds have been removed or converted to standard domains, such as gouv.bj. Many new slds have been created as well.

the accurate list of slds can be found at https://nic.bj/bj-suffixes.txt

DNS Verification via dig
=======
```
dig +short TXT _psl.africa.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.agro.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.architectes.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.assur.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.avocats.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.co.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.com.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.eco.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.econo.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.edu.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.info.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.loisirs.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.money.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.net.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.org.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.ote.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.resto.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.restaurant.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.tourism.bj
"https://github.com/publicsuffix/list/pull/1694"
```
```
dig +short TXT _psl.univ.bj
"https://github.com/publicsuffix/list/pull/1694"
```

We also set _psl.nic.bj, for additionnal verifications, just in case
```
dig +short TXT _psl.nic.bj
"https://github.com/publicsuffix/list/pull/1694"
```

Results of Syntax Checker (`make test`)
=========

```
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Top-Down from root, following ICP-3 - 
[IANA Root DB for .bj](https://www.iana.org/domains/root/db/bj.html) Lists nic.bj as the appropriate authority
[nic.bj SLD list furnished matches submitted patch](https://nic.bj/bj-suffixes.txt)
Noting Submitter has sorted this list per the guidelines in this PR  -  @aadehan Thank you.

```
>nslookup -type=txt _psl.nic.bj 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find _psl.nic.bj: NXDOMAIN
```

1 need a TXT in each affected zone rather than nic.bj with the PR URL
2 Lookup of NXDOMAIN on a public resolver (tried 1.1.1.1 or 8.8.8.8)  fails validation for nic.bj

**Comment by dnsguru** [comment]
Noting that this PR solves issue #1692 and rolls in the change proposed in #1693 to remove gouv.bj

**Comment by aadehan** [comment]
Hi @dnsguru 
thank you for your quick feedback on this PR, even if it was a draft and not yet submitted. the requested _psl records are now available for each sld, as well as the previously mentioned record, _psl.nic.bj.

**Comment by dnsguru** [comment]
CONFIRMED DNS ENTRIES IN PLACE - PR Validated / Verified to NIC
```
> dig +short TXT _psl.africa.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.agro.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.architectes.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.assur.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.avocats.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.co.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.com.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.eco.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.econo.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.edu.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.info.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.loisirs.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.money.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.net.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.org.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.ote.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.resto.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.restaurant.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.tourism.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
> dig +short TXT _psl.univ.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
```


```
 dig +short TXT _PSL.nic.bj. 8.8.8.8
"https://github.com/publicsuffix/list/pull/1694"
```

**Review by dnsguru — CHANGES_REQUESTED** [review]
One minor change please.

Instead of adding a new line for the bj-suffixes URL would you please instead remove the wikipedia, as it is an artifact of an import from 2008ish - the nic page should really be the authority and replace it...

so
// bj : https://en.wikipedia.org/wiki/.bj
// https://nic.bj/bj-suffixes.txt

becomes
// bj : https://nic.bj/bj-suffixes.txt

**Comment by aadehan** [comment]
> One minor change please.
> 
> Instead of adding a new line for the bj-suffixes URL would you please instead remove the wikipedia, as it is an artifact of an import from 2008ish - the nic page should really be the authority and replace it...
> 

Hi @dnsguru. 
The resquested change is done.
thx

**Review by dnsguru — APPROVED** [review]
- Formatted to guidelines
- Tests Pass
- DNS Validates
- IANA NIC Validated for ccTLD via DNS and following IANA->ccTLD->Subzones via web
- No conflict with base


APPROVED

**Pull request merged**
