### PR TITLE
Add xenapponazure.com to the PSL

### PR DESCRIPTION
**Pull request by alexstoddard**
Citrix is offering subdomains under xenapponazure.com which resolve to customer managed deployments of Citrix XenApp.

### CODE REVIEW

**Comment by gerv** [comment]
Hi Alex. Do you work for Citrix? Is there an official email address @ this domain or @citrix.com we can email to confirm the validity of this request?

**Comment by alexstoddard** [comment]
I do work for Citrix. Email is not currently set up for this particular domain, but a whois query will show prasanna.padmanabhan@citrix.com as the registrant contact. I submitted this pull request on his behalf and he will be able to confirm by email.

**Comment by alexstoddard** [comment]
Please let me know if there are any additional acceptance requirements. The registrant contact is awaiting a verification email.

**Comment by weppos** [comment]
Reviewed via email.

**Comment by dnsguru** [comment]
@alexstoddard DOMAIN NO LONGER REGISTERED; ENTRY WILL BE REMOVED

**Pull request merged**
