### PR TITLE
Add splitmetrics.com

### PR DESCRIPTION
**Pull request by jxcorra**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://splitmetrics.com

SplitMetrics is the comprehensive mobile A/B testing platform enabling validation of ideas, concepts, and features via fully transparent A/B tests for iOS and Android on the product, search, and category pages. Trusted by Google, Rovio, Wargaming, and other market leaders, SplitMetrics is the accelerator that helps reach new levels of profitability and app growth for small, mid, and enterprise-size businesses. 

We provide each client with a pre-made landing page (a website) that our system generates specifically for their app or game. This page has a unique URL, but the domain is the same for each client. This domain is owned by us - SplitMetrics Inc. 

Сonsidering the latest privacy policy updates, we want to offer our clients a unique subdomain that they could pick for their business. For example:
- Google has a bunch of apps such as Gmail, Google Maps. They can pick google.splitmetrics.com for all projects.
- Rovio (Angry Birds) has many mobile games. They can pick rovio.splitmetrics.com

Reason for PSL Inclusion
====

1. We wish to give ownership to our clients over the landing pages they use to a/b testing their mobile apps and games. All clients run experiments on our domain, but we want to provide each client with their unique subdomain. 
2. We want to continue isolating cookies between each client’s subdomain (and each test) because sharing cookies contradicts a/b testing nature and services we provide. 
3. We want to allow our clients to set aggregated measurements in Facebook Events Manager for their Facebook pixels for events that come from their subdomain that they choose on our platform (in accordance with Facebook's domain verification docs). 

DNS Verification via dig
=======

The referenced domain (splitmetrics.com) has been registered until 23 May 2022. We also commit to maintaining our domain’s registration every year.

```
dig TXT +short _psl.splitmetrics.com
"https://github.com/publicsuffix/list/pull/1336"
```

make test
=========

```
test_NFKC: OK
test_allowedchars: OK
test_dots: OK
test_duplicate: OK
test_exception: OK
test_punycode: OK
test_section1: OK
test_section2: OK
test_section3: OK
test_section4: OK
test_spaces: OK
test_wildcard: OK
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Please see #1245 as to why this is labelled wontfix

**Comment by n8schloss** [comment]
Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737  

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift. 

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
excellent @n8schloss - appreciate FB stepping up to remedy the thundering herd sent to the PSL for salvation without context.    closing this, reference this pr# should a new one be requested

**Comment by jxcorra** [comment]
@dnsguru, @n8schloss thank you so much for the updates and info provided!

**Pull request closed without merging**
