### PR TITLE
Add fh-muenster.io to PSL

### PR DESCRIPTION
**Pull request by senk**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://www.fh-muenster.de

We are the University of Applied Sciences Muenster. I am the responsible IT Administrator.

Reason for PSL Inclusion
====

We want to host Gitlab Pages under this subdomain and according to cookie security best practices it is advisable to be included in the PSL

DNS Verification via dig
=======

```
dig +short TXT _psl.fh-muenster.io
"https://github.com/publicsuffix/list/pull/1134"
```
make test
=========
make test run successfully

### CODE REVIEW

**Comment by TimWolla** [comment]
>     * [x]  Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

This is not the case according to whois:

```
$ whois fh-muenster.io |grep Expiry
Registry Expiry Date: 2021-10-26T16:22:06Z
```

**Comment by senk** [comment]
Unfortunately we are not able to register the domain for more than one year with our registrar.

**Comment by dnsguru** [comment]
> Unfortunately we are not able to register the domain for more than one year in advance with our registrar. But we will extend it beyond 2 years

Perfect. please comment once that is completed so we can proceed

**Review by dnsguru — APPROVED** [review]
- DNS validates
- Tests Pass
- No Conflict With Base
- Rationale Complete
- Expiry Date 1 year but attestation of renewal to extend

**APPROVED**, pending renewal extension

**Comment by senk** [comment]
Sorry for the confusion. Our registrar does not allow extension of 2 years. It will renew yearly for one more year.

**Comment by senk** [comment]
@dnsguru is an exeption possible or do we need to change registrar to register for more than 1 year in advance?

**Comment by sleevi** [comment]
> @dnsguru is an exeption possible or do we need to change registrar to register for more than 1 year in advance?

You would need to consider changing registrars, unfortunately.

**Comment by senk** [comment]
@dnsguru @sleevi Our registrar was able to register the domain til 2023 now. So we are good to go now 
```
➜  ~ whois fh-muenster.io | grep Expiry
Registry Expiry Date: 2023-10-26T16:22:06Z
```

**Comment by dnsguru** [comment]
@senk thank you - all set

**Pull request merged**
