### PR TITLE
Update TicketSearch Public Suffix List

### PR DESCRIPTION
**Pull request by tixblaker**
update suffix list

[TicketSearch is a global ticketing platform offering next-generation services for venues to enhance customer experience with an affordable, efficient, and powerful self-managed solution. Built in collaboration with 700 venues and more than a thousand professionals across three continents, developers have incorporated SMART social-distancing technologies, virtual event integrations for both hybrid and streamed events, as well as merchandising modules. With a mobile-first approach, the platform provides customers quick and easy options to complete their transactions. Additionally, 37 visual intelligence dashboards, powered by Tableau, provide venue managers with real-time reports to optimize sales and marketing decisions. TicketSearch is live in USA, Australia, New Zealand, Mexico and Asia. ]   Description of Organization

[ Ticket have a multiple client, they want to manage their own business account with their on TicketSearch sub domains. For example (abc.sales.ticketsearch.com). Ticket search domain is already verified in own Facebook business account. So we have to register ticket search domain and client sub domain in PSL list so they can manage their own account ]  Reason for PSL Inclusion

[ $ dig TXT _psl.artshouse.sales.ticketsearch.com
https://github.com/https://github.com/publicsuffix/list/pull/1518]

$ dig TXT _psl.ticketsearch.com
https://github.com/publicsuffix/list/pull/1518%5D DNS verification via dig

* [Yes] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by dnsguru** [comment]
labelling this as draft/wontfix untill it is complete.

The patch has an extra carriage return that needs removing, as well as the entire submission form missing organization description, rationale, and answers to the checkboxes.

**Comment by tixblaker** [comment]
#1518 is now updated with the required information.

**Comment by tixblaker** [comment]
#1520 has been closed now.. would you please consider this one.

**Comment by tixblaker** [comment]
Guys, Would you please update us, on where we are at this moment?

**Comment by tixblaker** [comment]
Guys, please update us, it's been a long time, and we have to shot out this asap now.

**Review by dnsguru — CHANGES_REQUESTED** [review]
Need to bring this into spec with the submission guidelines:

- Please relocate this change higher in the file (alphabetically by company would place this nearer to tikets.io entry)
- Please remove the extra newline at end (should be only one)

**Comment by dnsguru** [comment]
You might need to rebase the source PSL in making these changes  

https://github.com/publicsuffix/list/blob/a7cc621db86f3fa3c46b6c6842b36b9c0eeeb40f/CONTRIBUTING.md in case you need to see the contribution guidelines.

**Comment by tixblaker** [comment]
We have updated the changes as suggested.  would you please review it asap? so we can move further.

**Comment by tixblaker** [comment]
@dnsguru - as we requested earlier, we have updated the record as you suggested. but we did hear you after that. 
and we have been waiting so long.

Would you please update as asap?

**Comment by dnsguru** [comment]
Noting the revisions eventually got made, the PR has been updated to remove the fail states

"you're in the queue"

Is this request for something related to Facebook?  Not sure why they're mentioned but you should be working with them on things related to their platform.   I added the IOS/FB label to see if someone from FB will step in and walk the submission through review

Side note, we're volunteers, and the various starts and stops and revisions have made this a cycle-expensive PR to get it to where it is now, especially from amongst the many other ones.

**Comment by bedfordsean** [comment]
@tixblaker can you confirm the request number you have raised with Facebook directly as per the guidance at https://www.facebook.com/business/help/126789292407737?id=1205376682832142?

**Comment by tixblaker** [comment]
@bedfordsean  - hey i'm not sure about the request number, but our PR is #1518. would you please take action on it? because it has been a long time. please.

**Comment by bedfordsean** [comment]
@tixblaker, if you've not read the instructions and followed the process via Facebook, as detailed at https://www.facebook.com/business/help/126789292407737?id=1205376682832142, then unfortunately this task isn't likely to move at all.

You're listing a dependency on "Facebook Business Account" above, which makes it sound like this request is related to allowing your clients to independently run advertising on domains that you host? If that is the case, please raise a request from the linked Facebook.com help form and we can progress from there

**Comment by tixblaker** [comment]
@bedfordsean, I have created a request over there.. please see the below text which I got..

Thanks for contacting us. You should receive an email response soon. For your reference, job [#888676212535845](https://www.facebook.com/support) has been created.

apart from that, would you guys please help us, Ticket Search app is deactivated for further compliance, and users are not able to login with Facebook in ticket search.

App ID: 2945845942096370 
Would you please check further in the case as well?

**Comment by bedfordsean** [comment]
Thanks. @lennyfb can help with this request. 

To be clear, FB *Login* has nothing to do with needing to be on the public suffix list. This is purely for the purposes of using Aggregated Events Measurement when you are hosting a web site on behalf of other businesses. If you have FB Login issues, following this process will not resolve it

**Comment by tixblaker** [comment]
Hi @bedfordsean,

Would you please let us know the status of this Public suffix list request?

**Comment by lennyfb** [comment]
> Would you please let us know the status of this Public suffix list request?

Followed up via Meta support ticket 888676212535845. I replied to the email on file for that support case.

**Comment by dnsguru** [comment]
For requests that are leveraging the PSL as a work-around to the security/privacy in IOS for targest facebook marketing, rather than decline these outright as invalid, there is a label that was made for the queue of those seeking facebook solution workaround pull requests

There is no timeline attached to when these would get merged into the PSL, but an initial group was approved a while back, with some expression that another group _might_ merge at some unidentified point in the future

**Comment by tixblaker** [comment]
HI @dnsguru, 

I got an email from Facebook and I did reply to that. but did not get any reply from Facebook after this. 

Would you please check.. and suggest..
------------------------------------------------------------------------------------------------------------------

Hi Support,

Yes, we have added generic link also. As you can see we have a dynamic sab domain which belongs to our different different clients.
That’s why we have added with *( asterisk) with prefix. It will be good if it works, otherwise each time we have to add client domain in this list. 

And really take taking process from your side.  So please suggest.

artshouse.sales.ticketsearch.com
norpa.sales.ticketsearch.com
*.sales.ticketsearch.com

Many Thanks
J.
From: Facebook <[case++aazslnyrrq23sv@support.facebook.com](mailto:case++aazslnyrrq23sv@support.facebook.com)> 
Sent: 05 August 2022 15:03
To: Jitendra Singh <[jitendras@tixtechnology.com](mailto:jitendras@tixtechnology.com)>
Subject: artshouse.sales.ticketsearch.com, norpa.sales.ticketsearch.com, *.sales.ticketsearch.com

Hi,

Apologies for the delay with this request. I see you're trying to add [sales.ticketsearch.com](http://sales.ticketsearch.com/) so the PSL. Is that correct? If so, everything looks in order except for one thing. The PSL maintainers require that domains' expiry be at least 2 years in the future. Could you please update the domain so the expiry is at least August 2024?

Thank you,
Meta Support

**Comment by bedfordsean** [comment]
@lennyfb please can you follow up on this one on the support ticket?

**Comment by tixblaker** [comment]
Hi @bedfordsean 

still, I'm waiting for updates..

Please let me know, still, we need to change anything on our side.

**Comment by bedfordsean** [comment]
@tixblaker you should have an update from our support team at this point.

**Comment by dnsguru** [comment]
> We are confused here, Would guys please confirm related to PSL Txt record?
>
> a) As we have lots of ticket search sub domain for example(
> artshouse.sales.ticketsearch.com, norpa.sales.ticketsearch.com etc) So if
> we create generic Txt record _psl.*.sales.ticketsearch.com then it will
> work for all sub domain?
>
> b) Or do we need to create Txt record _psl.ticketeserch.com only. As main
> domain is ticketsearch.com?
>
> Please suggest..
>

"B", BUT FOR EACH DOMAIN YOU SEEK TO ADD

**Comment by dnsguru** [comment]
DNS Validation failing for all requested names, will review in next sortee

**Comment by dnsguru** [comment]
Received NXDOMAIN response on all ticketsearch PSL txt records.

```
]$ dig TXT _psl.ticketsearch.com

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> TXT _psl.ticketsearch.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 53140
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;_psl.ticketsearch.com.         IN      TXT

;; AUTHORITY SECTION:
ticketsearch.com.       900     IN      SOA     ns-811.awsdns-37.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 91 msec
;; SERVER: 66.33.200.80#53(66.33.200.80)
;; WHEN: Mon Oct 03 12:39:46 PDT 2022
;; MSG SIZE  rcvd: 131

```

**Comment by tixblaker** [comment]
Hello @dnsguru,

As you mentioned below we have a little bit confused here,  do we need to contain only subdomains in the list as you mentioned if we include *.sales.ticketserch.com then it will stop the cookies for the main domain? We don’t want to stopping cookies for the main domain.

Additionally your Pull Request submission is incorrect - it seems to contain "[ticketsearch.com](http://ticketsearch.com/)" as well as "[sales.ticketsearch.com](http://sales.ticketsearch.com/)". To confirm, if that was submitted to the public suffix list, your website at "[ticketsearch.com](http://ticketsearch.com/)" will stop supporting cookies, and I expect this is not what you would like to do. If you can resolve the remaining issues, we can make a recommendation to proceed on GitHub.


Also you mentioned we need to create TXT record for each subdomain then I don’t think we need to include *.sales.ticketsearch.com or ticketsearch.com in the PList.

Please suggest so we can resolve this asap. 

Many Thanks
J.

**Comment by dnsguru** [comment]
> Hello @dnsguru,
> 
> As you mentioned below we have a little bit confused here, do we need to contain only subdomains in the list as you mentioned if we include *.sales.ticketserch.com then it will stop the cookies for the main domain? We don’t want to stopping cookies for the main domain.
> 
> Additionally your Pull Request submission is incorrect - it seems to contain "[ticketsearch.com](http://ticketsearch.com/)" as well as "[sales.ticketsearch.com](http://sales.ticketsearch.com/)". To confirm, if that was submitted to the public suffix list, your website at "[ticketsearch.com](http://ticketsearch.com/)" will stop supporting cookies, and I expect this is not what you would like to do. If you can resolve the remaining issues, we can make a recommendation to proceed on GitHub.
> 
> Also you mentioned we need to create TXT record for each subdomain then I don’t think we need to include *.sales.ticketsearch.com or ticketsearch.com in the PList.
> 
> Please suggest so we can resolve this asap.
> 
> Many Thanks J.

This may be a point that is lost but the PSL is a volunteer-based catalog, and I am a volunteer investing personal time to maintain the PSL.  

It appears you're sorting out whatever facebook stuff with facebook - that's not me.  I am not recommending any specific configuration of your domain name or its addition to the PSL.  Is that guidance perhaps from facebook?  I am not Facebook support, nor do I desire to volunteer my personal time to be their support or answer questions about their guidance related to whatever entries you think you should request.

Separate from that, so that this can proceed, there needs to be a DNS entry per the guidelines here - Just need simple ability to confirm the domain(s) in a PR connect to the DNS "proof" you're domain owner.  

Just add a DNS TXT record for _psl.ticketsearch.com that contains the URL of this PR - because there is not a txt record on _psl.ticketsearch.com, the validation is failing, so you're causing yourself all this extra delay because you've not done this.

Whatever of your choice(s) of other subdomains of that domain, each should have its own _psl txt entry, so that we can validate them, but also so that future cleanup scripts detect them and do not erase the entries from the PSL.

We are not resourced to provide help with setting this up or any more detailed instructions. Not having that record in place when we next have time to validate will continue to delay further processing as the validation will fail again.

**Comment by bedfordsean** [comment]
@tixblaker *you* need to decide for your own website purposes what makes sense. Neither the PSL maintainers, nor Meta can really determine that for you because we don't know how your website works. 

Please read the associated documentation on the PSL wiki to fully understand what putting an entry on to the PSL does, and then follow through for the appropriate domains that you wish to list. 

As you mention, you do not want the root "ticket search.com" domain in the list, which Meta support (@lennyfb) validated, however for all other subdomains, it depends entirely on how you want things to work.

**Comment by dnsguru** [comment]
Closing this due to lack of DNS validation records after protracted period.   Used up all your PSL volunteer cycles on this.

cannot validate ticketseach.com at any level of DNS

Fourth:   NOPE
```
$ dig TXT _psl.artshouse.sales.ticketsearch.com @8.8.8.8

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> TXT _psl.artshouse.sales.ticketsearch.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 26678
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_psl.artshouse.sales.ticketsearch.com. IN TXT

;; AUTHORITY SECTION:
ticketsearch.com.       900     IN      SOA     ns-811.awsdns-37.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 16 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Nov 22 15:00:36 PST 2022
;; MSG SIZE  rcvd: 147
```

Third:  NOPE
```
$ dig TXT _psl.sales.ticketsearch.com @8.8.8.8

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> TXT _psl.sales.ticketsearch.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 18378
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_psl.sales.ticketsearch.com.   IN      TXT

;; AUTHORITY SECTION:
ticketsearch.com.       900     IN      SOA     ns-811.awsdns-37.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 17 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Nov 22 15:00:49 PST 2022
;; MSG SIZE  rcvd: 137
```

Second:  NOPE
```
$ dig TXT _psl.ticketsearch.com @8.8.8.8

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> TXT _psl.ticketsearch.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 32190
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_psl.ticketsearch.com.         IN      TXT

;; AUTHORITY SECTION:
ticketsearch.com.       900     IN      SOA     ns-811.awsdns-37.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 25 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Nov 22 15:00:56 PST 2022
;; MSG SIZE  rcvd: 131

```

[There was an opportunity to correct given over a month ago](https://github.com/publicsuffix/list/pull/1518#issuecomment-1285159314), but it appears this was not taken.

Please re-open after these have been added, but because this was not performed in the DNS as requested, the PR fails, and we're super resource anemic here and can't iterate or hand-hold on this, it will start its queue time over, and the second test group of #1245 victims is missed.

**Comment by tixblaker** [comment]
Hello Guys,

 
As per the mentioned in below document,  we need to understand few things..

https://www.facebook.com/business/help/126789292407737?id=1205376682832142 <https://www.facebook.com/business/help/126789292407737?id=1205376682832142> 

 
As our main domain is TicketSearch(https://ticketsearch.com/ <https://ticketsearch.com/> ) which is informatic website and having the less operation, mainly use for provide the information for business related and there are many organisation/client are registered in ticket search, and each organisation/client is operating their business with their backed portal which is operated by their operator with sub domain(for example https://tix.ticketsearch.com <https://tix.ticketsearch.com> ) and sub domain are using cookies for authentication and further purpose etc.. also each organisation are having their frontend URL(for example(https://tixsales.ticketsearch.com <https://tixsales.ticketsearch.com> ) for sales, which are using by customers for purchasing a ticket, voucher etc..  which is also having the cookies for further operation. 

 
So, our requirement is, there are many client want to register their frontend sub domain URL (https://tixsales.ticketsearch.com <https://tixsales.ticketsearch.com> ) in Facebook Public Suffix List to manage their account and business.

 
So we need to understand about the cookies, how the Facebook will handle it, as mentioned in document main website cookies will not be stored on domain after register the sub domain in Facebook Public Suffix List, so our question is, entire cookies will stop to work or only Facebook created cookies will not be stored like Facebook Pixel etc 

 
Please suggest.. 

 
Many Thanks

J.

**Comment by tixblaker** [comment]
Hello Guys,

As per the mentioned in below document,  we need to understand few things..
https://www.facebook.com/business/help/126789292407737?id=1205376682832142

As our main domain is TicketSearch(https://ticketsearch.com/) which is an informatic website and having the less operation, mainly use for provide the information for business related and there are many organisation/client are registered in ticket search, and each organisation/client is operating their business with their backed portal which is operated by their operator with sub domain(for example https://tix.ticketsearch.com/) and sub domain are using cookies for authentication and further purpose etc.. also each organisation are having their frontend URL(for example(https://tixsales.ticketsearch.com/) for sales, which are using by customers for purchasing a ticket, voucher etc..  which is also having the cookies for further operation. 

So, our requirement is, there are many client want to register their frontend sub domain URL (https://tixsales.ticketsearch.com/) in Facebook Public Suffix List to manage their account and business.

So we need to understand about the cookies, how the Facebook will handle it, as mentioned in document main website cookies will not be stored on domain after register the sub domain in Facebook Public Suffix List, so our question is, entire cookies will stop to work or only Facebook created cookies will not be stored like Facebook Pixel etc 

Please suggest.. 

Many Thanks
J.

**Comment by dnsguru** [comment]
Seems like the mention of the PSL not being Facebook or run by Facebook got
lost somewhere.

This github repo isn't the Facebook tech support forum - the PSL is a very
anemic volunteer-resourced project.

The ticket was closed due to a failure of DNS administrative validation on
the submitted names.

It sounds like you used this as a control mechanism to ensure there were
answers as you have plenty of questions... all a great opportunity for a
multi-billion dollar company to support you, their client.

Having your partner support you  seems far more appropriate than an unpaid
open source volunteer doing so on their behalf to support their services.

If you have concerns about proceeding, address those questions with
Facebook support and leave this pull request closed,

You can always submit a new one (and please perform the appropriate dns
validations for it) when you have higher confidence.

When doing a new pull request, reference back to this pull request number
so you preserve the context and background.

**Comment by bedfordsean** [comment]
@tixblaker it sounds like you're not really certain from this thread as to the purposes of the PSL or what the implications are for being on it. This has come up a few times in comments around Login, subdomains, and otherwise. Being on the PSL affects how *all* browsers treat listed websites, not just how Facebook/Meta will treat your website. 

As @dnsguru has rightfully said, the place to get support for FB/Meta issues is not here. Generally speaking, as per the document you have referenced, our priority is to *existing* public suffix list entries, and not creating new ones:

`Our current efforts are designed to support pre-existing Public Suffix List domain registrations or eTLDs. This support is in line with Apple's recent private click measurement. There are other technical implications if a domain is registered as a Public Suffix that a business should consider (for example, the domain that is registered on the Public Suffix List cannot have its own cookies) and as such, we do not recommend that clients register their domains on the Public Suffix List specifically for Meta event configuration.`

The easiest resolution is to not use the Public Suffix List at all and instead rework your product so that your customers have their own eTLD+1 domains outside of "ticketsearch.com".

If you still believe that the Public Suffix List is the best route to go, please follow the support process detailed in the Meta support form through to completion and advise to raise a pull request here. Meta validates all of the pre-required configuration and DNS entries as part of that process. Nothing will proceed here without reducing the workload on public suffix list maintainers to a bare minimum.

**Pull request closed without merging**
