### PR TITLE
Add regional domain for filegear.me

### PR DESCRIPTION
**Pull request by renqiz**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

Description of Organization
====
Filegear Inc. provides personal cloud devices to our customers. They can use this device to organize their files, photos, music, and videos automatically. And they can access these files from anywhere, and share with anyone.

Organization Website: https://www.filegear.com

Reason for PSL Inclusion
====
We already use filegear.me for our customer's devices. Each of these device has a sub-domain name that is generated dynamically during device initialization and registration, e.g. vxnaowas.filegear.me.

As we are expanding our business overseas, we have customers from different regions. We would like to have regional domain names for devices at different regions, e.g. vxnaowas.filegear-jp.me for a device in Japan. Therefore, we could provide better performance and access to these devices.

DNS Verification via dig
=======
Completed

make test
=========
Passed

### CODE REVIEW

**Comment by frju365** [comment]
Can we have DNS verification ? :-) Without this verification, we won't be able to merge this PR.

**Comment by simon-friedberger** [comment]
@renqiz Are you still using these? Some of the suffixes have disappeared and filegear.me seems to be a private page now.

**Comment by renqiz** [comment]
> @renqiz Are you still using these? Some of the DNS entries have disappeared and filegear.me seems to be a private page now.

Yes. We are sunsetting this product from filegear.com. But the devices delivered to customers previously are still using these entries. It will take time to fade them out.

**Comment by simon-friedberger** [comment]
@renqiz Can I already remove some of them?
It seems filegear-au.me, -de.me, -ie.me either don't have the _psl entry (gentle reminder that you're supposed to keep those) or don't resolve anymore.

**Comment by groundcat** [comment]
pinging @renqiz 

The regional domains listed below had expired and were likely registered by different registrants (all after 2019). 

Can you confirm if they should be removed from the PSL?

| Domain           | Creation Date          | Registrar Name   | Nameservers                             |
|------------------|------------------------|--------------------------|----------------------------------------|
| filegear-au.me   | 2021-01-27T18:08:42Z   | Key-Systems GmbH         | ns-cloud-e1.googledomains.com, ns-cloud-e2.googledomains.com, ns-cloud-e3.googledomains.com, ns-cloud-e4.googledomains.com |
| filegear-de.me   | 2022-06-08T22:13:07Z   | Danesco Trading Ltd.     | ns1.gm238.parklogic.com, ns2.gm238.parklogic.com |
| filegear-gb.me   | 2021-05-11T16:01:59Z   | NameCheap, Inc.          | dns1.registrar-servers.com, dns2.registrar-servers.com |
| filegear-ie.me   | 2023-08-16T19:52:08Z   | NameCheap, Inc.          | dns1.registrar-servers.com, dns2.registrar-servers.com |
| filegear-jp.me   | 2024-03-16T02:17:05Z   | NameCheap, Inc.          | dns1.registrar-servers.com, dns2.registrar-servers.com |
| filegear-sg.me   | 2024-03-08T10:14:53Z   | NETIM SARL               | nsla01.listen53.net, nsla02.listen53.net |

**Comment by renqiz** [comment]
@groundcat Yes, just confirmed that these regional domains can be removed. Please keep the global domain "filegear.me". Sorry for the inconvenience.

Regional domains that are no longer used:
- filegear-au.me
- filegear-de.me
- filegear-gb.me
- filegear-ie.me
- filegear-jp.me
- filegear-sg.me

**Pull request merged**
