### PR TITLE
Add codeberg.page to PSL

### PR DESCRIPTION
**Pull request by moqmar**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://codeberg.org

Codeberg is a non-profit code hosting service for OSS projects, similar to GitHub, that also offers static website hosting under the name "Codeberg Pages" (see below). I am a an elected member of the Presidium and also the main developer of the current version of Codeberg Pages.

Reason for PSL Inclusion
====

Codeberg Pages (https://codeberg.page) hosts static user content similar to GitHub Pages (at `username.codeberg.page`), and those pages shall be treated as its own domain for all purposes. The inclusion at PSL also exists as an issue on our platform: https://codeberg.org/Codeberg/Community/issues/451

DNS Verification via dig
=======

```
dig +short TXT _psl.codeberg.page
"https://github.com/publicsuffix/list/pull/1482"
```

make test
=========

:heavy_check_mark: passes

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by dnsguru** [comment]
@6543 Who are you and why are you making any approvals on this PR in this project?

**Comment by dnsguru** [comment]
Flagging this as invalid pending response from 6543 or @moqmar

**Comment by 6543** [comment]
@dnsguru well It was ment as an ACK,

Since I'm not a maintainer/member of this repo/org the approval should only be inforable (you can configure that in github ...)

Disclamer: I'm also member of Codeberg e.V.

**Comment by 6543** [comment]
@dnsguru any questions left?

**Comment by dnsguru** [comment]
just a queue ahead of this for these unpaid volunteers to review and approve - now it looks like permissions need a review as well because folks should not be approving their own company's PR, so more volinteer time down the drain.

**Comment by 6543** [comment]
my bad it distract your work ... :/ it was meant as help to ack its right ...

> ... company

codeberg is no company its an NGO also run by volunteer

**Comment by 6543** [comment]
should we create a new pul and close that one?!?  @dnsguru

**Comment by dnsguru** [comment]
> should we create a new pul and close that one?!? @dnsguru

No, please, just let us work through the queue - if there were any recommendations it would be ... patience and low-maintenence mode as requestor.

**Review by dnsguru — APPROVED** [review]
- Follows Guidelines
- DNS Validation of Admin Authority
- Tests Pass
- No Conflict With Base


Approved

**Pull request merged**
