### PR TITLE
Add Ukgbi.com 

### PR DESCRIPTION
**Pull request by RegistryPRO**
Closed, because who does not speak English fluently, but is not welcome!
As said by one of the volunteers, I must change teachers. But I chose to change possibilities!
See you!

### CODE REVIEW

**Comment by sleevi** [comment]
This request does not comply with the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

**Comment by RegistryPRO** [comment]
@sleevi The request for NITR.PRO is in compliance or tactic that do another,?

**Comment by sleevi** [comment]
@RegistryPRO I'm really not sure why this is difficult. The Guidelines spell out what needs to be done, and we've been over this several times now. If there are challenges with understanding them, we're open to helping non-native English speakers better understand, but as a simple matter of courtesy, respect, and demonstration of understanding of the implications of adding to the PSL, please actually read the Guidelines and ensure your requests comply with them.

Quite literally, every issue you have had is already covered in the Guidelines. You didn't know how to create a Pull Request, but the documentation is clearly linked as the first step in [Submit the Change](https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change). This similarly fails to include information about why you're requesting.

If future requests continue to have these issues, they will be denied.

**Comment by RegistryPRO** [comment]
@sleevi I understand what you say. I tried my best not to err, but I can not find the error in the NITR.PRO request.

I made the TXT change of the NITR. Pro, but but unfortunately, not even reading, but still can not find the error.

In this new request I follow the guidelines and the rules and includes following the alphabetical order More but now I do not know if the request is completely wrong or if it has some errors.

**Comment by weppos** [comment]
@RegistryPRO Please carefully read this section, it contains what you have to provide (which is missing in this PR)
https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change

**Comment by frju365** [comment]
@RegistryPRO In fact, what is the most important is why you request your domain to be added here. @sleevi just needs a reason and a good reason. 

And you must prove that you really need to be added here. After the reason, you must add a short description of your organization/registry... to legitimate your request.

The PSL is very important and is a base for many organization on internet. 

I think the best is to see other PR which have been merged. For example you can see this : https://github.com/publicsuffix/list/pull/615 From my point of view, this PR is an example.

**Comment by sleevi** [comment]
> I made the TXT change of the NITR. Pro, but but unfortunately, not even reading, but still can not find the error.

I told you precisely what the error was. 

> but the documentation is clearly linked as the first step in Submit the Change. **_This similarly fails to include information about why you're requesting._**

**Comment by RegistryPRO** [comment]
@sleevi @frju365 My PRs were a real disaster. I'll have to start all over again.

**Comment by frju365** [comment]
No, no. Just add a comment like this. Just add a little text about the reason, and who is your organization/person who want to add this domain here.

**Comment by RegistryPRO** [comment]
@sleevi @frju365 The reason you request the PR for NITR.PRO:

NITR.PRO was marketed by Afilias, but since last year I took over the operations and got in touch with registrars.
NITR.PRO is currently a public suffix marketed by several companies.

**Comment by sleevi** [comment]
@RegistryPRO The reason for **this** pull request.

**Comment by RegistryPRO** [comment]
@sleevi The Ukgbi.com domain will be marketed in the UK and Ireland.

**Comment by RegistryPRO** [comment]
@sleevi @weppos I'm sorry for the bad things you did. It was not my intention. I am taking an English course, but the explanation of the Guidelines may seem confusing, but depending on the variation of Portuguese with English.

I consider the @frju365 s explanations of better than the Guidelines.

My sincere apologies for the problems!

**Comment by RegistryPRO** [comment]
@frju365 Should I create new PRs for NITR.PRO and UKGBI.COM? or not?

**Comment by frju365** [comment]
just comment here giving the reason, a short description and the test proof (TXT record) like in #615.

**Comment by RegistryPRO** [comment]
@frju365 

DESCRIPTION:

The suffix UKGBI.COM has an open and public record similar to CENTRALNIC.

The UKGBI.COM domains are intended for the United Kingdom and Ireland.

Destined for England, Wales, but Scotland, but Northern Ireland and Ireland.

The TXT record was included with the PR number.

**Comment by RegistryPRO** [comment]
@frju365 Would it be this?

**Comment by RegistryPRO** [comment]
screenshot_2018-05-15-16-42-35

**Comment by frju365** [comment]
Jusr one thing:  why the URL you provided doesn't work ? http://www.registry.ukgbi.com ?

**Comment by RegistryPRO** [comment]
@frju365 It worked normally.

http://registry.ukgbi.com/i/

Or

http://registry.ukgbi.com/

**Comment by RegistryPRO** [comment]
@frju365 Is it correct or is it still wrong?

**Comment by frju365** [comment]
Could you just precise the reason why you want your domain to be added here ? The problem you have if there are problem ?

**Comment by RegistryPRO** [comment]
@frju365  no problem

**Comment by sleevi** [comment]
@RegistryPRO Perhaps it might be good if you were able to find a more proficient English speaker to assist with your pull request? @frju365 is kindly trying to highlight that you've still failed to meet the Guidelines, and that failure prevents moving forward.

More troubling, the confusion about that - how to follow the Guidelines, the questions being asked - suggest that you may not fully appreciate the nuance and risk of adding to the Public Suffix List. While we certainly want to help domain holders add to the PSL as appropriate, it would be reckless to do so without a reasonable belief that the purpose and nature are well-understood - and that might be better helped with the assistance of a translator.

**Comment by RegistryPRO** [comment]
@frju365 I already put the reason described. Is there still an error?

**Comment by frju365** [comment]
Well, "reason" is not perhaps clear for everybody. In fact, you describe how and where the domain are being used which is quite good and are more "extra informations". 

But, to add a domain to the PSL, you must tell us a reason. The main question is :  why do you want to add this domain to the PSL ? 

You can tell us in Portuguese if it's easier (I understand quite well), I think.

---
Queremos saber porque querem acrescentar este domínio na Public Suffix List. Nao e facilo para nos de comprendre porque querem acrescentar este domínio na PSL : tem um problema ? ou um motivo para querer isso ?

Desculpe do meu mau português

**Comment by RegistryPRO** [comment]
@sleevi Sorry for the problems you caused. Thank you for your help!

**Comment by frju365** [comment]
Can you just add example too when you say the domain is "marketed in the UK and Ireland." ? Perhaps URL ? (I read too fast)

**Comment by RegistryPRO** [comment]
@frju365 Reason for adding the domain to the PSL:

The UKGBI.COM domain is marketed as a public and open suffix.

We are a web hosting provider, and we market the domain to several clients.

The operation of the UKGBI.COM domain is similar to the operation practiced by CENTRALNIC.

Example:

UKGBI.COM operates in the same way as BR.COM and US.ORG

**Comment by frju365** [comment]
Well, I think it's much better. 
For the record, finally, can you remove this TXT record you did and add a subdomain : _psl.ukgbi.com with just the URL of this PR `https://github.com/publicsuffix/list/pull/661` .

If you have a zone text/file, you can add directly this line (after the other one) : 
`_psl 3600 IN TXT "https://github.com/publicsuffix/list/pull/661"`

After that, I think it will be ok for me.

**Comment by RegistryPRO** [comment]
ORGANIZATION:

The company operates in several areas of domains. He specializes in Portuguese-speaking and Latin-domains.

Subscriber loans for ccTLD domain registrars BR, VE, AR, EC, CU, BO

Currently we operate presse.ml which was operated by NIC du Mali, nitr.pro which was operated by Afilias.

We are trying to work in the international market with a focus on the UK, but since one of its territories (Ascension) is near the state of Pernambuco in Brazil (where we have some servers).

REASONS TO REQUEST PR:

The UKGBI.COM domain is in use and is marketed openly and publicly. Being that any individual or organization can own a domain.

The domain was created based on the UK and Irish domain markets.

ABOUT ME:

- Participated in ICANN projects in Portuguese,
- I published articles on Internet governance and domain management for CGI.br
- I'm learning English with 2 American teachers.
I still do not speak fluently, but I can already write some sentences and texts.
- I am a product and marketing manager,
-business consulting for domains that want to work in Brazil.

**Comment by RegistryPRO** [comment]
@frju365 I did the same as PR # 615

**Comment by frju365** [comment]
Very good.

@sleevi, @weppos : is it enough to validate this PR ?

**Comment by frju365** [comment]
I think moreover the efforts to be ok with the PSL have been done now (after this long discussion).

**Comment by weppos** [comment]
@frju365 @RegistryPRO I would appreciate if you amend the opening ticket adding all the information requested, so that we don't have to chase every single answer inside the thread.

**Comment by frju365** [comment]
@weppos I'm not able to edit first comment. Only @RegistryPRO, @sleevi and you are able to do that.

**Comment by RegistryPRO** [comment]
@frju365 Which comment do you want to edit?

**Comment by RegistryPRO** [comment]
@weppos Which comment do you want to edit?

**Comment by frju365** [comment]
Edit the first comment of the PR, the most at the top and sum up every info you gave us (copy/paste).
To edit a comment click on the pencil which is at the top right of the comment.

**Comment by RegistryPRO** [comment]
@frju365 I already did as you asked. Thank you for your help

**Comment by RegistryPRO** [comment]
@frju365 Make sure the first comment is right now?

**Comment by frju365** [comment]
it's ok for me. 

@sleevi, @weppos  : is there something missing ?

**Comment by frju365** [comment]
In fact, @weppos, I agree totally that Github Issues is not good to discuss, **but** apparently to discuss on your mailing-list I need to create a google account, so no. I don't trust Google and I'm against service where you have to create account on GAFA instance to communicate. Really sorry, but my help will stay here waiting you (or me if you agree) create your own instance(forum, channel, gitter channel, Matrix, IRC...) to discuss or use another service(I can give you alternatives). Really sorry.

**Comment by RegistryPRO** [comment]
@weppos yesterday I did a review and updated the first comment with all the necessary information.

I edited the first comment and analyzed PRs that were successful.

It is important to note that GitHub's explanations of the PSL are confusing for me and other Brazilians.

I have read the Guidelines several times to try to find the error.

I asked for help from other Brazilians who participate in the community and foreigners, which is they were confused about how it is explained.

**Comment by weppos** [comment]
> It is important to note that GitHub's explanations of the PSL are confusing for me and other Brazilians.
> I asked for help from other Brazilians who participate in the community and foreigners, which is they were confused about how it is explained.

Just stating something is confusing, without providing an actual way to make it clear, it's not very helpful to improve the documentation.

Feel free to join the [mailing list](https://groups.google.com/forum/#!forum/publicsuffix-discuss) and provide specific amendment suggestions to improve the docs.

**Comment by RegistryPRO** [comment]
@weppos The PR's first comment was edited for review.

But I must be honest about some comments in this PR that translated into Portuguese become malicious and humiliating comments. Our team is unmotivated when reading certain comments.

I am aware of the importance of the PSL, but thank the help @ frju365 and also thank the help attention of @weppos, but the masters getting sad with all that there was.

Thank you for understanding

**Comment by RegistryPRO** [comment]
@weppos yesterday I did a review and updated the first comment with all the necessary information.

I edited the first comment and analyzed PRs that were successful.

It is important to note that GitHub's explanations of the PSL are confusing for me and other Brazilians.

I have read the Guidelines several times to try to find the error.

I asked for help from other Brazilians who participate in the community and foreigners, which is they were confused about how it is explained.

**Comment by RegistryPRO** [comment]
Closed

**Pull request closed without merging**
