### PR TITLE
Add spacekit.io

### PR DESCRIPTION
**Pull request by jedireza**

### CODE REVIEW

**Comment by jedireza** [comment]
:pager: @sleevi @weppos 

What's next in the process for getting this PR merged?

**Comment by jedireza** [comment]
```bash
$ dig TXT _psl.spacekit.io

; <<>> DiG 9.10.3-P4 <<>> TXT _psl.spacekit.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12397
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_psl.spacekit.io.		IN	TXT

;; ANSWER SECTION:
_psl.spacekit.io.	300	IN	TXT	"https://github.com/publicsuffix/list/pull/166"

;; Query time: 21 msec
;; SERVER: 10.251.75.120#53(10.251.75.120)
;; WHEN: Mon Apr 25 15:06:22 PDT 2016
;; MSG SIZE  rcvd: 103
```

**Comment by sleevi** [comment]
Requests are being processed in the order they are received. To ensure rapid processing, please double-check and make sure everything matches the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) and the surrounding entries

**Comment by jedireza** [comment]
I've seen some PRs created and merged the same day. I'm curious about the wait time here.

Any changes need on our end?

**Comment by jedireza** [comment]
Rebased from latest `master`

**Pull request merged**
