### PR TITLE
Add `activetrail.biz` for #1245 workaround

### PR DESCRIPTION
**Pull request by shlomi-activetrail**
Adding activetrail.biz

 
Description of Organization
====
* [X] Description of Organization
ActiveTrail (https://www.activetrail.com/) provides marketing solutions for business owners for the past 18 years.
The platforms allows you to communicate with your customers using various channels such as Email, SMS, WhatsApp, Popups etc'.
As part of the platform, we provide a web page builder solution (hosting and publishing) for our customers using the https://activetrail.biz/ domain.

Reason for PSL Inclusion
====
* [X] Reason for PSL Inclusion
Each subdomain is dedicated to a separate customer, each customer is a separate business with his own pixels and events.
The customers wish to configure pixel conversion events on the eTLD+1 assigned to them, they cannon verify the eTLD as it belongs to us and cannot be verified by more than one account.

DNS Verification via dig
=======
* [X] DNS verification via dig

make test
=========
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

* [X] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  
* [X] This request was _not_ submitted with the objective of working around other third-party limits

* [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms

* [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

* [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.

### CODE REVIEW

**Comment by shlomi-activetrail** [comment]
@dnsguru Hi Jothan, I've updated the "Description of Organization" & "Reason for PSL Inclusion" to be more descriptive.
I am not sure as to what is the next step to have the PR approved and our company's record included in the list.
Can you please advice?
Thanks, 
Shlomi

**Comment by bedfordsean** [comment]
Hi @shlomi-activetrail, the rationale you give here is "Pixel". Is this change intended for the purposes of allowing Facebook advertising to work correctly for the businesses you support? 

If yes, we have a process in place to assess whether these changes make sense on the Facebook/Meta side. I'd recommend following the process and form detailed here for Public Suffix List prior to proceeding with raising a pull request on this side > https://www.facebook.com/business/help/126789292407737?id=1205376682832142

If you have already been through this process, please can you provide me with the reference number given to you by the form and I can validate?

**Comment by shlomi-activetrail** [comment]
Hi @bedfordsean, thanks for the quick response :-)

Yes we went through the form a long time ago and filled the form multiple times with no response from Meta. Here are the references we got.
305918820904246 - Sent on 10/10/21
707063923999096 - Sent on 23/02/22
1119264528835236 - Sent on 02/03/22

**Comment by bedfordsean** [comment]
Thanks @shlomi-activetrail - I will chase on this one for you. In the meantime, this PR will have to hold pending the FB-side process

**Comment by lennyfb** [comment]
Confirming from the Meta perspective that we have worked with ActiveTrail and carried out our checks, and to the best of our ability to understand, ActiveTrail is a legitimate platform hosting use case that caters to multiple subdomain businesses and therefore has a legitimate reason to be placed on to the PSL for the purposes of cookie separation for each of those subdomains.

**Comment by dnsguru** [comment]
> Confirming from the Meta perspective that we have worked with ActiveTrail and carried out our checks, and to the best of our ability to understand, ActiveTrail is a legitimate platform hosting use case that caters to multiple subdomain businesses and therefore has a legitimate reason to be placed on to the PSL for the purposes of cookie separation for each of those subdomains.

Thanks @lennyfb but can you please provide a list of what review was done or some level of detail so that this PR stands on its own as having had dillegence applied?

As with all of the PCM/META workaround _stuff_ that PRs like this seek to fix, there needs to be adequate documentation.  The optics on the record here of having anecdotal narrative lack a reasonable amount of transparency by future eyeballs and those who might discontinue their voluntary participation in using the PSL as a source.

**Comment by shlomi-activetrail** [comment]
@dnsguru hi, can you please advice us on the next steps to complete this PR? 
Your help in seeing this to completion is greatly appreciated.

**Comment by dnsguru** [comment]
> @dnsguru hi, can you please advice us on the next steps to complete this PR? Your help in seeing this to completion is greatly appreciated.

So kind... and your patience while others seeking their PR to proceed is kindly appreciated.

Meta needs to provide details vs "we say so" in order to let this be reviewed which you can see listed here: https://github.com/publicsuffix/list/pull/1541#issuecomment-1079350842.

Once better details of review are provided, this can be reviewed and it can be determined if this does or does not proceed.  PSL is maintained by volunteers so it gets cycles from those volunteers as they can volunteer them.

**Comment by lennyfb** [comment]
Here are the checks performed from the Meta side:

		o Ensured 2+ years of domain registration remaining
		o Ensured it is possible to validate that there are indeed a significant amount of subdomains currently publicly visible for domains being added
		o Ensured that TXT record _psl.activetrail.biz exists and is linked to the PSL PR number for ownership validation
		o Ensured that domain owner acknowledges that they are a platform and do not use activetrail.biz

I'll be sure to include these checks performed in future comments where we've vetted requests.

**Comment by shlomi-activetrail** [comment]
@dnsguru, above is the response from Meta. Is there anything else needed to continue with the approval of the PR?

**Comment by dnsguru** [comment]
volunteers here, no service levels 

See paragraph 2 
[resourcing and expectations](https://github.com/publicsuffix/list/wiki/Guidelines#resourcing-and-level-of-effort-loe-impacts-the-pace-of-processing-validation-or-merge-of-a-contribution)

**Comment by btok** [comment]
Hi @dnsguru, Hope all is well. 
Can you please help us finalize the pull request?
Thanks

**Comment by Kalaofer** [comment]
@dnsguru any chance this can be done? 
We have a lot of customers waiting for several months. 

It will be much appreciated

**Review by dnsguru — CHANGES_REQUESTED** [review]
DNS Validates, and the background about #1245 and the victim's queue processing is ready to go, but due to the timing there is a conflict with the base source.

Would you please either 
- create a new pull request with the changes from the current base and reference #1541 in the notes so that we have the bg on this, -or-
- Rebase your patch from a fresh copy of the PSL dat file

**Comment by shlomi-activetrail** [comment]
Hi, Sure. Here is the new PR: 
https://github.com/publicsuffix/list/pull/1655

Thanks!

**Comment by dnsguru** [comment]
Closing this as completed by #1655

**Pull request closed without merging**
