### PR TITLE
Update public_suffix_list.dat

### PR DESCRIPTION
**Pull request by mramos29**
My name is Marco Ramos and I'm an employee of SAPO. You can reach me on mramos at co.sapo.pt

### CODE REVIEW

**Comment by mramos29** [comment]
Yes, my bad. It's fixed now. Thanks for your help :) 

Cheers.

**Comment by sleevi** [comment]
Please review the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), in particular, play close attention to the ordering requirement in [Preparing the change](https://github.com/publicsuffix/list/wiki/Guidelines#prepare-the-change)

**Comment by weppos** [comment]
@mramos29 thanks, the change is correct. Please do provide a reason for inclusion as [per Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines).

**Comment by weppos** [comment]
Closing due to no follow up.

**Pull request closed without merging**
