### PR TITLE
.br updated 2nd level domains + 3rd level gov.br

### PR DESCRIPTION
**Pull request by fnevesbr**

### CODE REVIEW

**Comment by fnevesbr** [comment]
.br is a delegation only zone. It's not possible to add the _psl.br TXT recording authenticating this pull request. We could follow on the _psl TXT record bellow dns.br infrastructure zone or the email authentication.

**Comment by gerv** [comment]
We don't normally authenticate requests at this level using _psl.*, we authenticate them by checking the person submitting the change is an authorized representative of the registry.

So this is fine.

**Comment by weppos** [comment]
@fnevesbr if you are a representative of the registry, you can also email us at team@publicsuffix.org to confirm the PR from your authoritative email.

I suppose this is you:
https://github.com/fnevesbr/list/blob/45aa3a3d06005b13600c93ea0dc5e59b43cc9c2b/public_suffix_list.dat#L400

**Comment by ericroman920** [comment]
Is this change correct?

This broke sites like https://webmail.es.gov.br/ in Chrome, whose certificates rely on a subjectAltName on the wildcard *.es.gov.br. Following this change, es.gov.br is considered public/icann registry controlled and disallowed in the same manner that a wildcard subjectAltName on *.com is disallowed by the browser.

**Comment by fnevesbr** [comment]
On Wed, Aug 2, 2017 at 1:10 AM ericroman920 <notifications@github.com>
wrote:

> Is this change correct?
>
Yes

> This broke sites like https://webmail.es.gov.br/ in Chrome, whose
> certificates rely on a subjectAltName on the wildcard *.es.gov.br.
> Following this change, es.gov.br is considered public/icann registry
> controlled and disallowed in the same manner that a wildcard subjectAltName
> on *.com is disallowed by the browser.
>
The validity of this wildcard certificates for those state domains are a
serious security liability for all the delegated cities. 76 in the case of
the ES.

Frederico

**Comment by ericroman920** [comment]
Thanks fnevesbr!

**Pull request merged**
