### PR TITLE
Add deSEC dynamic DNS domain: dedyn.io

### PR DESCRIPTION
**Pull request by peterthomassen**

### CODE REVIEW

**Comment by peterthomassen** [comment]
Hey. While I don't intend to be pushy -- can you let me know what the ETA for this is? This would help me tell our customers what the timeline is, very roughly. Thanks a lot!

**Comment by peterthomassen** [comment]
Hi. Thanks for your reaction. Can you give a rough ETA? Is the list updated monthly or something, or sporadically?

**Comment by weppos** [comment]
@peterthomassen We generally manage the requests within a couple of weeks, however we're currently experiencing an high number of requests, apparently due to some new requirements imposed by Let's Encrypt.

We need/want to know more before proceeding with the merge of all the related requests. Considering this project is maintained in a volunteer basis and we're approaching the end of the year, you may expect the changes to be merged between the end of this year and the beginning of the new one.

**Comment by peterthomassen** [comment]
@weppos Thanks a lot, this is very useful information. Thanks for doing this. Enjoy the holidays! :-)

**Comment by peterthomassen** [comment]
@weppos Is there an update on this?

**Comment by LeoVerto** [comment]
I'd love to see this PR merged, my letsencrypt certificate recently expired and I'm unable to renew it; the LE people just point here.

**Comment by weppos** [comment]
@LeoVerto even if this change would be merged, there are other "work-in-progress" issues about the PSL updates being merged into Go and Let's Encrypt that will not solve you this issue. You better have to wait for Let's Encrypt to increase their rate-limiting, or release the form to request the increase of their limits.

**Comment by weppos** [comment]
@peterthomassen would you mind to update the patch and this ticket according to the Guidelines
https://github.com/publicsuffix/list/wiki/Guidelines

Once updated (and the DNS record is in place), I'll be happy to go ahead and merge this patch.

**Comment by peterthomassen** [comment]
We added the TXT record (dig TXT _psl.dedyn.io).

We also went through the guidelines again, but we're not sure in what regard the patch and/or ticket needs updating. Can you please clarify?

**Comment by weppos** [comment]
Please remove the date from the second line, also rebase your PR against master so that it's easily mergeable (it currently conflicts with master).

Also provide here the reason you are requesting the domain to be listed.

**Comment by peterthomassen** [comment]
I just rebased the PR and removed the date.

We would like to have dedyn.io added to the PSL because it is a public domain under which subdomains are offered for dynamic DNS purposes. We thus don't control subdomains of dedyn.io. (Subscription at desec.io.) We would also like to benefit from the side effects this has with the Let's Encrypt policies.

**Pull request merged**
