### PR TITLE
Add authgearapps.com authgear-staging.com

### PR DESCRIPTION
**Pull request by carmenlau**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://authgear.com, https://oursky.com

Authgear is an authentication server for web and mobile apps. We allow our users to create applications in our cloud service and use it as their application authentication server. 

Reason for PSL Inclusion
====

We allow our users to create applications in our cloud service and use it as their application authentication server. The authentication server of applications are under subdomains of authgearapps.com and authgear-staging.com. So we would like to add them to the list to isolate cookies per application.

DNS Verification via dig
=======

```
dig +short TXT _psl.authgearapps.com
"https://github.com/publicsuffix/list/pull/1304"
```

```
dig +short TXT _psl.authgear-staging.com
"https://github.com/publicsuffix/list/pull/1304"
```

make test
=========

```
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Review by dnsguru — CHANGES_REQUESTED** [review]
Please revise to group this, sorted, in the section you had submitted for #892 that is just below this.

**Comment by carmenlau** [comment]
@dnsguru Thanks for reviewing! I updated the PR to group them together, see if it looks good.

**Comment by dnsguru** [comment]
```
Name: AUTHGEARAPPS.COM
Registry Expiration: 2023-11-09 06:18:29 UTC
```
PASS

```
Name: AUTHGEAR-STAGING.COM
Registry Expiration: 2024-11-11 08:26:14 UTC
```
PASS

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Pull request merged**
