### PR TITLE
Syncloud dynamic dns service

### PR DESCRIPTION
**Pull request by cyberb**
I would like to add syncloud.it as we are distributing devices with per user dns for example user1.syncloud.it.

dig TXT _psl.syncloud.it

### CODE REVIEW

**Comment by cyberb** [comment]
Syncloud is an OS for single board computers like Raspberry Pi. It allows people not knowing IT to have their personal services like email, file sharing, social network ... For convenience we provide domain names under syncloud.it like nextcloud.user1.syncloid.it, mail.user1.syncloud.it.

One of the problems we hit is that we cannot get Let's Encrypt certificates per user with individual rate limit.

I was told by Let's Encrypt members that I probably should apply for PSL:
https://community.letsencrypt.org/t/subdomain-per-user/55365

Website: syncloud.org
Syncloud is open source: github.com/syncloud/platform

**Comment by cyberb** [comment]
Each user gets a wildcard DNS record for a domain they register.
A [device IP] user1.syncloud.it
CNAME  *.user.syncloud.it user1.syncloud.it

This is like IoT DDNS service.
We as owners of syncloud.it have no control over content under user1.syncloud.it

Original reason was Let's Encrypt limits but that pointed me at this list and after reading the guidelines I have realized that this very useful for our project in terms of cookies.

Let me know if this is not the case.
Thank you.

**Comment by cyberb** [comment]
Sorry, I did not see the changes requested and re-based to resolve conflicts with latest master.
Now github says it cannot find the commits to show requested changes, could you check again?

**Comment by cyberb** [comment]
@sleevi Could you check again please?

**Comment by cyberb** [comment]
Could anyone re-validate my feedback?

**Comment by cyberb** [comment]
Can I do anything to make this merged?
Many our users complaining aboit rate limits.

**Comment by weppos** [comment]
> Many our users complaining aboit rate limits.

The correct way to fix that problem is described here:

https://letsencrypt.org/docs/rate-limits/
https://goo.gl/forms/plqRgFVnZbdGhE9n1

**Comment by cyberb** [comment]
@weppos thanks for the reply.

Could you tell me why you are not treating Syncloud project DDNS service the same way as other ddns services that are on the list?
I just want to understand the difference.

**Comment by frju365** [comment]
@cyberb just one thing to unblock the situation, because I'm a bit lost in this PR, and I think syncloud is an awesome project. Could you close this one, and reopen it. Remove any mention of LE rate limit and please explain why : 
>  this very useful for our project in terms of cookies.

**Comment by cyberb** [comment]
Thanks!

**Comment by weppos** [comment]
> Could you close this one, and reopen it. Remove any mention of LE rate limit and please explain why :

There is no need to create noise with further PRs. Please do not encourage it, it just adds more burden. If the reasons for listing are valid, when we'll review this PR we'll approve it.

**Comment by weppos** [comment]
Anyways, since I saw the branch as already been deleted and this PR was not recent enough to use the template, then I'm fine to go ahead with a new one.

As a warning, if your goal is to get into LE, opening a new PR purposely avoiding to mention LE would not increase the chance of this PR to get merged.

I can't stress enough the importance to understand the PSL is NOT the way to bypass LE limits.

**Comment by cyberb** [comment]
another PR: https://github.com/publicsuffix/list/pull/727

**Comment by frju365** [comment]
@weppos I don't encourage anything. I just think reasons are not enough clear here for me(info are not organized). And LE reason must be avoid (it's written in the Guidelines), so no need to mention it if it's not a valid reason, isn't it a good way to have something clear with PSL compliance ? I don't understand your message, @weppos.

When you quoted @cyberb's message you quoted only LE reason, and forgot the other one, so : 

> If the reasons for listing are valid, when we'll review this PR we'll approve it.

Approval is ok only if we have a clear description and not messages which pollute the PR. So, my message was ok, I think.

> I can't stress enough the importance to understand the PSL is NOT the way to bypass LE limits.

So, why not sending a mail or opening a post on LE forum to tell the moderator it's a bad thing to suggest PSL when dev are confronted to LE rate limit ?

Because in fact, if LE community manager suggest PSL as a way to bypass LE rate limit, if I were hosting manager, I would be completely lost between one who tells me to use PSL and another which tells me the opposite.

Anyway, I tried to help and I find the initiative of the PSL very good. I tried to understand your community and the system of the PSL. But, the PSL disappointed me and it is just the last time I helped you.

**Comment by weppos** [comment]
> So, why not sending a mail or opening a post on LE forum to tell the moderator it's a bad thing to suggest PSL when dev are confronted to LE rate limit ?

Feel free to point me to recent cases where this happened, and I'll happily follow up. Or you can follow up yourself, https://letsencrypt.org/docs/rate-limits/ is posted by LE hence it's an authoritative source.

> Because in fact, if LE community manager suggest PSL as a way to bypass LE rate limit, if I were hosting manager, I would be completely lost between one who tells me to use PSL and another which tells me the opposite.

I'm sorry about the confusion, but as the PSL maintainers have already mentioned in multiple tickets, we are not responsible for how the consumers use the list. Nor this project should be considered a subsidiary of Let's Encrypt.

If you were a hosting manager, you should read https://letsencrypt.org/docs/rate-limits/ entirely and you'll find the answer directly in that article, in the section Overrides, telling:

> If you are a large hosting provider or organization working on a Let’s Encrypt integration, we have [a rate limiting form](https://goo.gl/forms/plqRgFVnZbdGhE9n1) that can be used to request a higher rate limit. It takes a few weeks to process requests, so this form is not suitable if you just need to reset a rate limit faster than it resets on its own.

I am not inventing anything. I am just reinstating exactly what LE already says on the official site.

**Comment by frju365** [comment]
Example of post : 
https://community.letsencrypt.org/t/subdomain-per-user/55365/2
https://community.letsencrypt.org/t/third-party-tools-to-check-your-configuration/76272
(these are posts of community manager and leader).

and well, It's a little confusing : 
>The main limit is Certificates per Registered Domain, (50 per week). A registered domain is, generally speaking, the part of the domain you purchased from your domain name registrar. For instance, in the name www.example.com, the registered domain is example.com. In new.blog.example.co.uk, the registered domain is example.co.uk. We use the Public Suffix List to calculate the registered domain.

**Pull request closed without merging**
