### PR TITLE
Update nymnom section

### PR DESCRIPTION
**Pull request by DaveMcCormack**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

Description of Organization
====

Organization Website:  https://nymnom.com/

'NymNom' is a 'PDNR' (Private Domain Name Registry), allowing 3rd parties to register domain names in a variety of domain name extensions / suffixes.

Reason for PSL Inclusion
====

'NymNom' has an existing section in the 'Public Suffix List', and is updating it's section to include additional domain extensions / suffixes in it's portfolio.

Inclusion is required for cookie security, 'Let's Encrypt' issuance, et al.

DNS Verification via dig
=======

This section is complete.

```
dig +short TXT _psl.nym.ec "https://github.com/publicsuffix/list/pull/771"
```
```
dig +short TXT _psl.nym.hk "https://github.com/publicsuffix/list/pull/771"
```

make test
=========

Test has been run, and all is correct.

No conflicts reported (etc).

### CODE REVIEW

**Comment by DaveMcCormack** [comment]
"DNS Authentication" DNS TXT record '_psl' with URL to pull request has been added to DNS records, as per requirements - https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by sleevi** [comment]
$ host -t txt _psl.nym.ec
Host _psl.nym.ec not found: 3(NXDOMAIN)
$ host -t txt _psl.nym.hk
Host _psl.nym.hk not found: 3(NXDOMAIN)

**Comment by DaveMcCormack** [comment]
Sorry.

Just realized that one of the DNS servers was serving a dated DB of the network.

dig +short TXT _psl.nym.ec "https://github.com/publicsuffix/list/pull/771"
dig +short TXT _psl.nym.hk "https://github.com/publicsuffix/list/pull/771"

Is now correct.

Please merge this pull request.

Thank you.

**Comment by DaveMcCormack** [comment]
I don't know how to reopen this pull request.

What do I need to do to make that happen?

There was a mishappening in the '_psl.' lookups that has been corrected.

How do I get this pull request reopened and approved?

**Comment by DaveMcCormack** [comment]
How do I reopen this pull request on 'GitHub'?

I would like this pull request reopened and examined.

There was a stupid little mistake from the 'DNS servers', and the '_psl' whatever didn't work.

That is now fixed.

How do I get this pull request reopened and examined?

I don't know how to use 'Github' and all the instructions found via search engines are worthless.

How do I get this pull request reopened and examined?

**Pull request merged**
