### PR TITLE
Update Snowflake Inc domains in PRIVATE section

### PR DESCRIPTION
**Pull request by sfc-gh-shaar**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Snowflake is a major cloud data warehousing and analytics solution. Streamlit is a Snowflake product, that turns data scripts into shareable web apps in minutes. All in pure Python. No front‑end experience required.

I'm a Software Engineer on the Streamlit team at Snowflake .

Organization Website: https://www.snowflake.com/

Reason for PSL Inclusion
====

This PR modifies two domains previously added in https://github.com/publicsuffix/list/pull/1634.  The URL scheme is being updated and we're now including a wildcard in the leftmost label of the eTLD.

Number of users this request is being made to serve

snowflake.app and privatelink.snowflake.app will serve the very many Snowflake users. The exact number I'm not at liberty to disclose, but it's a large amount. If this isn't satisfactory please let me know.
We provide customers with a unique subdomain from this set.
We want our customers' apps to be fully isolated from each other (cookies, etc.)
We want to prevent setting cookies on the apex domains.

Number of users this request is being made to serve:

DNS Verification via dig
=======
```
dig +short TXT _psl.snowflake.app
"https://github.com/publicsuffix/list/pull/1634 https://github.com/publicsuffix/list/pull/1743"

dig +short TXT _psl.privatelink.snowflake.app
"https://github.com/publicsuffix/list/pull/1634 https://github.com/publicsuffix/list/pull/1743"
```

Results of Syntax Checker (`make test`)
=========

All tests pass

### CODE REVIEW

**Comment by dnsguru** [comment]
@sfc-gh-folapade what say you as original submitter?

**Comment by sfc-gh-shaar** [comment]
Hi @dnsguru 👋  Thanks for taking a look.
@sfc-gh-folapade was indeed the first on our team to submit for Snowflake back on https://github.com/publicsuffix/list/pull/1591, and is listed as the submitter in the list itself.
But the two domains modified here were actually submitted by me in https://github.com/publicsuffix/list/pull/1634

**Comment by sfc-gh-folapade** [comment]
Thanks for taking the time to do this. 

Will it be possible to assign this approval rights to another GitHub account?

**Comment by sfc-gh-shaar** [comment]
Hi @dnsguru, this PR has been open for a while now, is there anything I can do to help get it merged?  Thanks so much.

**Review by simon-friedberger — CHANGES_REQUESTED** [review]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] snowflake.app expires 2027-05-15
* [x] DNS _psl entries
  * [x] _psl.snowflake.app
  * [x] _psl.privatelink.snowflake.app
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Comment by sfc-gh-shaar** [comment]
@simon-friedberger Thank you for taking a look.  Does the DNS challenge for `_psl.snowflake.app` not also provide proof for `_psl.privatelink.snowflake.app` since it's a subdomain?  Or do we need an explicit entry for each full domain?

I will update the email to be non-personal.

**Comment by simon-friedberger** [comment]
Yes, you should add a _psl. entry for all domains which you want to be public suffixes. .app is a public suffix but we still need you to provide proof for snowflake.app and so on recursively...

**Comment by sfc-gh-shaar** [comment]
@simon-friedberger 
1. I've updated the email contact to a company owned non-personal email
2. Added a TXT record for DNS verification for `_psl.privatelink.snowflake.app` and updated the PR description accordingly.

**Comment by sfc-gh-shaar** [comment]
Hi @dnsguru, this has been approved by @simon-friedberger, would very much appreciate if we can get this merged as it's been open for almost a full year now, is there anything blocking? Thank you so much for taking a look.

**Comment by danderson** [comment]
@sfc-gh-shaar As part of writing https://github.com/publicsuffix/list/pull/2160 to verify _psl TXT records, `*.snowflake.app` and `*.privatelink.snowflake.app` are currently failing validation, because their _psl records list both #1743 and #1634, and the wildcards don't exist in the latter.

These two suffixes are the only ones in this situation, so rather than writing more code to handle this case, could I trouble you to update the TXT records for `_psl.snowflake.app` and `_psl.privatelink.snowflake.app` to contain just `https://github.com/publicsuffix/list/pull/1743` ?

**Pull request merged**
