### PR TITLE
Add dattoweb.com, dattorelay.com, dattolocal.net, dattolocal.com, mydatto.net and mydatto.com

### PR DESCRIPTION
**Pull request by binwiederhier**
[Datto](https://www.datto.com/) is a backup and disaster recovery company. We sell backup appliances and we'd like to add Let's Encrypt based HTTPS support with custom domains to them.  

```
$ dig TXT _psl.dattolocal.net +short
"https://github.com/publicsuffix/list/pull/624"

$ dig TXT _psl.mydatto.net +short   
"https://github.com/publicsuffix/list/pull/624"

$ dig TXT _psl.dattoweb.com +short   
"https://github.com/publicsuffix/list/pull/624"

$ dig TXT _psl.dattolocal.com +short
"https://github.com/publicsuffix/list/pull/624"

$ dig TXT _psl.dattorelay.com +short
"https://github.com/publicsuffix/list/pull/624"

$ dig TXT _psl.mydatto.com +short 
"https://github.com/publicsuffix/list/pull/624"
```

Edit: All domain TXT records have now been propagated.

### CODE REVIEW

**Comment by frju365** [comment]
I didn't understand the reason of the request. But if it's to circumvent the Let's Encrypt rate limits, you must fill in this form : https://letsencrypt.org/docs/rate-limits/ We don't validate request with this reason (https://github.com/publicsuffix/list/wiki/Guidelines#validation). Can you detail the resaon pls ?

**Comment by binwiederhier** [comment]
My apologies for not being detailed enough. I didn't know a detailed description was necessary. I am aware that Let's Encrypt has a rate limit form. We do intend to also submit a rate limit exemption request there. 

However, there are a few reasons why we are **also** requesting to be added to the PSL:

- Two of the above mentioned domains are already used to remotely access devices behind a NAT via tunneling, so https://device1.dattoweb.com and https://device2.dattoweb.com are two completely different, user controlled devices (device1.dattoweb.com will be a tunnel to device 1 owned by user 1, and device2.dattoweb.com will be pointing to device 2 owned by user 2). In this case shielding user cookies is necessary.

- The other domains will be used to provide secure local access to devices inside the LAN via a local DDNS service and HTTPS certs from Let's Encrypt. So again, https://device1.mydatto.net and https://device2.mydatto.net point to two completely different user controlled devices. Again, shielding users is desired.

I hope this explanation is enough. Let me know if you need more detail.

**Comment by binwiederhier** [comment]
Hello again. Is this description sufficient? Can I provide more clarity somehow? 
Happy weekend!

**Comment by sleevi** [comment]
Note: Issues are processed in reverse order, as time permits, with the oldest first. These friendly bumps therefore keep moving it to the back of the queue.

**Comment by sleevi** [comment]
Note that the sorting was not correct. However, it was simple enough to correct by hand that I did.  Please review the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) in the future :)

**Pull request merged**
