### PR TITLE
Add ASUSTOR DDNS domain: myasustor.com

### PR DESCRIPTION
**Pull request by vincenttseng63**
This is Vincent Tseng from ASUSTOR Inc. Please add our DDNS domain name: myasustor.com to public suffix list, thank you.

### CODE REVIEW

**Comment by vincenttseng63** [comment]
Please let me know how to verify the pull request. I can be reached via vincenttseng@asustor.com. Thank you.

**Comment by weppos** [comment]
Please update the patch according to our Guidelines and add the relevant DNS records for validation.
https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by vincenttseng63** [comment]
The patch is updated and the required DNS record is added as well. Thank you.

$ dig TXT _psl.myasustor.com
https://github.com/publicsuffix/list/pull/167

**Comment by vincenttseng63** [comment]
We provide free subdomains under *.myasustor.com to our customers for remote accessing their NAS (network attached storage) and websites.

**Comment by vincenttseng63** [comment]
@weppos Is there any information missing for validating our request? Please advise, thank you.

**Pull request merged**
