### PR TITLE
Add `cf-ipfs.com`, `cloudflare-ipfs.com`, and `r2.dev`

### PR DESCRIPTION
**Pull request by mathew-cf**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowlegements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: 

Organization Website: https://www.cloudflare.com/

Cloudflare is an edge network offering a variety of services, often serving as a reverse proxy and firewall. There is an existing email alias to be contacted over ([publicsuffixlist@cloudflare.com](mailto:publicsuffixlist@cloudflare.com)).

Cloudflare provides CDN and DDOS protection, but we've recently launched [R2, an object storage platform](https://www.cloudflare.com/products/r2/). This storage platform allows users to easily store arbitrary disorganized data for their applications.

 I am an engineer working on web3 (including the IPFS Gateway) at Cloudflare. r2.dev is being added on behalf of @Frederik-Baetens who is an engineer on the R2 team.

Reason for PSL Inclusion
====

We're adding our IPFS gateways cloudflare-ipfs.com and cf-ipfs.com so that content served from the IPFS network is isolated per subdomain and to reduce the negative effects to the reputation of the domain.

Number of users this request is being made to serve:

Estimate of ~20k users/day based on Cloudflare's visit analytics.

Cloudflare R2 customers can make their buckets publicly available on r2.dev. When doing so, the customer gets a unique r2.dev subdomain associated with their specific bucket. These domains should be treated as separate domains for cookie purposes. Since these domains will often be used to serve files, things like "Sorting in the download manager" for Firefox will also be a nice added benefit.

Example of such a public url: https://pub-ae08589711b94eb3a7bf08c8750ccf2b.r2.dev/dog.jpg

Number of users this request is being made to serve: This would concern R2 customers, and all of their users, which is a large amount. The exact amount of customers is something I cannot disclose. If that's a problem, I can see if I can get permission to publish an approximate number.

DNS Verification via dig
=======

```
dig +short TXT _psl.cf-ipfs.com
"https://github.com/publicsuffix/list/pull/1582"
dig +short TXT _psl.cloudflare-ipfs.com
"https://github.com/publicsuffix/list/pull/1582"
 dig +short TXT _psl.r2.dev
"https://github.com/publicsuffix/list/pull/1582"
```

Results of Syntax Checker (`make test`)
=========

All 5 tests passed

### CODE REVIEW

**Comment by mathew-cf** [comment]
Hi, @dnsguru. Is there an issue with this PR or can it be merged at some point soon?

**Comment by dnsguru** [comment]
Had meant to do this and the r2 at same time but #volunteer got distracted by the stuff that pays for groceries and rent an all that today.

@mathew-cf can you see if the r2 PR didn't create a re-base conflict on this?

**Comment by dnsguru** [comment]
@mathew-cf @Frederik-Baetens please see if you can mash together #1582 and #1635 in one edit within this PR please so they don't "cross streams" in the bad, ghost-busters way.

**Review by dnsguru — CHANGES_REQUESTED** [review]
Please fix section sorting as done within #1635 and add the change from #1635 into this Pull Request so there's one "Cloudflare's stuff" PR to merge

**Comment by dnsguru** [comment]
Soooo close...   sort the entries by TLD then SLD (hint: TryCloudflare.com moves up above the .dev domains)

**Comment by Frederik-Baetens** [comment]
I've updated the verification record for r2.dev to point to this PR instead:

```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_psl.r2.dev.			IN	TXT

;; ANSWER SECTION:
_psl.r2.dev.		300	IN	TXT	"https://github.com/publicsuffix/list/pull/1582"
```

**Comment by mathew-cf** [comment]
Should be ready to go now :)

**Review by dnsguru — APPROVED** [review]
- DNS Validates
- Followed Guidelines
- No conflict w base
- Tests pass

APPROVED

**Pull request merged**
