### PR TITLE
Add dyn53.io

### PR DESCRIPTION
**Pull request by schiederme**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [ ] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://port53.io

I'm the owner of port53, which will run a Anycast DNS Network.

Reason for PSL Inclusion
====

Because user.dyn53.io is used for customers, Cookie Security would be crucial.

DNS Verification via dig
=======

```
dig +short TXT _psl.dyn53.io
"https://github.com/publicsuffix/list/pull/820"
```

make test
=========

I could not getting make test work. It throws errors (make not list errors)

### CODE REVIEW

**Comment by schiederme** [comment]
Maybe im just stupid. But I cannot find any infos regarding the make errors:
`sh: 1: aclocal: not found
autoreconf: aclocal failed with exit status: 127
Makefile:17: recipe for target 'libpsl-config' failed
make: *** [libpsl-config] Error 127`

**Comment by sleevi** [comment]
Note: Your organization is also not presently sorted

**Comment by schiederme** [comment]
@sleevi have seen it, working on a fix. Thank you for the information.

**Comment by schiederme** [comment]
The position should now be fixed, can you review if this is right?

**Comment by groundcat** [comment]
Hello @schiederme, it seems that the project or organization associated with your domain, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. If the service has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Pull request merged**
