### PR TITLE
Add minisite.ms

### PR DESCRIPTION
**Pull request by comstarsystemsltd**
* [x] Description of Organization
Organization Website: https://sendmsg.co.il
sendmsg provides solutions to business owners to communicate with their customers for about 10 years.
We provide a landing pages platform and serving solution for our customers.
Registered users get their own subdomain (e.g. username.minisite.ms) on which their sites are hosted.

* [x] Reason for PSL Inclusion
Some of our customers are using custom domain with their landing pages that created with our platform. However, some prefer to use a dedicated subdomain under the minisite.ms domain.

* [x] DNS verification via dig
$ dig TXT _psl.minisite.ms
#1344

* [x] Run Syntax Checker (make test)
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.
minisite.ms is valid till 2024-05-01

### CODE REVIEW

**Comment by dnsguru** [comment]
( Replaces: #1338 , #1341 )

__Submitter affirms the following:__ 
  * [ ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [ ] This request was _not_ submitted with the objective of working around other third party limits
  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

**Comment by dnsguru** [comment]
@comstarsystemsltd please tick the boxes on the affirmations above

**Comment by comstarsystemsltd** [comment]
> Submitter affirms the following:
> 
> * [x]   We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
> * [x]   This request was _not_ submitted with the objective of working around other third party limits
> * [x]  The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
> * [x]  The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Comment by dnsguru** [comment]
Good luck Assaf @comstarsystemsltd

**Pull request merged**
