### PR TITLE
Add `ctfcloud.net`

### PR DESCRIPTION
**Pull request by colomolo**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: [https://contentful.com](https://contentful.com)

Contentful is a content management platform, providing rich tooling to manage and serve your content across your products. Our customers can host their custom Contentful apps on a subdomains of `ctfcloud.net`. Each app have unique subdomain (<unique_id>.ctfcloud.net).

Reason for PSL Inclusion
====
Mainly because of cookie security:
- We provide each customer with a unique subdomain of `ctfcloud.net`.
- We want our customers' apps to be isolated from each other (cookies, etc.)
- We want to prevent setting cookies on the apex domains.

Number of users this request is being made to serve:
18000+ customers.

DNS Verification via dig
=======

```
dig +short TXT _psl.ctfcloud.net
"https://github.com/publicsuffix/list/pull/1700"
```

Results of Syntax Checker (`make test`)
=========
tests pass

### CODE REVIEW

**Comment by colomolo** [comment]
@dnsguru hello, this should be good to go.

**Comment by dnsguru** [comment]
> @dnsguru hello, this should be good to go.

Excellent.  Be patient.

**Comment by colomolo** [comment]
@dnsguru Hello, any plans to merge this?

**Review by simon-friedberger — CHANGES_REQUESTED** [review]
* [ ] Expiration
  * [ ] ctfcloud.net expires 2025-03-02
* [x] DNS _psl entries
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Comment by dnsguru** [comment]
There are branch issues - can you rebase please @colomolo

**Pull request closed without merging**
