### PR TITLE
Update `.fr` list, move some subspaces to PRIVATE section listing of `smallregistry.net`

### PR DESCRIPTION
**Pull request by jerome**
Reason for PSL Inclusion
====

- The AFNIC no longer manages the SLD list, now mostly handled by Smallregistry
- The French National Board of Surveyors (Ordre des Géometres-Experts) asks for their domain geometres-experts.fr to be remloved (contact: <ordre@geometre-expert.fr> )

### Checklist of required steps

* [X] Description of Organization
* [X] Robust Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [X] This request was _not_ submitted with the objective of working around other third-party limits

  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

SMALLREGISTRY manages .fr SLD

Organization Website: https://www.smallregistry.net

### CODE REVIEW

**Comment by dnsguru** [comment]
@jerome to conform to the sorting guidelinse, the smallregistry.net subsection and respective domain listings would belong in the PRIVATE section rather than the ICANN section alongside afnic's .fr delegation subsection.

Each moving string will require the DNS validation record.

**Comment by dnsguru** [comment]
In addition to the moving subdomains, for the removal of `geometres-experts.fr` this needs a DNS proof record for validation - we are a volunteer-based labor and only resourced to validate via DNS _PSL txt entry with the URL of this pull request for that domain.

**Comment by jerome** [comment]
> In addition to the moving subdomains, for the removal of `geometres-experts.fr` this needs a DNS proof record for validation - we are a volunteer-based labor and only resourced to validate via DNS _PSL txt entry with the URL of this pull request for that domain.

added !

**Comment by jerome** [comment]
> @jerome to conform to the sorting guidelinse, the smallregistry.net subsection and respective domain listings would belong in the PRIVATE section rather than the ICANN section alongside afnic's .fr delegation subsection.

done, thank you

**Comment by jerome** [comment]
/ping https://github.com/publicsuffix/list/pull/530#issuecomment-390482154 @weppos

**Comment by bortzmeyer** [comment]
Since PR #1732 has been merged, and since I work for Afnic, registry of .fr, and since, indeed, domains like avocat.fr are now "ordinary" domains for Afnic, I confirm that this demand by Promopixel / SmallRegistry (technical operator of these domains) is legit. These domains are indeed delegated and can be used for further delegation.
For the case of geometres-experts.fr, I defer to the domain name holder.

**Comment by dnsguru** [comment]
> * No Conflict with Base 
### Oops.

Actually, I noticed a conflict after the approval @jerome - this PR collides with subsequent restructuring of #1732  that was recently submitted where .fr changed within their ICANN section.  Would you be so kind as to rebase your pull request to resolve that conflict with the base?     You can either modify it here or close this one and make a new one (please reference #1621 in it so we keep the discussion thread for transparency). 

I will monitor this pull request to proceed once you have done this step.

**Review by dnsguru — CHANGES_REQUESTED** [review]
There is a conflict with the base as result of changes made in #1732 that allowed for approving #1621, can you re-base please or resolve the conflict with the base?

**Comment by dnsguru** [comment]
/ping @jerome please review this PR as there are some conflicts with the base that need your attention

**Comment by dnsguru** [comment]
/ping @jerome this will be closed without being applied if it does not get attention and updating by August 2023

**Comment by dnsguru** [comment]
Last chance @jerome

**Comment by dnsguru** [comment]
This has been replaced by #1823 but we will process that other pull request using the original date of THIS pull request

**Pull request closed without merging**
