### PR TITLE
Add `2.azurestaticapps.net` DNS suffix

### PR DESCRIPTION
**Pull request by joslinmicrosoft**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowlegements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://www.microsoft.com/

Reason for PSL Inclusion
====

Azure Static Web Apps allows users to host full stack web applications seamlessly. Users are given a generated hostname. We are further partitioning our DNS so that these generated domains may be a subdomain of the 2.azurestaticapp.net. We are adding this domain to the PSL to ensure one site cannot set a cookie for the whole domain.

DNS Verification via dig
=======

```
$ dig +short TXT _psl.2.azurestaticapps.net
"https://github.com/publicsuffix/list/pull/1604"
```

Results of Syntax Checker (`make test`)
=========

Ran `make test`, all tests pass.

### CODE REVIEW

**Comment by joslinmicrosoft** [comment]
Hi @dnsguru can you please help review or let us know if there are any other pending steps on us? Thank you!

**Comment by dnsguru** [comment]
We emailed the section contact and received a bounced message, so thus unable to verify the change with the listed contact address

"The group msftpsladmin only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list."

Please fix that

Meanwhile there are other requests in the queue ahead of this

**Comment by joslinmicrosoft** [comment]
Hi @dnsguru thank you for the update. We've updated the email list settings; can you please try again and let us know if you're able to send through now?

**Comment by dnsguru** [comment]
Retrying.  Please confirm https://github.com/publicsuffix/list/pull/1604 is
a desired change

**Comment by joslinmicrosoft** [comment]
Thanks @dnsguru! We received the retry and confirmed via email. Please let us know if there's anything else for us to do.

**Comment by joslinmicrosoft** [comment]
@dnsguru any updates here? Thanks.

**Review by dnsguru — APPROVED** [review]
* Validated PR Change out of band with submitter/section contact to ensure no dangling subdomains
* Conforms to Guidelines
* DNS Validation
* No Conflict with Base
* Tests Pass

**Comment by dnsguru** [comment]
Joseph

This was approved and merged and this likely crossed wires with the timing
on your most recent bump.

The PSL is a volunteer-based project, so it gets cycles as it does.

One way for more efficient processing of requests is for requestors to look
through and volunteer on reviews to offload the burden and backlog (and
"professional persistence" aka "bump"/"nudge" responses)

Being addative vs draining to cycles method is preferred to "bumps", but
most folks inappropriately assume this is some large multi-billion dollar
company vs a small volunteer-driven project.

**Comment by dnsguru** [comment]
Hi "Public Suffix List Admin" ***@***.***>

Please confirm https://github.com/publicsuffix/list/pull/1604 is a desired
change

Thank you from the PSL Maintaining Volunteers in helping us help you

-Jothan

**Pull request merged**
