### PR TITLE
Add lohmus.me to the private section

### PR DESCRIPTION
**Pull request by Repentinus**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

The Lõhmus Family

I am Heiki Lõhmus and I own the domain name `lohmus.me`, which I use to provide DNS services to various members of the Lõhmus family.

Reason for PSL Inclusion
====

The delegated zones under `lohmus.me` are operated by various family members of varying technical skill independently of each other. As a consequence, `lohmus.me` ought to be treated as a public suffix for the purposes of cookie security, HSTS preloading, and accessing third-party services such as Cloudflare and Let's Encrypt.

The domain has been registered for the maximum registration period of the `me` TLD (10 years) and I shall ensure that the remaining validity period is longer than two years while the domain remains listed as a public suffix.

```
$ whois lohmus.me
Domain Name: LOHMUS.ME
Registry Expiry Date: 2030-09-22T12:40:55Z
```

DNS Verification via dig
=======

```
$ drill TXT _psl.lohmus.me
;; ANSWER SECTION:
_psl.lohmus.me.	209	IN	TXT	"https://github.com/publicsuffix/list/pull/1161"
```

make test
=========

[All tests pass](https://paste.sr.ht/~repentinus/7c0c1d7ae1a5d36562f7d67c586383dd9b687e0f).

### CODE REVIEW

**Comment by fsodic** [comment]
Did you read Submitting Amendments (https://publicsuffix.org/submit/) ?

**accessing third-party services such as Cloudflare and Let's Encrypt.**

They was write about let's encrypt. And about cloudflare, what the service do you want with suffix?

**Comment by fsodic** [comment]
@dnsguru and @sleevi Sorry invite you, but if someone or some organization explain their reason about 3rd-party service it maybe will be a list that is full and will out of the original purpose of publicsuffix was founded

**Comment by dnsguru** [comment]
It is not stated outright, but because this is a globally used resource, there's a modest approach that should be taken on adding things, in order to respect that this is downloaded and used millions of times daily.

Additions which are for limited private use like this are typically declined, especially where the stated purpose is to work around Lets Encrypt or Cloudflare limits instead of working with the respective providers.

**Comment by Repentinus** [comment]
> Did you read Submitting Amendments (https://publicsuffix.org/submit/) ?

@fsodic, yes, I did. I also read [the guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation) on the wiki and noted the word "sole" there. The main reason for the pull request (listed first in the pull request) is cookie security. I do not trust the technical skills of everyone I wish to hand out delegated zones to. Furthermore, the purpose of this pull request is not to circumvent limits of third-party services, although it is a secondary objective to enable users of delegated zones to make their own decisions on the use of third-party services such as HSTS preloading, Cloudflare DNS and proxying, and Let's Encrypt without affecting the users of other delegated zones.

@dnsguru, I fully recognize and respect that inclusion is at the discretion of the list maintainers. However, I hope that the list maintainers recognize that if the Internet is to remain a truly open network and thrive, then there must be scope for people to offer network services, including DNS hosting, on a noncommercial, voluntary basis to friends and family while maintaining high levels of security and interoperability. From a networking perspective, people to whom I have delegated zones under lohmus.me should be able to use those zones for anything they could if all of us had chosen to buy delegated zones under lohmus.name from Verizon instead, and they should not be able to set cookies on lohmus.me and track visitors across the delegated zones. The number of people I am offering services to is small and they are related, but they are also very much mutually nontrusting for networking purposes.

Whether you decide to accept or reject the pull request, I am thankful for the time you have taken to review this.

**Comment by fsodic** [comment]
@Repentinus 
How your family member get the domain, is your authority or they register? explain it maybe can help the author to accept the request.
Like blogger, when some one register they can get the subdomain.blogspot.com.
How about this domain
Hope you enjoy this day

**Review by dnsguru — APPROVED** [review]
- description accepted
- test passes
- no conflict with base
- dns authentication ok

**APPROVE**

**Comment by dnsguru** [comment]
Upon further review this does describe a larger community and Heike thank you for all your past contribs to Free Software Foundation Europe.

**Pull request merged**
