### PR TITLE
Add netfy.app

### PR DESCRIPTION
**Pull request by Mavicsoft**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
    - <UPDATE THIS LIST WITH YOUR LIMITATIONS!>

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Netfy is a hosted platform where users get a free subdomain for creating and managing websites with minimal resources. Netfy is a web service initiated and managed by Mavicsoft.com, Mavic Platforms. The platform is particularly aimed at students and individuals who wish to perform web-related experiments, practicals, and projects. Each user on the platform gets their own domain like *.netfy.app. Netfy simplifies the process of web development by providing essential tools and services to get started quickly.

I am the Head of DevOps at Mavicsoft.com, Mavic Platforms.

Organization Website: https://mavicsoft.com

Reason for PSL Inclusion
====

We let multiple parties host different websites and do not want cookie pollution, or the risk of leaking cookies across domains.

Number of users this request is being made to serve:
Currently more than 100 and expecting more on this year

DNS Verification via dig
=======

dig +short TXT _psl.netfy.app
"https://github.com/publicsuffix/list/pull/1991"

Results of Syntax Checker (`make test`)
=========

### CODE REVIEW

**Comment by Mavicsoft** [comment]
dig +short TXT _psl.netfy.app
"https://github.com/publicsuffix/list/pull/1991"

**Comment by Mavicsoft** [comment]
dig +short TXT _psl.netfy.app
"https://github.com/publicsuffix/list/pull/1991"

**Comment by Mavicsoft** [comment]
dig +short TXT _psl.netfy.app
"https://github.com/publicsuffix/list/pull/1991"

**Comment by groundcat** [comment]
- The sorting looks correct to me.
- `netfy.app` expires on 2026-11-18, which is more than 2 years from now.
- The `_psl` record exists and is correct.
- The organization’s website https://mavicsoft.com matches what is described in the "Description of Organization" section.
- The organization’s website menu has a link to https://netfy.domains, which provides a domain registration service, matching the intention described in this PR.

Under the third-party limits you seek to work around, you have listed both Cloudflare and Let's Encrypt. If you are trying to circumvent limitations by Cloudflare and Let's Encrypt, you should contact them directly. If this is not your intention, you should remove those entries.

**Comment by Mavicsoft** [comment]
> Under the third-party limits you seek to work around, you have listed both Cloudflare and Let's Encrypt. If you are trying to circumvent limitations by Cloudflare and Let's Encrypt, you should contact them directly. If this is not your intention, you should remove those entries.

Actually that was a mistake while submitting the PR. Those entries should be removed. I can't find a way to remove those lines. Can you do that for me ?

**Comment by simon-friedberger** [comment]
> I can't find a way to remove those lines.

Click on the three dots of your initial comment and click edit.

**Comment by Mavicsoft** [comment]
> > I can't find a way to remove those lines.
> 
> Click on the three dots of your initial comment and click edit.

Thank you for your guide. Updated the content.

**Comment by simon-friedberger** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] netfy.app expires 2026-11-18
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

TY @groundcat

**Comment by Mavicsoft** [comment]
Got a notification that mentioning "tld-update / Check for TLD data updates 
Failed in 26 seconds". What should i do ?

**Comment by dnsguru** [comment]
> Got a notification that mentioning "tld-update / Check for TLD data updates Failed in 26 seconds". 

Where did this occur/who provided this notice?

> What should i do ?

Provide more detail on where this is occurring

If it is not from github or the PSL, contacting wherever that message came from is appropriate

The options here are to remove or add a listing

**Comment by Mavicsoft** [comment]
Received from Github. I think it's related to CI activity [ci_activity@noreply.github.com].

**Comment by Mavicsoft** [comment]
> Received from Github. I think it's related to CI activity [[ci_activity@noreply.github.com](mailto:ci_activity@noreply.github.com)].

Got it. That notification for my Fork.

**Comment by wdhdev** [comment]
@Mavicsoft Please place the `_psl.netfy.app` TXT record back in order to prevent a future removal, thank you. These are required to stay in place.

**Comment by Mavicsoft** [comment]
> @Mavicsoft Please place the `_psl.netfy.app` TXT record back in order to prevent a future removal, thank you. These are required to stay in place.

Done

**Pull request merged**
