### PR TITLE
Add seidat.net private domain

### PR DESCRIPTION
**Pull request by anschutz**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://www.seidat.com

Seidat is a cloud presentation platform for teams. I am responsible for the technology and infrastructure there.

Reason for PSL Inclusion
====

We'd like to let our customers run their own Google Tag Manger containers in a sandboxed iframe (hosted on seidat.net) for presentation analytics. Letting them run their GTM setup effectively means allowing them to execute any code in the iframe. Each team loads the iframe from its own subdomain (example: team_id.seidat.net). We'd like to restrict the ability to set cookies on the parent domain to isolate teams from one another.

DNS Verification via dig
=======

```
dig +short TXT _psl.seidat.net
"https://github.com/publicsuffix/list/pull/974"
```

make test
=========

Passed

### CODE REVIEW

**Comment by dnsguru** [comment]
Is this for an internal-use-only project?

**Comment by dnsguru** [comment]
@anschutz can you clarify the request?  Is this an internal-only namespace being requested?

**Comment by anschutz** [comment]
This domain will be used by our customers. We let them run their Google Tag Manager containers on this domain in an iframe that's baked into our production web app (https://app.seidat.com). So this is not for internal use. We have no control of what code our customers run in their Tag Manager containers.

**Comment by anschutz** [comment]
Adding to that, this is not for our customers' internal use either. This subdomain is used to run analytics of the slide decks our customers create using our app. Those slide decks are most of the time shared with anonymous visitors and are publicly available.

**Comment by dnsguru** [comment]
@anschutz thank you for the clarifications; approved and merging.

**Pull request merged**
