### PR TITLE
Add byen.site

### PR DESCRIPTION
**Pull request by yaslama**
P.P.COM (ppcom.fr via byen.site) offers our customers a website hosted in a domain *.byen.site
E.g.:  dupond-pierre-taxi.byen.site

Reason for inclusion
Cookie isolation. Each customer can partially modify himself his site so cookie isolation is needed for security reason.

### CODE REVIEW

**Comment by yaslama** [comment]
$ dig +short TXT _psl.byen.site
"https://github.com/publicsuffix/list/pull/490"

**Comment by tmm1** [comment]
Based on your example domain, the entry should not contain *. at the beginning.

The list should also be sorted alphabetically.

**Comment by yaslama** [comment]
Hi @tmm1,
1. I don't understand why do you think that the entry should not contain *.
2. In https://github.com/publicsuffix/list/wiki/Guidelines, I can read "Sort first by the TLD, then the first label to the left of the TLD, and so forth". So I think the order is right.

**Comment by tmm1** [comment]
If your example subdomain is `dupond-pierre-taxi.byen.site`, then the suffix should be `byen.site`. By adding `*.byen.site` to the suffix list, you are stating that no cookies can be set on `dupond-pierre-taxi.byen.site` or any other subdomain.

Please review the documentation on the list format.

**Comment by tmm1** [comment]
The order needs to be fixed now to be alphabetical.

**Comment by yaslama** [comment]
It's already sorted: site > fr

**Comment by tmm1** [comment]
Ah ok, you're right. 👍

**Comment by weppos** [comment]
Thanks @tmm1 for the support.

**Comment by tmm1** [comment]
Sure, reviewing all these PRs seems like a tedious and thankless job, so I'm happy to do my small part to help support the great work you all do.

**Pull request merged**
