### PR TITLE
Add jur.pro.br (see GH-324)

### PR DESCRIPTION
**Pull request by RegistryPRO**
Add Private Domain Section

+// Company : http://www.jur.pro.br
+// Submitted by Jean Turola suffix@jur.pro.br
+jur.pro.br

### CODE REVIEW

**Comment by RegistryPRO** [comment]
@weppos I thought the suffix .jur.pro.br had been included in the PublicSuffix.org list.

**Comment by sleevi** [comment]
I'm unable to find the TXT record for `_psl.jur.pro.br`

**Comment by RegistryPRO** [comment]
@sleevi I would like to change the suffix .jur.pro.br to .brbr.com.br

The TXT record of the same ID of the .jur.pro.br suffix was included in the suffix .brbr.com.br

$ Dig TXT _psl.brbr.com.br https://github.com/publicsuffix/list/pull/57747

The suffix .jur.pro.br will be replaced by the suffix .brbr.com.br!

sorry for the inconvenience

**Comment by RegistryPRO** [comment]
@sleevi

+// Company Registro de Domínios do Brasil : http://registro.brbr.com.br
+// Submitted by Saymon Rhuano: saymonrhuano@gmail.com
+brbr.com.br

$ Dig TXT _psl.brbr.com.br https://github.com/publicsuffix/list/pull/57747

**Comment by RegistryPRO** [comment]
Add TXT in .jur.pro.br

**Comment by RegistryPRO** [comment]
@sleevi @weppos Add TXT record in .jur.pro.br

**Comment by RegistryPRO** [comment]
"TXT" DNS records for jur.pro.br

:jur.pro.br. 1800 IN TXT "$ dig TXT _psl.jur.pro.br https://github.com/publicsuffix/list/pull/57747

**Comment by RegistryPRO** [comment]
@sleevi Could you test?

**Comment by weppos** [comment]
@RegistryPRO is this PR still valid? The DNS record does not resolve.

**Comment by RegistryPRO** [comment]
@weppos Can I reopen ISSUE and / or PR for jur.pro.br?

**Comment by RegistryPRO** [comment]
@weppos Reopen the PR of jur.pro.br, please.

Thank you

**Comment by weppos** [comment]
@RegistryPRO We tried to validate the request 3 times (including this one), and still there are no records. Please follow up once the DNS records are included.

Also please read https://github.com/publicsuffix/list/wiki/Guidelines and make sure your request follows the guidelines.

**Comment by RegistryPRO** [comment]
Please reopen the PR. I will do the management for validation now,!

**Comment by sleevi** [comment]
Please open a new one, making sure to read the Guidelines first. The number of issues had in doing this leaves me very worried that you are not aware of the risks of being added on the PSL, so if there are any issues with following the guidelines this last time, such requests will be closed.

**Pull request closed without merging**
