### PR TITLE
Remove domain no longer under Supabase control.

### PR DESCRIPTION
**Pull request by darora**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
    - [Cloudflare](https://developers.cloudflare.com/learning-paths/get-started/add-domain-to-cf/add-site/)
    - [Letsencrypt](https://letsencrypt.org/docs/rate-limits/)
    - <UPDATE THIS LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY! REMOVE THIS LINE!>

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Supabase builds and operates a Backend-as-a-Service platform (database, data APIs, realtime functionality, etc).

I work at Supabase on the Infrastructure team.

Organization Website: 

https://supabase.com/

Reason for PSL Inclusion
====

N/A - request is for removing a domain that was added by us in #1363 , but has expired and is no longer under our control.

Number of users this request is being made to serve:

N/A - request for removal

DNS Verification via dig
=======

Can't create the entry under the domain being removed as it is no longer owned by us. For verification, I've created a record under our primary domains:

```
> dig +short TXT _psl.supabase.com
"https://github.com/publicsuffix/list/pull/2037"

> dig +short TXT _psl.supabase.io 
"https://github.com/publicsuffix/list/pull/2037"
```

Results of Syntax Checker (`make test`)
=========

```
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by dnsguru** [comment]
This was noted in #1763 a year ago

**Comment by darora** [comment]
Linking to the correct PR: #1753

@dnsguru are we OK to remove the specific domain in this PR? Or are removals on hold pending a long-term solution?

**Comment by simon-friedberger** [comment]
For verifying, it would be helpful if @inian could comment here that this removal is indeed desired. If that is not a possibility I could also send an email to security@supabase.io and ask for confirmation. Let me know if you would like me to do that. @darora

**Comment by macgrayson** [comment]
> For verifying, it would be helpful if @inian could comment here that this removal is indeed desired. If that is not a possibility I could also send an email to [security@supabase.io](mailto:security@supabase.io) and ask for confirmation. Let me know if you would like me to do that. @darora

I'd suggest sending an email to confirm, just to be on the safe side. It looks like a third-party organization is already using this domain to offer free subdomain services. They're eager to scoop up expired domains listed in the PSL and provide services under those domains. They even advertise the domains as being in the PSL. For instance, the domain paba.se has already been used on a Chinese forum with claims that it can be used on Cloudflare simply because it is in the PSL.

Is there anything we can do to stop expired domains being re-registered and staying in the PSL?

image

image

**Comment by groundcat** [comment]
According to the WHOIS records, the domain was created after Subapase let it expire, likely being registered by a different party.

```
domain: paba.se
created: 2024-04-28
modified: 2024-05-27
expires: 2025-04-28
```

**Comment by simon-friedberger** [comment]
Confirmed by email.

**Comment by darora** [comment]
Sorry I missed your earlier comments; thanks for resolving over email!

**Pull request merged**
