### PR TITLE
add new domains for thingdust AG

### PR DESCRIPTION
**Pull request by adrianimboden**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====
Organization Website: https://thingdust.com

We are a small startup that provides a solution for measuring the occupancy of workplace environments (primarily shared desk and meeting rooms). Every customer gets his own instance with his own subdomain provided by us.

Reason for PSL Inclusion
====

A new product (reservd) is built in the same way (every customer has his own separate subdomain). We use these domains:
prod: customername.reservd.com
testing: customername.reservd.testing.thingdust.io
local dev: customername.reservd.dev.thingdust.io
disaster recovery test: customername.reservd.disrec.thingdust.io

We want as much isolation (Cookies Security, etc.) between the customers as possible, therefore we want to add the domains to the public suffix list.

We don't plan to cancel the registration. We confirm to hold the registration for longer than 2 years and will maintain the TXT section during that time.

Previous additions:
https://github.com/publicsuffix/list/pull/1031
https://github.com/publicsuffix/list/pull/767
https://github.com/publicsuffix/list/pull/419

DNS Verification via dig
=======
```
$ dig +short _psl.reservd.com TXT @8.8.8.8
"https://github.com/publicsuffix/list/pull/1361"
```

```
$ dig +short _psl.reservd.dev.thingdust.io TXT @8.8.8.8
"https://github.com/publicsuffix/list/pull/1361"
```

```
$ dig +short _psl.reservd.disrec.thingdust.io TXT @8.8.8.8
"https://github.com/publicsuffix/list/pull/1361"
```

```
$ dig +short _psl.reservd.testing.thingdust.io TXT @8.8.8.8
"https://github.com/publicsuffix/list/pull/1361"
```

make test
=========
Did run successfully

### CODE REVIEW

**Review by dnsguru — CHANGES_REQUESTED** [review]
Please revise to sort these by TLD, then SLD (.com before .io)

**Comment by adrianimboden** [comment]
:+1: 
I also fixed the order of the .ch domains which were already in there. I hope that is ok.

**Comment by dnsguru** [comment]
#419 #767 #1031 #1361
PSL Records intact 

```
_psl.cust.disrec.thingdust.io   text = "https://github.com/publicsuffix/list/pull/419"
_psl.reservd.disrec.thingdust.io        text = "https://github.com/publicsuffix/list/pull/1361"
_psl.cust.testing.thingdust.io  text = "https://github.com/publicsuffix/list/pull/419"
_psl.reservd.dev.thingdust.io   text = "https://github.com/publicsuffix/list/pull/1361"
_psl.reservd.testing.thingdust.io       text = "https://github.com/publicsuffix/list/pull/1361"
_psl.cust.dev.thingdust.io      text = "https://github.com/publicsuffix/list/pull/419"
_psl.cust.prod.thingdust.io     text = "https://github.com/publicsuffix/list/pull/419"
_psl.firenet.ch text = "https://github.com/publicsuffix/list/pull/1031"
_psl.thingdustdata.com  text = "https://github.com/publicsuffix/list/pull/767"
_psl.svc.firenet.ch     text = "https://github.com/publicsuffix/list/pull/1031"
_psl.reservd.com        text = "https://github.com/publicsuffix/list/pull/1361"
```

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base
- Formatted / Sorted per Guidelines

**Approved**

**Pull request merged**
