### PR TITLE
Add hasura-app.io to the list

### PR DESCRIPTION
**Pull request by shahidhk**
Hasura issues sub-domain based project urls to its customers. These projects should not be able to set cookie anywhere else other than on their own root domain. Like herokuapp.com

### CODE REVIEW

**Comment by shahidhk** [comment]
```bash
dig TXT +short _psl.hasura-app.io
"https://github.com/publicsuffix/list/pull/203"
```

**Comment by shahidhk** [comment]
Hello, sorry for being pushy. We are kind-of waiting on this merge for our product launch. This is very important to us, otherwise we won't be able to securely provide different different accounts for users on our domain `hasura-app.io`. 

We badly need the cookie settings to be restricted. I know the maintenance is volunteer based. But, please let us know if can do something from our side to speed things up.

**Comment by gerv** [comment]
You do know that even if this change is merged, it will take weeks or months to propagate to all the clients?

**Comment by shahidhk** [comment]
Yes, we do understand. Delay in this merge will effectively affect the delay with clients also. At least we could be certain that the first step has been done.

**Comment by gerv** [comment]
Please make this PR match the guidelines, e.g. place entries in alphabetical order:
https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by shahidhk** [comment]
@gerv Sorry for the mistake, I thought the alphabetical order applies only within a group. Have updated the PR to sort by alphabetical order

**Pull request merged**
