### PR TITLE
Pull request for adding hb.cldmail.ru name

### PR DESCRIPTION
**Pull request by 13excite**
Pull request for adding hb.cldmail.ru names

### CODE REVIEW

**Comment by sleevi** [comment]
As per the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) please explain why you are making this request, and provide sample domains so we can help make sure the entries are correct.

**Comment by 13excite** [comment]
Hi @sleevi,
We are building a service which allows our users to create 4th level domains on hb.cldmail.ru and put their content on it. Similar to s3.amazonaws.com 
 Sample domain:
https://hb.cldmail.ru

Thank you.

**Comment by sleevi** [comment]
As per https://github.com/publicsuffix/list/pull/421#issuecomment-292625507 can you please provide example domains?

https://hb.cldmail.ru does not provide sufficient examples of your intended service (indeed, it somewhat conflicts)

Please also make sure you understand that adding that domain may prevent navigation to it. That is, some browsers will refuse to load https://hb.cldmail.ru, much like they would refuse to load https://com.

**Comment by 13excite** [comment]
Hi @sleevi,
A specific example of a domain:
https://test698853.hb.cldmail.ru/pub 
Yes, we are understand that adding that domain may prevent navigation to it.

Thank you.

**Comment by sleevi** [comment]
@13excite The example you provided does not suggest it needs the wildcard; that is, that `hd.cldmail.ru` would be sufficient as the rule. Could you explain why you changed it?

Ideally, if you could provide three example domains that demonstrate the fullness of the policy, that will reduce the time it takes to get this reviewed.

**Comment by 13excite** [comment]
Hi @sleevi,
Read again guidelines and rollback changed.

  As I wrote earlier, we are building a service which allows our users to create 4th level domains on hb.cldmail.ru and put their content on it. 
  Each customer's account will get its own domain, for example: example-test.hb.cldmail.ru .

As a concrete example, existing test domain: https://test698853.hb.cldmail.ru/

Thank you.

**Comment by sleevi** [comment]
I have fixed several of the errors on this pull request directly. However, please indicate the registered legal identity. E.g. is there a company called "Hotbox"? It appears Hotbox is just the name of the service provided by mail.ru.

Please correct the company name, ensure the entry appears in the PRIVATE section sorted by company name, and then we can proceed with this request.

**Comment by 13excite** [comment]
Thank you @sleevi 
I changed service name  Hotbox on registered legal identity Mail.Ru Group and changed position on private domains list

**Pull request merged**
