### PR TITLE
add `preview.wdh.app` and `t.hrsn.net`

### PR DESCRIPTION
**Pull request by wdhdev**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

I am an individual software engineer who hosts websites, APIs, automation tools, etc for my clients which are usually small businesses or organisations.

Organization Website: 

https://wdharrison.com

Reason for PSL Inclusion
====

Pretty much the same rationale as in my original PR #2067.

- Cookie security: Preventing super cookies & ensuring sites on subdomains stay separate.
- URL highlighting: Shows the end user that these subdomains are separate from each other (as different parties manage them)

Domain usage:
- preview.wdh.app: Used for previewing deployments before they go to production on the root domain (wdh.app).
- t.hrsn.net: An [ngrok](https://ngrok.com)-like tunneling system via SSH.

Number of users this request is being made to serve:

1,500+ monthly unique vistors, due to be more as our infrastructure continues to grow.

DNS Verification via dig
=======

```
dig +short TXT _psl.preview.wdh.app
"https://github.com/publicsuffix/list/pull/2119"
```

```
dig +short TXT _psl.t.hrsn.net
"https://github.com/publicsuffix/list/pull/2119"
```

Results of Syntax Checker (`make test`)
=========

All tests passed.

### CODE REVIEW

**Comment by wdhdev** [comment]
This PR will remain in draft until I have finished configuring the infrastructure behind these subdomains. Will likely take less than 2 days.

**Comment by groundcat** [comment]
* [x]   Expiration (Note: Must STAY >2y at all times)
   * [x]  wdh.app expires `2027-07-13T05:45:17Z` > 2 years, OK
 * [x]   DNS _psl entries (Note: Must STAY in place)
   * [x]  `_psl.preview.wdh.app` OK
   * [x]  `_psl.tunnel.wdh.app` OK
 * [x]   Tests pass
 * [x]   Sorting
 * [x]   Reasoning/Organization description
   * The scenario and reasoning make sense to me regarding the need to prevent super cookies and ensure that sites on subdomains remain separate, which indeed requires the inclusion of the PSL. Just a few quick questions: Are all 1,500+ monthly unique visitors you mentioned going to use both `preview.wdh.app` and `tunnel.wdh.app`? If you could roughly provide a breakdown of the service usage by individual third-level domains, that would be great (e.g., how many third-level subdomains are expected to be issued, even if they are short-lived). Are both subdomains (preview and tunnel) used for intranet tunneling or no SSL/self-signed SSL, and is this probably why we don't observe any usage through CT for third-level domains (since CA-issued SSLs, even short-lived sites, would usually appear in CT logs)? Thanks!!
 * [x]   Non-personal email address

**Comment by wdhdev** [comment]
Cloudflare (the analytics software I use) only provides those statistics for the entire domain including subdomains so I cannot give specific analytics per 3rd/4th level domains. As for the amount of subdomains I can provide a very rough estimate:
- `preview.wdh.app`: Likely up to 25 **active** preview deployments at once. These deployments will likely last longer than tunnels as they are mainly used when previewing deployments on pull requests.
- `tunnel.wdh.app`: Around 3-5 **active** tunnels at once, could be more, could be less depending on the amount of users using them.

There will not be very many SSL certificate logs under `preview.wdh.app` or `tunnel.wdh.app` as we use a single wildcard certificate for each service issued for `*.{preview,tunnel}.wdh.app` in order to prevent any potential rate limits, etc. We tend to not issue SSLs at the 4th level.

Please note, service infrastructure has not been deployed for `tunnel.wdh.app` yet, which is why this PR is in draft and you won't see any activity under it. Once the infrastructure for `tunnel.wdh.app` has been deployed I'll mark this PR as ready.

**Comment by wdhdev** [comment]
All infrastructure has been deployed, and this PR is ready to review.

**Comment by wdhdev** [comment]
I've moved my tunnel service from `tunnel.wdh.app` to `tunnel.hrsn.net` due to the SSL requirements on the .app TLD. 

The `_psl` TXT record has been placed at `_psl.tunnel.hrsn.net` and the domain has been renewed up to 2027-03-25.

**Comment by simon-friedberger** [comment]
Can you elaborate and add a link to those requirements, please?

**Comment by wdhdev** [comment]
@simon-friedberger The registry (Google) behind the `.app` TLD requires SSL certificates for all `.app` domains in order to keep a secure namespace. I moved from `tunnel.wdh.app` to `t.hrsn.net` due to these requirements as we offer TCP tunnels where having an SSL certificate is not very possible.

You can see the registration policy here: https://www.registry.google/policies/registration/app/

**Comment by simon-friedberger** [comment]
Oh, so they actually require a website for all domains? Including all subdomains?

**Comment by wdhdev** [comment]
> Oh, so they actually require a website for all domains? Including all subdomains?
> 
> I don't really understand. If there is a website it makes sense to require HTTPS and if there is no website it's not entirely obvious that one is required. Anyway, there is probably no point in discussing this here.

What they mean is if you have a site hosted on a .app domain it must use an SSL certificate or it will not resolve in the browser. Basically they force HTTPS. They don't require you to host a website, it's just if you do you need it to have an SSL certificate.

**Pull request merged**
