### PR TITLE
Add reliqs.net as Private Domain

### PR DESCRIPTION
**Pull request by sermore**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====
Individual, hosting for personal use only
Organization Website: www.reliqs.net

Reason for PSL Inclusion
====
In order to publish gitlab's pages, there is the need to have different cookie security management for each subdomain.
Confirm that registration term is longer than 2 years and it will be maintained for more than 1 year.

None

DNS Verification via dig
=======
dig +short TXT _psl.reliqs.net
"https://github.com/publicsuffix/list/pull/1153"

make test
=========

```
===========================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-public
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Please expand the description of the number of users that this benefits, and what this is for aside from working around gitlab limits or cookie configuration.  

The description and reason for this PR, as provided, currently reads as being specifically a personal, private project.  With the information currently provided, it is unclear that there is justification to place this entry on a globally distributed resource.

**Comment by sermore** [comment]
> Please expand the description of the number of users that this benefits, and what this is for aside from working around gitlab limits or cookie configuration.
> 
> The description and reason for this PR, as provided, currently reads as being specifically a personal, private project. With the information currently provided, it is unclear that there is justification to place this entry on a globally distributed resource.

Actually there aren't any users apart me, because, as you said, this is a personal, private domain being used to publish my personal tools and projects.
My request was only driven by the need to have different cookie settings for each subdomain (and, by the way, suggested by gitlab guide https://docs.gitlab.com/ee/administration/pages/index.html#add-the-domain-to-the-public-suffix-list).
I frankly missed the point about the fact that the acceptance of this request is related to public interest or business only.
If this is the case, please disregard my request and accept my apologies.

**Comment by fsodic** [comment]
@sermore ,
There may be a slight misconception about cookie security. When one or several domains are only used for personal (in this case you yourself) you do not need to worry about this security where people will not be able to set cookies for other people.
To set the cookies differently on each subdomain level you can use the subdomain level in the cookie paths sub1.example.com, sub2.example.com, and so on.

Maybe my words above are my personal views or opinions and my experience about cookies in the internet world since 2014.

Why doesn't this PR need to be made public? This is because only you are the user and there are no worries about other users (apart from your server security).
Sorry my English not good.

**Comment by sermore** [comment]
Hi @fsodic,
Thanks for your clarification, anyway the fact that this domain is related to an individual, or being for personal use only, doesn't implies that there couldn't be other users (thought quite limited in number) accessing it.
I'm just trying to understand if this acceptance is subjected to the number of user being served, because in that case I don't think of being in a good position to achieve it ;)
Thanks again for your time.

**Comment by dnsguru** [comment]
hi @sermore - This file is downloaded millions of times daily and because this is a widely downloaded resource, the bias is to keep it as modest as possible and focus on larger project audiences (I am picking a number from the air) of at least 100 and perhaps 1000 subdomain users, and decline individual or small group projects out of respect to the larger community.

If I am misunderstanding the description of the purpose and rationale for your PR, I'll leave this open for you to revise it if it were describing a larger user base, otherwise it would likely not be approved, and ask you to close the request

**Comment by sermore** [comment]
Hi @dnsguru,
Thanks for your clarification, I see your point and I'm going to close the request.

**Pull request closed without merging**
