### PR TITLE
Adds umbraco.io domains

### PR DESCRIPTION
**Pull request by Shazwazza**
Adding umbraco.io and *.umbraco.io to the list for our upcoming Umbraco as a service release

### CODE REVIEW

**Comment by gerv** [comment]
These two rules contradict each other. Say you have a domain "www.foo.umbraco.io". The first rule says that "www.foo" is the registered part and "umbraco.io" is the suffix. The second rule says that "www" is the registered part, and "foo.umbraco.io" is the suffix. Which is it? :-)

**Comment by Shazwazza** [comment]
Hi, thanks for the reply and clearly I've misunderstood :)

I was under the impression that with these rules

> umbraco.io
> *.umbraco.io

* Cookies may not be set for umbraco.io
* Cookies may not be set for foo.umbraco.io
* Cookies may be set for foo.bar.umbraco.io

But I guess the first rule is not necessary? The domains hosted under umbraco.io will always be 4 levels, like: foo.bar.umbraco.io and hello.world.umbraco.io but never foo.umbraco.io or just umbraco.io.

**Comment by gerv** [comment]
Actually, exactly how the PSL should behave for umbraco.io when it has simply the following rules:

```
io
*.umbraco.io
```

is currently a matter of debate. So we should make it clear by including the additional rule.

Gerv

**Comment by gerv** [comment]
@Shazwazza: this got reverted due to test failures. Can you open another PR to add it again, and we can continue the discussion?

Gerv

**Pull request merged**
