### PR TITLE
Adding regional domain `bielsko.pl`

### PR DESCRIPTION
**Pull request by marceli7**
### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

University of Bielsko-Biala (legal Polish name: Akademia Techniczno-Humanistyczna w Bielsku-Białej) is a public university in Bielsko-Biała (currently the only one).
University is managing regional domain and allows external companies/entities to register the subdomains.
Academic Centre of Informatics (ACI) is the IT organization within the University, coordinating the process of registration and managing the domains.

Organization Website: https://www.ath.bielsko.pl/

Reason for PSL Inclusion
====

Number of users this request is being made to serve: over 600

* University provides each customer with a unique subdomain of bielsko.pl.
* External entities' apps should be isolated from each other (cookies, etc.)
* University seeks to prevent setting cookies on the apex domains.

DNS Verification via dig
=======
```
dig +short TXT _psl.bielsko.pl
"https://github.com/publicsuffix/list/pull/1749"
```

Results of Syntax Checker (`make test`)
=========

```
PASS: libpsl_icu_load_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-registrable-domain
  CCLD     test-is-public
  CCLD     test-is-public-all
PASS: test-is-public-builtin
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by simon-friedberger** [comment]
Similar to https://github.com/publicsuffix/list/pull/1726

**Comment by simon-friedberger** [comment]
* [ ] Expiration (Note: Must STAY >2y at all times)
  * [ ] bielsko.pl expires 2024-12-31
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [ ] Reasoning/Organization description

**Comment by dnsguru** [comment]
agree with university exception

**Comment by simon-friedberger** [comment]
@marceli7 Any updates?

**Comment by marceli7** [comment]
Please hold. Working on expiration date and HTTPS support. Will update you once done.

**Comment by marceli7** [comment]
HTTPS is added. Expiry date is now 2026-12-31.

**Comment by simon-friedberger** [comment]
This looks good for PSL acceptance but just to point this out "bielsko.pl" has no HTTPS and then redirects to HTTPS with a cert that is not for the right domain. Going to "www.dns.bielsko.pl" directly works but the encoding of special characters is incorrect.

**Pull request merged**
