### PR TITLE
Update Public Suffix List for TicketSearch

### PR DESCRIPTION
**Pull request by tixblaker**
* [TicketSearch is a global ticketing platform offering next-generation services for venues to enhance customer experience with an affordable, efficient, and powerful self-managed solution. Built in collaboration with 700 venues and more than a thousand professionals across three continents, developers have incorporated SMART social-distancing technologies, virtual event integrations for both hybrid and streamed events, as well as merchandising modules. With a mobile-first approach, the platform provides customers quick and easy options to complete their transactions. Additionally, 37 visual intelligence dashboards, powered by Tableau, provide venue managers with real-time reports to optimize sales and marketing decisions. TicketSearch is live in USA, Australia, New Zealand, Mexico and Asia. ] Description of Organization
* [ Ticket have a multiple client, they want to manage their own business account with their on TicketSearch sub domains. For example (abc.sales.ticketsearch.com). Ticket search domain is already verified in own Facebook business account. So we have to register ticket search domain and client sub domain in PSL list so they can manage their own account] Reason for PSL Inclusion
* [ $ dig TXT _psl.artshouse.sales.ticketsearch.com
https://github.com/publicsuffix/list/pull/1520

$ dig TXT _psl.norpa.sales.ticketsearch.com
https://github.com/publicsuffix/list/pull/1520

$ dig TXT _psl.ticketsearch.com
https://github.com/publicsuffix/list/pull/1520] DNS verification via dig
* [Yes ] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [ ] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by dnsguru** [comment]
attempt at updating #1518 ;  Hoping the FB (meta) folk can come in and triage their client on this or comment on it running their gauntlet

**Comment by bedfordsean** [comment]
Flagging this one to our team that is checking requirements.

**Comment by lennyfb** [comment]
Confirming from the Meta perspective that we have worked with TicketSearch and carried out our checks, and to the best of our ability to understand, TicketSearch is a legitimate platform hosting use case that caters to multiple subdomain businesses and therefore has a legitimate reason to be placed on to the PSL for the purposes of cookie separation for each of those subdomains.

**Comment by dnsguru** [comment]
between this and #1518 there are two half-ish attempts at a PR.  Once the 10 item checklist is in place with responses on the active PR and 1520 or 1518 (whichever duplicate is not the active one) is closed by the requestor this will get a re-review

**Comment by tixblaker** [comment]
Updated https://github.com/publicsuffix/list/pull/1518 request now.

**Comment by tixblaker** [comment]
> between this and #1518 there are two half-ish attempts at a PR. Once the 10 item checklist is in place with responses on the active PR and 1520 or 1518 (whichever duplicate is not the active one) is closed by the requestor this will get a re-review

We have updated #1518 PR now.

**Pull request closed without merging**
