### PR TITLE
fix broken test case c.il

### PR DESCRIPTION
**Pull request by malkusch**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider prepending this line to the tests:
```
{ echo '<?php '; cat tests/test_psl.txt; } | php -l || echo "Invalid code in text file."
```

**Comment by malkusch** [comment]
No, this PR is only for fixing the syntax error. What you suggest should go in something like a .travis file.

**Comment by szepeviktor** [comment]
Yes. Of-course.

**Comment by yaneti** [comment]
Any particular reason this hasn't been merged yet ?

**Comment by malkusch** [comment]
let it brew a bit.

**Comment by szepeviktor** [comment]
An old PR has higher value?

**Comment by gerv** [comment]
Sorry for the delay.

Gerv

**Pull request merged**
