### PR TITLE
Update public_suffix_list.dat

### PR DESCRIPTION
**Pull request by 3aaber**
Adding ArvanCloud Edge Compute Domain to public suffix list

# Public Suffix List (PSL) Submission

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (`make test`)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the `_psl` TXT record in place in the respective zone(s).

__Submitter affirms the following:__ 

 * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

ArvanCloud does not submit suffixes to the Public Suffix List to work around rate-limits of any third-party products or tooling

 * [x] This request was _not_ submitted with the objective of working around other third-party limits.

 * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, and responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

 * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms to them.
 * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting.

---

For PRIVATE section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*. I could break my organization's website cookies and cause other issues, and the rollback timing is acceptable. *Proceed anyways*.
---

## Description of Organization

ArvanCloud is a cloud services provider, offering a wide range of cloud computing and content delivery network (CDN) services. 
The company aims to improve website performance and security by providing solutions such as cloud security, cloud DNS, cloud storage, edge computing and video streaming services.

**Organization Website:**

arvancloud.ir

## Reason for PSL Inclusion

ArvanCloud recently announced arvanedge.ir as a way to easily deploy serverless applications running on ArvanCloud Edge Compute Service.

ArvanCloud customers will given a subdomain of arvanedge.ir to which they can deploy their serverless applications. Because subdomains are each controlled by different customers, they should be treated as separate domains for cookie purposes.

I am an engineer on the EdgeCompute team at ArvanCloud. 

**Number of users this request is being made to serve:**

Around 20000 users.

## DNS Verification

```
dig +short TXT _psl.arvanedge.ir
"https://github.com/publicsuffix/list/pull/2205"
```

## Results of Syntax Checker (`make test`)

[make test output](https://pastebin.com/3mZWdkzV)

### CODE REVIEW

**Comment by wdhdev** [comment]
Yes, it is.

**Comment by wdhdev** [comment]
This all looks good. You just need to fix the sorting of your entry, then this PR should be good to go.

**Comment by 3aaber** [comment]
> fix the sorting of your entry

Thank you. Which part need to be fixed?

**Comment by wdhdev** [comment]
You need to move your entry out of the Amazon section.

**Comment by 3aaber** [comment]
I fixed it

**Comment by wdhdev** [comment]
This PR looks good to me 👍

**Comment by groundcat** [comment]
- [x]  Expiration (Note: Must STAY >2y at all times)
  - [x]  arvanedge.ir expires 2028-11-26 (WHOIS is not available for this TLD, expiry date provided by the requestor at https://github.com/publicsuffix/list/pull/2205#issuecomment-2400169572 )
- [x]  DNS _psl entries (Note: Must STAY in place)
  - `"https://github.com/publicsuffix/list/pull/2205"`
- [x]  Tests pass
- [x]  Sorting
- [ ]  Reasoning/Organization description
  - The use of the domain `arvanedge.ir` is detailed on the ArvanCloud website in their [documentation site](https://docs.arvancloud.ir/fa/edge-computing/trigger/path), which appears to be consistent with the description in this PR.
  - [CT](https://crt.sh/?q=arvanedge.ir) shows 59 certificates for subdomains. Additionally, 43 subdomains were identified by the [subdomain finder](https://subdomainfinder.c99.nl/scans/2024-10-09/arvanedge.ir). The [market share](https://w3techs.com/technologies/details/cn-arvancloud) seems substantial enough for PSL inclusion, assuming sufficient adoption of this service by ArvanCloud users.
- [x]  Non-personal email address

---

> Number of users this request is being made to serve:
> Around 20000 users.

@3aaber Is this user count an estimate of the number of ArvanCloud users who would specifically benefit from the PSL inclusion of the `arvanedge.ir` domain?

**Comment by 3aaber** [comment]
> @3aaber Is this user count an estimate of the number of ArvanCloud users who would specifically benefit from the PSL inclusion of the `arvanedge.ir` domain?

Yes It is, this new product will be available to current ArvanCloud CDN users that are about more than 20k.

**Pull request merged**
