### PR TITLE
Added Lokalized domain

### PR DESCRIPTION
**Pull request by ntaheij**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---

Description of Organization
====

Organization Website: https://lokalized.nl

Providing hosting for websites and servers. We are working on a platform that can host websites and provide a secure environment for testing and deployment. We also strive to make an option to proxy to your own server (like ngrok.io). Use cases are: proxying, hosting your static content and deploy scalable apps with for example multiple nodes.

Reason for PSL Inclusion
====

Needed for Cookie Security due to the different websites (with "subdomains") on the hosting. Due to having multiple websites hosted by different people, we want to make it as secure as possible, therefore needing the PSL which will make the sites less vulnerable for same-site attacks.

DNS Verification via dig
=======

```
dig +short TXT _psl.servers.run
"https://github.com/publicsuffix/list/pull/1390"
```

make test
=========
Done.

### CODE REVIEW

**Comment by bedfordsean** [comment]
As per #1245 please see the guidance from Facebook on how to proceed if this request relates to iOS/Facebook related advertising issues.

**Comment by ntaheij** [comment]
Sorry, I misread the article. Advertising is not the reason for this addition, I thought it was for something different.

**Comment by bedfordsean** [comment]
Thanks for coming back - for avoidance of doubt, please can you thumbs up react to this comment if you agree with the following as confirmation of the following statement, after which the PSL maintainers:

"I confirm that this pull request is not being raised in an attempt to work around or bypass browser restrictions put in place in iOS 14 for Facebook advertising purposes"

**Comment by ntaheij** [comment]
Yes, certainly.

**Comment by dnsguru** [comment]
The organization and reason responses were not very descriptive, but what was written 

>... Needed for recognition on Cloudflare ...

indicates that this PR aims to work around the limits that Cloudflare have in place, which is not aligned with the 
```"This request was not submitted with the objective of working around other third party limits"``` that was ticked above it.

Could there be a better description provided that would allow this to proceed, as it would be rejected in its current form.

**Comment by ntaheij** [comment]
Hello there, sorry for the confusion (again). 

I have edited the original post and I confirm the pull request was not made to bypass third party limits (I once again thought it meant something else and I am sorry for not fully reading the documentation attached).

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base
- Formatted / Sorted per Guidelines

**Approved**

**Pull request merged**
