### PR TITLE
Remove altoadige.it from list

### PR DESCRIPTION
**Pull request by gsmember**
altoadige.it is not a TLD

### CODE REVIEW

**Comment by daftano** [comment]
Hi @gsmember, thank you for highlight that issue.

According to nic.it _**altoadige.it**_ is a reserved name and should effectively act as a TLD as it is in the lists of domain names related to Italian Provinces (Appendix B).
According to nic.it regulation (3.3.2) 

> These domain names are not assignable and are an integral part of the organizational and geographical structure. They allow for the registration and maintenance of domain names under this structure.

However altoadige.it has been assigned to an Italian company. Suspecting it could not be an isolated case, I found that other "not assignable" domain names **_.it_** have been assigned.

To clarify that subject, I wrote to the nic asking to comment such discrepancy, providing a list of all other names registered to private persons and private and public organizations against that regulation. 

I don't know if the registry will revoke those assignations or amend the regulation. Until an official decision will be made, in my opinion, we should not change this list, as it looks to be the safer option to the general public.

Links to the regulation:

- in english: http://www.nic.it/sites/default/files/docs/Regulation_assignation_v7.1.pdf
- in italiano: http://www.nic.it/sites/default/files/docs/Regolamento_assegnazione_v7.1.pdf

**Comment by weppos** [comment]
The scope of this list goes beyond only TLDs.
See https://publicsuffix.org/

**Comment by gsmember** [comment]
@weppos Hi, I know that the list represents much more than TLDs. 
My problem is, that altoadige.it  can't be added to the CDN Cloudflare due to the fact that they are using this list.
altoadige.it is a local italian newspaper and they own the domain since 1998.
And we are the registrar and maintainer of this zone.

As @daftano pointed out nic.it's document should be considered as garbage as there are other zones assigned even if they are unassignable...

**Comment by daftano** [comment]
@gsmember I do not consider the regulation a garbage at all. Errors and typos happens as well as policies change. They're the authority designated by IANA to manage the .it zone that's why I requested the nic.it to comment about that. 

I understand you have a real not hypothetical case, but changes to this list may not be easily reverted. Hopefully the NIC will get back soon clarifying that matter. As registrar you may have a more direct communication with the NIC and get that matter clarified faster.

**Comment by gsmember** [comment]
@daftano Okay, thanks for your comment. I will also forward the request directly to NIC IT.

**Comment by weppos** [comment]
@gsmember it looks like the issue requires a little bit of more investigation effort. I am going to re-open it for now, as a reminder for myself.

Just keep in mind that I can't guarantee we will apply changes _because of Cloudflare_. In fact, we are not bounded to a specific consumer. Cloudflare _should_ provide a way to bypass the list (whatever use they do) on demand.

I'll keep you posted.

**Comment by gsmember** [comment]
@weppos Thanks for your answer. I turned to Cloudflare first. Unfortunately, they have referred me to this list because of lack of responsibility.

**Comment by gsmember** [comment]
Hello,
we got this answer from nic.it/register.it:

Italian:
faccio seguito al colloquio telefonico di poco fa per confermarti che il nome a dominio altoadige.it risulta correttamente assegnato a S.E.T.A. Spa dalla metà degli anni 90. Tale nome a dominio compare, al pari degli altri nomi a dominio corrispondenti ai nomi ufficiali delle regioni e delle provincie italiane, nell’appendice A e B del Regolamento di assegnazione e gestione dei nomi a dominio nel ccTLD .it come nome a dominio riservato e non assegnabile in quanto corrisponde appunto alla denominazione della provincia autonoma di Bolzano. Nel caso in cui l’attuale assegnatario (S.E.T.A. Spa) non sia più interessato a tale nome a dominio o lo stesso venga revocato per qualsiasi motivo entrerà a pieno titolo tra i nomi a dominio non assegnabili ed utilizzabile solo nella struttura geografica predefinita del  ccTLD .it. Tale situazione è evidente anche consultando il DB whois del Registro .it che per altoadige.it riporta:

whois -h whois.nic.it altoadige.it
[... whois altoadige.it ...]

English (my translation):
I'm following up the telephone interview just now to confirm that the domain name altoadige.it is correctly assigned to S. E. T. A. Spa since the mid-1990s. This domain name appears, like the other domain names corresponding to the official names of the Italian regions and provinces, in Appendix A and B of the Regulation for the allocation and management of domain names in the ccTLD. it as a reserved domain name and not assignable since it corresponds to the name of the autonomous province of Bolzano. If the current assignee (S. E. T. A.) Spa) is no longer interested in such a domain name or revoked for any reason will enter fully into the domain names that are not assignable and can only be used in the pre-defined geographical structure of ccTLD. it. Have a look at the DB whois 

... so I think in this case we have to re-contact Cloudflare and Microsoft (we can't use their service as well :( ) in order to implement some workaround and not to remove the domain from the public suffix list. What do you think?

Thanks again

**Comment by daftano** [comment]
I got a slightly different reply from the registry about altoadige.it. They say it was a typo, thus I asked about their plans to publish an updated version of the regulation removing altoadige.it from that list.

According to that reply, you may get a better outcome once available the updated regulation.
If they will stick with what they wrote to me, you may not need workarounds.

I'll update this thread when I'll get more on that.

**Comment by daftano** [comment]
According to last reply from the registry altoadige.it and aquila.it (the domains included in the list by mistake) "will be fixed on the occasion of next release of the regulation", but no date has been provided.

@gsmember @weppos

**Comment by dnsguru** [comment]
This has been open a long time and I wonder,  @daftano @gsmember is there an update?  working to merge or clear the old issues and PR within the PSL requests, and this has not had new information provided in a couple years.  It appears to need some regulatory / policy information from nic.it, according to the information in this thread.

**Comment by gsmember** [comment]
> This has been open a long time and I wonder, @daftano @gsmember is there an update? working to merge or clear the old issues and PR within the PSL requests, and this has not had new information provided in a couple years. It appears to need some regulatory / policy information from nic.it, according to the information in this thread.

Hi, as the domain altoadige.it is still on the list, we implemented a workaround long time ago. And nothing changed since then.

**Comment by dnsguru** [comment]
Thank you @gsmember - We will go ahead and close this for now - once there is some update from the registry, submit a PR at that time with the appropriate _PSL DNS validation for review or updating this.

**Pull request closed without merging**
