### PR TITLE
add bounty-full.com for skyhat.io

### PR DESCRIPTION
**Pull request by shanteadam**

### CODE REVIEW

**Comment by sleevi** [comment]
Can you please update this PR to adhere to the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

Further, as explained on the Guidelines, can you explain the motivation for this request? Particularly concerning are the names alpha and beta - we're strongly hesitant to add staging domains.

**Comment by shanteadam** [comment]
The staging sub domains will be generated on-demand by public users and can contain content generated by public users.

examples:
johnny.alpha.bounty-full.com
marysue.alpha.bounty-full.com
alphadog623.alpha.bounty-full.com

Since we will not control all content on these generated sub domains, the browser should not treat them with equivalent levels of trust.

**Comment by shanteadam** [comment]
I've altered my changes to be compliant with new guidelines. I have also added the necessary TXT records to our DNS.

**Comment by groundcat** [comment]
Hello @shanteadam , it seems that the project or organization associated with your domain, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. 

```
// Skyhat : http://www.skyhat.io
// Submitted by Shante Adam <shante@skyhat.io>
bounty-full.com
alpha.bounty-full.com
beta.bounty-full.com
```

If the service has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Pull request closed without merging**
