### PR TITLE
Adding ravendb.cloud domain to allow separation between users

### PR DESCRIPTION
**Pull request by ayende**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

I'm not sure if the above 👆 is intended for the reviewers or me to fill. Left it empty, but all the items here are checked.

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website - company - https://hibernatingrhinos.com/ - product - https://ravendb.net

Hibernating Rhinos produces the RavenDB database, a NoSQL Document Database that can run on premise or in the cloud.

We provide our users with clusters that are running on `ravendb.cloud` subdomains. Each customer has each own independent subdomain and they are completely isolated from one another.

Those database clusters are offered from https://cloud.ravendb.net and the actual clusters are hosted on `ravendb.cloud` subdomains.

Reason for PSL Inclusion
====

We want to ensure that there is a proper separation at the domain level as well, so a cookie on one user won't be accessible from another. We also user certificate authentication and it would be very useful in the browser understood that there is a security boundary between those domains for this reason.

We already have other domains on this list (`ravendb.run`, for example) for the same purpose and want to extend the same behavior to our cloud users.

We previously included domains in the following PR: https://github.com/publicsuffix/list/pull/535
This PR is an extension of this to a new domain that we are started user using after that PR was accepted.

DNS Verification via dig
=======

```
$  dig +short TXT _psl.ravendb.cloud
"https://github.com/publicsuffix/list/pull/1468"
```

make test
=========

I run this, output of that is here:

https://gist.github.com/ayende/fa98c80fd486658a6ac2f567b4cde445

### CODE REVIEW

**Comment by ayende** [comment]
This says 5 or 10 tasks pending - I intentionally left some checkboxes cleared, since I don't know if I or the reviewer should manage them.

**Review by dnsguru — CHANGES_REQUESTED** [review]
fix sorting - please put .cloud before .com

**Comment by dnsguru** [comment]
Submitter same as #535, upating same section.  Fix sorting and then we'll confirm all expiries and dns entry presence to validate

**Comment by ayende** [comment]
@dnsguru thanks, sorting fixed.

**Review by dnsguru — APPROVED** [review]
- DNS OK Validation
- Sorting / Guidelines compliant
- Tests Pass
- No Conflict with Base
- Updates existing entry - same submitter
 

APPROVED

**Pull request merged**
