### PR TITLE
Added on-web.fr (planet-work.com)

### PR DESCRIPTION
**Pull request by fvanniere**
on-web.fr is the subdomain for our shared hosting customers.

### CODE REVIEW

**Comment by weppos** [comment]
Please add the DNS records as required per our Guidelines.
https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by fvanniere** [comment]
I've added the TXT DNS record, sorry.

**Comment by sleevi** [comment]
This PR still needs to be sorted according to the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

**Comment by sleevi** [comment]
Closing this due to no response.

**Pull request closed without merging**
