### PR TITLE
Add `ngo.us` for the NGO.US Registry

### PR DESCRIPTION
**Pull request by alstrasolutions**
Public Suffix List (PSL) Pull Request (PR) Template
====

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

### Description of Organization

Organization Website: [https://client.ngo.us](https://client.ngo.us)

The ".NGO.US Registry" is a not-for-profit division of [Alstra Solutions Ltd.](https://alstra.ca) ([AS212387](https://bgp.he.net/AS212387#_whois)), a server hosting and digital marketing company federally registered in Canada since 2020. The .NGO.US Registry, as a division of Alstra, will serve as a domain registry for non-governmental organizations (NGOs) worldwide, providing a unique domain registration service. Our mission is to foster trust, enhance visibility, and bridge the digital divide for nonprofits.

As the Chief Information Officer of Alstra Solutions Ltd., I am submitting this PR on behalf of the ".NGO.US Registry" to include our domain `ngo.us` in the Public Suffix List. 

We are committed to supporting nonprofits by providing free .ngo.us domain names, aiming to empower NGOs and charities with authenticity, reach, and a distinct online identity. 

Including `ngo.us` in the Public Suffix List will benefit NGOs, charities, and nonprofit groups that will apply the `.ngo.us` domain names, especially in terms of cookies security.

We have carefully considered the potential impacts of this inclusion and understand the responsibility involved. 

I kindly request the review and consideration of our PR for the inclusion of ngo.us in the Public Suffix List. Thank you for your attention and support.

Reason for PSL Inclusion
====

The inclusion of `ngo.us` in the Public Suffix List is necessary for several reasons related to cookie security, Let's Encrypt issuance, and Cloudflare account splitting:

1. Let's Encrypt Issuance: Each domain under `ngo.us` will belong to a separate nonprofit organization. By being listed in the PSL, we can ensure that each nonprofit organization can obtain and manage its own Let's Encrypt certificate for its `ngo.us` subdomain using their standalone monthly limit. This separation allows for independent certificate issuance and renewal, enhancing the security and privacy of nonprofit organizations' websites.

2. Cloudflare Account Splitting: With `ngo.us` domains, each subdomain will represent a separate nonprofit organization. By including `ngo.us` in the PSL, we enable nonprofit organizations to create and manage their own individual Cloudflare accounts for their respective `ngo.us` subdomains. This account splitting ensures that each organization has full control over their Cloudflare settings, including DNS management, caching, security features, and other cf services.

3. **Cookie Security (the most important reason)**: The inclusion of `ngo.us` in the PSL is crucial for maintaining cookie security. With separate subdomains for each nonprofit organization, we can prevent cookies from being shared between different organizations' applications. This isolation enhances the security and privacy of user data, ensuring that sensitive information remains within the appropriate organizational context.

Number of users this request is being made to serve:

We aim to accommodate a significant number of nonprofit applicants in the future. We have already witnessed interest from nonprofits who have joined the waitlist, and as the waitlist continues to grow, the number of potential users for .ngo.us domains increases as well.

Our domain `ngo.us` has been renewed and is currently valid until 2030-05-25.

[WHOIS](https://www.whois.us/):

```
Domain Name: ngo.us
Registry Domain ID: D6147912-US
Registrar WHOIS Server: https://porkbun.com/whois
Registrar URL: www.porkbun.com
Updated Date: 2023-06-14T19:30:03Z
Creation Date: 2004-05-26T15:04:59Z
Registry Expiry Date: 2030-05-25T23:59:59Z
```

DNS Verification via dig
=======

```
$ dig +short TXT _psl.ngo.us
"https://github.com/publicsuffix/list/pull/1821"
```

Results of Syntax Checker (`make test`)
=========

```
Making clean in po
Making clean in include
Making clean in src
rm -f ./so_locations
Making clean in tools
 rm -f psl
Making clean in fuzz
 rm -f libpsl_icu_fuzzer libpsl_icu_load_fuzzer libpsl_icu_load_dafsa_fuzzer
Making clean in tests
 rm -f test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain
Making clean in msvc
Making check in po
Making check in include
Making check in src
  CC       libpsl_la-psl.lo
  CC       libpsl_la-lookup_string_in_fixed_set.lo
  CCLD     libpsl.la
Making check in tools
  CC       psl.o
  CCLD     psl
Making check in fuzz
  CC       libpsl_fuzzer.o
  CC       main.o
  CC       libpsl_load_fuzzer.o
  CC       libpsl_load_dafsa_fuzzer.o
  CCLD     libpsl_icu_load_fuzzer
  CCLD     libpsl_icu_load_dafsa_fuzzer
  CCLD     libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Just want to understand this correctly.  This is intended for USA NGOs but it is operated in Canada by a Canadian company, is this correct?

**Comment by alstrasolutions** [comment]
> Just want to understand this correctly. This is intended for USA NGOs but it is operated in Canada by a Canadian company, is this correct?

Thank you for your inquiry! Sorry, we should have included more details and clarifications in our PR. Yes - we are a Canadian company based in Toronto, Ontario [(Corporation No. 1339459-0)](https://ised-isde.canada.ca/cc/lgcy/fdrlCrpDtls.html?p=0&corpId=13394590&V_TOKEN=null&crpNm=Alstra&crpNmbr=&bsNmbr=&cProv=&cStatus=&cAct=) that is currently collaborating with a few nonprofit organizations in the United States and Canada as our clients. We are "a foreign entity or organization with a bona fide presence in the United States", as per the `.us` registry policies under [Nexus Category 3](https://www.about.us/cdn/resources/ebooks/policies/usTLD_Nexus_Requirements_Policy.pdf).

Although the eligibility criteria and registration procedures are still being finalized, we intend to offer `.ngo.us` domains to all non-profit organizations, whether they are based in the United States or elsewhere. 

We have been offering our existing NPO clients such as PAUSE, a US-based suicide prevention organization, with the domain name `pauseint.ngo.us` (which currently serves as a redirection) and Youth Mental Health Canada with internally-purposed domain names. Before the end of 2023, we will open the public registration and offer free renewals to all nonprofit organizations. Please feel free let us know if you require more information or documents.

**Review by simon-friedberger — CHANGES_REQUESTED** [review]
nic.ngo.us is defunct

**Comment by alstrasolutions** [comment]
Hello, Simon! Thank you for checking us out. Yes, we are still interested in this request, but we have been undergoing a rewrite of the registry's web services since January 16, 2024. This process only affects the website user interface, not the DNS functionality of our clients' currently registered subdomains. To avoid confusion during your review process, I'll mark this request as "Draft" and reopen it once we have the registry portal in order.

**Comment by simon-friedberger** [comment]
Please add user numbers to the initial PR description!

**Comment by simon-friedberger** [comment]
@alstrasolutions Any updates?

**Comment by alstrasolutions** [comment]
Hello @simon-friedberger, thank you for your follow-up. Apologies for the delayed response.

We are seeking clarification on the definition of "user number" since we function as a subdomain registry and do not have direct access to user statistics, unlike SaaS providers like `.canva[.]site` who are aware of their user count. Currently, we have 36 registered subdomains. Although we offer free subdomains to nonprofits, our manual review process limits the number of registrants. 

We reached out to some of our clients that we know well; one reported having 21,093 unique visitors in the last 30 days according to their nginx access logs. We are unsure if these incomplete figures can be considered as valid statistics for the PSL submission. The subdomain registry project remains actively maintained. One of our clients, a grassroot journalism group, raised concerns about security issues such as cookie separation, which prompted this PSL request.

However, if the number of users does not meet the PSL requirement, we understand completely and are prepared to close this pull request. Thank you for your volunteer efforts.

**Comment by simon-friedberger** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] ngo.us expires 2030-05-25
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Review by simon-friedberger — APPROVED** [review]

**Pull request merged**
