### PR TITLE
Remove: `gov.ky`

### PR DESCRIPTION
**Pull request by CIG-CSD**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.
Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  
The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://www.gov.ky

Reason for PSL Inclusion
====

Cayman Islands Government acquired the mentioned domain some time back and it seems it was added to the Public Suffix List on 2008-06-17 and the organization no longer requires the mentioned domain to be on the list. We would like it removed from the list.

DNS Verification via dig
=======

```
dig +short TXT _psl.gov.ky
"https://github.com/publicsuffix/list/pull/1503"
```

make test
=========
Tests have been executed successfully.

### CODE REVIEW

**Comment by dnsguru** [comment]
This appears to have come from the initial 'bootstrap' sources of the PSL - I have validated the DNS record, please leave it in place

**Review by dnsguru — CHANGES_REQUESTED** [review]
Have validated gov.ky in DNS via the _PSL txt record.

Please revise the .ky entries into alphabetical order by SLD in this patch
```
ky
com.ky
edu.ky
net.ky
org.ky
```

**Comment by CIG-CSD** [comment]
@dnsguru Revised the .ky into alphabetical order as requested.

**Review by dnsguru — APPROVED** [review]
- DNS Validated
- Formatted to Guidelines
- Tests Pass
- No Conflict with base

APPROVED 

Please note this was expedited to support important information sharing related to local covid pandemic resources

**Comment by dnsguru** [comment]
@CIG-CSD Merged

**Pull request merged**
