### PR TITLE
pro: Add new suffixes

### PR DESCRIPTION
**Pull request by weppos**
Validated using http://registry.pro/get-pro

> Select third level .PRO domains are also available including:
> law.pro, avocat.pro, bar.pro, recht.pro, jur.pro, cpa.pro,
> aaa.pro, aca.pro, acct.pro, med.pro, eng.pro.

/cc @sherwinflight

---

Closes GH-124

### CODE REVIEW

**Comment by gerv** [comment]
It seems like that list is not complete ("including:"). Should we drop them a line and suggest they give us a complete list?

But r=gerv for this change in the mean time.

**Comment by weppos** [comment]
@gerv I don't have any afilias contact and the .PRO was added in 2007. I've sent an email to them, I used the email address listed on the site.

I'll hold off the merge for one more day, in case they should respond to my email.

**Comment by weppos** [comment]
The response I got:

> Thank you for contacting .PRO Support.
> The one's listed are only second level zones we offer for .PRO.
> http://registry.pro/get-pro

**Pull request merged**
