### PR TITLE
Added EU (Stockholm) eu-north-1

### PR DESCRIPTION
**Pull request by panshap**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [ ] Run Syntax Checker (make test)

Reason for PSL Inclusion
Added eu-north-1  EU (Stockholm)

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by panshap** [comment]
Do i need to do anything else for this pull request ?

**Comment by sleevi** [comment]
Edit your initial PR to indicate the necessary steps have been completed,
such as the DNS verification and testing. Once you’ve done that, wait for
your turn in the queue.

**Comment by weppos** [comment]
> Do i need to do anything else for this pull request ?

@panshap FYI the verification DNS records have not been setup.

**Comment by sleevi** [comment]
@lawells Can you please ensure the necessary records are created?

**Comment by weppos** [comment]
Closing due to no follow up.

Friendly ping to @pzb if you want to assist @panshap with the patch getting merged.

**Pull request closed without merging**
