### PR TITLE
Add mintere.site

### PR DESCRIPTION
**Pull request by benaubin**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Mintere is a digital marketing company. We've launched a CMS for our users.

Organization Website: https://mintere.com/

Reason for PSL Inclusion
====

Users will be able to go to mintere.com, create a site and receive a *.mintere.site subdomain where they can place arbitrary content.

We'd like to be included in the list to improve our cookie security.

DNS Verification via dig
=======

```
dig +short TXT _psl.mintere.site
"https://github.com/publicsuffix/list/pull/993"
```

make test
=========

✅

### CODE REVIEW

**Comment by benaubin** [comment]
cc @weppos

**Comment by benaubin** [comment]
@sleevi Does this look okay?

**Comment by benaubin** [comment]
@dnsguru This all look good? 

By the way, have you considered adding a Travis check for DNS records?

**Comment by tomkln** [comment]
@dnsguru, just had a look at the PSL and saw that this entry was added to the very end of the list, therefore not being alphabetically sorted. Is this intended?

**Comment by groundcat** [comment]
@benaubin Do you still need this entry in the PSL? The domain `mintere.site` has been expired for over a month. The `_psl` record no longer exists. If the domain has been deprecated, let to expire, and is no longer associated with an active project, it would be great if you could submit a PR to rollback.

**Comment by benaubin** [comment]
Thanks for the reminder @groundcat! I'll submit a rollback

**Pull request merged**
