### PR TITLE
Added tabit.cloud, tabitisrael.co.il and tabitorder.com

### PR DESCRIPTION
**Pull request by orenagiv**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====
Organization Website: https://tabit.cloud/

Tabit is a restaurant ordering system as well as a point-of-sale that streamlines restaurant operations and extends sales opportunities.
Our 360 degree integrated ecosystem connects every aspect of the customer experience: from guest management, customer ordering and kitchen productivity to tableside payment, bringing efficiencies to every interaction point.

Reason for PSL Inclusion
====
Our clients (restaurants) are attempting to set up conversion tracking, and therefore inclusion in the public suffix list is required for the cookie security with changes in iOS 14.5 per https://www.facebook.com/business/help/331612538028890?id=428636648170202

We have 3 domains:
tabit.cloud
tabitorder.com
tabitisrael.co.il

DNS Verification via dig
====
```
dig +short TXT _psl.tabit.cloud
"https://github.com/publicsuffix/list/pull/1317"
```

```
dig +short TXT _psl.tabitisrael.co.il
"https://github.com/publicsuffix/list/pull/1317"
```

```
dig +short TXT _psl.tabitorder.com
"https://github.com/publicsuffix/list/pull/1317"
```

make test
====
Tests have been executed successfully.

### CODE REVIEW

**Comment by dnsguru** [comment]
#1245

**Comment by bedfordsean** [comment]
Hi @orenagiv,

Wanted to check on the rationale behind adding these domains to the PSL? I do not see individual subdomains that represent individual businesses for any of the domains you list above. 

The PSL is intended to be used to ensure cookie separation for individual businesses hosted on subdomains underneath your top level domain. You'll lose functionality on the top level domain by being on the PSL, and irrespective of being on the PSL, your clients do not avoid the requirement of having to verify their own domains.

Can you confirm for me that you understand the above and perhaps some example subdomains for the domains you are requesting additions to the PSL for?

**Comment by orenagiv** [comment]
Hey @bedfordsean,

Currently we do not yet have sub-domains on these domains of ours.
But it's in process, and we'll soon start having our sites migrated to the sub-domain level.

For example - Currently we have a site called CoffeeBar, here:
https://www.tabitorder.com/?siteName=coffeebar
But it will soon be converted to:
https://coffeebar.tabitorder.com/

We understand that our clients will still need to verify their (sub)domains.
And each client of ours - each sub-domain - is a completely separate business entity.

P.S.
You wrote "you'll lose functionality on the top level domain by being on the PSL" - which functionality were you referring to?

**Comment by bedfordsean** [comment]
Hi @orenagiv,

Yes, primarily cookie and local storage functionality on your root domain (and setting for subdomains) will be lost, however the browser behaviour for PSL domains is largely undefined - this means you may experience other inconsistent functionality behaviour on your root domain and we cannot be certain of that here as people who do not work on or maintain the browser functionality.

Some browsers may render and allow for functionality on this page, others may not, so this is just a warning to be careful with what you do on domains entered in the PSL because they may not function in the same way as previously post-addition. 

A further note is that browsers do not provide any guarantees of when they will update their own copies of the PSL, and therefore changes may come into effect for you at an unexpected time. For the same reason it's also hard to rapidly back out a change if you see something you weren't expecting. See https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion for more details.

If you're comfortable with all of this, please can you confirm here and we can take it from there?

**Comment by orenagiv** [comment]
Hey @bedfordsean 

Thanks so much for the clarification!
In this case - we will **cancel** our current pull-request, and we'll setup new domains for this purpose.
Please do **NOT** proceed.

**Comment by bedfordsean** [comment]
Thanks for confirming @orenagiv - glad we cleared this up. Please **close** this pull request to ensure it does not get actioned. When you have new domains ready, feel free to open another pull request and reference this one for previous reasoning/discussions.

**Pull request closed without merging**
