### PR TITLE
Update Futureweb OG Private Domains

### PR DESCRIPTION
**Pull request by futureweb**
Customer level Domains for Cloud CMS - Frontend arbitrary User Content & Backend Administration - Frontend + Backend Cookies - need seperation for security reasons

### CODE REVIEW

**Comment by futureweb** [comment]
- [x] DNS Authentication TXT entries added

```
[root@localhost ~]# dig +short TXT _psl.ex.futurecms.at
"https://github.com/publicsuffix/list/pull/520"

[root@localhost ~]# dig +short TXT _psl.in.futurecms.at
"https://github.com/publicsuffix/list/pull/520"
```

**Comment by daftano** [comment]
@futureweb could you please provide some existing examples?

**Comment by futureweb** [comment]
@daftano  - of course ... some Examples:

http://cutline.at.in.futurecms.at/
http://www.muehltalhof.at.in.futurecms.at/
http://www.bergrettung-stjohann-2017.at.in.futurecms.at/
http://www.vmfimmo.at.in.futurecms.at/

And there are thousands more ... ;-)

**Comment by sleevi** [comment]
@futureweb Can you expand on why you're continuing to add domains? That is, understanding what use case you're trying to accomplish, or what separation, is a way to inform the platform and consumers of the PSL as to gaps that may need to be addressed.

As the PSL is a static list, continued additions impose additional size constraints, especially for embedded and low-profile devices. In the effort of serving a broad spectrum of consumers, our goal is to minimize the need for additions as much as possible for a single organization. This is why it's important to understand why this structure.

From the looks of it, you're providing a form of 'proxying', which, like IP address redirection (e.g. `192-168-0-1.example.net`) is something that'd problematic.

**Comment by futureweb** [comment]
Hi @sleevi, 
we operate a rather Big Cloud CMS for our Customers and are in the process of switching over to a new URL-Schema (away from the kunden.ortsinfo/ex.ortsinfo Schema to futurecms) - As this Switch will take quite some time the new additions. 
Needed is Frontend/Backend Cookie isolation as for example one can reach the Administration with
futurecms.at/admin and also with customerdomain.futurecms.at/admin (which could lead to potenitally Security Issues because of the High-Level Cookies)
Sorry for that much new additions - we had a little lack of planning the switchover ... :/
Andreas

**Pull request merged**
