### PR TITLE
Added 0emm.com to Google's list

### PR DESCRIPTION
**Pull request by scottwug**
Hi Eduardo (@sirdarckcat),
This request is to add the root 0emm.com as well.
If *.0emm.com added last time already implied its root domain, please just ignore.

Thank you very much!
Scott Wu

### CODE REVIEW

**Comment by sleevi** [comment]
please explain why this is necessary.

From the documentation I have seen, it is not. Given the PSL is used in a wide variety of ways, there is a desire to keep it as minimal as is reasonable.

**Comment by scottwug** [comment]
You are right, from the document this should be implied. But we are not very clear about this, just in case for double check.

**Comment by sleevi** [comment]
As you can see, this PR creates conflicts for applications.

Since it is not necessary from the Google documentation I've seen, nor is it well supported (*.foo and foo both being added), in going to close this as WontFix. Provided you stick to your documented plan of x.y.0emm.com, you will have no issues.

**Comment by scottwug** [comment]
Cool, just want to confirm that x.y.0emm.com cannot put cookie on 0emm.com, is this true?

**Comment by sleevi** [comment]
Implementation defined due to historical ambiguities, but generally so across the platforms you care about.

**Comment by scottwug** [comment]
Great!
Thank you for your quick response, we really appreciate your help!

**Pull request closed without merging**
