### PR TITLE
add *.bbzw-labor.ch

### PR DESCRIPTION
**Pull request by adrianimboden**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [X] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [X] This request was _not_ submitted with the objective of working around other third-party limits

  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://beruf.lu.ch/bbzw

I am Adrian Imboden, a teacher at BBZW.
BBZW is a public school in lucerne, which among other professions, teaches computer science to young apprentices.

bbzw-labor.ch is the domain we want to use for our apprentices for various teaching purposes. For example, apprentice Jon Doe gets the domain: www.jondoe.bbzw-labor.ch to publish his webpage as part of a group project.
(labor is german for laboratory)

Reason for PSL Inclusion
====

We want the domain to be as close to reality as possible. The different webpages from our apprentices shall not interact with each other in any way. The domain will be used in the years to come, it is a permanent solution we want to use many years to come.

DNS Verification via dig
=======

```
$ dig +short TXT _psl.bbzw-labor.ch
"https://github.com/publicsuffix/list/pull/1543"
```

make test
=========

all passed

### CODE REVIEW

**Comment by cfredric** [comment]
How many users (globally) will benefit from having this TLD? (Given that this PR is for students of a single school, I'm not sure if this would be considered "too small" in scale, according to the 5th bullet of https://github.com/publicsuffix/list/wiki/Guidelines#validation-and-non-acceptance-factors.)

**Comment by adrianimboden** [comment]
Hi @cfredric
Hmm, the amount of users is hard to guess right now. Cumulated there may be more than a 1000 users over the years.

At the moment, the userbase will probably be considerably lower. It is up to you I would say. Not being on the list is not too big of a problem and when the userbase grows bigger, I will create a pull request again, if that is ok?

**Comment by cfredric** [comment]
That plan sounds reasonable to me.

(If hosting the students' sites on `bbzw-labor.ch` is not a hard requirement, there are also some existing project/education/blog-oriented sites that are already on the Public Suffix List, which you could use to isolate the students' projects from each other.)

**Comment by dnsguru** [comment]
@adrianimboden 

>Not being on the list is not too big of a problem and when the userbase grows bigger, I will create a pull request again, if that is ok?

If you'd close this request for now, and submit later once scale grows, that would be appreciated, and if/when you achieve 1000s + in scale please open a new Pull Request, but please reference this one.  Your (or your org) demonstration of helping us to respect the file size modesty would be on record and there'd likely be less resistance.

**Comment by adrianimboden** [comment]
Perfect, thank you very much.

**Pull request closed without merging**
