### PR TITLE
Add Amune.org to Public Suffix List

### PR DESCRIPTION
**Pull request by mindprotectionkit-admin**

### CODE REVIEW

**Comment by mindprotectionkit-admin** [comment]
Authentication Records added

;; ANSWER SECTION:
_psl.t3l3p0rt.net.	3600	IN	TXT	"https://github.com/publicsuffix/list/pull/357"

;; ANSWER SECTION:
_psl.tele.amune.org.	3600	IN	TXT	"https://github.com/publicsuffix/list/pull/357"

**Comment by mindprotectionkit-admin** [comment]
Reason:

We offer Browser VMs inside a web browser and need an entry in Public Suffix List to improve integration into client browsers (history, security). Thanks a lot

**Comment by mindprotectionkit-admin** [comment]
We are hosting VMs containing Browsers on behalf of our customers to make it more clear. Thanks

**Comment by groundcat** [comment]
Hi @mindprotectionkit-admin Do you still need this entry in the PSL?

- **Organization website**: https://amune.org/ (defunct)
- **tele.amune.org**: NXDOMAIN error
- **t3l3p0rt.net**: seems to have no active subdomains
- The described service "Browser VMs inside a web browser" appears to be terminated

The _psl record no longer exists. (Reminder: you need to keep the _psl records.)

If the domain has been decommissioned and is no longer associated with an active project as described in your original request, it would be great if you could confirm that it can be safely removed from the PSL. Then, please submit a PR to roll back and avoid leaving debris for PSL volunteers and future registrants to deal with.

**Pull request merged**
