### PR TITLE
Add `1.azurestaticapps.net` DNS suffix

### PR DESCRIPTION
**Pull request by joslinmicrosoft**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://www.microsoft.com/

Reason for PSL Inclusion
====
Azure Static Web Apps allows users to host full stack web applications seamlessly. Users are given a generated hostname. We are partitioning our DNS so that these generated domains may be a subdomain of the 1.azurestaticapp.net. We are adding this domain to the PSL to ensure one site cannot set a cookie for the whole domain.

DNS Verification via dig
=======
```
$ dig +short TXT _psl.1.azurestaticapps.net
"https://github.com/publicsuffix/list/pull/1514"
```

make test
=========

Ran `make test`, all tests pass.

### CODE REVIEW

**Comment by joslinmicrosoft** [comment]
Hi @dnsguru, I saw you added the pending-validation label. Is that indicating an action needed on my side? Thanks!

**Comment by joslinmicrosoft** [comment]
Hi @dnsguru are there any updates here?

**Comment by miwebst** [comment]
@dnsguru what is left here? I see the pending-validation tag but the dns records should be in place.

**Comment by dnsguru** [comment]
Sent note by email to head of corporate domains division to verify this request and have not heard a response.  PSL is resourced on a volunteer basis so it gets cycles as it does.

Just re-sent note to corp domains contact @ ms 

DNS record is validated, but want to confirm presense in GAL and otherwise validate this request w corp domains or azure team

**Comment by miwebst** [comment]
@Microsoft Corp. Domain ***@***.***> can y'all help with approving this request?

Thanks,

Mitch
________________________________

**Comment by miwebst** [comment]
Thanks @dnsguru, I will follow up with the domain team to get this sorted out.

**Comment by dnsguru** [comment]
Corporate domains were reaching out to @joslinmicrosoft about this last I spoke with them, so with efforts from both sides this hopefully can move forward.

**Comment by miwebst** [comment]
@dnsguru what is the corp domains contact that you have for Microsoft? I synced with @joslinmicrosoft and no one ever reached out to them. I heard from our domains team that they had not been reached out to either so there must be a communication drop somewhere.

**Comment by dnsguru** [comment]
@joslinmicrosoft @miwebst thank you for the patience here - this aids in some important safety checks - It appears that the mail alias discussion with corporate domains was implemented - which confirms to me that the loop was closed on folks connecting to discuss this.  The change will also be helpful for allowing future requests or changes to be more fluid.

**Comment by miwebst** [comment]
Hello Mitchell,

I'm not able to track down any mail from Jothan Frakes that was recently received by our team. The DomainsDNS team ***@***.******@***.***>) typically works on DNS requests and may have been contacted regarding this.

That said, it looks like azurestaticapps.net is pointing to an azure instance we don't have access to. The internal owners of the domain may be able to assist.  We have the internal owners listed as ***@***.******@***.***>.

Kind regards,

Jake Hewitt
Corporate Domains Analyst, Azure Core Networking
Microsoft Corporate Domains Team
Corporate Cookies
Office: (425) 707-3206 X73206
Allyis, Inc<http://www.allyis.com/> | Domains Manager<https://prod.msftdomains.com/> | CELAWeb<https://microsoft.sharepoint.com/sites/celaweb-copyrights-trademarks-and-patents/sitepages/corporate-domains-team.aspx>
***@***.***

**Pull request merged**
