### PR TITLE
Add new frusky.de

### PR DESCRIPTION
**Pull request by frusky**
* [x]  Description of Organization
* [x]  Reason for PSL Inclusion
* [x]  DNS verification via dig
* [x]  Run Syntax Checker (make test)

# Description of Organization
Organization Website: https://www.frusky

We build Solution for organizations deploying and provides web hosting and email services. I am the founder and director.

# Reason for PSL Inclusion
To simplify the onboarding experience, we want to give users the ability to dynamically register a DNS name that points to their Ambassador instance.

# DNS Verification via dig
```
:~dig +short txt _ps1.frusky.de
"https://github.com/publicsuffix/list/pull/1273"
```

# make test
```
============================================================================
Testsuite summary for libpsl 0.21.0
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Can you please provide a better rationale, and move the location of this section you are adding this into so that your company name is alphabetically sorted. within the PRIVATE serction.

**Comment by frusky** [comment]
We are a private company in the field of telecommunications and hosting. I assumed that alphabetical sorting is required. Sorry for troubles

**Comment by dnsguru** [comment]
Thank you for redoing the PR change to relocate to the PRIVATE section.

Can you confirm please that this is not being requested related to working around the issue described in #1245 related to IOS/Facebook?

Also please confirm that your request conforms to the contributing guidelines (link in footer at bottom of the PR page on Github)

**Comment by frusky** [comment]
> Thank you for redoing the PR change to relocate to the PRIVATE section.
> 
> Can you confirm please that this is not being requested related to working around the issue described in #1245 related to IOS/Facebook?
> 
> Also please confirm that your request conforms to the contributing guidelines (link in footer at bottom of the PR page on Github)

Yes, we confirm that our request is not related to # 1245. This is the first time I've heard this problem

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Comment by wdhdev** [comment]
@frusky Is this entry still needed? Your website doesn't appear to resolve.

**Comment by frusky** [comment]
> @frusky Is this entry still needed? Your website doesn't appear to resolve.

yes, after an dns-server move i forgott the settings

**Comment by groundcat** [comment]
Hi @frusky **do you still need the domain frusky.de to be included in the PSL?**
It appears that the project or organization associated with your domain, which was previously added to the Public Suffix List (PSL), may no longer be active based on current domain usage and availability checks. If the service has been discontinued and the domain is no longer associated with an active project, please confirm whether the entry can be safely removed from the PSL. _This helps keep the list accurate and avoids retaining unused entries when projects reach end of life. The PSL is a widely used resource relied upon by many applications and users worldwide, so entries should remain limited to projects that continue to require inclusion._ If your project is still active and requires continued PSL coverage, **please reply with confirmation** and ensure that the required verification records are maintained according to the [PSL guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), and that the domain remains properly renewed. If no response is received after a reasonable period, the entry may be considered for removal. Thank you.

**Pull request merged**
