### PR TITLE
Add Netlify domains

### PR DESCRIPTION
**Pull request by verythorough**
Netlify deploys websites for customers under subdomains at *.netlify.com and *.bitballoon.com.

Examples:
* https://opensmc.netlify.com/
* https://special-tester.bitballoon.com

Adding DNS records when we have a PR number.

### CODE REVIEW

**Comment by verythorough** [comment]
Fixed the domain order (d'oh!) and added the proper DNS records:

screen shot 2017-06-17 at 2 16 27 pm

**Comment by sleevi** [comment]
Can you please include answers to the questions in https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change

**Comment by verythorough** [comment]
- Each website we deploy under the above subdomains is controlled by a different customer. Inclusion on the list would help prevent multi-site cookies.
- I don't know what you're looking for in terms of "expected input/output," but I don't think we need help validating the correctness of the request.
- I can think of no other useful information to add, but am happy to provide more on request.

**Comment by verythorough** [comment]
@sleevi Please let me know if there's any other information you need.

**Comment by fu-sen** [comment]
@verythorough,
I know that Netlify has recently switch from `netlify.com` to `netlify.app`.
Reminds you of the addition here.
You may also need to delete `bitballoon.com`.

**Comment by verythorough** [comment]
Yes, thank you! We have it on our migration to-do list. :)

**Comment by fu-sen** [comment]
You are going to do this in April. This could be done right away.

**Pull request merged**
