### PR TITLE
Add `*.vid.playfilm.tv` to work around IOS PCM limits

### PR DESCRIPTION
**Pull request by MikiPF**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowlegements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
PlayFilm developed an interactive videos editor to make them easily without programming knowledge.

With this app, we make interactive videos with forms to recover leads for our clients through ads in social netwowks like Facebook or Instagram.

We send qualifyed leads to our clients thanks to machine learning and sending them extra info like their answers to our questions, or filtering leads due to age, formation, location, etc.

Organization Website: 
https://playfilm.tv

Reason for PSL Inclusion
====
IOS/Facebook: Ous SaaS customers can make their own interactive video ads and, due to iOS pixel restrictions, we need to create their own subdomains.

Number of users this request is being made to serve:
Currently 5 but we're launching our service. It's difficult to estimate, but hundreds, I hope.

DNS Verification via dig
=======
dig +short TXT _psl.vid.playfilm.tv
"https://github.com/publicsuffix/list/pull/1575"

Results of Syntax Checker (`make test`)
=========
make test run properly

### CODE REVIEW

**Comment by MikiPF** [comment]
Hi, bedforsean. 

Yes, we have a dedicated Facebook adviser due to our high budget volume and he told us to do it this way. 

Kind regards.

**Comment by bedfordsean** [comment]
@MikiPF have you filed a form, as per the process above? Directly raising things here on GitHub isn't the way to approach this. If you have filed the form, please can you let us know your reference number and we can follow up

**Comment by MikiPF** [comment]
Sorry, @bedfordsean, Facebook form reference number is 536253784813625.

Kind regards.

**Comment by bedfordsean** [comment]
Thank you, I'll follow up on this one for you

**Comment by dnsguru** [comment]
DNS Validates for TXT record

**Comment by dnsguru** [comment]
@bedfordsean @mikipf has this been advanced at all in your discussions to know this can proceed?

**Pull request closed without merging**
