### PR TITLE
Add mod.uk to public_suffix_list.dat

### PR DESCRIPTION
**Pull request by jones6r**
adding mod.uk

### CODE REVIEW

**Comment by jones6r** [comment]
Not sure how I get this change committed. I've added a TXT record for the pull request any further action required?

**Comment by sleevi** [comment]
Could you indicate how you added the TXT record? `_psl.mod.uk` does not return a TXT record for this domain.

With respect to the positioning of this - are you intending for this to be a registry-assigned delegation (e.g. prevent any navigation to `mod.uk`, and have it set aside as per registry policies for `.uk`) or a private delegation (e.g. potentially allow navigation to `mod.uk`, disallow cookies)

**Comment by jones6r** [comment]
Apologies I added ps1.mod.uk not _ps1.mod.uk. I've updated now.

The only reason we need this is because Thawte will only provide an SSL cert covering both domainname.mod.uk and www.domainname.mod.uk if the domain listed on the publicsuffix list. i.e. until we're on the list we have to buy two certs for every website.

Regards
Rhodri

**Comment by sleevi** [comment]
Note that's "_psL" (as in public suffix list).

That said, from your description, it sounds like your CA is making things unnecessarily complicated for you (e.g. these requirements are not part of the Baseline Requirements that all CAs follow, and this is something specific your CA is doing). Because of this, it may be a simple matter of miscommunication on their part, and we can avoid adding you to the PSL (which can have unwanted side effects)

**Comment by jones6r** [comment]
Apologies I added ps1.mod.uk not _ps1.mod.uk. I've updated now.

The only reason we need this is because Thawte will only provide an SSL cert covering both domainname.mod.uk and www.domainname.mod.uk if the domain listed on the publicsuffix list. i.e. until we're on the list we have to buy two certs for every website.

Regards
Rhodri

**Comment by jones6r** [comment]
I've changed the dns entry.

Unfortunately our hosting provider have tried to convince the CA that their rule isn't appropriate but with no success and they're in a better position to apply pressure than I am.

Could you explain what the side effects might be?

**Comment by rhart100** [comment]
Hi sleevi,

Could you let us know what the side effects are? Unfortunately as Rhodri has said the CA has said that they rely on this list to determine the TLDs.

Many thanks

Richard

**Comment by sleevi** [comment]
Your CA is wrong. Contact sleevi@google.com and I will work with them directly, or call out that they're adding additional unnecessary hurdles for their customers and provide alternative recommendations. You shouldn't have to add to the list because of a CA's ignorance.

**Comment by rhart100** [comment]
Hi Sleevi,
Having no luck with the CA Symantec brands (Symantec, Geotrust, Thawte, Rapid SSL) and they say their systems rely on this PSL to determine TLDs.

Can you try adding the TLD to the PSL and we can test whether this works?

Thanks

**Comment by rhart100** [comment]
Hi Sleevi,

Replied to you on email, please hold off on adding mod.uk to PSL until the side effects have been evaluated.

Thanks

**Comment by weppos** [comment]
Closing until further update.

**Pull request closed without merging**
