### PR TITLE
Adds translate.goog and tr-test.goog

### PR DESCRIPTION
**Pull request by sicter**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://translate.google.com/intl/en/about/

Engineer at Google on the Translate team

Reason for PSL Inclusion
====

.translate.goog will be serving 3rd party code separated by publisher. This is very similar to (but a different use case than) appspot.com. Currently there is no much public usage, but since it takes a while to get into the PSL, we would like to have it available before wider use.

DNS Verification via dig
=======

```
dig +short TXT _psl.translate.goog
"https://github.com/publicsuffix/list/pull/1107"
```
```
dig +short TXT _psl.tr-test.goog
"https://github.com/publicsuffix/list/pull/1107"
```

make test
=========

All tests passed.
```
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Review by dnsguru — APPROVED** [review]
- No conflict with base
- DNS Validates
- Test passes
- Rationale describes use case

APPROVE

**Comment by dnsguru** [comment]
@sicter suggest you check with @sleevi that you are applying the wildcard in the manner you expect it to behave

**Comment by dnsguru** [comment]
nudge @sleevi to approve

**Comment by sicter** [comment]
@sleevi Updated list, ready for review

**Comment by sleevi** [comment]
@dnsguru Did you verify this domain? I'm having trouble locating the record at `_psl.translate.goog`

Chatted with @sicter about this case, and the example domains are of the form:

`foo.translate.goog` being a distinct entity than `bar.translate.goog`, so this looks like the right entry. But the trouble verifying has me wanting to make sure it was verified.

**Review by sleevi — APPROVED** [review]
Signing-off on this, but not adding r=sleevi because I have not verified the TXT record.

**Comment by dnsguru** [comment]
I have.  Is that what r= means?

**Pull request merged**
