### PR TITLE
Add STACKIT subdomains (`runs.onstackit.cloud`, `stackit.gg`, `stackit.rocks`, `stackit.run`, `stackit.zone`)

### PR DESCRIPTION
**Pull request by Slm0n87**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
STACKIT is a strong growing german cloud provider that offers managed Infrastructure- and Platform as a Service solutions for our customers.  
Within the STACKIT DNS service we offer our customers free domains under which the customer can register his own DNS zones as a subdomain  
to make his cloud application available. This is why we have to add the new domains.

Organization Website: https://www.stackit.de/en/

Reason for PSL Inclusion
====
Our customers share the provided domains registered and owned by us. Every customer has full DNS control over the subdomains.  
We need to protect the subdomains from the exchange of cookies between them.

Number of users this request is being made to serve: over 550k

DNS Verification via dig
=======
```
dig +short TXT _psl.runs.onstackit.cloud
"https://github.com/publicsuffix/list/pull/1785"
dig +short TXT _psl.stackit.gg
"https://github.com/publicsuffix/list/pull/1785"
dig +short TXT _psl.stackit.rocks
"https://github.com/publicsuffix/list/pull/1785"
dig +short TXT _psl.stackit.run
"https://github.com/publicsuffix/list/pull/1785"
dig +short TXT _psl.stackit.zone
"https://github.com/publicsuffix/list/pull/1785"
```

Results of Syntax Checker (`make test`)
=========
```
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by Slm0n87** [comment]
put to draft for internal review

**Comment by Slm0n87** [comment]
Ready for review

**Comment by Slm0n87** [comment]
@dnsguru - may you could have a quick look here? To check if something is missing from our side?  
Thanks in advance.

**Review by simon-friedberger — APPROVED** [review]
* [x] Expiration
  * [x] runs.onstackit.cloud expires 2026-07-26
  * [x] stackit.gg has no expiry information
  * [x] stackit.rocks expires 2027-04-26
  * [x] stackit.run expires 2027-04-26
  * [x] stackit.zone expires 2027-04-26
* [x] DNS _psl entries
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Pull request merged**
