### PR TITLE
Add freifunk.net

### PR DESCRIPTION
**Pull request by xf-**
make test-syntax - passed
freifunk.net has over 100 regional communitys and everyone can use region.freifunk.net.

### CODE REVIEW

**Comment by xf-** [comment]
DNS entry is missing - working on it

**Comment by sleevi** [comment]
Can you expand more, such as with sample domains?

It sounds like you're suggesting there's `<user domain>.<region>.freifunk.net` - where <reigion> is one of 100 values - in which case, you'd want *.freifunk.net

Does that make sense?

**Comment by xf-** [comment]
Hi,

Services:
forum.freifunk.net
blog.freifunk.net
bug.freifunk.net
global.freifunk.net
pad.freifunk.net

Communitys:
aachen.freifunk.net
augsburg.freifunk.net
bad-gandersheim.freifunk.net
badoldesloe.freifunk.net
barnstorf.freifunk.net
berlin.freifunk.net
bgl.freifunk.net
bremen.freifunk.net
chemnitz.freifunk.net
darmstadt.freifunk.net
dithmarschen.freifunk.net
eberswalde.freifunk.net
erfurt.freifunk.net
ffm.freifunk.net
freiburg.freifunk.net
fulda.freifunk.net
greifswald.freifunk.net
gronau.freifunk.net
guetersloh.freifunk.net
hamburg.freifunk.net
hannover.freifunk.net
harz.freifunk.net
helgoland.freifunk.net
herford.freifunk.net
hochstift.freifunk.net
ics.freifunk.net
ilmenau.freifunk.net
karlsruhe.freifunk.net
kbu.freifunk.net
kuerten.freifunk.net
leipzig.freifunk.net
luebeck.freifunk.net
malente.freifunk.net
marburg.freifunk.net
md.freifunk.net
mueritz.freifunk.net
nms.freifunk.net
nord.freifunk.net
nordheide.freifunk.net
ortenau.freifunk.net
osnabrueck.freifunk.net
pinneberg.freifunk.net
ploen.freifunk.net
potsdam.freifunk.net
regensburg.freifunk.net
saar.freifunk.net
siegerland.freifunk.net
stade.freifunk.net
trier.freifunk.net
unna.freifunk.net
vogtland.freifunk.net
wahlsdorf.freifunk.net
wiesbaden.freifunk.net

(only publicly announced domains via api.json from freifunk)

Additionally often server or services in community like gw1.regensburg.freifunk.net or meshviewer.fulda.freifunk.net . This is up to community, but mostly it is used for gateways.

Main reason for this request is Lets Encrypt, but our issue is freifunk.net would need a new domain or use www.freifunk.net because of cookies. I saw no solution in documentation or is 
```
freifunk.net
!freifunk.net
```
possible and reasonable?
I think we need to close this PR. :(

Big THX for quick reply and maintaining this project :)

**Comment by mweinelt** [comment]
Letsencrypt's rate limit really shouldn't be an issue, as renewals are always exempt from rate-limiting and there can be 20 new certificates per week, with up to 100 SANs. So with time every community should be able to get their cert, and be able to renew them.

Also affecting freifunk.net's cookie policy without consulting them is a no-no.

**Comment by xf-** [comment]
@mweinelt i wrote with DNS part of course and approval here is only possible with DNS administration from freifunk.net
A lot of community's have access and adding a new service needs a renew  with different domain and counts to weekly 20 limit. Old Wildcard *.freifunk.net expires and won't be renewed.

I will close this issue for now.

**Pull request closed without merging**
