### PR TITLE
Add azimuth.network and arvo.network

### PR DESCRIPTION
**Pull request by Fang-**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://urbit.org

I am Mark Staarink, engineer at [Tlon](https://tlon.io), the company working on Urbit. It comprises several separate components, which include Azimuth (decentralized identity) and Arvo (personal server).

Reason for PSL Inclusion
====

Azimuth and Arvo will provide identity owners with their own subdomain under `azimuth.network` and `arvo.network` respectively. For example, `palfun-foslup.arvo.network`.

In the case of Azimuth, the identity subdomain will serve as a unique log-on point for that specific identity.  
In the case of Arvo, the identity subdomain will point to the owner's personal server, which can serve arbitrary content.

DNS Verification via dig
=======

```
> dig +short TXT _psl.azimuth.network
"https://github.com/publicsuffix/list/pull/812"

> dig +short TXT _psl.arvo.network
"https://github.com/publicsuffix/list/pull/812"
```

make test
=========

`make test` sees all tests pass.

### CODE REVIEW

**Comment by sleevi** [comment]
Please place these in a single section for your organization.

**Comment by Fang-** [comment]
@sleevi Fair! Let me know if you need anything else.

**Comment by dnsguru** [comment]
@Fang- will azimuth.network be renewing?

**Comment by Fang-** [comment]
@dnsguru I'm not sure I understand the question. If you're asking whether we want to keep these domains on the PSL, the answer is yes. Do we need to explicitly flag this somewhere?

**Comment by dnsguru** [comment]
@fang glad to hear you are renewing vs deleting.  Encourage >1 year renewal when you do

we have been getting a lot of 'set and forget' inclusions into the PSL that subsequently do not renew the domain name and we have a discussion around planning for this to be automated to delete entries where the domain name does not hold a renewal term of >1 year.  In a manual review, I noticed that your domain name has a very short term left in its registration (see #1119) and want to determine if we can delete the entry if you're not renewing it, or encourage you to renew the domain name for >1 year when you do in order to not get flagged by the automation.

**Pull request merged**
