### PR TITLE
Update .so suffix list

### PR DESCRIPTION
**Pull request by byjml**
In addition to .so, .edu.so, .com.so, .gov.so, .net.so, and .org.so, the .SO ccTLD also supports ~~.sch.so for schools,~~ .me.so for individuals ~~and .gm.so, .hs.so, .jl.so, .pl.so, and .sw.so for federal member state administrations~~. I have updated the suffix list to reflect this.

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

.so is the ccTLD of the Republic of Somalia. The PSL already partially supports the .so TLD but there are many missing TLD which I added.

Organization Website: http://sonic.so

Reason for PSL Inclusion
====

I am not affiliated with the .so entity, I am sending this pull request because I run an accredited .so registrar and this PR would help many other registrars who sell the .so TLD.

DNS Verification via dig
=======

N/A

make test
=========

All the tests are passing.

### CODE REVIEW

**Comment by weppos** [comment]
Hi @byjml thanks for the patch. Unfortunately, we can only accept patches to TLDs if they are submitted by the registry, or supported by official documentation.

According to http://sonic.so/policies/ the only suffixes are:

> All domains registered under the .so, .com.so, .edu.so, .gov.so, .me.so, .net.so and .org.so namespaces are governed by the .SO Domain Name Registration Policies.

Are you able to provide an official reference to the other suffixes you included?

**Comment by byjml** [comment]
Welcome @weppos! As I said I’m not affiliated to them and I am only submitting this patch as a volunteer and also because I run an accredited .so registrar.

Should I update the PR to include only the TLDs publicly documented on their website?

**Comment by weppos** [comment]
> Should I update the PR to include only the TLDs publicly documented on their website?

I would appreciate it. This would be the only way I can go ahead and merge the changes.

**Comment by byjml** [comment]
> I would appreciate it. This would be the only way I can go ahead and merge the changes.

Done. I have reduced the changes to the officially documents TLDs.

**Pull request merged**
