### PR TITLE
Adding upli.io

### PR DESCRIPTION
**Pull request by lennybakkalian**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Organization Website: https://upli.io
upli is a service provider for creating static websites. These websites are built from github repositories and then hosted under their own domain or a subdomain provided by upli. for example, lenny.upli.io - In addition, in the distant future it will be possible to rent virtual servers and create lambda functions (similar to aws lambda).

Reason for PSL Inclusion
====
Since each user has his own subdomain, it should be forbidden to create supercookies to compromise the main site. Even if on the main page the session token is stored in the localstorage, because not all browsers contain the public suffix list. Nevertheless we want to separate all subdomains via the PSL.

DNS Verification via dig
=======

```
dig +short TXT _psl.upli.io
"https://github.com/publicsuffix/list/pull/1446"
```

### CODE REVIEW

**Comment by dnsguru** [comment]
We need to be provided better Org description and Reason on this PR.

The one sentence Org and Reason prompted a visit to the organization website URL, which returns "502 Bad Gateway"

**Comment by dnsguru** [comment]
Please improve the org/reason and inform us when working website

**Comment by wdhdev** [comment]
@lennybakkalian Is this domain safe to remove? It does not seem to be used.

Please see #2302.

**Comment by lennybakkalian** [comment]
Yea it can be removed

**Pull request merged**
