### PR TITLE
Add 105 `lolipop` and `heteml` domains to private section for GMO

### PR DESCRIPTION
**Pull request by linyows**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: [GMO Pepabo, Inc.](https://pepabo.com)

I'm Tomohisa Oda, engineering manager at GMO Pepabo. [Lolipop](https://lolipop.jp/) and [Heteml](https://heteml.jp/) are web hostings people use to build, deploy, and serve websites. They are provided by GMO Pepabo, Inc.

Reason for PSL Inclusion
====

Each subdomain on the domain belongs to a different customer, so inclusion on the list was necessary to prevent multi-site cookies. 

We have a large number of customers and are rated by [hostadvice.com](https://hostadvice.com/marketshare/jp/) as having the highest webhosting market share in Japan. lolipop is ranked 2nd and hetml is ranked 6th. Both of them together are number one in Japan.

Our customers choose their domain from over 100 domains. We are adding these domains to PSL this time.
<a href="https://lolipop.jp/order/form/?plan_9"></a>

There are 650 users for the fewest and 110,000 users for the most. We would like to register these domains in PSL for the safety of the web.

DNS Verification via dig
=======

```
list=`cat << EOL | perl -pe 's/\n/ /'
angry.jp
babyblue.jp
babymilk.jp
backdrop.jp
bambina.jp
bitter.jp
blush.jp
boo.jp
boy.jp
boyfriend.jp
but.jp
candypop.jp
capoo.jp
catfood.jp
cheap.jp
chicappa.jp
chillout.jp
chips.jp
chowder.jp
chu.jp
ciao.jp
cocotte.jp
coolblog.jp
cranky.jp
cutegirl.jp
daa.jp
deca.jp
deci.jp
digick.jp
egoism.jp
fakefur.jp
fem.jp
flier.jp
floppy.jp
fool.jp
frenchkiss.jp
girlfriend.jp
girly.jp
gloomy.jp
gonna.jp
greater.jp
hacca.jp
heavy.jp
her.jp
hiho.jp
hippy.jp
holy.jp
hungry.jp
icurus.jp
itigo.jp
jellybean.jp
kikirara.jp
kill.jp
kilo.jp
kuron.jp
littlestar.jp
lolitapunk.jp
lomo.jp
lovepop.jp
lovesick.jp
main.jp
mods.jp
mond.jp
mongolian.jp
moo.jp
namaste.jp
nikita.jp
nobushi.jp
noor.jp
oops.jp
parallel.jp
parasite.jp
pecori.jp
peewee.jp
penne.jp
pepper.jp
perma.jp
pigboat.jp
pinoko.jp
punyu.jp
pupu.jp
pussycat.jp
pya.jp
raindrop.jp
readymade.jp
sadist.jp
schoolbus.jp
secret.jp
staba.jp
stripper.jp
sub.jp
sunnyday.jp
thick.jp
tonkotsu.jp
under.jp
upper.jp
velvet.jp
verse.jp
versus.jp
vivian.jp
watson.jp
weblike.jp
whitesnow.jp
zombie.jp
heteml.net
EOL`

for domain in $list; do
  echo -n "$domain:"
  dig +short TXT _psl.$domain
done
```

make test
=========

The syntax check passed:

```sh
$ make test-syntax
cd linter;                                \
          ./pslint_selftest.sh;                     \
          ./pslint.py ../public_suffix_list.dat;
-n test_NFKC:
OK
-n test_allowedchars:
OK
-n test_dots:
OK
-n test_duplicate:
OK
-n test_exception:
OK
-n test_punycode:
OK
-n test_section1:
OK
-n test_section2:
OK
-n test_section3:
OK
-n test_section4:
OK
-n test_spaces:
OK
-n test_wildcard:
OK
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Hello Oda-san 

We try to keep the PSL size as modest as possible, and this is a very large list of domain names being submitted for addition on behalf of your organization.  In respect of the objective of file size modesty, we often push back for smaller lists.  Could you please provide more of a rationale text that helps the reviewers to understand the number of affected customers or users and a stronger justification for this large list?

Thank you

**Comment by linyows** [comment]
Hi @dnsguru , We are very grateful to the PSL maintainers. You're right. I checked the number of active users in the domain and [removed the domains that had little impact](https://github.com/publicsuffix/list/pull/1522/commits/0ca8a4954333cef4da900973ad44e2da901f33e5). Other domains are used in the range of 650 to 110,000 users. The number of active users in each domain cannot be published from a business perspective. Thank you.

**Comment by linyows** [comment]
We have a large number of customers and are rated by [hostadvice.com](https://hostadvice.com/marketshare/jp/) as having the highest webhosting market share in Japan. lolipop is ranked 2nd and hetml is ranked 6th. Both of them together are number one in Japan.

Our customers choose their domain from over 100 domains. We are adding these domains to PSL this time.
<a href="https://lolipop.jp/order/form/?plan_9"></a>

As already mentioned, there are 650 users for the fewest and 110,000 users for the most. We would like to register these domains in PSL for the safety of the web.

**Comment by dnsguru** [comment]
Confirmed DNS validation

```
angry.jp:"https://github.com/publicsuffix/list/pull/1522"
babyblue.jp:"https://github.com/publicsuffix/list/pull/1522"
babymilk.jp:"https://github.com/publicsuffix/list/pull/1522"
backdrop.jp:"https://github.com/publicsuffix/list/pull/1522"
bambina.jp:"https://github.com/publicsuffix/list/pull/1522"
bitter.jp:"https://github.com/publicsuffix/list/pull/1522"
blush.jp:"https://github.com/publicsuffix/list/pull/1522"
boo.jp:"https://github.com/publicsuffix/list/pull/1522"
boy.jp:"https://github.com/publicsuffix/list/pull/1522"
boyfriend.jp:"https://github.com/publicsuffix/list/pull/1522"
but.jp:"https://github.com/publicsuffix/list/pull/1522"
candypop.jp:"https://github.com/publicsuffix/list/pull/1522"
capoo.jp:"https://github.com/publicsuffix/list/pull/1522"
catfood.jp:"https://github.com/publicsuffix/list/pull/1522"
cheap.jp:"https://github.com/publicsuffix/list/pull/1522"
chicappa.jp:"https://github.com/publicsuffix/list/pull/1522"
chillout.jp:"https://github.com/publicsuffix/list/pull/1522"
chips.jp:"https://github.com/publicsuffix/list/pull/1522"
chowder.jp:"https://github.com/publicsuffix/list/pull/1522"
chu.jp:"https://github.com/publicsuffix/list/pull/1522"
ciao.jp:"https://github.com/publicsuffix/list/pull/1522"
cocotte.jp:"https://github.com/publicsuffix/list/pull/1522"
coolblog.jp:"https://github.com/publicsuffix/list/pull/1522"
cranky.jp:"https://github.com/publicsuffix/list/pull/1522"
cutegirl.jp:"https://github.com/publicsuffix/list/pull/1522"
daa.jp:"https://github.com/publicsuffix/list/pull/1522"
deca.jp:"https://github.com/publicsuffix/list/pull/1522"
deci.jp:"https://github.com/publicsuffix/list/pull/1522"
digick.jp:"https://github.com/publicsuffix/list/pull/1522"
egoism.jp:"https://github.com/publicsuffix/list/pull/1522"
fakefur.jp:"https://github.com/publicsuffix/list/pull/1522"
fem.jp:"https://github.com/publicsuffix/list/pull/1522"
flier.jp:"https://github.com/publicsuffix/list/pull/1522"
floppy.jp:"https://github.com/publicsuffix/list/pull/1522"
fool.jp:"https://github.com/publicsuffix/list/pull/1522"
frenchkiss.jp:"https://github.com/publicsuffix/list/pull/1522"
girlfriend.jp:"https://github.com/publicsuffix/list/pull/1522"
girly.jp:"https://github.com/publicsuffix/list/pull/1522"
gloomy.jp:"https://github.com/publicsuffix/list/pull/1522"
gonna.jp:"https://github.com/publicsuffix/list/pull/1522"
greater.jp:"https://github.com/publicsuffix/list/pull/1522"
hacca.jp:"https://github.com/publicsuffix/list/pull/1522"
heavy.jp:"https://github.com/publicsuffix/list/pull/1522"
her.jp:"https://github.com/publicsuffix/list/pull/1522"
hiho.jp:"https://github.com/publicsuffix/list/pull/1522"
hippy.jp:"https://github.com/publicsuffix/list/pull/1522"
holy.jp:"https://github.com/publicsuffix/list/pull/1522"
hungry.jp:"https://github.com/publicsuffix/list/pull/1522"
icurus.jp:"https://github.com/publicsuffix/list/pull/1522"
itigo.jp:"https://github.com/publicsuffix/list/pull/1522"
jellybean.jp:"https://github.com/publicsuffix/list/pull/1522"
kikirara.jp:"https://github.com/publicsuffix/list/pull/1522"
kill.jp:"https://github.com/publicsuffix/list/pull/1522"
kilo.jp:"https://github.com/publicsuffix/list/pull/1522"
kuron.jp:"https://github.com/publicsuffix/list/pull/1522"
littlestar.jp:"https://github.com/publicsuffix/list/pull/1522"
lolipop.jp:"https://github.com/publicsuffix/list/pull/1522"
lolitapunk.jp:"https://github.com/publicsuffix/list/pull/1522"
lomo.jp:"https://github.com/publicsuffix/list/pull/1522"
lovepop.jp:"https://github.com/publicsuffix/list/pull/1522"
lovesick.jp:"https://github.com/publicsuffix/list/pull/1522"
main.jp:"https://github.com/publicsuffix/list/pull/1522"
mods.jp:"https://github.com/publicsuffix/list/pull/1522"
mond.jp:"https://github.com/publicsuffix/list/pull/1522"
mongolian.jp:"https://github.com/publicsuffix/list/pull/1522"
moo.jp:"https://github.com/publicsuffix/list/pull/1522"
namaste.jp:"https://github.com/publicsuffix/list/pull/1522"
nikita.jp:"https://github.com/publicsuffix/list/pull/1522"
nobushi.jp:"https://github.com/publicsuffix/list/pull/1522"
noor.jp:"https://github.com/publicsuffix/list/pull/1522"
oops.jp:"https://github.com/publicsuffix/list/pull/1522"
parallel.jp:"https://github.com/publicsuffix/list/pull/1522"
parasite.jp:"https://github.com/publicsuffix/list/pull/1522"
pecori.jp:"https://github.com/publicsuffix/list/pull/1522"
peewee.jp:"https://github.com/publicsuffix/list/pull/1522"
penne.jp:"https://github.com/publicsuffix/list/pull/1522"
pepper.jp:"https://github.com/publicsuffix/list/pull/1522"
perma.jp:"https://github.com/publicsuffix/list/pull/1522"
pigboat.jp:"https://github.com/publicsuffix/list/pull/1522"
pinoko.jp:"https://github.com/publicsuffix/list/pull/1522"
punyu.jp:"https://github.com/publicsuffix/list/pull/1522"
pupu.jp:"https://github.com/publicsuffix/list/pull/1522"
pussycat.jp:"https://github.com/publicsuffix/list/pull/1522"
pya.jp:"https://github.com/publicsuffix/list/pull/1522"
raindrop.jp:"https://github.com/publicsuffix/list/pull/1522"
readymade.jp:"https://github.com/publicsuffix/list/pull/1522"
sadist.jp:"https://github.com/publicsuffix/list/pull/1522"
schoolbus.jp:"https://github.com/publicsuffix/list/pull/1522"
secret.jp:"https://github.com/publicsuffix/list/pull/1522"
staba.jp:"https://github.com/publicsuffix/list/pull/1522"
stripper.jp:"https://github.com/publicsuffix/list/pull/1522"
sub.jp:"https://github.com/publicsuffix/list/pull/1522"
sunnyday.jp:"https://github.com/publicsuffix/list/pull/1522"
thick.jp:"https://github.com/publicsuffix/list/pull/1522"
tonkotsu.jp:"https://github.com/publicsuffix/list/pull/1522"
under.jp:"https://github.com/publicsuffix/list/pull/1522"
upper.jp:"https://github.com/publicsuffix/list/pull/1522"
velvet.jp:"https://github.com/publicsuffix/list/pull/1522"
verse.jp:"https://github.com/publicsuffix/list/pull/1522"
versus.jp:"https://github.com/publicsuffix/list/pull/1522"
vivian.jp:"https://github.com/publicsuffix/list/pull/1522"
watson.jp:"https://github.com/publicsuffix/list/pull/1522"
weblike.jp:"https://github.com/publicsuffix/list/pull/1522"
whitesnow.jp:"https://github.com/publicsuffix/list/pull/1522"
zombie.jp:"https://github.com/publicsuffix/list/pull/1522"
heteml.jp:"https://github.com/publicsuffix/list/pull/1522"
heteml.net:"https://github.com/publicsuffix/list/pull/1522"
```

**Comment by linyows** [comment]
I'm ready

**Review by dnsguru — APPROVED** [review]
- DNS Validation OK
- Guidelines Followed
- Tests Pass
- No Conflict with Base

APPROVED
(but noting there were concerns about the modesty of the scale of names added)

**Comment by linyows** [comment]
Thanks!

**Pull request merged**
