### PR TITLE
Add Joyent Triton

### PR DESCRIPTION
**Pull request by bahamat**
Add namespaces for Joyent's Triton Container Name Service.

### CODE REVIEW

**Comment by sleevi** [comment]
I'm unable to verify this per https://github.com/publicsuffix/list/wiki/Guidelines

Could you update the PR (and ensure it's sorted properly against master) once you've done so?

**Comment by bahamat** [comment]
I've rebased the commit against master, and added the following DNS entries.

    $ dig -t txt +short _psl.triton.zone
    "https://github.com/publicsuffix/list/pull/266"
    $ dig -t txt +short _psl.cns.joyent.com
    "https://github.com/publicsuffix/list/pull/266"

**Comment by sleevi** [comment]
It's still sorted incorrectly, at least, assuming J is still after I (... it's been a long day of PRs). Would you mind ensuring that you're adding the corporate entity to the correct section @bahamat

**Comment by bahamat** [comment]
Oh! Sorry! It should be fixed now.

**Comment by sleevi** [comment]
Sent you a PR to your branch to fix.

**Comment by bahamat** [comment]
Bah, forgot to git add before pushing last time. Again, sorry about all of this.

**Comment by bahamat** [comment]
Thanks!

**Pull request merged**
