### PR TITLE
 Handle EBEROs: Use DelegationDate alongside ContractTerminated

### PR DESCRIPTION
**Pull request by aaomidi**
Solution for #1174. Replaces #1754

Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website:  N/A

Reason for PSL Inclusion
====

Number of users this request is being made to serve: N/A

`.wed` is an EBERO TLD. This means it's still an active suffix for domains (e.g. may27.wed). I've updated the updater code to ensure that these DNS names (currently only one) don't get dropped by the automation until they're ready to be dropped.

DNS Verification via dig
=======

```
dig soa +short wed.
dns1.emdns.uk. hostmaster.nominet.org.uk. 2100001071 7200 900 2419200 3600
```

```
whois wed.
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

domain:       WED

organisation: Emergency Back-End Registry Operator Program - ICANN
address:      12025 Waterfront Drive
address:      Suite 300
address:      Los Angeles CA 90094
address:      United States of America (the)

contact:      administrative
name:         EBERO Event Director
organisation: Internet Corporation for Assigned Names and Numbers (ICANN)
address:      12025 Waterfront Drive
address:      Suite 300
address:      Los Angeles CA 90094
address:      United States of America (the)
phone:        +1 310 301 5800
fax-no:       +1 310 823 8649
e-mail:       eventdirector@icann.org

contact:      technical
name:         Nominet EBERO Event Manager
organisation: Nominet
address:      Minerva House
address:      Edmund Halley Road
address:      Oxford Science Park
address:      Oxford Oxon OX4 4DQ
address:      United Kingdom of Great Britain and Northern Ireland (the)
phone:        +44 1865 332470
e-mail:       ebero@nominet.uk

nserver:      DNS1.EMDNS.UK 213.248.217.153 2a01:618:401:0:0:0:0:153
nserver:      DNS2.EMDNS.UK 103.49.81.153 2401:fd80:401:0:0:0:0:153
nserver:      DNS3.EMDNS.UK 213.248.221.153 2a01:618:405:0:0:0:0:153
nserver:      DNS4.EMDNS.UK 2401:fd80:405:0:0:0:0:153 43.230.49.153
nserver:      DNSA.EMDNS.UK 156.154.100.3 2001:502:ad09:0:0:0:0:3
nserver:      DNSB.EMDNS.UK 156.154.101.3 2001:502:2eda:0:0:0:0:3
nserver:      DNSC.EMDNS.UK 156.154.102.3 2610:a1:1009:0:0:0:0:3
nserver:      DNSD.EMDNS.UK 156.154.103.3 2610:a1:1010:0:0:0:0:3
ds-rdata:     60571 8 2 32ed00d841e724eaa980472283420ee9de48905e1b04709e79fc418c08fa1561

whois:        whois.nic.wed

status:       ACTIVE
remarks:      Registration information:
remarks:      https://www.icann.org/resources/pages/ebero-2013-04-02-en

created:      2013-12-12
changed:      2021-11-11
source:       IANA
```

Results of Syntax Checker (`make test`)
=========

```
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public
PASS: test-is-public-builtin
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by aaomidi** [comment]
DNS Verification for `desi.`:

```
dig soa +short desi.
dns1.emdns.uk. hostmaster.nominet.org.uk. 1699968187 900 300 2419200 3600
```
```
whois desi
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

domain:       DESI

organisation: Emergency Back-End Registry Operator Program - ICANN
address:      12025 Waterfront Dr., Suite 300
address:      Los Angeles CA 90094
address:      United States of America (the)

contact:      administrative
name:         EBERO Event Director
organisation: Internet Corporation for Assigned Names and Numbers (ICANN)
address:      12025 Waterfront Dr., Suite 300
address:      Los Angeles CA 90094
address:      United States of America (the)
phone:        +1(310) 301-5800
fax-no:       +1(310) 823-8649
e-mail:       eventdirector@icann.org

contact:      technical
name:         Nominet EBERO Event Manager
organisation: Nominet
address:      Minerva House, Edmund Halley Road, Oxford Science Park
address:      Oxford Oxon OX4 4DQ
address:      United Kingdom of Great Britain and Northern Ireland (the)
phone:        +44 1865 332470
e-mail:       ebero@nominet.uk

nserver:      DNS1.EMDNS.UK 213.248.217.153 2a01:618:401:0:0:0:0:153
nserver:      DNS2.EMDNS.UK 103.49.81.153 2401:fd80:401:0:0:0:0:153
nserver:      DNS3.EMDNS.UK 213.248.221.153 2a01:618:405:0:0:0:0:153
nserver:      DNS4.EMDNS.UK 2401:fd80:405:0:0:0:0:153 43.230.49.153
nserver:      DNSA.EMDNS.UK 156.154.100.3 2001:502:ad09:0:0:0:0:3
nserver:      DNSB.EMDNS.UK 156.154.101.3 2001:502:2eda:0:0:0:0:3
nserver:      DNSC.EMDNS.UK 156.154.102.3 2610:a1:1009:0:0:0:0:3
nserver:      DNSD.EMDNS.UK 156.154.103.3 2610:a1:1010:0:0:0:0:3
ds-rdata:     5621 8 2 2ae99319e83d075eac0f4b572822e3685027038688b38ceb2c5445e09606f752

whois:        whois.nic.desi

status:       ACTIVE
remarks:      Registration information:
remarks:      https://www.icann.org/resources/pages/ebero-2013-04-02-en

created:      2014-03-06
changed:      2023-10-23
source:       IANA
```

**Comment by dnsguru** [comment]
This was previously discussed and hashed out well by the core volunteers in #1754

**Review by cpu — COMMENTED** [review]
LGTM. Thanks for adding the test coverage :rocket:

**Comment by aaomidi** [comment]
Are we waiting on anything else for this PR?

**Comment by aaomidi** [comment]
Hi @dnsguru @weppos - to make sure this doesn't drift from `master`, I want to understand what's outstanding with this PR before we get it merged in?

**Comment by dnsguru** [comment]
Available volunteer time to review it

**Comment by weppos** [comment]
From the code side, the changes look good to me. I'd like @dnsguru to chime in and confirm the idea of checking for the delegation date not being blank is a valid assumption for EBERO domains.

```
// If the Delegation Date is not empty, the gTLD is likely in EBERO.
if entry.ContractTerminated && entry.DelegationDate == "" {
```

I also noticed `.DESI` leaked into this PR. Is it expected?

**Comment by dnsguru** [comment]
I would like to confirm the logic with ICANN technical services to ensure
they are aware of our approach so that they do not change structure.

> desi
Desi was the second ebero tld from 2012.

**Comment by weppos** [comment]
> I would like to confirm the logic with ICANN technical services to ensure they are aware of our approach so that they do not change structure.

This would be very helpful!

**Comment by dnsguru** [comment]
Ok to merge though @Simone Carletti ***@***.***>

**Comment by dnsguru** [comment]
Ok and now we watch the autopull for tomorrow and see what it does

**Comment by aaomidi** [comment]
https://github.com/publicsuffix/list/blob/master/.github/workflows/tld-update.yml#L3 You should be able to get it to do a manual run of the tld-update workflow

**Comment by weppos** [comment]
I dispatched a manual run to fast-track the verification @dnsguru @aaomidi

**Pull request merged**
