### PR TITLE
Add `as.sh.cn`

### PR DESCRIPTION
**Pull request by yubospace**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

[Shanghai Accounting Society (SAS)](https://www.sssa.org.cn/skjxh.htm) is a subsidiary of the [Shanghai Municipal Bureau of Finance](https://czj.sh.gov.cn). The registration authority of the Society is the Shanghai Municipal Administration of Social Organizations, and the business unit in charge is the Shanghai Federation of Social Science Circles. The Society accepts the supervision and management of the registration authority, the business unit in charge, and the affiliated unit. SAS has 21 branches, including working committees and professional committees, which carry out activities under the leadership of the Council of the Society.

Organization Website: 
https://www.sasf.org.cn
https://czj.sh.gov.cn (parent)
https://www.sssa.org.cn/skjxh.htm (documentation)

Reason for PSL Inclusion
====

We seek to properly isolate each subdomain to prevent global cookie setting on as.sh.cn and to highlight that each subdomain hosts sites of different users, unrelated to each other. We are delegating subdomains to each of our 21 branches, e.g., `{abbreviation_of_organization}.as.sh.cn`, with each branch functioning as a separate entity. Implementation Timeline: This is part of planned domain name changes that will be implemented by fall of this year.

**Number of users this request is being made to serve:**

The Shanghai Accounting Society (SAS) plans to allocate subdomains under `as.sh.cn` for each of its 21 branches, treating each as a separate legal entity. Each branch is expected to have a significant number of users, with a conservative estimate of over 3,000 users per branch. This segregation ensures proper isolation and security standards for the diverse and unrelated user groups across different branches.

Domain expiry > 3 years.

DNS Verification via dig
=======

```sh
$ dig +short TXT _psl.as.sh.cn @8.8.8.8
"https://github.com/publicsuffix/list/pull/1992"

$ dig +short TXT _psl.as.sh.cn @1.1.1.1
"https://github.com/publicsuffix/list/pull/1992"
```

Results of Syntax Checker (`make test`)
=========

```
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by groundcat** [comment]
- The sorting looks correct to me.
- `as.sh.cn` expires on 2027-06-08, which is more than 2 years from now.
- The `_psl` record exists and is valid.
- The organization’s website https://www.sasf.org.cn belongs to the Shanghai Accounting Society and matches what is described in the "Description of Organization" section. Relationship verifiable through the government website (https://czj.sh.gov.cn/zys_8908/bsfw_9071/bszn_9072/hjzyjszg_9074/20190801/0017-170578.html), confirming that SAS is part of the Shanghai Municipal Bureau of Finance (https://czj.sh.gov.cn). The registration document (https://www.sssa.org.cn/skjxh.htm) matches the PR description.

**Comment by yubospace** [comment]
> While all information about the organization description checks out, I can't find details about the planned suffix `as.sh.cn`. Is there information or links about the planned use of `as.sh.cn` on the website of either `sasf.org.cn` or `czj.sh.gov.cn`? This would potentially help volunteers verify if this request is genuinely from the municipality. Thanks.

Hello there, thanks for following up on my pull request. To help you verify that this request is indeed from the organization, we have added a temporary `TXT` record to serve as the connection between the organization and this pull request, as follows:

```sh
$ dig +short TXT temporary_validation.sasf.org.cn
"https://github.com/publicsuffix/list/pull/1992"
```

**Comment by simon-friedberger** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] as.sh.cn expires 2027-06-08
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [ ] Reasoning/Organization description

Thank you for the thorough checking, @groundcat!

**Comment by simon-friedberger** [comment]
@yubospace Please provide estimates of how many subdomains and how many users per subdomain you expect.

**Comment by yubospace** [comment]
@simon-friedberger Thank you, Simon, for reviewing! I have updated the explanation under the "Number of users this request is being made to serve" heading.

**Pull request merged**
