### PR TITLE
Add MyFRITZ! DynDNS-Service 'myfritz.net'

### PR DESCRIPTION
**Pull request by weand**
This PR is submitted on behalf of domain owner Kai Schroeder. 
http://whois.domaintools.com/myfritz.net

You can confirm the request using his mail address linked in the whois information.

Best regards.

### CODE REVIEW

**Comment by csett86** [comment]
Any update on the inclusion of myfritz.net into the PSL? Any known blocker?

**Comment by weppos** [comment]
We are working on other priorities to make sure we properly test and validate the pending requests for private domains. Once these priorities are completed, we'll review the pending requests.

If anything will block this PR, we'll comment and we'll follow up with the owner of the domain.

**Comment by quizilkend** [comment]
see https://github.com/publicsuffix/list/pull/64

**Comment by weand** [comment]
Any updates on this?

For faster and easier domain confirmation purposes, we've created an additional TXT record, pointing to this PR.

Type	Domain Name	TTL	Record
TXT	myfritz.net	24 hrs	https://github.com/publicsuffix/list/pull/77

**Comment by weand** [comment]
@gerv @weppos 

We know you are working on improving the approval process. As this PR is pending for over 4 months, I would like to add some details.

[AVM](https://avm.de) as a leading manufacturer of broadband devices for DSL, cable, LTE (4G) and fiber optics in Germany and Europe is interested not only in circumventing the LE rate limiter, but also in cookie isolation for different login mechanisms.

We really appreciate the effort of maintaining the PSL. Please let me know if we can do anything more to get this PR merged - also via [Mail](mailto:a.weise@avm.de).

Thanks in advance.
Andreas

**Comment by sleevi** [comment]
Apologies for the delay @weand 

Can you please update this submission based on https://github.com/publicsuffix/list/wiki/Guidelines

Specifically:
* Rebase to master
* Remove the date

I have validated via the TXT record that everything is otherwise correct.

**Comment by weand** [comment]
@sleevi Glad to see your reply. I've updated the commit accordingly.

Thanks in advance.

**Pull request merged**
