### PR TITLE
Add b-data.io

### PR DESCRIPTION
**Pull request by benz0li**
- [x] Description of Organization
 - [x] Reason for PSL Inclusion
 - [x] DNS verification via dig
 - [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://www.b-data.io

I'm a Data Scientist at b-data using GitLab (https://gitlab.b-data.ch) to serve repositories to my customers.

Reason for PSL Inclusion
====

b-data.io is used for GitLab pages to allow arbitrary users to have subdomains.

### CODE REVIEW

**Comment by benz0li** [comment]
DNS Verification via dig
=======

```
$ dig _psl.b-data.io TXT +short
"https://github.com/publicsuffix/list/pull/759"
```

**Comment by benz0li** [comment]
make test
=======
None of the failing entries are related to this change.

**Comment by benz0li** [comment]
- [x] Description of Organization
 - [x] Reason for PSL Inclusion
 - [x] DNS verification via dig
 - [x] Run Syntax Checker (make test)

**Comment by benz0li** [comment]
Hi @weppos, could you please merge my request? Thank you.
If anything is preventing the merge, I'd like you to tell me.

**Comment by benz0li** [comment]
The web address for my company is https://www.b-data.io, served by GitLab pages.

**Comment by sleevi** [comment]
You can update your PR with this information.

**Pull request merged**
