### PR TITLE
Adding reserve-online.net, reserve-online.com, bookonline.app, hotelw…

### PR DESCRIPTION
**Pull request by apostolos**
…ithflight.com

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://www.webhotelier.net/

I am the CTO of WebHotelier Technologies Ltd. which provides hoteliers with booking engine systems which are hosted under our domains. The booking engines take the form of <hotelname>.reserve-online.net

Some current examples:

https://mykonosgrand.reserve-online.net/
https://padmaresortlegian.reserve-online.net/
https://albergodelsenatorome.reserve-online.net/

Reason for PSL Inclusion
====

- Cookie Security between subdomains. Each property is usually a complete separate business and we want to prevent cross-engine cookie pollination.

Domain holding period:
- `reserve-online.net`: registered 2008-03-17 (13 years), shall maintain for additional multi-year term.
- `reserve-online.com`: registered 2009-12-24  (11 years), shall maintain for additional multi-year term.
- `hotelwithflight.com`: registered 2013-03-13 (8 years), shall maintain for additional multi-year term.
- `bookonline.app`: registered 2018-05-09 (3 years), shall maintain for additional multi-year term.

DNS Verification via dig
=======

```
dig +short TXT _psl.reserve-online.net
"https://github.com/publicsuffix/list/pull/1254"
```

```
dig +short TXT _psl.reserve-online.com
"https://github.com/publicsuffix/list/pull/1254"
```

```
dig +short TXT _psl.hotelwithflight.com
"https://github.com/publicsuffix/list/pull/1254"
```

```
dig +short TXT _psl.bookonline.app
"https://github.com/publicsuffix/list/pull/1254"
```

make test
=========

Tested & verified

### CODE REVIEW

**Comment by dnsguru** [comment]
See #1245

**Comment by apostolos** [comment]
@dnsguru I understand your reservations regarding the FB issue (removed from the PR), however the point about cookie isolation remains. There is a real need, our platform is used by more than 7000+ individual hoteliers in 45+ countries, each one with a different subdomain under a domain from the list above. These are completely different businesses that must be kept separate.

**Comment by dnsguru** [comment]
Thank you for the clarification @apostolos

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Pull request merged**
