### PR TITLE
AWS ap-south-1 EC2 and S3 domains

### PR DESCRIPTION
**Pull request by lawells**
*Adding ap-south-1.compute.amazonaws.com EC2 domain
*Adding s3-ap-south-1.amazonaws.com and s3.ap-south-1.amazonaws.com S3 domains

### CODE REVIEW

**Comment by sleevi** [comment]
@lawells - Would Amazon be willing to consider `*.amazonaws.com` and `*.*.amazonaws.com` (or `*.compute.amazonaws.com` ) ?

I'm wondering if that might offer a more scalable, efficient means of handling these additions. It does cause some limits on what the subdomains you can have under amazonaws, but would help you launch quicker and with fewer risks.

**Comment by weppos** [comment]
@sleevi per https://github.com/publicsuffix/list/issues/145 `*.*.amazonaws.com` is currently formally valid, but practically not supported. Unless I missed something.

**Comment by sleevi** [comment]
@weppos That's why I suggested `*.compute.amazonaws.com` :) Trying to figure out if there's a more general expression of the hierarchy of suffices, which could prevent churn and also help reduce the PSL size

**Comment by lawells** [comment]
@sleevi, let me talk it over with a couple folks. re: *.compute.amazonaws.com, if we still have to add S3 subdomains then it's not really that much net gain for the PSL or Amazon since we're still having pull requests for each new region. @weppos from #145  it also looks like s3.*.amazonaws.com would not work either?

**Comment by sleevi** [comment]
I'm guessing formatting screwed up for @lawells 

The benefit of `*.compute.amazonaws.com` is that it reduces the number of distinct entities (and can help browsers behave slightly faster if they're using DAFSA/Tries rather than perfect hashes), even if you'd still need to add entries for distinct `.amazonaws.com` entries.

Note that `*.compute.amazonaws.com` and `*.amazonaws.com` are both valid entries (and can be used together), indicating everything under compute is a public suffix, but also anything under amazonaws.com is as well. The only reason you would *not* want to do this is if you wanted `foo.amazonaws.com` and `bar.amazonaws.com` to share cookies/other security state.

**Comment by lawells** [comment]
@sleevi I've got the question out to a couple folks. will keep you posted...

**Comment by sleevi** [comment]
@lawells Would `*.elb.amazonaws.com` do what you need instead?

**Comment by lawells** [comment]
@sleevi @weppos AWS would like to keep regional domains instead of wildcarding for the following reasons:
1. Our goal is to have regional independence, meaning that eu-west-1 should not affect us-east-1, whereas *.compute.amazonaws.com, *.elb.amazonaws.com and *.amazonaws.com introduces the potential for sharing cookie state across multiple regions/subdomains.
2. Not all browsers honor the * syntax in a determinable way, e.g. see the Internet Explorer note in [https://devcenter.heroku.com/articles/cookies-and-herokuapp-com] 
3. If we were to introduce another subdomain layer in the future, e.g. "<new-aws-controlled-subprefix>.<region>.amazonaws.com" then we could be susceptible to broadly scoped cookies sharing state.

**Comment by sleevi** [comment]
@lawells Regarding #1, you may be misunderstanding what the wildcard rule says.

`*.elb.amazonaws.com` means that `foo.elb.amazonaws.com and `bar.elb.amazonaws.com` are both public suffices, and thus can't share state, nor can their subdomains. That seems to align with exactly what you want.

Regarding #2, the issue is not with the wildcard syntax, the issue is that IE did not honor or use the PSL *at all*. Edge changed this, and now Microsoft is also consuming the PSL, moving away from their heuristic.

Regarding #3, I'm not sure what you're saying (it looks like your example domain was clipped), but the point of the wildcard is precisely so that you can add regions at will and not have to worry about updating the PSL. As you've currently done it, you're significantly more at risk in introducing new regional zones, because you cannot 'safely' do so until all PSL consumers have updated (which can take up to 18 months).

I'm pretty sure @pzb is tuned into the PSL issues, so maybe ya'll can chat with him internally and see if there's a strategy that gives Amazon the flexibility it needs, w/o adding risk. But I'm pretty sure everything you said you're concerned about is exactly the thing wildcards help mitigate, rather than cause :)

**Comment by lawells** [comment]
@sleevi talking to @pzb now...

**Comment by sleevi** [comment]
Any updates?

**Comment by lawells** [comment]
@sleevi sorry for the delay...I think we finally have the best possible wildcarding case for AWS. EC2 and ELB are drastically simplified, however, S3 is still growing and will need to be updated in the future. Would be great to do:
<code>
s3.\*.amazonaws.com</code>
<code>
s3.dualstack.\*.amazonaws.com
</code>

With the above two, it would only leave the s3-ap-southeast-1.amazonaws.com domains to be updated.

**Comment by sleevi** [comment]
Awesome, thanks for taking a pass on this.

I think it's unlikely we'd be able to add support for your S3 case in any reasonable time, and I think it'd cause a fair number of issues for clients (all, AFAICT, assume they can stop processing at a wildcard, and I think that's probably desirable). As such, it may be worthwhile to think about how you're going to expand S3 in the future, because it may be necessary to apply limits (to organizations and additions) in the coming future, to help mitigate growth.

@gerv @weppos Mind cross-checking and making sure we're happy with authorization?

**Comment by lawells** [comment]
@sleevi @pzb @weppos @gerv Any thoughts?

**Comment by sleevi** [comment]
Oh, sorry @lawells I had thought I merged this.

If you can rebase, I can merge either tonight or tomorrow :)

@weppos How do we want to authenticate? @pzb indicates that @lawells is a coworker :)

**Comment by lawells** [comment]
@sleevi sorry about that, did a rebase - you should be good to merge!

**Comment by weppos** [comment]
> @weppos How do we want to authenticate? @pzb indicates that @lawells is a coworker :)

@sleevi I personally authenticated him at
https://github.com/publicsuffix/list/issues/105#issuecomment-180260499

It's a 👍  for me.

**Comment by sleevi** [comment]
@lawells There's still some conflicts with master (and perhaps we merged something after your rebase). I can try to manually fix it up tomorrow morning, or if you're able to get it clean from the web interface, I'll squash and merge sooner :)

**Comment by lawells** [comment]
@sleevi should be good now

**Comment by 131** [comment]
I do not understand something.
I thought that *.compute-1.amazonaws.com beeing a level 4 tld, means that ec2-23-20-71-128.compute-1.amazonaws.com is a TLD, on ONLY a tld. And therefore cannot be used a a domain name alone.
Yet, this URL  : http://ec2-23-20-71-128.compute-1.amazonaws.com/news/uk-news/2020/04/14/life-on-the-inside-10-ways-to-ease-an-anxious-mind-during-lockdown/ 
Is somewhat.. invalid ?

Please help me understanding what's going on here

**Comment by sleevi** [comment]
No, it doesn’t work that way, for the same reason as appspot.com or
github.io

**Pull request merged**
