### PR TITLE
Add publishproxy.com to PSL

### PR DESCRIPTION
**Pull request by sjnickerson**

### CODE REVIEW

**Comment by sirdarckcat** [comment]
+ @sleevi

**Comment by sleevi** [comment]
@sirdarckcat https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by sirdarckcat** [comment]
Interesting.. sounds like a good chance to test the DNS method for Google.
Did this get automated? Or is it manual changes?

Simon, could you file a ticket with traffic team?

**Comment by sleevi** [comment]
It's still manual, for now. It's not strictly required to use the DNS method, but it would be great if Google could, as opposed to me harassing you on internal corp communications to vet :D

Sorry, I was on mobile when I linked to it, but ideally, we'd treat all pull requests - big or small - the same. In particular, https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change - A brief description of why, ideally expected input/output, and any extra information to help vet this.

**Comment by sjnickerson** [comment]
Thanks.

1. publishproxy.com is going to be used to host DNS records for customer sites. We are concerned that a poorly configured site could end up attempting to set a cookie on publishproxy.com rather than the correct domain.

2. I am expecting the public suffixes for foo.bar.publishproxy.com and foo.publishproxy.com to be publishproxy.com.

3. I am working on getting the DNS TXT verification token added. I will report back when it's ready.

**Comment by sjnickerson** [comment]
$ dig +short txt _psl.publishproxy.com
"https://github.com/publicsuffix/list/pull/294"

**Comment by sjnickerson** [comment]
DNS verification should now be possible for this domain.

**Comment by sjnickerson** [comment]
Friendly ping for this pull request?

**Comment by groundcat** [comment]
@sjnickerson Do you still need this entry in the PSL?

The domain publishproxy.com no longer seems to serve the purpose of "hosting DNS records for customer sites," as stated in the original request.

The _psl record no longer exists. (Reminder: you need to maintain the _psl records if you want to keep it in the PSL.)

If the domain has been decommissioned and is no longer associated with an active project as described in your original request, please confirm that it can be safely removed from the PSL. If so, kindly submit a PR to roll it back to avoid leaving unnecessary debris for PSL volunteers and future registrants to manage (#1996). Thank you.

**Comment by sjnickerson** [comment]
I confirm that it can be removed, but I am not able to submit a PR to
remove it until I get back from vacation.

**Comment by groundcat** [comment]
Hello @sjnickerson , it seems that the project associated with your domain `publishproxy.com`, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. If the service has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

We are also looking into a number of Google's blogspot cctld domains in #2100 - Is there somebody whom you could ping?

---

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Comment by groundcat** [comment]
Created PR https://github.com/publicsuffix/list/pull/2131 to remove it.

@sjnickerson  We are also looking into a number of Google's blogspot cctld domains in https://github.com/publicsuffix/list/pull/2100 - Is there somebody whom you could ping?

**Pull request merged**
