### PR TITLE
Add `vultrobjects.com` and future regional subdomains

### PR DESCRIPTION
**Pull request by mozulamt**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__
  * [X] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [X] This request was _not_ submitted with the objective of working around other third-party limits

  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

```
Seriously, carefully read the downline flow of the PSL and the
guidelines. Your request could very likely alter the cookie and
certificate (as well as other) behaviors on your core domain name in
ways that could be problematic for your business.

Rollback is really not predictable, as those who use or incorporate
the PSL do what they do, and when. It is not within the PSL volunteers'
control to do anything about that.

The volunteers are busy with new requests, and rollbacks are lowest
priority, so if something gets broken by your PR, it will potentially
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---
Description of Organization
====

Organization Website: https://www.vultr.com/

My name is Niels Maumenee. I am a Cloud Storage Engineer and Product Manager of
Vultr Objects, a highly available S3 compatible object storage product at
Constant (the parent company of Vultr). Vultr, founded in 2014, is on a mission
to empower developers and businesses by simplifying the deployment of infrastructure
via its advanced cloud platform. Vultr is strategically located in 19 datacenters
around the globe and provides frictionless provisioning of public cloud, storage
and single-tenant bare metal compute resources.

Reason for PSL Inclusion
====

Submitting *.vultrobjects.com would have security benefits with regards to
cookies or potential cross-site scripting attacks for users of vultrobjects products
and services. In addition, having Vultr Objects in the public suffix list may help
Internet Service Providers identify potential phishing and/or spoofing attacks by
individual users of Vultr Objects as opposed to service as a whole.

We also have plans to expand the Vultr Objects S3 service to additional points
of presence and therefore would like to extend the same functionality to all
content that utilizes the same top level domain of *.vultrobjects.com.

This request is for our object storage sites only at this point and no previous
requests have been made to include any Vultr products or services at this time.

Finally, it is worth noting that vultrobjects.com expires before the criteria:
Lack of proper domain ownership or expiry dates less than 2Y away
We have owned vultrobjects.com since February 15, 2019 and intend to renew our
registration with Godaddy before the Registry Expiry Date: 2023-02-15T16:17:41Z

```
$ whois vultrobjects.com | grep Date
   Updated Date: 2021-02-16T12:59:32Z
   Creation Date: 2019-02-15T16:17:41Z
   Registry Expiry Date: 2023-02-15T16:17:41Z
Updated Date: 2019-05-16T00:51:12Z
Creation Date: 2019-02-15T11:17:41Z
Registrar Registration Expiration Date: 2023-02-15T11:17:41Z
```

DNS Verification via dig
=======

dig +short TXT _psl.vultrobjects.com
"https://github.com/publicsuffix/list/pull/1470"

make test
=========

test ran and passed

### CODE REVIEW

**Comment by mozulamt** [comment]
Updated DNS to reflect the updated pull request number
```
dig +short TXT _psl.vultrobjects.com
"https://github.com/publicsuffix/list/pull/1472"
```

**Comment by dnsguru** [comment]
Thank you for the submission.  Is there a reason that the box was not ticked next to disclosures about rate limits in this PR?

**Comment by mozulamt** [comment]
That was an oversight on my part. We agree to disclose any rate limits with regards to IOS 14.5+ and Facebook.

**Comment by mozulamt** [comment]
Hello. Just curious if there are any other blockers keeping this pull request from being merged?

**Review by dnsguru — APPROVED** [review]
- DNS Tests Pass
- No Conflict with base
- Tests Pass
- Follows Guidelines

APPPROVED

**Comment by dnsguru** [comment]
@mozulamt MERGED

**Pull request merged**
