### PR TITLE
Add .vlogs.com.br in Public Suffix Llist

### PR DESCRIPTION
**Pull request by rhuano**
+// Company : http://www.registry.com-br.biz Saymon Rhuano Dias de Andrade - ME
+// Submitted by Saymon Rhuano <ceweb.br@gmail.com>
+br
+com.br
+vlogs.com.br

### CODE REVIEW

**Comment by weppos** [comment]
@rhuano your PR contains several changes beyond the scope of what is supposed to be your request. Please provide a new PR containing only the proposed changes for evaluation.

**Comment by rhuano** [comment]
@weppos How do I apply for a new PR, because I'm not getting. Can you help me please?

**Comment by rhuano** [comment]
@weppos I can not understand how to include a domain in "Public Suffix List" I'm trying to include vlogs.com.br domain suffixes in the private section, but do not understand the Guidelines.

If you can help me, I'll be very happy, because I'm not very good at Public Suffix.

**Comment by rhuano** [comment]
@weppos I read the link you gave me, but I can not understand.

**Pull request closed without merging**
