### PR TITLE
Add hd.free.fr domains

### PR DESCRIPTION
**Pull request by r0ro**
Add a new suffix end user can choose to get a custom domain name

### CODE REVIEW

**Comment by weppos** [comment]
@r0ro do you represent freebox.fr and/or are you the owner of the domain you are submitting?

**Comment by r0ro** [comment]
Yes, I am. I was the one submitting the first inclusion in the list. (https://github.com/publicsuffix/list/pull/129)

Freebox and Free (and Online.net) are subsidiaries of 'Iliad' (see: http://www.iliad.fr/en/societes.html), and xxx.hd.free.fr domains are offered to Free broadband customers to get a free domain name and custom reverse dns (see: http://www.free.fr/assistance/54.html)

Due to the way this domain is managed, dns entry is not easy to setup, can you valide this domain by emailing me at rfliedel@corp.free.fr ?

**Comment by weppos** [comment]
@r0ro I'd actually have to ask you to provide the DNS entry. The reason is because we are working towards automating it, hence we'd rather not proceed anymore with email validation (as it's very error prone).

Also please follow right-left sorting (which means the new entry should go before freeboxos.fr, that should be moved before freebox-os.fr)

**Comment by r0ro** [comment]
Just to be sure the correct order should be:
```
freebox-os.com
freeboxos.com
fbx-os.fr
fbxos.fr
hd.free.fr
freeboxos.fr
freebox-os.fr
```

because the pslint.py says it should be

```
freebox-os.com
freeboxos.com
fbx-os.fr
fbxos.fr
freebox-os.fr
freeboxos.fr
hd.free.fr
```

I'll push on the admin to get the proper dns record ...

**Comment by bcecchinato** [comment]
@r0ro Since you are part from Illiad's company, would it be possible to add dedibox.fr as well ?

Regards,

**Comment by r0ro** [comment]
@bcecchinato I can ask but why ? I think it's only used for default server names

**Comment by bcecchinato** [comment]
@r0ro My bad I forgot to tell why. Letsencrypt is using this is to remove limit rates when requesting ssl certificates :) (see #88 for instance).

**Comment by r0ro** [comment]
I'm not sure it's something we want to encourage, and not so much people seems to be using it: https://crt.sh/?Identity=%25dedibox.fr&iCAID=16418&n=1000

**Comment by sleevi** [comment]
Any update on the proper DNS record?

**Comment by Chris12345678900** [comment]
Why this domain is always in pending validation?
Will it be added one day to the list?
Tanks

**Comment by gerv** [comment]
@Chris12345678900: it needs the proper DNS record put in place, as requested in December. See https://github.com/publicsuffix/list/wiki/Guidelines .

**Pull request closed without merging**
