### PR TITLE
add support for scaleway subdomains

### PR DESCRIPTION
**Pull request by remyleone**
- [x] Description of Organization
- [x] Reason for PSL Inclusion
- [x] DNS verification via dig
- [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

# Reason for this Pull Request

(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: <https://www.scaleway.com>

I'm Rémy Léone, I work as an Engineering Manager and cloud developer advocate at Scaleway.
Scaleway is a cloud provider that offers different kinds of managed services for our customers.
Some of those services include DNS functionality: for instance, a DNS record will be added to a load balancer or an instance server.

Reason for PSL Inclusion
====

Product | Sub-domains available for customers | Examples
-- | -- | -- 
baremetal | - `fr-par-1.baremetal.scw.cloud` <br/> - `fr-par-2.baremetal.scw.cloud` <br/> - `nl-ams1.baremetal.scw.cloud` <br/> - `dedibox.fr` | - `11111111-1111-1111-1111-111111111111.fr-par-2.baremetal.scw.cloud` </br> - `sd-167474.dedibox.fr` 
serverless | - `fnc.fr-par.scw.cloud` <br/> - `functions.fnc.fr-par.scw.cloud` | https://fdsfdsnhuqkasr-sdfsfsfsd.functions.fnc.fr-par.scw.cloud 
k8s | - `nodes.k8s.fr-par.scw.cloud` <br/> - `nodes.k8s.nl-ams.scw.cloud` <br/> - `nodes.k8s.pl-waw.scw.cloud` <br/> - `k8s.scw.cloud` <br/> - `k8s.fr-par.scw.cloud` <br/> - `k8s.nl-ams.scw.cloud` <br/> - `k8s.pl-waw.scw.cloud` | `11111111-1111-1111-1111-111111111111.api.k8s.fr-par.scw.cloud` <br/> - `*.11111111-1111-1111-1111-111111111111.nodes.k8s.fr-par.scw.cloud` 
Instance | - `priv.instances.scw.cloud` <br/> - `pub.instances.scw.cloud` | `11111111-1111-1111-1111-111111111111.pub.instances.scw.cloud` <br/> `11111111-1111-1111-1111-111111111111.priv.instances.scw.cloud` 
LB | - `lb.fr-par.scw.cloud` <br/> - `lb.nl-ams.scw.cloud` <br/> - `lb.pl-waw.scw.cloud` | `51-158-57-55.lb.fr-par.scw.cloud` 
AI | - `smartlabeling.scw.cloud` <br/> - `scalebook.scw.cloud` | `11111111-1111-1111-1111-111111111111.smartlabeling.scw.cloud` 
object storage | - `s3.fr-par.scw.cloud` <br/> - `s3.nl-ams.scw.cloud` <br/> - `s3.pl-waw.scw.cloud` <br/> - `s3-website.fr-par.scw.cloud` <br/> - `s3-website.nl-ams.scw.cloud` <br/> - `s3-website.pl-waw.scw.cloud` | - https://dumpremy.s3.fr-par.scw.cloud 
Webhosting | - `whm.fr-par.scw.cloud` <br/> - `whm.nl-ams.scw.cloud` | - `pf-1000.whm.fr-par.scw.cloud` <br/> - `pf-1001.whm.fr-par.scw.cloud` <br/> - `ns1.whm.fr-par.scw.cloud` <br/> - `ns2.whm.fr-par.scw.cloud`

We tried in the past to be included: https://github.com/publicsuffix/list/pull/684 

DNS Verification via dig
=======

```
dig +short TXT _psl.fr-par-1.baremetal.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.fr-par-2.baremetal.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.nl-ams-1.baremetal.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.fnc.fr-par.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.functions.fnc.fr-par.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.k8s.fr-par.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.nodes.k8s.fr-par.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.lb.fr-par.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.s3.fr-par.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.s3-website.fr-par.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.whm.fr-par.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.priv.instances.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.pub.instances.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.k8s.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.k8s.nl-ams.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.nodes.k8s.nl-ams.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.lb.nl-ams.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.s3.nl-ams.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.s3-website.nl-ams.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.whm.nl-ams.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.k8s.pl-waw.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.nodes.k8s.pl-waw.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.lb.pl-waw.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.s3.pl-waw.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.s3-website.pl-waw.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.scalebook.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.smartlabeling.scw.cloud
"https://github.com/publicsuffix/list/pull/1507"

dig +short TXT _psl.dedibox.fr
"https://github.com/publicsuffix/list/pull/1507"
```

make test
=========

I've run the test using:

```
brew install icu4c
echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.zshrc
echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.zshrc
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"
make test
```

The tests run fine.

### CODE REVIEW

**Comment by dnsguru** [comment]
This request eliminated many of the typical tickboxes present on a standard requestor form that are really not mandatory, so please replace them or make a new request and respond to them.  Without this, the request would be closed as wontfix

Also, some of the use cases listed may be in violation of the non-acceptance criteria - specifically the LB one or those that channel an IP address may require additional reviews.  Others may also fall into the non-acceptance criteria, so this request may take additional time to process to ensure those reviews are possible.  We are volunteer-based, so that timing is on an 'as available' basis.

**Comment by remyleone** [comment]
Hello, @dnsguru I'm still working on this PR to get it to the standard required for passing a review. I will notify you once I fill up all the required fields. I mostly opened to get started internally at scaleway and update the DNS zone with the right URL for the TXT record.

**Comment by remyleone** [comment]
@dnsguru thanks for your patience and for your time 🙏 , I've added back the tickboxes and completed the section. If you think some details are still missing do not hesitate to ask them. 
As for the load-balancers, the IPs are those of our customers that are shipped with an LB. It is not a service like `xip.io`. It only resolves the IP of the LB.

**Comment by dnsguru** [comment]
I have not had response from other maintainer volunteers related to the lb component being in compliance with (and not against our) guidelines and acceptance criteria, and really need to get that before proceeding.

@remyleone If you'd like this to go through faster so that the lb discussion/approval does not hold the whole entry up, could you take the lb component out for now and submit that as an amendment?

**Comment by remyleone** [comment]
@dnsguru thanks a lot for your answer. Here's are two options:

Option1: I remove the load balancer part and we can merge this pull request. The problem with this option is that it is suboptimal and it leaves us with something remaining to be done.

Option2: You can open a Scaleway account, communicate me your organization number and I can provide you with a voucher so that you can test for free and in complete autonomy our products and gain confidence that this MR complies with your guidelines and acceptance criteria.

If you have other options, I'm willing to negotiate and provide you all the assistance you need :) Worst case scenario we can stick with option 1. Having something merged is better than nothing at all.

**Comment by dnsguru** [comment]
The other volunteer colleague who reviews IP stuff is on sabbatical leave with no ETA on return for review, but I am not sure that they'd have the extra volunteer cycles for option 2 (I certainly don't, but appreciate your suggestion) so we have to just wait if not Option 1 

I was offering an opportunity at your choice between the lesser of two sub-optimals - which is still open

**Comment by remyleone** [comment]
Option 1 should be available now. I would appreciate a notification when your colleague is back and I can contribute the configuration for the lb product. :)

**Comment by dnsguru** [comment]
> Option 1 should be available now. 
Thanks, and sorry you had to pick the lesser of two evils here, but wanted to offer an option to have the majority of what you were looking for move forward.

> I would appreciate a notification when your colleague is back 
So would I.  We volunteer here, so I ask you to instead of enrolling me for this to keep this to-do on YOUR side, as I lack the cycles or a tool to track that for you and would not seek to fail given your importance

**Comment by dnsguru** [comment]
@remyleone scalebook.scw.cloud does not have PSL TXT record and dedibox.fr is returning PR #684

```
scalebook.scw.cloud:
dedibox.fr:"https://github.com/publicsuffix/list/pull/684"
```

Please fix those two and I'll have a look next volunteer cycle I have in the next few days

The rest all validated (putting this here in the record) :

```
fr-par-1.baremetal.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
fr-par-2.baremetal.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
nl-ams-1.baremetal.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
fnc.fr-par.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
functions.fnc.fr-par.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
k8s.fr-par.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
nodes.k8s.fr-par.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
s3.fr-par.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
s3-website.fr-par.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
whm.fr-par.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
priv.instances.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
pub.instances.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
k8s.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
k8s.nl-ams.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
nodes.k8s.nl-ams.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
s3.nl-ams.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
s3-website.nl-ams.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
whm.nl-ams.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
k8s.pl-waw.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
nodes.k8s.pl-waw.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
s3.pl-waw.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
s3-website.pl-waw.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
smartlabeling.scw.cloud:"https://github.com/publicsuffix/list/pull/1507"
```

**Review by dnsguru — APPROVED** [review]
- DNS Validations ok
- Tests Pass
- Sorted to Guidelines
- No Conflict with Base

Approved

**Comment by dnsguru** [comment]
@remyleone MERGED
Thank you for patience with the volunteer cycle availability on this free resource

**Comment by groundcat** [comment]
Hello @ , it seems that some of the domains in your submission, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. 

Examples (NXDOMAIN errors)

```
nodes.k8s.fr-par.scw.cloud
nodes.k8s.nl-ams.scw.cloud
nodes.k8s.pl-waw.scw.cloud
```

If some of the services have been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Comment by groundcat** [comment]
Hello @remyleone , it seems that some of the domains in your submission, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. 

Examples (NXDOMAIN errors)

```
nodes.k8s.fr-par.scw.cloud
nodes.k8s.nl-ams.scw.cloud
nodes.k8s.pl-waw.scw.cloud
```

If some of the services have been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Comment by remyleone** [comment]
Hello @groundcat they are still used. Please keep them.

**Comment by jtherin** [comment]
@groundcat are you sure about your resolvers ?

```
_psl.nodes.k8s.fr-par.scw.cloud. 1800 IN TXT	"https://github.com/publicsuffix/list/pull/1507"
_psl.nodes.k8s.nl-ams.scw.cloud. 1800 IN TXT	"https://github.com/publicsuffix/list/pull/1507"
_psl.nodes.k8s.pl-waw.scw.cloud. 1800 IN TXT	"https://github.com/publicsuffix/list/pull/1507"
```

**Pull request merged**
