### PR TITLE
add cx.ua

### PR DESCRIPTION
**Pull request by cityhostgithub**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://cityhost.ua/

We are hosting provider and domain registrator. Using a lot services on tech subdomains like cx.ua

For Example 
https://prtscr.cx.ua/
http://ip.cx.ua/

Reason for PSL Inclusion
====

The reason for inclusion is a way to using Сloudflare, Alexa and staff like that. 

Some kind of our clients can actually used a cx.ua as a main domain for their project and it should have to use CloudFlare, Alexa and other type of metrics, like yandex or w/e. 

DNS Verification via dig
=======

```
dig +short TXT _psl.cx.ua
"https://github.com/publicsuffix/list/pull/1066"
```

make test
=========

### CODE REVIEW

**Comment by cityhostgithub** [comment]
@dnsguru should be ok ? check it please, thanks.

**Comment by dnsguru** [comment]
@cityhostgithub these PR require more in the rationale to describe the usage and requirement for inclusion than what was provided.  Please review prior PR to see examples.

**Comment by cityhostgithub** [comment]
@dnsguru thank you. pls check.

**Comment by dnsguru** [comment]
Please read : [https://github.com/publicsuffix/list/wiki/Guidelines#validation](https://github.com/publicsuffix/list/wiki/Guidelines#validation)

**Comment by cityhostgithub** [comment]
@dnsguru 

 I have done this before a lot of times. 

What should I get from it ?

**Comment by dnsguru** [comment]
Rationale provided:
>The reason for inclusion is a way to **using Let's encrypt and Сloudflare, Alexa and staff like that**.

https://github.com/publicsuffix/list/wiki/Guidelines#validation :
"We do not accept entries whose sole purpose is to circumvent Let's Encrypt rate limits. They have a form you can use."
Link: [https://letsencrypt.org/docs/rate-limits/](https://letsencrypt.org/docs/rate-limits/)

**Comment by cityhostgithub** [comment]
Why have u thought so ?

This is not actually a reason of adding or cx.ua into psl. 

Tbh : i actually copied info into 'Reason for PSL Inclusion' about LE coz of privious GP request. which was accepted without any problem. 

The main reason we want to reach - is a possibility to use our domains in CF, Alexa and other sort of metriks which are using psl databases. The impossibility of adding domains to the DNS cloudflare creates great difficulties for us and our clients.

Thats all. 

p.s. we dont have any difficulties with LE.

**Comment by cityhostgithub** [comment]
@dnsguru all ok now?

**Comment by cityhostgithub** [comment]
@dnsguru pls check, our clients are waiting. thanks a lot

**Comment by cityhostgithub** [comment]
@dnsguru hi, can we get some info here ? accept or decline or any other solution. 

freezed task keep making sadness. 

if u need some time - let us know, np. 

thanks for understanding

**Review by dnsguru — APPROVED** [review]

**Comment by dnsguru** [comment]
* DNS Validation Check passes
* Rationale reviewed
* tests pass
* No Conflict with base

**APPROVED**

**Pull request merged**
