### PR TITLE
Add powerdms.net for our DevOps team

### PR DESCRIPTION
**Pull request by timwelch**

### CODE REVIEW

**Comment by gerv** [comment]
timwelch: how can we validate this request? Is there an email address @powerdms.net that we can contact?

**Comment by timwelch** [comment]
We don't have email set up on powerdms.net ... We own both powerdms.net and powerdms.com. That's where all of our emails are set up. If you run a whois query on the domain powerdms.net you'll see that my email (tim.welch@powerdms.com) is the contact. On powerdms.com you'll see technical@powerdms.com ... Either of those can be used to verify, as they go to myself.

**Comment by sleevi** [comment]
Can you please update this patch to follow the submission Guidelines ( https://github.com/publicsuffix/list/wiki/Guidelines )

Specifically:
* Remove the date
* Rebase to master
* Sort your entry according to the company name first
* Indicate the validation method to use (TXT record is ideal)
* Provide on this PR a brief description of why you want the suffix(es) to be added to the list

**Comment by sleevi** [comment]
Closing due to no response.

**Pull request closed without merging**
