### PR TITLE
Added forgeblocks.com to psl

### PR DESCRIPTION
**Pull request by roderickparr**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization We are a PaaS delivering customer identity and access management service
====

Organization Website: forgerock.com

Reason for PSL Inclusion Many web security features (notably cookies) rely on the notion of "registerable domain" (eTLD+1) rather than origin for their security boundary. Under this definition, every tenant could be in the same security context, and can for example overwrite each others' cookies and potentially steal them if misconfigured.
====

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by dnsguru** [comment]
@roderickparr please fill out the info above in order for this to get reviewed or proceed

**Comment by roderickparr** [comment]
> @roderickparr please fill out the info above in order for this to get reviewed or proceed

Does the TXT record need to include the https://github.com/publicsuffix/list/pull/XXXX in the TXT data? or is that. part of the dig request?

**Comment by dnsguru** [comment]
the record would be 
_psl  IN TXT "https://github.com/publicsuffix/list/pull/1238"

In the DNS.

Can you put a bit more oopmh into the description above?  The marketing blurb / compnay description is less important than the rationale for why you want this entry included in the PSL.

**Comment by dnsguru** [comment]
That's a sufficient rationale - please ensure the DNS entry is correct - it appears it got processed by markup:
```
_psl  IN TXT "https://github.com/publicsuffix/list/pull/1238"
```
is what it should say.

**Comment by roderickparr** [comment]
DNS TXT record has been added.

**Comment by roderickparr** [comment]
Is this ok to merge?

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Comment by dnsguru** [comment]
@roderickparr Merged! cheers

**Pull request merged**
