### PR TITLE
Add vibe.to

### PR DESCRIPTION
**Pull request by d-rek**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://artisthub.io

I represent ArtistHub. We are a marketing platform for musicians. Our platform allows users to easily create landing pages for their music and brand.

Reason for PSL Inclusion
====

We would like to address iOS advertising limitations by allowing our users to create subdomains on vibe.to and verify them on Facebook. This is a step towards creating a more frictionless platform for our users.

vibe.to has been registered until 2024-04-23.

DNS Verification via dig
=======

```
dig +short TXT _psl.vibe.to
"https://github.com/publicsuffix/list/pull/1320"
```

make test
=========

The test completed successfully.

### CODE REVIEW

**Comment by dnsguru** [comment]
#1245

**Comment by bedfordsean** [comment]
Hi @d-rek 

I don't see any subdomain sites registered at vyb.to? https://www.google.com/search?q=site%3A%2A.vyb.to

Please can you confirm the domain structure, approximately how many artists you serve, and why we cannot see landing pages for these artists? I'd imagine they would want their landing pages to be found via Google etc?

**Comment by d-rek** [comment]
Hi @bedfordsean! 
We haven't publicly launched vyb.to as an available option.
Most of our users are using our other domain (vibe.to)
The common link formats are https://vibe.to/ARTIST or https://ARTIST.vibe.to/SONG for landing pages.

We refrained from adding vibe.to to the PSL list, due to concerns about breaking the existing landing pages using the https://vibe.to/ARTIST format. However, after reviewing the discussions and your other comments, it seems like we can have functionality on vibe.to but should not set cookies on this domain. This works for us since the only cookie we set from our domains is for managing opt-out and is served by privacy.vibe.to.

Am I understanding that correctly? If so, we would add vibe.to to this commit (it already has the verification PSL TXT record set up).

Every subdomain from vibe.to is independently managed and each is correlated with a different business/artist, and should be treated as a different website. Additionally, there is no need to configure events on vibe.to

You can see some vibe.to landing pages (in both URL formats) that Google picked up here:
https://www.google.com/search?q=site%3Avibe.to

We're growing quickly and currently serve landing pages for about 1,000 artists. We're relied on by marketing agencies, indies, and major label artists. Additionally, while Google has picked up some landing pages, our users primarily use us to improve the fan journey during paid campaigns. As a result, a good chunk of our landing page traffic (52%) is currently driven by Facebook ads. We expect this metric to increase as we've recently rolled out an access token integration that our users seem excited about.

**Comment by bedfordsean** [comment]
Thanks for the details! A couple of comments inline below:

> We refrained from adding vibe.to to the PSL list, due to concerns about breaking the existing landing pages using the https://vibe.to/ARTIST format. However, after reviewing the discussions and your other comments, it seems like we can have functionality on vibe.to but should not set cookies on this domain. This works for us since the only cookie we set from our domains is for managing opt-out and is served by privacy.vibe.to.

The cookie you set on privacy.vibe.to will **only** work on "privacy.vibe.to" after addition and propagation on the PSL. It won't work for any other *.vibe.to domain, which is probably not quite what you want for opt-out across your entire site. Each independent subdomain would effectively become responsible for their own cookies.

This may be correct if you intentionally want to distinctly separate those subdomains but if you still rely on cookies between your own subdomains (eg "www.vibe.to" and "privacy.vibe.to") then putting this domain on to the PSL probably isn't the best way to go.

Let us know your thoughts on this!

**Comment by d-rek** [comment]
Thank you for the insight!

After some testing and discussion, I believe our latest opt-in/out system works within those constraints. It sends a withCredential CORS request to privacy.vibe.to, the cookie is processed server-side on privacy.vibe.to, and a JSON'd state is returned to the client.

This avoids cross-domain cookie reads and is now providing shared opt-in/out across all our users' separate custom domains. Examples of different domains using this system:
[https://lucidious.vibe.to/deja-vu](https://lucidious.vibe.to/deja-vu)
[https://listen.blueavemusic.com/TreeHouse](https://listen.blueavemusic.com/TreeHouse)

With this in mind, we'd like to proceed forward by adding vibe.to to the PSL list.

**Comment by n8schloss** [comment]
Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737  

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift. 

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
excellent to hear FB has added this form.  Regret it took a couple months, so there's a queue of folks in limbo, but the help in getting that cleared up is appreciated @n8schloss 

As we are finding out from a lot of really time consuming interaction and Q&A back and forth on requests sourced from the early help page guidance - as well as some folks who have made requests and since rolled them back because of poor understanding of the change impacts,  blindly flowing people to the PSL as some form of salvation for the IOS change impacts to Facebook Pixel without pre-qualification.

Closing this now, please reference it if there is a new one submitted.

**Comment by d-rek** [comment]
Thank you for the update @n8schloss. That makes perfect sense. I'll submit everything through the Facebook form.

And thank you, too @dnsguru. I know the PSL volunteers are working through a lot. Hopefully the new process can provide your team some relief.

**Pull request closed without merging**
