### PR TITLE
add startengine.com

### PR DESCRIPTION
**Pull request by devender-startengine**
* [*] Description of Organization
* [*] Reason for PSL Inclusion
* [*] DNS verification via dig
* [*] Run Syntax Checker (make test)
* [*] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://www.startengine.com

My name is Devender Gollapally, I'am a Principal Engineer at StartEngine.

StartEngine is a FinTech organization. We provide companies a platform and services to raise capital from the crowd.

Reason for PSL Inclusion
====

We provision all new companies with a `*.startengine.com` subdomain. Because of this, requests between companies using `*startengine.com` domains are considered to be same site, leaving them open to CSRF.

We are looking to add `startengine.com` to the Public Suffix List to improve cookie security for all of our companies who do not yet make use of a custom domain.

DNS Verification via dig
=======

```
➜ dig +short TXT _psl.startengine.com
"https://github.com/publicsuffix/list/pull/1287"
```

make test
=========

```
PASS: test-is-public
PASS: test-is-public-all
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-builtin
PASS: test-registrable-domain
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
➜  list git:(startengine_com) ✗
```

Domain Registration
================
[Registrar Registration Expiration Date: 2026-11-17T16:10:24Z](https://www.godaddy.com/whois/results.aspx?checkAvail=1&tmskey=tmskey%3D123&domain=startengine.com)

### CODE REVIEW

**Comment by dnsguru** [comment]
#1245

**Comment by bedfordsean** [comment]
Hi @devender-startengine, 

Can you please provide some examples of accessible *.startengine.com subdomains? I'm searching on Google and cannot see any of them listed, nor can I find any that are accessible given the pattern you currently have in search results of startengine.com/<COMPANY>

**Comment by dnsguru** [comment]
@devender-startengine because you are requesting same domain, please confirm you want to have cookies work at phormed.startengine.com and not work at startengine.com - this is the effective outcome of what you've submitted.

If you seek to have cookies still work on startengine.com it might be advised to use an alternative domain for your roll out and request whatever that domain is.    (See #1283 conversation)

**Comment by devender-startengine** [comment]
> @devender-startengine because you are requesting same domain, please confirm you want to have cookies work at phormed.startengine.com and not work at startengine.com - this is the effective outcome of what you've submitted.
> 
> If you seek to have cookies still work on startengine.com it might be advised to use an alternative domain for your roll out and request whatever that domain is. (See #1283 conversation)

Thank you for pointing that out, let me discuss this internally and get back to you.

**Comment by devender-startengine** [comment]
@dnsguru @bedfordsean 

Thanks for pointing out the implications, we had a lengthly discussion and it was decided that this is really what we want the behavior to be. So when you get a chance go ahead and merge.

CC @se-joe our VP of Engineering

**Comment by dnsguru** [comment]
@devender-startengine please confirm this is not a workaround to third party limits that would violate our guidelines on acceptance.     Specifically: [acceptance/validation](https://github.com/publicsuffix/list/wiki/Guidelines#validation-and-non-acceptance-factors)

**Comment by devender-startengine** [comment]
@dnsguru Thanks for the quick response. I reviewed the acceptance/validation we seem to be in line with your guidelines.

CC @se-joe our VP of Engineering

**Comment by dnsguru** [comment]
trying to move forward ... this will help please tick the boxes next to the ones below that are true

__Submitter affirms the following:__ 
  * [ ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [ ] This request was _not_ submitted with the objective of working around other third party limits
  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

**Comment by dnsguru** [comment]
@devender-startengine please answer the above  -  trying to workthrough the backflow

**Comment by n8schloss** [comment]
Hi @devender-startengine, is this related to iOS 14 and Facebook advertising? If so please see the info below:

Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift.

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Pull request closed without merging**
