### PR TITLE
Added bh.je and bhcod.es

### PR DESCRIPTION
**Pull request by BenjaminEHowe**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [x] DNS verification via dig
* [X] Run Syntax Checker (make test)

Description of Organization
====

I'm an individual who makes various things on the internet. My website is https://www.bh96.uk/.

Reason for PSL Inclusion
====

For some side projects, I may not have complete (or in some cases, any) control over the source code. If If not using their own domain name, these projects are typically subdomains of bh.je or bhcod.es. I would like browsers to treat these appropriately with respect to cookies.

DNS Verification via dig
=======

```
ben@ben-laptop:~$ dig +short TXT _psl.bh.je
"https://github.com/publicsuffix/list/pull/775"
ben@ben-laptop:~$ dig +short TXT _psl.bhcod.es
"https://github.com/publicsuffix/list/pull/775"
```
`make test`
=========

I have run `make test`: https://pastebin.com/U7td9ajQ

### CODE REVIEW

**Comment by sleevi** [comment]
The Public Suffix List is a globally shared resource. Every cookie-using client in the world needs to be aware of it. This must be treated as a shared (although inefficient) resource. Adding personal domains to the list is problematic, and would be desirable not to do this. As you note it's for personal usage, you can make use of Clear Site Data or other appropriate local policies to address this risk.

**Comment by BenjaminEHowe** [comment]
>As you note it's for personal usage, you can make use of Clear Site Data or other appropriate local policies to address this risk.

As I originally posted:
>I may not have complete (or in some cases, any) control over the source code

I'm not sure how Clear Site Data (or any other policies) can help me here - but I suspect that's through my ignorance. Please could you explain how this would work? For example, tlb.bh.je was a tool (now removed) set up to help colleagues at work collaborate on a project. They were hosting their code on the (sub)domain, and I couldn't prevent any shenanigans. While I mostly trust them, I'd prefer to have solid technical measures in place to prevent shenanigans.

Regardless, I've reshuffled things so going forward everything will be (sub)domains branching off one "real" domain: beh.uk. If I create a fresh pull request for that domain, would that be acceptable? I appreciate that I'll be adding ~100 bytes to the PSL, but unfortunately don't see any viable alternative.

**Comment by BenjaminEHowe** [comment]
@sleevi

**Comment by dnsguru** [comment]
Looks like this was an internal dev project - I am reading this quickly so maybe I missed something.  This is a worldwide used resource so this is typically discouraged, if so. 

In any event, if there remains an interest for this as beh.uk, it will require a new PR and according DNS txt validation along with rationale, closing this one for now @BenjaminEHowe @sleevi

**Comment by BenjaminEHowe** [comment]
Will get a new PR raised with additional explanation.

**Pull request closed without merging**
