### PR TITLE
Add elementor.cloud and elementor.cool

### PR DESCRIPTION
**Pull request by antonelementor**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Organization Website: https://elementor.com/

Elementor is, among other things, a Wordpress site building platform.
Registered users get their own subdomain (e.g. username.elementor.cloud or username.elementor.cool) on which their Wordpress sites are hosted.

Reason for PSL Inclusion
====
We'd like to properly isolate each subdomain to prevent global cookie setting on elementor.cloud/elementor.cool and highlight that each subdomain hosts sites of a different user, unrelated to the others.

DNS Verification via dig
=======
```
dig +short TXT _psl.elementor.cool
"https://github.com/publicsuffix/list/pull/1386"
```

```
dig +short TXT _psl.elementor.cloud
"https://github.com/publicsuffix/list/pull/1386"
```

make test
=========
https://gist.github.com/antonelementor/57b8e2eb1bf1b60f8a58771622a5e2f5

### CODE REVIEW

**Comment by dnsguru** [comment]
Is this a work in progress?  There are required minimum elements that are not present in this PR as submitted.  This request cannot proceed without being complete (currently empty description, reason, DNS etc. above, please fix)

**Comment by dnsguru** [comment]
@antonelementor nudge ... if still wanting to proceed, this PM needs more effort to make it complete.  It cannot proceed as-is due to being insufficient

**Comment by antonelementor** [comment]
@dnsguru Hi. I think I fulfilled all requirements. Can you look it, please. Thanks.

**Comment by dnsguru** [comment]
> @dnsguru Hi. I think I fulfilled all requirements. Can you look it, please. Thanks.

Yes, you addressed it.  The rationale works but was a bit briefer than usually supplied.  I am familiar with Elementor, enough that this will suffice, but or bias is to have submitters be wordy

**Pull request merged**
