### PR TITLE
Adding No-IP.com's domains to the PSL.

### PR DESCRIPTION
**Pull request by noipcom**
As title says adding the No-IP.com domain names to public_suffix_list.dat.

### CODE REVIEW

**Comment by weppos** [comment]
I sent an email to validate this PR.

**Comment by noipcom** [comment]
We responded back to the validation email on Saturday. Please let us know if there is anything we can do.

**Comment by markuskr** [comment]
How long will it take from the domain being verified to the domain being on the list? Are we taking days, weeks or months?

**Comment by sleevi** [comment]
As this is done on a volunteer basis, it can take anywhere between days or weeks depending on schedules.

**Comment by markuskr** [comment]
Thanks for the quick response, you are doing a great job!

**Comment by mrbscreen** [comment]
Hi. Something to say about the timeline? Thank you.

**Comment by gerv** [comment]
We need to hear back from @weppos before we can merge this.

Gerv

**Comment by kTitan** [comment]
@weppos 
Many people are waiting for that. Can You please perhaps give a short status update on the validation? Thank You!

**Comment by noipcom** [comment]
We understand you are very busy. If there is anything we can do to help please let us know.

**Comment by jblume58** [comment]
@weppos 
I'm one of the many people @kTian was speaking about yesterday.
Since I heared first about letsencrypt the last November I'm waiting for the possibility to create a not self-signed certificate to use my Server securely.
Thank You!

**Comment by weppos** [comment]
We are currently discussing internally what's the best way to proceed given the large amount of requests that we recently received, specifically related to the Let's Encrypt rate-limiting. This PR will be reviewed as soon as we take a decision.

Moreover, this PR contains a long list of suffixes and we'll have to validate the ownership of all of them and make sure they all belong sto no-ip.com, to avoid the risk of including other suffixes by mistake. This will take a little bit of time (and may be some back-and-forth), given the amount of items in the patch.

@jblume58 @kTitan Let's encrypt is not the only CA available. If time and security matter for you, then you may want to consider to initially purchase a certificate from another CA until either this PR is merged, or Let's Encrypt will relax their rate-limiting policy (which is expected to happen, given the restrictive rate-limiting is a temporary measure for the initial period).

We appreciate your patience.

**Comment by kaefert** [comment]
@weppos well, security matters in most use cases, but thanks to Mozilla and other browser vendors which work hard to make the user believe their lie that using a self signed certificate is a DANGER and LESS secure than using non encrypted connections, admins are often forced to compromise on security when there is no money or no legal entity to buy a trusted certificate.

Let's Encrypt finally brings a gleam of hope into those Mozilla caused dark ages that we are in when it comes to security on the web. But once again, Mozilla seems to work hard to keep us in those dark ages.

**Comment by weppos** [comment]
@kaefert let's try to keep personal comments or belief outside of this thread, as they don't add any value to the process and they derail the conversation from the content of this PR. I'd rather not have to lock this PR.

> Let's Encrypt finally brings a gleam of hope into those Mozilla caused dark ages that we are in when it comes to security on the web. But once again, Mozilla seems to work hard to keep us in those dark ages.

As a side note (speaking for myself and not for Mozilla as I don't represent them) you probably missed the fact that Mozilla is one of the main contributors to LE, including the ACME protocol behind LE.

**Comment by thawn** [comment]
would it be possible to do the verification (semi) automatically?
here is a one-liner, that checks whether a line like `Name Server: ns1.no-ip-com` exists in the whois record of the domain on each line of the diff:

      for line in $( cat noip.diff ); do echo ${line#+}; if  whois ${line#+} |grep 'erver:.*no-ip.com' ;then echo true; else echo false;fi; sleep 2; done

To me it seems like using the name server entry of the whois database is a sensible way of checking if the corresponding domain is used as a public suffix for their dyndns service by no-ip.

**Comment by d7415** [comment]
@thawn Amongst other things, that specific search would also catch all No-IP managed domains (e.g. No-IP Plus/Squared). Checking the organisation field may work better, but I don't know whether that is sufficient, and @weppos has said that there are other discussions happening outside of this github issue which will have to be concluded before this happens.

**Comment by thawn** [comment]
@d7415 I am not suggesting to run this as an automated search over all domain names but just over the 88 domains added by this pull request. This would help in verifying whether the respective domains are managed by noip. Also, the line I gave above could be extended to write an automated email to the respective domain manager stating something like: 

    Unless we receive an answer to this email within 5 days, we will add this domain to the public suffix list. This will cause cookies to be restricted to specific subdomains of this domain in most common browsers. If this is intended by the domain owner, no further steps are required. Otherwise please reply to this email. Best regards your publicsuffix staff".

Since noip repeatedly offered their help, I am sure they wont mind and since this email will only go to the contact persons that appear in the whois entries of the 88 domains listed this pull request, no one else should be bothered unless noip made a mistake (which I assume to be unlikely).

A similar approach could also be used for other mass pull requests like this.

**Comment by Panderine** [comment]
hi there. Is this PR pending a decision on how to proceed with this kind of requests (or the rate-limiting policy as a hole) or is just a matter of physical time to manually work it out?

**Comment by weppos** [comment]
> To me it seems like using the name server entry of the whois database is a sensible way of checking if the corresponding domain is used as a public suffix for their dyndns service by no-ip.

@thawn not necessarily. the domain may be delegated to a different provider, partially or entirely. It may also not be delegated at all. Or it may be delegated, but the owner may be a different entity that doesn't want to include the domain in the list. It's our policy that we need the approval of the owner.

> hi there. Is this PR pending a decision on how to proceed with this kind of requests (or the rate-limiting policy as a hole) or is just a matter of physical time to manually work it out?

Both. We are discussing a policy for requests related to LE, plus (as I already explained) this project is maintained on a volunteer basis.

We'll follow up with the poster of this request as soon as we're ready to proceed. Keep asking for the status doesn't help, in fact, it just causes us to fragment our time even further trying to answer to the various emails.

We appreciate your patience.

**Comment by thawn** [comment]
> @weppos It's our policy that we need the approval of the owner.

I understand that, but isn't there a way to automate this at least partially using the whois information? This would make your life much easier particularly for large requests such as this one.

**Comment by lhsei** [comment]
Hi,
are there any news on adding noip's domains?

**Comment by spacemanspiff2007** [comment]
I am also waiting for this!

**Comment by jblume58** [comment]
Me too!

Am 10.02.2016 um 11:02 schrieb spacemanspiff2007:
> I am also waiting for this!
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publicsuffix/list/pull/64#issuecomment-182286755>.
> 


-- 
Jürgen Blumenschein, eMail: blumenschein@huntington-info.eu
Homepage: http://huntington-info.eu/
c/o Sozialdienst St. Josef Hospital
Gudrunstraße 56, 44791 Bochum
Tel.: +49 234 509-2428, Fax: +49 234 509-2427
public key:
http://huntington-info.eu/Juergen_Blumenschein_(0xC9358EBB)_public_key.asc

**Comment by jobenvil** [comment]
Sorry for pointig this again, me too.

**Comment by Markus87** [comment]
> Sorry for pointig this again, me too.

And probably another 1000 no-ip users too, because the first issued certificates just stopped being valid.(3 months)

**Comment by afcady** [comment]
> We are currently discussing internally what's the best way to proceed given the large amount of requests that we recently received, specifically related to the Let's Encrypt rate-limiting

@weppos Where is this discussion?  Who is in charge of making such decisions?

Thanks.

**Comment by WinPack** [comment]
Me too.

**Comment by jpeeler** [comment]
@weppos At the risk of slowing things down with another "me too", it's been nearly a month since the last status update. Is there anywhere else to view status or any discussion with regard to the rate limiting being relaxed? Also if breaking the pull request apart to a separate commit per domain helps in any way for getting some of them in faster, I'll gladly volunteer!

**Comment by weppos** [comment]
> Is there anywhere else to view status or any discussion with regard to the rate limiting being relaxed?

This is Let's Encrypt specific question you should ask on the [Let's Encrypt forum](https://community.letsencrypt.org/).

I don't think splitting would help, not at this point. If you look at the various recently commented tickets you'll see we have spent a reasonable amount of time in the last months trying to get better tools to make sure the requests we accept are well tested. We don't want to risk to mistakenly add not-validated domains.

There's still some work to be done on this side, and that's the real priority at the moment. Moreover, even if this PR should get merged today, it will probably take some reasonable amount of time before landing into the LE codebase as there are currently discussions around changing the way the PSL changes are loaded into Go and the LE repo itself.

Therefore, if the goal is to be able to use Let's Encrypt, my advice is to be patient and wait for the service to get out of beta and/or be able to accept more domains. There is a good reason why they set rate-limits, and all the people commenting here should understand that.

If privacy and security is really important to you, you can still buy a certificate today for 1 year at a price lower than 1 coffee per month and be setup for an entire year. At that point, Let's Encrypt will probably be out of beta and be able to accept a larger number of requests.

The PSL existed for almost 9 years, and it looks like everybody magically discovered it just in the last 3 months. So please, just be patience and trust that we are doing as much as we can to manage the requests in a way that will continue to provide a valuable service for the consumers of the PSL.

We appreciate your understanding.

**Comment by afcady** [comment]
@weppos:

> If privacy and security is really important to you, you can still buy a certificate today for 1 year at a price lower than 1 coffee per month and be setup for an entire year. At that point, Let's Encrypt will probably be out of beta and be able to accept a larger number of requests.

Of course, you can get **a** certificate like that.  Indeed, you can get **a** certificate from Let's Encrypt *for free*.

But what you cannot do, probably for any amount of money -- and definitely not for less than several thousands of dollars per month -- is get a **CA certificate** signed.  And a CA certificate is what you would need in order to secure a public suffix.  Because if you just get a wildcard certificate for your suffix (which, by the way, isn't as cheap as a coffee/month, or even a coffee/day) then you have to share the same private key between all of the different people using your public suffix -- which defeats the security completely.

So, in truth, there is no way.  I don't say this to complain about it, but just to acknowledge reality.

**Comment by afcady** [comment]
(Also, is it actually true that anyone, other than Let's Encrypt, will sign a certificate for a subdomain of a privately-owned public suffix, for someone who does not own the suffix?  For any amount of money?  Will *anyone* sell a certificate for `joeschmoe.blogspot.com`?  I'm not sure, but I doubt it.)

**Comment by d7415** [comment]
@afcady I'm pretty sure the suggestion was that the users of the public suffix could get a certificate each. A shared wildcard would be silly. And to reiterate the point, the Public Suffix List is not a part of Let's Encrypt - it's a separate (and older) project. LE may be why so many people are interested all of a sudden, but the PSL maintainers aren't really responsible for that.

I'm not sure who will sign certs like that. I think cacert will, but they have their own issues.

Back to the point though, LE-specific things should probably be kept on **their** github/forums/etc rather than here.

**Comment by afcady** [comment]
@d7415 see my follow-up comment.  I don't think that that is in fact possible.  Of course, maybe CACert will sign a certificate.  You can even sign your own certificate . *Anybody* can download OpenSSL and sign *any* certificate request.  But are we being silly or are we not being silly?  Because the signing CA needs to be trusted by browsers.  Sharing private keys is less silly than signing certificates with untrusted CAs.

> LE may be why so many people are interested all of a sudden, but the PSL maintainers aren't really responsible for that. [...] Back to the point though, LE-specific things should probably be kept on their github/forums/etc rather than here.

I don't see how it's LE-specific.  We aren't talking about people *pretending* domains are public suffixes, but *actual public suffixes*, right?  The fact that LE exposed the problem doesn't mean the problem is "LE-specific."

Anyway, *my* point was just that we ought to be realistic and factual about what options are actually available and what options are not.

**Comment by sebasbaumh** [comment]
@weppos I see your point and I can imagine the number of requests currently "rolling" over the public suffix list in terms of issues and pull requests.
Nevertheless I still think this is a point to work on. The suffixes listed in these pull requests are indeed public and every software relying on this list (besides letsencrypt) should treat them as such. Therefore it seems perfectly right to me to enter them in this place.

Don't get me wrong, I'm not blaming the team of the public suffix list for being to slow or something, but I propose you will have to think about scaling up the process on how you verify a public suffix.

What I really would like to know: from a security point of view is there any strong need to execute a complex verification process for every suffix that we are currently unaware of?
Or would it be sufficient to actually live with some false positives in the worst case while increasing verification speed?

Furthermore to reduce the time needed for verification you could try to catch at least some of the cases using a script, which checks the sub-domain for the same owner information as the parent domain. That would reduce the verification process to one manual check of the "main" domain and automated checks of all sub-domains.

**Comment by mrbscreen** [comment]
Hi All,

one work around (which I am using now) could be: Register your own domain with the possibility to add DNS records. 
I created subdomains with CNAME to the corresponding no-ip hostnames.

Example:
host1.mydomain.org has an DNS entry CNAME host1.sytes.net

Yes, you have to use the new name and perhaps a lot of changes, but you are now independent of the no-ip Domains.

**Comment by daw87** [comment]
@mrbscreen: Thank you for this idea! Hadn't thought of this solution and it works great!

**Comment by ThemGo** [comment]
Add MyFRITZ! DynDNS-Service 'myfritz.net'

**Comment by fda77** [comment]
Stillnot fixed, even the pull reques is 3 month old :-/

**Comment by taurus-forever** [comment]
Guys, if you cannot accept whole list, maybe it will be easier to split it?

I believe most of the participants here are waiting for no-ip.* domains, like no-ip.com/no-ip.info/no-ip.org/no-ip.biz

Maybe you can process them first and the rest like "privatizehealthinsurance net" in the last order?

Thank you for the understanding!

P.S. no-ip users will go away soon as letsencrypt certificates are going to be expired now +/- week.

**Comment by jpeeler** [comment]
@taurus-forever I proposed splitting it up two weeks ago, see the response right after.

**Comment by fda77** [comment]
@jpeeler: I propose to start with zapto.org, bacause I use it ^^

**Comment by xxxtonixxx** [comment]
@jpeeler please, ddns.net too :laughing:

**Comment by My1** [comment]
@kaefert "[...] their lie that using a self signed certificate is a DANGER and LESS secure than using non encrypted connections"
well, self signed certs arent exactly less secure than plaintext, BUT the problem of any PKI is on how to check whether the public key REALLY belongs to that domain, which is the main reason CAs exist.

the problem is not that self signed certs are insecure, encryption wise they cna give the same security, but the issue is that a selfsigned cert can be form anyone giving the user a FALSE sense of security, because the cert can be from an attacker.

with DANE the problems of CAs (cost, misissuances etc etc etc) begin to fade away because domain owners are able to specify what keys/certificates are valid for the domain but there are 3 problems.
1) DNSSec is not supported everywhere.
2) even if DNSSec is supported, DANE/TLSA may be not supported everywhere, cloudflare for exmaple.
3) browsers dont support it yet.

DNSSec may be another CA-ish system, but there's a large difference. the tree architecture. meaning that someone who has access to the DNSSec of the com domain cannot affect info domains and so on, unlike the anyone can do everythig approach CAs have, which led to the major problems with DigiNotar etc.

**Comment by kaefert** [comment]
@My1: I agree that using a certificate signed by a trusted authority is more secure than a self-signed certificate.

What makes me furious (which caused me to address this browser policy here although this is probably not the place for that discussion) is that Mozilla and other browser vendors decided to tell their user that using unencrypted http (gray for not perfect but okey) is much better than using self-signed certificates - showing a red icon and nowadays even complex huge warning screens that are difficult to get around

**Comment by My1** [comment]
@kaefert github sadly doesnt do Private messages so read this if you are intrested:
https://gist.github.com/My1/615843f53ff4fb6d2573

**Comment by sleeksorrow** [comment]
What I don't understand is, why is renewing limited, too? I successfully created a certificate for a noip.me hostname and use it since months and propagated it now to the users of my services, and now I cannot renew. 

I'm in some real trouble now.

What's the reason and logic behind that?

**Comment by weppos** [comment]
@sleeksorrow please note this is not the Let's Encrypt project, rather the Public Suffix repository. Issues with Let's Encrypt should not be discussed here but in the [Let's Encrypt forum](https://community.letsencrypt.org/).

**Comment by sleeksorrow** [comment]
I am sorry and I agree with you. I still find my point partly valid as you have the power to solve this dilemma for no-ip users.

**Comment by penoud** [comment]
What usage if didn't work with no-ip and such provider.

**Comment by ezar** [comment]
Please add noip.me certificates!!!

**Comment by My1** [comment]
@ezar the PSL itself has NOTHING to do with certificates it is just the LE uses it. BUT the matter is a different one for the PSL.
it's about setting cookies.

**Comment by uriel-fanelli** [comment]
I do not think this will happen. Never ever. All the IT industry is against self-hosting , you MUST pay an ISP for that. So they make it hard to selfhost, as much as they can.

I am using self signed certificates for selfhosting, and since of my audience, it is ok. When they say the browser is complaining , I just answer "browser issue" and I suggest to use Opera. Opera tells you the certificate is selfsigned, but with a single click allows you to go ahead. 

I am just having fun to look how many naif people is hoping anybody will help or incourage self-hosting , even the so-called "good opensource fighters of freedom". They aim of having monopoly of everything, like facebook and google. 

And you hope they will help selfhosting? Sure... when hell will freeze.

**Comment by TPXP** [comment]
@uriel-fanelli Just to clarify the things, we all paid for an ISP, otherwise we would not be able to see your post. You probably meant a webhost. :wink: 

Still, I have to say it has been way too long for this pull request and others. There is not point making us wait anymore : the owner of the domains gave its agreement, and it is obvious that anyone can get a subdomain from these domains for free. Just register to No-IP and have a look at the list you have when you want to create a domain. These domains are public, this is obvious. 

As said in the Readme, the role of this list is to list all these domains, there is no point in discussing whether these domains should make it to the list or not. They perfectly fit the criterias, so they should.

So what are you waiting for ? No news (and I meant another word...) have been given for a while. And I'm sorry to say that, but the only explanation that comes to our minds after so much time is laziness. I mean, come on, this is your project, and you can't maintain properly, letting Pull Request hanging for too long. What should we do ? Fund a kickstarter to give this project a full-time employee ? That seems like overkill for a little list don't you think ?

@weppos If you can't anymore handle the "huge" workload this project implies (wow, clicking on a button is so hard !), just give ownership of this project to someone else. This is okay, we will forgive you for being honest.

My 2 cents. Don't take it personally, I am just bored to see the enormous lack of professionalism this list (it is just a text file, and over 30 persons have been discussing it ? Really?!) has endured these last months.

**Comment by Markus87** [comment]
Well there was an update to let's encrypt. I read it on the weekend in the forums, people who got a cert can update it now without problems. Worked, at least for me. Still don't know how they will handle new request's though.

**Comment by kaefert** [comment]
1.) @Markus87 If you want to reference something, please do it a little bit more verbose than "on the weekend in the forums" - A link to the thread would have been very nice. I did not find the discussion but I also did not try very hard since easier renewal would not help me anyway without a chance to get a certificate first. 

2.) I can't see how that's even relevant to the issue at hand here: The maintainers of the publicsuffix list are not merging this addition to their list although it fit's the bill perfectly. They have been offered help both by the owner of the domains (noipcom) and also by volunteers that would be willing to code an automated or half-automated checks for big pull requests like this one. Those offers seem to have been ignored.

3.) Project contributer @sleevi told us almost 4 months ago that the merging of this issue would take "anywhere between days or weeks depending on schedules". I guess we're long past that fuzzy time scale.. Is there a new timescale that you could give us?

4.) Pull request assignee @weppos told us over 3 months ago that there is an internal discussion of the public suffix list team how to handle large requests like this one. I guess the word internal has been chosen to tell us that the discussion is private & secret and the public can not observe or even partake in that discussion. It would be very nice if you could tell us though weither the stagnancy that can be observed here is what has been decided in that discussion (In other words that it has been decided to simply ignore large pull requests) or if the discussion is still ongoing or has simply stopped without a result?

**Comment by unclejamal3000** [comment]
First of all this pull request does not comply with the current guidelines so I guess it will not be merged.
https://github.com/publicsuffix/list/wiki/Guidelines

As I see all the TXT records are missing for validation and the "Submitted by" line should not contain the date.
Similar discussion here: https://github.com/publicsuffix/list/pull/68

**Comment by thawn** [comment]
Did anyone inform the contact person at noip about this?

**Comment by sebasbaumh** [comment]
@noipcom could you please add the necessary DNS TXT records like stated in the [Guidelines/DNS Authentication](https://github.com/publicsuffix/list/wiki/Guidelines#dns-authentication) for the subdomains in this pull request?

@unclejamal3000 looking at the commit, it seems like [everyone else](https://github.com/publicsuffix/list/pull/64/commits/dcf9003ebc3bfa19a9ec1e8d3bc4405e77710592#diff-7a8a497c39dadd4b04d30f5e8e679bf8R11200) added the date. So this should not be a big deal. By the way I would have thought that such issues should come up much earlier as someone involved in the public suffix list would have to look at it anyway?

**Comment by jblume58** [comment]
Honestly @weppos, is it so difficult or exhausting to remove a date by yourself?

Other providers in the existing list do have a date at the end of the second line.
There is no rule (or I can't find it) in your guidelines saying there should be no date in the second line (a normal comment).

The easiest way, @weppos, to get rid of this discussion is finally merging the request.

Please, do it soon

**Comment by Markus87** [comment]
@kaefert Sorry, it was late last time I answered. Also because of all the noise around this problem this statement is kind of hard to find: [Lets encrypt - Update to rate limits](https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769/2)

Its not directly related to this issue, but I figured there might be more people in my situation that are watching this issue and are waiting for it to be resolved without knowing that their problem is already solved. Nice fixes like that should be in the community digest e-mail from lets-encrypt.

**Comment by kugnos** [comment]
It's not strictly relevant but perhaps noteworthy: another recent LE update that [LetsEncrypt has now left beta](https://letsencrypt.org/2016/04/12/leaving-beta-new-sponsors.html) after four months [in public beta](https://letsencrypt.org/2015/12/03/entering-public-beta.html), more or less when this PR was initiated. 
> Therefore, if the goal is to be able to use Let's Encrypt, my advice is to be patient and wait for the service to get out of beta and/or be able to accept more domains.

So, following on from @weppos comment - in order for LE to accept more domains (such as noip's), it only needs to know which suffixes are public, and thus sensibly chooses to use the PSL, also created with web security in mind with a different aim but identical result.  (Unless the suggestion is that LE creates a second PSL for itself, thus detracting from this project by needlessly reinventing the wheel?)
Like most others here, I cannot understand why such an ideal candidate for the PSL has gone unattended for so long, and I'm sure that an updated schedule & any explanations for delays would be greatly appreciated by everyone waching this thread.

**Comment by weppos** [comment]
> Like most others here, I cannot understand why such an ideal candidate for the PSL has gone unattended for so long, and I'm sure that an updated schedule & any explanations for delays would be greatly appreciated by everyone waching this thread.

The problem is that most people here only care about their own interest. The majority of the people commenting here have no idea of the work behind maintaining the list, and didn't even took the time to notice that the list keeps being updated constantly, but there are different priorities.

@unclejamal3000 is the very only person lately who took the time to read the Guidelines, which by the way is one of the documents that were written as part of our discussion to formalize the approval process and (potentially) automate it in the future. But (most) people here only care about their own interest, which are not even the PSL interest. They care about getting their free certificate as soon as possible, because clearly that's what the purpose of this list have been for the last 7 years.

I refrained to comment so far because I can make a better use of my time and follow up with the various pending maintenance tasks. But since I read so many selfish comments lately and I was pinged multiple time, here's my answer.

I've been in touch with the owner of this PR, and when we'll be ready we'll follow up on it. I also asked a while ago to kindly stop commenting to this ticket unless comments were providing clear value, but it looks like the same people pretending this PR to be merged did not even took the time to read the history so far.

Therefore, I'm afraid but I will have to lock this conversation. Once more, I appreciate @noipcom for being cooperative and patient. I ensure that we will definitely move forward as soon as ready.

**Comment by weppos** [comment]
I got an email from Deven that informed me they deployed the DNS record for validation to all the domains. I've also followed up with some updates required for the patch.

**Pull request merged**
