### PR TITLE
add mediatech.by and mediatech.dev domains

### PR DESCRIPTION
**Pull request by ugenk**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://mediatech.by https://mediatech.dev

We're company developing applications and solutions for TV and OTT

Reason for PSL Inclusion
====

We're hosting different clients applications/sites/api under our mediatech.by / mediatech.dev subdomains.

DNS Verification via dig
=======

```
$  dig +short TXT _psl.mediatech.by
"https://github.com/publicsuffix/list/pull/1333"
$  dig +short TXT _psl.mediatech.dev
"https://github.com/publicsuffix/list/pull/1333"
```

-->

make test
=========

All the tests passed.

### CODE REVIEW

**Comment by dnsguru** [comment]
@ugenk The PR is missing all of the required information that must accompany a PR (see the link to "contributing guidelines" below in the comment stream on github).

If you are in the process of updating this PR, this can be ignored, but this PR won't proceed unless it is complete.

**Comment by dnsguru** [comment]
Marking this as invalid so it stands out against the other PRs to re-review.  Please read #1245 for important considerations related to requesting subdomains, and indicate if this request was submitted to work around limits.

**Comment by dnsguru** [comment]
@ugenk please complete or close this PR, there is a lot missing and this is currently invalid and not possible to process.

Additionally, please tick the boxes on the following which are true:
__Submitter affirms the following:__ 
  * [ ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [ ] This request was _not_ submitted with the objective of working around other third party limits
  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting
  
  If we don't see a conforming response in the next 7 days, we'll go ahead and close this PR

**Comment by ugenk** [comment]
Hi!

I've updated original comment with all the required data.

- [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see Issue #1245 as a well-documented example)
- [x] This request was not submitted with the objective of working around other third party limits
- [x] The Guidelines were carefully read and understood, and this request conforms
- [x] The submission follows the guidelines on formatting

**Comment by dnsguru** [comment]
The rationale is still too basic - it does not provide the various eyes that read these enough information to process PR

>We're hosting different clients applications/sites/api under our mediatech.by / mediatech.dev subdomains.

But why is a PSL entry needed?  What is the purpose or objective?  

Only stating that the company hosts clients on subdomains is not enough.

**Comment by dnsguru** [comment]
Also you should look at #1337 as a recent rollback of a similar request, and #1342 which requested a core domain and #1343.

We have no control over when or if the various projects, browsers, CA, etc add or remove entries, and those submissions where the domain name of their primary organziation domain in the header is being submitted are often affected in ways that harm the core domain.  Do read those and confirm you want to proceed (once better rationale is provided as well, of course).

**Comment by n8schloss** [comment]
Hi @ugenk, is this PR related to iOS 14.5 changes and Facebook advertising at all? If so please see below:

Posting to let you know that Facebook has updated our guidance to include a validation flow run by Facebook staff. We encourage anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift.

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by ugenk** [comment]
Hi

We have to disable coockies tracking between different client sites hosted on our subdomains.

This PR is not related to ios/facebook.

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base

**Approved**

**Pull request merged**
