### PR TITLE
Update Platform.sh section - add `upsunapp.com`, `upsun.app` domains, remove `bc.platform.sh`

### PR DESCRIPTION
**Pull request by kotnik**
### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing any third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see https://github.com/publicsuffix/list/issues/1245 as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

[Platform.sh](https://platform.sh) is new generation PaaS hosting solution. Our product allows developers to efficiently build, iterate, and deploy applications via Git-based workflow.

Organization Website: https://platform.sh

Reason for PSL Inclusion
====

Developers can create as many environments (clones) of their application using Platform.sh PaaS as they need and those environments will be served from one of the URLs featured here in our part of the PSL. We need our endpoints to be in the PSL for security reasons. Platform.sh is already featured in PSL via [#417](https://github.com/publicsuffix/list/pull/417),  [#1061](https://github.com/publicsuffix/list/pull/1061), [#1256](https://github.com/publicsuffix/list/pull/1256) and [910295a](https://github.com/publicsuffix/list/commit/910295a) (before the PR workflow).

Here, in this merge request, we are removing one endpoint we have deprecated and adding two new ones that we will open soon.

Number of users this request is being made to serve: 50k+, but most probably much more

DNS Verification via dig
=======

```
dig +short TXT _psl.upsun.app
"https://github.com/publicsuffix/list/pull/1792"
```

```
dig +short TXT _psl.upsunapp.com
"https://github.com/publicsuffix/list/pull/1792"
```

Results of Syntax Checker (`make test`)
=========

```
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

### CODE REVIEW

**Comment by dnsguru** [comment]
rationale previously submitted ; not flagging in same way as new entrant, so FAIL situation is self-corrected.

See also
#417
#1061
#1256

**Comment by kotnik** [comment]
@dnsguru thank you for your effort and hard work. Could you please let us know if there is anything missing from our side? Thanks in advance!

**Comment by kotnik** [comment]
Hello. Please take a look at this PR, it is ready and waiting in the queue.

**Review by simon-friedberger — APPROVED** [review]
LGTM

**Comment by fabpot** [comment]
We are about to launch the new Upsun platform and this is on our critical path. Any chance it can be merged? Thank you. @dnsguru

**Review by dnsguru — APPROVED** [review]
* DNS Proof
* Sorted
* Tests pass
* No conflict w base

APPROVED

**Comment by dnsguru** [comment]
@kotnik this is merging, brace yourself

**Pull request merged**
