### PR TITLE
Add linkitools.space to psl

### PR DESCRIPTION
**Pull request by pmatos**
Will create DNS record _psl.linkitools.space pointing to this PR.

### CODE REVIEW

**Comment by sleevi** [comment]
Please see the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

1) Read https://github.com/publicsuffix/list/wiki/Guidelines#prepare-the-change (this does not conform)
2) Read https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change (this does not conform)
  - Indicate why you're requesting
  - Provide sample input/output

**Comment by pmatos** [comment]
Apologies, I fixed 1. by adding company name.
2. Reason for request: to host gitlab pages under the domain. I am following the procedure referenced in: https://docs.gitlab.com/ee/administration/pages/

Samples
```
project1.linkitools.space
project2.linkitools.space
```

**Comment by sleevi** [comment]
You're still in the ICANN section, not the PRIVATE section.

It sounds like this is just for internal purposes, is that correct? Note that your HTTPS link is also misconfigured - https://www.ssllabs.com/ssltest/analyze.html?d=linki.tools

**Comment by dnsguru** [comment]
@pmatos this linkitools.space domain is no longer registered and this is being removed from the PSL

**Comment by pmatos** [comment]
> @pmatos this linkitools.space domain is no longer registered and this is being removed from the PSL

Makes sense, thanks.

**Pull request merged**
