### PR TITLE
Add Mittelab APS domain mittelab.dev

### PR DESCRIPTION
**Pull request by LizardM4**
* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://mittelab.org

Mittelab APS is a non-profit organization based in Trieste, Italy that manages a hackerspace. I am part of the board at Mittelab and a sysadmin of our server infrastructure.

Reason for PSL Inclusion
====

As part of the services offered to our members and staff, we self-host an [instance of Gitlab](https://git.mittelab.org). We recently activated [Gitlab pages](https://docs.gitlab.com/ee/user/project/pages/), a feature that enables users to host static websites at `<username>.mittelab.dev`.

In line with [Gitlab's recommendations](https://docs.gitlab.com/ee/administration/pages/#add-the-domain-to-the-public-suffix-list) (see #268), we would like to add `mittelab.dev` to the PSL, so that browsers can manage cookies and domain highlighting correctly.

DNS Verification via dig
=======

```
dig +short TXT _psl.mittelab.dev
"https://github.com/publicsuffix/list/pull/1033"
```

make test
=========

All tests passed: [log](https://gist.github.com/LizardM4/9d7834c07568d2881579ff8e88c5f97e).

### CODE REVIEW

**Comment by dnsguru** [comment]
Because the PSL is downloaded and used so widely, we typically will politely decline requests for internal use or small lab audiences out of respect for the file size and download requirements.

It appears that this request is to serve a small quantity ( <100 ) of users.

@LizardM4 for how many users is this request?

**Comment by dnsguru** [comment]
+ @weppos In case it is simpler for the submitting party to communicate in Italian, could you help translate?

**Comment by weppos** [comment]
I can provide assistance if necessary.

**Comment by LizardM4** [comment]
Indeed, it's for 55 people; it's reasonable that you accept only requests for >100 users. In that case, I would close the PR for the time being, and reopen only once we reach a larger userbase.

**Pull request closed without merging**
