### PR TITLE
Update Kuwait's ccTLD (.kw)

### PR DESCRIPTION
**Pull request by Bashar**
updating Kuwait's ccTLD (.kw)
Email verification can be done via IANA DB or dig

### CODE REVIEW

**Comment by weppos** [comment]
@Bashar are you responsible for the .KW registry?

**Comment by Bashar** [comment]
@weppos Yes I am https://www.iana.org/domains/root/db/kw.html

**Comment by Bashar** [comment]
@weppos if you recall we were discussing at #641 in April

**Comment by weppos** [comment]
I sent you an email for validation. Please reply to the email for confirmation.

**Comment by Bashar** [comment]
Replied, Thank you

**Comment by weppos** [comment]
Merged, thanks.

**Pull request merged**
