### PR TITLE
Additional ngrok domains - more `ngrok.io` from #48 + `ngrok.app` `ngrok-free.app` `ngrok.dev` `ngrok-free.dev` `ngrok.pizza`

### PR DESCRIPTION
**Pull request by bobzilladev**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
Ngrok provides network ingress and tunneling services for more than 5 million developers. Ngrok is used by engineers to aid in local development, as well as for network connectivity, and management for systems in production. I am an engineer at Ngrok adding additional ingress domains for regional points of presence, grouping different types of customers together, and also offering more customer choice.

Organization Website: https://ngrok.com/

Reason for PSL Inclusion
====
The reason for inclusion is for Cookie Security between different users' sessions. Customers can reserve or be assigned subdomains of these domains for ingress, browsers should not send cookies across them.

The previous PR that added `ngrok.io`: https://github.com/publicsuffix/list/pull/48

Number of users this request is being made to serve: 5 million developers currently ([ngrok.com/customers](https://ngrok.com/customers))
```
ngrok.app        2025-09-12
ngrok-free.app   2025-11-16
ngrok.dev        2025-02-24
ngrok-free.dev   2025-11-16
ngrok.io         2027-05-25
ngrok.pizza      2025-07-21
```

**Example Use-Cases:**

A developer wants to test the code running on their laptop with a system like Twilio that uses webhooks. The developer starts an ngrok agent locally and ngrok provides a public url which forwards encrypted traffic to the service running on their local machine. The developer can then configure Twilio to use that domain to call when an event occurs such as an incoming SMS message. A domain in that situation would look like `84c5df439d74.ngrok.dev`, or  `3a5c10d67779.eu.ngrok.io` if the agent is configured to use the European region (one of seven regions available).

The user can then easily add [webhook verification](https://ngrok.com/docs/cloud-edge/modules/webhook) to make sure it is Twilio making the request, or add [basic-auth](https://blog.ngrok.com/posts/authentication-with-ngrok), [oauth](https://blog.ngrok.com/posts/how-to-secure-your-network-tunnels-with-oauth-fast), [mutual-TLS](https://ngrok.com/docs/ngrok-agent/ngrok#flags-12), [allow/deny CIDR ranges](https://ngrok.com/docs/ngrok-agent/ngrok#flags-12), and other features. More information is in the [Getting Started guide](https://ngrok.com/docs/getting-started), or this Twilio ["6 awesome reasons to use ngrok when testing webhooks"](https://www.twilio.com/blog/2015/09/6-awesome-reasons-to-use-ngrok-when-testing-webhooks.html) post.

Customers can also reserve specific subdomains instead of having them randomly assigned, which could look like `my-company.ngrok.app` or `webhook-development.ngrok.dev`.

Enterprise customers use ngrok to centrally manage and secure ingress for their many applications deployed across public cloud, serverless platforms, their own data center or Internet of Things devices. This article about the recent ngrok funding raise provides a nice overview: [techcrunch.com/2022/12/13/ngrok-a-service-to-help-devs-deploy-sites-services-and-apps-raises-50m](https://techcrunch.com/2022/12/13/ngrok-a-service-to-help-devs-deploy-sites-services-and-apps-raises-50m/)

DNS Verification via dig
=======
```
>> dig +short txt _psl.ngrok.io
"https://github.com/publicsuffix/list/pull/1653"
>> dig +short txt _psl.ngrok.app
"https://github.com/publicsuffix/list/pull/1653"
>> dig +short txt _psl.ngrok.dev
"https://github.com/publicsuffix/list/pull/1653"
>> dig +short txt _psl.ngrok-free.app
"https://github.com/publicsuffix/list/pull/1653"
>> dig +short txt _psl.ngrok-free.dev
"https://github.com/publicsuffix/list/pull/1653"
>> dig +short txt _psl.ngrok.pizza
"https://github.com/publicsuffix/list/pull/1653"
```

Results of Syntax Checker (`make test`)
=========
The tests ran successfully:
```
# TOTAL: 5
# PASS:  5
```

### CODE REVIEW

**Comment by dnsguru** [comment]
please insert DNS proof in each zone being requested for addition for our validation purposes.  Also want to get input from @inconshreveable  as initial submitter, or alternatively if you can also add DNS proof for ngrok.com to indicate you're affiliated with the submitter org, it will help the review process.

**Comment by inconshreveable** [comment]
all good here, thank you @dnsguru

**Comment by bobzilladev** [comment]
The domains' time to expiry has been extended and DNS TXT records are in place, so this PR has now been moved to ready for review.

**Comment by bobzilladev** [comment]
@dnsguru Hello! Could you add this issue to the "List Add/Mod/Del" project if it passes muster? Thanks!

**Comment by dnsguru** [comment]
Can you provide an example of the use case ?  what is an example of what some entries would look like?

**Comment by bobzilladev** [comment]
No problem, I've added some use-cases to the "Reason for PSL Inclusion" section. Thank you for adding this issue on to the To-Do list.

**Comment by dnsguru** [comment]
This took a little longer to review as it required a bunch of hunting and came during a period when there were close to zero volunteer cycles available.

The following are arguments and rationale for advancing this to be merged:
* `ngrok.io` was previously approved in #48 by @weppos
* the initial submitter of #48 has [weighed in above with no objections](https://github.com/publicsuffix/list/pull/1653#issuecomment-1341410300)
* the domain had been identified as potentially requiring security review, but a test to [SpamHaus checker](https://check.spamhaus.org/not_listed/?searchterm=ngrok.io) indicated "clean"

This is documented because of the nature of the premise of the project being to bypass firewalls.  Although the PSL is just a catalog, it seems to have been implemented in a number of ways that infer security of some sort (despite our advice against this).  As such, some additional review was merited, which adds more volunteer time, which in the absense of other volunteers, takes longer.

Moving this to approval now that this has some documentation of the considerations.

If there are security notices that indicate this was done in error, we reserve the right to roll back this PR if directed.

**Review by dnsguru — APPROVED** [review]
* DNS Validates
* Tests Pass
* Followed Sorting/Formatting Guidelines
* No Conflict with Base
APPROVED

**Comment by bobzilladev** [comment]
This is excellent news, thank you to everyone who volunteers their time for the PSL.

**Pull request merged**
