### PR TITLE
Add `ewp.live` (EasyWP)

### PR DESCRIPTION
**Pull request by crabique**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

My name is Alexey, I am representing the [Namecheap Cloud](https://github.com/NCCloud) infrastructure engineering team submitting this PR on behalf of EasyWP product. 

EasyWP is a managed WordPress hosting service provided by Namecheap, allowing users to easily create and manage WordPress sites on our private cloud. We do not require a domain name and provide a public subdomain for all hosted sites that don't have a domain name assigned to them.

Organization Website: https://www.easywp.com

Reason for PSL Inclusion
====

We operate a number of public ingress points to our cloud to shard the customer websites evenly across multiple clusters we operate, every website is assigned a unique subdomain under a sharded ingress mask `*.ewp.live` (e.g. `some-website.ingress-alpha.ewp.live`, the `alpha` part is the wildcard). 

At the moment, ~20k websites don't have a registered domain name assigned to them, so they are only available through their respective third-level subdomains of `ewp.live`. We would like to isolate those websites from affecting each other and the parent domain by cookies, make CSP-bypass attacks a bit more difficult etc.

In order not to bloat the list and allow future scalability more easily, we are adding this as a single wildcard entry instead of the individual ingress subdomains.

Number of users this request is being made to serve: about 20000
 

DNS Verification via dig
=======

```
❯ dig -t TXT _psl.ewp.live +short
"https://github.com/publicsuffix/list/pull/1773"
```

Results of Syntax Checker (`make test`)
=========

Test results are identical to master, rules stage passes but there is an error about unrelated domain on `libpsl/test-registrable-domain` stage (probably because of running in an Alpine container?):
```
psl_str_to_utf8lower(www.�yer.no)=-2
psl_str_to_utf8lower(�aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)=-2
psl_str_to_utf8lower(�aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)=-2
psl_str_to_utf8lower(�aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)=-2
psl_str_to_utf8lower(�aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)=-2
Summary: 5 out of 95 tests failed
```

### CODE REVIEW

**Comment by Sea-you** [comment]
@dnsguru anything we miss here to have it merged?

**Comment by simon-friedberger** [comment]
Can you provide some numbers of how many customers actively and persistently use these domains? For this kind of product users typically abandon them or move to a dedicated domain.

**Comment by crabique** [comment]
The total number of websites using the free subdomains oscillates between 20k and 30k depending on the season and the promotions that we run, but many of them are long-term users. Right now, about 4k are on free domains for more than one year and about 13k more than one month.


Additionally, some customers don't even need a dedicated domain added through our system because they just reverse proxy the subdomain through CloudFlare et al., but we have no reliable way to count those.


As for the domain expiration ineligibility label, we have preemptively extended the domain registration until 2026:
```
❯ whois ewp.live -h whois.nic.live | grep 'Expiration Date'
Registrar Registration Expiration Date: 2026-05-26T13:46:56.29Z
```

**Comment by simon-friedberger** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] ewp.live expires 2026-05-26
* [x] DNS _psl entries
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Pull request merged**
