### PR TITLE
Add `SoftEther.net` Dynamic DNS Service

### PR DESCRIPTION
**Pull request by dnobori**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 
  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: 
https://www.softether.net/
https://www.softether.org/

Hello. We provide the SoftEther DDNS service for free of charge to any registered users worldwide since 2013. As described on the [softether.net](https://www.softether.net/) web page this service allows anyone to register a unique hostname (subdomain) under the `softether.net` domain with associated IPv4 and IPv6 address. Some users use this their DDNS subdomains to operate VPN servers, and other users use it to run original web servers. We have three parent domains: (1) `softether.net`, (2) `v4.softether.net` and (3) `v6.softether.net`. (1) allows both IPv4 hosts (A and AAAA records). (2) allows only IPv4 hosts (A records). (3) allow only IPv6 hosts (AAAA records).

Reason for PSL Inclusion
====

Since many users operate individual and independent VPN servers and web servers in this DDNS service under the `softether.net` domain, it is important that web browsers recognize DDNS parent domains correctly as public domains for security reasons (e.g. prevent sharing cookies).

[https://www.google.com/search?q=site%3Asoftether.net](https://www.google.com/search?q=site%3Asoftether.net)

Number of users this request is being made to serve:
6,863,193 registered hosts on December 18, 2022.
The history of growing number of hosts is published in the following URL:
[https://www.softether.net/](https://www.softether.net/)

DNS Verification via dig
=======

```
$ dig +short TXT _psl.softether.net
"https://github.com/publicsuffix/list/pull/100"
$ dig +short TXT _psl.v4.softether.net
"https://github.com/publicsuffix/list/pull/100"
$ dig +short TXT _psl.v6.softether.net
"https://github.com/publicsuffix/list/pull/100"
```

Results of Syntax Checker (`make test`)
=========

```
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-builtin
PASS: test-is-public
PASS: test-registrable-domain
PASS: test-is-public-all
============================================================================
Testsuite summary for libpsl 0.21.1
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

### CODE REVIEW

**Comment by dnsguru** [comment]
Could you please provide some example use cases on the endpoints that
cookie assignment would occur on?

**Comment by dnobori** [comment]
@dnsguru 
Hello. Thank you for your question.

#### 1. Prevent cookie-sharing between DDNS subdomains

softether.net is an ordinary Dynamic DNS (DDNS) service.
Webmaster A can create any hostname, e.g. example123.softether.net to host the web site http://example123.softether.net/.
Similarly, webmaster B can create another hostname, for example example456.softether.net to host the web site http://example456.softether.net/.

In the above assumptions, there are at least three problems:

(1) Assume that example123's Web site (e.g., CGI) uses a cookie SESSION=abc to interact with the visitor's Web browser. Assume that example123.softether.net is specified as the domain name of the cookie.
After that the example456 web site (e.g. CGI) can set a cookie named SESSION=def to the visitor's web browser. Assume that softether.net is specified as the domain name of the cookie.
The visitor's web browser mixes the cookie set by the example123 web site with the cookie set by the example456 web site. When the visitor again visits http://example123.softether.net/ the web browser combines the two cookie values, SESSION=abc and SESSION=def, and passes them to the example123 CGI. This confuses the behavior of example123's CGI since it expects just SESSION=abc.
(2) When the example123 web site program is misconfigured and uses an authentication token cookie for the domain softether.net, the example456's CGI can receive that authentication token cookie.
(3) Webmasters intentionally set marketing cookies for user tracking across multiple different web sites. Normally, web browsers prohibit such cookie-sharing between different domains. However, currently web browsers consider example123.softether.net and example456.softether.net to be the same domain, so a set-cookie with softether.net domain could cause the user's behavior to be tracked between multiple web operators on this DDNS domain.

All three of the above issues occur security risks to one or more of the integrity, confidentiality, or availability, which are usually developer or visitor expects to web browsers. To resolve this, web browsers need to be correctly informed that the many subdomains under softether.net are created, hosted, managed, and operated by different administrative entities.

The above describes the need for cookie separation in DDNS. There have been multiple precedents for DDNS on The Public Suffix List.
For example:
https://github.com/publicsuffix/list/pull/1359
https://github.com/publicsuffix/list/pull/950
https://github.com/publicsuffix/list/pull/727
https://github.com/publicsuffix/list/pull/732
https://github.com/publicsuffix/list/pull/727

These precedents are based on the reason according to security issues of cookie-sharing in DDNS. SoftEther DDNS is similar to these precedents.


#### 2. Prevent credential and/or privacy leaking by web browser autocomplete functionality across DDNS subdomains

A web browser may share autocomplete database with two or more subdomains that it deems to belong to the same domain. The information that is shared includes privacy information such as user information and autocomplete username or password entries are stored by the password manager. Information stored in example123.softether.net's web forms should be prevented from being re-entered by users on example456.softether.net, either automatically or as a careless mistake of user's UI operation. Some web browsers use The Public Suffix List to prevent autocomplete function's cross-domain sharing. To protect user privacy and maintain confidentiality, it is necessary to ensure that web browsers correctly identify that each of softether.net's subdomains are operated by different entities.

**Comment by dnobori** [comment]
@dnsguru 
Hello.

We submitted this Pull Request in December 2022 and responded to your questions. We believe this listing addition meets the guidelines and validation process.

Perhaps this pull request has been long forgotten. We apologize for the inconvenience, but we ask for your judgment and approval.

**Review by simon-friedberger — CHANGES_REQUESTED** [review]
* [ ] Expiration
  * [ ] softether.net expires 2024-07-25
* [ ] DNS _psl entries
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Pull request closed without merging**
