### PR TITLE
update for .PK ccTLD

### PR DESCRIPTION
**Pull request by ashar9**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [X] Description of Organization
* [X] Robust Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
    - [Cloudflare](https://developers.cloudflare.com/learning-paths/get-started/add-domain-to-cf/add-site/)
    - [Letsencrypt](https://letsencrypt.org/docs/rate-limits/)
    - <UPDATE THIS LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY! REMOVE THIS LINE!>

  * [X] This request was _not_ submitted with the objective of working around other third-party limits

  * [X] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
PKNIC is the .PK ccTLD
.pk Registry 
Please contact us, if needed, at staff@pknic.net.pk

Organization Website:  https://pknic.net.pk

Reason for PSL Inclusion
====
We found it already included in the list (even though this list does not seem to be the result of an RFC, IETF standard, or protocol). Just need to update it to make it accurate.

Number of users this request is being made to serve:

DNS Verification via dig
=======
dig +short TXT _psl.pk
"https://github.com/publicsuffix/list/pull/XXXX"

The DNS record will be added when we obtain the pull ID for XXXX

Results of Syntax Checker (`make test`)
=========
Test Results:

PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_fuzzer
;;============================================================================
Testsuite summary for libpsl 0.21.5
;============================================================================
;# TOTAL: 3
;# PASS:  3
;# SKIP:  0
;# XFAIL: 0
;# FAIL:  0
;# XPASS: 0
;# ERROR: 0
;;============================================================================
Making check in tests
  CC       test-is-public.o
  CC       common.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-public
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public-builtin
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
PASS: test-is-public-all

Testsuite summary for libpsl 0.21.5

;# TOTAL: 5
;# PASS:  5
;# SKIP:  0
;# XFAIL: 0
;# FAIL:  0
;# XPASS: 0
;# ERROR: 0

### CODE REVIEW

**Comment by groundcat** [comment]
- Running `dig +short TXT _psl.pk` against multiple public DNS servers (Cloudflare, Google, OpenDNS, authoritative) consistently shows the correct value of the URL in this PR, confirming it comes from the .PK registry.
- Reasoning/Organization description: from authoritative source as per above.
- Sorting looks correct.

**Comment by simon-friedberger** [comment]
This looks good but I cannot immediately tell if the automatic ICANN merging would create conflicts with this. @dnsguru, do you know?

**Comment by ashar9** [comment]
The contact email was added to file public_suffix_list.dat of our fork.
The email was already there in the PR template (under the description heading).

**Comment by ashar9** [comment]
The required email was added 5 days ago. Do you have any estimate of when
we can see the updated list?

**Review by dnsguru — APPROVED** [review]
* guidelines followed
* authoritative DNS responds with validation PR # as TXT record
* no conflict with base
* tests pass

APPROVED AND MERGED

**Pull request merged**
