### PR TITLE
Add url.tw in public suffix

### PR DESCRIPTION
**Pull request by kencorp131**
sorry. i re-apply once  

+// Company : https://hosting.url.com.tw/
+// Submitted by Ken <ken@corp.url.com.tw>
+url.tw
+

**add DNS record** 
[root@bloga letsencrypt.sh]#  dig TXT _psl.url.tw

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.17.rc1.el6 <<>> TXT _psl.url.tw
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44923
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_psl.url.tw.                   IN      TXT

;; ANSWER SECTION:
_psl.url.tw.            3599    IN      TXT     "https://github.com/publicsuffix/list/pull/393"

### CODE REVIEW

**Comment by kencorp131** [comment]
add 
mymailer.com.tw
twmail.cc
twmail.net
twmail.org

**Comment by kencorp131** [comment]
domain already add _psl  TXT 

If there is any omission of the process, please tell me

**Comment by sleevi** [comment]
Unfortunately, this pull request doesn't conform to the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines)

Please review that document on how to format patches and pull requests and include the necessary details.

It appears you have this in the wrong section, have not formatted the identifying information correctly, have not specified the purpose of this request, and have not provided example domain structure.

Since you mentioned ACME, please also be aware that if your purpose is to increase Let's Encrypt rate limit, the way to do that is not through a pull request, but via contacting Let's Encrypt (see https://letsencrypt.org/docs/rate-limits/ for details, https://docs.google.com/forms/d/e/1FAIpQLSfg56b_wLmUN7n-WWhbwReE11YoHXs_fpJyZcEjDaR69Q-kJQ/viewform?c=0&w=1 for the form). You should only submit a pull request if your needs are captured by https://publicsuffix.org/learn/

**Comment by kencorp131** [comment]
Hi, I tried to fix it. Can I ask if there are any missing issues?

**Comment by kencorp131** [comment]
I keep repeating the Guidelines
I can confirm that I can not apply for the success of the reason is because whois owner email different
Because whois owner email is my boss, I must first confirm it

Thank you for looking at this message

**Pull request closed without merging**
