### PR TITLE
2024 Update for domain diher.solutions and rss.my.id

### PR DESCRIPTION
**Pull request by pereceh**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make 

- [x]  #test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
    - [Cloudflare](https://developers.cloudflare.com/learning-paths/get-started/add-domain-to-cf/add-site/)
    - [Letsencrypt](https://letsencrypt.org/docs/rate-limits/)
    - <UPDATE THIS LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY! REMOVE THIS LINE!>

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

I am a blog writer. and I'm also the sole manager for the listed domains.

Organization Website: https://rss.my.id

Reason for PSL Inclusion
====
My firewall software cannot detect wildcard characters.

DNS Verification via dig
=======
`dig +short TXT _psl.diher.solutions
"https://github.com/publicsuffix/list/pull/1393"`

`dig +short TXT _psl.rss.my.id
"https://github.com/publicsuffix/list/pull/1393"`

make test
=========
All test passed.

### CODE REVIEW

**Comment by pereceh** [comment]
> > Reason for PSL Inclusion
> > My firewall software cannot detect wildcard characters.
> 
> could you elaborate what exactly this means and what you want to achieve with the firewalls by including your domain in the PSL? It doesn't seem like a valid reason to add your domain to the PSL.

the filter on my firewall uses data from this [list](https://publicsuffix.org/list/public_suffix_list.dat) to validate a domain.

**Comment by pereceh** [comment]
> sorry for the confusion! I initially thought you were trying to add new domains to workaround firewall limitations, but I now realized you're simply trying to remove the `*.` from existing ones. In that case, your request makes sense.


Yes, waiting for updates.

**Comment by groundcat** [comment]
* [ ]  Expiration (Note: Must STAY >2y at all times)
  * [ ]  rss.my.id expires 2026-07-24
  * [x]  diher.solutions expires 2031-03-15
* [ ]  DNS _psl entries (Note: Must STAY in place)
  * [ ]  `_psl.rss.my.id`
  * [ ]  `_psl.diher.solutions`
* [x]  Tests pass
* [x]  Sorting
* [x]  Reasoning/Organization description
  * Updating existing entries
  * Submitter = original submitter
* [x]  Non-personal email address

---

- Please renew rss.my.id to extend it for more than 2 years from now.
- Please update `_psl.rss.my.id` and `_psl.diher.solutions` TXT records with the URL of this PR.

**Comment by pereceh** [comment]
> * [ ]   Expiration (Note: Must STAY >2y at all times)
>   
>   * [ ]   rss.my.id expires 2026-07-24
>   * [x]   diher.solutions expires 2031-03-15
> * [ ]   DNS _psl entries (Note: Must STAY in place)
>   
>   * [ ]   `_psl.rss.my.id`
>   * [ ]   `_psl.diher.solutions`
> * [x]   Tests pass
> * [x]   Sorting
> * [x]   Reasoning/Organization description
>   
>   * Updating existing entries
>   * Submitter = original submitter
> * [x]   Non-personal email address
> 
> * Please renew rss.my.id to extend it for more than 2 years from now.
> * Please update `_psl.rss.my.id` and `_psl.diher.solutions` TXT records with the URL of this PR.

I have renewed my domain **rss.my.id** until 2030 .

**Pull request merged**
