### PR TITLE
Add affinitylottery.org.uk raffleentry.org.uk and weeklylottery.org.uk to public suffix list

### PR DESCRIPTION
**Pull request by ChrisWhittleWV**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organisation
====
Organisation Website: https://www.woodsvalldata.co.uk/
WoodsValldata is a charity fundraising service provider.
I am a software developer at WoodsValldata catering for the hosted raffle and lottery websites that we provide.

Reason for PSL Inclusion
====
This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we seek to resolve the impacts to the best of our ability to do so.  Both Apple and Facebook support Public Suffix List for Private Click Measurement and Aggregated Event Measurement respectively.
We have reviewed the wiki here outlining the PSL and understand what it is and is not.
We have reviewed this matter with the team at Facebook, we are now fully aware about the consequences to the change we are requesting as it relates to cookies or other services, and choose to proceed in submitting this PR. We understand that despite reviewing the matter with Facebook, Facebook cannot control which use cases get accepted to the PSL We understand that there is not any urgency and should this PR be merged to include our requested change, that there is no control over the timing of this change being updated downstream in browsers, libraries, certificate authorities or other systems or processes that incorporate the PSL.
We understand that if we later want to back out this change, there is also no guarantee that this will occur in a rapid fashion due to the same lack of control over browser, library, certificate authority, or other system or process changes.

DNS Verification via dig
=======
```
>nslookup -type=txt _psl.affinitylottery.org.uk 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.affinitylottery.org.uk     text =

        "https://github.com/publicsuffix/list/pull/1398"
```

```
>nslookup -type=txt _psl.raffleentry.org.uk 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.raffleentry.org.uk text =

        "https://github.com/publicsuffix/list/pull/1398"    
```     
```        
>nslookup -type=txt _psl.weeklylottery.org.uk 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.weeklylottery.org.uk       text =

        "https://github.com/publicsuffix/list/pull/1398"
```
make test
=========
I have followed the test as outlined in https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change
and the output hasn't come back with any errors.

Please note, a previous pull request was made at https://github.com/publicsuffix/list/pull/1329

### CODE REVIEW

**Comment by bedfordsean** [comment]
Thanks Chris.

@dnsguru for context, Facebook have validated the use case here and believe it to be legitimate. These domains relate to lotteries/raffles run for charitable organisations in the UK to raise funds. The specific domains requested do not have more than a couple of hundred subdomains in total, which I know is not ideal for addition to the PSL. 

What are your thoughts on reasonable/legitimate use case for charitable purposes here vs PSL brevity?

**Comment by dnsguru** [comment]
> @dnsguru for context, Facebook have validated the use case here and believe it to be legitimate. These domains relate to lotteries/raffles run for charitable organisations in the UK to raise funds. The specific domains requested do not have more than a couple of hundred subdomains in total, which I know is not ideal for addition to the PSL.

@benfordsean One of the meta concerns (not just on the IOS/FB matter, but generally) is transparency for the browsers etc 'consumers' of the PSL to have the ability to review vetting of these in the light of day.

Obviously, this is case by case and somewhat "build as you fly" for all parties dealing with things because it is some new territory addressing the IOS/FB _stuff_, and the team there at FB have been very helpful at some of the triage here.  

A concern with this (and the other #1245 motivated PR) and sorting out how to move forward on them is that I am not sure if the 'FB vouches' covers things adequately enough to stand to up scrutiny by the various parties that voluntarily incorporate the PSL as to vetting.  

There may be more transparency required about the process internal to FB on what was reviewed and specifically what were the answers.

> What are your thoughts on reasonable/legitimate use case for charitable purposes here vs PSL brevity?
no opinion on this part - but there are some PR that have not cleared the hurdles to proceed where the quantity of affected parties vs entries on a globally accessed file been found to not meet a threshold - and that can sometimes be subjective.

In the case of this, I don't see where scale is a constraint.  Other PRs that have been declined for sake of file size modesty have been those for dozens or hundreds of people.  This seems like it might have larger audience meriting that part, but I am not looking closely.

I think the FB Vouches having a bit less opacity would be the gate here, not the charity angle (or gambling for that matter).

**Comment by dnsguru** [comment]
In reading the initial PR, there was some good kvetching and vetting and dialog.  This type of request is incedibly time consuming well above our typical scenarios here, it appears at the core of this was an attempt to isolate client subdomains.

Focusing on the connective tissue that would merit this proceeding, this was found:

(from #1329) 
>1) We want to segregate users cookies for security purposes, so that one subdomain cannot track cookies under another subdomain, as these cookies are intended for completely different clients. As we don’t host any websites at our top level domain, we are not interested in setting cookies for ourselves, simply to stop our clients from inadvertently sharing data, as they are all separate legal entities.

This merits a TEST to attempt and determine that those clients are able to appropriately have the desired isolations.

There is reticense here among the volunteers that allowing IOS/FB a workaround to proceed creates some precedent for others to flash mob the project again but more crucially that workarounds to limits will cause a lot of the voluntary use of the PSL by browsers to segment away from using the PSL, which will break more things and make remedy far harder for scenarios where vendors rugpull cookie behavior like this.

Will proceed, but let there be reference pointing to this PR as rationale for other requests being pressed forth.

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base
- Formatted / Sorted per Guidelines

**Approved**

**Comment by bedfordsean** [comment]
Thanks @dnsguru. I'm going to raise a PR against your wiki pages to clarify exactly what the FB vouching/vetting process consists of in the aim of full transparency. Stay tuned for that (which we can tweak as per your feedback)

**Pull request merged**
