### PR TITLE
Add `*.hosted.app`

### PR DESCRIPTION
**Pull request by svipul**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
Google Cloud Platform (GCP) is a collection of Google's cloud products. One of the platform's products provides web hosting services. That product serves content for developers at region-sharded subdomains of `hosted.app`. E.g. `my-website.us.hosted.app`. 

I am a software engineer at GCP.

Organization Website: https://cloud.google.com/

Reason for PSL Inclusion
====

Number of users this request is being made to serve: 4m estimated users

* We serve customers' web content at unique subdomains of `[region].hosted.app`.
* We want our customers' apps to be isolated from each other (cookies, etc.)
* We want to prevent setting cookies on the apex domains.

DNS Verification via dig
=======

```
dig +short TXT _psl.hosted.app
"https://github.com/publicsuffix/list/pull/1947"
```

```
dig +short TXT _psl.*.hosted.app
"https://github.com/publicsuffix/list/pull/1947"
```

Results of Syntax Checker (`make test`)
=========
All tests passed

```
============================================================================
Testsuite summary for libpsl 0.21.5
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by svipul** [comment]
Checking in on this, is further action required on our end?

**Comment by simon-friedberger** [comment]
* [x] Expiration (Note: Must STAY >2y at all times)
  * [x] hosted.app expires 2033-09-11
* [x] DNS _psl entries (Note: Must STAY in place)
* [x] Tests pass
* [x] Sorting
* [x] Reasoning/Organization description

**Comment by simon-friedberger** [comment]
@svipul Can the long list of old blogspot URLs be pruned?

**Comment by svipul** [comment]
> @svipul Can the long list of old blogspot URLs be pruned?

Unfortunately I'm not close enough to the relevant teams to say. I can ask around and have someone submit a follow-up PR if those are no longer necessary.

**Pull request merged**
