### PR TITLE
Add `wix.run`

### PR DESCRIPTION
**Pull request by OrLeib**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====
Organization Website: https://www.wix.com/

Wix is a website building platform.

Registered developers can create apps and get their own subdomain (e.g. `<appId>.wix.run`) on which their apps are hosted.
Organization Website: 

Reason for PSL Inclusion
====
We'd like to properly isolate each subdomain to prevent global cookie setting on wixsite.com/editorx.io and highlight that each subdomain hosts sites of a different user, unrelated to the others.

DNS Verification via dig
=======
```
dig +short TXT _psl.wix.run "https://github.com/publicsuffix/list/pull/1691"
```

Results of Syntax Checker (`make test`)
=========

`make test` passed:
```
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by OrLeib** [comment]
@sleevi @dnsguru Do I need to take any further action?

**Comment by dnsguru** [comment]
Volunteer here.  Queue ahead of you.  Will review, time permitting, but we
get distracted responding to nudges.

**Comment by dnsguru** [comment]
This updates #927 and may be impacted by #1799 to where #1799 would require a re-base.  Can @OrLeib @shahata coordinate on consolidating the #1799 into this request, adhering to the sorting guidelines?  We have some (hopefully) additional volunteer resources that can help us get through the backlog/queue where THIS pull request is waiting, and doing both at once is more efficient and would expedite #1799 being performed.

**Comment by shahata** [comment]
Cool. @OrLeib plz add wixstudio.io to this PR. Also plz add the required TXT record for wixstudio.io. I will close #1799.

**Comment by shahata** [comment]
@OrLeib I took care of required TXT records, plz just add `wixstudio.io` to this PR:
```
dig _psl.wix.run TXT +short
"https://github.com/publicsuffix/list/pull/1691"
dig _psl.wixstudio.io TXT +short
"https://github.com/publicsuffix/list/pull/1691"
```

**Comment by OrLeib** [comment]
@shahata Done

**Comment by shahata** [comment]
@dnsguru done

**Review by dnsguru — APPROVED** [review]
* DNS Validates
* Tests Pass
* No Conflict with Base
* Sorted to guidelines
* submitter != section op, but section op commenting and combined other PR = ok
APPROVED

(Note: this PR rolls up another previously submitted PR, preserving the earliest date for ordering of processing this Pull Request if other PR in queue get salty about the order of operation here on what PRs the unpaid volunteers advance when they get cycles to donate.)

**Comment by dnsguru** [comment]
@shahata @OrLeib MERGED

**Pull request merged**
