### PR TITLE
add impertrix.com and impertrixcdn.com

### PR DESCRIPTION
**Pull request by impertrixsolutions**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====
we are a platform as a service startup that provide global content delivery and web hosting services
Organization Website: https://cloud.impertrix.com

Reason for PSL Inclusion
====
for cookie security of domains that point to our domain and lets encrypt issuance for domains that points to our content delivery and webhosting domains

DNS Verification via dig
=======
dig +short TXT _psl.impertrix.com
"https://github.com/publicsuffix/list/pull/1060"
dig +short TXT _psl.impertrixcdn.com
"https://github.com/publicsuffix/list/pull/1060"

make test
=========

the tests were successful, https://pastebin.com/uYcSkxxh

### CODE REVIEW

**Comment by impertrixsolutions** [comment]
is this still being looked at?

**Comment by dnsguru** [comment]
> is this still being looked at?

**Yes**.

**Comment by impertrixsolutions** [comment]
should be fixed

**Comment by impertrixsolutions** [comment]
rebased, should be good

**Comment by groundcat** [comment]
@impertrixsolutions Do you still need this entry in the PSL? The domains `impertrix.com` and `impertrixcdn.com` had been expired and taken over by possibly a different registrant.

The `_psl` record no longer exists. (Reminder that you need to keep the _psl records)

If the domain has been deprecated, let to expire, and is no longer associated with an active project, it would be great if you could submit a PR to rollback and avoid leaving debris for PSL volunteers and future registrants to deal with.

```
$ whois impertrix.com
   Domain Name: IMPERTRIX.COM
   Registry Domain ID: 2714477470_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namecheap.com
   Registrar URL: http://www.namecheap.com
   Updated Date: 2024-06-20T01:02:01Z
   Creation Date: 2022-07-28T19:26:07Z                        <-- After PR was created
   Registry Expiry Date: 2024-07-28T19:26:07Z
```

```
$ whois impertrixcdn.com
   Domain Name: IMPERTRIXCDN.COM
   Registry Domain ID: 2867520874_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.spaceship.com
   Registrar URL: http://www.spaceship.com
   Updated Date: 2024-03-28T19:39:08Z
   Creation Date: 2024-03-28T17:16:20Z                        <-- After PR was created
   Registry Expiry Date: 2025-03-28T17:16:20Z
```

**Pull request merged**
