### PR TITLE
Add Ici la Lune hosting domain suffix 

### PR DESCRIPTION
**Pull request by morvans**

### CODE REVIEW

**Comment by ici-la-lune** [comment]
TXT record added :

`_psl.moonscale.net.     900     IN      TXT     "#370"
`

**Comment by morvans** [comment]
Description of the request: Our hosted customers gets a hostname like [container].[cluster].moonscale.net on for their hosted containers.

**Comment by morvans** [comment]
Dear Maintainers,
What should we do now to the issue to get this request handled ?
Thanks ! :)

**Comment by morvans** [comment]
The final pattern will eventually be [project-name].moonscale.net.
PR update to reflect that. Please let me know if something needs to be done as it is becoming a release blocker at our side (cookie sharing, let's encrypt, ...)

**Pull request merged**
