### PR TITLE
Add logoip.de and logoip.com domains

### PR DESCRIPTION
**Pull request by nmeilick**
SBE network solutions GmbH offers our customers (mostly schools) dynamic DNS services under the domains logoip.de and logoip.com (e.g., hostname.logoip.de).

For security reasons (cookie isolation) and to provide them with the ability to create Let's Encrypt certificates, we would like to add those domains to the public suffix list.

### CODE REVIEW

**Comment by nmeilick** [comment]
We added the DNS entries for validation:

```
$ host -t txt _ps1.logoip.de 
_ps1.logoip.de descriptive text "https://github.com/publicsuffix/list/pull/182"

$ host -t txt _ps1.logoip.com
_ps1.logoip.com descriptive text "https://github.com/publicsuffix/list/pull/182"


```

**Comment by weppos** [comment]
@nmeilick I was not able to validate the request as the record is not there.

```
➜  publicsuffix-list git:(master) dig TXT _psl.logoip.de

; <<>> DiG 9.8.3-P1 <<>> TXT _psl.logoip.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 61207
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;_psl.logoip.de.			IN	TXT

;; AUTHORITY SECTION:
logoip.de.		28	IN	SOA	dyns1.logodidact.de. hostmaster.sbe.de. 2016062611 300 60 604800 60

;; Query time: 42 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Sun Jun 26 11:20:20 2016
;; MSG SIZE  rcvd: 100
```

Can you please update the records?

**Comment by nmeilick** [comment]
@weppos I've added the correct entries now, I'm sorry for the mistake (I've read psl as ps1 and added those; time to get some glasses).

**Comment by weppos** [comment]
No problem!

**Comment by groundcat** [comment]
@nmeilick I've sent an email to your organization regarding a security concern with your PSL entries. During a recent review, I discovered that both logoip.de and logoip.com implement unrestricted wildcard IP-to-DNS mapping (e.g., 1.0.0.1.logoip.de resolves to 1.0.0.1 for any IP), which conflicts with our non-acceptance criteria and poses certificate security risks. Please review the email and respond either via email or by commenting on issue #2667 where this concern is being tracked. We'd appreciate your prompt attention to this matter.

**Pull request merged**
