### PR TITLE
Add wego domains

### PR DESCRIPTION
**Pull request by XavierEr**

### CODE REVIEW

**Comment by XavierEr** [comment]
Sharing credentials between subdomains.

Unable to authenticate user with password credentials on a sub domain.

> Failed to execute 'fetch' on 'Window': Credentials may only be submitted to endpoints on the same registrable domain.

**Comment by sleevi** [comment]
As per the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) please explain why you are making this request, and provide sample domains so we can help make sure the entries are correct.

**Comment by XavierEr** [comment]
Hey @sleevi , we are storing credential in www.wego.com and we want to share the stored credential with all our sub-domain, example: dz.wego.com, ar.wego.com, bh.wego.com etc... and vice versa.

**Comment by sleevi** [comment]
Uh, adding yourself to the public suffix list will **prevent** that.

Are you sure that's what you meant to describe? If so, I will need to close this pull request, because that's quite literally the opposite of what the PSL does :)

**Comment by XavierEr** [comment]
Hi @sleevi , Thanks for info. I will close this pull request.

**Pull request closed without merging**
