### PR TITLE
Update public_suffix_list.dat

### PR DESCRIPTION
**Pull request by michalkolar**
Hi,
add testurl.cz to public suffix list
Best Regards,
Kolar

### CODE REVIEW

**Comment by michalkolar** [comment]
Please add this domain to the PSL.

I have just added the TXT record for verification, it might take a couple of minutes to propagate:

`dig -t txt +short psl.testurl.cz
"https://github.com/publicsuffix/list/pull/173"`

**Comment by michalkolar** [comment]
testurl.cz

We provide webhosting and customer can use test link (testurl.cz), where customers can open preview of uploaded page to our servers. 

Reason

Cookie isolation and unlimited rate limit (creating cert) of SSL certificates with Let's Encrypt.

**Comment by weppos** [comment]
Please update the patch according to our Guidelines.
https://github.com/publicsuffix/list/wiki/Guidelines

Specifically, the domain should be in the correct Private section of the list.

**Comment by sleevi** [comment]
Closing due to no response.

**Pull request closed without merging**
