### PR TITLE
Updated .bn ccTLD. Removed wildcard.

### PR DESCRIPTION
**Pull request by thefitri**
BNNIC has recently allowed .bn registration. Updating the list to remove wildcard (*.bn)

### CODE REVIEW

**Comment by sleevi** [comment]
Please provide a link to such policies.

**Comment by thefitri** [comment]
I can't find a link to a policy or versioned document. They have this downloadable guideline (http://bnnic.bn/files/Guidelines%20Application%20for%20Second%20Level%20Domain%20Names%20(SLD).pdf). But I'm not sure how that is more concrete than their FAQ especially since that document can be moved/changed/deleted. Meanwhile, I've removed the reseller link. Kindly advice on how to proceed.

**Comment by weppos** [comment]
Merged, thanks.

**Comment by thefitri** [comment]
Thanks. Looking forward to the generated rules.go on /weppos/publicsuffix-go/publicsuffix and subsequently /letsencrypt/boulder so I can get my Let's Encrypt certificate. (ICANN TLD error right now)

**Pull request merged**
