### PR TITLE
Adding asuscomm.com domain to the public list

### PR DESCRIPTION
**Pull request by adecagny**
Adding this extension as it is used by Asus routers for DynDNS.

### CODE REVIEW

**Comment by drovetto** [comment]
Only the domain owner can request the inclusion of the domain to the list. I've asked the technical support to include it but I only got a generic feedback. I think the owners of ASUS routers that want the domain to be included in this list should open a tech support inquiry.

Here is the link I've used:
[https://vip.asus.com/VIP2/Services/QuestionForm/TechQuery?lang=en-us](https://vip.asus.com/VIP2/Services/QuestionForm/TechQuery?lang=en-us)

**Comment by adecagny** [comment]
I managed to get in touch with someone from support which escalated the issue to the team managing the DDNS. I will let you know if i get any update.

**Comment by drovetto** [comment]
Thank you for letting me know! Let's just hope they'll do something about it.

**Comment by weppos** [comment]
At the time being, we only accept private domains to be submitted/approved by the owners. I'm closing this PR for now. Please ask a representative of Asuscomm to submit a request if they want the domain to be listed.

**Pull request closed without merging**
