### PR TITLE
Add daplie.me

### PR DESCRIPTION
**Pull request by coolaj86**
Daplie, Inc provides Domains, Dynamic DNS, and a home Cloud server. Subdomains of daplie.me are available to DIY users, hobbyists, and developers.

### CODE REVIEW

**Comment by coolaj86** [comment]
dig TXT +short _psl.daplie.me
"https://github.com/publicsuffix/list/pull/200"

**Comment by coolaj86** [comment]
@weppos here's the updated request

**Comment by coolaj86** [comment]
Was there anything else I needed to do? Or is this ready to move forward?

**Comment by weppos** [comment]
Merged.

**Pull request merged**
