### PR TITLE
Add .tv.ni

### PR DESCRIPTION
**Pull request by lala1997**
Cloudflare It is a free system that acts as a proxy (intermediary) between site visitors and the server. When I wanted to add my website educa6.tv.ni, there was an error, which I contacted support and they gave me the following answer:

Hello,

Thanks for contacting Cloudflare support. My name is Venkat and I will be looking into this ticket for you. We're sorry to read that you're experiencing difficulties.

I understand that you are seeing the following error: Please ensure you are providing the root domain and not any subdomains.

As per the following article: I cannot add my domain to Cloudflare

If you see this error, you need to make sure that the domain uses a verified TLD
You will find the verified TLD list here: https://publicsuffix.org/list/public_suffix_list.dat

As per above list, I do not see .tv.ni as a verified TLD. However, it does have .ni as a verified TLD. I believe this is why you are seeing the error.

I would suggest submitting an amendment to have .tv.ni added to the list of verified TLDs. Please refer: https://publicsuffix.org/submit/

Once this has been verified, you will be able to add the domain to Cloudflare.

Thank you for using Cloudflare. For now, I will mark this ticket as solved but please let us know if you have any further questions by replying back to this message.

Kind regards,

Venkat Chintha
Technical Support Engineer

Search the Cloudflare Community for advice and insight.

For this reason, I am making this request.

### CODE REVIEW

**Comment by dnsguru** [comment]
Kattya -

If you are able to add a dns txt record with the url of your pull request
to the _psl.tv.ni please.

We use this to validate submissions are done with the zone operator.

Thank you.

**Comment by lala1997** [comment]
$ dig TXT _psl.tv.ni
"https://github.com/publicsuffix/list/pull/1413"

**Comment by lala1997** [comment]
$ dig TXT _psl.tv.ni
https://github.com/publicsuffix/list/pull/100

**Comment by dnsguru** [comment]
needs to be #1413 on the DNS txt record @lala1997

**Comment by dnsguru** [comment]
Also, the tv.ni should be placed on its own in the PRIVATE section unless you can prove you work with the .ni TLD, as their listings do not indicate that .tv.ni is 'official' part of the .ni namespace vs being PRIVATE space.

**Review by dnsguru — CHANGES_REQUESTED** [review]
This may not be placed among the main .ni entries unless you can place a _PSL txt record in .ni directly.

Unless you are able to indicate in this manner that you are connected with the official NIC.NI, the change must be moved out of the ICANN section for .ni and down into the PUBLIC section of the PSL on its own.  Please follow the guidelines for sort ordering on this.

**Comment by dnsguru** [comment]
Reached out to nic.ni for comment - IF this is to be under their entry in the ICANN section, they'll need to have validated / verified this.

If that zone is privately operated and not affiliated with nic.ni then place move the tv.ni entry into the private section as noted in the review.

**Comment by lala1997** [comment]
You are right they manage the .ni, I should have contacted them, since they manage the .ni domains, I will send you an email.

**Comment by dnsguru** [comment]
> You are right they manage the .ni, I should have contacted them, since they manage the .ni domains, I will send you an email.

Or, instead of requesting this be alongside the entries of .ni that are managed by the nic.ni, place it instead lower in the file inthe private section.

**Comment by lala1997** [comment]
Ok, I will add it to the archive in the private section.

**Comment by dnsguru** [comment]
As you move the entry, please ensure that it is only listed once.  It is in twice right now, which is invalid.

**Comment by lala1997** [comment]
Sorry, it's ready now

**Comment by dnsguru** [comment]
This now seems like it is just being requested to get around cloudflare's rate limits

**Comment by lala1997** [comment]
Do I have to apply to Cloudflare?

**Comment by dnsguru** [comment]
This seems related to getting a domain to work inside of Cloudflare - if they need to make a domain work, and are referring you here, this is unforunate but we are a volunteer-based project that maintains a modest catalog of domains. 
 The objective of PSL is in addressing a need to have hundreds or thousands of subdomains experience distinct cookie security - and we are constantly rejecting small projects that affect <100 subdomains. 
 
 This seems like a request to add for a single domain to work around the fact that Cloudflare won't add the name for you.
 
 Do you operate and admin tv.ni?  If so, add it and place an entry in that zone.  We're a volunteer-run project and cloudflare tech support should be addressing this vs sending you to us.

**Comment by dnsguru** [comment]
This has not received any updates since November 9. 2022, so this PR is closing, as the requested changes were not made and there has been no response or updates to the comments.

If this was done in error, please feel free to re-open the PR.  If there is a new PR opened instead, please reference this one so that the historical dialog is preserved and connected.  

Thank you

**Pull request closed without merging**
