### PR TITLE
AWS Submissions to the Public Suffix List - Q4 2023

### PR DESCRIPTION
**Pull request by erichays**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter. This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [X] Description of Organization
* [X] Robust Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

 * [X] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example) 
 _AWS does not submit suffixes to the Public Suffix List to work around rate-limits of any third-party products or tooling._

 * [X] This request was _not_ submitted with the objective of working around other third-party limits
 _Please see the Reasonsection below for objectives in this pull request._

 * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
 * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [X] *Yes, I understand*. I could break my organization's website cookies etc. and the rollback timing, etc is acceptable. *Proceed*.

---

Description of Organization
====

Amazon Web Services (AWS) is the world’s most comprehensive and broadly adopted cloud, offering over 200 fully featured services from data centers globally. 
More information about AWS is available on our website:
[What is AWS?](https://aws.amazon.com/what-is-aws/)

**Organization Website:** 
[AWS Homepage](https://aws.amazon.com)

Reason for PSL Inclusion
====

These features/services have been identified by AWS Security and AWS service
teams as supporting different distinct customers/resources across shared
DNS suffixes. Adding these suffixes to the PSL is expected to improve the
security posture of customers using our services. This may include:

- impact to the Same-Origin Policy in modern browsers (cookies + others)
- representation of these domains to the CA/Browser Forum
- any other use-cases of the PSL which may benefit from updated information about multi-tenant AWS services

**Number of users this request is being made to serve:**

These changes are expected to impact all customers using these AWS services.
This includes both AWS-internal and external customers. Specific user counts
for these listed features/services are not publicly available.

Services/Features in PR:
====

Amazon API Gateway
Amazon S3
Amazon SageMaker Notebook Instances
AWS Cloud9
AWS re:Post Private

DNS Verification via dig
=======

<details>
<summary>DNS query results</summary>

```
execute-api.ca-west-1.amazonaws.com: dig +short -t TXT _psl.execute-api.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



webview-assets.aws-cloud9.il-central-1.amazonaws.com: dig +short -t TXT _psl.webview-assets.aws-cloud9.il-central-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



vfs.cloud9.il-central-1.amazonaws.com: dig +short -t TXT _psl.vfs.cloud9.il-central-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



*.private.repost.aws: dig +short -t TXT _psl.private.repost.aws)
"https://github.com/publicsuffix/list/pull/1876"



s3.dualstack.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3.dualstack.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3-accesspoint.dualstack.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3-accesspoint.dualstack.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3-accesspoint-fips.dualstack.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3-accesspoint-fips.dualstack.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3-fips.dualstack.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3-fips.dualstack.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3-website.dualstack.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3-website.dualstack.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3-accesspoint.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3-accesspoint.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3-accesspoint-fips.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3-accesspoint-fips.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3-fips.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3-fips.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



s3-website.ca-west-1.amazonaws.com: dig +short -t TXT _psl.s3-website.ca-west-1.amazonaws.com)
"https://github.com/publicsuffix/list/pull/1876"



notebook-fips.ca-central-1.sagemaker.aws: dig +short -t TXT _psl.notebook-fips.ca-central-1.sagemaker.aws)
"https://github.com/publicsuffix/list/pull/1876"



notebook.ca-west-1.sagemaker.aws: dig +short -t TXT _psl.notebook.ca-west-1.sagemaker.aws)
"https://github.com/publicsuffix/list/pull/1876"



notebook-fips.ca-west-1.sagemaker.aws: dig +short -t TXT _psl.notebook-fips.ca-west-1.sagemaker.aws)
"https://github.com/publicsuffix/list/pull/1876"
```

</details>

Results of Syntax Checker (`make test`)
=========

<details>
<summary>Test results</summary>

```
cd linter;                                \
	  ./pslint_selftest.sh;                     \
	  ./pslint.py ../public_suffix_list.dat;
-n test_NFKC:
OK
-n test_allowedchars:
OK
-n test_dots:
OK
-n test_duplicate:
OK
-n test_exception:
OK
-n test_punycode:
OK
-n test_section1:
OK
-n test_section2:
OK
-n test_section3:
OK
-n test_section4:
OK
-n test_spaces:
OK
-n test_wildcard:
OK
test -d libpsl || git clone --depth=1 https://github.com/rockdaboot/libpsl;   \
	  cd libpsl;                                                                    \
	  git pull;                                                                     \
	  echo "EXTRA_DIST =" >  gtk-doc.make;                                          \
	  echo "CLEANFILES =" >> gtk-doc.make;                                          \
	  autoreconf --install --force --symlink;
Updating 26daf61..141d54a
Fast-forward
 docs/libpsl/meson.build         | 14 +++++++++++++-
 src/Makefile.am                 |  2 ++
 src/psl.c                       |  2 ++
 tests/test-is-public-all.c      |  2 ++
 tests/test-is-public-builtin.c  |  2 ++
 tests/test-is-public.c          |  2 ++
 tests/test-registrable-domain.c |  2 ++
 7 files changed, 25 insertions(+), 1 deletion(-)
autopoint: using AM_GNU_GETTEXT_REQUIRE_VERSION instead of AM_GNU_GETTEXT_VERSION
Copying file m4/gettext.m4
Copying file m4/host-cpu-c-abi.m4
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: linking file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: linking file 'm4/libtool.m4'
glibtoolize: linking file 'm4/ltoptions.m4'
glibtoolize: linking file 'm4/ltsugar.m4'
glibtoolize: linking file 'm4/ltversion.m4'
glibtoolize: linking file 'm4/lt~obsolete.m4'
cd libpsl && ./configure -q -C --enable-runtime=libicu --enable-builtin=libicu --with-psl-file=/Users/username/Documents/github_repos/psl-git/public_suffix_list.dat --with-psl-testfile=/Users/username/Documents/github_repos/psl-git/tests/tests.txt && make -s clean && make -s check -j4
config.status: creating po/POTFILES
config.status: creating po/Makefile
Making clean in po
Making clean in include
Making clean in src
rm -f ./so_locations
Making clean in tools
 rm -f psl
Making clean in fuzz
 rm -f libpsl_icu_fuzzer libpsl_icu_load_fuzzer libpsl_icu_load_dafsa_fuzzer
Making clean in tests
 rm -f test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain
Making clean in msvc
Making check in po
Making check in include
Making check in src
  CC       libpsl_la-psl.lo
  CC       libpsl_la-lookup_string_in_fixed_set.lo
  CCLD     libpsl.la
Making check in tools
  CC       psl.o
  CCLD     psl
Making check in fuzz
  CC       libpsl_fuzzer.o
  CC       main.o
  CC       libpsl_load_fuzzer.o
  CC       libpsl_load_dafsa_fuzzer.o
  CCLD     libpsl_icu_fuzzer
  CCLD     libpsl_icu_load_fuzzer
  CCLD     libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_load_dafsa_fuzzer
PASS: libpsl_icu_fuzzer
PASS: libpsl_icu_load_fuzzer
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-public-builtin.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-registrable-domain.o
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
PASS: test-is-public
PASS: test-is-public-all
PASS: test-is-public-builtin
PASS: test-is-cookie-domain-acceptable
PASS: test-registrable-domain
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in msvc
```

</details>

### CODE REVIEW

**Comment by aph3rson** [comment]
@dnsguru: making sure you're aware - we've marked this submission as "ready for review" a couple of weeks prior.  
We haven't seen any motion on our submission yet, though, and the `DRAFT` label is still present.  


Our internal processes currently dictate that we move the draft pull request to a submitted pull request ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review), [prior example](https://github.com/publicsuffix/list/pull/1784#event-10702119988)).  
Is moving the PR from a draft -> ready status still sufficient? This may be duplicative to the `DRAFT` label in use by the maintainers.

**Comment by dnsguru** [comment]
@simon-friedberger  can you review the presence of DNS _PSL TXT on the entries please

**Comment by simon-friedberger** [comment]
It seems `amazonaws.com` expires in less than two years.

**Comment by aph3rson** [comment]
@simon-friedberger: thanks for the review. I've reached out to our domain management contacts for their assistance. Context on those two domains:

- `amazonaws.com` - this zone is for our Commercial [partition](https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/partitions.html), the portion of AWS used by the majority of AWS customers. Past submissions have included suffixes in this zone, and we have internal domain management processes to ensure the registration will not lapse. Management of this domain's registration is handled by MarkMonitor.
- `sagemaker.aws` - this zone is for our [Amazon SageMaker](https://aws.amazon.com/sagemaker/) product. Additionally, the zone is within the `.aws` brand TLD, which we also operate. Likewise, past submissions have included suffixes in this zone, and we have internal domain management processes to ensure the domain registration (or the TLD) will not lapse. Management of the TLD is handled by Com Laude.

We'll share more information here as soon as it's available.

**Comment by dnsguru** [comment]
@simon-friedberger @aph3rson - Typically this 2 year requirement is more enforced upon new entries vs existing ones, as a means of having reasonable friction in place to keep 'spaghetti at wall' requests from adding things that have non-permanent trajectory and experimental stuff that folks let the domain name lapse on when their attention pivots or their operating capital gets burned through.

Because amazonaws.com was already present, and it has been for some time - with mutually assured consequences of non-renewal, there is merit to apply a relaxing of this frictional requirement.

Additionally, in this exceptional case, the AWS top level domain name is operated by the requestor, so their ability to perpetually renew the domain name allows again for some discretion towards relaxing the frictional requirement of 2years of registration term on the domain name.

**Comment by dnsguru** [comment]
All things considered, the balance of the PR looks ok and I see no reason to not merge this.

**Review by dnsguru — APPROVED** [review]
* Tests Pass
* No Conflict with Base
* DNS proofs validated to Pull Request URL
* Sorting conforms to guidelines

APPROVED

**Review by dnsguru — APPROVED** [review]
* Sorted to Guidelines
* DNS TXT = Pull Request URL
* Tests Pass
* No conflict with base

APPROVED

**Comment by dnsguru** [comment]
@erichays @aph3rson woot

**Comment by aph3rson** [comment]
@dnsguru - thanks for the merge.

In the interest of completing the outstanding callouts on thread, the domain registration renewal periods for the domains mentioned by @simon-friedberger are now in-line with the requirements for the PSL.

```
$ whois amazonaws.com | grep Expiry
   Registry Expiry Date: 2027-01-16T04:59:59Z
$ whois sagemaker.aws | grep Expiry
Registry Expiry Date: 2027-11-15T23:31:12Z
```

**Pull request merged**
