### PR TITLE
Add `ie.ua`

### PR DESCRIPTION
**Pull request by HostFly**
* [x]  Description of Organization (It doesn't matter)
* [x]  Reason for PSL Inclusion
* [x]  DNS verification via dig (High priority)
* [x]  Run Syntax Checker
* [x]  Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place
  
  * [x]  We are listing _any_ third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x]  This request was _not_ submitted with the objective of working around other third-party limits
  * [x]  The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x]  The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

**For Private section requests that are submitting entries for domains that match their organization website's primary domain:**

```
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```

(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

* [x]  _Yes, I understand_.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  _Proceed_.

# Description of Organization (It doesn't matter)
ie.ua - Expiry Date: 2032 year,
official e-mail support@hostfly.com.ua always works.
I have an ID in IANA https://www.iana.org/assignments/epp-repository-ids/epp-repository-ids.xhtml
Website: https://www.ie.ua (under construction)
We offer various Internet services for our customers. We create new zone  " .ie.ua ", so we would like these zone to be on the public suffix list as well as others zones " .(*).ua ".

# Reason for PSL Inclusion
Users can register domains in the domain ie.ua. 
which means subdomains (*.ie.ua) are registered by independent 3rd parties.
We want user subdomains to be isolated from each other (cookies, suffix allocation, etc.). The domain is registered until 2032 year.

# DNS Verification via dig (High priority)
```
_psl.ie.ua IN TXT "https://github.com/publicsuffix/list/pull/1597"
```

# test
All tests pass

### CODE REVIEW

**Comment by HostFly** [comment]
Please, add  zone

**Comment by HostFly** [comment]
Why are you ignoring the request?

**Comment by dnsguru** [comment]
Unpaid volunteers here working through a queue of requests.

**Comment by dnsguru** [comment]
Polite Request:  There is a queue being worked on - Please stop emailing personal inbox of volunteers with accusations of bias.

**Comment by dnsguru** [comment]
In reviewing this PR it appears, based upon the following discussion at CloudFlare, that the request is made to overcome account limits of Cloudflare.
https://community.cloudflare.com/t/add-new-zone-in-cloudflare/413202 - This is in direct violation of the PSL guidelines. 

This is a non-discriminatory rule, designed to keep companies from inappropriately using the PSL volunteers as their edge labor on verification or frictional conversations about rejection.

Rather than close this PR as a wontfix, we wanted to provide the opportunity to explain how this pull request is not attempting to overcome the rate limits of Cloudflares domain rules that might be potentially solved with their enterprise products?

**Comment by HostFly** [comment]
dnsguru, let CloudFlare provide evidence of corporate service abuse, otherwise don't accuse us of a crime we didn't do.
We monitor the movement of commits publicsuffix and we see how we are ignored.

We have followed the rules:
Domain registration for 10 years.
Adding TXT entry _psl.
Correct addition to PRIVATE section.
Can you tell us if we should wait for the process to move forward? Or will it never happen?
Thanks.

**Comment by dnsguru** [comment]
@HostFly there is a large backup with the issue that Apple/Meta caused in the IOS change that has a number of queue items ahead and other stuff processing that are older, with people who have had far more patience extracted from them over their wait times.    You are welcome to politely wait (and perhaps reduce lost volunteer cycles to respond to these nudges) or withdraw -  nobody is saying never.

**Comment by HostFly** [comment]
@dnsguru When you are silent, we do not understand what is happening. Now we understand that we have to wait. Thanks

**Comment by dnsguru** [comment]
@HostFly Thank you for your patience.  

There is a prioritization / sorting that is done based upon the time invested per request (including responding, nudges, direct email harassment of volunteers, etc) and the review of entries + sometimes sorting defaults differently per seating in what PR are listed.

Because of the inferred security that some of the integrations of third parties have chosen in their incorporation/use of the PSL, subdomain operations in certain namespaces take more processing, with pressures on volunteers to do further reviews to not empower rate limit workarounds or other security bypasses for cookies, certificates or other wise.

As previously mentioned, Apple/Meta interaction put us on our back heels a bit with additional burdens on the anemic resourcing the PSL has.  We anticipate that Google's announcement that they are abandoning support for subdomains that are not PSL listed on March 20, 2023 will perhaps create a new flash mob.

Before that happens, and given the amount of time and persistence, I will merge this.

I leave this link [SPAMHAUS Shows this as Clean](https://check.spamhaus.org/not_listed/?searchterm=ie.ua) here as a means to demonstrate that there WAS some review of this from a security perspective, that the spamhaus RBL showed no issues with this namespace, and point to Issue #1699 to proactively defend this action.  

This proof of 'clear' use, along with the patience of the requestor, should hopefully stand as record as to the rationale of proceeding with the merging of this record.

**Comment by dnsguru** [comment]
@HostFly is this a namespace operated by Centralnic or your own company?  It is ok where it is IF it is run by Centralnic, but if this is specifically for Hostfly, would you please move this patch to be just above / Hostyhosting  ?

**Review by dnsguru — CHANGES_REQUESTED** [review]
Am about to merge this but want to confirm that sorting is according to the submission guidelines.

Will watch for your response and promptly process a merge once you either

* Confirm it the Hostfly entry is appropriately listed as a sub-namespace client of Centralnic; or
* Move the entry by revising you doing a rebase and move the section so it is correctly sorted according to the guidelines by the commented org in your Pull Request

**Comment by HostFly** [comment]
Is everything correct?

**Review by dnsguru — APPROVED** [review]
* DNS VALIDATES
* TESTS PASS
* GUIDELINE CONFORMANT
* NO CONFLICT WITH BASE

APPROVED

**Comment by HostFly** [comment]
dnsguru, thanks!

**Pull request merged**
