### PR TITLE
Move Travis tests into a reusable shell script

### PR DESCRIPTION
**Pull request by rockdaboot**
@weppos You can locally perfrom the Travis tests by executing .travis.sh manually.

### CODE REVIEW

**Comment by weppos** [comment]
Thanks @rockdaboot. I was trying to make the test run today on my machine. I was creating a Makefile for test (as it will allow me to run specific task independently).

I'm currently experiencing an issue running the tests:

```
➜  libpsl git:(master) ./configure -q -C --enable-runtime=libicu --enable-builtin=libicu --with-psl-file=/Users/weppos/Code/publicsuffix-list/public_suffix_list.dat --with-psl-testfile=/Users/weppos/Code/publicsuffix-list/tests/tests.txt && make -s clean && make -s check -j4
config.status: creating po/POTFILES
config.status: creating po/Makefile
Making clean in po
Making clean in include
Making clean in src
rm -f ./so_locations
 rm -f psl2c
Making clean in tools
 rm -f psl
Making clean in tests
 rm -f test-is-public test-is-public-all test-is-cookie-domain-acceptable test-is-public-builtin test-registrable-domain
Making check in po
Making check in include
Making check in src
  CC       psl2c-psl2c.o
  CC       psl2c-lookup_string_in_fixed_set.o
  CCLD     psl2c
sh: sha1sum: command not found
  CC       libpsl_la-psl.lo
  CC       libpsl_la-lookup_string_in_fixed_set.lo
  CCLD     libpsl.la
Making check in tools
  CC       psl.o
  CCLD     psl
Making check in tests
  CC       test-is-public.o
  CC       test-is-public-all.o
  CC       test-is-cookie-domain-acceptable.o
  CC       test-is-public-builtin.o
  CC       test-registrable-domain.o
  CCLD     test-is-public
  CCLD     test-is-cookie-domain-acceptable
  CCLD     test-is-public-builtin
  CCLD     test-is-public-all
  CCLD     test-registrable-domain
FAIL: test-is-public-builtin
PASS: test-is-public
PASS: test-is-cookie-domain-acceptable
PASS: test-is-public-all
PASS: test-registrable-domain
============================================================================
Testsuite summary for libpsl 0.13.0
============================================================================
# TOTAL: 5
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to tim.ruehsen@gmx.de
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

**Comment by rockdaboot** [comment]
Not here and not on Travis either...
If you see a test failing, first have a look into tests/name-of-the-test.log. In this case tests/test-is-public-builtin.log. If you still have no idea what could be wrong, the next step is posting the log file here and/or send it to me.
You could also remove the -q from the ./configure call and restart - so you can see if all libraries are found. Also check the output of libpsl/tools/psl --print-info.

**Comment by weppos** [comment]
```
➜  tests git:(master) ✗ cat test-is-public-builtin.log
have 6322 suffixes and 9 exceptions
psl_builtin_file_time()=1457183507
psl_builtin_sha1sum()=
Summary: 1 out of 32 tests failed
FAIL test-is-public-builtin (exit status: 1)
```

I'm running the tests against master, with no extra modifications. It's worth to mention Travis run on Ubuntu, whereas I'm trying to run the tests on my Mac.

```
➜  tools git:(master) ✗ ./psl --print-info
builtin suffixes: 6322
builtin exceptions: 9
builtin wildcards: 31
builtin filename: /Users/weppos/Code/publicsuffix-list/public_suffix_list.dat
builtin file time: 1457183507 (Sat, 05 Mar 2016 14:11:47 CET)
builtin SHA1 file hash:
builtin outdated: 0
```

**Comment by rockdaboot** [comment]
Looking more closer at the output, I see: sh: sha1sum: command not found
That's the problem, I guess. You have no checksum, the output should look like
have 6322 suffixes and 9 exceptions
psl_builtin_file_time()=1457171893
psl_builtin_sha1sum()=f8059a9cad729b75c90d5bf04445f80fbbf0243f
Summary: All 32 tests passed
PASS test-is-public-builtin (exit status: 0)

**Comment by rockdaboot** [comment]
Just out of interest, how do you manage to have no sha1sum ? I thought this is one of the basic commands (e.g. in Debian: coreutils: /usr/bin/sha1sum).

**Comment by weppos** [comment]
> Just out of interest, how do you manage to have no sha1sum?

As I mentioned, I'm completely out the C world. All the time I had to deal with hashes I used either built-in language functions or specific libraries, but never used operating-system specific commands.

I've never had any problem so far generating SHA1 or SHA256 hashes.

**Comment by weppos** [comment]
FYI, these bins are not available by default in Mac.
https://raam.org/2008/howto-install-md5sum-sha1sum-on-mac-os-x/

**Comment by weppos** [comment]
To be honest, I had to install several dependencies in order to try to run the test suite on my Mac, it's definitely not very easy to run it on a Mac.

**Comment by weppos** [comment]
That was it! I installed `md5sha1sum` and all the tests are green now. Thanks @rockdaboot

**Comment by rockdaboot** [comment]
Yes, libpsl has a few dependencies (listed in .travis.yml). And Mac is not what I call 'developers choice' :-). I guess you would have much more problems using plain Windows (no real shell, no real compiler, ...). But as a Windows user, you would know about CygWin.

**Comment by weppos** [comment]
I haven't been using any Windows machine in the last 10 years. Mac served me well for a very long time. :) I use Ubuntu as well, but it's not my primary development environment as Mac offers several more advantages (at least to my specific needs).

BTW, OS discussions apart, I was able to prepare a Makefile elaborating the content of this PR that was actually quite useful. I think I'll consider using the Makefile, as it doesn't require extra settings in Travis (Travis runs `make test` by default if a `Makefile` is found) and because it allows me to run separate tasks (e.g. I can run just the linter, or the libpsl tests).

I pushed a branch with the `Makefile`. It's probably not perfect, but it does the job. :) I'll check if it works on Travis.

**Comment by rockdaboot** [comment]
Sounds good ! I didn't know about the automatic 'make test' feature on Travis.

**Comment by weppos** [comment]
Closing in favor of #171. Thanks @rockdaboot, this change helped me to create the Makefile and make the tests running locally on my env.

**Pull request closed without merging**
