### PR TITLE
Add shopware.store domain

### PR DESCRIPTION
**Pull request by jenskueper**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://shopware.store
I am an engineer at shopware working on our SaaS hosting for e-commerce shops which are based on Shopware 6 (https://github.com/shopware/platform).

Reason for PSL Inclusion
====

Cookie security between subdomains since the subdomains will be managed and run by different organizations with the ability to set cookies.

DNS Verification via dig
=======

```
dig +short TXT _psl.shopware.store
"https://github.com/publicsuffix/list/pull/958"
```

make test
=========

All passed

### CODE REVIEW

**Comment by sleevi** [comment]
Could you indicate why you're requesting `shopwaredemo.store`?

That is, per the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), can you:
> * When submitting private domains, add a brief description of why you want the suffix(es) to be added to the list
> * When submitting private domains, provide expected input/output to help us validate the correctness of the request
> ...
> * Provide extra information useful for the PSL team to handle the pull request

**Comment by jenskueper** [comment]
Hello sleevi,

thank you for the fast response! We currently have two domains:

- shopwaredemo.store: Anybody can request a demo for our e-commerce shop system (Shopware 6). They get their own subdomain and access to a their shop which they can modify to try out our service but they can't generate revenue with it
- shopware.store is for real production shops. They will also receive a subdomain and full access to their shop

If we can only add one domain to the list, I would remove shopwaredemo.store since the risk/chance of cookie manipulation is lower compared to shopware.store where production shop with real transactions are  hosted.

Best regards
Jens

**Comment by jenskueper** [comment]
Hello @sleevi,

I just wanted to ask if the answer above is sufficient or if I can assist in any way to move this issue forward.

Best regards
Jens

**Comment by jenskueper** [comment]
>

**Comment by jenskueper** [comment]
Hello @sleevi,

I removed shopwaredemo.store so only our main/production domain is now included.

Best regards
Jens

**Comment by dnsguru** [comment]
@jenskueper Thank you for reducing the request to a single domain and providing additional rationale

- Rationale ok
- tests pass
- DNS Validation Verified
```
>nslookup -type=txt _psl.shopware.store
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
_psl.shopware.store     text =        "https://github.com/publicsuffix/list/pull/958"
```

**Comment by dnsguru** [comment]
@sleevi please confirm the rationale was addressed - I have reviewed it and the DNS validation all looks accurate.  Merge if ok or add q's

**Comment by jenskueper** [comment]
Thank you @dnsguru for the positive response. If I see it correctly @sleevi has approved afterward. It would be awesome if the PR could be merged in the near future.

**Pull request merged**
