### PR TITLE
Add perspecta.cloud

### PR DESCRIPTION
**Pull request by kvanals**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====
Perspecta is a corporation in Northern Virginia, USA that has recently acquired KnightPoint Systems, LLC.  As such, Perspecta has taken ownership of the KnightPoint Systems cloud enclave.

Organization Website: https://perspecta.com/

Reason for PSL Inclusion
====
Perspecta recently acquired KnightPoint Systems (which utilized knightpoint.systems already on the PSL).  As such, we are migrating from knightpoint.systems to perspecta.cloud.  Our primary reason for PSL inclusion for both the prior and new domain is "cookie security".

DNS Verification via dig
=======
`lancelot:~ kvanals$ dig +short TXT _psl.perspecta.cloud`
`"https://github.com/publicsuffix/list/pull/898"`

make test
=========
See:  https://pastebin.com/krfngLeA

### CODE REVIEW

**Comment by kvanals** [comment]
I'm not sure how to move this along, but is there anything else needed to merge this change in?

**Comment by sleevi** [comment]
Should the Knightpoint entries be updated to Perspecta due to the acqusition?

**Comment by kvanals** [comment]
> Should the Knightpoint entries be updated to Perspecta due to the acqusition?

Probably?  I'll discuss internally and submit another PR.  We're planning on migrating away from knightpoint.systems eventually.

**Comment by groundcat** [comment]
Hello @kvanals , it seems that the project or organization associated with your domain, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. 

perspecta.cloud
- only 1 subdomain found
- email `rkeene@knightpoint.com` not reachable
- organization website `https://perspecta.com/` not working

If the service has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.

**Comment by kvanals** [comment]
> Hello @kvanals , it seems that the project or organization associated with your domain, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains.
> 
> perspecta.cloud
> 
>     * only 1 subdomain found
> 
>     * email `rkeene@knightpoint.com` not reachable
> 
>     * organization website `https://perspecta.com/` not working
> 
> 
> If the service has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).
> 
> The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.
> 
> If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**.
> 
> Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.
> 
> Thank you.

@groundcat KnightPoint and Perspecta are both now owned by Peraton.  I don't believe EITHER merit inclusion in the PSL at this point, however I should note I am no longer employed by Peraton so I can't speak on behalf of them.

**Pull request merged**
