### PR TITLE
Add gov.hu special name

### PR DESCRIPTION
**Pull request by herczegzsolt**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [X] Description of Organization
* [X] Robust Reason for PSL Inclusion
* [ ] DNS verification via dig
* [X] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 
  * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third-party limits
  * [X] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [X] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [ ] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

The gov.hu domain is maintained by NISZ Zrt on behalf of the Hungarian Government. It is tld available for registration by government entities, and is currently used by most government agencies and services.

I'm not affiliated with NISZ Zrt or the government. I'm a non-affiliated Hungarian citizen who is concerned by the typical behavior of browsers treating the gov.hu tld.

Organization Website: 
https://nisz.hu/en/
as indicated by
https://www.domain.hu/special-names/

Reason for PSL Inclusion
====

I'm concerned by the browser behavior, mainly regarding Cookie Security and password auto-fill, as browsers incorrectly treat unrelated agencies with very different security profiles as a single entity.

As of now, the non-profit agency "Hungary Helps" WordPress site (hungaryhelps.gov.hu) is treated as having the same domain as the national id login system (kau.gov.hu), as well as the government healtcare system (ogyei.gov.hu) storing all healthcare data of Hungarian citizens, all sharing the domain with a tiny forest maintenance company (anp.nemzetipark.gov.hu) 

As .gov.hu domains are registerable by a wide range of organizations, I personally think they clearly belong to the public domains list.

Number of users this request is being made to serve:

This change is expected to impact all citizens and residents in Hungary.

DNS Verification via dig
=======

I can't provide DNS verification as I'm not affiliated with NISZ Zrt or the government.

Results of Syntax Checker (`make test`)
=========

```
...
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
...
============================================================================
Testsuite summary for libpsl 0.21.2
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by simon-friedberger** [comment]
I agree with you that it should be fixed but a request would have to be made from the actual domain owners.

@dnsguru How have we handled such cases in the past?

**Comment by dnsguru** [comment]
> @dnsguru How have we handled such cases in the past?

All requests require DNS TXT records added by the respective zone which is the URL of the pull request.  SOMETIMES, where the request is coming from the TLD administrator directly, we'll use the chain of proof, following from the iana db to the specific page of for the apex TLD in focus, to the specific policy page for the request.

In the case of gov/mil or other national interest spaces, there's more involvement typically in behind the scenes validation of there being an undestanding of the impact of the change and ensuring that it is intentional.

**Comment by simon-friedberger** [comment]
@herczegzsolt Given that you are Hungarian and speak the language, could you maybe reach out to the actual registrars and suggest to them that they should request addition?

**Comment by herczegzsolt** [comment]
I've sent them the following letter (in Hungarian) to both their public e-mail and their domain registrar administrative contact.

`Tisztelt NISZ Zrt!

Mint a [gov.hu](http://gov.hu/) különleges domain regisztrátorához fordulok Önökhöz.

Tekintettel a [gov.hu](http://gov.hu/) domain különleges státuszára, szeretném javasolni
hogy az kerüljön fel a Public Suffix List-re.

A legtöbb modern szoftver - ide értve a böngészőket is - a public
suffix list alapján dönti el, hogy milyen aldomaineket kell
"különállóként" kezelni. Jelenleg ezen a listán nem szerepel a [gov.hu](http://gov.hu/)
végződés, vagyis a [gov.hu](http://gov.hu/) aldomainjei között a legtöbb esetben nem
állnak fent olyan biztonsági korlátozások, mint két általános célú
weboldal között. Jelenleg, ha bármely hivatalos szerv oldala
kompromittálódik, az közvetett módon így érintheti az összes többi
[gov.hu](http://gov.hu/) alatt üzemelő szolgáltatást, köztük a különösen érzékeny
központi azonosítási ügynököt is.

A public suffix listről bővebben:
https://publicsuffix.org/
A javaslat miszerint a [gov.hu](http://gov.hu/) kerüljön fel a listára:
https://github.com/publicsuffix/list/pull/1885

Üdvözlettel:
Herczeg Zsolt`

We'll see if I get a reply, or any follow-up from official representatives here.

**Comment by dnsguru** [comment]
Thank you @herczegzsolt 

We want tlds to request these directly - hopefully tied to a _psl txt record in zone to further demonstrate some technical participant was involved - in order to ensure the affectation of cookies, certificates, dmarc etc and those changes are deliberate and intentional.

**Comment by simon-friedberger** [comment]
Closing as there is no action we can take at the moment.

**Comment by bra-fsn** [comment]
I've also contacted them.

**Comment by herczegzsolt** [comment]
I've never received any sort of reply.

I'd assume this should be more feasible now, that as the government sites are slowly migrating to the standard OAuth implementation, but I have zero confirmation.

**Comment by herczegzsolt** [comment]
I've never received any meaningful reply. (They did acknowledge receiving the mail.)

I'd assume this is more feasible now, as the government sites are slowly migrating to the standard OAuth implementation, but I have zero confirmation.

**Comment by ttyS4** [comment]
I am in contact with the HU cctld and they are willing to make a statement that gov.hu is special name (or a 2nd level domain for the government). How can they make such a request?

**Comment by simon-friedberger** [comment]
Thank you! They should just add a pull request here and a matching _psl DNS record.

**Comment by ttyS4** [comment]
@simon-friedberger If I understand correctly _psl.gov.hu TXT record need to be added.
Unfortunately the cctld itself cannot do this as they have delegated that zone to the government.
(Meaning it is not a special zone that the government manages at the cctld, but it is directly under the control of the government.)
If this is the only way then the only possibility is to pursue the zone operator for gov.hu.

**Comment by simon-friedberger** [comment]
Yes, talking to the zone operator is the right thing to do. We should not be turning a domain into an SLD without people running services there knowing about it! And contacting the zone operator at least makes it likely that this information reaches the right people.

Adding a domain to the PSL generally improves security but it does also lead to breakage. There might be a system "taxes.gov.hu" which uses "auth.gov.hu" to log people in and if "gov.hu" gets added to the PSL they are no longer same-site and if they communicated using cookies, the authentication flow would break.

**Comment by ttyS4** [comment]
Thank you @simon-friedberger this is useful information.

**Pull request closed without merging**
