### PR TITLE
Tabitorder.co.il

### PR DESCRIPTION
**Pull request by orenagiv**
* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====
Organization Website: https://tabit.cloud/

Tabit is a restaurant ordering system as well as a point-of-sale that streamlines restaurant operations and extends sales opportunities.
Our 360 degree integrated ecosystem connects every aspect of the customer experience: from guest management, customer ordering and kitchen productivity to tableside payment, bringing efficiencies to every interaction point.

Reason for PSL Inclusion
====
This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we seek to resolve the impacts to the best of our ability to do so.  Both Apple and Facebook support Public Suffix List for Private Click Measurement and Aggregated Event Measurement respectively.
- We have reviewed the wiki here outlining the PSL and understand what it is and is not.
- We have reviewed this matter with the team at Facebook, we are now fully aware about the consequences to the change we are requesting as it relates to cookies or other services, and choose to proceed in submitting this PR. We understand that despite reviewing the matter with Facebook, Facebook cannot control which use cases get accepted to the PSL
- We understand that there is not any urgency and should this PR be merged to include our requested change, that there is no control over the timing of this change being updated downstream in browsers, libraries, certificate authorities or other systems or processes that incorporate the PSL.
- We understand that if we later want to back out this change, there is also no guarantee that this will occur in a rapid fashion due to the same lack of control over browser, library, certificate authority, or other system or process changes. 

Our clients (restaurants) are attempting to set up conversion tracking, and therefore inclusion in the public suffix list is required for the cookie security with changes in iOS 14.5 per https://www.facebook.com/business/help/331612538028890?id=428636648170202

Our restaurants online ordering websites are sub-domains in https://*.tabitorder.co.il/

DNS Verification via dig
====
```
dig +short TXT _psl.tabitorder.co.il
"https://github.com/publicsuffix/list/pull/1385"
```

make test
====
Tests have been executed successfully.

### CODE REVIEW

**Comment by dnsguru** [comment]
It appears that you did not read #1245

**Comment by bedfordsean** [comment]
Hi @orenagiv,

The process has moved on since last we spoke on your previous PR. Please follow these steps:

Facebook encourages anyone requesting addition to the PSL as it relates to Facebook and iOS 14 interactions to make a request directly to Facebook via the form linked from our Help Center Article: https://www.facebook.com/business/help/126789292407737

In the form, given that you have already raised a pull request here, please include a link to this pull request in the description.

We have agreed to do this to reduce the burden on PSL maintainers, ensure that you are asking to be on the PSL for the right reasons, and to allow us to collate and understand the issues that businesses are facing as part of this shift.

After Facebook has assessed one of these requests we will make a recommendation or no recommendation decision, the PSL maintainers will make the final determination and we will coordinate with them on next steps accordingly.

**Comment by dnsguru** [comment]
Retry of #1317

**Comment by orenagiv** [comment]
Hey,
We haven't yet received a confirmation from Facebook. 
Just one question, which we answered, and then nothing...

Hope there is a way to speed them up... But we are stuck right now.

**Comment by bedfordsean** [comment]
Thanks @orenagiv please can you confirm the ID you got from Facebook here and I will chase for you?

**Comment by orenagiv** [comment]
Hi @bedfordsean 
We got a response from Facebook, approving us to proceed with this pool request.
I've updated the pull-request description per their request, the following paragraph:

> This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we seek to resolve the impacts to the best of our ability to do so.  Both Apple and Facebook support Public Suffix List for Private Click Measurement and Aggregated Event Measurement respectively.
                ○ We have reviewed the wiki here outlining the PSL and understand what it is and is not.
                ○ We have reviewed this matter with the team at Facebook, we are now fully aware about the consequences to the change we are requesting as it relates to cookies or other services, and choose to proceed in submitting this PR. We understand that despite reviewing the matter with Facebook, Facebook cannot control which use cases get accepted to the PSL
                ○ We understand that there is not any urgency and should this PR be merged to include our requested change, that there is no control over the timing of this change being updated downstream in browsers, libraries, certificate authorities or other systems or processes that incorporate the PSL.
                ○ We understand that if we later want to back out this change, there is also no guarantee that this will occur in a rapid fashion due to the same lack of control over browser, library, certificate authority, or other system or process changes.

**Review by dnsguru — CHANGES_REQUESTED** [review]
Please re-base and re-order the location based upon the Alphabetic sorting of your org to those within the private section as per prior guidance.

**Comment by orenagiv** [comment]
Hey @dnsguru 
Tabitorder.co.il has been re-positioned per alphabetical order.

**Comment by bedfordsean** [comment]
Confirming from the FB perspective that we made the recommendation to proceed

**Review by dnsguru — APPROVED** [review]
- DNS Validation ok
- Tests ok
- Rationale ok
- No conflict with base
- Formatted / Sorted per Guidelines

**Approved**

**Comment by dnsguru** [comment]
Approved and Merging.  Thank you for patience Oren, let us TEST to see if this process worked, but I want to be clear that this approval does not pave a freeway for others to inappropriately workaround rate limits via the PSL.

**Comment by orenagiv** [comment]
Thanks @dnsguru 

Just to clarify - not sure I follow what you meant by:
> ...but I want to be clear that this approval does not pave a freeway for others to inappropriately workaround rate limits via the PSL

Did we do anything wrong?

**Comment by bedfordsean** [comment]
> Did we do anything wrong?

No, but we don't want the PSL to become a means to work around browser limitations put in place with the intent of increasing user privacy. The reason we have been more careful in allowing you to proceed is to validate that indeed there is no other straightforward way for you to continue to operate as a business and serve your clients without a PSL addition.

@dnsguru please add any other context you feel is missing above!

**Comment by orenagiv** [comment]
Thanks for the clarification @bedfordsean 
And we perfectly understand that.

Thanks again for all your help.

**Comment by dnsguru** [comment]
you nailed it @bedfordsean 

@orenagiv what affected your service was a power struggle for privacy / marketing surveillance between two billion+ dollar tech companies  - your project was collateral damage.  And the thing that kind of restores it ends up being the PSL which was not meant to be used for that purpose.  For a number of reasons, but basically my objective is that by letting your PR through it does  not become seen as the liferaft for others, as the PSL is not supposed to be used this way and we'd lose the voluntary use by browsers, cert issuers etc if seen to be allowing people or orgs to work around rate limits.

**Pull request merged**
