### PR TITLE
Add ip-ddns.com and ddns-ip.net

### PR DESCRIPTION
**Pull request by boyanpeychev**
# Public Suffix List (PSL) Submission

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (`make test`)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the `_psl` TXT record in place in the respective zone(s).

__Submitter affirms the following:__ 

 * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
 - [Cloudflare](https://developers.cloudflare.com/learning-paths/get-started/add-domain-to-cf/add-site/)
 - [Let's Encrypt](https://letsencrypt.org/docs/rate-limits/)
 - MAKE SURE UPDATE THE FOLLOWING LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY AS WELL AS REMOVING THIS LINE!

 * [x] This request was _not_ submitted with the objective of working around other third-party limits.

 * [x] The submitter acknowledges that it is their responsibility to maintain the domains within their section. This includes removing names which are no longer used, retaining the _psl DNS entry, and responding to e-mails to the supplied address. Failure to maintain entries may result in removal of individual entries or the entire section.

 * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms to them.
 * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting.

**Abuse Contact:** 

* [x] Abuse contact information (email or web form) is available and easily accessible.

  URL where abuse contact or abuse reporting form can be found: abuse@cloudns.net or https://www.cloudns.net/contact/
  

---

For PRIVATE section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*. I could break my organization's website cookies and cause other issues, and the rollback timing is acceptable. *Proceed anyways*.
---

## Description of Organization

ClouDNS is a dns hosting company providing dynamic dns for free.
We provide dyndns subdomain ip-ddns.com and ddns-ip.net to our users, allowing them to self-host some services without the need of buying an own domain and with the advantage to bypass some ISPs dynamic IP and to configure DNS entries automatically.

It could be very useful, if browser could correctly manage those subdomains (cookies, highlighting the subdomain, sorting by subdomain and not all the domain ). We want these services to be recognized as a known public suffix and dyndns services too.

**Organization Website:**

https://www.cloudns.net

## Reason for PSL Inclusion

Each user receive 1 sub-domain for free. The reason for PSL inclusion is to isolate the cookie scope of subdomains.

**Number of users this request is being made to serve:** up to 30000

## DNS Verification

```
$ dig _psl.ip-ddns.com txt +short
"https://github.com/publicsuffix/list/pull/2234"
$ dig _psl.ddns-ip.net txt +short
"https://github.com/publicsuffix/list/pull/2234"
```

## Results of Syntax Checker (`make test`)

5 PASS , no errors

### CODE REVIEW

**Comment by groundcat** [comment]
- [ ]  Expiration (Note: Must STAY >2y at all times)
  - [ ]  `ip-ddns.com` expires 2025-10-24
  - [x]  `ddns-ip.net` expires 2027-10-24
- [x]  DNS _psl entries (Note: Must STAY in place)
  - [x] `_psl.ip-ddns.com` points to `"https://github.com/publicsuffix/list/pull/2234"`
  - [x] `_psl.ddns-ip.net` points to `"https://github.com/publicsuffix/list/pull/2234"`
- [x]  Tests pass
- [x]  Sorting
- [x]  Reasoning/Organization description
  - Similar to [#2202](https://github.com/publicsuffix/list/pull/2202)
- [x]  Non-personal email address
- [x]  Abuse contact

**Comment by groundcat** [comment]
@boyanpeychev Please extend the registration of `ip-ddns.com` to ensure an expiration date more than two years from today. This two-year buffer needs to be maintained continuously in future years to keep the domains in the PSL.

**Comment by boyanpeychev** [comment]
> @boyanpeychev Please extend the registration of `ip-ddns.com` to ensure an expiration date more than two years from today. This two-year buffer needs to be maintained continuously in future years to keep the domains in the PSL.

Hi! Yes, I know for this requirement, but  because of mistake by one of our team members this domain name was registered only for 1 year, instead of 3, and now domain registry has an lock for 55 days from today for any modifications, including renewals :(

**Comment by groundcat** [comment]
@boyanpeychev Thank you for the explanation! It seems that a WHOIS check for `ip-ddns.com` currently shows only the `clientTransferProhibited` lock. According to [ICANN's description of this status](https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en#clientTransferProhibited), it should not prevent renewal. I am not entirely sure, but gTLDs might have [a 5-day grace period](https://www.icann.org/resources/pages/gtld-lifecycle-2012-02-25-en) after registration where certain operations are restricted, but after that, it might be fine. Could you reconfirm with the registrar if this is correct?

**Comment by boyanpeychev** [comment]
> @boyanpeychev Thank you for the explanation! It seems that a WHOIS check for `ip-ddns.com` currently shows only the `clientTransferProhibited` lock. According to [ICANN's description of this status](https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en#clientTransferProhibited), it should not prevent renewal. I am not entirely sure, but gTLDs might have [a 5-day grace period](https://www.icann.org/resources/pages/gtld-lifecycle-2012-02-25-en) after registration where certain operations are restricted, but after that, it might be fine to renew. Could you reconfirm with the registrar if this is correct?

There is 60 day lock for transfer and renewals from the moment of the registration with the registrar we are using. If that's critical for you, we can wait more 55 days and I will comment again here once the renewal is done.

**Comment by wdhdev** [comment]
It shouldn't be too much of a problem, just ensure you renew it when you can. @groundcat

**Pull request merged**
