### PR TITLE
Remove wildcard id.forgerock.io

### PR DESCRIPTION
**Pull request by roderickparr**
* [ ] Description of Organization
* [ ] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

### CODE REVIEW

**Comment by dnsguru** [comment]
@roderickparr  rationale for removal is necessary Please provide this to proceed

  Did you break something trying to solve something with #1252 ?  

Request / rollback burns through the time of the volunteers, so the rollbacks get deprioritized, but also be aware of the following once this rollback PR might get merged: [Guidelines: Expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion)

#1238 #1245 
#1251 and rolls back #1252

**Comment by roderickparr** [comment]
> Guidelines: Expectations
@dnsguru the wildcard is causing issues configuring redirect URLs in Google

**Comment by dnsguru** [comment]
> > @dnsguru the wildcard is causing issues configuring redirect URLs in Google

Chrome Browser, Cloud Hosting, Search Engine, Paid Advertising?  Can you mention what precisely is the service where there is an issue and what it is?  There are eyes on these PR dialogs so it may help you or others to elevate awareness/details

**Comment by netyaroze** [comment]
Hello @dnsguru 

This is for Google Oauth, which you are probably more than aware requires a TLD for security purposes. 

To give you an idea of the reasons behind the reversion, our customer tenancies all live on the structure: `$customer.id.forgerock.io`. So with that said, the wildcard being added erroneously has some not-so-ideal consequences for our tenants, e.g Google reporting that said domain is not a TLD. 

We are aware, however, prepared for most of the fallout. 

Cheers
J

**Review by dnsguru — APPROVED** [review]
Change Submitter = Initial Submitter
No Conflict with Base
Tests ok
DNS Verified
Name >2y

Approved

**Comment by dnsguru** [comment]
Fortunately, the 60 day hold concept has not yet formed concensus, so this change is approved and can move forward

**Comment by dnsguru** [comment]
@netyaroze @roderickparr MERGED.  Good luck, and appreciate your awareness of our lack of control as to propogation timing downline from us

**Pull request merged**
