### PR TITLE
include fastly.net subdomain for related services

### PR DESCRIPTION
**Pull request by mabrown-corp**

### CODE REVIEW

**Comment by weppos** [comment]
@mabrown-corp do you work for Fastly?

**Comment by mabrown-corp** [comment]
Greetings, yes, I do.

I have also created the appropriate TXT record has been created in accordance with PSL expectations (which we learned under an earlier addition to the PSL, https://github.com/publicsuffix/list/pull/371).

Thank you,

-Martin

**Comment by miyagawa** [comment]
The TXT record has been added:

```
> dig +short TXT _psl.freetls.fastly.net
"https://github.com/publicsuffix/list/pull/424"
```

(I also work for Fastly)

**Comment by weppos** [comment]
@mabrown-corp can you please sort the entry according to the guidelines in https://github.com/publicsuffix/list/wiki/Guidelines?

I think that should actually be the first item, according to the right-to-left sorting.

**Comment by mabrown-corp** [comment]
Greetingss @weppos; thank you -- I believe that I have now sorted the names according to alphabetical by label, from right to left.  Applying that sort to our names caused the `fastlylb.net` names to move up, as well.

-Martin

**Pull request merged**
