### PR TITLE
Add `aliases121.com`

### PR DESCRIPTION
**Pull request by graafcom**
Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowlegements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

GCom Internet is a web and email hosting provider.

We provide each hosting client with a unique subdomain of aliases121.com.

I am a Network and Software Engineer on the GCom Internet team.

Organization Website: https://www.gcom.net.au

Reason for PSL Inclusion
====

We provide each hosting client with a unique subdomain of aliases121.com.

We need our customers' applications to be isolated from each other with respect to cookies etc.

Number of users this request is being made to serve:  Currently 5K+ with growth expected.

DNS Verification via dig
=======

```
dig +short TXT _psl.aliases121.com
"https://github.com/publicsuffix/list/pull/1614"
```

Results of Syntax Checker (`make test`)
=========

All tests passed.

### CODE REVIEW

**Comment by simon-friedberger** [comment]
Can you please add current and predicted user numbers?

**Review by simon-friedberger — APPROVED** [review]
* [x] aliases121.com expires 2026-06-12
* [x] aliases121.com has DNS entry for PR 1614
* [x] Tests pass
* [x] Sorting according to guidelines
* [x] Reasoning/Organization description

**Comment by graafcom** [comment]
G'day Simon,

Thanks very much for your time and action on this request.

I noticed a question was added and then removed regarding numbers. We're currently running around 7.2K subdomains under aliases121.com for hosted users. However, we'll allow that grow more freely once aliases121.com is listed in the PSL.

Thanks again for your and your associates' voluntary work on this project.

**Review by dnsguru — APPROVED** [review]
https://github.com/publicsuffix/list/pull/1614#event-11652147795

**Pull request merged**
